### ISSUE TITLE
Facilitate proper handling of background `NSURLSession`

### ISSUE THREAD

**Issue by robertmryan** [AFNetworking/AFNetworking#1776]
In iOS, when using a background `NSURLSession`, one should, as the [Handling iOS Background Activity](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/UsingNSURLSession.html#//apple_ref/doc/uid/TP40013509-SW26) section of the _URL Loading System Programming Guide_ says:

> If you are using NSURLSession in iOS, your app is automatically relaunched when a download completes. Your app’s application:handleEventsForBackgroundURLSession:completionHandler: app delegate method is responsible for recreating the appropriate session, storing a completion handler, and calling that handler when the session calls your session delegate’s URLSessionDidFinishEventsForBackgroundURLSession: method.

I'd suggest:
1. Add a `copy` property in `AFURLSessionManager` to hold the completion handler block provided by `handleEventsForBackgroundURLSession`.
2. Update the documentation to remind users to set this property from `handleEventsForBackgroundURLSession` if doing background `NSURLSession`.
3. In the `URLSessionDidFinishEventsForBackgroundURLSession` delegate method of `AFURLSessionManager`, call this completion handler block when the downloads are done.

This would make it a little easier for iOS developers to ensure that they're correctly handling background sessions properly.

If you'd like me to do a pull request for this, I'd be happy to. Let me know.

**Comment by SlaunchaMan** [comment]
Closing this as this is a super-old discussion. If anyone has a good idea for properly dealing with true background sessions in AFNetworking—where the app is relaunched when the download completes—that would be an appropriate improvement for AFNetworking 4.
