### ISSUE TITLE
AFSSLPinningModePublicKey incompatibility between 2.0.x and 2.1.0/2.2.0

### ISSUE THREAD

**Issue by bensie** [AFNetworking/AFNetworking#1852]
On 2.0.3, I am able to set the security policy to `AFSecurityPolicy.policyWithPinningMode: AFSSLPinningModePublicKey` without issues -- public key is a .cer in the bundle.

Starting with 2.1.0 and also in 2.2.0, this no longer works.

So far the only way I've been able to get it to work is by setting both `validatesDomainName` and `validatesCertificateChain` to `NO`.

Is this expected or was there a regression? Is there any debug setting I can enable to provide more info?

**Comment by petalvlad** [comment]
Any updates on this issue (wildcard)?

**Comment by pjjw** [comment]
hey, the current implementation makes a smooth transition to SHA2-chained certs impossible. like reedloden stated above, pinning to the end-entity cert (and more generally, forcing one specific cert chain) only serves to make things brittle. in order to allow current releases to function when we switch to a sha2-signed cert, we need to allow certs that are signed (in our specific case) either by the digicert high assurance CA-3 cert or the digicert SHA2 high assurance server CA cert. failure to accept both means best case, versions would have to point to different ssl termination endpoints, which is extremely overcomplicated.

**Comment by simonmcl** [comment]
Any update on this? seeing quite a few crashlytic logs related to AFNetworking in our apps. Would love to upgrade to newer versions but I'm completely blocked moving past 2.0.3 until this is resolved or has a work around

**Comment by mathpirate** [comment]
A quick +1, we're also being bitten by this one.

**Comment by hdoria** [comment]
+1 for this.

**Comment by esetnik** [comment]
+1 we are facing the same issue and stuck on 2.0.3. We are trying to use AFSSLPinningModePublicKey in conjunction with pinning to root CA only instead of EE/leaf.

**Comment by kcharwood** [comment]
Just circling back on this and trying to parse out the problem.

If I am reading @reedloden's [comments](https://github.com/AFNetworking/AFNetworking/issues/1852#issuecomment-36199389) correctly, it looks like there is some specific implementation details that we could use Chromium as some inspiration. I can take a look through of those docs.

Would anyone like to take a first stab at implementation? I'd be happy to review and collaborate with you on this.

**Comment by reedloden** [comment]
@kcharwood, I'm not an iOS dev (just a security engineer), but I am happy to answer any questions you or anybody implementing this has about best practices around TLS pinning.

**Comment by kcharwood** [comment]
@reedloden I'd love your thoughts on #2744

**Comment by kcharwood** [comment]
Also, after fully digging into `AFSecurityPolicy`, I now have my head wrapped on this issue and the questions it raises. We'll be making some changes there to make this more straightforward, and will be creating a security guide as well

If you have specific use cases you would like to see supported, please drop them in #2744

**Comment by kcharwood** [comment]
Please reference #2856 going forward.

**Comment by donaldking** [comment]
Havinig similar issue with RestKit 2 which uses AFNetworking - `AFRKSSLPinningModePublicKey` `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: allowedCertificate'`. Anyone got a fix for this yet?
