### ISSUE TITLE
-[AFURLConnectionOperation outputStream] leaking memory

### ISSUE THREAD

**Issue by fulldecent** [AFNetworking/AFNetworking#2306]
My program is freezing based on a memory leak of `-[AFURLConnectionOperation outputStream] leaking memory`. If I leave the program run, entry points it my code are not touched and AFNetworking continues to consume gigabytes. 

Here is data showing what is happening. I am using the Pod release AFNetworking (2.4.1).

![screen shot 2014-09-16 at 6 22 10 pm](https://cloud.githubusercontent.com/assets/382183/4296027/b3940e2c-3df0-11e4-8a3f-5e4845094562.png)
![screen shot 2014-09-16 at 6 22 15 pm](https://cloud.githubusercontent.com/assets/382183/4296028/b6039466-3df0-11e4-81b8-49b25a0b5908.png)
![screen shot 2014-09-16 at 6 22 19 pm](https://cloud.githubusercontent.com/assets/382183/4296030/b874387c-3df0-11e4-912c-339145477319.png)
![screen shot 2014-09-16 at 6 25 48 pm](https://cloud.githubusercontent.com/assets/382183/4296031/baaed2b4-3df0-11e4-9213-1b061ba9f091.png)

**Comment by igorkulagin** [comment]
I was using
`operation.outputStream = [NSOutputStream outputStreamToFileAtPath: path append: NO];`
in AFNetwrorking 2.3 and everything was ok.

However after updating to 2.5 I found that if file **already exists** then this code doesn't work: operation hangs and doesn't call **success** or **failure** block.

So I added following code and it solved the problem:
`operation.outputStream = [NSOutputStream outputStreamToFileAtPath: path append: NO];
[operation.outputStream open];
[operation start]`

Probably these issues are connected.

**Comment by kcharwood** [comment]
Now that 2.6.2, we are going to be shifting our focus to the 3.0.0 stream, which removes support for `NSURLConnection`.

 We are planning on only addressing critical security and stability issues in the 2.x branch going forward. If this becomes a widespread problem, it will be addressed.

:beers:
