### ISSUE TITLE
AFSSLPinningModePublicKey behavior when validatesCertificateChain = NO

### ISSUE THREAD

**Issue by niranjanr** [AFNetworking/AFNetworking#2333]
In AFSecurityPolicy.m, we have the following cases for SSL pinning:

1. AFSSLPinningModeCertificate & validatesCertificateChain = YES
    - The entire certificate chain is checked and the certificates in the chain must exactly match ones that the app is pinned to and when that happens, validation passes.
2. AFSSLPinningModeCertificate & validatesCertificateChain = NO
    - If ANY certificate in the certificate chain matches the one that the app is pinned against, trust validation passes.
3. AFSSLPinningModePublicKey & validatesCertificateChain = YES
    - The entire set of public keys is validated for trust validation to pass
4. AFSSLPinningModePublicKey & validatesCertificateChain = NO [This is the case that is a problem]
    - Only the first key in the chain is picked and the public keys that we pin against are checked for validation to pass.

In point 4, it should be ok to pin against the public key of a root CA and hence have the public keys of any certificate in the chain match the public key that the app pins against for trust validation to pass. 

Is there a specific reason why this is not the case? I would be happy to submit a pull request based on this.

**Comment by jbelkins** [comment]
Agreed.  Submitted #2656 which addresses this case.

**Comment by kcharwood** [comment]
@niranjanr I'm digging in here and spotting the same problems. Thanks for calling these out.

I've opened up #2744 for discussion on what should be the proper expected behavior for pinning, and calling for community feedback there. Would love each of your opinions and use cases there.

I'll close this to consolidate, and we can move forward there.

**Comment by niranjanr** [comment]
Thanks @kcharwood. Will do.
