### ISSUE TITLE
AFNetworking 2.5.0 (#2411) breaks AFNetworkActivityIndicatorManager on iOS 7

### ISSUE THREAD

**Issue by tangphillip** [AFNetworking/AFNetworking#2458]
My [swizzle-fix](https://github.com/AFNetworking/AFNetworking/pull/2411) for #1477 broke `AFNetworkActivityIndicatorManager` on iOS 7.
_Reported by @erikjalevik_ [here](https://github.com/AFNetworking/AFNetworking/issues/1477#issuecomment-63974854)_._

The swizzle was intended to replace KVO-watching the `NSURLSessionTask`s' `state` by producing `NSNotification`s whenever `-resume` or `-suspend` was called on any `NSURLSessionTask`.

On iOS 8, this approach works. On iOS 7, however, the public subclasses of `NSURLSessionTask` do not actually derive from a class called `NSURLSessionTask `. Instead, they derive from a class called `__NSCFLocalSessionTask`. Swizzling its `-resume` and `-suspend` methods works, and solves the issue.

But...as the name suggests, it's a private class. We can't go about calling `NSClassFromString("__NSCFLocalSessionTask")`. But could we swizzle `[taskInstance superclass]`? I'm not sure.

Code here: https://github.com/AFNetworking/AFNetworking/pull/2459

**Comment by amarcadet** [comment]
Hi, any news on this?

**Comment by mattt** [comment]
Fixed by #2477.
