### ISSUE TITLE
Upload Task for a Multi-Part Request: timeout and no network traffic is ios8 swift

### ISSUE THREAD

**Issue by andyryan** [AFNetworking/AFNetworking#2497]
trying to upload a file to a server using the Upload Tast for a Multi-Part Request method in the ReadMe.

Always gives -1001 error "The Request Timed out"
No network traffic occurring in debugger
no error messages in attaching file to form data or setting up request and manager
![screen shot 2015-01-05 at 03 31 30](https://cloud.githubusercontent.com/assets/5088093/5608988/6703487e-948b-11e4-82dc-ae0cc268f008.png)

(spike in disk in above image is the file being read for attachment to form)

```swift
let urlString: NSString = NSString(format: "%@%@", base_url, "/negotiations")
        var error : NSError?
        var request = AFJSONRequestSerializer().multipartFormRequestWithMethod("POST", URLString: urlString, parameters: params, constructingBodyWithBlock: { (formData:AFMultipartFormData!) -> Void in
            if formData.appendPartWithFileURL(self.imageURL, name: "negotiation[image]", fileName: "image.jpeg", mimeType: "image/jpeg", error: nil){
                NSLog("File added to form data")
            } else {
                NSLog("Error adding file to form Data: %@", error!.localizedDescription)
            }
        }, error: &error)
        
        var manager : AFURLSessionManager = AFURLSessionManager(sessionConfiguration: NSURLSessionConfiguration.defaultSessionConfiguration())
        var progress : NSProgress?
        
        var uploadTask : NSURLSessionUploadTask = manager.uploadTaskWithStreamedRequest(request, progress: &progress, completionHandler: { (response:NSURLResponse!, responseObject:AnyObject!, error: NSError!) -> Void in
            if error == nil{
                NSLog("Proposal submitted with response: %@", response.description)
            } else {
                NSLog("Failed to submit proposal with error: %@", error.localizedDescription)
            }
        })
uploadTask.resume()

```
I know this has been brushed off as a coding error on the users part in the past, but I notice a lot of people having issues with iOS 8 and file upload

**Comment by andyryan** [comment]
Updated to latest version. This appeared to fix issue. Now getting 404, even though url exists, but different error so closing issue

**Comment by 1Reinier** [comment]
I have this exact issue, using the current AFNetworking version. Using a packet sniffer I found out that the POST request is never actually sent.

**Comment by 1Reinier** [comment]
Did you find a solution eventually?

**Comment by BruhhGarcia** [comment]
I have this issue too. I'm using AFNetwork 3.0 and iOS 9.2
