### ISSUE TITLE
Memory usage appears to grow unbounded w/ repeated GET from AFHTTPRequestOperationManager

### ISSUE THREAD

**Issue by texel** [AFNetworking/AFNetworking#2499]
I have an app that uses AFNetworking 1.3.4, and makes frequent calls to a local http service on a timer. If I leave my app running for a few days, it ends up consuming 2GB+ of memory, though Instruments doesn't seem to tell me where it's being used. I've confirmed that this issue also occurs in the latest version of AFNetworking, and I've prepared a reduced test case:

https://github.com/texel/AFHTTPClientLeakTest/tree/afn2

It's pretty simple- it just repeatedly makes a failing request to localhost. I've also attempted to defeat the default shared `NSURLCache`. Here's an example memory graph from Xcode:

![memory](http://texel-monosnap.s3.amazonaws.com/AFHTTPClientLeakTest.xcodeproj_2015-01-05_17-03-27.png)

I'm fully open to the possibility that I'm doing something drastically wrong, but any investigation I've done so far doesn't seem to explain the memory usage reported by the OS. Slowing down the timer only seems to lessen the slope of the curve, it doesn't appear to level off or go back the other way.

Thanks so much for taking a look at this!

**Comment by mattt** [comment]
> I have an app that uses AFNetworking 1.3.4.

AFNetworking 1.3.4 is no longer supported.

As far as attempting to reproduce this with AFNetworking 2.x, I was unable to do so:

![screen shot 2015-01-09 at 11 41 17](https://cloud.githubusercontent.com/assets/7659/5686027/75e7f364-97f4-11e4-9525-f88bafb5697f.png)

Allocations were flat over several minutes, and the single spike in leaks do not appear to be significant or related to AFNetworking.

The only thing I might recommend is to ensure that your timer is not somehow creating a retain cycle or otherwise causing objects to go unreleased.

**Comment by texel** [comment]
Hey @mattt thanks for taking a look! So part of the problem here is that instruments will tell you that the allocations are flat, but if you look in activity monitor or in the memory mini-instrument in Xcode, you'll see the process memory growing unbounded. It's super weird. Are you seeing the same thing on your end?

**Comment by mattt** [comment]
>  If you look in activity monitor or in the memory mini-instrument in Xcode, you'll see the process memory growing unbounded.

That probably says more about the Xcode mini-instruments than anything else. I wouldn't rely on those for an accurate measure of allocations. Instruments (proper) should be considered the canonical source of truth as far as that goes.

**Comment by mattt** [comment]
If you believe that this is indeed an issue with Xcode mini-instruments, I would encourage you to file a Radar with Apple describing this problem.

**Comment by texel** [comment]
Ok fair enough, but Activity Monitor agrees w/ the mini-instruments. If this test app runs for a couple of days, the memory usage reported by the system is >9GB. Seems a bit concerning...
