### ISSUE TITLE
AFImageWithDataAtScale double free issue

### ISSUE THREAD

**Issue by safecase123** [AFNetworking/AFNetworking#2501]
I am using like this  

[imgView setImageWithURL:[NSURL URLWithString:strImageURL]];

![screen shot 2015-01-06 at 3 07 50 am](https://cloud.githubusercontent.com/assets/1125736/5625985/d8dc938e-9552-11e4-9561-11a3435111f2.png)

**Comment by mattt** [comment]
I cannot reproduce. Please open a new issue with a small reproducible example.

**Comment by himuleo** [comment]
Same happend here

**Comment by alexmalek** [comment]
I also repro - trying hard to narrow down

**Comment by jiashuw** [comment]
Same here.

**Comment by CraigMason** [comment]
Also seeing this issue in the simulator in certain scenarios.

![image](https://cloud.githubusercontent.com/assets/307066/6401060/6650d214-bdf5-11e4-9ebe-50252b682572.png)

**Comment by sydneyitguy** [comment]
+1
happens randomly (5-10% chances)

**Comment by runeb** [comment]
Also seeing this intermittently

**Comment by TomCarton** [comment]
Same on my side ;(

**Comment by paulosotu** [comment]
Hi guys I thimk I was able t fix this please refer to my comment on https://github.com/AFNetworking/AFNetworking/issues/2572
