### ISSUE TITLE
reachableViaWiFi property of reachabilityManager is incorrect when used in application:didReceiveRemoteNotification:fetchCompletionHandler:

### ISSUE THREAD

**Issue by chung2014** [AFNetworking/AFNetworking#2504]
steps to reproduce:
1. After I turn on WiFi on device, I call startMonitoring method on reachabilityManager when the app is in foreground. (after this step, if I check somewhere in the code, I get reachabilityManager.reachableViaWiFi is YES. This is correct!)
2. I press Home button to make the app into background.
3. I turn off the WiFi on device.
3. My app then receives push notification and application:didReceiveRemoteNotification:fetchCompletionHandler: is called. (If i check reachabilityManager.reachableViaWiFi at the beginning of application:didReceiveRemoteNotification:fetchCompletionHandler:, I get YES. This is incorrect! It should be NO!)

**Comment by mattt** [comment]
That's not how `AFNetworkReachabilityManager` works. The calls necessary to determine reachability execute asynchronously, and may not be available immediately.
