### ISSUE TITLE
AFNetworking (com.apple.root.default-qos.overcommit)

### ISSUE THREAD

**Issue by oNguyenTaCuong** [AFNetworking/AFNetworking#2512]
I running my app on iPhone 6 Plus. But i have an issue with AFNetworking as log below.

Thread : AFNetworking (com.apple.root.default-qos.overcommit)
0  libsystem_kernel.dylib         0x33f824f0 mach_msg_trap + 20
1  libsystem_kernel.dylib         0x33f822e9 mach_msg + 40
2  CoreFoundation                 0x260fa31b __CFRunLoopServiceMachPort + 146
3  CoreFoundation                 0x260f88c1 __CFRunLoopRun + 1016
4  CoreFoundation                 0x260463c1 CFRunLoopRunSpecific + 476
5  CoreFoundation                 0x260461d3 CFRunLoopRunInMode + 106
6  Foundation                     0x26d7fbfd -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 264
7  Foundation                     0x26dce0bd -[NSRunLoop(NSRunLoop) run] + 80
8  MyApp                    0x002e8eab +[AFURLConnectionOperation networkRequestThreadEntryPoint:] (AFURLConnectionOperation.m:189)
9  Foundation                     0x26e44b5b __NSThread__main__ + 1118
10 libsystem_pthread.dylib        0x34012e93 _pthread_body + 138
11 libsystem_pthread.dylib        0x34012e07 _pthread_start + 118

Any suggestions how I can determine the cause?

Thanks.

**Comment by mattt** [comment]
Unfortunately, this is not a useful stack trace, and does not demonstrate any specific problem with AFNetworking. If you continue to have problems, please post a small, reproducible example and full crash log.
