### ISSUE TITLE
AFHTTPRequestOperationManager doesn't send Authorization HTTP header

### ISSUE THREAD

**Issue by iwheelbuy** [AFNetworking/AFNetworking#2518]
I want to use `AFHTTPRequestOperationManager` in my project. Each request should contain an authorization header. Otherwise server reports an error.

Well, I create an `AFHTTPRequestOperationManager`:

    - (void) setManager:(AFHTTPRequestOperationManager *)manager
    {
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            _manager = [AFHTTPRequestOperationManager manager];
            _manager.responseSerializer.acceptableContentTypes = [NSSet setWithObjects:@"text/plain", nil];
            _manager.operationQueue.maxConcurrentOperationCount = 1;
            [_manager.requestSerializer setValue:@"XsziXjva92jAO29jng0wpBmKFJ92s9q" forHTTPHeaderField:@"Authorization"];
        });
    }

And send a request with the help of the manager:

    + (void) requestBoards
    {
        // show me my manager headers
        DLog(@"%@", [[[[RequestManager instance] manager] requestSerializer] HTTPRequestHeaders]);
        [[[RequestManager instance] manager] GET:URL_BOARDS parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {
            DLog(@"good");
        } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
            // show me request headers
            DLog(@"%@", operation.request.allHTTPHeaderFields);
        }];
    }

Each `DLog` shows:

    [RequestManager requestBoards]_block_invoke_2 [Line 66] {
        "Accept-Language" = "en;q=1";
        Authorization = XsziXjva92jAO29jng0wpBmKFJ92s9q;
        "User-Agent" = "SITE/1.0 (iPhone Simulator; iOS 8.1; Scale/2.00)";
    }

And the server response is no good:

    {"data": {}, "error_text": "Key None is unauthorized, sorry :/", "success": false, "error": "unauthorized_key"}

I decided to check my request with Wireshark and there is no **Authorization** header at all. What am I doing wrong?

Added:

Only **Authorization** header isn't send by `AFHTTPRequestOperationManager`. I have changed header title to **AuthorizationLOL** and is was sent successfully

**Comment by iwheelbuy** [comment]
I have found a very strange solution...

That was my url: http://www.some_site.ru/api/board
And it doesn't work

This is the new url: http://www.some_site.ru/api/board/
And it works

**Comment by mattt** [comment]
This is expected behavior. Unless you use the authentication challenge API, you are culpable to losing headers on redirect.

**Comment by RedBlueThing** [comment]
Hi @mattt, 

Would you be able to direct me to the documentation for the "Authentication Challenge API"? I have had a hunt around in the documentation and am not sure what you are referring to. (I am losing Authentication headers on a redirect and would like to understand why).

Cheers.

**Comment by pollito05** [comment]
Why I can't see this movi???
