### ISSUE TITLE
Authentication block callbacks don't facilitate asynchronous handling

### ISSUE THREAD

**Issue by danielpunkass** [AFNetworking/AFNetworking#2520]
I am enjoying getting to know AFNetworking 2 and have generally been satisfied by most of the default decisions and behaviors of the library. The exceptions have all been easy to override and I can see your reasoning for defaulting to them.

One area that hung me up is in the way AFNetworking handles authentication challenges from NSURLSession, passing them along to the client asynchronously via registered callback blocks such as the "taskDidReceiveAuthenticationChallenge" block.

I saw in the discussion around issue #1335 that there was some surprise that NSURLSession's own delegate method uses an asynchronous callback block. The reasoning as far as I can understand it (and owing to the way I intend to use it) is that authentication could be delayed by the need to interact with the user e.g. to present a password prompt or other authentication flow. For this reason, the NSURLSession system seems designed to put a request on ice while the client obtains authorization from the user.

I think I could achieve what I need by taking advantage of the fact that the callback is on a non-main thread, blocking the thread while a prompt is displayed, and then returning the result synchronously to AFNetworking. But this seems a little shaky to me and also seems to be in defiance of the NSURLSession delegate expectation that the delegate should return promptly and call the callback when the credentials are ready. I don't know if the system puts the thread into any more useful of a sleeping state than I would waiting for my main thread UI to complete, but it does seem possible that it could have an effect on e.g. timeout timers or other machinery within NSURLSession.

I'm working around this by subclassing AFHTTPSessionManager and implementing my own delegate method for the authorization challenge, but I thought I would file an issue to get your take on it and get you thinking about whether it would be a good idea to facilitate NSURLSession's expected asynchronous callback mechanism in the longer term.

**Comment by kcharwood** [comment]
Thanks for the write up here @danielpunkass, and I apologize for this sitting for so long with no interaction. I haven't seen anyone else talking about this feature, so its just been on the backburner.

I think your logic and reasoning does make sense. I'd love to see your implementation and see how it may fit back into AFNetworking. I'll do some thinking here as well.

:beers:

**Comment by 0xced** [comment]
I noticed the same issue while working on #3425. I’ll try to propose a solution that doesn’t require to subclass `AFURLSessionManager`.

**Comment by danielpunkass** [comment]
@kcharwood Somehow I glossed over your response in December. Maybe I can blame GitHub notifications somehow ;) Anyway @0xced's follow-up got my attention. As it turns out I ended up not using AFNetworking, so I'm not really invested in this. I'm glad to hear that @0xced has some motivation to work on it, though!
