### ISSUE TITLE
What are the differences of UIImageView's categories?

### ISSUE THREAD

**Issue by qingqinghebiancao** [AFNetworking/AFNetworking#2530]
When I want to use  UIImageView's methods to download images from remote server, I can't decide which method to use? So can anybody tell me what are the differences of `setImageWithURL:` and `setImageWithURL:placeholderImage:` and  `setImageWithURLRequest:placeholderImage:success:failure`? %>_<%

**Comment by tomasikp** [comment]
This should be placed on stackoverflow.  `setImageWithURL:` will set the image after the image is finished downloading.  `setImageWithURL:placeholderImage:` will first set the image to the placeholder and then set the image after it is finished downloading.  and the last one allows you to do some sort of image processing before setting the image yourself in the success block.

**Comment by mattt** [comment]
Thanks, @tomasikp.

**Comment by qingqinghebiancao** [comment]
O(∩_∩)O~Um, I see. Thanks,@tomasikp and @mattt .
