### ISSUE TITLE
[AFNetworkReachabilityManager managerForDomain:] works incorrectly

### ISSUE THREAD

**Issue by willingheart** [AFNetworking/AFNetworking#2532]
In my application I check Internet connection.

If I use
    [[AFNetworkReachabilityManager sharedManager] startMonitoring];
    [[AFNetworkReachabilityManager sharedManager] setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {
}];
that's OK: status changes correctly, if internet sets down or up.

If I use 
    self.internetManager = [AFNetworkReachabilityManager managerForDomain:@"www.google.com"];
    [self.internetManager setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {
}];
    [self.internetManager startMonitoring];
when application starts, status is correct (reachable), but after internet sets down and up, status is always AFNetworkReachabilityStatusNotReachable.

Please, see a function [AFNetworkReachabilityManager managerForDomain:].

**Comment by mattt** [comment]
This method behaves according to the underlying SystemConfiguration framework's `SCNetworkReachabilityCreateWithName` function. If it's not working as expected, you should use the `sharedManager` instead, or just disregard reachability entirely. Network reachability is a diagnostic tool that can be used to understand why a request might have failed. It should not be used to determine whether or not to make a request.
