### ISSUE TITLE
UIImageView+AFNetworking does not support webp?

### ISSUE THREAD

**Issue by Wangxiaotao** [AFNetworking/AFNetworking#2539]
I found that AFImageResponseSerializer does not support webp, the code below show that it can not accept content type @"image/webp".

```
@implementation AFImageResponseSerializer

- (instancetype)init {
    self = [super init];
    if (!self) {
        return nil;
    }

    self.acceptableContentTypes = [[NSSet alloc] initWithObjects:@"image/tiff", @"image/jpeg", @"image/gif", @"image/png", @"image/ico", @"image/x-icon", @"image/bmp", @"image/x-bmp", @"image/x-xbitmap", @"image/x-win-bitmap", nil];

#if defined(__IPHONE_OS_VERSION_MIN_REQUIRED)
    self.imageScale = [[UIScreen mainScreen] scale];
    self.automaticallyInflatesResponseImage = YES;
#endif

    return self;
}
```

I add @"image/webp" to self.acceptableContentTypes array, and it works!

but i do not want to modify the source code, can you support that?

**Comment by mattt** [comment]
UIImage does not support WebP out of the box, so it is not reasonable to assume that the image response serializer should not accept the `image/webp` content type.

If, for some reason, you've patched UIImage to allow this to work (or more likely, your server is sending the wrong MIME type for another supported image format), you can set the `acceptableContentTypes` property directly onto your response serializer. There is no need to patch the original code.

**Comment by Wangxiaotao** [comment]
ok, thanks.
