### ISSUE TITLE
AFNetworkActivityIndicatorManager does not work on iOS 7

### ISSUE THREAD

**Issue by tomassliz** [AFNetworking/AFNetworking#2541]
Activity indicator does not work on iOS 7, in iOS 8 works properly. This issue can be reproduced in iOS 7 simulator too.

**Comment by mattt** [comment]
Fixed by #2477.

**Comment by tomassliz** [comment]
I tried this fix, but it doesn't work for me.

**Comment by mattt** [comment]
Apologies, I meant #2459.
