### ISSUE TITLE
Clone AFHTTPRequestOperation

### ISSUE THREAD

**Issue by pablog** [AFNetworking/AFNetworking#2543]
I'm working on a module that works based on AFNetworking 2.0 that will be used to enqueue the operations that failed in case it was due to a lack of internet connection (using AFNetworkReachability).

My idea is checking the reachability when a request fails and if it's not reachable, I enqueue the operation to be resumed / started when reachable again.

The issue is that I know that if the operation is finished, I cannot resume neither start it again, so I'd like to know if I there's a way to "clone" or create a new operation based on it, maintaining its URL, parameters, body, etc, but setting its state to Ready.

I think it'd be very useful.

**Comment by pablog** [comment]
I've found a possible workaround for my problem here:

https://github.com/AFNetworking/AFNetworking/issues/596

Which is creating a new instance of AFHTTPRequestOperation by using the method copy, and assigning again the success/failure blocks.

**Comment by mattt** [comment]
Request operations conform to `NSCopying`. Beyond that, there is no prescribed approach for reappropriating completion blocks.
