### ISSUE TITLE
Unable to compile on swift with iOS7

### ISSUE THREAD

**Issue by stephenyao** [AFNetworking/AFNetworking#2544]
Have installed AFNetworking as a Pod in a swift project. Everything works fine if I set deployment target to 8.0 but however if I change deployment target to 7.1 I get the following error:

ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/AFNetworking.framework/AFNetworking) for architecture arm64

**Comment by mattt** [comment]
As per the README, embedded frameworks are not supported on iOS 7.

**Comment by mattt** [comment]
iOS 7 does not support embedded frameworks. For additional support, you should look to CocoaPods resources.
