### ISSUE TITLE
Makes any unit test crash

### ISSUE THREAD

**Issue by jcayzac** [AFNetworking/AFNetworking#2547]
In my unit tests, I mock a REST API using `NSURLProtocol`, then call my Objective-C API, which relies on AFNetworking.

However, AFNetworking uses this pattern pretty much everywhere:

```objc
NSString *errorMessage = [NSString stringWithFormat:NSLocalizedStringFromTable(@"Could not decode string: %@", @"AFNetworking", nil), @"string"];
```

Under XCTest, `+[NSBundle mainBundle]` returns `nil`. This causes `NSLocalizedStringFromTable()` to return `nil` as well, which makes `+[NSString stringWithFormat:]` raise an `NSInvalidArgumentException` every time it is invoked.

**Comment by mattt** [comment]
I cannot reproduce this. Unit tests in personal applications and AFNetworking itself have always worked consistently with `NSLocalizedString` and its variants.

For your particular case, you may need to set the Host Application of your test target, or stub `NSBundle`.
