### ISSUE TITLE
NSURLSessionDownloadTask does not release memory when finished

### ISSUE THREAD

**Issue by zhw511006** [AFNetworking/AFNetworking#2548]
I make a simple demo about this, one start button for downloading a pdf file.

1)NSURLConnection

[NSURLConnection sendAsynchronousRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensibilityPG.pdf"]]
                                       queue:[NSOperationQueue mainQueue]
                           completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
                               if (connectionError == nil) {
                                   NSLog(@"success");
                               }
                               else {
                                   NSLog(@"failure");
                               }
                           }];

![screen shot 2015-02-05 at 11 29 12 am](https://cloud.githubusercontent.com/assets/2869093/6054611/9e79acbe-ad2a-11e4-9e60-50a991e7dda6.png)

2) NSURLSessionDownloadTask

AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];
    
    NSURLSessionDownloadTask *downloadTask = [manager downloadTaskWithRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensibilityPG.pdf"]]
                                                                     progress:nil
                                                                  destination:nil
                                                            completionHandler:^(NSURLResponse *response, NSURL *filePath, NSError *error) {
                                                               
                                                        
                                                                if (error == nil) {
                                                                    NSLog(@"success");
                                                                }
                                                                else {
                                                                    NSLog(@"failure");
                                                                }

                                                            }];
    
    [downloadTask resume];

![screen shot 2015-02-05 at 11 30 10 am](https://cloud.githubusercontent.com/assets/2869093/6054631/e0d0f590-ad2a-11e4-825c-3519032dc4e0.png)

I do this on iPhone6, iOS8+, may I make some mistakes? When using download task, the memory keep growing，but URLConnection don't like this.

Thanks for your help!

**Comment by zhw511006** [comment]
I have tested this in iOS7.1, and the result is better, the memory is growing, but no fast as iOS8+.

**Comment by zhw511006** [comment]
Nobody met this problem? or I make a mistake?

**Comment by mattt** [comment]
I see nothing particularly problematic about this. Memory allocations do not imply leaks, and allocations are consistent with the underlying caching and URL Loading System infrastructure. Xcode's memory monitors are not a replacement for Instruments.app, either, so do not rely on them for a definitive diagnosis of any problems.

**Comment by zhw511006** [comment]
I seached this: 
https://stackoverflow.com/questions/27300415/nsurlsession-downloadtask-not-releasing-memory
