### ISSUE TITLE
Why isn't AFSecurityPolicy validatesDomainName enabled default?  

### ISSUE THREAD

**Issue by jmkk** [AFNetworking/AFNetworking#2549]
AFSecurityPolicy's "validatesDomainName" is set to NO by default, and only when using policy created from +policyWithPinningMode: does this flag get enabled.

What is the reason for this flag to default to NO? It appears that all SSL/TLS traffic should evaluate DN by default, and only for cases explicitly specified by the dev should it be changed to NO. It should be treated similar to the "validatesCertificateChain" flag.

Note that there are places where it's not possible to enforce enabling "validatesDomainName", like request operations created inside of UIImageView+AFNetworking and UIButton+AFNetworking. These requests will never follow the security policy set on the HTTP client/request manager.

**Comment by mattt** [comment]
The default security policy is `AFSSLPinningModeNone`, and having `validatesDomainName` set to `NO` is consistent with this. If you require security evaluation for remotely loading images, do not use the built-in UIKit categories.

**Comment by jmkk** [comment]
@mattt thanks for the response. However, AFSSLPinningModeNone for SSLPinningMode is a setting for certificate pinning. I'm not talking about certificate pinning, but regular SSL/TLS trust evaluation. 

Not validating the name in the SSL certificate against the hostname during SSL traffic is considered to be an extremely bad practice, exposing all AFNetworking clients to a potential Main in the Middle attack.

As is, AFNetworking is altering the security policy setting, which directly violates Apple's API guidelines:

> Do not disable hostname checking by creating a non-TLS policy or passing in a NULL pointer for the  hostname. If you are intentionally connecting to a host using a hostname other than one of the names listed on its certificate, you should allow the operation only if the certificate you receive from that host is valid for some other domain that you control.

(https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NetworkingTopics/Articles/OverridingSSLChainValidationCorrectly.html)

Also note that due to TLS Session Cache that takes place in SecureTransport layer (https://developer.apple.com/library/ios/qa/qa1727/_index.html), if the AFNetworking client hosts images on the same server (IP+name+port) as their other content that needs to be protected, if the first request is to fetch an image (without validating the name), the remaining calls could suffer from MITM attack for the next 10 minutes as the same (not fully protected) SSL session would be reused by iOS. 

Given the above, I strongly encourage AFNetworking to follow the established security standards and default to the more secure settings, and allow the users to opt-out as needed for testing/debugging.
