### ISSUE TITLE
AFURLSessionManagerTaskDelegate crash.

### ISSUE THREAD

**Issue by oday0311** [AFNetworking/AFNetworking#2551]
Crashed: com.alamofire.networking.session.manager.processing
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x0000000000000008

[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke69 (AFURLSessionManager.m:193)

0  libdispatch.dylib              0x0000000195f39d40 dispatch_group_async + 80
1  libdispatch.dylib              0x0000000195f39d3c dispatch_group_async + 76
2  Pinnacle                       0x000000010020dff4 __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke69 (AFURLSessionManager.m:193)
3  libdispatch.dylib              0x0000000195f353ac _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x0000000195f3536c _dispatch_client_callout + 16
5  libdispatch.dylib              0x0000000195f3df90 _dispatch_async_redirect_invoke + 692
6  libdispatch.dylib              0x0000000195f3536c _dispatch_client_callout + 16
7  libdispatch.dylib              0x0000000195f4140c _dispatch_root_queue_drain + 1152
8  libdispatch.dylib              0x0000000195f4275c _dispatch_worker_thread3 + 108
9  libsystem_pthread.dylib        0x00000001961112e4 _pthread_wqthread + 816

**Comment by mattt** [comment]
Isolated backtraces without the context of a full crash log and application code context is not particularly useful by itself. If you can provide an example that reliably reproduces the issue in question, please open a new issue.
