### ISSUE TITLE
2.5.0 compiles in Xcode 5, but 2.5.1 does not.

### ISSUE THREAD

**Issue by dtartaglia** [AFNetworking/AFNetworking#2555]
I can understand why support  for Xcode 5 would end at some point, but I was surprised that it ended in a minor version number change. Was this a mistake? (Compile error in AFURLConnectionOperation.h line 219.)

**Comment by tewha** [comment]
Possibly relevant link: http://stackoverflow.com/questions/24119896/ns-designated-initializer-expected-colon

**Comment by dtartaglia** [comment]
Yes, this is the issue. Yes, I can work around it. And yes, you are right.

**Comment by mattt** [comment]
Fixed by #2559
