### ISSUE TITLE
Never ending activity indicator

### ISSUE THREAD

**Issue by pjebs** [AFNetworking/AFNetworking#2556]
I don't think this is related to #2476

I have subclassed a AFHTTPSessionManager and have 2 methods inside that perform a [self POST...] eg  A and B for example.
A performs a POST request as does B.

When you nest the methods, so that A calls B from within its success block, then the AFNetworkActivityIndicatorManager registers 2 increments but at the very end of A and B,  only decrements once, hence a never ending activity indicator.

**Comment by mattt** [comment]
Looking through the delegate and notification logic, I cannot find a reason why the situation you described would result in imbalanced activity indicator increments / decrements.

If you can create a small, reproducible example that demonstrates this behavior, please open a new issue with it attached.
