### ISSUE TITLE
Memory crashes in App while handling large JSON response

### ISSUE THREAD

**Issue by yasirmturk** [AFNetworking/AFNetworking#2558]
this a test run with ~8 MB gzipped response and inflated to ~60 MB `NSData` size...

1. `NSData` is converted to `NSString`, App memory goes to ~200 MB
2. `NSString` is converted back to `NSData`, App memory goes to ~260 MB
3. `NSData` is converted to JSON, App memory rises over ~300 MB and boom memory crash

![2015-02-12_1008](https://cloud.githubusercontent.com/assets/306691/6162260/a0340dfc-b2a1-11e4-833a-87f62fc066ae.png)
![2015-02-12_1009](https://cloud.githubusercontent.com/assets/306691/6162261/a32ff566-b2a1-11e4-89a0-3aee0e336d5e.png)
![2015-02-12_1010](https://cloud.githubusercontent.com/assets/306691/6162263/a6683d6a-b2a1-11e4-9b06-910cdba86c28.png)

**Comment by yasirmturk** [comment]
any update on this one ...may be if user is able to specify to skip string encoding check to optimize memory usage???

**Comment by mattt** [comment]
`AFJSONResponseSerializer` is just the built-in way of handling JSON. If your requirements are different, you may prefer to roll your own response serializer that reads from an input stream or does not do the same checks.

Unfortunately, I don't see anything really to be done about the Foundation framework's handling of large JSON data. I would be happy to review and PR that attempts to improve this, however.
