### ISSUE TITLE
when using " dispatch_async " timeout fail, only iPhone4 and iOS 7

### ISSUE THREAD

**Issue by saintevil** [AFNetworking/AFNetworking#2561]
// when using    " dispatch_async "    timeout fail
	// only iPhone4 and iOS 7
	// how to using both   " dispatch_async " and " AFHTTPRequestOperation "  ?

	AFHTTPRequestOperation *operation = [manager_ HTTPRequestOperationWithRequest:request success:^(AFHTTPRequestOperation *operation, id responseObject) {
		// It's OK
	} failure:^(AFHTTPRequestOperation *operation, NSError *error) {
	}];

	dispatch_queue_t dQueue = dispatch_queue_create("appStart",NULL);
	dispatch_async(dQueue, ^{
		AFHTTPRequestOperation *operation = [manager_ HTTPRequestOperationWithRequest:request success:^(AFHTTPRequestOperation *operation, id responseObject) {
		} failure:^(AFHTTPRequestOperation *operation, NSError *error) {
			// when using    " dispatch_async "    timeout fail
		}];
	});

**Comment by Ramalus** [comment]
What was the issue here? Were you able to solve it?
