### ISSUE TITLE
Failed to get correct response object if responseData contains some specific value

### ISSUE THREAD

**Issue by lmnbeyond** [AFNetworking/AFNetworking#2565]
Hi,
  This issue is a little strange, you can reproduce it by running the following code:

        id responseObject = nil;
        NSString *responseString = @"[{\"area\":76.32}]";
        NSError *serializationError = nil;
        NSData *data = [responseString dataUsingEncoding:NSUTF8StringEncoding];
        responseObject = [NSJSONSerialization JSONObjectWithData:data options:0 error:&serializationError];

BTW:
The above code is extracted from AFURLResponseSerialization::- (id)responseObjectForResponse:(NSURLResponse *)response
                           data:(NSData *)data
                          error:(NSError *__autoreleasing *)error

Expected result:
Printing description of **responseObject**:
<__NSCFArray 0x7fd94ca0ae90>(
{
    area = "76.32";
}
)

Actual result:
Printing description of **responseObject**:
<__NSCFArray 0x7fd94ca0ae90>(
{
    area = "76.31999999999999";
}
)

In fact, I'm not sure this is a bug, but I really want to finger out why this is happening!

**Comment by mattt** [comment]
That's just how floating point numbers work. [This article is a good primer](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html).
