### ISSUE TITLE
Adding "nullability" annotations?

### ISSUE THREAD

**Issue by dapenggao** [AFNetworking/AFNetworking#2566]
The new Clang compiler allows Objective-C code to have "nullability annotations." Should we add them into the project so that it can interact with Swift code better?

**Comment by franklsf95** [comment]
+1 would love to see this.

**Comment by kcharwood** [comment]
I'd be happy to review this if anyone wants to take a stab at the initial implementation.

**Comment by franklsf95** [comment]
I would love to work on this. Progress at https://github.com/franklsf95/AFNetworking.

**Comment by kcharwood** [comment]
Sounds great. Feel free to create a PR when its ready for review!
