### ISSUE TITLE
Future certs being treated as valid in 2.5.1

### ISSUE THREAD

**Issue by AaronSofaer** [AFNetworking/AFNetworking#2573]
Setup: Roll back your system clock to a paste date such that the cert for an API you're using is invalid, because it's not valid until some future date. I used 1960, for consistency.
Devices tested on include various iOS 8 and iOS 7 iPads, both in simulation and on physical hardware.

With AFNetworking 2.5.0 installed, the validation will fail.
With AFNetworking 2.5.1 installed, the validation will succeed, despite future certs technically not being valid.

I looked through the changelog and commit log, and didn't find anything about this.

**Comment by infimache** [comment]
The problem is not related to date, but to validation of certificates in general in v2.5.1, see issue <link>https://github.com/AFNetworking/AFNetworking/issues/2560</link>

**Comment by AaronSofaer** [comment]
Noted; thank you.
