### ISSUE TITLE
AFNetworking crash

### ISSUE THREAD

**Issue by VeeraSrinivasan** [AFNetworking/AFNetworking#2575]
Is this fixed in AFnetworking 2.5.1?

Device: iPad 3,1
iOS 8.1.2 (12B440)
AFNetworking version: 2.3.1

Stacktrace (from Crittercism)
0	
libsystem_platform.dylib 0x30070218 _platform_memmove$VARIANT$CortexA9 + 176
1	
Foundation 0x22acea85 _NSDataCreateVMDispatchData + 98
2	
Foundation 0x22a9e0f5 -[_NSPlaceholderData initWithBytes:length:copy:deallocator:] + 218
3	
Foundation 0x22a9e00f -[NSData(NSData) initWithBytes:length:copy:freeWhenDone:bytesAreVM:] + 76
4	
Foundation 0x22aaba0f -[NSData(NSData) copyWithZone:] + 116
5	
Foundation 0x22b14811 +[NSData(NSData) dataWithData:] + 162
6	
Apartments 0x0019d4f3 -[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:] (AFURLSessionManager.m:150)
7	
Apartments 0x001a0ec9 -[AFURLSessionManager URLSession:task:didCompleteWithError:] (AFURLSessionManager.m:845)
8	
Apartments 0x00291081 -[CRNSURLSessionDelegateProxy URLSession:task:didCompleteWithError:] + 110
9	
CFNetwork 0x2196adb3 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke227 + 56
10	
Foundation 0x22b440fd __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 6
11	
Foundation 0x22aaefc5 -[NSBlockOperation main] + 146
12	
Foundation 0x22aa1845 -[__NSOperationInternal _start:] + 766
13	
Foundation 0x22b46a57 __NSOQSchedule_f + 184
14	
libdispatch.dylib 0x2feff5d9 _dispatch_queue_drain$VARIANT$mp + 946
15	
libdispatch.dylib 0x2feff0a9 _dispatch_queue_invoke$VARIANT$mp + 82
16	
libdispatch.dylib 0x2ff010d3 _dispatch_root_queue_drain + 328
17	
libdispatch.dylib 0x2ff021fb _dispatch_worker_thread3 + 104
18	
libsystem_pthread.dylib 0x30072e25 _pthread_wqthread + 666
19	
libsystem_pthread.dylib 0x30072b78 start_wqthread + 6

**Comment by mattt** [comment]
A stack trace without context is not particularly useful. If you can reproduce this behavior, please open a new issue with an example project.
