### ISSUE TITLE
Wrong Method Called In Test

### ISSUE THREAD

**Issue by kolpanic** [AFNetworking/AFNetworking#2576]
In `AFURLSessionManagerTests`'s `-testUploadTasksProgressBecomesPartOfCurrentProgress` [method](
https://github.com/AFNetworking/AFNetworking/blob/master/Tests/Tests/AFURLSessionManagerTests.m#L46), a download method is called instead of an upload method. I'm not sure which of `AFURLSessionManager`'s `-uploadTaskWithRequest:` methods is appropriate, though.

**Comment by mattt** [comment]
Fixed by ee182bb. Thanks, @kolpanic.
