### ISSUE TITLE
AFHTTPRequestSerializer returns request with incorrect timeoutInterval

### ISSUE THREAD

**Issue by micahhainline** [AFNetworking/AFNetworking#2582]
AFHTTPRequestSerializer.requestWithMethod:URLString:parameters:error: returns an NSMutableURLRequest with the default timeoutInterval set, instead of respecting the timeoutInterval that was set on the serializer.

**Comment by danielgomezrico** [comment]
+1 Same for me

**Comment by mattt** [comment]
Duplicate of #2563.

**Comment by danielgomezrico** [comment]
is it a duplicate? 

I'm not subclassing AFHTTPRequestOperationManager and it happens too.

**Comment by mattt** [comment]
Yes, it's the same underlying cause.

**Comment by danielgomezrico** [comment]
Ok, I didn't said anything ;)
