### ISSUE TITLE
Request specific response serializer using AFHTTPSessionManager API

### ISSUE THREAD

**Issue by rdoddi** [AFNetworking/AFNetworking#2588]
Old AFNetworking AFHTTPRequestOperation has request instance specific response serializer - this is very convenient while parsing different types of payloads (e.g. one from /photos another from photos/123).

Using newer version of AFHTTPSessionManager this is not possible. We can only set global serializer or compound serializer but not request specific serializer.

Is there a plan to accommodate this in near future.

**Comment by mattt** [comment]
> Using newer version of AFHTTPSessionManager this is not possible.

This is not the case.

https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFHTTPRequestOperation.h#L45

**Comment by rdoddi** [comment]
Matt, thanks a lot for quick look on the ticket. You're awesome.

I see that version 2 has AFHTTPRequestOperation with request specific serializer. But as per the documentation, it is recommended to use  AFHTTPSessionManager, which does not have the same convenience as AFHTTPRequestOperation.
