### ISSUE TITLE
AFNetworking won't build in a WatchKit Extension

### ISSUE THREAD

**Issue by wlisac** [AFNetworking/AFNetworking#2595]
AFNetworking references a couple unavailable methods when included in a WatchKit Extension.

`AFNetworkActivityIndicatorManager.m` references `[UIApplication sharedApplication]`.

`UIAlertView+AFNetworking.m` references `UIAlertView`'s `initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:`

These should probably be wrapped in `#ifndef AF_APP_EXTENSIONS`.

**Comment by mattt** [comment]
Fixed by #2589.

**Comment by wlisac** [comment]
Thanks, Mattt.
