### ISSUE TITLE
Memory Leak in AFHTTPRequestOperationManager

### ISSUE THREAD

**Issue by CaptainStiggz** [AFNetworking/AFNetworking#2596]
I ran some tests trying to isolate a strange memory leak, and found AFHTTPRequestOperationManager to be the (most likely) offender. Here are the tests, as well as the results. In the second screenshot, the memory step-up you'll find at ~50s recurs every ~20s in perpetuity. Gun to my head, I'd hazard a guess that AFHTTPRequestOperation in the success/failure blocks might have something to do with it, but I really have no idea, as I haven't dug too deeply into the AFNetworking nuts and bolts.

```objective-c
//app delegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    NSURL *url = [NSURL URLWithString:@"http://myserver/path"];
    self.session = [[AFHTTPSessionManager alloc] initWithBaseURL:url];
    self.manager = [AFHTTPRequestOperationManager manager];
    [self syncNotifications];
    return YES;
}

//this works (AFHTTPSessionManager)
- (void)syncNotifications {
    NSString *path = @"http://myserver/path/action";
    NSLog(@"GET: %@", path);

    [self.session GET:@"/action" parameters:nil success:^(NSURLSessionDataTask *task, id responseObject) {
        NSLog(@"success");
    } failure:^(NSURLSessionDataTask *task, NSError *error) {
        NSLog(@"failure");
    }];

    [self performSelector:@selector(syncNotifications) withObject:nil afterDelay:1];
}

//this leaks memory (AFHTTPRequestOperationManager)
- (void)syncNotifications {
    NSString *path = @"http://myserver/path/action";
    NSLog(@"GET: %@", path);

    [self.manager GET:path parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {
        NSLog(@"success");
    } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        NSLog(@"failure");
    }];

    [self performSelector:@selector(syncNotifications) withObject:nil afterDelay:1];
}
```

![test 1 - afhttpsessionmanager](https://cloud.githubusercontent.com/assets/704532/6647767/3cf7f492-c98f-11e4-9827-5ad04af95125.png)
![test 2 - afhttprequestoperationmanager](https://cloud.githubusercontent.com/assets/704532/6647768/3cf8e532-c98f-11e4-9777-77c057ccba93.png)

**Comment by CaptainStiggz** [comment]
An interesting note: a large chunk of persistent memory seems to be gobbled by VM: Performance Tool Data. I'm not sure what this is, and might be the actual culprit. Furthermore, if I run the AFHTTPSessionManager (no leak) test for a long period of time, I see the Performance Tool Data memory climb at the rate of ~10MB/hour. This might indicate that the memory "leak" is related to the frequency of networking calls: possibly some sort of buildup if the responses are returned slower than they are requested.

**Comment by mattt** [comment]
I don't see any leaks, just a plateau and periodic tick in net allocations. This is not unexpected, given differences in the underlying URL Loading Systems—could be in-memory caching, connection pooling, or any number of things. 

Unless there are allocations that can be traced back to something AFNetworking is  specifically doing, unfortunately, this isn't really actionable information...

**Comment by sandychales** [comment]
I think that problem is caused by this method as Apple API says。
