### ISSUE TITLE
AFURLSessionManager's downloadTaskWithRequest: overwrite file issue

### ISSUE THREAD

**Issue by OmarPedraza** [AFNetworking/AFNetworking#2604]
Hi there,
First of all, thanks @mattt for this awesome framework, I don't know how to live without it right now.

I've been moving a really "vintage" app from NSURLConnection to AFNetworking, and I've chosen the AFURLSessionManager methods.

There were no problems moving all the data tasks, but I found a really annoying issue when downloading files. Once debugged, I saw that old code created the new file before being downloaded so downloadTaskWithRequest: completion was no able to move the downloaded item to that path.

Here's the question: what's the desirable behavior? Maybe remove the existing file and overwrite it with the new content? Or finishing the download as failed instead of just posting a notification? If a behavior is defined, I'll create a pull request for it.

Sorry if this issue has been treated before, but I didn't find anything about it.

Thanks again, best regards!

**Comment by mattt** [comment]
It's the user's responsibility to ensure that the file URL returned from the `destination` block does not already exist. You could either generate a guaranteed unique URL and move to the existing file path in the completion handler, or simply remove the URL in that block.
