### ISSUE TITLE
timeoutInterval is not considered in the requests

### ISSUE THREAD

**Issue by bennibau** [AFNetworking/AFNetworking#2608]
I am using AFNetworking (2.5.1). I am setting the timeoutInterval to 10s when I create the requests in my own classes. This timeout interval is not considered in the request, it is set back to 60s. In the version of AFNetworking I used before this was working perfectly. Is it intended to work like that in the new version?
I added the code to the AFURLRequestSerialization class now by myself but I am not too happy with that.

**Comment by mattt** [comment]
This was a bug introduced by a patch for #2523. This commit has been reverted by df51854. A new release is forthcoming.
