### ISSUE TITLE
AFNetworking ios demo memory leaks 

### ISSUE THREAD

**Issue by dev-xdyang** [AFNetworking/AFNetworking#2617]
when run AFNetworking ios demo with instruments, I find some memory leaks!

![0f476520-1e1e-415a-a134-91e2063295e7](https://cloud.githubusercontent.com/assets/7471748/6861808/95c49326-d477-11e4-8664-7138c1635755.png)
![4c728b5a-b00f-4944-be45-1f25be6caa9b](https://cloud.githubusercontent.com/assets/7471748/6861812/a3cc1336-d477-11e4-8ea5-7966913384a4.png)
![a9192d17-f1ee-4271-adf6-363a5c8e0597](https://cloud.githubusercontent.com/assets/7471748/6861822/d6b19758-d477-11e4-9cb8-7c944db30e44.png)
![8445c2eb-17e5-4985-9800-cdd351c17b5a](https://cloud.githubusercontent.com/assets/7471748/6861824/e12d541a-d477-11e4-8d27-13dc78ccdab9.png)

**Comment by mattt** [comment]
Fixed by a13a244526e4110739872904c860edd645accdd1, 7a4797e186a45bd3efcf8e7dd28ef754e87ee741, and 346d3498dbb93349049fe82904d89c960c665c34. Thanks, @dev-xdyang!
