### ISSUE TITLE
Reachability gives different results in 2.5.2

### ISSUE THREAD

**Issue by KristopherGBaker** [AFNetworking/AFNetworking#2618]
I just updated to 2.5.2 through pod update.  I noticed AFNetworking's reachability was giving me unexpected results, so I investigated further by downgrading to 2.5.1, where I saw what I normally expect.

To reproduce this issue, create a new Single View Application iOS project (Objective-C) in Xcode (I'm using Xcode 6.2 if that matters).  Setup the project to use AFNetworking 2.5.2.

Modify AppDelegate.m so it looks like below, run the project.  You should see two log statements, one saying "Network Reachable", and the other saying "Network Not Reachable".  The order of these two statements isn't always the same.  

Now setup the project to use AFNetworking 2.5.1 and run the project again.  You should see a single log statement saying "Network Reachable", which is what I would normally expect (unless I have actual network or server issues of course).

```objectivec
#import "AppDelegate.h"
#import "AFNetworkReachabilityManager.h"

@interface AppDelegate ()

@property (strong, nonatomic) AFNetworkReachabilityManager *networkReachabilityManager;

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    self.networkReachabilityManager = [AFNetworkReachabilityManager managerForDomain:@"google.com"];
    
    [self.networkReachabilityManager setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {
        
        switch (status) {
            case AFNetworkReachabilityStatusReachableViaWiFi:
            case AFNetworkReachabilityStatusReachableViaWWAN:
                NSLog(@"Network Reachable");
                break;
                
            case AFNetworkReachabilityStatusNotReachable:
                NSLog(@"Network Not Reachable");
                break;
                
            case AFNetworkReachabilityStatusUnknown:
                NSLog(@"Reachability Status Unknown");
                
            default:
                break;
        }
    }];
    
    [self.networkReachabilityManager startMonitoring];
    
    return YES;
}

- (void)applicationWillResignActive:(UIApplication *)application {
}

- (void)applicationDidEnterBackground:(UIApplication *)application {
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
}

- (void)applicationWillTerminate:(UIApplication *)application {
}

@end
```

**Comment by KristopherGBaker** [comment]
Using AFNetworking 2.5.2, but replacing AFNetworkReachabilityManager.m with the version from 2.5.1 also shows expected behavior (a single log statement saying "Network Reachable").

**Comment by aporat** [comment]
same here. `AFNetworkReachabilityManager` fails to detect network reachability

**Comment by kcharwood** [comment]
I'm guessing 99894d4033d9fb8f8904390c860539366c06e7bd or dccc98dc23599e92c77f9aa1829a7d4429e57764 are the culprits. I'll try and dig in some today.

**Comment by kcharwood** [comment]
Looks to be a race condition on [line 202](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFNetworkReachabilityManager.m#L202) with start monitoring, leading to a double call with not reachable firing second.

**Comment by kcharwood** [comment]
From what I can tell so far, 99894d4033d9fb8f8904390c860539366c06e7bd is the culprit. The old code had a special case to not run the reachability code that includes calling the status block. With that switch case removed, it looks like its causing the block to be called twice, with not reachable being reported last.

**Comment by eviltofu** [comment]
I've experienced this under 8.2 and 7.1. Under both cases, the change block is called twice. Under 8.2, both times I get a "Reachable via Wifi" call. Under 7.1, I get a "Reachable Via Wifi" call followed by a "Not Reachable" call. I repeated this several times with the same results. I hope this helps.

**Comment by faken** [comment]
same problem here with iOS 8.2 down to iOS 7.1 - reachability status is not reliable.

**Comment by jhudsonWA** [comment]
Glad I saw this. I'll hold off on 2.5.2 until this is resolved.

**Comment by taylesworth** [comment]
Yep, we're seeing this too.

**Comment by KingOfBrian** [comment]
Hey folks, I have a PR that fixes my issue if you guys could check it out and give it some votes of confidence that'd be great!

**Comment by nrbrook** [comment]
+1 for this bug, causing me problems too

**Comment by issue2k** [comment]
+1

**Comment by chillpop** [comment]
This appears to only be an issue if you create a reachability manager for a domain.  The `sharedManager` seems to work as before if you need a workaround.

**Comment by skyemccaskey** [comment]
+1

**Comment by mattt** [comment]
Reverted with e92af05.

**Comment by KingOfBrian** [comment]
+1
Less risk all in all, look forward to a release!
