### ISSUE TITLE
AFSSLPinningModeNone vulnerable to man-in-the-middle attacks

### ISSUE THREAD

**Issue by ivanlei** [AFNetworking/AFNetworking#2619]
### AFSSLPinningModeNone vulnerable to man-in-the-middle attacks

[`AFSecurityPolicy.validatesDomainName`](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFSecurityPolicy.h#L62) should default to `YES` in all cases.

At a high level HTTPS is meant to provide both an encryption and authentication. By default, AFNetworking sets `AFSSLPinningModeNone` which as a side effect disables validation of CN name in the server certificate. This disables authentication of the server and leaves sessions vulnerable to man-in-the-middle attacks.

This may be considered a breaking change but would make AFNetworking *secure by default*.

**Comment by mattt** [comment]
I agree. Fixed by 3e631b2.

**Comment by natecode** [comment]
@mattt, as I understand it, this flaw means that an attacker can present *any* valid certificate and the CNAME will not be checked. I could use a Verisign cert for `nate.com` to MITM your connections to `yourbank.com`, as long as they weren't using pinning. However, this commit was not released in 2.5.2 along with the other SSL cert validation fix so developers using 2.5.2 are *not* safe against this yet.

In both cases, apps that are using pinning (either cert or public key) are not vulnerable to either of these flaws. Is this also correct? Thanks.

**Comment by biddster** [comment]
Chaps, does this affect the 1.x series? I ask as I use restkit which uses AFNetworking 1.3.0 (https://github.com/RestKit/RestKit/issues/2207). I've pulled that release code and taken a look, just wanted to confirm.

**Comment by bioche** [comment]
:+1:  biddster. I would also be interested by experts opinion on this. Thanks

**Comment by natecode** [comment]
Some number of versions from 1.2.0 - 1.3.4 are vulnerable, as well as some of the 2.x series. (We tested only 1.3.4 but the code was introduced in 1.2.0). We are continuing to review all these versions to identify which ones are vulnerable but this takes time.

I've created issue #2690 to explain how this flaw works. Hopefully there will be a fix soon.

**Comment by biddster** [comment]
The answer is here https://github.com/AFNetworking/AFNetworking/issues/2690

**Comment by natecode** [comment]
#2690 has been closed, and there is no currently known issue with 1.2.0 - 1.3.4. Apologies for the broken test.

I do think it would be worth mentioning which released versions of the 2.x series (besides 2.5.0 - 2.5.2) are affected by this issue where `AFSecurityPolicy.validatesDomainName` defaults to `NO`.
