### ISSUE TITLE
AFNetworking 2.5.2 crashes on OS X 10.8

### ISSUE THREAD

**Issue by clemensg** [AFNetworking/AFNetworking#2623]
Hi, apps using AFNetworking crash when built with a deployment target of OS X 10.8 on 10.8.

Details:
```
...
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
 Symbol not found: _OBJC_CLASS_$_NSURLSessionDataTask
...
```

Looks similar to: https://github.com/AFNetworking/AFNetworking/pull/2621

Maybe this bug was introduced in commit https://github.com/AFNetworking/AFNetworking/commit/27964aa9dc8b3f5aece2c1528e8135355ee21156 ?

**Comment by clemensg** [comment]
@tangphillip I think it was introduced by your change to the swizzle logic. Can you please fix this so it works again on 10.8 and all newer systems? (iOS 7 and higher respectively)

**Comment by tangphillip** [comment]
Wow, yes, I can do that! I'm an iOS developer, so I tested the fix on both iOS 7 and 8, but completely forgot about OS X. Oops! I'll take a look today.

**Comment by mattt** [comment]
See discussion on #2621.
