### ISSUE TITLE
NSURLSessionDataTask (_AFStateObserving) leaks with version 2.5.2

### ISSUE THREAD

**Issue by molon** [AFNetworking/AFNetworking#2629]
![9778d5af-86bc-460b-84a2-dc9614e83692](https://cloud.githubusercontent.com/assets/3739161/6941920/4de435d2-d8b6-11e4-9321-6dc3657f08f4.png)

**Comment by mattt** [comment]
This is fixed in master. See a13a244526e4110739872904c860edd645accdd1.

**Comment by molon** [comment]
Sorry for trouble you. I would check the newest source file (because of new problem next time)     :)
