### ISSUE TITLE
totalBytesExpectedToRead is -1 when downloading large amounts of data

### ISSUE THREAD

**Issue by shawnirvin** [AFNetworking/AFNetworking#2645]
I implemented the:

[operation setDownloadProgressBlock:^(NSUInteger bytesRead, long long totalBytesRead, long long totalBytesExpectedToRead) {
//Download progress code
}];

block, but noticed that for large-ish downloads, the totalBytesExpectedToRead is -1. I put an NSLog in the block and printed out the bytesRead and the expected, and it was properly called for each progress however, the totalBytesExpectedToRead was -1 the whole time. However, for other downloads, it sets the value properly. Here is an example final log output when the totalBytesExpectedToRead is -1: "6551797 Bytes Read of -1".

**Comment by mattt** [comment]
`-1` means that no `Content-Length` was provided by the server.

For more information, please consult the [Foundation URL Loading System programming guide](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/URLLoadingSystem/URLLoadingSystem.html).
