### ISSUE TITLE
iO6 Support 

### ISSUE THREAD

**Issue by yasargil** [AFNetworking/AFNetworking#2648]
Hi with Version 2.5.2 i am getting following error while running on iOS 6:
dyld: Symbol not found: _OBJC_CLASS_$_NSURLSessionDataTask

I installed AFNetworking via cocoa pods. When reverting back to AFNetworking 2.5.1 the error disappears.

**Comment by TayfunAslan** [comment]
Same error for me, help !!!! ??? !!!!!

**Comment by mattt** [comment]
The NSURLSession subspec requires a minimum target of iOS 7. Use `Alamofire/NSURLConnection` instead.

**Comment by yasargil** [comment]
if i use the  pod 'AFNetworking/NSURLConnection', '~> 2.5' subspec i get a missing symbol error:
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_AFNetworkActivityIndicatorManager", referenced from
