### ISSUE TITLE
SSL Certificate Pinning

### ISSUE THREAD

**Issue by AsceticMonk** [AFNetworking/AFNetworking#2652]
From reading issue #1771, I realized that you need to bundle all the certificates for SSL Pinning to work, and I got my project to work. However, I noticed that for some API, the last certificate in the chain changes periodically. My question is: is there anyway for AFNetworking to just pin the top 2 certificates, instead of the entire chain? Are there any other possible solutions for this scenarios? Thanks!

**Comment by AsceticMonk** [comment]
To answer my own question, I ended up setting validatesCertificateChain to NO and only bundled the root certificate in the app. Let me know if there are other approaches, thanks!

**Comment by mattt** [comment]
@AsceticMonk That's the solution I would recommend.
