### ISSUE TITLE
iOS 6 AFNetworking/UIKit

### ISSUE THREAD

**Issue by yasargil** [AFNetworking/AFNetworking#2657]
With Version 2.5.2 it ist not possible to have to UKit subspec without the the NSURLSession subspec. Breaking backwards compatibility with iOS 6.

**Comment by TayfunAslan** [comment]
Same issue for me, i use pod 'AFNetworking', '~> 2.0' and in my device on iOS 6.1 not working
Please help me

**Comment by mattt** [comment]
See #2638.
