### ISSUE TITLE
AFNetworkActivityIndicatorManager doesn't work for background downloads

### ISSUE THREAD

**Issue by phoney** [AFNetworking/AFNetworking#2660]
I'm using AFHTTPSessionManager and I create it with a background NSURLSessionConfiguration. When I do a GET the networkActivityIndicator doesn't appear in the status bar. In the app I'm working on if I use the identical code but use a default SessionConfiguration the networkActivityIndicator works as expected.

This previously did work. In the past the networkActivityIndicator didn't work at all for iOS 7.x but did work for iOS 8 for default and background downloads. Now default downloads show the networkActivityIndicator on iOS 7.x and 8.x but when using background downloads the networkActivityIndicator doesn't appear on iOS 7.x and 8.x.

I believe the problem lies with the method swizzling code in AFURLSessionManager, which changed recently. I notice that for background downloads when I send resume to the NSURLSessionDownloadTask the af_resume method isn't called, like it is for non-background downloads. Since the AFNetworkActivityIndicatorManager is dependent on the resume method causing a notification to be posted the networkActivityIndicator doesn't appear.

BTW, the first two unit tests in AFNetworkActivityManagerTests.m are faulty. The completion blocks are never executed so the expect() blocks inside the completion blocks are never executed either. Regardless, there is no test for the scenario that I describe. 

Sorry that I don't have a simple test case to show you. I did spend some time trying to build a simple test based on the code in AFNetworkActivityManagerTests.m but I mostly just got crashes. A valid test would simply create an AFURLSessionManager with a background session configuration. Then start a download and test that the networkActivityIndicator is visible. I think you'll find that it isn't visible.

**Comment by phoney** [comment]
I've written a small test app to demonstrate this problem. You can download it from https://dl.dropboxusercontent.com/u/17892523/NoProgress.zip

**Comment by kcharwood** [comment]
This should be fixed when #2702 gets merged in. 

Thanks for work in reviewing that PR @phoney
