### ISSUE TITLE
Lockup/timeout with large uploads over fast networks (iOS7/8)

### ISSUE THREAD

**Issue by edovino** [AFNetworking/AFNetworking#2664]
Whenever I try to do a large file upload over fast networks (fiber, good cable, or even 4G), I get a timeout error (after a long delay). I'm using AFNetworking 2.5.2

I construct a upload operation with `AFHTTPRequestOperationManager POST`, building the body with `appendPartWithInputStream`.

The upload appears to continue: `NSLog` tells me the progress-block is still being called, and `bytesWritten` continues to count up, but the UI updates (done from within the same block) stop, and the app appears frozen.

This *only* happens on fast networks - on my crappy home ADSL (1mbit up on a good day), everything works smoothly. 
On fast networks, the upload completes successfully if I artifically slow down the upload with `[formData throttleBandwidthWithPacketSize:kAFUploadStream3GSuggestedPacketSize delay:kAFUploadStream3GSuggestedDelay / 2];`
(Dividing by two was a random successful choice...)

**Comment by kcharwood** [comment]
Can you provide any other timing information around this? I.e. the upload finishes in under a second? Can you confirm the upload actually makes it to the remote server? Any other symptoms?

**Comment by cdzombak** [comment]
What size files are you talking about for "large file upload"s?

**Comment by edovino** [comment]
The files in quesiton are video-recordings up to 1 min long - depending on chosen quality, in the range 6 - 10mb. On a 'slow' (my crappy home adsl) or artificially slowed-down connection this translates to around 2 mins for a successful upload.
If I *don't* throttle the upload (& have a fast connection) the upload times out after 3-5 minutes.

I should clarify: when I wrote 'The upload appears to continue:..." - I meant that the NSLog messages from the progress-block continue, bytesWritten continue count up, right up until the timeout. Server-side, the file upload never completes. I don't know how much (if any) of the data actually makes it to the server.
The only symptom I see is that while the progress block is still being called (as evidenced by the NSLog messages), the app UI appears frozen (the progress-bar no longer moves). Only after the timeout the app becomes responsive again.

**Comment by cdzombak** [comment]
Hm. That sounds possibly similar to, but not exactly like, something I'm seeing uploading ~30MB videos. In my instance, the network operation goes on for minutes then I get a "connection not available"-family error from iOS itself. The UI never locks up.

**Comment by kcharwood** [comment]
Could this be related to #2481?

**Comment by kcharwood** [comment]
Also, do you see the problem if you use an `AFHTTPSessionManager` instead of an `AFHTTPRequestOperationManager`?

**Comment by kcharwood** [comment]
Now that 2.6.2, we are going to be shifting our focus to the 3.0.0 stream, which removes support for `NSURLConnection`.

 We are planning on only addressing critical security and stability issues in the 2.x branch going forward. If this becomes a widespread problem, it will be addressed.

:beers:
