### ISSUE TITLE
Why not make HTTPRequestOperationWithHTTPMethod:... public on AFHTTPRequestOperationManager ?

### ISSUE THREAD

**Issue by Jafared** [AFNetworking/AFNetworking#2670]
Is there a reason why the following method os not public on AFHTTPRequestOperationManager ?

	- (AFHTTPRequestOperation *)HTTPRequestOperationWithHTTPMethod:(NSString *)method
	                                                 URLString:(NSString *)URLString
	                                                parameters:(id)parameters
	                                                   success:(void (^)(AFHTTPRequestOperation *operation, id responseObject))success
	                                                   failure:(void (^)(AFHTTPRequestOperation *operation, NSError *error))failure;

The requestOperation build that takes a NSURLRequest is public but not this one.
I would find it useful like for instance having the chance to add a custom header on the url request before adding it to the queue.

If making this method public isn't an issue I'd happy to submit a PR for this.

**Comment by mattt** [comment]
Because it doesn't do anything special. It merely delegates to `HTTPRequestOperationWithRequest:...`.

**Comment by Jafared** [comment]
So what do you recommend to customize url requests like I'd like to do?

My goal was to avoid building the request manually or with the requestSerializer (like it's done in that method) to make more concise code. Don't you think it would be convenient?
I'd rather even use the GET:... POST:... ones but they are queuing the operations right away...

**Comment by mattt** [comment]
> So what do you recommend to customize url requests like I'd like to do?

That's what the URL request serializer is designed to do.
