### ISSUE TITLE
POST parameters problems

### ISSUE THREAD

**Issue by shiyingyan** [AFNetworking/AFNetworking#2677]
when I post, I print the parameters I have uploaded on success ,but I found the result is key-value type even I upload a string. I found the reason is you change it to key-value in AFQueryStringFromParametersWithEncoding in AFURLRequestSericalization.m file , I don`t know why you change it .  Now I have modified the method as following:

```
static NSString * AFQueryStringFromParametersWithEncoding(id parameters, NSStringEncoding stringEncoding) {
    if ( [parameters isKindOfClass:[NSDictionary class]] ){
        NSMutableArray *mutablePairs = [NSMutableArray array];
        for (AFQueryStringPair *pair in AFQueryStringPairsFromDictionary(parameters)) {
            [mutablePairs addObject:[pair URLEncodedStringValueWithEncoding:stringEncoding]];
        }
        
        return [mutablePairs componentsJoinedByString:@"&"];
    }
    
    return [parameters stringByAddingPercentEscapesUsingEncoding:stringEncoding];
}
```
but I don`t know whether it`s the best. Wish your answer!

**Comment by mattt** [comment]
AFNetworking works as expected. Parameters are specifically key-value pairs.

**Comment by shiyingyan** [comment]
NO,it doesn't work expectly.When I give a string, the http body is a key-value and the key is null when request completly. 
And another question is your post method.when I use afnetworking,the service is always not able to prase, but I use NSUrlConnection,it can work

**Comment by shiyingyan** [comment]
Now it has two new problems when I post String:

1. Yes ,it still can`t work. I know you fix the problems that the key is null,but the '=' is still there ,it still not work. 
2. Another problem is encoding. 

For example, what I post is "Great minds think alike=", but I print the request.HttpBody  is "=Great minds think alike%3D" when the request fails.  I read your code and the reason is you invoke method stringByAddingPercentEncodingWithAllowedCharacters： in 
function static NSString * AFPercentEscapedStringFromString(NSString *string) ;
in  AFURLRequestSericalization.m file.

so I remove the invocation in function AFPercentEscapedStringFromString and I modify the instance method URLEncodedStringValue :

、、、
static NSString * AFPercentEscapedStringFromString(NSString *string) {
    static NSString * const kAFCharactersGeneralDelimitersToEncode = @":#[]@"; // does not include "?" or "/" due to RFC 3986 - Section 3.4
    static NSString * const kAFCharactersSubDelimitersToEncode = @"!$&'()*+,;=";

    NSMutableCharacterSet * allowedCharacterSet = [[NSCharacterSet URLQueryAllowedCharacterSet] mutableCopy];
    [allowedCharacterSet removeCharactersInString:[kAFCharactersGeneralDelimitersToEncode stringByAppendingString:kAFCharactersSubDelimitersToEncode]];
	// FIXME: https://github.com/AFNetworking/AFNetworking/pull/3028
    // return [string stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacterSet];

    static NSUInteger const batchSize = 50;

    NSUInteger index = 0;
    NSMutableString *escaped = @"".mutableCopy;

    while (index < string.length) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wgnu"
        NSUInteger length = MIN(string.length - index, batchSize);
#pragma GCC diagnostic pop
        NSRange range = NSMakeRange(index, length);

        // To avoid breaking up character sequences such as 👴🏻👮🏽
        range = [string rangeOfComposedCharacterSequencesForRange:range];

        NSString *substring = [string substringWithRange:range];
        
        NSString *encoded = [substring stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacterSet];
        [escaped appendString:encoded];

        index += range.length;
    }
	return escaped;
}
、、、
、、、
- (NSString *)URLEncodedStringValue {
    if (!self.value || [self.value isEqual:[NSNull null]]) {
        return AFPercentEscapedStringFromString([self.field description]);
    } else {
        if( !self.field || [self.field isEqual:[NSNull null]] ){
            return AFPercentEscapedStringFromString([self.value description]);
        }
        return [NSString stringWithFormat:@"%@=%@", AFPercentEscapedStringFromString([self.field description]), AFPercentEscapedStringFromString([self.value description])];
    }
}
、、、
