### ISSUE TITLE
[version 2.5.3] crash on AFURLSessionManager when POST data

### ISSUE THREAD

**Issue by TranChuong** [AFNetworking/AFNetworking#2678]
I using AFURLSessionManager to POST data to server and crash at class AFURLSessionManagerTaskDelegate

![screen shot 2015-04-23 at 3 32 36 pm](https://cloud.githubusercontent.com/assets/7924855/7293340/5962361a-e9ce-11e4-8f15-95d92be45d94.png)

![screen shot 2015-04-23 at 3 34 04 pm](https://cloud.githubusercontent.com/assets/7924855/7293352/807c280a-e9ce-11e4-9f17-ae126e9a6e09.png)

![screen shot 2015-04-23 at 3 39 51 pm](https://cloud.githubusercontent.com/assets/7924855/7293441/46876212-e9cf-11e4-9e1e-af756d5a44de.png)

Who can help me?

**Comment by mattt** [comment]
This is not an issue with AFNetworking. Your code is crashing at the point AFNetworking calls back into your app. Notice that your crashlog backtrace resolves back to ORB DEV `-doPostWith:parameters:completionBlock:`.
