### ISSUE TITLE
Response Body With Invalid Encoding Should Return an Error

### ISSUE THREAD

**Issue by jlnbuiles** [AFNetworking/AFNetworking#2679]
I have a request that is returning a full response body in JSON, but for some reason the `responseObject` returned in the `success` block was nil, even though a 200 was returned. 

After diving into `AFURLResponseSerialization`, I found that the request returned data, but it was successfully converted into a string. This occurs in `responseObjectForResponse:data:error`, line 253. After trying a few things, I realized that it's an encoding issue.

Shouldn't there be an error instead? [this SO thread] (http://stackoverflow.com/a/11478530/922571) discusses this very issue and although there doesn't seem to be a consensus on the specific code, they do agree that it's an error.

The other option would be attempt to render the content anyway. I was able to do so with a new iOS 8 methods added to `NSString` called `stringEncodingForData: encodingOptions: convertedString: usedLossyConversion:`.

Are my suspicions correct?

**Comment by kcharwood** [comment]
I think should probably be an error as well. Should be easy to create some tests around this and demonstrate the issue. Would you want to put those together?

If I'm reading the linked SO post you provided correctly, 415 seems more appropriate if the request is malformed, not the response as received on the client?

**Comment by jlnbuiles** [comment]
hey @kcharwood - so i have a sample [response](https://www.dropbox.com/s/3dtny1wr69h4s15/response.json?dl=0) on which i was receiving the error, but it's lengthy and i honestly don't know where the error is exactly occurring, so i'm uploading the whole response to dropbox to keep the post short. 

i didn't go into the speficifics

`NSData *data = [NSJSONSerialization dataWithJSONObject:response
                                                                                      options:0
                                                                                          error:&error];`

 as mentioned in my initial post, the following works:

`NSString *str2 = [[NSString alloc] initWithData:data encoding:NSASCIIStringEncoding];`

while this returns nil:

`NSString *str2 = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];`

does this make sense?

**Comment by mattt** [comment]
@jlnbuiles ASCII is a subset of UTF-8. If a string is valid ASCII it is (or should be) valid UTF-8.

According to [RFC 7159](http://tools.ietf.org/html/rfc7159):

> JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.  The default encoding is UTF-8, and JSON texts that are encoded in UTF-8 are interoperable in the sense that they will be read successfully by the maximum number of implementations; there are many implementations that cannot successfully read texts in other encodings (such as UTF-16 and UTF-32).

As default behavior, `AFJSONResponseSerializer`, as with most of AFNetworking, follows the relevant specifications. If you're experiencing an issue with the serializer because of invalid behavior from the server, your best recourse is to create your own serializer to work around the issue yourself.

**Comment by jlnbuiles** [comment]
Thanks for clarifying @mattt, I was not aware of this and quite honestly I had not looked at the spec you referenced. However, shouldn't the serializer return an error here? I agree that this is a server error, but shouldn't the response code be different than a 200?

**Comment by mattt** [comment]
> I agree that this is a server error, but shouldn't the response code be different than a 200?

That's totally up to the server. AFNetworking only uses what it receives. I don't see any reason why the serializer would report an error in the scenario as described.

Closing, since there does not appear to be anything to be done here.
