### ISSUE TITLE
Auto property synthesis will not synthesize property ...

### ISSUE THREAD

**Issue by audiocommander** [AFNetworking/AFNetworking#2680]
The latest Xcode release 6.3.1 that has been released April 21st 2015 reports two new warnings:

    AFHTTPRequestOperation.h:38:60: 
    Auto property synthesis will not synthesize property 'response' 
    because it is 'readwrite' but it will be synthesized 'readonly' via another property

and

    AFHTTPSessionManager.h:94:87: 
    Auto property synthesis will not synthesize property 'responseSerializer'; 
    it will be implemented by its superclass, use @dynamic to acknowledge intention

**Comment by tewha** [comment]
This isn't a problem in 2.5.3.

**Comment by jageverola** [comment]
@audiocommander  
Check this

**Comment by mattt** [comment]
Fixed by #2554.
