### ISSUE TITLE
Get raw data from AFHTTPSessionManager responseObject

### ISSUE THREAD

**Issue by annehiro** [AFNetworking/AFNetworking#2681]
I just upgraded to AFNetworking 2.~ and realized that instead of NSData, I am getting a JSON dictionary. I do not want this behavior. Is there any way to globally prevent this serialization?

**Comment by kcharwood** [comment]
By default, the response serializer is set to [AFJSONResponseSerializer](https://github.com/AFNetworking/AFNetworking/blob/3a1785ccccbd0489dc7bf937d577b6f7ca89cacf/AFNetworking/AFHTTPSessionManager.m#L84).  Take a look at the [migration guide](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-2.0-Migration-Guide), and read up on how response serializers work. Just create a new one or use one of the other built in response serializers.

Also, in the future please use StackOverflow for these types of questions. Github should be used for issue reporting and feature discussion.

:beers:

**Comment by mattt** [comment]
Thanks, @kcharwood!
