### ISSUE TITLE
AFNetworking 1.2.0 - 1.3.4 does not validate the domain name in the SSL cert

### ISSUE THREAD

**Issue by natecode** [AFNetworking/AFNetworking#2690]
Some number of versions of AFNetworking (not done with reviewing/testing all of them) from 1.2.0 up through 1.3.4 are vulnerable to the domain validation flaw if pinning is not in use + properly configured. This is because AFNetworking/AFURLConnectionOperation.m only creates policies of type SecPolicyCreateBasicX509 (not SecPolicyCreateSSL, which does hostname validation). It’s the same behavior that 2.x has before 2.5.3, just different code.

It was first reported in 2013, but never properly fixed in 1.x. We don’t know how many versions of 2.x are also vulnerable. 

Issue: https://github.com/AFNetworking/AFNetworking/issues/1157
Pull request: https://github.com/AFNetworking/AFNetworking/pull/1564/

There are some interesting parts to the patch, such as self-tests that would have detected the 2.5.2 domain name validation problem (default should be YES). I don’t know what happened to this patch in 2.x as we are still analyzing the history of the AFN SSL code.

Users are vulnerable if they use AFHTTPClient for SSL. We successfully ran MITM against a demo app with AFNetworking 1.3.4. This version also happens to be embedded in the RestKit tree, and there are a lot of users of RestKit.

We verified it as follows. Configure Burp Proxy to present a cert with the wrong domain name (say, `yahoo.com` for a connection to `sourcedna.com`). Install Burp’s root CA cert on your device or simulator. Make a request to `https://sourcedna.com` with NSURLConnection and see validation returns errors. Then use AFHTTPClient and see that it trusts the server.

Test snippet:

    AFHTTPClient *httpClient = [[AFHTTPClient alloc] initWithBaseURL:url];
    NSMutableURLRequest *req = [httpClient requestWithMethod:@"GET"
           path:@"https://sourcedna.com" parameters:nil];
    AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:req];
    …

Thanks,
Nate (SourceDNA)

**Comment by mattt** [comment]
Thanks for opening this issue, @natecode. We are taking this matter very seriously.

AFNetworking 1.x has not been officially supported since 2013, when it was deprecated by 2.0. However, security patches are applied if deemed necessary for anyone still using 1.x.

To the best of our knowledge, the SSL validation code used in AFNetworking 1.x follows the recommendations of [Apple Technical Note 2232](https://developer.apple.com/library/ios/technotes/tn2232/_index.html), which establishes guidelines on this matter.

Here's what this document says about domain name validation:

> ### Server Name Failures
> If server trust evaluation fails because the server's DNS name does not match the DNS name in the certificate, you can work around the failure by overriding the DNS name in the trust object. To do this, call `SecPolicyCreateSSL` to create a new policy object with the correct server name and then call `SecTrustSetPolicies` to apply it to the trust object.

As we understand it, `SecTrustEvaluate` will validate the domain name of the server with the authentication challenge protection space trust object, and will fail if there is no match. `SecPolicyCreateSSL` should only be necessary if a domain other than the one for the server response is sent (e.g. api.example.com when certificate is not for wildcard domain).

> We verified it as follows. Configure Burp Proxy to present a cert with the wrong domain name (say, yahoo.com for a connection to sourcedna.com). Install Burp’s root CA cert on your device or simulator. Make a request to https://sourcedna.com with NSURLConnection and see validation returns errors. Then use AFHTTPClient and see that it trusts the server.

Just to confirm, are you saying that a MitM is only possible if a root CA certificate is installed?

**Comment by kcharwood** [comment]
Mattt's questions are good ones. Would love to see your thoughts on that front.

I've also reviewed the TN, and the question seems to come down to this:

Does `SecTrustEvaluate` validate the domain of the server, or not? The TN note isnt exactly clear on that front, but it least seems to indicate if you want to validate against a different domain name, you can use `SecPolicyCreateSSL` to build a custom policy to do so. That seems to infer that by default domain names are validated, but it is not explicitly stated.

Your other point about `NSURLConnection` returning a validation error is interesting. Could you provide the exact error you get back in that scenario? That may aid in tracking down the differences.

I'd also be interesting in understanding if there is a real world scenario where this attack could be executed without installing a custom certificate on the device. Can you expound on that?

Thanks again @natecode

**Comment by kcharwood** [comment]
One other note here @natecode 

`SecPolicyCreateBasicX509` appears to only be used when pinning against public certificates. That code is not used when pinning against the certificate, or when pinning is disabled. Your snippet above does not reference setting a pinning mode. Am I chasing a red herring there?

:beers:

**Comment by natecode** [comment]
@kcharwood This is with the default pinning mode, `AFSSLPinningModeNone`. Please see the issue #1157 from 2013 for a full discussion.

We have tested this with an iOS app with the above snippet. With a per-host cert, both AFN and NSURLConnection allow the SSL connection. With an invalid domain name, only AFN allows it and NSURL rejects it (correctly).

Can you try to reproduce? This is pretty much a point-click option in Burp.

**Comment by kcharwood** [comment]
Thanks @natecode. I don't have Burp. Looks like a Windows only app? I'll look to try something similar on my mac.

Could you take a stab at some of the other questions asked above by both me and @mattt? Just trying to get all the info out on the table for full understanding.

Thanks.

**Comment by natecode** [comment]
It's Java.

**Comment by kcharwood** [comment]
Saw the screenshots, and assumed it was Windows :)

**Comment by natecode** [comment]
The real world attack is buy a $50 SSL cert for some domain you own (or reuse one you have), and use that with Burp or MITMProxy to see or modify SSL plaintext.

We traced the internals of `AFURLConnectionOperation` for 1.3.4. `SecEvaluateTrust` returns `kSecTrustResultUnspecified` (success, cert is ok; enum = 4) even though the cert has the wrong domain name. This is the call to SecEvaluateTrust in the `AFSSLPinningModeNone` case of `willSendRequestForAuthenticationChallenge:`. If you're not using `AFHTTPClient` (as above), SecEvaluateTrust properly returns `kSecTrustResultRecoverableTrustFailure` (= 5).

We have not fully audited the pinning code, but it appears to avoid this specific issue.

**Comment by natecode** [comment]
I'm confused at your confusion because this is the exact same behavioral change (`SecPolicyCreateBasicX509` vs. `SecPolicyCreateSSL `) that you fixed in AFN 2.5.3. Switching these two policy objects is exactly what the `validatesDomainName` flag does in 2.5.x.

If you weren't confused about how those two security policy objects work back then, why is that the case now? What is different here?

Issue: https://github.com/AFNetworking/AFNetworking/issues/2619

**Comment by mattt** [comment]
> I'm confused at your confusion because this is the exact same behavioral change (SecPolicyCreateBasicX509 vs. SecPolicyCreateSSL) that you fixed in AFN 2.5.3. Switching these two policy objects is exactly what the validatesDomainName flag does in 2.5.x.

I don't think it is. The `policy` value from `SecPolicyCreateBasicX509` is not used in 1.3.4 with the default pinning mode, whereas in 2.5.3, a policy is explicitly pulled in by `SecTrustSetPolicies`.

I think the confusion now at this point is whether the behavior in 1.3.4 conforms to Apple's Technical Note, and if so, why that behavior would differ from `NSURLConnection`'s default authentication challenge handling.

**Comment by hubert3** [comment]
Has anyone else successfully reproduced this on AFNetworking 1.3?

I have not on an app that uses AFNetworking 1.3.3.

**Comment by subin84** [comment]
I have an app using restkit with AP 1.3.4 ,the app talks to a rest service https://m.testAF.com  , all connections are made using AFHTTPClient . as per the suggestions, 
1. Configured Burp to present a cert with a different domain ( yahoo.com) -using the generate a CA signed cert with specific hostname option
2.Installed the cert on ios device and ran the app
3. I see errors in Burp -  1430274032742	Proxy	[14]  The client failed to negotiate an SSL connection to m.testAF.com:443: Remote host closed connection during handshake.
4.re- Configured Burp to present a cert with a correct domain (m.testAF.com) 
5.re-Installed the cert on ios device and ran the app
6. No errors , the connections go through fine
 
Please advise if im missing something  on how to replicate the issue .

**Comment by natecode** [comment]
@mattt Those are both good questions. I see now that the basic x509 `policy` is used only within `SecTrustCreateWithCertificates` in the pinning code, so it should not apply here.

I'll see if I can do some more digging.

**Comment by tomj** [comment]
@natecode could you link to a complete project which displays the issue?  I'm interested in what value you used for `baseURL

**Comment by natecode** [comment]
@tomj yes, shortly. I am reviewing the test project in depth, as well as the code for each version of 1.2.0 and up. I'd like to understand what is going on here for this issue, but also for pinning in general (i.e. why `SecTrustSetAnchorCertificatesOnly(trust, YES);` is not used.

**Comment by cossorn** [comment]
If it doesn't sully the discussion.. but I put some notes in https://github.com/RestKit/RestKit/issues/2208 on tests we did, and my hacky solution into the local 1.3.4 AFN copy. As the code I nicked from the newer 2.5.3 AFSecurityPolicy.m had references to properties (such as self.validatesDomainName) which aren't relevant to us (as we never accept invalid certs or need to use unvalidated domain name) my quick solution won't be as elegant as the real fix.. but perhaps helps

**Comment by tomj** [comment]
@cossorn funny that I haven't been able to reproduce this issue and >1 other party has.  If I try having a different cert domain on AFN 1.3.4 I receive an SSL handshake failure and then iOS gives me an `NSURLDomain` error -1012 (`kCFURLErrorUserCancelledAuthentication`)...

**Comment by kcharwood** [comment]
@natecode 

I'm trying to give as much information as possible here in my tests for you to double check my scenarios. Still using Burp for the first time here, so I want to make sure I have everything matching your test cases.

I'm performing the following tests in the example project of the [1.3.4 tag of AFNetworking](https://github.com/AFNetworking/AFNetworking/tree/1.3.4) with only one modification ([I am commenting out these lines to disable SSL Pinning](https://github.com/AFNetworking/AFNetworking/blob/1.3.4/Example/Classes/AFAppDotNetAPIClient.m#L53))

I have installed the Burp certificate on my iPhone, and configured it to proxy through Burp.

*Test 1:*
Burp has the following configuration:
* Proxy listener interface set to bind to all interfaces
* Proxy listener set to be invisible
* Proxy listener set to generate a CA-signed certificate with a specific hostname set to `www.yahoo.com`.
* I have turned the Intercepter off, as to not need to manually forward every request.

Results:
* Attempting to connect to https://www.yahoo.com succeeds in Safari.
* Attempting to connect to any other https site in Safari fails.
* Running the modified 1.3.4 AFN example with pinning disabled that attempts to connect to https://alpha-api.app.net/ fails. I have verified that it falls through to line [675](https://github.com/AFNetworking/AFNetworking/blob/1.3.4/AFNetworking/AFURLConnectionOperation.m#L675), cancels the authentication challenge, and properly fails with -1012.

*Test 2:*
Burp has the following configuration:
* Proxy listener interface set to bind to all interfaces
* Proxy listener set to be invisible
* Proxy listener set to generate a CA-signed certificate with a specific hostname set to `alpha-api.app.net`.
* I have turned the Intercepter off, as to not need to manually forward every request.

Results:
* Attempting to connect to https://www.yahoo.com fails in Safari.
* Attempting to connect to any other https site in Safari fails.
* Running the modified 1.3.4 AFN example with pinning disabled that attempts to connect to https://alpha-api.app.net/ succeeds as expected.

**Comment by j5an** [comment]
I have been doing exactly the same tests @subin84 have been doing.  I am not able to reproduce the same results.  Am i missing something?

**Comment by kcharwood** [comment]
@natecode Can you let me know what version of iOS you are testing on? I'm running my tests on 8.3

**Comment by subin84** [comment]
Looking into the apple system logs ,I see the following error when a different hostname was presented

Apr 28 23:52:23 Subin iphone_test_app[379] <Error>:  SecTrustEvaluate  [leaf SSLHostname]
Apr 28 23:52:23 Subin iphone_test_app[379] <Error>:  SecTrustEvaluate  [leaf SSLHostname]

@kcharwood and @j5an , Do you see the same errors as well?

**Comment by j5an** [comment]
I have 1.3.4 and it looks like it checks for SSL hostnames by calling SecTrustEvaluate.  It was part of the fix for 1.3.4 by Josh Chung (https://github.com/AFNetworking/AFNetworking/blob/master/CHANGES)

**Comment by natecode** [comment]
@kcharwood I was able to find a bug in the test app we created for AFN 1.3.4. The code snippet is as follows.

    NSURL *url = [NSURL URLWithString:@"https://google.com"];
    AFHTTPClient *httpClient = [[AFHTTPClient alloc] initWithBaseURL:url];
    NSMutableURLRequest *req = [httpClient requestWithMethod:@"GET"
        path:@"http://google.com" parameters:nil];
    AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:req];

The snippet we wrote to test `NSURLConnection` did not have this bug, so that's why it correctly detected the cert domain name mismatch.

I'm sorry for wasting each of your time on this issue. We've spent the past 24 hours trying to figure out this behavior too, even digging into the internals of `SecEvaluateTrust` to see what Apple was doing in this case. All because of one missing letter. I'll be sure to issue a correction as well.

Related question: should URLRequests be compared to be sure they're relative or match the BaseURL? I'm wondering if a developer could make the same mistake as above?

**Comment by natecode** [comment]
@cossorn I see you were able to reproduce too? Now I'm confused.

**Comment by mattt** [comment]
@natecode To clarify what you meant by "All because of one missing letter", do you mean using "http" instead of "https" here?

```objective-c
NSMutableURLRequest *req = [httpClient requestWithMethod:@"GET"
    path:@"http://google.com" parameters:nil];
```

**Comment by natecode** [comment]
@mattt Yes. This code has mutated a lot over the past couple days and I don't know when this bug got introduced in our testing cycle. I'd like to step away for a bit and let others try to reproduce. I'm not an expert at all the ways AFNetworking can be used, so I'm slow at this stuff.

**Comment by kcharwood** [comment]
@natecode do you see any issues with my steps listed above and using Burp?

**Comment by natecode** [comment]
@kcharwood No, that looks like an excellent approach. I don't use "invisible proxy mode" but that shouldn't make a difference since your Mac will be proxy-aware and not generate relative requests.

http://portswigger.net/burp/help/proxy_options_invisible.html

**Comment by kcharwood** [comment]
Thanks @natecode. I'll wait to hear back more information from @cossorn before closing this issue, but right now it looks like we may in fact not have an issue here.

**Comment by j5an** [comment]
@natecode So about the app lookup SourceDNA has here -> http://searchlight.sourcedna.com/lookup 

Are there any other validations done other than checking if the iOS app uses AFNetworking framework?

**Comment by natecode** [comment]
@j5an This github issue is based solely on a standalone iOS test project we created to review older versions of AFNetworking. It has nothing to do with Searchlight, just research.

We'll be posting more about how it works (and improving its results, updating scans, etc.) soon but I think that's off-topic here.

**Comment by kcharwood** [comment]
@cossorn At this point, you are the only person with an unresolved issue in this thread, and there are currently no reproducible issues that we are aware of. Can you please update your status and more information around your test case that so we can attempt to reproduce, or can we close this as not a bug?

Thanks :beers:

**Comment by natecode** [comment]
@kcharwood I wouldn't call my case "unresolved" as we're still investigating this. For example, did Apple change the default behavior of server trust evaluation? For iOS and/or Mac? What OS versions? I'm still wondering about some odd behavior I saw last night that I plan to dig into.

I won't stand in the way if you want to close this for now if that's your goal since we don't have a concrete test case at the moment, unless @cossorn reconfirms his results. Thanks.

**Comment by kcharwood** [comment]
Understood @natecode. The original issue was due to a problem in the test case, so in my opinion that particular case is resolved. If you have other behavior we can attempt to reproduce, I would be happy to dig into it. I'm not sure why are you referencing Apple's default behavior of trust evaluation, since we don't have reproducible evidence of that being a problem right now.

I'm not aware of any reproducible combination of OS's/API's that are causing problems, so at the moment I'm leaning towards no issue here. I'd like to get more information from @cossorn first before closing the book on this, but at the moment I don't know what else to look into. Everything seems to check out fine on my end and I can't cause a problem with AFN 1.2 -> 1.3.4.

Let me know if I am misunderstanding the situation from your end. If any new evidence arises I'll be happy to dig in further.

**Comment by natecode** [comment]
Sure, sounds reasonable. I can't promise you a deadline and there's a pretty big search space here. I'll be sure to let you know first if we find anything.

**Comment by tomj** [comment]
I'm with @kcharwood on this one.  The original issue was "AFNetworking 1.2.0 - 1.3.4 does not validate the domain name in the SSL cert" and it seems that the issue was opened in error (as a result of an error in test code) which would make the issue dead butfor @cossorn experiencing something (potentially) related.

FWIW I think a lot of people have so far spent a fair bit of time chasing this which could have been avoided if the complete test code was immediately posted - I'm not sure how the maintenance team feel about this but it seems hard to me to rationalise spending time on a serious security bug without being able to see fully how it operates.

**Comment by natecode** [comment]
@tomj I'm happy to collaborate on improving this process. Security reporting in open-source is something that requires a bit of preparation that Github doesn't provide. For example, there's no way to file a private issue on a public project (that I know of). I know @mattt has created a security alias at `afnetworking.org`, so that's helpful. Perhaps we could chat offline? I'm nate via sourcedna.com

**Comment by tomj** [comment]
@natecode sounds good - I'll reach out.  I've only really stumbled across the issues section on the project over the past couple of days so I'm not sure how @mattt has it set up around here w/r/t reporting security issues (whether there's an accepted process etc).

ps: @mattt thanks for your work on AFN - it's a great library.

**Comment by cossorn** [comment]
sorry all, I have been buried today. Will try to lock down a extremely specific failure case for you asap.

**Comment by tomj** [comment]
@cossorn that would be great - interested to close the loop on this one

**Comment by cossorn** [comment]
Hi.. this is driving me slightly more batty. The issue which I saw (RestKit GET to internal node https://dev.com on simulator (I think iOS 8.2) which has a valid cert (for a different domain). I had consistently opened URLs (I believe SecTrustEvaluate was returning result 4). The original test was simply take an existing project which used RestKit 2.3.1 in non-pinned mode, put some breakpoints in the NSURLConnection delegate method  connection:willSendRequestForAuthenticationChallenge: and change the configured URL to hit a node with a valid certificate but a domain mismatch, then observer the flow.

I am been retesting and am now getting rejected connections (SecTrustEvaluate returning 5) i.e. the original code is correctly failing the connection. At present either I was completely barmy and seeing things, or there is something environmental has changed. I have tried multiple different iOS versions.. nothing.

I would think it was just be being dumb in my original tests, but I had called in an iOS developer work-colleague (to do a sanity check) when I did those original tests, check the project URL config.. and he observed the errant behaviour, and the correct (rejection) behaviour with my my small patch.

Having said that.. the lack of domain validation appears to have been raised in issue 1157, closed as supposedly merged into the 2.0 base in 1169.. however, it appear AFN added the functionality to validate the domain in non-pinned mode somewhere between 2.2.0 and 2.3.0 (in AFSecurity.m in the method evaluateServerTrust:domain:). If the code to validate the domain is not in the 1.3.4 code, I can't see why this is not easier to reproduce.

In the original 1.3.4 AFN (non-pinned) the OSStatus status = SecTrustEvaluate(serverTrust, &result); call is purely reliant on the unmodified serverTrust = challenge.protectionSpace.serverTrust; Does this mean that any AFN test-cases will be affected by the specific certificate settings on the test node ? That could impact the repeatability.

**Comment by tomj** [comment]
@cossorn - long post for a Saturday night! :)  Seems like the initially reported bug can't be reproduced?

**Comment by cossorn** [comment]
Not at present. Work pressure has restricted my time to look at this, and I didn't feel the urge to go to the office (the only place I can access the node with the different domain cert).

**Comment by kcharwood** [comment]
Thanks for the update @cossorn. 

At the moment, this issue as originally reported seems to be unreproducible. 

I'm still seeing this issue linked in many places around the internet, including multiple references on twitter popping up daily. I'm going to close this issue, and add a note to the original post above to clarify what has happened as a result of this thread.

If anyone finds any further issues, don't hesitate to update this issue, or email security@alamofire.org.

I really appreciate the many people who have jumped in here and attempted to verify this behavior. It's been a great help having multiple people confirm the library is currently working as expected.

Cheers all around :beers:
