### ISSUE TITLE
AFNetworkReachabilityManager does not handle kSCNetworkReachabilityFlagsTransientConnection reachability flag 

### ISSUE THREAD

**Issue by gavrilovska** [AFNetworking/AFNetworking#2693]
Only on a specific model of iPhone 5S (ME434DN/A with iOS 8.3) the SCNetworkReachability returns kSCNetworkReachabilityFlagsTransientConnection flag, when switching from WiFi to 4G, which then is handled by AFNetworkReachabilityStatus as not reachable, which is not true. This only happens when I use our dev server as host and not our production server, but still I think it is a state that should be handled maybe differently?
Thanks

**Comment by kcharwood** [comment]
Notes on from the header file on `kSCNetworkReachabilityFlagsTransientConnection`

> 	@constant `kSCNetworkReachabilityFlagsTransientConnection`
		This flag indicates that the specified nodename or address can
		be reached via a transient connection, such as PPP.

Here is more info on [PPP](http://en.wikipedia.org/wiki/Point-to-Point_Protocol).

SCNetworkReachability returns a mask, not an individual value. Are there any other bits flipped in the mask, or is that the only one in your scenario?

**Comment by gavrilovska** [comment]
Yes, I know it is a mask, and in my case it returns only that one (0)

**Comment by kcharwood** [comment]
That's interesting. I certainly havent came across that one myself.

Reachability is also difficult to build tests around. I'm assuming you do in fact have a connection in this scenario, and network traffic does complete?

How long do you spend in that scenario as the phone is transitioning from WiFi to 4G? I would imagine that is a relatively quick scenario?
