### ISSUE TITLE
SSL Public Key Hash Pinning

### ISSUE THREAD

**Issue by arein** [AFNetworking/AFNetworking#2695]
I would like to add [SPKI Hash Pinning](https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning#Hashing) rather than extracting the SPKI from the .cer file in my target. [This is considered best practice by OWASP](https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning#Hashing) and also how Pinning is implemented in [Chrome, Chromium](http://scarybeastsecurity.blogspot.de/2011/04/fiddling-with-chromiums-new-certificate.html), and [OkHttp](http://square.github.io/okhttp/javadoc/com/squareup/okhttp/CertificatePinner.html). It provides the following benefits:

1. Anonymization of the Public Key: Can be important if the app is concerned about disclosing information during recompilation
2. Convenience: It is more convenient to hard code the hashes in the application than to use .cer files. This allows more easily to change the hashes based on compile flags

I would also like the option of providing a __backup key__ in case the primary key is compromised/lost. This is complimentary to SPKI Hash Pinning as hashing ensures that attackers cannot see the backup SPKI prior to its use. This is also part of [Google's IETF websec-key-pinning draft](https://tools.ietf.org/html/draft-ietf-websec-key-pinning-21#section-4.3).

It would be important to me that a PR makes it into the master branch. That's why I'd like to start the discussion with you now. Are you generally cool with adding this in case the AFSecurityPolicy remains backwards compatible?

**Comment by kcharwood** [comment]
I think this is certainly worth exploring and would be happy to review and collaborate on it.

**Comment by kcharwood** [comment]
It would also make sense to make sure this is captured in #2673

**Comment by arein** [comment]
Agreed! I'll start working on this soon.

**Comment by kcharwood** [comment]
closing this issue. Direct all further communication to #2733
