### ISSUE TITLE
AFSecurityPolicy Vulnerability on 2.1

### ISSUE THREAD

**Issue by skpullano** [AFNetworking/AFNetworking#2696]
Hello,
i am currently only version 2.1 of AFNetworking and to upgrade at this time for me will be a big task. However, i was wondering in order to fix the security issue can i simply update the source to enable domainValidation in the init method like below. I tested locally with a MiM and i can see it fix the issue after the patch. Does anyone see any issues doing this instead of upgrading? we will be upgrading in the next month or so but want to patch this asap. Thanks!

- (id)init {
    self = [super init];
    if (!self) {
        return nil;
    }

    self.validatesCertificateChain = YES;
    self.validatesDomainName = YES; //ADDED to fix vulnerablity

    return self;
}

**Comment by tewha** [comment]
Wouldn't this be enough to do it, somewhere in your application?

    AFSecurityPolicy *policy = [AFSecurityPolicy defaultPolicy];
    policy.validatesDomainName = YES;

**Comment by skpullano** [comment]
I believe that should work as well

**Comment by kcharwood** [comment]
Yep. Either will do the trick.
