### ISSUE TITLE
Auto property synthesis will not synthesize property 'responseSerializer'; it will be implemented by its superclass, use @dynamic to acknowledge intention

### ISSUE THREAD

**Issue by datomnurdin** [AFNetworking/AFNetworking#2698]
I got this warning message after update latest pod.

```
/Users/MNurdin/Documents/iOS/xxxxx/Pods/AFNetworking/AFNetworking/AFHTTPSessionManager.h:102:87: Auto property synthesis will not synthesize property 'responseSerializer'; it will be implemented by its superclass, use @dynamic to acknowledge intention
```

Code

```
@property (nonatomic, strong) AFHTTPResponseSerializer <AFURLResponseSerialization> * responseSerializer;
```

Please advice. Thank you.

**Comment by kcharwood** [comment]
I believe this was fixed by #2554 

Can you confirm what version of AF you are using?

**Comment by datomnurdin** [comment]
I'm using 2.0.

**Comment by kcharwood** [comment]
Can you confirm you actually are using 2.5.3?

#2680 claims that fixes it.

**Comment by kcharwood** [comment]
I'm building the example project of the latest version of master, and not seeing the error. 

I'm going to close this out. Please let me know if I have misunderstood the issue.

:beers:
