### ISSUE TITLE
AFNetworkActivityIndicatorManager  Memory Leak?

### ISSUE THREAD

**Issue by testwangping** [AFNetworking/AFNetworking#2700]
self.activityIndicatorVisibilityTimer = [NSTimer timerWithTimeInterval:kAFNetworkActivityIndicatorInvisibilityDelay target:self selector:@selector(updateNetworkActivityIndicatorVisibility) userInfo:nil repeats:NO];

The timer maintains a strong reference to this object until it (the timer) is invalidated.

never run
- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self];

    [_activityIndicatorVisibilityTimer invalidate];
}

**Comment by mattt** [comment]
To properly dispose of `AFNetworkActivityIndicatorManager`, you must set `enabled` to `NO`, which will invalidate the timer. This avoids any retain cycle.

This is, of course, a moot point for most use cases, as applications generally enable the activity indicator manager on startup, and let it run until the application is terminated.
