### ISSUE TITLE
Dynamic framework targets for iOS & OS X

### ISSUE THREAD

**Issue by sharplet** [AFNetworking/AFNetworking#2707]
Hi! Something I'd like to work on is adding dynamic framework targets for iOS & OS X. Is this a contribution you'd be interested in accepting?

It's great that Alamofire already supports this for Swift — but it would be really nice to have it back in Objective-C land too!

There's obviously implications for a few different project configuration things: a new Xcode project, how best to support and test this alongside CocoaPods, whether there's a suitable alternative to CocoaPods submodules, etc.. I have some ideas here, but would love to get your input!

If this is something you're interested in then I'd be happy to open a pull request. Thanks for the great library!

**Comment by mattt** [comment]
See previous discussion in #2552.

**Comment by sharplet** [comment]
Ah, sorry for the dupe, didn't see that one when searching.
