### ISSUE TITLE
A GET Request never updates AFURLSessionManager Progress

### ISSUE THREAD

**Issue by AlexmReynolds** [AFNetworking/AFNetworking#2709]
I'm using my own `NSProgress` for a synchronization task. I was getting odd unresolved child progresses. I found that they are created by AFNetworking in the init method of `AFURLSessionManager`. Seems that the `totalUnitCount` and `completedUnitCount` are never set. I'm not sure if that is because the server I hit does not send back data length but either way in `URLSession:task:didCompleteWithError` we should resolve the progress to the total bytes in `self.mutableData` so there is never a dangling progress. Additionally since we are setting the `totalUnitsCount` after we initialize the `NSProgress` we should initialize that progress with a total of -1 which means indeterminate.

I think these lines of code will fix it but I wanted to check first to see if the issue is a real bug or I am missing some delegate call or option.

    @implementation AFURLSessionManagerTaskDelegate

    - (instancetype)init {
        self = [super init];
        if (!self) {
            return nil;
        }
    
        self.mutableData = [NSMutableData data];

        self.progress = [NSProgress progressWithTotalUnitCount:-1];

        return self;
    } 

Then line 163 of the same file

     if(self.progress.indeterminate){
        self.progress.totalUnitCount = self.mutableData.length;
        self.progress.completedUnitCount = self.mutableData.length;
    }

**Comment by kcharwood** [comment]
Would you be willing to put together a pull request and some tests demonstrating this fix?

:beers:

**Comment by AlexmReynolds** [comment]
Ya I'lll work up a PR.

**Comment by skhavari** [comment]
we ran into this recently.  In our case, the progress doesn't update when we get a response from a server that has `transfer-encoding: chunked` and no `content-length` header.  can anyone confirm the progress bar works with HTTP chunking and that is the root cause here?

**Comment by kcharwood** [comment]
Thanks @AlexmReynolds and @skhavari.

I'd assume that is what is going on. AFNetworking tracks progress by KVO'ing NSURLSessionTask, so the update doesn't make it there, you won't get it either.

I've streamlined some of the progress API's in the 3.0.0 branch, so take a look there. But I'd assume you will need some server side support here in order to get the progress update.

:beers:
