### ISSUE TITLE
UIImageView+AFNetworking does not work for Gif

### ISSUE THREAD

**Issue by y88huang** [AFNetworking/AFNetworking#2711]
I was building a gif app and found all the gif does not play using 
```objective-c 
[cell.imageView setImageWithURL:[NSURL URLWithString:gif.smallGifURL]];
```
In `AFURLResponseSerialization.h` 
```objective-c
static UIImage * AFImageWithDataAtScale(NSData *data, CGFloat scale) {
    UIImage *image = [[UIImage alloc] initWithData:data];
    if (image.images) {
        return image;
    }
    
    return [[UIImage alloc] initWithCGImage:[image CGImage] scale:scale orientation:image.imageOrientation];
}
```
I think ```image.images``` is always nil because ``` [[UIImage alloc] initWithData:data] ``` does not work for animated gif.
Why didn't we bring in [AnimatedGIFImageSerialization?](https://github.com/mattt/AnimatedGIFImageSerialization)
The issue will be fixed if I include the  [AnimatedGIFImageSerialization](https://github.com/mattt/AnimatedGIFImageSerialization) in my project.

**Comment by mattt** [comment]
> The issue will be fixed if I include the AnimatedGIFImageSerialization in my project.

Yes, that's what should be done. They are different dependencies.
