### ISSUE TITLE
Missing localizable strings

### ISSUE THREAD

**Issue by grosch** [AFNetworking/AFNetworking#2714]
Localizable string "Request failed: unacceptable content-type: %@" not found in strings table "AFNetworking"

Localizable string "Request failed: %@ (%ld)" not found in strings table "AFNetworking"

**Comment by grosch** [comment]
My apologies, I'm using the current POD for this, which seems to be 2.5.3

**Comment by grosch** [comment]
So you ignored this for five months, and then closed it with no fix and no message as to why you're closing it?

**Comment by kcharwood** [comment]
My apologies grosch. I guess I didn't hit submit on my response.

AFNetworking [does not](https://github.com/AFNetworking/AFNetworking/issues/2396#issuecomment-61396238) provide localization for networking errors that should be presented to the user. That is the responsibility of the developer. You can provide a AFNetworking strings table, which should allow your message to be localized.
