### ISSUE TITLE
Bad Access - libsystem_network.dylib network_proxy_decrement_outstanding

### ISSUE THREAD

**Issue by eytanbiala** [AFNetworking/AFNetworking#2722]
I am occasionally seeing this crash when AFNetworking is managing the network activity indicator. I have not yet found a reproducible sequence for this.

![screen shot 2015-05-14 at 3 39 48 pm](https://cloud.githubusercontent.com/assets/1770794/7640257/2a316770-fa50-11e4-9deb-924d29d9ee66.png)

**Comment by mattt** [comment]
AFNetworking is not part of that backtrace. If you can reproduce this or demonstrate that AFNetworking could be doing something differently, please open a new issue.

**Comment by eytanbiala** [comment]
It's the only library in the app that access the network activity indicator, and it has only been happening after upgrading from AFNetworking 1.3.4 to 2.5.0 So, I believe it is either an issue with AFNetworking or some part of AFNetworking that exposes a bug in the Apple's underlying framework.

Either way, if there is anyone who is seeing the same issue, please share any details you can add. Thanks in advance.

**Comment by adam-siton** [comment]
I'm also seeing the same random crash after upgrading to AFNetworking 2.5.3.

**Comment by eytanbiala** [comment]
I am still seeing the same crash with AFNetworking 2.5.4. @adam-siton have you updated to 2.5.4, and if so, are you still getting this crash?

**Comment by plivesey** [comment]
FYI for others who google search to this page. I believe this is an Apple bug (or at least not related to AFNetworking): http://stackoverflow.com/questions/32465570/crash-network-proxy-decrement-outstanding/34904494#34904494
