### ISSUE TITLE
NSURLSessionDownloadTask response data is not available for 403 status codes

### ISSUE THREAD

**Issue by alfiehanssen** [AFNetworking/AFNetworking#2723]
I'm using `AFURLSessionManager` and an `NSURLSessionDownloadTask` to make a `POST` request to grab some JSON. 

I'm using a `downloadTask` instead of a `dataTask` because that's what background session configurations require. 

Because I'm using a background session configuration I'm relying on the session delegate methods rather than the task delegate methods. 

If this particular request fails with a 403, I need to access the response body data (it contains details about what went wrong) and respond accordingly.

But in the case of 403, the `setDownloadTaskDidFinishDownloadingBlock:` is never called. The only delegate method called is the `setTaskDidCompleteBlock:`. Tracing this back through AFNetworking I see that the `AFURLSessionManager`'s `self.mutableData` property is nil. Which means that I have no way to access the response body's data. 

Snooping the response in Charles Proxy confirms that the response body is being sent to the device.

Difficult to tell if this is an AFNetworking issue or an Apple issue. Any help would be much appreciated. Thanks!

**Comment by mattt** [comment]
> I'm using a downloadTask instead of a dataTask

That's why you're not getting data. `responseData` is `nil` for downloads, because the data is accumulated in a file instead. To see the data itself, look to the file path into which the response data was downloaded.

**Comment by alfiehanssen** [comment]
@mattt thanks for the quick reply. This seems like unexpected behavior because Apple forces us to use downloadTask in lieu of dataTask when using a background session. And in the event of failure (at least this 403 failure), the data is never downloaded to disk, so there's no file location to inspect. 

In short, downloadTask failures never call the `setDownloadTaskDidFinishDownloadingBlock:`. Odd to omit this because response body is in the spec for 403 failures. 

So just to clarify, seems like an Apple issue and not an AF issue?

Thanks again
