### ISSUE TITLE
Two different AFHTTPRequestOperations in the same time get the same responseData sometimes

### ISSUE THREAD

**Issue by gongruike** [AFNetworking/AFNetworking#2724]
I hava a class named OrganizationManager inherit from AFHTTPRequestOperationManager. There is two methods, getOne:success:failure and getTwo:success:failure.
I use this two methods in a view and call like this
{
    [manager getOne:success:failure];
    [manager getTwo:success:failure];
}
manager is a singleton.
Sometimes it work right, but sometimes it didn't. The two operations will get the same responseData. The responseData maybe the right responseData of getOne, and getTwo.
If I set the operationQueue.maxConcurrentOperationCount = 1, it will work correctly.

**Comment by gongruike** [comment]
I found where the problem is. Server turn on the keep-alive, cause this problem.

**Comment by 15972225572** [comment]
why did you set the manager singleton？
