### ISSUE TITLE
Security issue with AFNetworking

### ISSUE THREAD

**Issue by leofto** [AFNetworking/AFNetworking#2727]
According to this article, AFNetworking version from  >= 2.1.0 and <= 2.5.2 have security issue. 

http://blog.mindedsecurity.com/2015/03/ssl-mitm-attack-in-afnetworking-251-do.html

Could someone confirm the affected versions and v2.5.3 has the fix? Also, do AFNetworking version 1.x.x have the same issue?

Thanks

**Comment by mattt** [comment]
The maintainers posted an official response on April 27th: https://gist.github.com/AlamofireSoftwareFoundation/f784f18f949b95ab733a.

See also: #2690.
