### ISSUE TITLE
UIImageView+AFNetworking cache does not respect http protocol cache policy

### ISSUE THREAD

**Issue by fraggle222** [AFNetworking/AFNetworking#2731]
UImageView and its image cache (AFImageCache), will store and return images regardless of any http cache headers set in the **response**, when using `setImageWithURLRequest` or related methods.

In other words if my http response sets Cache-Control headers like "max-age=0, no-cache", the image will still get cached in AFImageCache and it will stay there as long as memory pressure allows. When `setImageWithURLRequest` is called again, the cached image will be used regardless of the age of the image in the cache (no max-age check for instance).

While it is true that you can set `NSURLRequestReloadIgnoringCacheData` or  `NSURLRequestReloadIgnoringLocalAndRemoteCacheData` in the **request** which forces the image view to ignore its AFImageCache, the functionality of other cache policies (especially like the default `NSURLRequestUseProtocolCachePolicy`) are ignored and the image is just returned from the cache.

To address this, maybe (not sure what the best fix here is), we need a new method that will fall through to the backing NSURLCache, which should respect the http cache headers.

**Comment by mattt** [comment]
That's correct. You may override this behavior by setting the shared image cache to another class that conforms to the `AFImageCache` protocol.

**Comment by fraggle222** [comment]
Would it be beneficial to have an alternate version of setImageWithURLRequest that will fall through to any backing NSURLCache in the request 'pipeline'? 

So that way instead of creating our own cache, we could just fall through to NSURLCache (assuming that is being used by underlying calls), but not force that cache to reload (not set NSURLRequestReloadIgnoringCacheData, unless we want that).
