### ISSUE TITLE
Align default behaviour of pinned certificates with documentation 

### ISSUE THREAD

**Issue by flufff42** [AFNetworking/AFNetworking#2735]
According to the documentation for [`AFSecurityPolicy.pinnedCertificates`](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFSecurityPolicy.h#L49):
> …  By default, this property is set to any (`.cer`) certificates included in the app bundle.

However, the implementation of [`defaultPinnedCertificates`](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFSecurityPolicy.m#L158) which is used to provide this set of certificates uses `[NSBundle bundleForClass:[self class]]` in order to instantiate the bundle that is searched for certificates. This does not work as expected if AFNetworking is integrated using a framework rather than a static library.

Based on the documentation for `NSBundle` the correct behaviour would be ensured by using `[NSBundle mainBundle]` instead.

If this is indeed the expected behaviour I can submit a corresponding pull request.

**Comment by mattt** [comment]
Distribution of AFNetworking through a framework is not supported. IIRC, the proposed change would break compatibility with CocoaPods.

**Comment by flufff42** [comment]
Thanks for the clarification regarding support for integration using frameworks.
Regarding CocoaPods, the project seems to be moving towards preferring integration as a framework: https://github.com/CocoaPods/CocoaPods/pull/3168

In the concrete project where this issue was identified the integration using `use_frameworks!` in the Podfile did not reveal any issues prior to this.

**Comment by kukudas** [comment]
What would be the workaround if i want to create a Cocoa Touch Framework (Mach-O Type - Dynamic Library) with Objective-C and this Library uses AFNetworking 2.5.4? If i integrate that library into another Objective-C project the ssl pinning does not work.

**Comment by kcharwood** [comment]
We now have `+ (NSArray *)certificatesInBundle:(NSBundle *)bundle`, where you can specify the bundle you would like to use to load your certificates and set them as pinned certificates.

:beers:

**Comment by 0xced** [comment]
For reference: introduced in 00b23107c4b169d01a226e6c2cd1b254cdb2c56f on `3_0_0_branch`.

**Comment by 0xced** [comment]
Also, the documentation on the master (2.x) branch is still wrong: *included in the app bundle* is wrong when AFNetworking is compiled as a framework.
