### ISSUE TITLE
Apps crash after on backgrounding after displaying any UIActivityIndicatorView

### ISSUE THREAD

**Issue by bnickel** [AFNetworking/AFNetworking#2739]
Commit 850e5e78503ee4a1170b1ac79139025ecf87a6a9 clobbers `-[UIActivityIndicatorView dealloc]` and `-[UIRefreshControl dealloc]`.  In addition to probably causing memory leaks, this eliminates the default behavior of unsubscribing from `UIApplicationDidEnterBackgroundNotification` so backgrounding the app causes a message to be sent to a zombie.

**Comment by kcharwood** [comment]
eeekkk you are right. Let me look further into this.

**Comment by bnickel** [comment]
I just added #2741 with a potential fix.
