### ISSUE TITLE
Crash introduced in commit 234447275464421442a0a290229498eb91b17363

### ISSUE THREAD

**Issue by NikDude** [AFNetworking/AFNetworking#2742]
Overriding dealloc in the UIActivityIndicatorView+AFNetworking and UIRefreshControl+AFNetworking categories is causing a crash (In my case it happens when the app enters background).

**Comment by kcharwood** [comment]
Sorry about that. We are going to get that fixed in #2741 

You should be able to use 2.5.4 for now!
