### ISSUE TITLE
sharedApplication is unavailable:not available on iOS(App Extension)

### ISSUE THREAD

**Issue by ZHANGMRXIN** [AFNetworking/AFNetworking#2749]
使用cocoapods管理AFNetworking时，extension target 的macros中定义了AF_APP_EXTENSION=1，然后在AFNetworking报错的位置，添加了判断条件:!defined(AF_APP_EXTENSIONS)，仍然报错。
Any ideas?

**Comment by kcharwood** [comment]
This should be fixed in the latest version of AFNetworking :beers:
