### ISSUE TITLE
Security policy and pinned SSL certificate

### ISSUE THREAD

**Issue by AymanMelhem** [AFNetworking/AFNetworking#2753]
Hello everyone - 

I need to use HTTPS within my application to communicate securely with my server, I am bit confused about Security policy and Pinned SSL certificates, you mention in the documentation that we should use  HTTPS connection with SSL pinning configured and enabled, so Should I add ssl certificate to my app bundle ? if yes how to handle expired certificate ? On the other hand if we don't add SSL certificate, What is the risk we have in our app? 

Looking forward to hearing back from you soon
Regards

**Comment by mattt** [comment]
We are actively discussing better ways to document SSL pinning on #2673. Feel free to contribute any thoughts or concerns there.
