### ISSUE TITLE
UIImageView(AFNetwork) doesn't work properly in Today extension

### ISSUE THREAD

**Issue by chzhong** [AFNetworking/AFNetworking#2764]
HI all,

I'm building an today extension that display news with images on notification bar.
However, it seemed that I can't get images loaded using setImageWithURL: of UIImageView+AFNetworking. Whether the images load correctly is fully depends on the network of cache: If the image is downloaded fast enough (before ios suspend/terminates my extension) or cached, the image would display. Otherwise, the image doesn't display.

I've tried using AFSessionManager with a background NSURLSession but with no luck. I'm wonder if I got something wrong or AFNetworking doesn't work well in today extension?

**Comment by mbLc** [comment]
Hi,

Same issue here I think did you resolve it? I post on stackoverflow but still got no answer:
http://stackoverflow.com/questions/30754730/uicollectionview-and-afnetworking-image-doesnt-load-sometimes

**Comment by chzhong** [comment]
HI all,

sorry for updating this issue so late. I've figure out that this neither the fault of AFNetworking nor iOS8. It is our stupid server that providing nil for Image URLs. With some checks and now it works perfectly on Today extension.
