### ISSUE TITLE
block retain cycle in AFUrLSessionManager init method

### ISSUE THREAD

**Issue by jl322137** [AFNetworking/AFNetworking#2767]
in AFURLSessionManager.m

line about 435

use session method getTasksWithCompletionHandler with a block

in this block directly use self, not weak self, cause a retain cycle problem

in my app , every manger do not release

**Comment by NathanLi** [comment]
Yes, I noticed this issue also.
But is not because of that block.

Caused by line 422:
self.session = [NSURLSession sessionWithConfiguration:self.sessionConfiguration delegate:self delegateQueue:self.operationQueue];

'delegate:self'

**Comment by jl322137** [comment]
if you debug step over from line 434 to 450 , you will find retain count added up to 5 (3 to 5) cause by this block

finally, i change self to weakSelf, this object can release by arc

and the method you pick also cause retain count added up to 3(1 to 3)

**Comment by kcharwood** [comment]
Any chance this is related to this [issue](https://github.com/AFNetworking/AFNetworking/issues/2149#issuecomment-46842747)? Are you properly cleaning up your manager by calling `invalidateSessionCancelingTasks:`?
