### ISSUE TITLE
With the same status, reachabilityManager.reachable is changing 

### ISSUE THREAD

**Issue by LeeKyungMoon** [AFNetworking/AFNetworking#2768]
Sometimes it shows true sometimes it shows false, what do you think of this situation?

My code is below :
+ (BOOL)isConnectedWithURLString:(NSString*)urlString{
    NSURL *url = [NSURL URLWithString:urlString];
    AFHTTPRequestOperationManager *manaer = [[AFHTTPRequestOperationManager alloc] initWithBaseURL:url];
    return manaer.reachabilityManager.reachable;
}

**Comment by kcharwood** [comment]
We've updated our reachability documentation. Please consult that documentation, and let us know if there are still any issues.

:beers:
