### ISSUE TITLE
Crash on AFURLResponseSerialization.m:534, UIImage *image = [[UIImage alloc] initWithData:data];

### ISSUE THREAD

**Issue by lengmolehongyan** [AFNetworking/AFNetworking#2769]
Hi, I got a crash with 2.5.3.

The breakpoint error message is: `Thread 4: signal SIGABRT`

The console error message is: `Demo(2948,0x114f43000) malloc: *** error for object 0x7ff44b42a560: double free
*** set a breakpoint in malloc_error_break to debug`

**Comment by kcharwood** [comment]
Dupe of [2572 ](https://github.com/AFNetworking/AFNetworking/issues/2572#issuecomment-76877540)
