### ISSUE TITLE
AFNetworking KVO crashes in background thread on OSX 10.9

### ISSUE THREAD

**Issue by mlfarrell** [AFNetworking/AFNetworking#2770]
Using POST method on request operation manager class.

0   libobjc.A.dylib               	0x00007fff90447cd2 objc_assign_ivar_non_gc + 0
1   com.apple.Foundation          	0x00007fff907d3974 __block_global_4 + 422
2   com.apple.Foundation          	0x00007fff906ef724 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 654
3   com.apple.Foundation          	0x00007fff90721a77 ____NSOQDelayedAttachPendingOperations_block_invoke_0 + 99
4   com.apple.Foundation          	0x00007fff906ef724 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 654
5   com.apple.Foundation          	0x00007fff907219d4 __NSOQDelayedAttachPendingOperations + 143
6   libdispatch.dylib             	0x00007fff849680b6 _dispatch_client_callout + 8
7   libdispatch.dylib             	0x00007fff8496c96f _dispatch_after_timer_callback + 22
8   libdispatch.dylib             	0x00007fff849680b6 _dispatch_client_callout + 8
9   libdispatch.dylib             	0x00007fff8496a29b _dispatch_source_invoke + 691
10  libdispatch.dylib             	0x00007fff84969305 _dispatch_queue_invoke + 72
11  libdispatch.dylib             	0x00007fff849691c3 _dispatch_worker_thread2 + 249
12  libsystem_c.dylib             	0x00007fff8c076cdb _pthread_wqthread + 404
13  libsystem_c.dylib             	0x00007fff8c061191 start_wqthread + 13

**Comment by kcharwood** [comment]
What version of AFNetworking are you using?

**Comment by mlfarrell** [comment]
Latest tagged release. Sorry but not at computer currently.

**Comment by kcharwood** [comment]
There is not much to go on here, and nothing in the trace points specifically to AFNetworking. If you are able to provide any additional information, or a reproducible case, feel free to open another issue. Until there, is there isn't much we can do here.

:beers:
