### ISSUE TITLE
POSTing array of objects strange form url encode

### ISSUE THREAD

**Issue by martinprot** [AFNetworking/AFNetworking#2772]
Hi.

I just had the same problem as this SO (http://stackoverflow.com/q/30118388/127493).

If I want to post an array of integer, for example, the `HTTPBody` of my `NSURLRequest` would be:

    array[]=1&array[]=2&array[]=3

That's what I want.

Now, if I want to send some object, like `{ name = john; age = 30}`, the `HTTPBody` would be:

    array[][name]=john&array[][age]=30&array[][name]=simon&array[][age]=40

This will create server side an unexpected array with 4 values : 

    [
      { name = john },
      { age = 30},
      { name = simon },
      { age = 40},
    ]

It's not what I want. I whoud have this `HTTPBody`

    array[0][name]=john&array[0][age]=30&array[1][name]=simon&array[1][age]=40

Is it an expected behaviour ?

**Comment by kcharwood** [comment]
You have the ability to set your own query serialization logic by using `setQueryStringSerializationWithBlock`. I'd recommend using that path for now.

Thanks!

:beers:
