### ISSUE TITLE
framework not found AFNetworking for architecture x86_64

### ISSUE THREAD

**Issue by jamesweb1** [AFNetworking/AFNetworking#2774]
I try to distribute my framework which including AFNetworking module to other developers using my framework. I can run unittests well in framework, but It shows error when others use my framework in the app. The error is as follow:
```
Framework not found AFNetworking for architecture x86_64
(null): Linker command failed with exit code 1 (use -v to see invocation)
```
I integrate AFNetworking to my framework with Cocoapods, and my podfile is as follow:
```
use_frameworks!
link_with 'xxx', 'xxxTests'
pod "AFNetworking", "~> 2.0"
pod 'FMDB', :git => 'https://github.com/robertmryan/fmdb.git'
```
What is the problem of my settings? BTW, my framework is written in Swift, and I use some objective-c framework, ex. AFNetworking, FMDB...

Thanks for answering me a lot.

**Comment by kcharwood** [comment]
AFNetworking 3.0.0 has been refactored to support framework distribution. Please try that branch!

:beers:
