### ISSUE TITLE
NSParameterAssert fails due to NSURL returning nil for a malformed URLString

### ISSUE THREAD

**Issue by mozeryansky** [AFNetworking/AFNetworking#2778]
I incorrectly used a url containing a space which caused NSURL to return nil when creating the url string, thus when `- (NSMutableURLRequest *)requestWithMethod:URLString:parameters:error:` is called, the assert `NSParameterAssert(URLString)` fails.

The error is misconceiving since I did supply a url, but it was just invalid.
Could we check if NSURL returns nil when `NSMutableURLRequest *request = [self.requestSerializer requestWithMethod:method URLString:[[NSURL URLWithString:URLString relativeToURL:self.baseURL] absoluteString] parameters:parameters error:&serializationError];
    ` is called?
There we could call the failure handler so the application doesn't crash.

**Comment by kcharwood** [comment]
I would say the assert worked as expected here. If you breakpoint there and po the URLString, you should see that is nil.
