### ISSUE TITLE
How to cancel a task in AFURLSessionManager

### ISSUE THREAD

**Issue by shuijinliuxi** [AFNetworking/AFNetworking#2782]
I download a file by downloadTaskWithRequest，and I want to cancel it.
How can I do?

**Comment by spbvasilenko** [comment]
@shuijinliuxi If you use AFURLSessionManager, method should be "downloadTaskWithRequest" return NSURLSessionDownloadTask, please read Apple documentation about this class. That can be cancel, resume, suspend :)
