### ISSUE TITLE
[Needs investigation][ios 9] dataTaskWithRequest returning empty responseObject on 200s

### ISSUE THREAD

**Issue by rromanchuk** [AFNetworking/AFNetworking#2783]
I need to make a reproducible project before this can be actionable, but i want to put it out there incase  someone else has seen this. 

Things i know or confirmed:
- using default nsurlsession configuration 
- Callback reached with error == nil 
- `[response allResponseHeaders]` looks healthy and status code 200
- Not an ATS ios 9.0 problem. Proper https, and  http 200 status code
- Confirmed request/response is normal using curl 
- ONLY happens on a ios 8.3 build, targeting 7.1, and running on a 9.0 device (all devices running prior versions of ios are fine)

**Comment by gwanhokim** [comment]
http://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed

**Comment by rromanchuk** [comment]
`Not an ATS ios 9.0 problem. Proper https, and http 200 status code`  :book:

**Comment by JosephLin** [comment]
I'm seeing similar issues. 
- using `AFHTTPRequestOperation`
- response has a status code 200 but no content
- only happens when running a ios 8.3 build on a 9.0 device
- the issue goes away when proxying through Charles
- i'm not 100% sure, but it seems to only happen on PUT/POST requests. GET works fine.

This is the header I saw
```
HTTP/1.1 200 OK
Server: Cowboy
Connection: close
Date: Tue, 16 Jun 2015 15:11:26 GMT
Status: 200 OK
Strict-Transport-Security: max-age=31536000
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Content-Type: application/json; charset=utf-8
X-Ua-Compatible: IE=Edge,chrome=1
X-Request-Id: b432a3b3-b822-4793-a004-03416b8cb325
X-Runtime: 0.221857
X-Rack-Cache: invalidate, pass
Via: 1.1 vaguer
```

**Comment by rromanchuk** [comment]
@JosephLin just changed to `AFHTTPRequestOperation` as a sanity test. I can also confirm your results. FWIW, also have similar headers

**Comment by JosephLin** [comment]
Maybe this is not an AFNetworking issue after all. I tried NSURLConnection and it's doing the same thing. I'm now only seeing the issue intermittently (with both AF or NS), maybe 3 out of 5 times.

I'm using `TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`, btw.

**Comment by rromanchuk** [comment]
I can also confirm that i'm using the same TLS version 
`TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`

Just for fun i added the `NSAppTransportSecurity` plist keys, no difference, as expected since this is an iOS 8.3 build on an ios9 device and we're both getting https 200

**Comment by rromanchuk** [comment]
@JosephLin have you found any workaround for this?

**Comment by kcharwood** [comment]
Have you filed a radar for this? If so, what's the number?

**Comment by rromanchuk** [comment]
@kcharwood I haven't yet, planning on it, just trying to do as much legwork as i can before submitting.

**Comment by rromanchuk** [comment]
@JosephLin I just rebuilt with ios9, and i'm getting the same issue. There must be something extremely subtle going on. You would think we would see more reports by now

**Comment by JosephLin** [comment]
@rromanchuk confirmed that it's happening on iOS 9 builds as well :(

**Comment by rromanchuk** [comment]
@JosephLin OK, i just completely removed AFNetworking and used a direct call to dataTaskWithRequest:completionHandler on a default shared session, and even here, data returns nil, error returns nil, and the response object looks healthy. It's not every request either.... and now i'm getting it on some GET requests... losing my mind on this :sos:

**Comment by rpranata** [comment]
Any update on this? I am also seeing this and I dont have any clue on whats going on.

**Comment by rromanchuk** [comment]
@rpranata i had to walk away from this bug for a while. Last friday i isolated this issue all the way down to a single GET request and it would fail >50%, but not always. 


Also tracked here http://stackoverflow.com/questions/30874329/datataskwithrequest-returning-empty-responseobject-on-200s-ios-8-3-builds-on-io

**Comment by rromanchuk** [comment]
And by "fail" i mean in the context of our problem, an empty response.

**Comment by rpranata** [comment]
@rromanchuk I see it also happening when run on iOS 9.0. I agree, it does not happen every single time. Its here as well (https://forums.developer.apple.com/message/14013#14013). I submitted a bug report to Apple as well, see how it goes. Did you do that as well?

When I was at WWDC 2 weeks ago and was in the lab with one of their engineer, I was also pointed out to the bug report. 

In my case, it happens more often for protected endpoint (with `Authorization` bearer token header -- OAuth 2.0).

**Comment by rromanchuk** [comment]
Just an update, this problem seems to have disappeared with ios9 beta2.  A bit unnerving though...

**Comment by rpranata** [comment]
@rromanchuk I confirmed that its no longer happening with beta2. Thank you!

**Comment by BridgeTheGap** [comment]
I'm building a library and having a similar issue with iOS 8.3 devices. Have no idea why both data and response are `nil`
