### ISSUE TITLE
AFImageCache is purged on app entering background

### ISSUE THREAD

**Issue by Vadim-Yelagin** [AFNetworking/AFNetworking#2784]
This happens as default `NSCache` behavior.
The positive consequence of this (and the rationale behind this behavior in `NSCache`) is that the app has more chance surviving in the background.
The negative consequence of this is that even the images currently present in app's UI are purged from the cache, though they still occupy the memory, and they are reloaded by `setImageWithURL` on another `UIImageView`.
The way to prevent images in use from being purged (and to allow unused images to be purged in foreground) is to use `NSDiscardableContent` protocol for cache items.

**Comment by kcharwood** [comment]
Here is an [old thread](https://github.com/AFNetworking/AFNetworking/issues/1268) that may be relevant here too. And another one here [too](https://github.com/AFNetworking/AFNetworking/issues/268). Probably worth revisiting.

**Comment by Vadim-Yelagin** [comment]
I've checked `NSCache` behavior with `NSDiscardableContent` and it proves to be totally inadequate. Neither have I found any third-party cache with `NSDiscardableContent`-like support. Will be rolling my own.

**Comment by Vadim-Yelagin** [comment]
I'm sorry, what's the resolution here? Not seeing a problem? Giving up?

**Comment by kcharwood** [comment]
Hi @Vadim-Yelagin. I took your last comment as you were rolling a custom solution. If you put something together, I'd be happy to take a look at PR.

**Comment by Vadim-Yelagin** [comment]
@kcharwood it's in Swift and uses NSURLSession directly. I put the relevant files in a repo in case you want to take a look
https://github.com/Vadim-Yelagin/ImageLoading
This also solves a problem with an image being downloaded multiple times if it used in multiple views at the same time, by cacheing and reusing tasks (possibly incomplete) instead of images.
