### ISSUE TITLE
How to construct a post request with header and body?

### ISSUE THREAD

**Issue by shuijinliuxi** [AFNetworking/AFNetworking#2785]
How to construct a post request with header and body?
The request is the follow:

POST /user/getToken.json HTTP/1.1
Host: api.cn.rong.io
App-Key: k51hidwq1mdqb
Nonce: 421497907
Timestamp: 1434420054
Signature: f69d87e84b5fdc31afb1825b66946e23bd8ae166
Content-Type: application/x-www-form-urlencoded 
Content-Length: 48 

userId=1&name=1&portraitUri=http%3A%2F%2F123.jpg

**Comment by kcharwood** [comment]
Questions like these are best suited for StackOverflow. That makes it easier for others to see questions answered as well. Github is for bug reporting and feature requests.

:beers:
