### ISSUE TITLE
Issue when I deploy on iOS9 

### ISSUE THREAD

**Issue by nadagamal** [AFNetworking/AFNetworking#2787]
Hi , 
The below issue appeared when I tried to run app in iOS9 beta version . It works fine in iOS 8 .  So what can I do ? 

Error Domain=AFNetworkingErrorDomain Code=-1011 "Expected status code in (200-299), got 406" UserInfo=0x14ef7f2e0 {NSLocalizedRecoverySuggestion=<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>406 - Client browser does not accept the MIME type of the requested page.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>406 - Client browser does not accept the MIME type of the requested page.</h2>
  <h3>The page you are looking for cannot be opened by your browser because it has a file name extension that your browser does not accept.</h3>
 </fieldset></div>
</div>
</body>
</html>
, NSErrorFailingURLKey=http://api.filgoal.com/MobileAppResources/ios/AppInfo.json, AFNetworkingOperationFailingURLRequestErrorKey=<NSMutableURLRequest: 0x14efa4250> { URL: http://api.filgoal.com/MobileAppResources/ios/AppInfo.json }, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x14ef6a4c0> { URL: https://www.filgoal.com/Arabic/html/error.html } { status code: 406, headers {
    "Cache-Control" = "max-age=31104000";
    "Content-Length" = 1346;
    "Content-Type" = "text/html";
    Date = "Tue, 16 Jun 2015 10:57:31 GMT";
    Server = "Microsoft-IIS/7.5";
    "X-Powered-By" = "ASP.NET";
} }, NSLocalizedDescription=Expected status code in (200-299), got 406}

Thanks a lot :) ,
Nada Gamal

**Comment by kcharwood** [comment]
This is probably best suited for stackoverflow. We have several examples of the library working on iOS 9.

If you find a specific bug with AF, please do let us know.

:beers:
