### ISSUE TITLE
How to discover when all requests and their completion blocks are done.

### ISSUE THREAD

**Issue by m0rt3z4** [AFNetworking/AFNetworking#2790]
I am using AFHTTPRequestOperationManager to send multi request, I want to run a completion block when all the request sent successfully and their completion blocks are done.

What I should do ?

**Comment by kcharwood** [comment]
Hi @m0rt3z4 

Questions like these are best suited for StackOverflow. That makes it easier for others to see questions answered as well. Github is for bug reporting and feature requests.

:beers:
