### ISSUE TITLE
AFURLSessionManager  af_resume  infinite recursive call 

### ISSUE THREAD

**Issue by com314159** [AFNetworking/AFNetworking#2796]
I use AFNetworking 2.5.3

in AFURLSessionManager , I do not know why you recursive call af_resume method. From your code 

- (void)af_resume {
    NSURLSessionTaskState state = self.state;
    [self af_resume];

    if (state != NSURLSessionTaskStateRunning) {
        [[NSNotificationCenter defaultCenter] postNotificationName:AFNSURLSessionTaskDidResumeNotification object:self];
    }
}

it will infinite recursive call af_resume.

And in  my app, some people crashed by this problem.

![image](https://cloud.githubusercontent.com/assets/5378240/8249695/8904f166-169f-11e5-8988-b28157c18fa2.png)

hope you can fix it.

**Comment by soleares** [comment]
I'm seeing the same crashes in 2.5.4 on iOS 8 only.

**Comment by kcharwood** [comment]
I'm really stumped on this one.

This has also been reported in [https://github.com/AFNetworking/AFNetworking/issues/2743]. Can you let me know what other third party libraries are included in your app? We have unit tests that specifically test and confirm the swizzling is properly setup for AF, but it appears some outside library is also creating a problem.

Can you add your information to #2743?

**Comment by TomSwift** [comment]
+ (void)initialize in the  NSURLSessionTask _AFStateObserving category is calling itself recursively (via NSURLSession dataTaskWithURL), and is also called for each instantiated NSURLSessionTask subclass.  It looks to me like the af_addMethod/af_swizzleSelector code is invoked multiple times, which doesn't seem good.   

I haven't dug any further.  Is this the correct behavior or should it be addressed.  Seems like it could result in this broken swizzling issue given the right set of circumstance.

My app is seeing this issue also, but very sporadically.  I don't have a solid repro.

**Comment by iosflio** [comment]
I am getting the same issue after OneSky integration. Is there any solution to resolve this conflict with third party library?

**Comment by waynett** [comment]
Same problem on 2.6.3 in ios9 above

**Comment by shivam-ucreate** [comment]
![screen shot 2016-10-05 at 6 28 07 pm](https://cloud.githubusercontent.com/assets/16460359/19144438/3ca60f3c-8bc7-11e6-8255-2dcb217c0a03.png)
Same crash on iOS 10

**Comment by PoonamYadav** [comment]
same problem when using Dynatrace integrated in the app. Did anyone find the fix to this crash?

**Comment by com314159** [comment]
Now we use Swift
