### ISSUE TITLE
NSData check failing.

### ISSUE THREAD

**Issue by arun-kumar0105** [AFNetworking/AFNetworking#2798]
- (id)responseObjectForResponse:(NSURLResponse *)response data:(NSData *)data error:(NSError *__autoreleasing *)error.

In the above method ([data length] > 0) is failing as data is nil.

 NSString *responseString = [[NSString alloc] initWithData:data encoding:stringEncoding];
 if (responseString && ![responseString isEqualToString:@" "]) //response string length is zero but it's not a nil for responseString will always be != nil.

File Name: AFJSONResponseSerializer

**Comment by kcharwood** [comment]
Can you be more specific? Isn't it failing correctly if data is nil? I would not expect `([data length] > 0) ` to be true if data is nil.
