### ISSUE TITLE
AFHTTPRequestOperationManager times out on Xcode 7.0 Beta/iOS 9

### ISSUE THREAD

**Issue by allanrvj** [AFNetworking/AFNetworking#2799]
This code prints "Success!" on Xcode 6.3.2/iOS 8.3, but prints "Failure. Error: Error Domain=NSURLErrorDomain Code=-1001 'The request timed out.'" on Xcode 7.0 Beta/ iOS 9 Beta.

NSString *url = @"https://autoconf.zylinc.com:8089/GateKeeper/Auth.getKey?format=hex";
AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
manager.responseSerializer = [[AFHTTPResponseSerializer alloc] init];

[manager GET:url parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {
	NSLog(@"Success!");
	
} failure:^(AFHTTPRequestOperation *operation, NSError *error) {
	
	NSLog(@"Failure. Error: %@", error);
}];

Here's a link to download the respective workspaces to recreate the issue:

https://www.dropbox.com/sh/3a36ec27ob2dsr5/AAC5cul6l0b2JOnAND4Au-QKa?dl=0

I've also filed a radar at Apple because I'm not sure if it's a simulator problem.

Thanks.

/Allan

**Comment by kcharwood** [comment]
This appears to be a problem with your URL. It times out in both Chrome and curling it from the command line.
