### ISSUE TITLE
Cache not working when using Heroku

### ISSUE THREAD

**Issue by caioremedio** [AFNetworking/AFNetworking#2800]
I've built some simple `GET` webservice using PHP that return some JSON. I've tested on my local and cache is working perfectly fine. But when I deploy to Heroku, the cache simple doesn't work.

I made few tests, and the server is returning perfectly fine all the cache headers:

**Heroku** Headers response got from AFNetworking:

    "Cache-Control" = "public, max-age=86400";
    Connection = "keep-alive";
    "Content-Type" = "application/json";
    Date = "Sat, 20 Jun 2015 05:10:20 GMT";
    Server = "Apache/2.4.10 (Unix)";
    "Transfer-Encoding" = Identity;
    Via = "1.1 vegur";
    "X-Powered-By" = "PHP/5.6.10";

**Local** server headers from AFNetworking:

    "Cache-Control" = "public, max-age=86400";
    Connection = "Keep-Alive";
    "Content-Length" = 1711;
    "Content-Type" = "application/json";
    Date = "Sat, 20 Jun 2015 05:11:39 GMT";
    "Keep-Alive" = "timeout=5, max=98";
    Server = "Apache/2.4.10 (Unix) OpenSSL/1.0.1j PHP/5.6.3 mod_perl/2.0.8-dev Perl/v5.16.3";
    "X-Powered-By" = "PHP/5.6.3";

Also, `NSCachedURLResponse` always return nill from my Heroku URL.

Does anyone have any ideia about this?

Btw: Using iOS 8.3 SDK.

**Comment by caioremedio** [comment]
I seems that works sometimes on iOS 7.1 devices. I'm not sure why and when it happens. But never works on iOS 8.x

**Comment by kcharwood** [comment]
Caching is definitely finicky across different versions of iOS. AFNetworking using the built in caching mechanisms of NSURLSession and NSURLConnection, and does nothing different by default. You have the ability to override the behavior by default.

It might be best to take this on to StackOverflow, as there is nothing with AFNetworking here that is affecting it.

:beers:
