### ISSUE TITLE
Encrypt the HTTPBody when make a request and decrypt the HTTPBody when receive a response

### ISSUE THREAD

**Issue by Shuangzuan** [AFNetworking/AFNetworking#2802]
Hello, my server is not over SSL so I want to know how to

Encrypt the HTTPBody when make a request.
Decrypt the HTTPBody when receive a response.

Thanks.

**Comment by kcharwood** [comment]
Hi @Shuangzuan,

Questions like these should be asked on Stackoverflow. Github is for reporting issues and feature requests.

:beers:
