### ISSUE TITLE
AFHTTPRequestSerializer, compiling error when overriding method

### ISSUE THREAD

**Issue by tiepvuvan** [AFNetworking/AFNetworking#2803]
class CustomHttpRequestSerializer: AFHTTPRequestSerializer {
    
    override func requestWithMethod(method: String!, URLString: String!, parameters: AnyObject!, error: ()) throws -> NSMutableURLRequest {
        var request = try super.requestWithMethod(method, URLString: URLString, parameters: parameters, error: error)
        return request
    }
}

Got error when compiling: Command failed due to signal: Abort trap: 6
Swift 2.0, XCode 7.0, iOS 9.0

**Comment by kcharwood** [comment]
Please let me know if you are still seeing this issue. I havent seen it reported elsewhere.
