### ISSUE TITLE
Constant -1003 or -1005 network error

### ISSUE THREAD

**Issue by hariharasudhankm** [AFNetworking/AFNetworking#2806]
All of a sudden all request returns -1003 or -1005 immediately within a split second. Its mostly happening for GET request, as that is being used more. But this happens out of the blue. Retrying it doesn't make any difference, after a 2-5 minute gap if you try again it works. 

I'm using 2.5.0, here is the code below how is use, its pretty same as the example code.

```
AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
[self setAcceptHeadersforManager:manager];
__block NSString *ep = endPoint;
[manager GET:url parameters:parameters  options:options success:^(AFHTTPRequestOperation *operation, id responseObject) {
        successBlock(responseObject);
    } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
            failureBlock(error);
}];
```

I've in one of the issues (forgot which one) someone said that calling it twice will solve it, i tried the same, not just twice, but like a 100 times, still fails. Not sure if the root cause if from AFNetworking or underlying Apple libraries. Any help will be appreciated.

**Comment by kcharwood** [comment]
All of our tests are currently passing, so I would assume there is something going on with your network and/or server.

If you can create a sample project/test that reproduces the problem, I'd be happy to look into it further.

Also, it might be time to look into to migrating to `AFHTTPSessionManager`. `NSURLConnection` is deprecated in iOS 9, and a future version of AF will be removing support for the `NSURLConnection` based API's.

**Comment by Senjor** [comment]
well done

**Comment by yoimhere** [comment]
well done

**Comment by kims154** [comment]
well done

**Comment by sea7reen** [comment]
well done

**Comment by Dephaye** [comment]
well done
