### ISSUE TITLE
Xcode7 beta,IOS9 SSL error

### ISSUE THREAD

**Issue by bingxue314159** [AFNetworking/AFNetworking#2807]
Xcode7 beta,IOS9
function:__63-[TYGSaleServiceView findServiceTypeByTypeWithCustomer:typeId:]_block_invoke174 line:265 content:Error: Error Domain=NSURLErrorDomain Code=-1200 "发生了 SSL 错误，无法建立与该服务器的安全连接。" UserInfo=0x7fc30960a690 {_kCFStreamErrorCodeKey=-9847, NSLocalizedRecoverySuggestion=您仍要连接此服务器吗？, NSUnderlyingError=0x7fc30b9018e0 "发生了 SSL 错误，无法建立与该服务器的安全连接。", NSLocalizedDescription=发生了 SSL 错误，无法建立与该服务器的安全连接。, NSErrorFailingURLKey=https://api.uuxoo.com:11000/api/api.action, _kCFStreamErrorDomainKey=3}
2015-06-24 08:49:02.000 AutomobileMarket[3281:98114] CFNetwork SSLHandshake failed (-9847)
2015-06-24 08:49:02.000 AutomobileMarket[3281:98114] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9847)

**Comment by dickwu** [comment]
在iOS9 beta1中，苹果将原http协议改成了https协议，使用 TLS1.2 SSL加密请求数据。

解决办法：

在info.plist中添加
<key>NSAppTransportSecurity</key><dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/></dict>

**Comment by kcharwood** [comment]
As I noted [here](https://github.com/AFNetworking/AFNetworking/issues/2779#issuecomment-112030880), setting `NSAllowsArbitraryLoads` to YES without good reason may lead to an app store rejection. Please follow the best practices laid out by Apple.

**Comment by yorkwang** [comment]
My apps use http, and doesn't update yet. Today I upgraded to iOS9 on my iPad, all my apps are still working using http. It seems Apple doesn't force https in iOS9 release version. Does anybody know when will Apple force do it?

**Comment by yorkwang** [comment]
Got answer here: http://stackoverflow.com/questions/32622289/about-ats-ssl-in-ios-9-release-version
ATS is enabled on apps that are built on Xcode 7 but not on apps that are built with an earlier version of Xcode. This is to prevent hundreds of thousands of apps from 'breaking' on iOS 9.

If you rebuild your app using Xcode 7, ATS will be enabled for your app and you will either need to change your back end to use HTTPS or add exceptions into info.plist.

So essentially, ATS is 'forced' for new/updated apps (or you need to explicitly partially or entirely disable it) but not for old apps.
