### ISSUE TITLE
watchOS 2.0 compilation problem (missing UIScreen class)

### ISSUE THREAD

**Issue by mdzwonek** [AFNetworking/AFNetworking#2808]
I'm having issues with compiling `AFURLResponseSerialization` on watchOS 2.0.

In implementation of class `AFImageResponseSerializer` (line 646 of `AFURLResponseSerialization.m`) there is a call to `mainScreen` method of `UIScreen` class. But `UIScreen` is not available in watchOS's version of UIKit. Will it be enough to put `!defined(AF_APP_EXTENSIONS)` before that call or do you want to handle watchOS case more specifically?

![screen shot 2015-06-24 at 10 52 31](https://cloud.githubusercontent.com/assets/3866270/8327412/0e2ab5e2-1a60-11e5-8604-30c76c70bfa5.png)

(Compiled on Xcode 7.0 beta for watchOS 2.0)

**Comment by kcharwood** [comment]
We probably need to reference `WKInterfaceDevice screenScale` there.

**Comment by kcharwood** [comment]
tracking in #2837
