### ISSUE TITLE
AFHTTPSessionManager GET callbacks never called

### ISSUE THREAD

**Issue by lexicalunit** [AFNetworking/AFNetworking#2809]
`self` here is a subclass of `AFHTTPSessionManager`:

```objc
    dispatch_semaphore_t semaphore = dispatch_semaphore_create(0);
    [self GET:@"v4/products/product/2d8dbbf5-eff5-58b7-a9f9-8d9cb7005a8a" parameters:nil
      success:^(NSURLSessionDataTask *task, id response) {
          assert(0);
          dispatch_semaphore_signal(semaphore);
      }
      failure:^(NSURLSessionDataTask *task, NSError *error) {
          assert(0);
          dispatch_semaphore_signal(semaphore);
      }];
    dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);
```

This code hangs forever. The assertions are never reached. If I travel over to my terminal window and run

```
curl "http://<my-api>/v4/products/product/2d8dbbf5-eff5-58b7-a9f9-8d9cb7005a8a"
```

it returns immediately. So network connectivity is not at issue here. If I remove the semaphore code the code executes without error and exits immediately, having never entered my success or failure callbacks.

**Comment by lexicalunit** [comment]
Also to note, this code is running as a unit test.

**Comment by lexicalunit** [comment]
If it matters, this code is executing as a unit test within Xcode.

**Comment by lexicalunit** [comment]
It did matter. Found the solution here: https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/testing_with_xcode/testing_3_writing_test_classes/testing_3_writing_test_classes.html#//apple_ref/doc/uid/TP40014132-CH4-SW6

**Comment by RushingTwist** [comment]
@lexicalunit hello, I also have the same problem. Do you know what's the cause? How do I deal with it?

**Comment by lexicalunit** [comment]
Hey, sorry I can't remember what it was that I linked to that solved my issue. Perhaps there's something in here https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/04-writing_tests.html <https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/04-writing_tests.html> that might help?

I think I found the answer by searching for some combination of Xcode, tests, AFNetworking, session manager, and semaphore. Maybe one of these pages has a hint:

- https://stackoverflow.com/questions/37696099/xcode-unit-testing-wait-in-class-setup <https://stackoverflow.com/questions/37696099/xcode-unit-testing-wait-in-class-setup>
- https://stackoverflow.com/questions/23567572/semaphore-wait-causing-a-block-of-afnetworking <https://stackoverflow.com/questions/23567572/semaphore-wait-causing-a-block-of-afnetworking>
