### ISSUE TITLE
Swift 2.0 compatibility issues

### ISSUE THREAD

**Issue by johansson** [AFNetworking/AFNetworking#2810]
I understand Swift 2.0 is still beta and all, but with the new `throws` behavior in light, I'd like Swift 2.0 users to be able to use AFNetworking without `throws` throwing it off.

The basis is simple, if you used the overridden serializer:

```swift
class FooSerializer: AFHTTPResponseSerializer {
    override func responseObjectForResponse(response: NSURLResponse!, data: NSData!) throws -> AnyObject {
        let response = try super.responseObjectForResponse(response, data: data)
        return FooResponse(data: response)
    }
}
```

and you get a HTTP error (401, for example). `AFHTTPRequestOperation` does not call the `failure` block, and instead calls the `success` block. However, if you don't use the subclassed `AFHTTPResponseSerializer` and simply use `AFHTTPResponseSerializer`, the `AFHTTPRequestOperation` correctly calls the `failure` block.

You can see the full code of my minimum test case for this bug [here](https://github.com/johansson/AFNetworkingTest). But I'll copy the important code here for context:

```swift
let s = FooSerializer()

let r_200 = NSURLRequest(URL: NSURL(string: "http://localhost:8080/200")!)
let r_401 = NSURLRequest(URL: NSURL(string: "http://localhost:8080/401")!)

let o1 = AFHTTPRequestOperation(request: r_200)

o1.responseSerializer = s
o1.setCompletionBlockWithSuccess({
    (operation, result) -> Void in
        NSLog("o1 success - EXPECTED")
}) {
    (request, error) -> Void in
        NSLog("o1 failure - NOT EXPECTED")
}

let o2 = AFHTTPRequestOperation(request: r_401)
o2.responseSerializer = s
o2.setCompletionBlockWithSuccess({
    (operation, result) -> Void in
        NSLog("o2 success - NOT EXPECTED")
}) {
    (request, error) -> Void in
        NSLog("o2 failure - EXPECTED")
}

let o3 = AFHTTPRequestOperation(request: r_401)
o3.responseSerializer = AFHTTPResponseSerializer()
o3.setCompletionBlockWithSuccess({
    (operation, result) -> Void in
        NSLog("o3 success - NOT EXPECTED")
}) {
    (request, error) -> Void in
        NSLog("o3 failure - EXPECTED")
}

o1.start()
o2.start()
o3.start()
```

The output of the above is something like:

```
2015-06-24 16:30:20.012 AFNetworkingTest[2301:57368] o2 success - NOT EXPECTED
2015-06-24 16:30:20.013 AFNetworkingTest[2301:57368] o1 success - EXPECTED
2015-06-24 16:30:20.013 AFNetworkingTest[2301:57368] o3 failure - EXPECTED
```

My suspicion is that the move to `throws` in Swift 2.0 somehow messes up `NSError` somewhere. I'm not sure if this is Apple's fault or simply `AFNetworking`hasn't had time to be compatible with the new `throws` syntax in Swift.

We fix this by manually checking the status code by casting `NSURLResponse` to `NSHTTPURLResponse`, check status code for 400, 401, etc. then `throw` a custom Swift `ErrorType` enum. Like this:

```swift
// Temporary error codes
enum Errors: ErrorType {
    case ResponseError
}

class BarSerializer: AFHTTPResponseSerializer {
    override func responseObjectForResponse(response: NSURLResponse!, data: NSData!) throws -> AnyObject {
        if let httpResponse = response as? NSHTTPURLResponse where httpResponse.statusCode >= 400 {
            throw Errors.ResponseError
        }

        let response = try super.responseObjectForResponse(response, data: data)
        return FooResponse(data: response)
    }
}
```

Am I wrong to assume that we shouldn't need to do so and that the `AFHTTPResponseSerializer` should do the checking of HTTP status codes for us and throw the error?

By the way, the example code includes a Node.js dummy server you can use to test 200 vs 401. Simply install Node.js and execute `npm install httpdispatcher` then `node dummy-server.js` and run the iOS against that.

**Comment by christophercotton** [comment]
Turns out it is how Swift decides whether to throw or not. From the documentation https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html#//apple_ref/doc/uid/TP40014216-CH7-ID6 

> If an error producing Objective-C method returns a BOOL value to indicate the success or failure of a method call, Swift changes the return type of the function to Void. Similarly, if an error producing Objective-C method returns a nil value to indicate the failure of a method call, Swift changes the return type of the function to a non-optional type.

Since the AFNetworking code both returns an object AND sets the error, swift doesn't throw. There is a macro which can be added `NS_SWIFT_NOTHROW` which will make Swift not make the function into one that throws.
```objective-c
@interface ReturnNil : NSObject
// testing throws
+(id) should:(BOOL)returnNil error:(NSError**)error;
+(id) shouldNoThrows:(BOOL)returnNil error:(NSError**)error NS_SWIFT_NOTHROW;
@end


```

```swift
do {
    let obj = try ReturnNil.should(false)
    print("got obj \(obj)")
} catch let theError as NSError {
    print("got error \(theError)")
}

// prints out the object

do {
    let obj = try ReturnNil.should(true)
    print("got obj \(obj)")
} catch let theError as NSError {
    print("got error \(theError)")
}
// prints out the error

var err:NSError? = nil
let o = ReturnNil.shouldNoThrows(false, error: &err)
print("\(o) \(err)")
// gets both
```

I just added the `NS_SWIFT_NOTHROW` to the method in AFNetworking and it seems to work great. Your method no longer throws, but is like the old code.

See my branch https://github.com/christophercotton/AFNetworking/tree/responseObjectForResponse_NOTHROW

**Comment by kcharwood** [comment]
@johanforssell @christophercotton how does this look? https://github.com/AFNetworking/AFNetworking/commit/aa81eb47d45c9a98789eb28df20ba75138c865a3

**Comment by christophercotton** [comment]
@kcharwood looks great!
