### ISSUE TITLE
The operation couldn't be completed using a VPN IP

### ISSUE THREAD

**Issue by quantumpotato** [AFNetworking/AFNetworking#2812]
I disabled validating certificate chain.

I disabled that and validates domain name in `AFSecurityPolicy.m`

Confirmed that db) po `[AFHTTPRequestOperationManager manager].securityPolicy.SSLPinningMode
AFSSLPinningModeNone` is left on None, too.

`- (NSString *)baseURL` pulls a String from a file.

    NSString *endpoint = @"/authentication.json";
    AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
    
    NSString *token = @"mytokenvalue"
    
    [manager.requestSerializer setValue:token forHTTPHeaderField:TOKEN_HEADER];
    manager.requestSerializer = [AFJSONRequestSerializer serializer];
    
    NSString *path = [NSString stringWithFormat:@"%@%@", [self baseURL], endpoint];
    
    [manager    POST:path
        parameters:nil
        success:^(AFHTTPRequestOperation *operation, id responseObject) {
            if (operation.response.statusCode == 200) {
                [self.delegate validated:true];
            }
      } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
            [self.delegate validated:false];
    }];

    (lldb) po error
    Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)" UserInfo=0x7bf3ed90 {NSErrorFailingURLKey=https://1.2.3.4/authentication.json, 
    NSErrorFailingURLStringKey=https://1.2.3.4/authentication.json}

I can connect to 1.2.3.4 through VPN in my terminal, but not through AFNetworking. I tried 1.2.3.4 and
https://1.2.3.4 .

I have [AFHTTPRequestOperationManager manager].securityPolicy.allowInvalidCertificates = YES; in my app Delegate.

How do I connect to this IP through AFNetworking?

**Comment by kcharwood** [comment]
Questions like these are best suited for StackOverflow. That makes it easier for others to see questions answered as well. Github is for bug reporting and feature requests.

:beers:

**Comment by quantumpotato** [comment]
Hi @kcharwood , I'm trying to connect to an IP available over VPN. It is accessible through command line and my webbrowser, but I get an error in AFNetworking. So this looks like a bug in AFNetworking to me.

Are you able to connect to an IP address through VPN with AFNetworking?

**Comment by mhaseebkhan** [comment]
@kcharwood: I am also facing a similar issue. Can you please comment?
@quantumpotato: Were you able to get this resolved?

**Comment by quantumpotato** [comment]
@mhaseebkhan I was able to get this resolved. I did not have the proper port set on my URL.

I ended up pointing my AFHTTPRequest Base URL to https://1.2.3.4:1000, and then listening on my machine with

```
socat TCP -LISTEN:1000,fork TCP:8.9.10.11:1000
```

where 1.2.3.4 is my machine on the local network and 8.9.10.11 was the server my machine is VPNing into.
