### ISSUE TITLE
Reachability callback not called when launching in iOS 9 in offline mode

### ISSUE THREAD

**Issue by maxgoedjen** [AFNetworking/AFNetworking#2817]
This appears to be a bug with `SCNetworkReachabilitySetCallback` in iOS 9, but figure this might save someone some googling if they're trying to figure out why their reachability callback isn't being hit like they expect. 

OpenRadar link: http://www.openradar.me/radar?id=5703110106284032
Sample project: https://github.com/maxgoedjen/OfflineLaunchCallback

**Comment by kcharwood** [comment]
I was able to verify this is working as expected in 9.1.

If you any additional information, please do let me know!

Thanks! :beers:
