### ISSUE TITLE
random crash from AFNetwork

### ISSUE THREAD

**Issue by nanyangyeren** [AFNetworking/AFNetworking#2818]
5
Crashed: com.apple.NSURLConnectionLoader
EXC_BREAKPOINT 0x0000defe
 raw
0	libsystem_platform.dylib	
_os_lock_corruption_abort
2	libsystem_pthread.dylib	
pthread_mutex_destroy + 14
3
CFNetwork	
CoreLockable::~CoreLockable() + 30
4
CFNetwork	
MutexLockable::~MutexLockable() + 10
5
CFNetwork	
NetConnection::~NetConnection() + 68
6
CFNetwork	
HTTPNetConnection::~HTTPNetConnection() + 78
7
CFNetwork	
HTTPNetConnection_NoAuth::~HTTPNetConnection_NoAuth() + 10
8
CoreFoundation	
__CFArrayReleaseValues + 192
9
CoreFoundation	
CFRelease + 462
10
CFNetwork	
HTTPConnectionCacheEntry::purgeIdleConnections(double, double) + 268
11
CFNetwork	
HTTPConnectionCache::performIdleSweep() + 160
12
CFNetwork	
HTTPConnectionCache::timeoutIdleConnections() + 22
13
CoreFoundation	
CFArrayApplyFunction + 36
14
CFNetwork	
RunloopBlockContext::perform() + 182
15
CFNetwork	
MultiplexerSource::perform() + 220
16
CFNetwork	
MultiplexerSource::_perform(void*) + 48
17	CoreFoundation	
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
21	CoreFoundation	
CFRunLoopRunInMode + 106
22
Foundation	
+[NSURLConnection(Loader) _resourceLoadLoop:] + 318
23	Foundation	
__NSThread__main__ + 1062
26	libsystem_pthread.dylib	
thread_start + 8

**Comment by nanyangyeren** [comment]
![2015-06-29 8 01 06](https://cloud.githubusercontent.com/assets/3656112/8407495/9e776bf8-1e99-11e5-8461-07a1dbc13df8.png)

**Comment by kcharwood** [comment]
We are dropping support for `NSURLConnection` in AFNetworking 3.0 since it has now been deprecated by Apple. I would recommend migrating to `NSURLSession`, and a by produce will be removing that crash.

There does not appear to be any specific AFNetworking code in that crash.

:beers:
