### ISSUE TITLE
Library fails to generate response when request param is string.

### ISSUE THREAD

**Issue by Chintan1307** [AFNetworking/AFNetworking#2824]
I was testing this library for itunes url with below code. It fails to provide response.

NSString *aStr  = @"term=apple&media=software";
AFHTTPRequestOperationManager *manager =    [AFHTTPRequestOperationManager manager];
 manager.requestSerializer = [AFHTTPRequestSerializer serializer];
[manager POST:@"https://itunes.apple.com/search" parameters:aStr success:^(AFHTTPRequestOperation *operation, id responseObject)
{
         NSLog(@"responseObject==%@",responseObject);
}
failure:^(AFHTTPRequestOperation *operation, NSError *error)
{
         
}];

I tried to diagnose the issue and I came to know its failing because of wrong http body generated in below method of AFURLRequestSerialization.m class.

- (NSURLRequest *)requestBySerializingRequest:(NSURLRequest *)request
                               withParameters:(id)parameters
                                        error:(NSError *__autoreleasing *)error

It set httpbody as '(null)=term%3Dapple%26media%3Dsoftware' but it should be set like 'term%3Dapple%26media%3Dsoftware' only.

Please let me know if there's anything I am missing in integration.

**Comment by markmeeus** [comment]
AFHTTPRequestSerializer expects those params to be a dictionary.
Try passing this as value for the params:
```objective-c
NSDictionary *params = @{@"term":@"apple", @"media":@"software"};
```

**Comment by Chintan1307** [comment]
Hello markmeeus,

Your solution worked for me thanks.
