### ISSUE TITLE
Wrong image scale for iPhone 6+ Zoomed in mode

### ISSUE THREAD

**Issue by kathy-tafel** [AFNetworking/AFNetworking#2830]
@implementation AFImageResponseSerializer

``` Objective-C
- (instancetype)init {
...snip----
#if defined(__IPHONE_OS_VERSION_MIN_REQUIRED)
    self.imageScale = [[UIScreen mainScreen] scale];
    self.automaticallyInflatesResponseImage = YES;
#endif

    return self;
}
```

here the scale is wrong if the iPhone 6+ uses the zoomed mode.

This fixes it, but only for the instance of 6+ and @3x:

``` Objective-C
    CGFloat scale =[[UIScreen mainScreen] scale];
    if  ([[UIScreen mainScreen]respondsToSelector:@selector(nativeScale)])
    {
        CGFloat nativeScale = [[UIScreen mainScreen]nativeScale];
        if (scale != nativeScale) {
            if ((scale==3)&&(nativeScale>2.65))
            {
                scale = 2;
            }
        }
    }

    self.imageScale = scale;
```

**Comment by kcharwood** [comment]
That's interesting. So you end up with a 3x image when you actually need a 2x image?

**Comment by kathy-tafel** [comment]
Yes. So say I GET an image that is 60x60px. if @2x it reports its size as 30x30px. If @3x it reports its size as 20x20 pixels. In zoomed in mode on iPhone 6+, which still reports its scale as 3 but is pretending to be 2, then, all the images look like they are 33% smaller. 

My solution works for this instance but I don't think it's great or I would have checked it in ;-)

**Comment by kcharwood** [comment]
For the iPhone 6, if you are running Zoomed Mode, you get the following values:

```
[[UIScreen mainScreen] scale] == 2.0
[[UIScreen mainScreen] nativeScale] == 2.34750
```

**Comment by kcharwood** [comment]
6+ In Standard Mode

```
[[UIScreen mainScreen] scale] == 3.0
[[UIScreen mainScreen] nativeScale] == 2.608696
```

6+ in Zoomed Mode

```
[[UIScreen mainScreen] scale] == 3.0
[[UIScreen mainScreen] nativeScale] == 2.88
```
