### ISSUE TITLE
Strange Issue with addOperations method

### ISSUE THREAD

**Issue by ansarimawais** [AFNetworking/AFNetworking#2832]
Hi,
I am facing a very strange issue as when I am using AFNetworking classes.
After adding operations to operation Queue, it immediately setting operationCount to nil. But when I am using custom class to handle Web services it works perfectly and I get know as when the queue finishes operations.

I also tried KVO option as well but I am getting operation count as nil while it is still calling web services.

**Comment by kcharwood** [comment]
Would you be able to provide a sample project demonstrating the problem?
