### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ItsTipTop** [AFNetworking/AFNetworking#2833]
https://github.com/Carthage/Carthage

Now Carthage failed with error: Project "AFNetworking OS X Example.xcodeproj" has no shared schemes

From Carthage page: Because Carthage has no centralized package list, and no project specification format, most frameworks should build automatically.

More info: https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by kcharwood** [comment]
Please direct your comments to #2552 

Thanks.
