### ISSUE TITLE
How could perform Https Request with AFHTTPRequestOperationManager

### ISSUE THREAD

**Issue by taojigu** [AFNetworking/AFNetworking#2838]
Hello,

Could you tell me how to post a https request?

My  Code is : 

    AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
    manager.requestSerializer = [AFJSONRequestSerializer serializer];
    manager.responseSerializer = [AFJSONResponseSerializer serializer];
    manager.responseSerializer.acceptableContentTypes =[NSSet setWithObjects:@"application/json",nil];
[manager POST:urlString parameters:bodyDict success:^(AFHTTPRequestOperation *operation, id responseObject)
    {
        if (nil==successBlock) return ;
         
        dispatch_async(dispatch_get_main_queue(),^
        {
            successBlock(responseObject);
        });
    }
    failure:^(AFHTTPRequestOperation *operation, NSError *error)
    {
        if (nil==failBlock)
        {
            
            return ;
        }
        

        dispatch_async(dispatch_get_main_queue(),^
        {
            failBlock(error);
        });
         
    }];

**Comment by hydr93** [comment]
This would help you.

```objectivec
AFHTTPSessionManager* manager = [AFHTTPSessionManager manager];
    manager.requestSerializer = [AFJSONRequestSerializer serializer];
    manager.responseSerializer = [AFJSONResponseSerializer serializer];
    
    [manager POST: urlString parameters:bodyDict
         success:^(NSURLSessionDataTask *task, id responseObject){
             
         return;
         }
         failure:^(NSURLSessionDataTask *task, NSError *error){
             
          failBlock(error);
         }
     ];
```

**Comment by samirGuerdah** [comment]
This is not and AFNetworking issue. Please see the documentation on how to use AFNetworking https://github.com/AFNetworking/AFNetworking or poste your question in http://stackoverflow.com/

**Comment by taojigu** [comment]
thank you ! Guys , it works well.

**Comment by taojigu** [comment]
I just update the AFNetworking code，The code followed does not work now, when post request https url. 
It works with past versions.
The error description show "Canceled"

AFHTTPSessionManager* manager = [AFHTTPSessionManager manager];
    manager.requestSerializer = [AFJSONRequestSerializer serializer];
    manager.responseSerializer = [AFJSONResponseSerializer serializer];

    [manager POST: urlString parameters:bodyDict
         success:^(NSURLSessionDataTask *task, id responseObject){

         return;
         }
         failure:^(NSURLSessionDataTask *task, NSError *error){

          failBlock(error);
         }
     ];

**Comment by taojigu** [comment]
error	 NSError *	domain: @"NSURLErrorDomain" - code: 18446744073709550617	0x0000000170050d10
