### ISSUE TITLE
Manual install xcode 6 iOS 8 

### ISSUE THREAD

**Issue by AladinWay** [AFNetworking/AFNetworking#2839]
I know using coaopods is better, but I need to install AFNetworking manually , I have added  the folder "AFNetworking" and "UIKit+AFNetworking" but I get the error

              ` Unknown type name 'NS_ASSUME_NONNULL_BEGIN'`
                `Cannot combine with previous '(error)' declaration specifier`

**Comment by enryzol** [comment]
i have the same problem when i manually install AFNetworking.

**Comment by kcharwood** [comment]
What version of Xcode are you using? I believe this was introduced in Xcode 6.3

**Comment by enryzol** [comment]
i resolv the problem.  I use Pods to install afnetworking and it's work fine.
