### ISSUE TITLE
issues revealed with Clang static code analysis (XCode 7.0)

### ISSUE THREAD

**Issue by nyotis** [AFNetworking/AFNetworking#2847]
![screen shot 2015-07-20 at 15 08 36](https://cloud.githubusercontent.com/assets/658719/8776430/61cf462c-2ef1-11e5-982b-03f6e1f8c3e6.png)

**Comment by kcharwood** [comment]
Fixed in #2867

**Comment by nyotis** [comment]
substituting
-@property (readwrite, nonatomic, assign) SCNetworkReachabilityRef networkReachability;
+@property (readwrite, nonatomic, strong) id networkReachability;
in AFNetworkReachabilityManager causes the attached
![screen shot 2015-08-04 at 9 31 25 am](https://cloud.githubusercontent.com/assets/658719/9055482/c83ee660-3a8b-11e5-8bea-3cdc15027378.png)

**Comment by kcharwood** [comment]
@nyotis tests are passing locally for me on iOS 9. Is anyone else seeing this issue?

**Comment by jcayzac** [comment]
@kcharwood It looks to me @nyotis thought that #2867 only did that one substitution, which it does not.

**Comment by jcayzac** [comment]
@nyotis why didn't you merge the complete PR?
