### ISSUE TITLE
Crash when I input the Two bit array

### ISSUE THREAD

**Issue by ali0201** [AFNetworking/AFNetworking#2851]
![bug](https://cloud.githubusercontent.com/assets/7078700/8821087/8aa04d92-308d-11e5-8527-d1bc467a8d81.png)
![Uploading bug.png…]()
![Uploading bug.png…]()
![Uploading bug.png…]()

**Comment by kcharwood** [comment]
Hey @ali0201 

Could you provide more information around the data your are inputting to generate that crash? I'd like to create a unit test around it in order to make sure we fix it properly. Thanks!

**Comment by kcharwood** [comment]
Please feel free to reopen this if you are able to provide any more information. Thanks!
