### ISSUE TITLE
operation Cancel doesn't get work, but keeps uploading the data bytes. I am using setUploadProgressBlock: NSData is being uploaded. I have also tried connection cancel

### ISSUE THREAD

**Issue by dharaahuja** [AFNetworking/AFNetworking#2852]
operation Cancel doesn't get work, but keeps uploading the data bytes. I am using setUploadProgressBlock: NSData is being uploaded. I have also tried connection cancel.

In AFHTTPRequestOperation. m
-(void)cancel
{
    [super cancel];
    
    if (self.outputStream) {
        [self.outputStream close];
    }
    
    if (self.inputStream) {
        [self.inputStream close];
    } 
}

In AFURLConnectionOperation.m
- (void)cancel {
    [super cancel];
      [self performSelector:@selector(cancelConnection) onThread:[[self class] networkRequestThread] withObject:nil waitUntilDone:NO modes:[self.runLoopModes allObjects]];
} 

http://stackoverflow.com/questions/3684550/how-to-cancel-an-asynchronous-nsurlconnection

Is there any way to end the threads initiated from AFNetworking class ?

Thanks
Dhara

**Comment by harryzh** [comment]
I meet the same issues. when uploading images with AFHTTPRequestOperationManager operation ,I  successfully cancel ,but still uploading the data to server.

**Comment by dharaahuja** [comment]
Hi,

If I run a for loop for queue.operations and cancel each operation, it doesn't work for me as well, but if I do [queue cancelalloperations] it works. 

Hope it works with you too, let me know if I can help. 

Thanks,
Dhara

**Comment by harryzh** [comment]
Does it means I can't cancel a special operation?

how can I cancel sigle one

Dhara, thank for your help @Dhara

**Comment by kcharwood** [comment]
Now that 2.6.2, we are going to be shifting our focus to the 3.0.0 stream, which removes support for `NSURLConnection`.

 We are planning on only addressing critical security and stability issues in the 2.x branch going forward. If this becomes a widespread problem, it will be addressed.

:beers:
