### ISSUE TITLE
Request dataTaskWithHTTPMethod be made public

### ISSUE THREAD

**Issue by soundspectrum** [AFNetworking/AFNetworking#2862]
Hi AFers,

Currently, dataTaskWithHTTPMethod:URLString:parameters:success:failure: is private within AFHTTPSessionManager.m but I think it makes sense for it to be public (and in AFHTTPSessionMananger.h).  It's not unreasonable at all to decide which HTTP method to use at runtime (which is our situation).  Further, I can't see any reason why it shouldn't be public since it essentially won't ever change given how the GET, POST, etc invocations work.

Thanks,
Drew

**Comment by kcharwood** [comment]
Hi @soundspectrum 

This is still possible today, albeit with just an extra step.

You can access the `requestSerialize`r on the manager, and call `requestWithMethod:URLString:parameters:error:`, and then call `dataTaskWithRequest:completionHandler:` on the manager. That should give you the behavior you are looking for.

:beers:

**Comment by tewha** [comment]
@kcharwood that's a really bad workaround, and I'd love to see this looked at again. The sequence you describe with signature, workarounds and reasonably complex block use is 41 carefully crafted lines of code in AFNetorking. I shouldn't have to copy those 41 lines and potentially be out of sync.

**Comment by kcharwood** [comment]
I'd be open to revisiting it and including it if someone wanted to put together a PR. Its a delicate balance of expanding the public facing API, when its something there hasn't been a lot of demand for yet.

**Comment by knellr** [comment]
+1 demand for this. It's an omission that I worry will lead to more fragile code.

**Comment by JotaMelo** [comment]
+1 for this. I have a fork just for this because otherwise it's just... awful. I'd have to repeat essentially the same code for each possible HTTP method.

**Comment by xzenon** [comment]
+1 for this. Totally agree to make it public.

**Comment by martins-p-sergio** [comment]
+1 for this. Should be public.
