### ISSUE TITLE
AFHTTPRequestSerializer: POSTing with no parameters results in Content-Type not being set

### ISSUE THREAD

**Issue by jcayzac** [AFNetworking/AFNetworking#2864]
In `-[AFHTTPRequestSerializer requestBySerializingRequest:withParameters:error:]`, if `parameters` is `nil`, the request's `Content-Type` header is never set to `application/x-www-form-urlencoded`.

An empty string is a valid `application/x-www-form-urlencoded` POST payload.

**Comment by jcayzac** [comment]
Fixed in #2868

**Comment by kcharwood** [comment]
Moving discussion to the PR #2868
