### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by csga5000** [AFNetworking/AFNetworking#2869]
I understand that in **most cases** the best option is **NOT to adjust the request timeout**.

But on **occasion** this is the **correct** course of action.  Perhaps you are doing a background operation that is meant to be slow, and on a slow network perhaps it will take **longer than 60** seconds.
In my case there is are several background operations, which is not typically an issue except on a slow network.

There may be a circumstance in which you should NOT wait 30 seconds.

I understand that there are **workarounds**, but why are they necessary?

In my case I have started on a project that is using RKRestkit, and AFNetworking.  There is already a lot of existing requests, and I need to make some of these background requests be a little more patient.

This layer of abstraction of your code makes it even more of a hassle to do the fix I need to make.

Afterall, while you may consider Apple to have a wise choice in request time, **Apple** presents an easy setting in order to empower programmers, for the occasions when they do need it.

Why make us all create a workaround, when you could provide a way to make this slightly easier for us?

Thank you for consideration, I'm sorry to bother you with this topic as many others have (a testimate to the fact that this is wanted),
    Chase

p.s. I agree that something as broad as setting the default is not a desirable solution

**Comment by csga5000** [comment]
For anyone who may stumble across this, here is the best way to solve this using restkit as is:
http://stackoverflow.com/questions/13855075/request-timeout-in-restkit-0-20-0

This sets the default though, so, you will likely should adjust it somehow.

**Comment by CyberMew** [comment]
Isn't setting the timeout of a request operation already doable?

**Comment by csga5000** [comment]
From **what I have seen/found** the developer, Matt, has rejected attempts to add library functionality for setting the timeout, the only way to do it is using native code, either by overriding methods, or some such work around.  He has some validity to his reasoning but I don't think it's sufficient excuse to deliberately make it more difficult to do.  I have spent a few hours working on how to do this.  Admittedly I moved into a project and I was unfamiliar with the libraries included, but still, it shouldn't be such a hassle.

**Comment by kcharwood** [comment]
RestKit uses AFNetworking 1.0, which is only getting security fixes at this time.

In 2.0, you can easily adjust this by changing the timeout on the request itself, or simply subclass the request URL serializer that you are using and adjust it there for every request.

The flexibility is there now, and I don't believe it's much of hassle to tailor it to your needs as is.

:beers:
