### ISSUE TITLE
Should reset the imageView?

### ISSUE THREAD

**Issue by onmyway133** [AFNetworking/AFNetworking#2874]
In [UIImageView+AFNetworking.m](https://github.com/AFNetworking/AFNetworking/blob/master/UIKit%2BAFNetworking/UIImageView%2BAFNetworking.m#L140), I wonder whether we should reset the imageView before doing the operation.

Before cell will be reused, and the `af_imageRequestOperation` may take time to finish, so use will see a temporary image (because cell is reused) before seeing the correct image for this indexPath.

I think we should not check for placeHolderImage, just

`self.image = placeholderImage;`

is enough

**Comment by kcharwood** [comment]
I could see that potentially a good solution. Would you want to put together a pull request?

**Comment by kcharwood** [comment]
The behavior came from #1768. I'll take a look and see if I can figure out which way would be better moving forward.

**Comment by kcharwood** [comment]
We've completely refactored the image loading in 3.0.0 branch. We'll move forward with that implementation for now.

Thanks!

:beers:
