### ISSUE TITLE
issue on #2867 build (OS X 10.11 El Capitan | Xcode 7.0 beta 4)

### ISSUE THREAD

**Issue by nyotis** [AFNetworking/AFNetworking#2876]
substituting
-@property (readwrite, nonatomic, assign) SCNetworkReachabilityRef networkReachability;
+@property (readwrite, nonatomic, strong) id networkReachability;
in AFNetworkReachabilityManager causes the attached
![screen shot 2015-08-04 at 9 31 25 am](https://cloud.githubusercontent.com/assets/658719/9055506/f5fb86f8-3a8b-11e5-9f11-3923cc98be3a.png)

**Comment by kcharwood** [comment]
Are you using the latest master with yesterdays checkin?

Mine is building fine on 10.10.4 in Xcode 7 Beta 4

**Comment by nyotis** [comment]
10.10.4 in Xcode 7 Beta 4
w/ the latest commit

**Comment by nyotis** [comment]
Builds fine w/ Version 7.0 beta 4 (7A165t)
