### ISSUE TITLE
HTTPAdditionalHeaders on NSURLSessionConfiguration is ignored.

### ISSUE THREAD

**Issue by zxhfirefox** [AFNetworking/AFNetworking#2877]
I find that if I configure HTTPAdditionalHeaders on NSURLSessionConfiguration, which is used to create AFURLSessionManager, but the header is not included on the request.
The header is added from AFURLRequestSerialization's HTTPRequestHeaders.

I think, may be in the AFURLRequestSerialization's logic, we check the HTTPAdditionalHeaders on NSURLSessionConfiguration will be better.

**Comment by simpoul** [comment]
Hi, just had a big problem with that...

Was working on iOS8, but don't on iOS9:
sessionManager.session.configuration.HTTPAdditionalHeaders =  ["Authorization" : "Bearer \(token!)"]

New code for iOS9:
sessionManager.requestSerializer.setValue("Bearer \(token!)", forHTTPHeaderField: "Authorization")

It is very confusing and frustrating... Just remove completely "HTTPAdditionalHeaders", it gets overwritten anyways...

Thank you guys

**Comment by kcharwood** [comment]
@simpoul Could you push an example up showing the problem? I'd like to dig in and see if there is something we can do there.

**Comment by kcharwood** [comment]
I'm going to close this for now. Feel free to open a new ticket and reference this one if you create an example.

:beers:
