### ISSUE TITLE
When app first install into iphone ,then launch with no network.Then I open the network,but the AFNet did not work any more,even I restart the app.

### ISSUE THREAD

**Issue by JokerXu** [AFNetworking/AFNetworking#2880]
Use the lastest version.When app first install into iphone,then first launch with no network.Then I open the network,but the AFNet did not work any more,even I restart the app. Every network response give me the error information like 
：Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo=0x7ff8ac22f7c0 {NSUnderlyingError=0x7ff8ac017790 "The network connection was lost.", NSErrorFailingURLStringKey=http://v.163.com/special/open_roster/, NSErrorFailingURLKey=http://v.163.com/special/open_roster/, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57, NSLocalizedDescription=The network connection was lost.}

**Comment by hardikdevios** [comment]
@JokerXu i suppose this is not AF issue this is something with your internet connection or with your server request that got hangup , but as far as my understanding this is not belongs to AF.

**Comment by JokerXu** [comment]
It's the iOS simulator's bug. So We should't care about it anymore ,Thank you very much~
