### ISSUE TITLE
[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke_3

### ISSUE THREAD

**Issue by felipe-garcia-movile** [AFNetworking/AFNetworking#2881]
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0xf2458c48

Hello guys, i came here about this bug, i working at app that using afnetworking, and we have a lot of crash its a level 5 at crashlytics.

The problem like you see at title is at AFHTTPResquestOperation when calling block return, so far i saw its that block doesn't exist, was dealloc.

This bug started after release of AFNetworking 2.2.3, this was where i went so far, if any one could help

**Comment by hardikdevios** [comment]
@felipe-garcia-movile Could you please post Fabric/Crashlytics screenshot ? i suppose this issue define that its crash on that block but that doesn't apply that block got delloc . if possible than please post that AF request here which is causing this issue.

**Comment by kcharwood** [comment]
Could you provide any more information around this crash? Keep in mind we are removing support for `AFHTTPRequestOperation` in AFN 3.0.0 since `NSURLConnection` has been deprecated. Migrating to `AFHTTPSessionManager` will most likely mitigate this issue you are seeing.

**Comment by kcharwood** [comment]
Now that 2.6.2, we are going to be shifting our focus to the 3.0.0 stream, which removes support for `NSURLConnection`.

 We are planning on only addressing critical security and stability issues in the 2.x branch going forward. If this becomes a widespread problem, it will be addressed.

:beers:
