### ISSUE TITLE
Crash on +[AFURLConnectionOperation networkRequestThreadEntryPoint:]

### ISSUE THREAD

**Issue by mehdihz** [AFNetworking/AFNetworking#2883]
AFURLConnectionOperation.m line 163
+[AFURLConnectionOperation networkRequestThreadEntryPoint:]

my AFNetworking is latest version.

my stack trace is:

Thread : Fatal Exception: NSGenericException
0  CoreFoundation                 0x2f573f83 __exceptionPreprocess
1  libobjc.A.dylib                0x39cc0ccf objc_exception_throw
2  CoreFoundation                 0x2f573a81 -[NSException name]
3  Foundation                     0x2fede913 -[NSISEngine substituteOutAllOccurencesOfBodyVar:withExpression:]
4  Foundation                     0x2fee159f -[NSISEngine pivotToMakeBodyVar:newHeadOfRowWithHead:andDropRow:]
5  Foundation                     0x2fedf325 -[NSISEngine minimizeConstantInObjectiveRowWithHead:]
6  Foundation                     0x2fee1d9f -[NSISEngine tryUsingArtificialVariableToAddConstraintWithMarker:rowBody:usingInfeasibilityHandlingBehavior:mutuallyExclusiveConstraints:]
7  Foundation                     0x2fedd5fd -[NSISEngine tryToAddConstraintWithMarker:expression:integralizationAdjustment:mutuallyExclusiveConstraints:]
8  Foundation                     0x2fedd23b -[NSLayoutConstraint _addLoweredExpression:toEngine:integralizationAdjustment:lastLoweredConstantWasRounded:mutuallyExclusiveConstraints:]
9  Foundation                     0x2fedaf6d -[NSLayoutConstraint _addToEngine:integralizationAdjustment:mutuallyExclusiveConstraints:]
10 UIKit                          0x31e80ae5 -[UIView(UIConstraintBasedLayout) _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:]
11 UIKit                          0x31e87dad -[UIView(UIConstraintBasedLayout) _constraints_didChangeAutoresizingConstraintsArrayForContainedView:]
12 UIKit                          0x31e81171 -[UIView(UIConstraintBasedLayout) _updateAutoresizingConstraints]
13 UIKit                          0x31e810b1 -[UIView(AdditionalLayoutSupport) updateConstraints]
14 UIKit                          0x3231d1ab -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPass:]
15 UIKit                          0x31e84aa9 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPass:]
16 CoreFoundation                 0x2f4a78f1 CFArrayApplyFunction
17 UIKit                          0x3231d145 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPass:]
18 UIKit                          0x31e84aa9 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPass:]
19 CoreFoundation                 0x2f4a78f1 CFArrayApplyFunction
20 UIKit                          0x3231d145 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPass:]
21 UIKit                          0x31e84aa9 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPass:]
22 Foundation                     0x2fedab2b -[NSISEngine withBehaviors:performModifications:]
23 UIKit                          0x31e9e915 -[UIWindow(UIConstraintBasedLayout) updateConstraintsIfNeeded]
24 UIKit                          0x31e0d5eb -[UIWindow(UIConstraintBasedLayout) layoutSublayersOfLayer:]
25 QuartzCore                     0x31a0e62b -[CALayer layoutSublayers]
26 QuartzCore                     0x31a09e3b CA::Layer::layout_if_needed(CA::Transaction*)
27 QuartzCore                     0x31a09ccd CA::Layer::layout_and_display_if_needed(CA::Transaction*)
28 QuartzCore                     0x31a096df CA::Context::commit_transaction(CA::Transaction*)
29 QuartzCore                     0x31a094ef CA::Transaction::commit()
30 QuartzCore                     0x31a0321d CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
31 CoreFoundation                 0x2f53f255 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
32 CoreFoundation                 0x2f53cbf9 __CFRunLoopDoObservers
33 CoreFoundation                 0x2f4a7ee1 CFRunLoopRunSpecific
34 CoreFoundation                 0x2f4a7ca3 CFRunLoopRunInMode
35 Foundation                     0x2fe9b1eb -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
36 Foundation                     0x2feec0a1 -[NSRunLoop(NSRunLoop) run]
37 Sib                         0x0009b2b3 +[AFURLConnectionOperation networkRequestThreadEntryPoint:] (AFURLConnectionOperation.m:163)
38 Foundation                     0x2ff5da5f __NSThread__main__
39 libsystem_pthread.dylib        0x3a2ec919 _pthread_body
40 libsystem_pthread.dylib        0x3a2ec88b _pthread_start
41 libsystem_pthread.dylib        0x3a2eaaa4 thread_start

And this is thread's stack trace:

Thread : Crashed: AFNetworking (com.twitter.crashlytics.ios.exception)
0  Sib                         0x001808f3 CLSProcessRecordAllThreads + 114
1  Sib                         0x00180b01 CLSProcessRecordAllThreads + 640
2  Sib                         0x0017052f CLSHandler + 30
3  Sib                         0x0017f74b __CLSExceptionRecord_block_invoke + 1150
4  libdispatch.dylib              0x3a1a881f _dispatch_client_callout + 22
5  libdispatch.dylib              0x3a1ae7cb _dispatch_barrier_sync_f_invoke + 26
6  Sib                         0x0017f24f CLSExceptionRecord + 290
7  Sib                         0x0017f057 CLSExceptionRecordNSException + 598
8  Sib                         0x0017ec3d CLSTerminateHandler() + 176
9  libc++abi.dylib                0x395791c7 std::__terminate(void (*)()) + 78
10 libc++abi.dylib                0x39578d2d __cxa_increment_exception_refcount + 98
11 libobjc.A.dylib                0x39cc0e17 objc_exception_rethrow + 42
12 CoreFoundation                 0x2f4a7f35 CFRunLoopRunSpecific + 640
13 CoreFoundation                 0x2f4a7ca3 CFRunLoopRunInMode + 106
14 Foundation                     0x2fe9b1eb -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 254
15 Foundation                     0x2feec0a1 -[NSRunLoop(NSRunLoop) run] + 80
16 Sib                         0x0009b2b3 +[AFURLConnectionOperation networkRequestThreadEntryPoint:] (AFURLConnectionOperation.m:163)
17 Foundation                     0x2ff5da5f __NSThread__main__ + 1062
18 libsystem_pthread.dylib        0x3a2ec919 _pthread_body + 140
19 libsystem_pthread.dylib        0x3a2ec88b _pthread_start + 102
20 libsystem_pthread.dylib        0x3a2eaaa4 thread_start + 8

**Comment by AlexSteinhart** [comment]
I got the same crash log, using version 2.5.0

**Comment by kcharwood** [comment]
Keep in mind that's not the crashing thread, that is just  the entry point for the networking thread used by AFNetworking. You can reference #2301 for additional details. Based on the stack, I would assume you have some UIView code somewhere that has gone awry.
