### ISSUE TITLE
AFNetworking (2.5.4) Warnings | Memory leaks (found with Version 7.0 beta 4 (7A165t))

### ISSUE THREAD

**Issue by nyotis** [AFNetworking/AFNetworking#2884]
<img width="1099" alt="screen shot 2015-08-06 at 21 07 21" src="https://cloud.githubusercontent.com/assets/658719/9121063/51bc5fda-3c80-11e5-8285-8c2b32ea38e7.png">
<img width="1103" alt="screen shot 2015-08-06 at 21 07 37" src="https://cloud.githubusercontent.com/assets/658719/9121066/51dfbe26-3c80-11e5-8b73-9e69c66c8954.png">
<img width="1105" alt="screen shot 2015-08-06 at 21 07 56" src="https://cloud.githubusercontent.com/assets/658719/9121065/51dee0e6-3c80-11e5-8d45-1ff040579e47.png">
<img width="563" alt="screen shot 2015-08-06 at 21 08 33" src="https://cloud.githubusercontent.com/assets/658719/9121064/51dbf7dc-3c80-11e5-8341-c890cb99c2a7.png">

**Comment by nyotis** [comment]
synopsis
<img width="558" alt="screen shot 2015-08-06 at 21 42 15" src="https://cloud.githubusercontent.com/assets/658719/9121666/118522a4-3c84-11e5-8e49-9d48095f2c86.png">

**Comment by TravisCrist** [comment]
+1 This occurs in Xcode 7 Beta 5 as well.

**Comment by kcharwood** [comment]
In the latest version using Xcode 7.1, I do not see these errors when Analyzing. Are either of you still seeing this?
