### ISSUE TITLE
iOS 9 compatability/readiness?

### ISSUE THREAD

**Issue by khappucino-nordstrom** [AFNetworking/AFNetworking#2885]
Our current application uses AFNetworking and we are looking at application readiness for iOS 9.
Are there any known issues (besides the reachability one in the issues list) with AFNetworking and iOS 9? 

-thanks

**Comment by taylesworth** [comment]
We are actively testing our app with each iOS 9 beta and have found no particular issues with AFNetworking. That said, YMMV.

**Comment by khappucino-nordstrom** [comment]
Thank you for the fast response. This is great to hear.

**Comment by taylesworth** [comment]
Just to be clear, in case it wasn't obvious, I'm not in any way affiliated with AlamoFire or the AFNetworking project. But we do use it heavily in my company's product and it's holding up well in our iOS 9 testing.

If you haven't done any network testing with iOS 9 yet, your biggest concern should be whether, and how, to support ATS. That's the biggest networking change in iOS 9.

**Comment by kcharwood** [comment]
All tests are currently passing on iOS 9. :beers:
