### ISSUE TITLE
AFNetworking content-type ERROR

### ISSUE THREAD

**Issue by charsdavy** [AFNetworking/AFNetworking#2889]
when I use the framework to parse JSON, it is occur content-type error.Now I find the error reason that acceptableContentTypes is not enough.
So I add a @"text/plain" to make my project no error.
I suggest that the next version can add it to resolve the error.Thanks very much.

**Comment by kcharwood** [comment]
You can add custom acceptable content types using the `acceptableContentTypes` property on the response serializer.
