### ISSUE TITLE
Issues with uploading to AppStore that includes AfNetworking

### ISSUE THREAD

**Issue by BitBlasters** [AFNetworking/AFNetworking#2892]
So I am having an issue uploading my app to the app store. I am using CocoaPods to install several third party libraries. One of them is AFNetworking. Everything is fine when it validates and verifies fine without errors, but when I try to upload the binary I get numerous errors. Here are the ones for AFNetworking.

ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle Coupons.app/Frameworks/AFNetworking.framework is invalid. The minimum value is 8.0"

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'Coupons.app/Frameworks/AFNetworking.framework/AFNetworking' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

 WARNING ITMS-90080: "The executable 'Payload/Coupons.app/Frameworks/AFNetworking.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library.",

I used one of my Apple DTS tickets to try to figure this out after a week of trying to figure it out myself. Here is what they found.

"We’ve determined that your question should be addressed by the support channel for Pods - the third-party resource you are using.  DTS supports developers using Apple-authored tools and frameworks only. We are unable to provide support for third-party tools, development environments, tutorials or other resources."

So my question is has anyone else seen these errors? I am completely baffled by these, and I need to get this fixed as the app is ready and needs to be uploaded to the store.

I am going to post this to each of the Developers Github page and see if anyone else has any ideas either.

One more thing, the first error that is listed makes no sense, I have a minimum version on my App as 7.0, and I don't quite understand why it says it needs to be a minimum of 8.0.

Thanks.

**Comment by hardikdevios** [comment]
@BitBlasters can you paste your pod file here ?

**Comment by BitBlasters** [comment]
Here you go

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
use_frameworks!


target 'Coupons' do
    pod 'AFNetworking', '~> 2.5'
    pod 'Mantle', '~> 2.0'
    pod 'CCHMapClusterController'
    pod 'SVProgressHUD'
    pod 'DXCustomCallout-ObjC'
    pod 'TOWebViewController'
end


target 'Coupons - Debug' do
    pod 'AFNetworking', '~> 2.5'
    pod 'AFNetworkActivityLogger'
    pod 'Mantle', '~> 2.0'
    pod 'CCHMapClusterController'
    pod 'SVProgressHUD'
    pod 'DXCustomCallout-ObjC'
    pod 'TOWebViewController'
end

**Comment by marcelofabri** [comment]
You cannot use dynamic frameworks with iOS < 8.

**Comment by hardikdevios** [comment]
@marcelofabri you are correct

**Comment by hardikdevios** [comment]
@BitBlasters  ```use_frameworks!``` is a very big line mate sorry to say but you have to remove that or you have to change you minimum requirement to ```8.0``` .. This could pass the Appstore submission

**Comment by BitBlasters** [comment]
Arghhhh... Yep you are correct. I even looked at that line, I thought its ok. Thanks for the help. It looks like it will work now. And sorry for taking your time.

**Comment by hardikdevios** [comment]
@BitBlasters Never mind cheers , Happy coding, you can close the issue if you want ;)

**Comment by wangchauyan** [comment]
Just wanna say thank, you save my day. I got the same problem. 
Finally find out what's wrong with it. 
Thanks a lot

**Comment by huangashz** [comment]
I have the same problem, this is my podfile, whats wrong with me ? which is the dynamic frameworks with iOS < 8 ?

platform :ios, '7.0'
inhibit_all_warnings!

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        puts "=== #{target.name}"
        if target.name == "AFNetworking"
            puts "Setting AFNetworking Macro AF_APP_EXTENSIONS so that it doesn't use UIApplication in extension."
            target.build_configurations.each do |config|
                puts "Setting AF_APP_EXTENSIONS macro in config: #{config}"
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AF_APP_EXTENSIONS=1']
            end
        end
    end
end

def news_pods

    pod 'TMCache'
    pod 'YYText'
    pod 'JRSwizzle'
    pod 'CocoaAsyncSocket'    
    pod 'WeiboSDK'
    pod 'WeixinSDK'
    pod 'FMDB'

end

def shared_pods
    pod 'AFNetworking','~> 2.5.4'
    pod 'SDWebImage'
    pod 'SDWebImage/WebP'
end

target 'sunews' do
    shared_pods
    news_pods
    project 'sunews'
end

target 'SuNewsTodayNews' do
    shared_pods
    project 'sunews'
end
