### ISSUE TITLE
iOS 9 - bug

### ISSUE THREAD

**Issue by lupugabriel** [AFNetworking/AFNetworking#2896]
[cell.imageView setImageWithURL:[NSURL URLWithString:currentItem.img_url] placeholderImage:placeholder];

it's not showing the image on iOS 9.
Same line i have no problem with lower version of IOS

**Comment by lupugabriel** [comment]
if i use: 
[cell.imageView setImageWithURLRequest:request placeholderImage:placeholder success:^(NSURLRequest *request, NSHTTPURLResponse *response, UIImage *image) {
            [cell.imageView setImage:image];
        } failure:^(NSURLRequest *request, NSHTTPURLResponse *response, NSError *error) {
             NSLog(@"Request failed with error: %@", error);
        }];

i got this error:

Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made."

**Comment by jarson** [comment]
That is an ATS error probably, google iOS 9 ATS

**Comment by matrosovDev** [comment]
Hi, I have the same issue. I tested this part of AFNetworking

`BlockerWrapper *wrapper = [[BlockerWrapper alloc] init];
    [wrapper setSuccessBlock:^(UIImage *img) {
        
        [weakSelf setImage:img];
        [weakSelf setNeedsDisplay];
        
        if(fadeIn) {
            
            [UIView beginAnimations:nil context:nil];
            [UIView setAnimationDuration:0.6];
            
            weakSelf.alpha = 1.0;
            
            [UIView commitAnimations];
        }
    }];`

So it never return success block

**Comment by brianhu** [comment]
for people who are facing this problem:
http://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed-on-ios-9
