### ISSUE TITLE
-[AFURLSessionManager URLSession:dataTask:didReceiveData:] crash

### ISSUE THREAD

**Issue by kubbing** [AFNetworking/AFNetworking#2900]
Hey, I am registering this crash in our app. Its 99% iOS8 and its our #1 crash (otherwise we are 99.9% crash free.

![screenshot 2015-08-18 15 16 25](https://cloud.githubusercontent.com/assets/324165/9330832/2001a104-45bc-11e5-9f8e-6de2d568ace8.png)

This problem started with AFNetworking 2.0.

We are using several AF sessions (images, thumbnails, uploads and lookup data) and a single AF manager for api calls (I'll be migrating this to session later).

I would love to fix this one, it has been there a while and its bothering me a lot.

Do you have an idea what the problem might be?

**Comment by Air-Craft** [comment]
Having this problem too...

**Comment by luomu0371** [comment]
having this problem too on v2.5.4  ios7.x when i set operationQueue.maxConcurrentOperationCount  not 1.

**Comment by luomu0371** [comment]
also having this probblem on v2.6.3

**Comment by bigParis** [comment]
crashed on iOS8.0.2 AFN version 3.1

**Comment by huang1988519** [comment]
crashed on iOS 7.X, AFN Version ~>3.1.0, how to repair  this problem ?

**Comment by huipengo** [comment]
see https://github.com/AFNetworking/AFNetworking/issues/2356

**Comment by WangMasterpro** [comment]
@bigParis   how to repair this problem?

**Comment by huang1988519** [comment]
@WangMasterpro  try this.

in  AFURLSessinManager.m L250:

```
- (void)URLSession:(__unused NSURLSession *)session
              task:(NSURLSessionTask *)task
didCompleteWithError:(NSError *)error

...

if (self.mutableData) {
        data = [self.mutableData copy];
        //We no longer need the reference, so nil it out to gain back some memory.
        @synchronized (self.mutableData) {
            self.mutableData = nil;
        }
    }

...

}
```

after this modify, this kind of crash don't appear.

**Comment by WangMasterpro** [comment]
having this problem too on v2.5.4 iOS7.x  and iOS 8.Xwhen i set operationQueue.maxConcurrentOperationCount not 1. 
Delete  It is OK。

**Comment by haofanning** [comment]
It still happen on 4.0.1
