### ISSUE TITLE
build error: function 'SecItemExport' is invalid

### ISSUE THREAD

**Issue by ElfSundae** [AFNetworking/AFNetworking#2901]
Is there anyone else met this build error? I'm not sure whether it is a bug.
I am using Xcode Version 6.4 (6E35b) with iOS8.4 SDK

AFNetworking/AFSecurityPolicy.m:30:27: Implicit declaration of function 'SecItemExport' is invalid in C99
AFNetworking/AFSecurityPolicy.m:30:46: Use of undeclared identifier 'kSecFormatUnknown'
AFNetworking/AFSecurityPolicy.m:30:65: Use of undeclared identifier 'kSecItemPemArmour'

**Comment by stevemoser** [comment]
I got this error after trying to work with a local development pod. Might be an issue with dependencies listing different versions of AFNetworking as a dependency.

**Comment by aakpro** [comment]
I got the same error now. With the same Xcode and iOS SDK.

**Comment by ElfSundae** [comment]
@stevemoser @aakpro It is a build issue on older Xcode, because the `TARGET_OS_IOS` has not been defined on iOS 8 SDK. To fix this error, you may update your Xcode, OR define the macro in a global header file such as `.pch` file:

    #if !defined(TARGET_OS_IOS)
        #define TARGET_OS_IOS TARGET_OS_IPHONE
    #endif

see 94dd608

**Comment by kcharwood** [comment]
As [mentioned](https://github.com/AFNetworking/AFNetworking/blob/master/CHANGELOG.md#260-08-19-2015) in the release notes for 2.6, if you are installing the library manually you will need to define the following variables in your project's pch:

```
#ifndef TARGET_OS_IOS
  #define TARGET_OS_IOS TARGET_OS_IPHONE
#endif
#ifndef TARGET_OS_WATCH
  #define TARGET_OS_WATCH 0
#endif
```

If you have an elegant approach to defining these within the project, please do let me know.

**Comment by aakpro** [comment]
@kcharwood Thanks!

**Comment by danieltigse** [comment]
@kcharwood works for me too thanks

**Comment by zhw511006** [comment]
Works! Thx!

**Comment by minhmera** [comment]
i think the issue appear when we use XCode 6+ , im using AFNetworking 2.0 and XCode 6.4 within that issue and the same solution to fix it 
Thanks

**Comment by beyondverage0908** [comment]
thanks
