### ISSUE TITLE
Why SPDY is not work for iOS with AFNetworking?

### ISSUE THREAD

**Issue by lindsayHan** [AFNetworking/AFNetworking#2903]
I see that SPDY protocol support is now available in NSURLSession on OS X Yosemite and iOS 8 , and is Supported transparently by NSURLSession.

see details： https://developer.apple.com/videos/wwdc/2014/ [What's New in Foundation Networking]

It is ok with NSURLSession like this,

NSURLRequest *request = [NSURLRequest requestWithURL:url];

NSURLSessionDataTask *task =[[NSURLSession sharedSession] dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {

}];
[task resume];

But why it not work When i use AFNetworking's AFURLSessionManage?

**Comment by kcharwood** [comment]
Is there a good SPDY server that I could test with? Something like httpbin.org?
