### ISSUE TITLE
error afnetworking ,AFHTTPRequestOperation

### ISSUE THREAD

**Issue by myusuf08** [AFNetworking/AFNetworking#2904]
+(void)eventswithLoading:(BOOL)isLoading success:(void (^)(NSDictionary *))success
{
    NSString *URL = [NSString stringWithFormat:@"%@/api/topevent.json",serviceURL];
    
    if (isLoading)
    {[SVProgressHUD show];}
    
    AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
    manager.responseSerializer.acceptableContentTypes = [NSSet setWithObject:@"text/html"];
    AFHTTPRequestOperation *operation = [manager POST:URL parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject)
                                         {
                                             if (isLoading)
                                             {[SVProgressHUD dismiss];}
                                             success([responseObject valueForKey:@"EVENTS"]);
                                             NSLog(@"data data %@",[responseObject valueForKey:@"EVENTS"]);
                                         }
                                               failure:^(AFHTTPRequestOperation *resultOperation, NSError *error)
                                               {
                                                   if (isLoading)
                                                   {[SVProgressHUD dismiss];}
                                                   
                                                   NSString *message = @"error";
                                                   NSString *status = @"try again";
                                                   [AlertMessage alertStatus:message withTitle:status withTag:0];
                                                   NSLog(@"fail %@",resultOperation);
                                               }];
                                              
                                              [operation start];

                                               }

end this error

2015-08-19 12:46:37.318 event2ku[1953:72952] fail <AFHTTPRequestOperation: 0x7f849b014480, state: isFinished, cancelled: NO request: <NSMutableURLRequest: 0x7f8498de1f10> { URL: http://event2ku.com/api/topevent.json }, response: <NSHTTPURLResponse: 0x7f8498c25cd0> { URL: http://event2ku.com/api/topevent.json } { status code: 200, headers {
    "Accept-Ranges" = bytes;
    Connection = "Keep-Alive";
    "Content-Length" = 4938068;
    "Content-Type" = "application/json";
    Date = "Wed, 19 Aug 2015 05:46:20 GMT";
    "Keep-Alive" = "timeout=5, max=100";
    "Last-Modified" = "Mon, 23 Mar 2015 09:39:39 GMT";
    Server = Apache;
} }>

please help:(

**Comment by kcharwood** [comment]
Hi @myusuf08 

Github is for bug reporting and feature requests. Please use Stackoverflow for general usage, debugging. 

:beers:
