### ISSUE TITLE
what is the role of the thread operation queue managed? 

### ISSUE THREAD

**Issue by wwxiaofeng** [AFNetworking/AFNetworking#2905]
when instances of NSOperation are added to an operation queue, the queue manages the thread responsible for executing the operation However, AFNetworking's AFURLConnectionOperation subclass spawns a new thread for runloop, and the execution of the operation's -main method is pushed off onto this network request thread ,that mean Network requests in this thread, the thread also request a callback processing, what is the role of the thread queue managed? Could anyone explain it

**Comment by kcharwood** [comment]
Hi @wwxiaofeng,

We've now removed support for `NSURLConnectionOperation` in 3.0.0 since Apple has deprecated it. I'd recommend upgrading to AFNetworking 3.0.0 and using the `NSURLSession` APIs!

:beers:
