### ISSUE TITLE
Can the "parameters" type be "NSString *"?

### ISSUE THREAD

**Issue by XenonChau** [AFNetworking/AFNetworking#2906]
```objective-c
- (NSURLRequest *)requestBySerializingRequest:(NSURLRequest *)request
                               withParameters:(id)parameters
                                        error:(NSError *__autoreleasing *)error
```

while "parameters" was converted into JSON or encrypted with AES.
the following assignment `query = AFQueryStringFromParametersWithEncoding(parameters, self.stringEncoding);` will take a wrong URL string.

I don't know how many kinds of parameters. I'm using `[parameters isKindOfClass[NSDictionary class]] || [parameters isKindOfClass[NSArray class]] ` to avoid these two situations.

Is there any else?

Thanks for all your help.

**Comment by youzg** [comment]
Excuse me. Why not make it possible to support a string?  @kcharwood

**Comment by istx25** [comment]
Any news on this?

**Comment by phoney** [comment]
The parameters are most often key/value pairs so if you pass in a dictionary it is converted to a key/value pair parameter string. @{@"name":@"chau", @"date":@"September 15, 2015"} becomes: @"&name=chau&date=September 15, 2015" 

Is there something different that you want to accomplish?

**Comment by XenonChau** [comment]
thanks for your answer.
but there is a problem: the parameters must be encrypted with AES in our server.
just like this: `1E0977332BDDFF784EC2C2F34D67A9F3961F2318C6ECA27F6A24248706EE0962`
I think there is lots of coders were bothering with this problem.

**Comment by istx25** [comment]
:+1:

**Comment by kcharwood** [comment]
Can you use the `setQueryStringSerializationWithBlock` method on `AFURLRequestSerializer` to set create your on query parameter serialization logic? That seems like the best place for it.

**Comment by XenonChau** [comment]
@kcharwood Thanks for owner's answer. It has fix my issue. Thanks again.
