### ISSUE TITLE
Not all files are added to watchOS target when using Cocoapods

### ISSUE THREAD

**Issue by eshurakov** [AFNetworking/AFNetworking#2909]
I'm trying to use AFURLSessionManager to perform network tasks on watchOS 2.

After adding AFNetworking to my podfile and updating pods, AFURLSessionManager is not added to Watch-AFNetworking target and linker build phase fails. 

If I manually add this file to a target, everything works as expected. 

I believe that "NSURLSession" subspec in AFNetworking podspec should have an s.watchos.deployment_target = '2.0' line inside.

**Comment by kcharwood** [comment]
I just updated the podspec about 10 minutes ago for 2.6

Can you see if that gets you going?

**Comment by kcharwood** [comment]
actually you may be right.

**Comment by kcharwood** [comment]
I'll get this fixed today. Let me make sure there arent any other immediate issues.

**Comment by kcharwood** [comment]
Fixed in a44c8a4

**Comment by eshurakov** [comment]
It works, thank you!
