### ISSUE TITLE
-[AFHTTPSessionManager dataTaskWithRequest:completionHandler] completion parameters are all nonnull

### ISSUE THREAD

**Issue by harlanhaskins** [AFNetworking/AFNetworking#2910]
The error and responseObject in that completion handler are nullable, but they're specified as nonnull.

This breaks my existing Swift that logs errors, expecting the error to be optional.

**Comment by andrewtoth** [comment]
Also every NSError and AnyObject in AFURLSessionManager.

**Comment by kcharwood** [comment]
Fixed by #2911
