### ISSUE TITLE
2.6.0 error while compiling

### ISSUE THREAD

**Issue by CyberMew** [AFNetworking/AFNetworking#2912]
AFSecurityPolicy.m, line 30:    __Require_noErr_Quiet(SecItemExport(key, kSecFormatUnknown, kSecItemPemArmour, NULL, &data), _out);

AFNetworking/AFSecurityPolicy.m:30:46: Use of undeclared identifier 'kSecFormatUnknown'
AFNetworking/AFSecurityPolicy.m:30:65: Use of undeclared identifier 'kSecItemPemArmour'

Didn't have this problem with 2.5.4 before. Apparently to fix this, we have to add this:
    #ifndef TARGET_OS_IOS
        #define TARGET_OS_IOS TARGET_OS_IPHONE
    #endif
    #ifndef TARGET_OS_WATCH
        #define TARGET_OS_WATCH 0
    #endif
into the .pch file. The problem is that copying and pasting is quite error prone, especially when we have 20+ targets inside a single project. Is there any other way besides setting it up via cocoa pods?

**Comment by David4D** [comment]
I've the same error (XCode 6.4 for iOS 7.0 compilation option)

**Comment by dannypier** [comment]
Same issue here. We've gotten around it by adding

```TARGET_OS_IOS```
and
```TARGET_OS_IPHONE```

to the preprocessor macros for our target.

Seems that CocoaPods takes care of this for you as a default: https://github.com/AFNetworking/AFNetworking/commit/7dab91359c64ee40e58d033b427b9d8dc8210456

but CocoaPods isn't appropriate for every use of AFNetworking.

**Comment by David4D** [comment]
Thank, this works. Adding on `Project.pch` :
```
#ifndef TARGET_OS_IOS
#define TARGET_OS_IOS TARGET_OS_IPHONE
#endif

#ifndef TARGET_OS_WATCH
#define TARGET_OS_WATCH 0
#endif
```

**Comment by kcharwood** [comment]
Trying to think of the simpliest, most elegant way to handle this for the non cocoapod users. Any ideas?

**Comment by linyize** [comment]
My solution is to add "TARGET_OS_IOS=1" at Preprocessor Macros -- Build Settings

**Comment by koenvanderdrift** [comment]
Can anyone conform that extra lines for the `.pch` file are no longer needed on XCode7?

**Comment by kcharwood** [comment]
Thats right @koenvanderdrift

**Comment by kcharwood** [comment]
Please see the [changelog](https://github.com/AFNetworking/AFNetworking/blob/master/CHANGELOG.md#important-upgrade-notes) for notes about upgrading to 2.6. Thanks!

**Comment by dennice13** [comment]
7dab913
