### ISSUE TITLE
AFHTTPSessionManager

### ISSUE THREAD

**Issue by pjebs** [AFNetworking/AFNetworking#2916]
Did something change recently?

My subclass of AFHTTPSessionManager was working fine.
Now compiler is spitting error:
Swift Compiler Error
Overriding method with selector 'initWithBaseURL:' has incompatible type '(NSURL)' -> 

class CentralServerManager: AFHTTPSessionManager {
    
    init(baseURL url: NSURL) { //Error is here
        super.init(baseURL: url, sessionConfiguration: nil)
   
    }

**Comment by pjebs** [comment]
I changed cocoapod to 2.5.4 and it works perfectly.
When I change it to ~> 2.0  (i.e. 2.6), it fails to compile again.

**Comment by andrewtoth** [comment]
Version 2.6 added nullability annotations. The baseURL field has been annotated to be nullable, therefore the subclassed init method needs to take an NSURL? instead of an NSURL.
