### ISSUE TITLE
AFNetworking 1.0 issue with ios8?

### ISSUE THREAD

**Issue by Nilesh2985** [AFNetworking/AFNetworking#2917]
I am using AFNetworking1.0 in my project for making HTTP Calls.
and My app works on ios8.

I have created AFHTTPClient class as an Singleton class.....were i have define all my url into this class.
my Problem is,Sometime when were i make an https: post Or put call, I get an error message "Generic error Message".
By getting this message i am not able to complete my request.
But when i close this message ,and again if i try to complete my request,it does complete the request.
So i am not able to find out what's the exact problem?
Can you plese advice?

**Comment by kcharwood** [comment]
Hi @Nilesh2985 

At this time AF 1.x is only receiving security fixes. If you are looking for help on the library, I'd recommend taking your question to Stackoverflow.

:beers:
