### ISSUE TITLE
Should a data tag added to AFHTTPRequestOperation or its base class?

### ISSUE THREAD

**Issue by Zhangwusheng** [AFNetworking/AFNetworking#2918]
When I use AFNetworking to send a http  request ,whether  success or fail,I must execute my business logical, such as removing the request from the data queue on success or re-adding it to the queue on failure.
With current interface ,I must make my data queue Global accessible by making it a singleton.

I hope AFHTTPRequestOperation should add a void* member as a glue to this library and outer business logical. With this ,I can do anything in the callback block of AFHTTPRequestOperation. for example, I can pass a Application's 'this' or 'self' pointer as the data tag,and cast it to Application in the callback block, and execute my own method.

**Comment by kcharwood** [comment]
As mentioned in the 2.6 release notes, we will soon be deprecating our support for NSURLConnection and begin removing the functionality from the library. Apple has been clear that all developers should be moving to NSURLSession, and we are going to focus continued development and maintenance on this library around NSURLSession.

:beers:
