### ISSUE TITLE
Serialization of NSDictionary objects for GET,HEAD,DELETE requests (1.3.4)

### ISSUE THREAD

**Issue by doncorsean** [AFNetworking/AFNetworking#2920]
Currently AFNetworking 1.3.4 uses square brackets to serialize nested objects.

Given the following:
"foo" : {
    "bar" : "baz
}

AFNetworking serializes to:
foo[bar] = "baz"

My API expects:
foo.bar = "baz"

This is easily corrected by modifying line # 160 in https://github.com/AFNetworking/AFNetworking/blob/1.3.4/AFNetworking/AFHTTPClient.m

It would be great if we could set a formatting block in AFHTTPClient to customize how complex objects serialize for these type of requests. This optional setting would allow anyone currently using 1.3.4 to customize how these params are formatted and if not set would have no impact on existing users. Any chance of getting this fixed? I'm using AFNetworking in a static library of which some consumers use RestKit. Until RestKit removes AFNetworking dependency or upgrades to AF2.x I'm stuck with 1.3.4.

**Comment by kcharwood** [comment]
Hi @doncorsean 

AF 1.x is no longer supported, and will only be updated for security vulnerabilities. If you need any custom changes, it is recommended you fork the library and maintain your changes independently.

:beers:

**Comment by doncorsean** [comment]
Ok, thx Kevin
