### ISSUE TITLE
App Crash on  AFURLConnectionOperation.m line 168 +[AFURLConnectionOperation networkRequestThreadEntryPoint:]

### ISSUE THREAD

**Issue by rajeshsingh90** [AFNetworking/AFNetworking#2923]
Here is log:

0	libsystem_kernel.dylib	
__pthread_kill + 8
1
libsystem_pthread.dylib	
pthread_kill + 112
2
libsystem_c.dylib	
abort + 112
3
libsystem_malloc.dylib	
_nano_malloc_check_clear + 318
4
libsystem_malloc.dylib	
nano_free + 192
5
CoreFoundation	
__CFDataDeallocate + 44
6
CoreFoundation	
CFRelease + 328
7	libobjc.A.dylib	
(anonymous namespace)::AutoreleasePoolPage::pop(void*) + 564
8
CFNetwork	
-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 216
9
CFNetwork	
-[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 60
10
CFNetwork	
___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 104
11
CFNetwork	
___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 104
12
CFNetwork	
RunloopBlockContext::_invoke_block(void const*, void*) + 76
13
CoreFoundation	
CFArrayApplyFunction + 68
14
CFNetwork	
RunloopBlockContext::perform() + 136
15
CFNetwork	
MultiplexerSource::perform() + 312
16
CFNetwork	
MultiplexerSource::_perform(void*) + 68
17	CoreFoundation	
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
20	CoreFoundation	
CFRunLoopRunSpecific + 396
21
Foundation	
-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 316
22
Foundation	
-[NSRunLoop(NSRunLoop) run] + 96
23
TrulyMadly	
AFURLConnectionOperation.m line 168
+[AFURLConnectionOperation networkRequestThreadEntryPoint:]
24	Foundation	
__NSThread__main__ + 1072
25
libsystem_pthread.dylib	
_pthread_body + 164
26
libsystem_pthread.dylib	
_pthread_body + 158
27	libsystem_pthread.dylib	
thread_start + 4

**Comment by RodolfoAntonici** [comment]
+ 1

**Comment by biluncloud** [comment]
We have one too!

**Comment by monsterfx** [comment]
I have one too!

**Comment by tspecht** [comment]
Me too, Swift 2.0 Xcode 7 GM https://github.com/AFNetworking/AFNetworking/issues/2937

**Comment by ceetah** [comment]
has anyone solved this yet ?

**Comment by tspecht** [comment]
Please see the answer to my own question here: http://stackoverflow.com/questions/32496522/swift-2-0-random-exc-bad-access?noredirect=1#comment52853946_32496522

**Comment by kcharwood** [comment]
Keep in mind that's not the crashing thread, that is just  the entry point for the networking thread used by AFNetworking. You can reference #2301 for additional details.

**Comment by kcharwood** [comment]
We are also removing support for `AFURLConnectionOperation` in AFN 3.0.0. If you haven't already, I recommend migrating over to the `NSURLSession` based API's (`AFHTTPSessionManager`).

**Comment by tritter** [comment]
Could it be a memory limitation on the main thread which results in a crash when creating a new thread in that exact moment?

**Comment by xaphod** [comment]
I have 12 occurrences of this crash in one my iOS apps in production, with AFN 2.6.0 (pod). I use almost all AFHTTPSessionManager requests - I have just one HEAD request that's made via AFHTTPRequestOperation. See last png for thread 14, where AFURLConnectionOperation is visible.
Would be great to get a fix in 2.x series of AFN.

![stack trace-1](https://cloud.githubusercontent.com/assets/3776302/10968328/c6553be6-83c0-11e5-87fa-33da2427d668.png)
![stack trace-2](https://cloud.githubusercontent.com/assets/3776302/10968331/c9d8125c-83c0-11e5-914d-df0d4913c479.png)
![stack trace-3](https://cloud.githubusercontent.com/assets/3776302/10968337/cd0c803e-83c0-11e5-8437-4512e9b4ebb6.png)
![stack trace-4](https://cloud.githubusercontent.com/assets/3776302/10968338/cfbb1890-83c0-11e5-880e-b5272bdaf9db.png)

**Comment by kcharwood** [comment]
@xaphod The 3.0 line removes all references to `NSURLConnection`, so this issue is "fixed" there.

Now that 2.6.2, we are going to be shifting our focus to the 3.0.0 stream, which removes support for `NSURLConnection`.

 We are planning on only addressing critical security and stability issues in the 2.x branch going forward. If this becomes a widespread problem, it will be addressed.

:beers:

**Comment by jeffluon** [comment]
Hey, could you take look at my issue:
Application Specific Information:
<BKNewProcess: 0x15e6ff90; com.vocera.ent.vcsclinicalcoordinator.alpha; pid: 142; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x15e70ad0> id: 43-D195E7A8-B98F-4A4F-808F-BBB49FF379EF name: Background Content Fetching (11) process: <BKNewProcess: 0x15e6ff90; com.vocera.ent.vcsclinicalcoordinator.alpha; pid: 142; hostpid: -1> permittedBackgroundDuration: 30.000000 reason: backgroundContentFetching owner pid:43 preventSuspend  preventThrottleDownUI  preventIdleSleep  preventSuspendOnSleep 
)}

Elapsed total CPU time (seconds): 0.250 (user 0.250, system 0.000), 2% CPU 
Elapsed application CPU time (seconds): 0.005, 0% CPU

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib        	0x3141a474 mach_msg_trap + 20
1   libsystem_kernel.dylib        	0x3141a268 mach_msg + 36
2   CoreFoundation                	0x226d356e __CFRunLoopServiceMachPort + 142
3   CoreFoundation                	0x226d1b14 __CFRunLoopRun + 1012
4   CoreFoundation                	0x2261e1fc CFRunLoopRunSpecific + 472
5   CoreFoundation                	0x2261e00e CFRunLoopRunInMode + 102
6   GraphicsServices              	0x2a0ef1fc GSEventRunModal + 132
7   UIKit                         	0x25deaa04 UIApplicationMain + 1436
8   vocera-vcc-enterprise         	0x000d459e main (main.m:18)
9   libdyld.dylib                 	0x31363aac start + 0

Thread 1 name:  Dispatch queue: com.apple.libdispatch-manager
Thread 1:
0   libsystem_kernel.dylib        	0x3141a224 kevent64 + 24
1   libdispatch.dylib             	0x3134f0ec _dispatch_mgr_invoke + 276
2   libdispatch.dylib             	0x31343d36 _dispatch_mgr_thread + 34

Thread 2:
0   libsystem_kernel.dylib        	0x3141a474 mach_msg_trap + 20
1   libsystem_kernel.dylib        	0x3141a268 mach_msg + 36
2   vocera-vcc-enterprise         	0x002ddae4 exception_server_thread + 228
3   libsystem_pthread.dylib       	0x314abe20 _pthread_body + 136
4   libsystem_pthread.dylib       	0x314abd92 _pthread_start + 114
5   libsystem_pthread.dylib       	0x314a9b1c thread_start + 4

Thread 3 name:  AFNetworking
Thread 3:
0   libsystem_kernel.dylib        	0x3141a474 mach_msg_trap + 20
1   libsystem_kernel.dylib        	0x3141a268 mach_msg + 36
2   CoreFoundation                	0x226d356e __CFRunLoopServiceMachPort + 142
3   CoreFoundation                	0x226d1b14 __CFRunLoopRun + 1012
4   CoreFoundation                	0x2261e1fc CFRunLoopRunSpecific + 472
5   CoreFoundation                	0x2261e00e CFRunLoopRunInMode + 102
6   Foundation                    	0x23388138 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 260
7   Foundation                    	0x233d6220 -[NSRunLoop(NSRunLoop) run] + 76
8   MyApp       	0x00268f06 +[AFURLConnectionOperation networkRequestThreadEntryPoint:] (AFURLConnectionOperation.m:189)
9   Foundation                    	0x2344d3b6 __NSThread__main__ + 1114
10  libsystem_pthread.dylib       	0x314abe20 _pthread_body + 136
11  libsystem_pthread.dylib       	0x314abd92 _pthread_start + 114
12  libsystem_pthread.dylib       	0x314a9b1c thread_start + 4
