### ISSUE TITLE
 Crash in AFHTTPRequestOperation.m (line 123) EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x0000000000000010 

### ISSUE THREAD

**Issue by suhitp** [AFNetworking/AFNetworking#2924]
Hi, just submitted the app in the app store and getting a lot of crashes (level 5 in crashlytics). I am using AFNetworking for all network requests.
mainly the crashes on iOS8 (83%) 

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x0000000000000010

AFHTTPRequestOperation.m line 123
__64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke_3

based on the logs i feel it's happening because the completion block is being accessed after it is deallocated. 

<img width="971" alt="crash_afnetworking1" src="https://cloud.githubusercontent.com/assets/6196402/9518199/9783b722-4cd2-11e5-8542-0074e26b1c13.png">

hard to reproduce while testing but happening regularly, can someone please suggest what is causing this issue or any improvement.

**Comment by istx25** [comment]
Did you find a solution, @suhitp?

**Comment by suhitp** [comment]
@istx25 No I am still searching for the solution

**Comment by andreitr** [comment]
Did you find a solution, @suhitp?

**Comment by suhitp** [comment]
@andreitr no still facing the issue

**Comment by andreitr** [comment]
As it turned out my issue was caused by iOS 9, full answer here http://stackoverflow.com/questions/32918430/getting-nsinvalidargumentexception-on-ios-8-0-afnetworking-2-6-0-xcode-7-0-1

**Comment by suhitp** [comment]
Figured out the solution, AFNetworking was returning correctly to the failure block, but the completion block is deallocated hence it was crashing, by just putting if(failureBlock) check resolved the issue.

**Comment by Amindv1** [comment]
What version of AFNetworking was this fixed with?
