### ISSUE TITLE
Second session task won't start if `tasks` methods were used in NSURLSessionTaskDelegate block

### ISSUE THREAD

**Issue by DanSkeel** [AFNetworking/AFNetworking#2927]
Sorry, I can't get what's going on here, but I made a test that is failing and showing the problem.
Second task just never finishes if you call `tasks` in `TaskDidCompleteBlock`. I guess it somehow related to semaphores that are used to synchronously get tasks, but I'm not sure.

You can insert this test for example in the end of `AFHTTPSessionManagerTests.m`

``` objectivec
- (void)testNonHangingOnAccessingTasksInTaskDidCompleteBlock {
    [self.manager setTaskDidCompleteBlock:^(NSURLSession *session, NSURLSessionTask *task, NSError *error) {
        self.manager.tasks;  // try to comment it and test will finish successfully
    }];

    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:@"/get" relativeToURL:self.baseURL]];
    __block NSURLSessionDataTask *secondTask;
    NSURLSessionDataTask *task = [self.manager dataTaskWithRequest:request completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
        secondTask = [self.manager dataTaskWithRequest:request completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
        }];
        [secondTask resume];
    }];
    [task resume];

    expect(task.state).will.equal(NSURLSessionTaskStateCompleted);  // is ok
    expect(secondTask.state).will.equal(NSURLSessionTaskStateCompleted);  // fails
}
```

Latest commit that failed to pass this test [64500e8]

**Comment by kcharwood** [comment]
Interesting. It is somehow hanging on the dispatch_semaphore_wait.

```
- (NSArray *)tasksForKeyPath:(NSString *)keyPath {
    __block NSArray *tasks = nil;
    dispatch_semaphore_t semaphore = dispatch_semaphore_create(0);
    [self.session getTasksWithCompletionHandler:^(NSArray *dataTasks, NSArray *uploadTasks, NSArray *downloadTasks) {
        if ([keyPath isEqualToString:NSStringFromSelector(@selector(dataTasks))]) {
            tasks = dataTasks;
        } else if ([keyPath isEqualToString:NSStringFromSelector(@selector(uploadTasks))]) {
            tasks = uploadTasks;
        } else if ([keyPath isEqualToString:NSStringFromSelector(@selector(downloadTasks))]) {
            tasks = downloadTasks;
        } else if ([keyPath isEqualToString:NSStringFromSelector(@selector(tasks))]) {
            tasks = [@[dataTasks, uploadTasks, downloadTasks] valueForKeyPath:@"@unionOfArrays.self"];
        }

        dispatch_semaphore_signal(semaphore);
    }];

    dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);

    return tasks;
}
```

**Comment by kcharwood** [comment]
It looks like the completion block is being called on the same thread that `getTasksWithCompletionHandler` needs to run and grab all the tasks. Since we are blocking with `dispatch_semaphore_wait`, that causes a deadlock.

If you `dispatch_async`out of the completion block, it should work fine.

**Comment by kcharwood** [comment]
Now the question is should we be [dispatching out to the main queue for the `taskDidCompleteBlock`?](https://github.com/AFNetworking/AFNetworking/blob/3.0.0-beta.1/AFNetworking/AFURLSessionManager.m#L1021) We currently aren't changing the queue for any of those delegate callbacks, so I'm not sure what the best way forward here is.

thoughts @kylef @jshier @cnoon ?

**Comment by kcharwood** [comment]
Btw I've modified the test in the 3.0 branch. This test shows the problem:

```Objective-C
- (void)testNonHangingOnAccessingTasksInTaskDidCompleteBlock {
    [self.manager setTaskDidCompleteBlock:^(NSURLSession *session, NSURLSessionTask *task, NSError *error) {
       self.manager.tasks;  // try to comment it and test will finish successfully
    }];

    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:@"/get" relativeToURL:self.baseURL]];
    __block NSURLSessionDataTask *secondTask;
    NSURLSessionDataTask *task = [self.manager dataTaskWithRequest:request completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
        secondTask = [self.manager dataTaskWithRequest:request completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
        }];
        [secondTask resume];
    }];
    [task resume];

    NSPredicate *predicate = [NSPredicate predicateWithFormat:@"state==%d", NSURLSessionTaskStateCompleted];
    [self expectationForPredicate:predicate evaluatedWithObject:task handler:nil];
    [self waitForExpectationsWithCommonTimeoutUsingHandler:nil];
    [self expectationForPredicate:predicate evaluatedWithObject:secondTask handler:nil];
    [self waitForExpectationsWithCommonTimeoutUsingHandler:nil];

}
```

**Comment by cnoon** [comment]
Is there any particular reason this method is synchronous to begin with? You're forcing an async call to be synchronous which is probably the majority of the problem. Additionally, I've seen that `getTasks` call take a while to resolve, so I don't know that having a synchronous API around it is wise. Since 3.0 has not yet been released, it would probably be good to think through this avenue first.

If modifying to an async API is not possible, then you probably just need to `dispatch_async` on the `dispatch_semaphore_signal`, but it sounds like you've worked through that already. 👍🏼

As for the final question of dispatching the task completion, I feel like that is a fair trade-off. If it was something that occurred as often as say a progress update, I would hesitate. But since it's not and it's something that is only called in the event of a request completing, I'd say it should be sufficient to dispatch to the main queue without any performance issues.

That's my take, really interested to see what @kylef and @jshier think on this one. I don't have nearly the background in AFN to say for sure, but those are my observations at least. Hopefully that helps some...

**Comment by kcharwood** [comment]
I'm assuming the reason they are synchronous is purely to be "handy". If we were to make them async, then you might as well use the method already provided by NSURLSession.

Interested in @kylef and @jshier's take.
