### ISSUE TITLE
Dispatching success/failure blocks in "http_request_operation_processing_queue" breaks ordering when using maxConcurrentOperationCount=1 for operation queue

### ISSUE THREAD

**Issue by manuyavuz** [AFNetworking/AFNetworking#2929]
Hi, 

When an AFHTTPRequestOperation completes, it dispatches the task of calling success/failure blocks into `http_request_operation_processing_queue()` queue which is a concurrent queue by default. 

I need to assure that success/failure blocks of the requests will be called exactly the same order with operations' start order. I can guarantee the process order of requests via setting `requestManager.operationQueue.maxConcurrentOperationCount=1`. However, call order of success/failure blocks happens to be broken in edge cases because `http_request_operation_processing_queue()` works concurrently.

I can set `completionGroup` and `completionQueue` myself, but in this case in need to set `http_request_operation_processing_queue` which is currently not possible.

Is there any workaround for this?

Thanks

**Comment by kcharwood** [comment]
Hi @manuyavuz,

Would you be able to create a test demonstrating the issue so I can look into it more? Thanks!

**Comment by manuyavuz** [comment]
Hi @kcharwood,

I'll add two test cases one demonstrating the fail scenario, other fixes it via using a serial queue, and let you know.

Thanks

**Comment by manuyavuz** [comment]
Hey @kcharwood,

I've added two test cases to #2935 demonstrating the issue. They pass on my machine (I'm using Xcode 7 GM and tried at least 40 times), however, one of them fails on travis CI. I can't catch the reason of failure, I guess it might result from travis using Xcode 6.4 (my guess).

Could you look for the tests and try to run on your machine? If it also fails on yours, I'll try to find the reason.

Thanks!

**Comment by kcharwood** [comment]
closed via conversation in #2935
