### ISSUE TITLE
Use of undeclared identifier 'AFNetworkActivityIndicatorManager'

### ISSUE THREAD

**Issue by y0unghe** [AFNetworking/AFNetworking#2931]
I install AFNetworking using pods. And when I try to do `[[AFNetworkActivityIndicatorManager sharedManager] setEnabled:YES];`
I am getting `Use of undeclared identifier 'AFNetworkActivityIndicatorManager'`.
What's wrong?

**Comment by CyberMew** [comment]
Did you include the file?

**Comment by y0unghe** [comment]
Right.
