### ISSUE TITLE
EXC_BAD_ACCESS when using iOS 9 with Xcode 7 Beta 6

### ISSUE THREAD

**Issue by tspecht** [AFNetworking/AFNetworking#2937]
Hi guys,

I switched to the newest Xcode and iOS 9 betas today and I'm receiving reproducible crashes while using AFNetworking. The crash occurs in AFURLConnectionOperation.m line 154 with EXC_BAD_ACCESS, apparently an NSURLRequest is being overreleased: *** -[NSMutableURLRequest release]: message sent to deallocated instance 0x7fa96d2c12f0.
 Any ideas on how to fix that?

**Comment by tspecht** [comment]
I'm still experiencing this issue with the Xcode GM from last night...Anyone else experiencing this?

**Comment by hatemalimam** [comment]
Another [Question](http://stackoverflow.com/questions/32496522/swift-2-0-random-exc-bad-access) regarding this issue, might help in the feature...

**Comment by tspecht** [comment]
Yeah thats mine ;) Haven't had any response here in more than a week so I hoped someone on Stackoverflow could help me ...

**Comment by hatemalimam** [comment]
You are alone after all :)

**Comment by kcharwood** [comment]
Are you still seeing this issue in the GM today?

**Comment by tspecht** [comment]
Yes indeed, just tried again.

**Comment by ceetah** [comment]
has anyone solved this yet ?

**Comment by tspecht** [comment]
http://stackoverflow.com/questions/32496522/swift-2-0-random-exc-bad-access?noredirect=1#comment52853946_32496522

**Comment by kcharwood** [comment]
Can you provide a sample project that demonstrates this problem? I'm not sure where else to look since I can't reproduce it directly.

Thanks!

**Comment by linshaolie** [comment]
刺vyvvvyvyvvvvvvyvvvvvv、一个人了、vyvvvv

**Comment by linshaolie** [comment]
vvv

**Comment by kcharwood** [comment]
Now that 2.6.2, we are going to be shifting our focus to the 3.0.0 stream, which removes support for `NSURLConnection`.

 We are planning on only addressing critical security and stability issues in the 2.x branch going forward. If this becomes a widespread problem, it will be addressed.

:beers:
