### ISSUE TITLE
UIImageView setting sharedImageCache

### ISSUE THREAD

**Issue by casey55** [AFNetworking/AFNetworking#2939]
What are other people using as a NSCache replacement for UIImageViews instead of the default AFImageCache?

I'm wanting a cache that will not purge when app enters the background. I'm currently trying out OSCache by Nick Lockwood. https://github.com/nicklockwood/OSCache.  After adding the protocols needed by AFImageCache, it seems to be what I need.  

What are others experience with setting your own image cache on UIImageView?

**Comment by Coody** [comment]
Tye this:
