### ISSUE TITLE
Nullable and Swift

### ISSUE THREAD

**Issue by georgbachmann** [AFNetworking/AFNetworking#2940]
I just did a pod update and got a compiler error in my swift code. The method I am using is the following:

    - (NSURLSessionDownloadTask *)downloadTaskWithRequest:(NSURLRequest *)request
                                                 progress:(NSProgress * __nullable __autoreleasing * __nullable)progress
                                              destination:(nullable NSURL * (^)(NSURL *targetPath, NSURLResponse *response))destination
                                        completionHandler:(nullable void (^)(NSURLResponse *response, NSURL *filePath, NSError *error))completionHandler;

And in my swift code I'd like to check if the error is present. I do so by asking `(error == nil)`. As the error is not declared `__nullable ` the compiler doesn't like that... 

I guess that's a bug, right? I guess other methods will also be affected?

Thanks,
Georg

**Comment by ZuYuanZhou** [comment]
I got the same problem, I think `error ` should be marked as `__nullable` also

**Comment by kylef** [comment]
This has been fixed by #2911.
