### ISSUE TITLE
AFImageCache truncated

### ISSUE THREAD

**Issue by wscheper** [AFNetworking/AFNetworking#2942]
When my app goes to the background it seems that the AFImageCache gets emptied. It makes new requests for the images.

I'm using NSURLRequestReturnCacheDataElseLoad; policy when creating a request in setImageWithURL: url placeholderImage:placeholderImage

Cache details:
NSURLCache *sharedCache = [[NSURLCache alloc] initWithMemoryCapacity:5 * 1024 * 1024
                                                            diskCapacity:200 * 1024 * 1024
                                                                diskPath:nil];

There is also no memory warning.

How can I make sure the images get persisted so that they are still available the next time the app starts up?

**Comment by casey55** [comment]
For UIImageViews

One way is to use a replacement cache for AFImageCache, that does not evict images when going to the background.  See my post https://github.com/AFNetworking/AFNetworking/issues/2939

You create your AFImageCache replacement, in my case OSCache, then set that as your shared image cache for UIImageView
    OSCache *osCache = [OSCache new];
    [UIImageView setSharedImageCache:osCache];

**Comment by wscheper** [comment]
@casey55 Could you expand on this how I replace AFImageCache for OSCache?

**Comment by casey55** [comment]
Include OSCache in your project.  https://github.com/nicklockwood/OSCache

In your app delegate didFinishLaunchingWithOptions, or somewhere else you prefer.  Tell UIImageView to use a different shared image cache.

OSCache *osCache = [OSCache new];
[UIImageView setSharedImageCache:osCache];

That is all.

**Comment by wscheper** [comment]
I had to adapt the OSCache to the AFImageCache protocol, but that was it. Thank you.

How about persisting when terminating the app?

**Comment by kcharwood** [comment]
Take a look at the 3.0.0 branch. We have a new caching architecture that we brought over from `AlamofireImage`. I think this will help solve this problem nicely. We are no longer subclassing NSCache and are in more control of when items are purged.
