### ISSUE TITLE
AFNetworking NS_ASSUME_NONNULL_BEGIN error

### ISSUE THREAD

**Issue by neerajcsa** [AFNetworking/AFNetworking#2943]
I am getting this error when i include AFNetworking framework manually in Xcode 6.4 
unknown type name 'NS_ASSUME_NONNULL_BEGIN'
NS_ASSUME_NONNULL_BEGIN

**Comment by rasika-marne** [comment]
I also have same issue.....

**Comment by YuaShizuki** [comment]
I got this same issue 2

**Comment by kylef** [comment]
AFNetworking 2.6 introduces nullability annotations, these will depend on a modern version of Xcode 6 or Xcode 7. I would suggest you upgrade to Xcode 7 which supports these nullability annotations or use an older version of AFNetworking such as 2.5.4.
