### ISSUE TITLE
Localizable string

### ISSUE THREAD

**Issue by francoismart** [AFNetworking/AFNetworking#2947]
Hello
I have these errors when not using my request API correctly
"Localizable string "Request failed: unacceptable content-type: %@" not found in strings table "AFNetworking"
I would like to catch this in french, spanish, etc ....
How/Where can I do this ? 
Have a nice day
Francois

**Comment by kylef** [comment]
I think the best way would be to catch AFNetworking's errors and create a user-friendly localised error and show that to the user instead.
