### ISSUE TITLE
Support client side certificates

### ISSUE THREAD

**Issue by therealx** [AFNetworking/AFNetworking#2951]
I was unable to find any documentation or code relating to supporting client side certificates (not certificate pinning).  Would love to have support for this, and apologies if I missed it somewhere.

**Comment by kcharwood** [comment]
We don't support that at the moment. Do you have any examples of other libraries/languages that have implemented the feature? Would be interested in reading up on it.

Also, if you have ideas on how it could fit into AF, we would love to hear them!

**Comment by therealx** [comment]
Here's a good example here: http://oso.com.pl/?p=207&lang=en

**Comment by geekerzp** [comment]
Here's also a python example https://www.safaribooksonline.com/library/view/python-cookbook-2nd/0596007973/ch15s12.html :)

**Comment by docmato** [comment]
+1

**Comment by wing328** [comment]
+1

**Comment by aklee** [comment]
why！！ i need it!!

**Comment by fanxiaofan** [comment]
static id AFPublicKeyForCertificate(NSData *certificate) {
    id allowedPublicKey = nil;
    SecCertificateRef allowedCertificate;
    SecCertificateRef allowedCertificates[1];
    CFArrayRef tempCertificates = nil;
    SecPolicyRef policy = nil;
    SecTrustRef allowedTrust = nil;
    SecTrustResultType result;
    allowedCertificate = SecCertificateCreateWithData(kCFAllocatorDefault, (__bridge CFDataRef)certificate);
***********************************************************************************************
if certificate‘s data not come from der-encoded certificate, allowedCertificate will always NULL,and allowedPublicKey will be NULL too. AFSSLPinningModePublicKey mode will never evaluate true. How to reslove this problem ?

**Comment by cnoon** [comment]
Anybody have any idea how to do this on non-deprecated APIs? I can't find anyway that this is supported in the `NSURLSession` docs.

**Comment by cnoon** [comment]
Okay, spoke a bit too soon. I wonder if this could be implemented by creating an `NSURLCredential` using the [init(identity:certificates:persistence)](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLCredential_Class/#//apple_ref/occ/instm/NSURLCredential/initWithIdentity:certificates:persistence:) initializer. From what I can tell, this would be initializing client certs to send back to the server. Does everyone else have the same understanding? Does anyone know of any public servers we could test this theory against?

**Comment by therealx** [comment]
I don't know of a public server, but I'd be glad to test on our private ones and help debug if it furthers the cause.

**Comment by jshier** [comment]
Client certificates can be handled by assigning an `NSURLCredential`. I suggest reading [this thread] for more details.
