### ISSUE TITLE
Can not send JSON data to server since 2015.09.08

### ISSUE THREAD

**Issue by tianye2856** [AFNetworking/AFNetworking#2955]
Hi,
   Today we find that all JSON data with HTTPS can not be send to our server using AFNetworking for both iOS 7.x and iOS 8.x, and this problem happens since today and we have not changed anything in our online iOS App version and our server. Others also find this problem. The old 1.x version for AFNetworking works well, but the latest version from 2015.08 does not work any more. It seems that Apple has changed something about network.
Code is this

AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
        NSDictionary *parameters = @{kEmailKey: @"tianye2856@hotmail.com",
                                     kPhoneNumberKey: @"+8617717370925",
                                     kPasswordKey: @"123456",
                                     kAppNameKey: @"GiftMaker",
                                     kAppVersionKey: @"3.0.0",
                                     kPlatformKey: @"iOS",
                                     kSignKey: @"mac",
                                     kSigKeyVersionKey: @"1.0.2"};
        [manager POST:@"https://api.ttstmm.com/v1/accounts/login" parameters:parameters success:^(AFHTTPRequestOperation *operation, id responseObject) {
            NSLog(@"Response: %@", responseObject);
            
        } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
            NSLog(@"JSON: %@", operation.responseObject);
            
            NSLog(@"status code  :%ld",(long)[operation.response statusCode]);
            NSLog(@"Failure Response %@, %@", error, operation.response.description);
            
        }];

The error message is 

2015-09-08 23:25:47.838 AFNetworking iOS Example[2259:57719] JSON: (null)
2015-09-08 23:25:47.838 AFNetworking iOS Example[2259:57719] status code  :0
2015-09-08 23:25:56.633 AFNetworking iOS Example[2259:57719] Failure Response Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)" UserInfo=0x7f8a82680d00 {NSErrorFailingURLKey=https://api.ttstmm.com/v1/accounts/login, NSErrorFailingURLStringKey=https://api.ttstmm.com/v1/accounts/login}, (null)

   This is not a network error since we have used all kind of VPN, the IP address contains US/CN/HK address. Our server have not received any message since the last few hours, it is really strange because all works well until today, our online App Store version has not been changed.
   Please help us immediately, thanks in advance.

**Comment by gwynantj** [comment]
So the error code for that response is `kCFURLErrorUserCancelledAuthentication`? 

From the documentation it is: `kCFURLErrorUserCancelledAuthentication The connection failed because the user cancelled required authentication.`

So it looks like somewhere the authentication challenge is getting cancelled.

Maybe you should ask on StackOverflow since that's where these types of questions are best asked?

**Comment by gwynantj** [comment]
Also I suspect this is a certificate issue since your certificate is not signed by a know authority. See screenshot below:

![screen shot 2015-09-08 at 16 57 50](https://cloud.githubusercontent.com/assets/2777576/9740088/d54cdf9e-564a-11e5-9a09-c77760cac4e0.png)

**Comment by tianye2856** [comment]
Our certificate is signed by a third certificate organization.
   AFNetworking 1.x works well but 2.x fail to work only from today.

**Comment by gwynantj** [comment]
AFNetworking 1.x shouldn't work unless you've turned on `allowsInvalidSSLCertificate`.

Basically that certificate is invalid until you add it as a pinned certificate.

**Comment by tianye2856** [comment]
YES, you are correct. 1.x works using allowsInvalidSSLCertificate. So how could we solve this problem now on 2.x?

**Comment by tianye2856** [comment]
allowsInvalidSSLCertificate does not work on 2.x, do I need to sign my certificate using VeriSign or other famous organization?

**Comment by gwynantj** [comment]
It's not recommended to have `allowsInvalidSSLCertificate` turned on at all. (This should only be used for internal environments for testing purposes)

For production deployments you need a known certificate authority, like VeriSign or various other companies that sell SSL certificates.

**Comment by tianye2856** [comment]
Really strange, it works now.

**Comment by gwynantj** [comment]
Yes it would since the certificate seems to be valid now.

![screen shot 2015-09-09 at 09 28 31](https://cloud.githubusercontent.com/assets/2777576/9756895/2ce85d5c-56d5-11e5-99eb-b5da29afeab8.png)

I think it's safe to say we can close this issue!
