### ISSUE TITLE
image not loading fron url

### ISSUE THREAD

**Issue by kakkuk** [AFNetworking/AFNetworking#2956]
hi, itryed meny times but this kind of image not loading
http://www.1-dk.cn/?m=thumb&url=image@3@20150827@20150827180629_30017.jpg&w=150&h=150

this is code: [cell.dataThumb setImageWithURL:[NSURL URLWithString:@"http://www.1-dk.cn/?m=thumb&url=image@3@20150827@20150827180629_30017.jpg&w=150&h=150"]placeholderImage:[UIImage imageNamed:@"holder.png"]];

**Comment by kcharwood** [comment]
This question is better suited for stackoverflow.

Github is for reporting issues and feature requests!

Thanks! :beers:
