### ISSUE TITLE
'pod lib lint' with AFNetworking ~> 2.5 dependency

### ISSUE THREAD

**Issue by jaskooo** [AFNetworking/AFNetworking#2960]
I am using AFNetworking as a dependency in my .podspec. When i want to verify my podspec for pushing trunk up to cocoapods i am getting this error:

```
: fatal error: 'AFHTTPSessionManager.h' file not found

Pods project available at /var/folders/lm/7pcgczhs01gbyz89p7p63r3c0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj for inspection.
```

When i open `Pods.xcodeproj` for inspection there is only `AFNetworking.h` in `Pods/AFNetworking/` folder.

Do you have any ideas what could happened?

**Comment by istx25** [comment]
Try deleting your pods directory and attempting to fetch all of your dependencies again.
