### ISSUE TITLE
iOS 9 deprecates some APIs in NSURLConnection

### ISSUE THREAD

**Issue by liuxuan30** [AFNetworking/AFNetworking#2961]
iOS 9 mentions there is some APIs to be deprecated:
The NSURLConnection API in the Foundation framework. Use NSURLSession APIs instead.
Here's the link what will be deprecated:
https://developer.apple.com/library/prerelease/tvos/documentation/Cocoa/Reference/Foundation/Classes/NSURLConnection_Class/

I see AFNetworking is using those. I tried search in issues, seems no one bring it up. Will it be updated when iOS 9 launches?

**Comment by kcharwood** [comment]
NSURLConnection based API's will be removed in a future release. It is recommended you move to the URLSession based classes, and away from the URLConnection based classes. In AFNetworking, that means moving over to the AFHTTPSessionManager class.

**Comment by jeffpearce** [comment]
That's the documentation for tvOS. Nothing is deprecated in iOS 9 that I could see.

I've been testing our product (OneDrive for iOS) on iOS 9, and AFNetworking seems to be working fine.

In general, deprecated doesn't mean gone - it means going away in a release or two. It needs to be taken care of, but isn't usually urgent.

**Comment by kcharwood** [comment]
Apple indicated at WWDC that is 'soft' deprecated. It's not going away because there is so much code written already using it, but they recommended all new code written be done so with NSURLSession. All new networking features and optimization will only be applied to NSURLSession going forward.

In an effort to keep this library maintainable going forward, we will be removing support for NSURLConnection in a future release.

**Comment by istx25** [comment]
I would be interested in contributing to the adoption of `NSURLSession` in AFNetworking. When are you looking to start the transition away from NSURLConnection in existing classes?

**Comment by kcharwood** [comment]
All of the support is already in the core library. The major work left is moving the UIKit extensions over to NSURLSession from NSURLConnection.

**Comment by istx25** [comment]
:+1: I'll take a look.

**Comment by liuxuan30** [comment]
@jeffpearce here's the general link:https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html#//apple_ref/doc/uid/TP40016198-SW1

I paste another one. But all of them point out The NSURLConnection API in the Foundation framework. Use NSURLSession APIs instead.
