### ISSUE TITLE
Xcode 7 / iOS 9: error not set in setTaskDidCompleteBlock when call fails

### ISSUE THREAD

**Issue by drdaz** [AFNetworking/AFNetworking#2963]
I've run into differing behaviour in Xcode 6 + iOS 8 / Xcode 7 + iOS 9 with regard to setTaskDidCompleteBlock.

Under Xcode 6, if the download task fails with a 404 error, the block is invoked with an error assigned to the error variable. Under Xcode 7, the error is nil. This is presumably not by design.

EDIT: Oh, I'm using Cocoapods release 2.5.4.

**Comment by kcharwood** [comment]
Hi @drdaz 

We have a test that looks at this specific case, and it's currently passing:

https://github.com/AFNetworking/AFNetworking/blob/cf78b03e9fea1dcdb1222ad491c0d94bea185e89/Tests/Tests/AFHTTPSessionManagerTests.m#L59

Let me know if you are able to cause that test to fail. Thanks!

**Comment by Coeur** [comment]
Strangely, I got the same issue on Xcode 7.2.1. So to workaround it, I've overridden those methods for the same effect:

    - (void)addDelegateForDataTask:(NSURLSessionDataTask *)dataTask
                 completionHandler:(void (^)(NSURLResponse *response, id responseObject, NSError *error))completionHandler;
    - (void)addDelegateForUploadTask:(NSURLSessionUploadTask *)uploadTask
                            progress:(NSProgress * __autoreleasing *)progress
                   completionHandler:(void (^)(NSURLResponse *response, id responseObject, NSError *error))completionHandler;
    - (void)addDelegateForDownloadTask:(NSURLSessionDownloadTask *)downloadTask
                              progress:(NSProgress * __autoreleasing *)progress
                           destination:(NSURL * (^)(NSURL *targetPath, NSURLResponse *response))destination
                     completionHandler:(void (^)(NSURLResponse *response, NSURL *filePath, NSError *error))completionHandler;

**Comment by Coeur** [comment]
@kcharwood, the issue is unrelated to the test you are showing. We are talking about `setTaskDidCompleteBlock:` from AFURLSessionManager.
