### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by born2pun** [AFNetworking/AFNetworking#2966]
Xcode 6.4

I tend to set fairly strict build settings so when I added AFNetworking to a project then I got some errors that were fixed by explicitly casting integer values:

AFURLConnectionOperation.m
	-[AFURLConnectionOperation initWithCoder:]: self.state = (AFOperationState)...

AFURLRequestSerialization.m
	-[AFURLRequestSerializer initWithCoder:]: self.queryStringSerializationStyle = (AFHTTPRequestQueryStringSerializationStyle)...
	-[AFPropertyListRequestSerializer initWithCoder:]: self.format = (NSPropertyListFormat)...

AFURLResponseSerialization.m
	-[AFURLResponseSerializer initWithCoder:]: self.format = (NSPropertyListFormat)...

Also I'm using C++ in the project so I have the compiler set to Obj-C++, which triggered errors due to using the C++ keyword "class" as a parameter name that were fixed by renaming to theClass:

AFURLSessionManager.m
	af_swizzleSelector(Class theClass, ...
	af_addMethod(Class theClass, ...
	+[_AFURLSessionTaskSwizzling swizzleResumeAndSuspendMethodForClass:(Class)theClass ...

**Comment by kcharwood** [comment]
Feel free to push these up in a PR!

Thanks!

Kevin
