### ISSUE TITLE
Pragma directives in UIKit categories causing compiler errors

### ISSUE THREAD

**Issue by ryanthon** [AFNetworking/AFNetworking#2968]
I'm not sure how I haven't seen anyone else run into this problem, but I'm getting compiler errors in Xcode 7 with some of the UIKit categories complaining about #pragma directives:

Example:
UIActivityIndicatorView+AFNetworking - line 138, 139, 141
"Embedding a #pragma directive within macro arguments is not supported"

Is this a known issue or is it just me? I couldn't find any other issue describing this problem.

**Comment by sumitmorey** [comment]
Hello,

Did you found any solution?

**Comment by ryanthon** [comment]
Nope. I just commented them out for now.

**Comment by kcharwood** [comment]
What version of Xcode are you using?

**Comment by roycableshine** [comment]
I have the same issue.

- Xcode 7.0.1
- Targeting iOS 7.1 Builds, with iOS 9 SDK.

**Comment by roycable** [comment]
I have the same issue.

Xcode 7.0.1
Targeting iOS 7.1 Builds, with iOS 9 SDK.

**Comment by peiyun007** [comment]
pragma can not embeded in macro,so you have to move pragma outside the macro

**Comment by roycable** [comment]
Here's a quick update to my original post (9 days ago, 13th October, 2015);

I upgraded the project I was working on to use Cocoapods, and the errors are no longer.

So instead of manually moving the framework into my folder, I let pods do it for me.

**Comment by scalessec** [comment]
Fwiw, I'm still seeing this in Xcode 7.3 (we don't use Cocoapods). I had to comment out all the #pragma directives manually.

**Comment by scalessec** [comment]
It's worth noting though that just moving the `#pragma` directives out of the `dispatch_async` blocks also works.

**Comment by devanshu2** [comment]
I am having same kind of issue on my new xcode 8
can anybody help
refer attached screenshot
<img width="996" alt="screen shot 2016-09-15 at 12 34 20 pm" src="https://cloud.githubusercontent.com/assets/1206072/18541129/dc8fde3e-7b40-11e6-87b4-90763fdd6a7c.png">
