### ISSUE TITLE
There should be a way to remove an image from the cache

### ISSUE THREAD

**Issue by dmelgar** [AFNetworking/AFNetworking#2969]
Fairly common scenario, someone uses an app to change an image that is already stored on the server.

Currently there is no way without forking and modifying AFNetworking to remove the image from the cache to force a reload of the new image. In my case, this has forced me to disable caching altogether.

**Comment by kcharwood** [comment]
Check out our 3.0.0 branch. We provide support for removing specific images.

Thanks!
