### ISSUE TITLE
AFNetworkReachabilityManager doesn't post which instance of itself is posting the notification.

### ISSUE THREAD

**Issue by donileo** [AFNetworking/AFNetworking#2970]
Hey guys is there any reason AFNetworkReachabilityManager doesn't post the sending object  in AFNetworkingReachabilityDidChangeNotification? Due to it not doing this theres no way to easily differentiate between the AFNetworking reachability manager posting and any other instances of AFNetworkReachabilityManager that I may instantiate for my own classes.

Also I am seeing weird behaviors such as multiple notifications coming when only should.

**Comment by mobitar** [comment]
As an alternative, you might be able to try using the block callback instead of notifications for reachability changes:

On `AFNetworkReachabilityManager`:
```
- (void)setReachabilityStatusChangeBlock:(nullable void (^)(AFNetworkReachabilityStatus status))block;```

**Comment by phoney** [comment]
I don't see any reason why self isn't passed for the object when that notification is posted. 

Having said that, I've always just used the singleton shared reachability manager in my code. I'm not sure what use case requires more than one instance.
