### ISSUE TITLE
AFNetworking 2.6.0 Cocoapods Mac undefined symbols

### ISSUE THREAD

**Issue by ghoover** [AFNetworking/AFNetworking#2976]
After upgrading to 2.6.0 via Cocoapods I get undefined errors for any AFNetworking classes I import.  If I set my podfile back to 2.5.4, the install proceeds just fine.  What I noticed is that with 2.6.0, the Pods-AFNetworking.xcconfig file is not generated and therefore not included in my Pods-MyApplication Mac.xcconfig file.

Didn't find anything in the release notes that spelled this out but I may have missed something.

**Comment by tvillafane** [comment]
I had the same issue and reverting back to 2.5.4 fixed it.

**Comment by kcharwood** [comment]
I was just able to successfully install it in an iOS and Mac app. I would expect to hear more widespread problems if this was an issue with the podfile. Are you able to install in other projects on your machine?

**Comment by tvillafane** [comment]
No, I actually accidentally updated my podfile in another app and AFNetworking threw me an error until I reverted back to 2.5.4.
