### ISSUE TITLE
Error at version 2.6.0

### ISSUE THREAD

**Issue by MQTAN** [AFNetworking/AFNetworking#2977]
![snip20150914_1](https://cloud.githubusercontent.com/assets/12954047/9849734/16d671bc-5b20-11e5-8074-97dda96c242c.png)
Could you help me?

**Comment by kcharwood** [comment]
Please read the changelog for 2.6 with the note about using the library without installing via cocoapods.

You can also see this [issue](https://github.com/AFNetworking/AFNetworking/issues/2901)
