### ISSUE TITLE
Issue with uploading multiple images

### ISSUE THREAD

**Issue by subinrevi** [AFNetworking/AFNetworking#2978]
Hi,
     Following is my code for uploading multiple images. Where should i provide the request headers ?

   __block int i=1;
             AFHTTPRequestOperationManager *manager = [[AFHTTPRequestOperationManager alloc] initWithBaseURL:[NSURL URLWithString:url]];
             NSDictionary *parameters = @{@"wave_Id": [inputDictionary objectForKey:@"wave_Id"]};
             AFHTTPRequestOperation *op = [manager POST:url parameters:parameters constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
                 
                 for(NSData *imageData in [inputDictionary objectForKey:@"images"])
                 {
                     [formData appendPartWithFileData:imageData name:[NSString stringWithFormat:@"file%d",i] fileName:[NSString stringWithFormat:@"abc%d.png",i] mimeType:@"image/png"];
                     i++;
                 }
                 NSError *error;
                 NSData *jsonData = [NSJSONSerialization dataWithJSONObject:parameters options:0 error:&error];
                 NSAssert(jsonData, @"Failure building JSON: %@", error);
                 NSLog(@"Json Data Image Upload %@",jsonData);
                 NSAssert(jsonData, @"Failure building JSON: %@", error);
                 NSString *token = [SSKeychain passwordForService:RegistrationTokenKey account:LoggedInUserKey];

                 NSDictionary *jsonHeaders = @{@"Content-Disposition" : @"form-data; name=\"parameters\"",
                                               @"Content-Type"        : @"application/json",
                                               @"Accept"              : @"application/json",
                                               @"Authorization"       : token};
                 [formData appendPartWithHeaders:jsonHeaders body:jsonData];
                 
             } success:^(AFHTTPRequestOperation *operation, id responseObject) {
                 NSLog(@"Success: %@ ***** %@", operation.responseString, responseObject);
             } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
                 NSLog(@"Error: %@ ***** %@", operation.responseString, error);
             }];
             [op start];

**Comment by kcharwood** [comment]
Hi @subinrevi,

Questions like these are best suited for StackOverflow. Github is for reporting issues and feature requests.

Thanks :beers:

Kevin
