### ISSUE TITLE
watchOS deployment target for NSURLSession subspec.

### ISSUE THREAD

**Issue by maxmeyers** [AFNetworking/AFNetworking#2979]
I noticed that the watchOS deployment target is set on master (https://github.com/AFNetworking/AFNetworking/commit/a44c8a4d0f75a54acfa3dc378c881166fc91cde8), but not in the 2.6.0 release. This makes it difficult to compile watchOS targets that use NSURLSession (using Cocoapods). After running a `pod install`, `AFURLSessionManager` and `AFHTTPSessionManager` are not included in the target's pod target.

When can we expect a version update to include the watchOS deployment target?

**Comment by kylef** [comment]
The watchOS target is indeed set on the 2.6.0 release, see the released podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/AFNetworking/2.6.0/AFNetworking.podspec.json#L23

@maxmeyers Could you take another look into this, and also ensure you are using AFNetworking 2.6.0?

**Comment by kylef** [comment]
My bad, this wasn't set in the subspec. This will be release in the upcoming 2.6.1 of AFNetworking. For now you can use AFNetworking from source:

```ruby
pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking'
```
