### ISSUE TITLE
Unknown type name 'nullable'

### ISSUE THREAD

**Issue by niravspaceo** [AFNetworking/AFNetworking#2985]
Hello,

I just installed latest AFNetworking version using Cocoapods and then I am calling GET service like below. But It is giving me error  -> Unknown type name 'nullable'

 [AFHTTPRequestOperationManager manager] GET:apiName parameters:parameters success:^nullable void(AFHTTPRequestOperation * __nonnull, id __nonnull) {
        
    } failure:^nullable void(AFHTTPRequestOperation * __nonnull, NSError * __nonnull) {
        
    }];

What is wrong with this code ?

Thanks

**Comment by kylef** [comment]
@niravspaceo AFNetworking 2.6 introduces nullability annotations, these will depend on a modern version of Xcode 6 or Xcode 7. I would suggest you upgrade to Xcode 7 which supports these nullability annotations or use an older version of AFNetworking such as 2.5.4.
