### ISSUE TITLE
AFHTTPRequestOperationManager.o  does not contain bitcode

### ISSUE THREAD

**Issue by nuke99** [AFNetworking/AFNetworking#2986]
Im getting this error after updating into iOS9 
> ld: '/Users/myAccount/Library/Developer/Xcode/DerivedData/AppName-ftxlbucmwlnghsehqlhsyfbtxsvb/Build/Products/Debug-iphoneos/libAFNetworking.a(AFHTTPRequestOperationManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

Im trying workout without disabling bitcode . help ?

**Comment by iosliujun** [comment]
i have try the example project,also failed

**Comment by johnpaulmanoza** [comment]
I'm happing the same problem. I confirm that i disabled bitcode in libAFNetworking.a but that setting does not applied to AFHTTPClient.o which is inside the libAFNetworking.a

**Comment by danipralea** [comment]
Same problem here

**Comment by johnpaulmanoza** [comment]
I solved it by disabling the Bitcode into the whole app (Target -> Info -> Bitcode Enabled -> NO). Maybe some of my dependencies are not Bitcode enabled yet.

**Comment by danipralea** [comment]
yes, I did that too. But for tvOS apps Bitcode is now mandatory needed as YES. So I will naturally have to move away from AFNetworking, which is used in all my project
And likely that the iOS apps will require setting Bitcode to YES as well...

**Comment by johnpaulmanoza** [comment]
That's true. Maybe consider to use a rest client with bitcode support such as Alamofire or wait for afnetworking to push with bitcode support.

**Comment by alok1upadhyay** [comment]
I am also facing same issue, for now i have just disabled bitcode for time being. But we can't submit (please correct me if i am wrong) a IPA generated from xcode7 with bitcode set to NO. when can we get AFNetworking support Bitcode.

**Comment by kcharwood** [comment]
How are you pulling the library into your project? With Cocoapods?

@iosliujun are you saying you cannot run the example project? I don't seem to have that problem here.

**Comment by kcharwood** [comment]
I'm going to close this issue for now. The 3.0.0 branch has Carthage Support that does enable bitcode, and to my knowledge there is nothing specific a library maintainer needs to do in order to support bitcode for Cocoapods.
