### ISSUE TITLE
UIAlertView is deprecated

### ISSUE THREAD

**Issue by rodrigomascher** [AFNetworking/AFNetworking#2988]
Hi Developer´s,

In newer ios9, we have this warning:
UIAlertView+AFNetworking.m:80:52: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead

I suggest ihis sollution:

UIAlertController * alertView=   [UIAlertController
                                          alertControllerWithTitle:title
                                          message:message
                                          preferredStyle:UIAlertControllerStyleAlert];

for (NSString *otherButtonTitle in mutableOtherTitles) 
{
        [alertView addAction:
                  [UIAlertAction
                   actionWithTitle:otherButtonTitle
                   style:UIAlertActionStyleDefault
                   handler:^(UIAlertAction * action)
                    {
                       
                     }]];
            }

       UIViewController *rootViewController = [UIApplication sharedApplication].keyWindow.rootViewController; [rootViewController presentViewController: alertView animated: YES completion: nil];

**Comment by kylef** [comment]
Hi @rodrigomascher,

UIAlertController is not support on iOS 7, and AFNetworking supports iOS 7. Therefore we cannot migrate to UIAlertController from UIAlertView until we drop support for iOS 7.

**Comment by kylef** [comment]
Going to close this issue for now, we will move to UIAlertController once we drop iOS 7 support.
