### ISSUE TITLE
 ld: library not found for -lPods-AFNetworking

### ISSUE THREAD

**Issue by bf3400** [AFNetworking/AFNetworking#2989]
ld: library not found for -lPods-AFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Xcode7  

pod 'AFNetworking', '~> 2.0'

**Comment by bf3400** [comment]
![11](https://cloud.githubusercontent.com/assets/5080247/9932874/d20c633c-5d79-11e5-80f8-3c5f2b105fae.png)

**Comment by ptyahoo** [comment]
Try this: http://stackoverflow.com/questions/23539147/xcode-ld-library-not-found-for-lpods
It works for me.
