### ISSUE TITLE
stringByAddingPercentEncodingWithAllowedCharacters crash when escaping long Chinese strings

### ISSUE THREAD

**Issue by wanggang316** [AFNetworking/AFNetworking#2991]
https://github.com/Alamofire/Alamofire/issues/206

Like the Alamofire issues, 
This issue reproduce on AFNetworking v2.6.0, crash at  'stringByAddingPercentEncodingWithAllowedCharacters' this line.

**Comment by kylef** [comment]
Closing as a duplicate of #2958. Please search existing issues before creating new ones.
