### ISSUE TITLE
Crash on iOS 6

### ISSUE THREAD

**Issue by zerdzhong** [AFNetworking/AFNetworking#2992]
[NSCharacterSet URLQueryAllowedCharacterSet] in AFPercentEscapedStringFromString method is available after iOS 7,so it will crash on iOS 6.

**Comment by kylef** [comment]
@zerdzhong iOS 6 is not supported by AFNetworking. See the [requirements](https://github.com/AFNetworking/AFNetworking#requirements) in the README.
