### ISSUE TITLE
Caching http/https POST requests

### ISSUE THREAD

**Issue by shahzadmajeed** [AFNetworking/AFNetworking#2994]
Hi,

We are adding eTags in our apis to support url caching. I want to know what are the precautions or handling in AFNetworking specifically for POST requests. 

In other words, does AFNetworking supports caching POST requests and how ? Thanks in advance.

**Comment by kcharwood** [comment]
AFNetworking leverages the URL loading scheme provided by the system. If you have properly configured an NSURLCache, then the OS will respect the caching headers provided by the system.
