### ISSUE TITLE
when upload pictures,AFMultipartBodyStream is not able to immediately dealloc.

### ISSUE THREAD

**Issue by wangchuanhui1216** [AFNetworking/AFNetworking#2995]
When i use - (nullable AFHTTPRequestOperation *)POST:(NSString *)URLString
                      parameters:(nullable id)parameters
       constructingBodyWithBlock:(nullable void (^)(id <AFMultipartFormData> formData))block
                         success:(nullable void (^)(AFHTTPRequestOperation *operation, id responseObject))success
                         failure:(nullable void (^)(AFHTTPRequestOperation *operation, NSError *error))failure;
upload pictures,AFMultipartBodyStream is not able to immediately dealloc.

**Comment by kcharwood** [comment]
Could you please provide a clearer example, and post your sample code?

Thanks!

**Comment by kcharwood** [comment]
Feel free to reopen this issue if you are able to provide more information.
