### ISSUE TITLE
SSL broken in iOS 9

### ISSUE THREAD

**Issue by Tiger-Coding** [AFNetworking/AFNetworking#2997]
Attempting to access http URL's work fine, but accessing an https URL with iOS 9 results in "GET had an error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made.""

However, switching to iOS 8 works without issue.

May be related to the recurring issue:
https://github.com/AFNetworking/AFNetworking/pull/2702

AFURLSessionManager.m, line 319, has warnings about how NSURLSession task is being instantiated.  This section of the code is already in a workaround state. iOS 9 may have broke it again.

**Comment by kcharwood** [comment]
Please see Apple's note on [App Transport Security](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/) in iOS 9.

Note that your SSL connection must meet all of the following criteria, or you will need to add domain exceptions to your info.plist.


> * The server must support at least Transport Layer Security (TLS) protocol version 1.2.
> * Connection ciphers are limited to those that provide forward secrecy (see the list of ciphers below.)
> * Certificates must be signed using a SHA256 or better signature hash algorithm, with either a 2048 bit or greater RSA key or a 256 bit or greater Elliptic-Curve (ECC) key.
Invalid certificates result in a hard failure and no connection.

**Comment by Tiger-Coding** [comment]
Thank you Kevin :)
