### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by tbaranes** [AFNetworking/AFNetworking#2998]
I see a PR is opened about this, but is there any news about the support of the Apple TV? Even a branch currently in dev?

**Comment by kcharwood** [comment]
We'll get that pulled in soon.

The alamofire project does have a branch. I recommend checking it out!

https://github.com/Alamofire/Alamofire/tree/tvOS

**Comment by tbaranes** [comment]
Well, since all my code is using `AFNetworking`, I'm looking forward for the `AFNetworking` update, let me know when you will have a branch working! Until then, I will use `Alamofire`

**Comment by kcharwood** [comment]
I've got a branch where where it _compiles_...

https://github.com/AFNetworking/AFNetworking/tree/tvOS

I'll be working on adding an example to that soon.

**Comment by tbaranes** [comment]
:+1: Thanks! :tada:

**Comment by pakmee** [comment]
Hi , are there any plans in the pipeline to support TVOS for 1.x ?

**Comment by kcharwood** [comment]
We have no plans @pakmee. If you require tvOS support for that version, I would recommend forking the library and maintaining your own branch. Since `NSURLConnection` is still currently supported on tvOS, most of that code _should_ work on tvOS. However, we will not be supporting it.
