### ISSUE TITLE
Not percent-encoding Slashes in Parameters Breaks Twitter Oauth

### ISSUE THREAD

**Issue by kolpanic** [AFNetworking/AFNetworking#2999]
[This line](https://github.com/AFNetworking/AFNetworking/blob/64500e8464174c6030c4c1418f8a9a4de8028911/AFNetworking/AFURLRequestSerialization.m#L77) defines what characters get percent-encoded. However, omitting `/` results in the `oauth_callback` parameter—a URL—having its slashes intact. It results in a 401 Unauthorized error from Twitter's API. Adding `/` to the string fixes the error.

Your comment indicates that the omission is intentional because of the RFC, but that states "it is **sometimes better for usability to avoid** percent-encoding those characters". It doesn't look like a requirement.

**Comment by kcharwood** [comment]
cc @cnoon. Any thoughts on this one?

**Comment by cnoon** [comment]
The problem is that the RFC spec is itself, speculative. It advises to not percent encode both the `/` and `?` characters. I think we'd do more harm than good by making this change. I'd advise @kolpanic to manually percent encode the Twitter URL before building the URL parameters.
