### ISSUE TITLE
UIImageView+AFNetworking.swift error in xCode 7 for IOS 9

### ISSUE THREAD

**Issue by xScylez** [AFNetworking/AFNetworking#3002]
Using xCode 7.0

This is the code i am using: http://pastebin.com/9FFgFrtR
Error message
<img width="577" alt="screen shot 2015-09-22 at 22 41 16" src="https://cloud.githubusercontent.com/assets/10552182/10043269/ed8dd146-61f1-11e5-840e-514af69f2460.png">

Error 1:
objc_setAssociatedObject(self, &AssociatedKeys.SharedImageCache, cache, UInt(objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN))

Error 2:
objc_setAssociatedObject(self, &AssociatedKeys.RequestImageOperation, newValue.operation, UInt(objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC))

Error 3:
objc_setAssociatedObject(self, &AssociatedKeys.URLRequestImage, newValue.request, UInt(objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC))

Any suggestions what to do here?

**Comment by kcharwood** [comment]
Where did UIImageView+AFNetworking.swift come from? That should not be a .swift file, since AFNetworking is written in objective-c
