### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found."

### ISSUE THREAD

**Issue by BijeshNair** [AFNetworking/AFNetworking#3004]
Hi, I am getting this error very random even after re-hitting the service url again and again.
Sometimes it works after the time span of 30-40 sec, but sometimes it doesn't.
Have any idea what is causing this? Any solution?

**Comment by chintan100** [comment]
+1. 

Even with "NSAllowsArbitraryLoads" turned ON, there are seemingly very random -1003 errors in iOS app.

**Comment by kcharwood** [comment]
Hi @BijeshNair 

This question is better suited for StackOverflow. Github is for reporting bugs with AFNetworking, and with new feature requests.

Thanks!

:beers:

**Comment by Heisenbean** [comment]
Delete your app in the simulator and run your project.

**Comment by BijeshNair** [comment]
I've tried that. Doesn't work :(
This issue is very random.
Not able to figure out the root cause. 
Some says it has to do something with Connection-Alive param in server

**Comment by xiepaul888** [comment]
I face the same issue,i got this error very random  and don't know why.

**Comment by chenjinfei** [comment]
+1

**Comment by haofanning** [comment]
+1 Did you figue out how to solve this problem? I have the same issue too.

**Comment by chenjinfei** [comment]
Change the hostname string' coding format


???? iPhone

? 2016?12?29??10:13?haofanning <notifications@github.com<mailto:notifications@github.com>> ???


+1 Did you figue out how to solve this problem? I have the same issue too.

-

**Comment by chenjinfei** [comment]
Yes. Pls try to revise the coded format of the domain name.

在 2016年12月29日，10:13，haofanning <notifications@github.com<mailto:notifications@github.com>> 写道：


+1 Did you figue out how to solve this problem? I have the same issue too.
