### ISSUE TITLE
Xcode 7.0 / Swift 2.0 - Cannot Invoke appendPartWithFileURL

### ISSUE THREAD

**Issue by Gerst20051** [AFNetworking/AFNetworking#3005]
![screen shot 2015-09-23 at 12 44 33 pm](https://cloud.githubusercontent.com/assets/235372/10051759/2a4f24e6-61f1-11e5-8056-2dc56dedccd4.png)

Cannot invoke 'appendPartWithFileURL' with an argument list of type '(NSURL, name: String, error: NilLiteralConvertible)'

**Comment by kcharwood** [comment]
What version of AFNetworking are you using? We marked the error parameter as nullable in 2.6

**Comment by petemillermultimedia** [comment]
I am updated to AFNetworking 2.6 and I get this error also (in the method that includes fileName and mimeType as parameters).

**Comment by petemillermultimedia** [comment]
I eliminated the error by leaving out the 'error:' parameter altogether.

**Comment by Gerst20051** [comment]
yeah. in swift 2.0 throws and trys are now being implemented.

```try! data.appendPartWithFileURL(fileURL, name: "file")```

**Comment by albincr** [comment]
@Gerst20051 I used your code try! data.appendPartWithFileURL(fileURL, name: "file") but still getting error
