### ISSUE TITLE
WatchOS support breaks compilation under Xcode 6.4

### ISSUE THREAD

**Issue by JoeSzymanski** [AFNetworking/AFNetworking#3007]
The recent updates to support WatchOS cause AFNetworking to no long be able to be built in Xcode 6.4. The root cause of this is the usage of TARGET_OS_IOS, which is only defined starting in Xcode 7.

This should be updated to support older versions of Xcode.

**Comment by kcharwood** [comment]
Please see the [notes in the 2.6 changelog](https://github.com/AFNetworking/AFNetworking/blob/master/CHANGELOG.md).
