### ISSUE TITLE
AFNetworking was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by mojtabacazi** [AFNetworking/AFNetworking#3008]
trying to step into AFNetworking code generates following warning:
`was compiled with optimization - stepping may behave oddly; variables may not be available.`

I've checked optimizer and it's set to None for everything (just to make sure). And of course I'm not able to debug the code.

Xcode 7. iOS 9
Using Cocoa-pods. No framework

[Updates]
I'm using Debug configuration
Strip symbols is OFF

**Comment by free1990** [comment]
Please check your project is in release mode.

**Comment by free1990** [comment]
I have same question with you.

**Comment by knikaha** [comment]
me to

**Comment by iwill** [comment]
me too

**Comment by kcharwood** [comment]
Is [this](http://stackoverflow.com/questions/32772573/project-name-was-compiled-with-optimization-stepping-may-behave-oddly-varia) helpful?

Given this is outside the control of the AFNetworking project, I'm going to close this.

:beers:
