### ISSUE TITLE
'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0

### ISSUE THREAD

**Issue by burhanaksendir** [AFNetworking/AFNetworking#3010]
- (void)operationDidStart 

AFURLConnectionOperation.m  'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)

**Comment by khawars** [comment]
Any plan to upgrade it on iOS 9.0?

**Comment by kcharwood** [comment]
We will be dropping support for `NSURLConnection` based API's in AFNetworking 3.0, which we are actively working on.

I would recommend to move to the `NSURLSession` based API's (`AFHTTPSessionManager`, `AFURLSessionManager`) sooner rather than later.

Thanks!

:beers:
