### ISSUE TITLE
Creating multiple instances of AFHTTPRequestOperationManager causes reachability block to be overriden

### ISSUE THREAD

**Issue by mobitar** [AFNetworking/AFNetworking#3014]
When you create an instance of `AFHTTPRequestOperationManager`, in the `initWithBaseURL:` initializer, the operation manager is assigned the shared `AFNetworkReachabilityManager`:

```objective-c
self.reachabilityManager = [AFNetworkReachabilityManager sharedManager];
```

This means if your app has multiple `AFHTTPRequestOperationManager`'s, setting the `networkReachabilityStatusBlock` on the `reachabilityManager` property of the operation manager instance overrides the block you may have set on other instances of an operation manager's `reachabilityManager`.

This is undesired behavior, as ultimately, only the last block set will be executed in the event of a reachability change.

The solution would be to assign each `AFHTTPRequestOperationManager` its own unique instance of `AFNetworkReachabilityManager`, rather than using the `sharedManager`.

Possible solution: https://github.com/mobitar/AFNetworking/commit/4829c0b012f36c280efca135eaf4d4e782426be0

**Comment by tommypeps** [comment]
I think this doesn't a bug, really Singleton implementation define a unique instance for all the execution.
If you call the singleton on 2 instance different normally one must disappear.

If you want, instances 

```Objective-C
self.reachabilityManager = [AFNetworkReachabilityManager sharedManager];
```
in appDelegate:
```Objective-C
self.reachabilityManager = [AFNetworkReachabilityManager sharedManager];
[self.reachabulityManager startMonitoring];
.
.
.
[self.reachabilityManagersetReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {
   [[NSNotificationCenter defaultCenter] postNotificationName:@"newConection"
                                                                             object: @{@"status":AFNetworkReachabilityStatus}];
}]
```
:arrow_up:  Send notification at your other class for know when arrive conection




other Option, implemented only a instance but not Singleton
```Objective-C
self.reachabilityManager =  [AFNetworkReachabilityManager managerForDomain:@"my domain"];
    [self.sharedManagerAF startMonitoring];
.
.
.
[self.reachabilityManagersetReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {
//TODO:
}]
```

**Comment by kcharwood** [comment]
The AF Documentation does state:

>The network reachability manager. `AFURLSessionManager` uses the `sharedManager` by default.

But I do see your point as well. It would require a call to `startMonitoring` for each manager you want to set up. Let me think about this some more.

**Comment by kcharwood** [comment]
Linked to #3015

**Comment by kcharwood** [comment]
Closing this. Please direct future conversation to #3015
