### ISSUE TITLE
firing resume on multiple operations causes the AFURLConnectionOperation to crash

### ISSUE THREAD

**Issue by Wielkibrat** [AFNetworking/AFNetworking#3017]
Steps to reproduce:
Setup AFHTTPRequestOperationManager with custom maxConcurrentOperationCount for example = 3  and add several operations.
Pause all the operations and then resume them.

AFURLConnectionOperation crashes at:
```
-[NSObject(NSKeyValueObserverNotification) didChangeValueForKey:] + 88
-[AFURLConnectionOperation setState:] (AFURLConnectionOperation.m:331)
-[AFURLConnectionOperation finish] (AFURLConnectionOperation.m:478)
-[AFURLConnectionOperation connectionDidFinishLoading:] (AFURLConnectionOperation.m:696)
```

It is somehow connected to customising maxConcurrentOperationCount because if it's not set the following crash will not occur.

**Comment by kcharwood** [comment]
Thanks for the issue @Wielkibrat. Would you be able to add a test demonstrating the crash, and post it up?

Thanks!

**Comment by Wielkibrat** [comment]
Created a very sample project demonstrating the issue and uploaded it here http://sendfile.es/pokaz/517680---qW1d.html

**Comment by kcharwood** [comment]
@Wielkibrat would you be able to push the example to github or include the zip here? I can't seem to access that URL.

**Comment by Wielkibrat** [comment]
@kcharwood Sure https://github.com/Wielkibrat/AFUrlConnectionCrash

**Comment by kcharwood** [comment]
@Wielkibrat Given we have now moved past AFN 2.x and deprecated all use of NSURLConnection, I am going to close this out.

We are now only going to accept security patches for 2.x going forward. 

:beers:
