### ISSUE TITLE
UIImageView+AFNetworking.h

### ISSUE THREAD

**Issue by jrespuny** [AFNetworking/AFNetworking#3018]
- (void)setImageWithURLRequest:(NSURLRequest *)urlRequest
              placeholderImage:(UIImage *)placeholderImage
                       success:(void (^)(NSURLRequest *request, NSHTTPURLResponse *response, UIImage *image))success
                       failure:(void (^)(NSURLRequest *request, NSHTTPURLResponse *response, NSError *error))failure;

Can we have a way to get an image returned through a JSON?
{"image":"LzlqLz ... L1o=","extension":"jpg"}

Could we have something like this:
- (void)setImageWithURLRequest:(NSURLRequest *)urlRequest
              placeholderImage:(UIImage *)placeholderImage
base64EncodedJSONImagePath:(NSString *)JSONImagePath
                       success:(void (^)(NSURLRequest *request, NSHTTPURLResponse *response, UIImage *image))success
                       failure:(void (^)(NSURLRequest *request, NSHTTPURLResponse *response, NSError *error))failure;

**Comment by kcharwood** [comment]
I don't that problem is worth solving within the image view category, specifically with some changes we are setting up in the 3.0 branch. I would recommend decoupling that logic and leaving it out of the image view.

**Comment by jrespuny** [comment]
It's to make use of the cache for the images within a UITableView, but thank you anyway.

El 30/09/2015, a les 18:17, Kevin Harwood <notifications@github.com> va escriure:
