### ISSUE TITLE
can't use self-signed SSL cert using AFHTTPSessionManager on watchOS 2.0

### ISSUE THREAD

**Issue by rapinto** [AFNetworking/AFNetworking#3020]
Hi guys!

I'm trying to use a self-signed cert using **AFHTTPSessionManager** on a watchOS 2.0 app.

Here my test code :

``` objective-c
NSURL* lBaseURL = [NSURL URLWithString:@"https://myDomain/"];
    AFHTTPSessionManager* lSessionManager = [[AFHTTPSessionManager alloc] initWithBaseURL:lBaseURL
                                              sessionConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];


    AFSecurityPolicy* lPolicy= [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
    lPolicy.allowInvalidCertificates = YES;

    lSessionManager.securityPolicy = lPolicy;


    [lSessionManager GET:@"https://myDomain/api/"
              parameters:nil
                 success:^(NSURLSessionDataTask * _Nonnull task, id  _Nonnull JSON)
     {
         NSLog(@"success %@", JSON);
     }
                 failure:^(NSURLSessionDataTask * _Nonnull task, NSError * _Nonnull error)
     {
         NSLog(@"failure %@", error);
     }];
```
- My custom **.cer** is included in the bundle (I can see it into AFSecurityPolicy.pinnedCertificates)
- ATS is active into the **.plist**
- The same code works fine on the iOS App
- I'm using the master branch cocoapods : **pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', branch: 'master'**

Here is the error I'm getting : 

> Error Domain=NSURLErrorDomain **Code=-1200** "An SSL error has occurred and a secure connection >to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to >connect to the server anyway?, NSErrorFailingURLKey=https://myDomain/api, _kCFStreamErrorCodeKey=-9802, NSErrorFailingURLStringKey=https://myDomain/api, NSErrorClientCertificateStateKey=0, _kCFStreamErrorDomainKey=3, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.}

**Comment by kcharwood** [comment]
If you print out the `pinnedCertificates` property, what comes back?
