### ISSUE TITLE
AFNetworking not add --Boundary at request bottom for large file upload

### ISSUE THREAD

**Issue by TangMonk** [AFNetworking/AFNetworking#3026]
When I upload a video/mp4 to server,

AFNetworking not adding --Boundary to bottom, and server throw me an error

**Comment by kcharwood** [comment]
Can you please provide more concrete information of what you are trying to accomplish? Perhaps a sample project?

**Comment by kcharwood** [comment]
Please feel free to reopen this if you are able to provide any more information.
