### ISSUE TITLE
Issues with decoded url 

### ISSUE THREAD

**Issue by sonatkarakas** [AFNetworking/AFNetworking#3027]
1) We've noticed that when a  '+' sign is present in a query parameter (eg: bing.com/search?q=hello+world) of a url, AfNetworking decodes the value of this query parameter as "hello+world"  as opposed to "hello world" where the + is interpreted as a space.
Is this by design? Or is there a way to override/change this default behavior?

2) Similarly, when sending a url with a '+' sign in the query parameter this is encoded as %2B instead of %20 (i.e. a space) using the GET method. Is this also as designed? Or is there a way to override/change this default behavior?

Thanks!

**Comment by kcharwood** [comment]
This is by design. You should pass a space rather than a + into the query parameters, and it will be properly encoded.
