### ISSUE TITLE
Unable to perform file uploads in background

### ISSUE THREAD

**Issue by themoonraker13** [AFNetworking/AFNetworking#3030]
My application performs file uploads to server using POST HTTP request.
I'm using AFHTTPRequestOperationManager to manage various upload operations(an operation on manager's operation queue is one upload request).
The problem is I'm unable to upload files to my sever when I switch to background mode. The uploads are working fine if the app is active in foreground.
Moreover, I want the uploads to resume from where they left off in case of network-failure or explicit pause from user.

Any help will be highly appreciated.

**Comment by kcharwood** [comment]
`AFHTTPRequestOperationManager` relies on `NSURLConnection`, which does not support the background upload features found in `NSURLSession`.

I would recommend moving to `AFHTTPSessionManager` since we will soon be dropping support for all of the `NSURLConnection` based API's.

:beers:

**Comment by themoonraker13** [comment]
AFHTTPManager would surely help me tackling my problem to some extent.
But, then the issue is that the upload would generally be long-running tasks. So the real deal here is whether or not I'll able to upload large files in foreground and background using AFHTTPManager without running into any issues?
