### ISSUE TITLE
3 errors when used in Apple TV project

### ISSUE THREAD

**Issue by halpz** [AFNetworking/AFNetworking#3033]
Xcode 7.1 b3

1. AFNetworking/AFSecurityPolicy.m:30:27: Implicit declaration of function 'SecItemExport' is invalid in C99

2. AFNetworking/AFSecurityPolicy.m:30:46: Use of undeclared identifier 'kSecFormatUnknown'

3. AFNetworking/AFSecurityPolicy.m:30:65: Use of undeclared identifier 'kSecItemPemArmour'

**Comment by kcharwood** [comment]
Are you using the 3_0_0_branch? We have tvOS support there.

**Comment by halpz** [comment]
no, sorry!
