### ISSUE TITLE
Add factory method to create a copy of sharedManager-kind of manager

### ISSUE THREAD

**Issue by pronebird** [AFNetworking/AFNetworking#3035]
As I understand using shared reachability manager is not convenient in complex apps with lots of components doing different kinds of networking.

Having disconnected instances of `AFNetworkReachabilityManager` around the app would allow different components conditionally start or stop monitoring reachability without interfering with each other.

Shared manager listens changes on socket for internet / `AF_INET`, however `AFNetworkReachabilityManager` does not expose a method to create an instance of such manager. 

It would be very helpful to include such factory method.

**Comment by kcharwood** [comment]
#3015 addresses this.
