### ISSUE TITLE
Can't install the 3_0_0_branch for tvOS Project

### ISSUE THREAD

**Issue by sarn** [AFNetworking/AFNetworking#3036]
I get a `The platform of the target (tvOS 9.0) is not compatible with AFNetworking (3.0.0), which does not support tvos.` The podfile I use looks like this:

```
platform :tvos

target 'classicFilms' do
        pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking', :branch => '3_0_0_branch'
end
```

**Comment by manonthemoon42** [comment]
Hi @sarn ,

Temporarily, you can use this hack :
https://github.com/orta/cocoapods-expert-difficulty

You will be able to use this branch until they push a fix.

**Comment by kcharwood** [comment]
I updated the branch podspec with tvOS support. Can you let me know if that solves it?

**Comment by manonthemoon42** [comment]
I tried to install AFNetworking without the plugin I suggested, and it does work perfectly.
There is no more the warning : 
`The platform of the target (tvOS 9.0) is not compatible with AFNetworking (3.0.0), which does not support tvos.` 

Thanks @kcharwood :+1:

**Comment by Gwion101** [comment]
I tried that and am now getting this error:. 
` Target 'Pods' of project 'Pods' was rejected as an implicit dependency for 'libPods.a' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos' `

**Comment by sarn** [comment]
It also worked for me without any error any more

**Comment by Gwion101** [comment]
Now working for me also, had to change the base sdk to tvOS 9.0 under build settings for the pods project.

**Comment by kcharwood** [comment]
Give it a try now. Should be good to go.
