### ISSUE TITLE
3_0_0_branch - Building errors, related to dispatch_queue_t

### ISSUE THREAD

**Issue by manonthemoon42** [AFNetworking/AFNetworking#3037]
Hi @kcharwood ! 

I'm using your branch with Cocoapods, and we there are some building errors. 

<img width="1121" alt="c87a5577-f61b-4df1-a364-679967b2a76c-1" src="https://cloud.githubusercontent.com/assets/2165625/10420960/9f0000a6-7053-11e5-93eb-a4b21416e3c2.png">

Is it a known issue ? Do you know when it would be possible to add a fix to that building error ? 

Thanks

**Comment by kcharwood** [comment]
Check out the latest commit (20bcb63) in the 3.0 branch , and let me know if that fixes it!

**Comment by manonthemoon42** [comment]
It does fixes it ! 
Thanks @kcharwood
