### ISSUE TITLE
Pod install errors using 3_0_0_branch

### ISSUE THREAD

**Issue by tbaranes** [AFNetworking/AFNetworking#3038]
Just switching to the new AFNetworking branch for the tvOS, but getting this errors after doing a `bundle exec pod install`. Is any workaround against them?

```
[!] Unable to satisfy the following requirements:

- `AFNetworking/NSURLSession (= 3.0.0)` required by `AFNetworking (3.0.0)`
- `AFNetworking/NSURLSession (= 3.0.0)` required by `AFNetworking/UIKit (3.0.0)`
- `AFNetworking/NSURLSession (~> 2.0)` required by `AFNetworkActivityLogger (2.0.2)`
- `AFNetworking (from `https://github.com/AFNetworking/AFNetworking.git`, branch `3_0_0_branch`)` required by `Podfile`
- `AFNetworking (from `https://github.com/AFNetworking/AFNetworking.git`, branch `3_0_0_branch`)` required by `Podfile`
- `AFNetworking (from `https://github.com/AFNetworking/AFNetworking.git`, branch `3_0_0_branch`)` required by `Podfile`
- `AFNetworking (from `https://github.com/AFNetworking/AFNetworking.git`, branch `3_0_0_branch`)` required by `Podfile`
- `AFNetworking (~> 2.0)` required by `AFNetworkActivityLogger (2.0.1)`
```

**Comment by kcharwood** [comment]
i just pushed up an updated podspec with tvOS support.

**Comment by tbaranes** [comment]
I'm targeting the master of cocoapods / cocoapods-core / xcodeproj. Just try it again, I'm getting now the following error:

```
[!] Unable to satisfy the following requirements:
- `AFNetworking/NSURLConnection (~> 2.0)` required by `AFNetworkActivityLogger (2.0.4)`
```

**Comment by kcharwood** [comment]
Looks like `AFNetworkActivityLogger` is your problem, since we havent updated that for 3.x yet.

**Comment by tbaranes** [comment]
You are right, removing `AFNetworkActivityLogger` from my Podfile solved the issue. Thanks!

**Comment by tbaranes** [comment]
By the way, I see you have breaking changes on this new branch. Is there an `AFNetworking` 2.x.x branch supporting tvos?

**Comment by kcharwood** [comment]
I updated `AFNetworkActivityLogger` to have a working branch with 3.0.0 as well:

https://github.com/AFNetworking/AFNetworkActivityLogger/tree/3_0_0

At the moment, we are not planning on a 2.x.x branch with tvOS support.

**Comment by tbaranes** [comment]
Alright, thanks for the information and `AFNetworkActivityLogger`.

**Comment by timothycosta** [comment]
To install this branch, add
```
pod 'AFNetworkActivityLogger', :git => 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => '3_0_0'
```
This page is the top google result for "AFNetworkActivityLogger 3.0.0", so I'm putting this here to help others who may find this page and struggle to get it installed.  I hope nobody minds.

**Comment by ScoutHarris** [comment]
Any idea when AFNetworkActivityLogger will be updated on Cocoapods? Thanks!

**Comment by judos** [comment]
Does anyone have an idea how to set the podspec dependency when I create a library with the Activity logger?
I have so far:
```
pod 'AFNetworkActivityLogger', :git => 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => '3_0_0'
```
And in the podspec file i'm using:
```
  s.dependency 'AFNetworkActivityLogger', '~> 3.0.0'
```
But still I get this error:
```
[!] Unable to satisfy the following requirements:

- `AFNetworkActivityLogger (~> 3.0.0)` required by `AppLibrary (0.0.1)`

None of your spec sources contain a spec satisfying the dependency: `AFNetworkActivityLogger (~> 3.0.0)`.
```
