### ISSUE TITLE
CocoaPods Issue

### ISSUE THREAD

**Issue by goodocy** [AFNetworking/AFNetworking#3042]
AFNetworking podspec
  s.subspec 'NSURLSession' do |ss|
    ss.ios.deployment_target = '7.0'
    ss.osx.deployment_target = '10.9'
    ss.watchos.deployment_target = '2.0'
    
    ss.dependency 'AFNetworking/Serialization'
    ss.ios.dependency 'AFNetworking/Reachability'
    ss.osx.dependency 'AFNetworking/Reachability'
    ss.dependency 'AFNetworking/Security'

    ss.source_files = 'AFNetworking/AF{URL,HTTP}SessionManager.{h,m}'
    ss.public_header_files = 'AFNetworking/AF{URL,HTTP}SessionManager.h'
  end

CocoaPods Spec
    {
      "name": "NSURLSession",
      "platforms": {
        "ios": "7.0",
        "osx": "10.9"
      },
      "dependencies": {
        "AFNetworking/Serialization": [

        ],
        "AFNetworking/Security": [

        ]
      },
      "ios": {
        "dependencies": {
          "AFNetworking/Reachability": [

          ]
        }
      },
      "osx": {
        "dependencies": {
          "AFNetworking/Reachability": [

          ]
        }
      },
      "source_files": "AFNetworking/AF{URL,HTTP}SessionManager.{h,m}",
      "public_header_files": "AFNetworking/AF{URL,HTTP}SessionManager.h"
    },

AFNetworking podspec NSURLSession is support by watchos 2.0
but CocoaPods Spec missing for NSURLSession platforms "watchos": "2.0"

**Comment by kcharwood** [comment]
This issue is fixed in the latest branch. My goal is to get a 2.6.1 out today with the fix.
