### ISSUE TITLE
Invalid nullability attributes for AFURLSessionManager

### ISSUE THREAD

**Issue by dimazen** [AFNetworking/AFNetworking#3043]
AFURLSessionManager in 2.6 contains following method:

```
- (NSURLSessionDataTask *)dataTaskWithRequest:(NSURLRequest *)request
                            completionHandler:(nullable void (^)(NSURLResponse *response, id responseObject, NSError *error))completionHandler;
```
Taking into account `NS_ASSUME_NONNULL_BEGIN` at the beginning of the file it means, that both `responseObject` and `error` won't be nil at the same time. 
Can be fixed by:
```
(nullable void (^)(NSURLResponse *response, nullable id responseObject, nullable NSError *error))
```

Also: 
In 2.5 AFURLSessionManager contains callback for task completion which is imported into Swift as:
```
public func setDownloadTaskDidFinishDownloadingBlock(block: ((NSURLSession!, NSURLSessionDownloadTask!, NSURL!) -> NSURL!)!)
```

As you see, NSURL is optional here, also implementation handles this NSURL as an optional value as well:

```
NSURL *fileURL = self.downloadTaskDidFinishDownloading(session, downloadTask, location);
if (fileURL) {
}
```

However in 2.6 this callback declared as:
```
public func setDownloadTaskDidFinishDownloadingBlock(block: ((NSURLSession, NSURLSessionDownloadTask, NSURL) -> NSURL)?)
```
But implementation is the same (i.e. allows optional values). 
Returning `nil`, as far as I know, instruct system to remove that file automatically, therefore if for some reason I can not return URL there is no reason for me to worry about that file.

**Comment by kcharwood** [comment]
Hi @dimazen,

Your first issue is already addressed in the latest master branch.

As for the second, I'm not sure that should be an optional NSURL returned. Can you explain the use case you see for that?

**Comment by sowenjub** [comment]
Hi @kcharwood, I'm facing the same issue with the following use case: I use setDownloadTaskDidFinishDownloadingBlock to save the temp file into CoreData, so I don't need the temp file to be moved anywhere.

**Comment by dimazen** [comment]
@kcharwood 
Regarding second issue: 

My code looks like that: 

```
tasksManager.setDownloadTaskDidFinishDownloadingBlock { [weak self] session, task, url in
    return self?.downloadURLForTask(task)
}
```
`Self`here is the service, that wraps file downloads management. In rare case after user logout (and all download tasks cancellation) and service deallocation this callback was called, so I used to replace `unowned` with `weak`. As the result in case of callback after user logout I won't get a dangling file on the disk - it'll be removed by the system automatically.

**Comment by kcharwood** [comment]
Check out #3133

**Comment by sowenjub** [comment]
Thanks @kcharwood

**Comment by dimazen** [comment]
@kcharwood thanks :sun_with_face:
