### ISSUE TITLE
Incomplete xml parsing with 3.0

### ISSUE THREAD

**Issue by Bejil** [AFNetworking/AFNetworking#3044]
i'm trying to get XML from an url (http://iph.cadremploi.fr/emploi/jobs/11502602670) but I can't get the whole datas. It seems to stop at "item" node and bypass it. Any idea ?

I'm using AFNetworking 3.0 in order to build for tvOS.
```
NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"http://iph.cadremploi.fr/emploi/jobs/11502602670"]];
[request setValue:@"text/xml-v25-09-2014" forHTTPHeaderField:@"Accept"];
[request setHTTPShouldHandleCookies:NO];

NSURLSessionConfiguration *sessionConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:sessionConfiguration];
AFXMLParserResponseSerializer *serializer = [AFXMLParserResponseSerializer serializer];
serializer.acceptableContentTypes = [NSSet setWithObject:@"application/rss+xml"];
[manager setResponseSerializer:serializer];
[[manager dataTaskWithRequest:request completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {

    if(error==nil){

        NSLog(@"%@",[XMLReader dictionaryForNSXMLParser:(NSXMLParser *)responseObject error:nil]);
    }
    else{

        CE_LOG(error.localizedDescription);
    }

}] resume];
```
And here is the output :
```
{
rss =     {
    channel =         {
        description =             {
            text = "Job description";
        };
        language =             {
            text = fr;
        };
        link =             {
            text = "http://www.cadremploi.fr";
        };
        pubDate =             {
            text = "Tue, 13 Oct 2015 08:14:07 GMT";
        };
        text = "";
        title =             {
            text = "Flux RSS Cadremploi";
        };
    };
    text = "";
    version = "2.0";
    "xmlns:ce" = "http://cadremploi.fr";
};
}
```

**Comment by Ponf** [comment]
@Bejil can you show how did you add 3.0.0 in Podfile?
I have specified brunch 3_0_0, but it does not contain parsers and some other classes.

**Comment by Bejil** [comment]
Thanks for your response.

I manually add 3.0.0 by cloning it then copy/paste "AFNetworking" and "UIKit+AFNetworking" folders to my project.

I use XMLReader in order to simplify parsing and reading but with basic NSXMLParser it does the same. It doesn't return the whole xml datas.

**Comment by kcharwood** [comment]
Drop some debugging in [line 350](https://github.com/AFNetworking/AFNetworking/blob/3_0_0_branch/AFNetworking/AFURLResponseSerialization.m#L350) of `AFURLResponseSerialization.` Try turning that data result into a string and printing it out. Is all the data there that you are looking for? If so, then the error you are seeing would not be related to AFNetworking.

**Comment by Bejil** [comment]
Ok sorry, you're right. AFNetworking is not involved in this issue.
Don't know why but now it's working great... I really can't explain why.
Thanks for your help !
