### ISSUE TITLE
Internet connection

### ISSUE THREAD

**Issue by iDevelopper** [AFNetworking/AFNetworking#3045]
Hello,

I would like to check by code why there is no Internet connection available : 

1) If it is because the user has unchecked cellular data and/or Wi-Fi in settings

or

2) If it is because there is no reachability in the region

Is it possible ans how to ?

Thanks,

Regards

Patrick

**Comment by kcharwood** [comment]
Hi Patrick,

Github is for reporting issues and new feature requests. Questions like these belong on StackOverflow.

Thanks!

:beers:

**Comment by iDevelopper** [comment]
Ok i will, have you the response ?

**Comment by iDevelopper** [comment]
Done !
I would like to propose to the user to go to the settings application if I am sure it is the cellular data option is disabled

**Comment by iDevelopper** [comment]
http://stackoverflow.com/questions/33105049/ios-internet-connection

Patrick BODET

De :  Kevin Harwood <notifications@github.com>
Répondre à :  AFNetworking/AFNetworking
<reply+001b32b21c5b09df198738bc5d28f7886a5221b213d5b9d392cf000000011234cddb9
2a169ce06a065fa@reply.github.com>
Date :  mardi 13 octobre 2015 15:49
À :  AFNetworking/AFNetworking <AFNetworking@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [AFNetworking] Internet connection (#3045)


Hi Patrick,

Github is for reporting issues and new feature requests. Questions like
these belong on StackOverflow.

Thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/AFNetworking/AFNetworking/issues/3045#issuecomment-14772
1011> .
