### ISSUE TITLE
AFNetworking 3.0 Migration guide - AFHTTPRequestOperation section needs more explanation about NSOperation

### ISSUE THREAD

**Issue by Foriger** [AFNetworking/AFNetworking#3056]
Hi,

IMO there is a need to be mentioned, that NSURLSessionTask objects aren't NSOperation subclasses. Apps may require their logic to be embedded as NSOperation-s or maybe  request have to be dependency on some NSOperation. I think, that developers have to be notified, that if they migrate on 3.0 their operation based app should have more tweaks, than just replacing request calls.

What do you think about that?

Related issue #1504

**Comment by dchohfi** [comment]
+1

**Comment by iMoreApps** [comment]
+1

**Comment by toftof** [comment]
+1

**Comment by kcharwood** [comment]
I updated the wiki with this note:

```
Note that `NSURLSession` is not built upon `NSOperation`. If you have an app that heavily requires on the `NSOperation` aspects of `AFURLConnectionOperation`, there may be additional rework needed for your application to wrap `AFHTTPSessionManager` with an `NSOperation` based approach.
```
