### ISSUE TITLE
Self-signed certificate stops working with AFNetworking 2.6

### ISSUE THREAD

**Issue by bdesham** [AFNetworking/AFNetworking#3058]
My iOS app pins to a self-signed certificate, which is included as a .cer file in my app. With AFNetworking 2.5.4 the following code worked fine to establish the security policy:

    manager.securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
    manager.securityPolicy.allowInvalidCertificates = YES;
    manager.securityPolicy.validatesDomainName = NO;
    manager.securityPolicy.validatesCertificateChain = NO;

I just tried building my app against 2.6.1 and I had to remove the last line, since that property was removed (#2856), and now I get the following error when I try to connect to my server:

> Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLKey=https://api.example.com/v1/register, NSErrorFailingURLStringKey=https://api.example.com/v1/register}

If I print out `manager.securityPolicy.pinnedCertificates` I see one entry, which seems to contain the same bytes as my .cer file.

Any pointers on what I’m doing wrong?

**Comment by kcharwood** [comment]
Hi @bdesham. Thanks for the note.

We have several unit tests around Self Signed Certificates that are still passing, so things should work. Can you step through your code and let me know where the method is exited in `evaluateServerTrust:forDomain:`?

**Comment by bdesham** [comment]
Sure. That method exits with `NO` at the end of the following block

    NSUInteger trustedCertificateCount = 0;
    for (NSData *trustChainCertificate in serverCertificates) {
        if ([self.pinnedCertificates containsObject:trustChainCertificate]) {
            trustedCertificateCount++;
        }
    }
    return trustedCertificateCount > 0;

because there is only one item in `serverCertificates` and it does not meet the condition `[self.pinnedCertificates containsObject:trustChainCertificate]`. I’m not sure what exactly that means :-)

**Comment by kcharwood** [comment]
In this case you are looking for an exact match. You can that when we load in the certificate, we are loading in the certificate using `NSData`, and `containsObject` is simply looking for an equal `NSData` object. That would seem to indicate to me that you are not actually comparing the same certificates.
