### ISSUE TITLE
AFURLResponseSerialization.m file error in xcode 7.0.1

### ISSUE THREAD

**Issue by christinatsan** [AFNetworking/AFNetworking#3060]
Error in AFURLResponseSerialization.m:

Assigning to 'NSPropertyListFormat' from incompatible type 'unsigned long _Nullable'

**Comment by kcharwood** [comment]
How are you adding AFNetworking to your project? I am not seeing the error right now.

**Comment by kcharwood** [comment]
I believe the latest copy of master has a fix in for this one.
