### ISSUE TITLE
AFHTTPSessionManager failed to request https at latest version.

### ISSUE THREAD

**Issue by taojigu** [AFNetworking/AFNetworking#3066]
I just update the AFNetworking code，The code followed does not work now, when request https url with post method . It failed all the time.

It works with past versions.
The error description show "Canceled"
 NSError * domain: @"NSURLErrorDomain" - code: 18446744073709550617

 AFHTTPSessionManager* manager = [AFHTTPSessionManager manager];
 manager.requestSerializer = [AFJSONRequestSerializer serializer];
 manager.responseSerializer = [AFJSONResponseSerializer serializer];
 [manager POST: urlString parameters:bodyDict
     success:^(NSURLSessionDataTask *task, id responseObject)
    {

     return;
     }
     failure:^(NSURLSessionDataTask *task, NSError *error){

      failBlock(error);
     }
 ];

**Comment by hardikdevios** [comment]
@taojigu which URL you are passing ?

**Comment by taojigu** [comment]
@"https://api.gusmedsci.cn/service/getRequestInfo"

**Comment by hardikdevios** [comment]
@taojigu are you using a pre-release beta version ? 3.0 ?

**Comment by taojigu** [comment]
I used the code git pull from "https://github.com/AFNetworking/AFNetworking"

**Comment by kcharwood** [comment]
Attempting to hit that URL gives me a 405.

Questions like these are best suited for StackOverflow. Thanks!

:beers:
