### ISSUE TITLE
Bad serialization using the method requestWithMethod: URLString: parameters: error:

### ISSUE THREAD

**Issue by juanruocco** [AFNetworking/AFNetworking#3069]
When I update the library to 2.6.1 and 3.0.0 the method "requestWithMethod: URLString: parameters: error:" doesn't work fine, the special character '/' is not replaced by %2F, this is an example to test :

NSDictionary *dict = @{@"parameter":@"ljke/il"};
    AFHTTPRequestSerializer *requestSerialized = [AFHTTPRequestSerializer serializer];
    NSURLRequest *urlRequest = [requestSerialized requestWithMethod:@"GET" URLString:@"www.test.com" parameters:dict error:nil];

The url should be "www.test.com?parameter=ljke%2Fil" instead of "www.test.com?parameter=ljke/il"

**Comment by kcharwood** [comment]
Hi @juanruocco 

This is noted as an upgrade note in the [2.6.0 changelog](https://github.com/AFNetworking/AFNetworking/blob/master/CHANGELOG.md#260-08-19-2015), and is related to #2908. This change brings it in line with Alamofire so that both libraries encode the parameter in the same way.

We've also included the following note in the source itself:

```
/**
 Returns a percent-escaped string following RFC 3986 for a query string key or value.
 RFC 3986 states that the following characters are "reserved" characters.
    - General Delimiters: ":", "#", "[", "]", "@", "?", "/"
    - Sub-Delimiters: "!", "$", "&", "'", "(", ")", "*", "+", ",", ";", "="

 In RFC 3986 - Section 3.4, it states that the "?" and "/" characters should not be escaped to allow
 query strings to include a URL. Therefore, all "reserved" characters with the exception of "?" and "/"
 should be percent-escaped in the query string.
    - parameter string: The string to be percent-escaped.
    - returns: The percent-escaped string.
 */
```
