### ISSUE TITLE
AFURLResponseSerialization OGC issue

### ISSUE THREAD

**Issue by mikejnowak** [AFNetworking/AFNetworking#3070]
Hello, I am looking at WhirlyGlobe and I ran into a bug in their software. In the end it looks like the AFURLResponseSerialization could use an update to include application/vnd.ogc.wms_xml. I have a fix that works with WhirlyGlobe and wanted to share it with you guys and wondered what the process is for helping out.

**Comment by mikejnowak** [comment]
Thinking about this further, I can overwrite the acceptable mime type to keep the interesting application/vnd.ogc.wms_xml part of *my* application. Is that approach more "acceptable"?

**Comment by kcharwood** [comment]
That is the more acceptable approach. We try and limit the acceptable content types to standard content types. If you need a custom one, you can simply add it to the response serializer using the `acceptableContentTypes` property.
