### ISSUE TITLE
AFURLConnectionOperation.m:462:52: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)

### ISSUE THREAD

**Issue by imchenglibin** [AFNetworking/AFNetworking#3071]

**Comment by hardikdevios** [comment]
@imchenglibin The answer is in your question mate , please do use ***NSURLSession*** if you targeting from iOS 9 and use ***AFHTTPSessionManager***

**Comment by kcharwood** [comment]
Note the 3.0.0 branch has completely removed `NSURLConnection` from the lirbary.
