### ISSUE TITLE
Incorrect nullability annotations for completionHandler argument of AFURLSessionManager's task constructing methods

### ISSUE THREAD

**Issue by alfiehanssen** [AFNetworking/AFNetworking#3073]
The nullability annotations for methods like the one below do not mark the completionHandler's `response`, `responseObject`, and `error` as nullable / optional. 

```
NS_ASSUME_NONNULL_BEGIN

...

- (NSURLSessionDataTask *)dataTaskWithRequest:(NSURLRequest *)request
                            completionHandler:(nullable void (^)(NSURLResponse *response, id responseObject, NSError *error))completionHandler;

...
```

This applies to the upload and download task constructors as well. And it means that we cannot effectively check for the presence of an error. 

![screen shot 2015-10-18 at 10 12 24 am](https://cloud.githubusercontent.com/assets/991059/10564403/e213069a-7580-11e5-9620-542519e0bb91.png)

Seems like the method signature should be set up like so:

```
- (NSURLSessionDataTask *)dataTaskWithRequest:(NSURLRequest *)request
                            completionHandler:(nullable void (^)(NSURLResponse *__nullable response, id __nullable responseObject, NSError *__nullable error))completionHandler;
```

**Edit:** I'm running Xcode Version 7.0 (7A220) and including AFNetworking 2.6.0 via Cocoapods.

**Comment by kcharwood** [comment]
This is fixed in the latest version of AFNetworking. Please update, and try that!

:beers:
