### ISSUE TITLE
Batch Upload AFURLConnectionOperation batchOfRequestOperations

### ISSUE THREAD

**Issue by toftof** [AFNetworking/AFNetworking#3074]
I'm using this to perform batch upload. 

AFURLConnectionOperation batchOfRequestOperations

since AFURLConnectionOperation is removed from 3.0 - can you please advice or provide a sample of how to perform batch upload using the new architecture? I wish to target iOS 9. Thanks in advance.

**Comment by kcharwood** [comment]
The `AFHTTPSessionManager` API's leverage [`NSProgress`](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSProgress_Class/), which allow you to build up a tree of progress objects for reporting ability. I'd recommend reading the NSProgress documentation for information on how to do that.

:beers:

**Comment by kcharwood** [comment]
This might be a good candidate to add to the 3.0 migration guide.
