### ISSUE TITLE
WatchOS 2.0 unsupported.

### ISSUE THREAD

**Issue by AleksanderAzizi** [AFNetworking/AFNetworking#3076]
AFNetworking isn't supported on WatchOS 2.0.

As
https://github.com/AFNetworking/AFNetworking/issues/2595

**Comment by kcharwood** [comment]
What version of AFNetworking are you using, and how are you installing it in your project?

**Comment by AleksanderAzizi** [comment]
v2.6.1 using pods.

**Comment by kcharwood** [comment]
Using this Podfile, I was able to successfully install and use AFNetworking on a Watch target:

```Ruby
platform :watchos, "2.0"
target :AFNWatchTestWatchKitExtension do
    pod 'AFNetworking', '~> 2.6.1'
end

```
