### ISSUE TITLE
UIImageView+AFNetworking.h

### ISSUE THREAD

**Issue by jrespuny** [AFNetworking/AFNetworking#3078]
I'd need to make a POST request to get a JSON with a base64 encoded image field.
Could we get a new method resembling something like the following method, where instead of the image, we could get the JSON string or something similar?

- (void)setImageWithURLRequest:(NSURLRequest *)urlRequest
              placeholderImage:(UIImage *)placeholderImage
                       success:(void (^)(NSURLRequest *request, NSHTTPURLResponse *response, JSON *json))success
                       failure:(void (^)(NSURLRequest *request, NSHTTPURLResponse *response, NSError *error))failure;

If this is not possible, I'd like to make a pull request and add this method, but I am using AFNetworking as a dependency of RestKit and I am not sure if this is possible since in my Podfile I just have:

platform :ios, '8.0'
pod 'RestKit', '~> 0.24.0'

Thanks.

**Comment by kcharwood** [comment]
RestKit still depends on AFN 1.0, so you aren't going to be able to pull in any updates there.

We have a new image downloading architecture in AFN 3.0, and this would be easier to extend your own custom implementation there. Therefore, I'm going to go ahead and close this one out.

:beers:
