### ISSUE TITLE
Overriding responseObjectForResponse in an AFJSONResponseSerializer subclass incorrectly populates error object on request success. 

### ISSUE THREAD

**Issue by alfiehanssen** [AFNetworking/AFNetworking#3079]
I'm using Xcode 7, Swift 2, AFNetworking 2.6.1. 

I have an AFJSONResponseSerializer subclass in which I'd like to override `responseObjectForResponse` so that I can parse out response body data into an error object upon request failure. 

When I override this method with a simple call to `super` like so: 

```Swift
    override func responseObjectForResponse(response: NSURLResponse?, data: NSData?) throws -> AnyObject
    {
        return try super.responseObjectForResponse(response, data: data)
    }
```

and the request receives a successful HTTP status code, this method is called and subsequently the `serializationError` object is incorrectly populated by the superclass. In other words the task's completionHandler always receives an error, even when the request was successful.

If I comment out my method override all works as expected. Based on [this post](http://stackoverflow.com/questions/32761236/subclass-afnetworking-json-response-serialization-to-insert-json-response-body-i) and the answer mentioning using the `NS_SWIFT_NOTHROW` macro, it seems like something is amiss when Swift 2's new error handling is in the mix. 

Adding `NS_SWIFT_NOTHROW` to the objc method signature fixes the issue. But seems like a hacky resolution. Any other ideas?

**Comment by kcharwood** [comment]
I believe this is the same issue as #2810?

**Comment by alfiehanssen** [comment]
@kcharwood seems like they're both caused by a similar oddity with Swift 2's throws behavior. But symptoms / use cases are a little different. 

The user who reported that issue is seeing failed requests report as success when using the AFHTTPRequestOperation APIs and overriding `responseObjectForResponse`. 

Whereas I'm seeing successful requests report as failures when using the AFURLSessionManager APIs and overriding `responseObjectForResponse`.

So I guess they are the same issue since they both are triggered by overriding `responseObjectForResponse` :cake:

**Comment by kcharwood** [comment]
https://github.com/AFNetworking/AFNetworking/pull/3130 addresses this.

Thanks!

:beers:
