### ISSUE TITLE
Depreciation Warning in iOS9

### ISSUE THREAD

**Issue by GoldenJoe** [AFNetworking/AFNetworking#3081]
In iOS9, I get the following warning:

/AFNetworking/AFURLConnectionOperation.m:462:52: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)

**Comment by kcharwood** [comment]
The 3.0.0 branch has fully removed `NSURLConnection` from AFNetworking, and relies exclusively on `NSURLSession`. We hope to have it out of beta in the next two weeks.
