### ISSUE TITLE
Dynamically add value in header for each request

### ISSUE THREAD

**Issue by fvisticot** [AFNetworking/AFNetworking#3083]
I would like to add timestamp value for each request issue from AFHTTPRequestOperationManager.
Having a prepareRequest hook in this class would help me to configure the timestamp dynamically.

I think this feature is not available yet with AFNetworking

**Comment by kcharwood** [comment]
Subclass your requestSerializer, and override `requestWithMethod:URLString:parameters:error:`, and add your value there.
