### ISSUE TITLE
AFNetworking still use non watch supported usages in 2.6.1

### ISSUE THREAD

**Issue by amichaim** [AFNetworking/AFNetworking#3084]
Hi I saw the issue https://github.com/AFNetworking/AFNetworking/issues/2849 with use of SystemConfiguration/SystemConfiguration.h in Reachability Manager, and I saw you solved it with 
#if !TARGET_OS_WATCH
But there are still more other non watch supported usages in other classes like another use of SystemConfiguration/SystemConfiguration.h in AFHTTPRequestOperationManager.h or use of UIApplication in AFURLConnectionOperation.m

**Comment by kcharwood** [comment]
NSURLConnection is not supported on watchOS, so those files are not included in the watch target. You [can see in the podspec](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking.podspec#L54) watch support is not available for those classes, therefore there is no need to mark up that file for watch support
