### ISSUE TITLE
App rejected due to 3.0.0-beta.1 framework version

### ISSUE THREAD

**Issue by tomtaylor** [AFNetworking/AFNetworking#3092]
Similar to https://github.com/CocoaLumberjack/CocoaLumberjack/issues/633, my app has been rejected during iTunes upload due to the framework version number in AFNetworking 3.0.0-beta.1 (b2c449c8334449be1ff297ef4313d9970771feed), when built using Carthage.

```
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '3.0.0-beta.1' in the Info.plist file must be a period-separated list of at most three non-negative integers."
```

I can change it in the built Info.plist, temporarily, but it'd be good to fix this in the project. What's the best approach?

**Comment by tomtaylor** [comment]
PR in #3093

**Comment by kcharwood** [comment]
I'd recommend changing it by hand at the moment. I don't want to release 3.0.0 just yet, so that could cause some version problems going forward. Sad Apple won't allow semantic versioning...

**Comment by kcharwood** [comment]
cc @cnoon

**Comment by tomtaylor** [comment]
I don't think it affects anything other than the metadata for the framework - the framework loaded is still referenced by path. I think that makes it a harmless change, and ensures that it's possible to use the beta in an app store/testflight release.

**Comment by cnoon** [comment]
Pretty bad problem that is not an issue with AFNetworking. Apple seriously changed the rules around versioning of frameworks with Xcode 7.1. TONs of detail can be found in [Carthage #859](https://github.com/Carthage/Carthage/issues/859).

**Comment by cnoon** [comment]
Here's a script that should help fix up the issue:

```bash
#!/bin/bash

for plist in ./Carthage/Build/iOS/*/*.plist ; do
  if [ -e "$plist" ] ; then   # Check whether file exists.
     plutil -replace 'CFBundleShortVersionString' -string $1 $plist
  fi
done
```

https://github.com/Jonge/Cocoapods-frameworks-version-number-fix

**Comment by hardikdevios** [comment]
Guys i also face the same @cnoon solution works for now :+1:

**Comment by kcharwood** [comment]
I'm going to close this one out for now. Hopefully to move out of beta later this week. Thanks @cnoon
