### ISSUE TITLE
SSLHandshake failed (-9808) with self-signed root certificate

### ISSUE THREAD

**Issue by jakubprusa** [AFNetworking/AFNetworking#3097]
Hello everyone,

I have custom hardware device with REST API. Device has self-signed root certificate. I'am trying to make simple GET call but all my request failed with:

```
CFNetwork SSLHandshake failed (-9808)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9808)
```

More description:
```
CFNetwork SSLHandshake failed (-9808)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9808)
Error Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.68.97” which could put your confidential information at risk." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x7fa2fb219530>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9808, NSErrorPeerCertificateChainKey=<CFArray 0x7fa2fb20ffd0 [0x1016d37b0]>{type = immutable, count = 1, values = (
	0 : <cert(0x7fa2f954a2e0) s: selfSignedRootCertificate i: selfSignedRootCertificate>
)}, NSUnderlyingError=0x7fa2fb3018e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x7fa2fb219530>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9808, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9808, kCFStreamPropertySSLPeerCertificates=<CFArray 0x7fa2fb20ffd0 [0x1016d37b0]>{type = immutable, count = 1, values = (
	0 : <cert(0x7fa2f954a2e0) s: selfSignedRootCertificate i: selfSignedRootCertificate>
)}}}, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.68.97” which could put your confidential information at risk., NSErrorFailingURLKey=https://192.168.68.97/api/switch/ctrl?switch=1&action=on, NSErrorFailingURLStringKey=https://192.168.68.97/api/switch/ctrl?switch=1&action=on, NSErrorClientCertificateStateKey=0}
```

My code in subclass of AFHTTPSessionManger is 

```
      NSData *myCertificate = [NSData dataWithContentsOfFile: [[NSBundle mainBundle] pathForResource:@"selfSignedRootCertificate" ofType:@"cer"]];

        AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModePublicKey];
        securityPolicy.validatesDomainName = NO;
        securityPolicy.allowInvalidCertificates = YES;
        securityPolicy.pinnedCertificates = @[myCertificate];
```

And i tried to add exception to plist according to changes in iOS 9.0

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

I have no idea what I'm doing wrong. My point was pin my self-signed-root certificate to app to be able use https connection. Can you please help me with correct way how to do it?

I have AFNetworking (2.6.1).

Thanks for your help!

**Comment by kcharwood** [comment]
You have generated a self signed certificate for an IP address, not a domain name? I've actually never tried that before. I must confess it's tricky for me to debug without having access to your project and certificate.

**Comment by jakubprusa** [comment]
Hi,

thanks for your interest, I have exported certificate in der format from device through Firefox because this device has web interface. 

Link to it: https://www.dropbox.com/s/jkjyoe1mo7aoakg/ExportedCertificate.der?dl=0

And I can try to assign for that device public IP for testing. I hoped it could improved your debugging. Project is not necessary because now I have only blank project only with AFNetworking without anything else. But I can send it to you if you want.

**Comment by kcharwood** [comment]
I'm not going to be able to hit your `192.168.68.97` server. I would recommend at looking at the AFNetworking test suite. You can several examples of pinning code passing, include tests for Self Signed certificates.

**Comment by jakubprusa** [comment]
Ok, thanks for help. But i found that my certificate using this cipher "TLS-RSA-WITH-AES-256-CBC-SHA" but supported ciphers from apple are

TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA

source: https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/#//apple_ref/doc/uid/TP40016240-CH1-SW3

**Comment by kcharwood** [comment]
Sounds like that is the problem! :beers:

**Comment by jakubprusa** [comment]
I also tried this code:

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

That means all ciphers should be enabled but aplication still did not work. But anyway thanks for your help :)
