### ISSUE TITLE
NSURLConnection is deprecated in iOS9

### ISSUE THREAD

**Issue by reza-ryte-club** [AFNetworking/AFNetworking#3100]
Xcode version : 7
Target OS: ios9
Compiler warning:
File name: AFURLConnectionOperation.m
Line number: 662

<i>    'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0' - Use NSURLSession (see NSURLSession.h)</i>

**Comment by kcharwood** [comment]
As noted in #3081, #3071, #2993, and many others, these are removed in the AFNetworking 3.0 branch. If you haven't already migrated from the `AFURLConnectionOperation` based API's, you should do so soon.
