### ISSUE TITLE
Is it appropriate to "binary/octet-stream" to acceptable content types?

### ISSUE THREAD

**Issue by cameronehrlich** [AFNetworking/AFNetworking#3108]
In order to retrieve images from AWS S3 I had to do this:

```objective-c
AFImageResponseSerializer *serializer = (AFImageResponseSerializer *)self.imageResponseSerializer;
serializer.acceptableContentTypes = [serializer.acceptableContentTypes setByAddingObject:@"binary/octet-stream"];
self.imageResponseSerializer = serializer;
```

Would it be appropriate to submit a PR to fix this here:
https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLResponseSerialization.m#L668

**Comment by kcharwood** [comment]
Because an `octet-stream` is not always an image, it would not be appropriate to add it there. Instead, add it in own your application for your custom usage.

:beers:

**Comment by cameronehrlich** [comment]
@kcharwood I ended up subclassing `UIImageView` and putting the above code in the `-init`, but I feel like it would be nice for there to be a class method where you could set acceptable content types without having to subclass. e.g. ```[UIImageView setAcceptableContentTypes:[NSSet ...]];```

**Comment by kcharwood** [comment]
You have [access to the response serializer](https://github.com/AFNetworking/AFNetworking/blob/master/UIKit%2BAFNetworking/UIImageView%2BAFNetworking.h#L64), where you can add that content type.

:beers:

**Comment by cameronehrlich** [comment]
don't I still need a `UIImageView` instance to access that property?
