### ISSUE TITLE
UIWebView+AFNetworking "Declaration shadows a local variable" Warning

### ISSUE THREAD

**Issue by rsilva** [AFNetworking/AFNetworking#3114]
Xcode 7.1
iOS 9

Enable the "Hidden Local Variables" (`GCC_WARN_SHADOW`) warning.

The warning is reported for lines [132](https://github.com/AFNetworking/AFNetworking/blob/3.0.0-beta.1/UIKit%2BAFNetworking/UIWebView%2BAFNetworking.m#L132) and [143](https://github.com/AFNetworking/AFNetworking/blob/3.0.0-beta.1/UIKit%2BAFNetworking/UIWebView%2BAFNetworking.m#L143).

**Comment by BestNash** [comment]
What do you want to tell me ?friends

**Comment by kcharwood** [comment]
Fixed with #3126. Thanks!

**Comment by BestNash** [comment]
ok! thank you! and welcome to share you find..
