### ISSUE TITLE
AFHTTPSessionManager and AFURLSessionManager never deallocated

### ISSUE THREAD

**Issue by orkenstein** [AFNetworking/AFNetworking#3116]
This looks like bug and memory leak to me. Am I right? Allocation summary looks like this for `AFHTTPSessionManager`:
![2015-11-04 18-44-20 instruments2](https://cloud.githubusercontent.com/assets/1461936/10943117/1f27270e-8324-11e5-8096-136963478959.png)

And for `AFURLSessionManager`:
![2015-11-04 18-43-45 instruments2](https://cloud.githubusercontent.com/assets/1461936/10943127/2955251e-8324-11e5-83e8-009c9dd4d51d.png)

As you can see `NSURLSession` holds managers forever. To reproduce, just init one.

`AFNetworking (2.6.1)` and `swift2.1` with **Xcode 7.1**

**Comment by kcharwood** [comment]
NSURLSessionManager [retains its delegate](https://github.com/AFNetworking/AFNetworking/issues/2149#issuecomment-46842747). See that link for a reference on how to clean it up.

:beers:

**Comment by orkenstein** [comment]
@kcharwood, this kinda forces to use manager as singleton. Or manually `invalidateSessionCancelingTasks` for every instance. Maybe you have suggestions?

**Comment by kcharwood** [comment]
Unfortunately, this is a side effect of how NSURLSession is designed. As you can see [here](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/instp/NSURLSession/delegate), it has a strong reference to its own delegate.

**Comment by orkenstein** [comment]
Yep, I examined the documentation.
Maybe you can advice some kind of best practice of handling manager
objects? Beside singleton approach.

Отправлено с iPhone

6 нояб. 2015 г., в 3:10, Kevin Harwood <notifications@github.com>
написал(а):

Unfortunately, this is a side effect of how NSURLSession is designed. As
you can see here
<https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/instp/NSURLSession/delegate>,
it has a strong reference to its own delegate.

—
Reply to this email directly or view it on GitHub
<https://github.com/AFNetworking/AFNetworking/issues/3116#issuecomment-154239723>
.
