### ISSUE TITLE
Adding a CA does not automatically make its certificates pass with AFSecurityPolicy

### ISSUE THREAD

**Issue by rafaelc0sta** [AFNetworking/AFNetworking#3119]
Adding a custom CA to AFSecurityPolicy does not seem to make its child certificates pass through -evaluateServerTrust... This is (or at least, should be) unexpected behaviour, as adding a CA makes much more sense than adding the whole tree (CA and certificate). Creating a "AFSSLPinningModeCA" pinning mode would solve the problem, and should be an easy fix.

Update: Updating the code to work as I expect it to, I saw that using allowInvalidCertificates produces an equal input (at first glance, don't know for sure). It's important to note that an invalid/expired certificate is very different than a self-signed non-expired one. Here's my modification though... I can submit a pull request any time :) https://github.com/AFNetworking/AFNetworking/compare/master...rafaelc0sta:master

**Comment by kcharwood** [comment]
Would you be able to submit a PR with tests?

**Comment by rafaelc0sta** [comment]
@kcharwood Will submit! Sidenote: I wasn't able to run the tests on my machine (not that they failed, I just couldn't run them).

**Comment by kcharwood** [comment]
Closing this. Reference #3159

**Comment by rafaelc0sta** [comment]
@kcharwood Thanks! Look forward to see #3159 on 3.0.0! :)

**Comment by kcharwood** [comment]
I released beta 2 earlier today, which has it in there. Thanks again!
