### ISSUE TITLE
AFNetworking.h file not found 

### ISSUE THREAD

**Issue by virengujariya** [AFNetworking/AFNetworking#3125]
I'm using pods to install AFNetworking (2.6.1) library on my project. Somehow #import AFNetworking.h return error as mentioned in title (AFNetworking.h file not found ). Does that have anything to do with Share Extension?

**Comment by kylef** [comment]
You will need to import AFNetworking as follows:

```objectivec
@import AFNetworking;
```

of

```objectivec
#import <AFNetworking/AFNetworking.h>
```

**Comment by virengujariya** [comment]
Still same error. If I switch to 2.4.1 then error is 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

**Comment by Gerst20051** [comment]
:+1: any solution?

**Comment by kcharwood** [comment]
Can you give me your exact project setup? Or push up an example? I haven't been able to reproduce this so I'm struggling to debug it.

**Comment by Gerst20051** [comment]
this might be a little unrelated now that i think about it but it looks like the cocoapods version is missing a bunch of files such as **AFHTTPRequestOperationManager**.

<img width="237" alt="screenshot 2015-11-10 14 45 03" src="https://cloud.githubusercontent.com/assets/235372/11073644/9c8d9374-87b9-11e5-9b1b-0699fcdec563.png">

**Comment by kcharwood** [comment]
What does your podfile look like? Can you push up an example proj with the error?

**Comment by Gerst20051** [comment]
```
target 'mobilepay' do
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!
  pod 'AFNetworking', '3.0.0-beta.1'
end
```

**Comment by kcharwood** [comment]
`AFHTTPRequestOperationManager` is not available in 3.0.0. It has been removed. Please see this [guide](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide).

**Comment by virengujariya** [comment]
@kcharwood First off, sorry for delay. My project's pod files were messed. I corrected it using following

def shared_pods
	pod 'AFNetworking'
end

And used #import <AFNetworking/AFNetworking.h> wherever necessary.

**Comment by alisamili** [comment]
@virengujariya hi,my friends,I also encountered this problem for a long time.Unfortunately,can you tell me  how to solve it. If you can, specific points can be?Thanks~~~
This is my first time to foreign friends to ask questions.
