### ISSUE TITLE
“Remote server closed the connection before sending response header” but successblock is called

### ISSUE THREAD

**Issue by haemi** [AFNetworking/AFNetworking#3127]
I'm just debugging an error some of my customers experience, now I stumbled upon a weird behavior: according to charles proxy, a request failed ("Remote server closed the connection before sending response header") but my success block was called.

Is this a known behavior/issue?

**Comment by kcharwood** [comment]
This is most likely has something to do with your servers keep alive configuration, or a Charles configuration issue. 

If you step through code and find evidence of a specific bug within AFNetworking, please feel free to reopen this issue!

:beers:
