### ISSUE TITLE
Breaking API change on v2.6.2?

### ISSUE THREAD

**Issue by priteshshah1983** [AFNetworking/AFNetworking#3137]
Not sure if this was intentional, but it seems like `AFURLResponseSerialization`'s `responseObjectForResponse:data:error:` signature changed in the latest release: `v2.6.2`.

In 2.6.1, it was:
```objective-c
- (nullable id)responseObjectForResponse:(nullable NSURLResponse *)response
                           data:(nullable NSData *)data
                          error:(NSError * __nullable __autoreleasing *)error;
```

In 2.6.2, it is:
```objective-c
- (nullable id)responseObjectForResponse:(nullable NSURLResponse *)response
                           data:(nullable NSData *)data
                          error:(NSError * __nullable __autoreleasing *)error NS_SWIFT_NOTHROW;
```

This breaks the compatibility if one is using AFNetworking in a Swift 2.1 project.

The error is:
```
Cannot invoke 'responseObjectForResponse' with an argument list of type '(NSURLResponse!', data: NSData?)'
```

**Comment by kcharwood** [comment]
You're right. This is a Swift API change, although it _isn't_ an Objective-C API change, which where my head was at.

Now that "it's done", let me see what we should do here. I may add a note to the release notes indicating the issue.

**Comment by kcharwood** [comment]
This was in reference to #2810

**Comment by kcharwood** [comment]
I've updated the changelog [here](https://github.com/AFNetworking/AFNetworking/blob/master/CHANGELOG.md#important-upgrade-note-for-swift) with an additional description.

**Comment by kcharwood** [comment]
And I've also updated the release notes:

https://github.com/AFNetworking/AFNetworking/releases/tag/2.6.2

**Comment by kcharwood** [comment]
Again, sorry for the churn here. Simply missed it in pulling the release together.

You'll need to migrate from do-try-catch to an error pointer there. I hope that doesn't major pain for you.

**Comment by priteshshah1983** [comment]
@kcharwood It's all good! I was skeptical of making the change in our codebase (to accommodate this change) before I confirm that this change was not accidental and is here to stay.

I will go ahead and make this change, thanks for the release!
