### ISSUE TITLE
an Error Occured When build a project

### ISSUE THREAD

**Issue by mlibai** [AFNetworking/AFNetworking#3138]
The file "AFNetworkReachabilityManager.m" at line 130, the class method need return nil if the condition is not supported.

```Objective-C
+ (instancetype)managerForDomain:(NSString *)domain {
#ifndef __clang_analyzer__
    SCNetworkReachabilityRef reachability = SCNetworkReachabilityCreateWithName(kCFAllocatorDefault, [domain UTF8String]);

    AFNetworkReachabilityManager *manager = [[self alloc] initWithReachability:reachability];

    return manager;
#endif
    return nil;
}

+ (instancetype)managerForAddress:(const void *)address {
#ifndef __clang_analyzer__
    SCNetworkReachabilityRef reachability = SCNetworkReachabilityCreateWithAddress(kCFAllocatorDefault, (const struct sockaddr *)address);
    AFNetworkReachabilityManager *manager = [[self alloc] initWithReachability:reachability];

    return manager;
#endif
    return nil;
}
```

**Comment by Ruoyiming** [comment]
change it like this
#ifndef __clang_analyzer__
+ (instancetype)managerForDomain:(NSString *)domain {

    SCNetworkReachabilityRef reachability = SCNetworkReachabilityCreateWithName(kCFAllocatorDefault, [domain UTF8String]);

    AFNetworkReachabilityManager *manager = [[self alloc] initWithReachability:reachability];
    return manager;
}
#endif

#ifndef __clang_analyzer__
+ (instancetype)managerForAddress:(const void *)address {
    SCNetworkReachabilityRef reachability = SCNetworkReachabilityCreateWithAddress(kCFAllocatorDefault, (const struct sockaddr *)address);
    AFNetworkReachabilityManager *manager = [[self alloc] initWithReachability:reachability];

    return manager;
}
#endif

**Comment by kcharwood** [comment]
How are you building your project? The example project builds and compiles for me, as well as on Travis. Just want to make sure I understand how I missed this.

Thanks!

**Comment by kcharwood** [comment]
I just put up #3142, but I still don't know you caused the failure. If you could let me know so I can verify that fix, that would be great!

**Comment by AngleFlying999** [comment]
I  have a problem  use 2.6.3  in xcode6.3

**Comment by kcharwood** [comment]
With the fixes in https://github.com/AFNetworking/AFNetworking/pull/3139, I am able to build in Xcode 6.4

@mlibai @Ruoyiming can you let me know what your setup is here? As soon as I confirm, I can release 2.6.3.

**Comment by Ruoyiming** [comment]
just create a new project,drag the AFNetworking into your project, just run it, then you can see the error

**Comment by mlibai** [comment]
"Product > Analyze" or "Command + Shift + B"，then the xCode will comment an error, but won't happen when run a program.

**Comment by mlibai** [comment]
The methods below in the file "AFNetworkReachabilityManager.m" at line 130:
```Objective-C
+ (instancetype)managerForDomain:(NSString *)domain;
+ (instancetype)managerForAddress:(const void *)address;
```
are compiled When "__clang_analyzer__" is not defined, but if "__clang_analyzer__" is defined, the method has no return value, so the error occur.

**Comment by kcharwood** [comment]
@mlibai I'm doing those _exact_ steps. That is how I verified the analyzer warning went away in the first place.

Can you get that to appear in the example project of this repo? How are you including AFNetworking in your project? And what version of Xcode are you using? Thanks! I'm holding up the 2.6.3 release on this specifically, so I would love to get it confirmed this morning.

**Comment by kcharwood** [comment]
Ok I've _finally_ reproduced. Doing a full clean appears to have been the needed step for me (although I'm not entirely sure why.) I'll get the patch in now that I can verify it!

Thanks!

**Comment by kcharwood** [comment]
#3142 has been merged. Release coming soon.

Thanks again :beers:

**Comment by mlibai** [comment]
You're welcome, it's glad that I can do something good for AFNetworking. My English is not well, and I sorry for my expression. I got the error by step: downloaded the file from github, built the iOS example project (shortcut key "cmd + shift + B"), then the xcode comment the error. Hope it may help you more.
