### ISSUE TITLE
No travis job for Xcode 6

### ISSUE THREAD

**Issue by jcayzac** [AFNetworking/AFNetworking#3140]
https://github.com/AFNetworking/AFNetworking#user-content-requirements claims AFNetworking is compatible with iOS 6, yet no CI is done with Xcode 6 to back that claim.

`2.6.2` can only be built with Xcode 7 using an iOS 8 or 9 base SDK.

There should be a Travis job for Xcode 6.4, or the requirement section should be amended if Xcode 7/iOS 8 is now the minimal supported environment.

**Comment by kcharwood** [comment]
Thanks @jcayzac!

Can you let me know what error you are seeing? I don't have a copy of Xcode 6 installed at the moment.

Also, have you seen an example of a travis project running with multiple versions of xcode? I haven't seen that yet.

**Comment by kcharwood** [comment]
Oops just saw #3139. Thanks for that!
