### ISSUE TITLE
Client closed connection before receiving entire response

### ISSUE THREAD

**Issue by moses-gangipogu** [AFNetworking/AFNetworking#3141]
unable to download file 
getting this error "Client closed connection before receiving entire response"
the file which i am trying to download is just 266KB

         for (NSString *downloadURL in arr) {
       // NSString *downloadURL = [d objectForKey:@"url"];
        dispatch_async(dispatch_get_main_queue(), ^{
            NSLog(@"URL for downloading : %@",downloadURL);
            NSArray *pathArray = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask,YES);
            NSString *documentsDirectory = [pathArray objectAtIndex:0];
            NSString *downloadedZipPath = [documentsDirectory stringByAppendingPathComponent:TEMP_DICTIONARY];
            NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:downloadURL]];
           // [request addValue:@"bytes=x-" forHTTPHeaderField:@"Range"];
           // [request setTimeoutInterval:20];
            AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:request];
           
            operation.outputStream = [NSOutputStream outputStreamToFileAtPath:downloadedZipPath append:NO];
            
            [operation setCompletionBlockWithSuccess:^(AFHTTPRequestOperation *operation, id responseObject) {
                NSLog(@"Success");
            } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
                NSLog(@"Error: %@", error);
            }];
            
            [operation start];
        });

tried to increase api request time out but still not working

http://stackoverflow.com/questions/33608425/client-closed-connection-before-receiving-entire-response-afnetworking

**Comment by kcharwood** [comment]
This typically has something to do with your server configuration, and not something specific to AFNetworking. You could try migrating to AFHTTPSessionManager, which uses NSURLSession under the hood. The NSURLConnection based API's you are using are no longer supported in the 3.0.0 branch.

:beers:
