### ISSUE TITLE
afnetworking 3.0 beta 1 setImageWithURL crashes when URL == nil

### ISSUE THREAD

**Issue by core-code** [AFNetworking/AFNetworking#3145]
=>
'*** setObjectForKey: key cannot be nil'

**Comment by kcharwood** [comment]
While the API doesnt specify that should be a nonnull argument, we can be a little safer under the hood with no impact. #3146 adds the check, as well as a test.

Thanks!

**Comment by core-code** [comment]
thanks. fixing it is especially valuable since it is a regression and we had a crash here after updating
