### ISSUE TITLE
AFNetWorking 3.0 Https 

### ISSUE THREAD

**Issue by lengain** [AFNetworking/AFNetworking#3156]
how to use  self-sign ssl certificate  with AFNetWorking 3.0?
in my app,I code:

NSString *cerPath = [[NSBundle mainBundle] pathForResource:kHttpCer ofType:@"cer"];
    NSData *certData = [NSData dataWithContentsOfFile:cerPath];
    AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeNone];
    [securityPolicy setAllowInvalidCertificates:YES];
    securityPolicy.allowInvalidCertificates = NO;
    [securityPolicy setPinnedCertificates:@[certData]];
    self.securityPolicy = securityPolicy;//self is kind of class AFHTTPRequestOperationManager.

but,it is not work,plase try to help me.

**Comment by liuchungui** [comment]
Hi lengain
Do you set `Allow Arbitrary Loads` to YES ?  how to set, you can see [https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html](https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html)

Here is my code:
```      
 //BGAFHTTPClient is kind of class AFHTTPSessionManager
        _httpClient = [[BGAFHTTPClient alloc] initWithBaseURL:[NSURL URLWithString:baseURL]];
        AFSecurityPolicy *policy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
        policy.allowInvalidCertificates = NO;
        policy.validatesDomainName = YES;
        _httpClient.securityPolicy = policy;
```

**Comment by lengain** [comment]
yes,I have setted Allow Arbitrary Loads to YES.......,but ,it still not work @liuchungui ,Do you found any mistake in my code?

**Comment by liuchungui** [comment]
I modify you code

AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
securityPolicy.allowInvalidCertificates = YES;
[securityPolicy setPinnedCertificates:@[certData]];
self.securityPolicy = securityPolicy;//self is kind of class AFHTTPRequestOperationManager.

you try it.

**Comment by lengain** [comment]
Think you! @liuchungui  ,I set securityPolicy.allowInvalidCertificates = YES;,it works. but I don't know reason why I set securityPolicy.allowInvalidCertificates = NO,it dones't work.here is output error.

Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)" UserInfo=0x170a75b00 
{NSErrorFailingURLKey=https://api.zhefengle.cn/index.html, NSErrorFailingURLStringKey=https://api.zhefengle.cn/index.html

I checked my .cer file, it is valid. 
I am confused.....

**Comment by liuchungui** [comment]
If you set allowInvalidCertificates = NO and SLLPinningMode = AFSSLPinningModeNone,   the code will go here

if (self.SSLPinningMode == AFSSLPinningModeNone) {
        return self.allowInvalidCertificates || AFServerTrustIsValid(serverTrust);
}

AFServerTrustIsValid will check your certificate whether is trusted certificate by system 'SecTrustEvaluate' method.
But, self-signed certificate that is not a trusted anchor, we can't pass `SecTrustEvaluate` method, for detail you can sell [https://developer.apple.com/library/ios/technotes/tn2232/_index.html#//apple_ref/doc/uid/DTS40012884-CH1-SECUNDERSTAND](https://developer.apple.com/library/ios/technotes/tn2232/_index.html#//apple_ref/doc/uid/DTS40012884-CH1-SECUNDERSTAND).
Hope to help you.

**Comment by lengain** [comment]
Thank you very much! help me a lot! @liuchungui
