### ISSUE TITLE
Huge memory allocation when doing lots of image-downloads (in blocks)

### ISSUE THREAD

**Issue by the-unforgiven** [AFNetworking/AFNetworking#3157]
Hi all,
I'm using AFHTTPRequestOperation to download a bunch of images. As soon as I put my hands on "responseobejct" and process the object in setCompletionBlockWithSuccess memory is piling up. Depending on the number of images a "didReceiveMemoryWarning" is received and usually the app crashes a little later. If I don't touch the "responseobject" all is well. So it it looks to me like a referencing-issue. If the "for-in" should come to an end - e.g. fewer images or device with more (free) RAM - all allocated memory is disposed and all is well.

I tried @autoreleasepool or to create a "local" copy of responseobject - but without success till now.

Working on Xcode 7.1, ARC, iOS 9.

Any idea?
Kind regards

    @try
    {
        
        for (NSDictionary *dictionary in updates)
        {
            NSURL *url = [NSURL URLWithString:[@"http://example.com/folder/" stringByAppendingString:[dictionary valueForKey:@"imagename"]]];
            
            AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:[NSURLRequest requestWithURL:url]];
            operation.responseSerializer = [AFImageResponseSerializer serializer];
            operation.userInfo = dictionary;
            
            [operation setCompletionBlockWithSuccess:^(AFHTTPRequestOperation *operation, id responseObject) {

                NSDictionary *userinfo = operation.userInfo;
                // NSMutableData *data = [[NSMutableData alloc] initWithData:UIImagePNGRepresentation(responseObject)];

            } failure:^(AFHTTPRequestOperation *operation, NSError *error)
             {
             }];
            
            [operation setDownloadProgressBlock:^(NSUInteger read, long long totalRead, long long totalExpectedToRead) {
            }];
            
            [requestArray addObject:operation];
        }
        
        NSArray *batches = [AFURLConnectionOperation batchOfRequestOperations:requestArray
                                                                progressBlock:^(NSUInteger numberOfFinishedOperations, NSUInteger totalNumberOfOperations) {
                                                                }
                                                              completionBlock:^(NSArray *operations) {
                                                                  
                                                              }];
        
        NSOperationQueue* queue = [NSOperationQueue mainQueue];
        [queue addOperations:batches waitUntilFinished:NO];
    }
    @catch (NSException * e) {
        NSLog(@"Exception: %@", e);
    }
    @finally {
    }

**Comment by the-unforgiven** [comment]
Just as I posted "... as I put my hands on the responseobject ..." I thought "... how about NOT putting my hands on the responseobject ..." and found a way how it works:

If I add "operation.outputStream = [NSOutputStream outputStreamToFileAtPath:filePath append:NO];" when creating the AFHTTPRequestOperation the images is streamed right right to the file and I can avoid handling the "responseobject". Nevertheless I wonder if this is just a workaround ...

**Comment by kcharwood** [comment]
Looks like you are alloc/init'ing NSData for every image that comes back, which would mean you are the owner of that memory going forward.

This simply looks like an implementation on your side and not an issue with AFNetworking, so I'm going to close this one out.

Thanks :beers:
