### ISSUE TITLE
AFNetworking (3.0.0-beta.1) UIProgressView+AFNetworking crashed when no data

### ISSUE THREAD

**Issue by NagiYan** [AFNetworking/AFNetworking#3161]
how I use:    

```Objective-C
NSURLSessionDataTask * task = [manager POST:url parameters:params constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
    [byteDatas enumerateObjectsUsingBlock:^(NSDictionary*  _Nonnull item, NSUInteger idx, BOOL * _Nonnull stop) {
        [formData appendPartWithFileData:[item objectForKey:@"data"]
                                    name:[item objectForKey:@"key"]
                                fileName:[item objectForKey:@"fileName"]
                                mimeType:[item objectForKey:@"type"]];
    }];
} success:^(NSURLSessionDataTask * _Nonnull task, id  _Nonnull responseObject) {
    callback(responseObject);
} failure:^(NSURLSessionDataTask * _Nonnull task, NSError * _Nonnull error) {
    callback(nil);
}];

if (progress) {
    [progress setProgressWithUploadProgressOfTask:(NSURLSessionUploadTask *)task animated:YES];
}
```
if `byteDatas` is an empty array, crash at UIProgressView+AFNetworking.m line 100:

```Objective-C
[object removeObserver:self forKeyPath:NSStringFromSelector(@selector(state))];
```

**Comment by NagiYan** [comment]
today I find a new problem:
same code, byteDatas with one object, after the progress get to the end, an extra thread run
[UIProgressView(AFNetworking) observeVlaueForKeyPath:ofObject:change:context:], 
keyPath =@"state" 
and [(NSURLSessionTask *)object state] == NSURLSessionTaskStateCompleted,
so removeObserver twice, crash,
the thread come from [NSURLSession delegate_task:didCompleteWithError:],
first thread come from [NSCFURLLocalSessionConnection withDelegateAndPendingCompletion:]

**Comment by kcharwood** [comment]
What version of AFNetworking are you using? When the observer is removed, its wrapped in a try catch where the exception is caught and not reported, so that should not have caused a crash.

**Comment by NagiYan** [comment]
3.0.0-beta.1
sorry for wasting your time to check the issue, the first time when I meet the exception, I thought it crashed, now I confirmed It did not crash, only exception twice,  but I did take much time to confirm the cause of the exception and to make sure it is not my problem, if you can solve the exeption it is better, the exception occors every time. thanks for your contribution.
