### ISSUE TITLE
How to get progress when using `AFHTTPSessionManager GET:parameters:success:failure:`

### ISSUE THREAD

**Issue by Vayn** [AFNetworking/AFNetworking#3163]
When I use AFNetworking 2, I could get progress with `AFHTTPRequestOperation` like this:

```objective-c
NSURLRequest *urlRequest = [[NSURLRequest alloc] initWithURL:aURL cachePolicy:NSURLRequestReturnCacheDataElseLoad timeoutInterval:_timeoutInterval];
AFHTTPRequestOperation *imageRequestOperation = [[AFHTTPRequestOperation alloc] initWithRequest:urlRequest];
imageRequestOperation.responseSerializer = [AFImageResponseSerializer serializer];
[runningRequests addObject:imageRequestOperation];
__weak AFHTTPRequestOperation *imageRequestOperationForBlock = imageRequestOperation;

[imageRequestOperation setCompletionBlockWithSuccess:^(AFHTTPRequestOperation *operation, id responseObject) {
    // ...
} failure:^(AFHTTPRequestOperation *operation, NSError *error) {
    // ...
}];

[imageRequestOperation setDownloadProgressBlock:^(NSUInteger bytesRead, long long totalBytesRead, long long totalBytesExpectedToRead) {
    if (progress) {
        progress((float)totalBytesRead / totalBytesExpectedToRead);
    }
}];
```
I don't know how to get progress in AFNetworking 3.

**Comment by kcharwood** [comment]
We need to have a good answer for this for 3.0.0 before we release. Thanks for opening this issue.

**Comment by kcharwood** [comment]
`AFURLSessionManager` exposes a method named `progressForDataTask:`, which returns a `NSProgress` that you can KVO off of. Could you take a look at that and see if that gives you what you are looking for?

**Comment by kcharwood** [comment]
I added a test demonstrating progress reporting does work for an `NSURLSessionDataTask` in b083b5dcf15411118901345a8b37fb10f34cb9ac

**Comment by kcharwood** [comment]
I also updated the migration guide: https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide#tracking-progress

**Comment by kcharwood** [comment]
I've merged that test in now.

Thanks again.

**Comment by Vayn** [comment]
Hi @kcharwood , I've asked the same question on [StackOverflow](http://stackoverflow.com/questions/33762970/how-to-get-download-progress-with-afhttpsessionmanager-in-afnetworking-3-0) and got the answser. @rocjark adviced me to use `setDataTaskDidReceiveDataBlock` to get `countOfBytesReceived` to calculate the progress.

I'll look at `progressForDataTask` then. Thanks for answering my question.

P.S. I miss `setDownloadProgressBlock` :smile:
