### ISSUE TITLE
Can’t distinguish between server trust evaluation failure and task cancellation

### ISSUE THREAD

**Issue by 0xced** [AFNetworking/AFNetworking#3165]
When server trust evaluation fails, AFNetworking calls the completion handler with disposition `NSURLSessionAuthChallengeCancelAuthenticationChallenge` which in turn calls NSURLSessionTask’s `cancel` method.

The resulting error is from `NSURLErrorDomain` with code `NSURLErrorCancelled` (-999) which is the exact same error you get if you call `cancel` on a task yourself.

I think it’s AFNetworking’s responsibility to properly handle server trust failure and report a better error.

I think we should introduce
```objc
- (BOOL)evaluateServerTrust:(SecTrustRef)serverTrust
                  forDomain:(NSString *)domain
                      error:(NSError **)error
```
, construct a better error and make it bubble up to the `AFHTTPSessionManager` failure handlers.

**Comment by kcharwood** [comment]
I wonder if we should be using `NSURLSessionAuthChallengeRejectProtectionSpace` instead of `NSURLSessionAuthChallengeCancelAuthenticationChallenge`.

```
/*
 * Disposition options for various delegate messages
 */
typedef NS_ENUM(NSInteger, NSURLSessionAuthChallengeDisposition) {
    NSURLSessionAuthChallengeUseCredential = 0,                                       /* Use the specified credential, which may be nil */
    NSURLSessionAuthChallengePerformDefaultHandling = 1,                              /* Default handling for the challenge - as if this delegate were not implemented; the credential parameter is ignored. */
    NSURLSessionAuthChallengeCancelAuthenticationChallenge = 2,                       /* The entire request will be canceled; the credential parameter is ignored. */
    NSURLSessionAuthChallengeRejectProtectionSpace = 3,                               /* This challenge is rejected and the next authentication protection space should be tried; the credential parameter is ignored. */
} NS_ENUM_AVAILABLE(NSURLSESSION_AVAILABLE, 7_0);
```

**Comment by 0xced** [comment]
Yes, this is much better! Here is the error you get when using `NSURLSessionAuthChallengeRejectProtectionSpace`:

> Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrust 0x10041f6f0 [0x7fff7a706390]>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<SecCertificate 0x10240d660 [0x7fff7a706390]>",
    "<SecCertificate 0x10240d8a0 [0x7fff7a706390]>"
), NSUnderlyingError=0x60000004d830 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrust 0x10041f6f0 [0x7fff7a706390]>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<SecCertificate 0x10240d660 [0x7fff7a706390]>",
    "<SecCertificate 0x10240d8a0 [0x7fff7a706390]>"
)}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.app.net/stream/0/posts/stream/global, NSErrorFailingURLStringKey=https://api.app.net/stream/0/posts/stream/global, NSErrorClientCertificateStateKey=0}

**Comment by kcharwood** [comment]
Yep that looks _much_ better. Want to whip up the PR? Maybe add a test to verify the error?

**Comment by 0xced** [comment]
Yep, will take care of that. What’s the policy regarding v2 and v3? Should I make two PR or are you manually cherry-picking ?

**Comment by kcharwood** [comment]
At this point, we're pushing all changes to v3, unless its a critical security/stability fix. No planned functionality changes in v2 going forward.

**Comment by kcharwood** [comment]
Once we remove the beta tag on v3, we'll push v3 to master.

**Comment by 0xced** [comment]
It looked like a very simple issue to solve but of course it's not! The error differs if the code is run from an app or from unit tests.

**Comment by kcharwood** [comment]
What are the two errors?

**Comment by 0xced** [comment]
The error in unit test is `NSURLErrorServerCertificateUntrusted` (-1202) but the error in the demo app is `NSURLErrorSecureConnectionFailed` (-1200). I’m connecting to httpbin.org with a google.com pinned certificate to generate this error.

**Comment by kcharwood** [comment]
That is _very_ interesting. Want to push it up and let me poke around? Maybe we can push it up to travis and see if there are any differences in iOS version as well.

**Comment by 0xced** [comment]
I just pushed my `invalidServerTrust-better-error` branch. Do you want me to create a PR to see what happens on Travis?

**Comment by kcharwood** [comment]
Ya sure lets try that, and then we move the discussion there. :beers:

**Comment by kcharwood** [comment]
See #3169 for ongoing discussion
