### ISSUE TITLE
Root level certificates weakens certificate pinning

### ISSUE THREAD

**Issue by pragmapilot** [AFNetworking/AFNetworking#3190]
Hi,

AFNetworking 2.6.3 seems to be allowing connections to sites with the *.google.com certificate when configured to use AFSSLPinningModeCertificate option and when using the "Geo Trust Global CA." certificate. 

I set a small test app for demo purposes (look no further than in AppDelegate.m as all relevant code is there) that configures AFNetworking to run in AFSSLPinningModeCertificate and does a series of GET requests to different HTTPS URLs. Under this scenario they all fail except the ones which present the *.google.com certificate. This refers to all URLs in google domain, plus youtube.com which also features the same certificate chain. The app just contains one certificate "Geo Trust Global CA.". 

You can find the test app here:
https://github.com/pragmapilot/AFNGoogleCertificatePinning/tree/master/AFNGoogleCertificatePinning

I would expect the following behaviours:

1) the entire certificate chain must be matched in order to connect to a server under AFSSLPinningModeCertificate
2) AFNetworking should ignore the *.google.com certificate as iOS9 seems to be blocking this certificate natively (as per https://support.apple.com/en-us/HT205205; see the "Blocked certificates" section).

Is the described behaviour (ie, connections to *.google.com established) expected?

Thanks in advance.

**Comment by pragmapilot** [comment]
I did a little debug and traced the issue to AFSecurityPolicy.m method:
 
    - (BOOL)evaluateServerTrust:(SecTrustRef)serverTrust
                      forDomain:(NSString *)domain

There, on the case for AFSSLPinningModeCertificate we can find code that returns YES in case at least one certificate in the server chain is found on the pinned certificates list. Here's the code:

```objc

case AFSSLPinningModeCertificate: {
            (...)
            NSUInteger trustedCertificateCount = 0;
            for (NSData *trustChainCertificate in serverCertificates) {
                if ([self.pinnedCertificates containsObject:trustChainCertificate]) {
                    trustedCertificateCount++;
                }
            }
            return trustedCertificateCount > 0;

```
I was able to trace an earlier (v2.5.0) implementation of this method with the following code:

```objc
case AFSSLPinningModeCertificate: {
            (...)
             NSUInteger trustedCertificateCount = 0;
            for (NSData *trustChainCertificate in serverCertificates) {
                if ([self.pinnedCertificates containsObject:trustChainCertificate]) {
                    trustedCertificateCount++;
                }
            }

            return trustedCertificateCount == [serverCertificates count];
```

Here the entire chain is validated.

I understand that might be desirable to relax a bit the constraints in order to allow pinning to intermediate certificates. But on the reverse side, by pinning to a top-level certificate like "Geo Trust Global CA." we are enabling connections to ANY server that has a certificate like that. 

What would be the official advice to prevent this behaviour?

Thanks in advance.

**Comment by pragmapilot** [comment]
Changed the title to better reflect the cause described on my last comment.

**Comment by kcharwood** [comment]
I believe this is expected behavior.

Take a look at the [2.6.0 changelog](https://github.com/AFNetworking/AFNetworking/blob/master/CHANGELOG.md#important-upgrade-notes), as well as #2744 for a full discussion on that change. 

In this case, a developer should decide what level they want to pin against to determine how much security they want to add to their connection. Once that decision has been made, there is no point in validating any more of the chain above that because the certificate itself is a derivative of the valid parents at the point.

By added the certificate yourself, it is adding it to the trust, therefore bypassing the blocked certificates of iOS 9.

**Comment by pragmapilot** [comment]
Makes sense to me. So if one wants to pin to intermediate certificate it can do so, if one wants to pin the leaf it also works.

Thanks for the clarification.
