### ISSUE TITLE
library not found for -lAFNetworking

### ISSUE THREAD

**Issue by Bruno-Piccinin-RealComm** [AFNetworking/AFNetworking#3192]
I tried to install AFNetworking as a Pod with Cocoapods v0.38.2 but XCode always shows me this error

`ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

This is not the first time that I try to use AFNetworking. Infact some time ago it worked perfectly but from some days it started to give me that error because i reinstalled the pods running command 

`pod install`

Maybe the problem is not the AFNetworking but something on my project settings, but I didn't change anything.
Can someone help me?

**Comment by kcharwood** [comment]
What version of Xcode are you using? This is most likely a Cocoapods issue, not an AFNetworking issue. 

Can you push up an example to Github demonstrating the problem? Does it work for fresh project?

**Comment by Bruno-Piccinin-RealComm** [comment]
I have the same problem with XCode 7.1 and XCode 6.4.
It seems like cocoapods issue as you said or maybe something setted wrong on my project.
What can determinate this error?

**Comment by kcharwood** [comment]
I'd go down the troubleshooting steps of cocoapods version checking, installing it in a clean project, reviewing project settings, etc. This issue falls outside the scope of the AFNetworking project, so I am going to close this one out. I'd recommend directing your question to forum more suited for support, like StackOverflow. We use the issues list on Github for tracking bugs and feature requests directly related to AFNetworking.

:beers:

**Comment by gholias** [comment]
Did you find a solution for this problem? Im also facing the same issue

**Comment by Bruno-Piccinin-RealComm** [comment]
Not yet. I tried to install AFNetworking pod with varius version of cocoapods but nothing solve my problem. I'm starting to think maybe it depends from versione of iOS target version of my application, but I can't change it because i need it to run from specific version of iOS. 
Have you any ideas @gholias ?

**Comment by gholias** [comment]
No and it is really frustrating...
I think I will have to add AFNetworking without cocoapods

**Comment by manpreetg** [comment]
its because of use_framework.

**Comment by altncmd** [comment]
manpreetg <---------- He is right!!!-----------> **it`s because of use_framework.**
