### ISSUE TITLE
ios https error

### ISSUE THREAD

**Issue by iDeveloperXiaoyao** [AFNetworking/AFNetworking#3194]
for 3.0beta2
i set policy.allowInvalidCertificates = YES,
get request response error,

```
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo={NSUnderlyingError=0x7fc2e2c70a40 {Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7fc2e2e64ed0>
```

why?

**Comment by iDeveloperXiaoyao** [comment]
{ status code: 403, headers {
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Type" = "text/html";
    Date = "Fri, 04 Dec 2015 10:32:21 GMT";
    Server = "nginx/1.4.7";
    "Transfer-Encoding" = Identity;
    }
I set Content-Type = application/json, but it changed to "text/html". why? please help me.

**Comment by gwynantj** [comment]
This has got nothing to do with AFNetworking or invalid certificates. The resource you tried to access on the server is protected, hence you get a 403 forbidden response.

Questions like this need to be asked on [Stackoverflow](www.stackoverflow.com)

**Comment by iDeveloperXiaoyao** [comment]
but when i used the earlier version(AFNetworking), it was ok.
error happend on v3.0

**Comment by gwynantj** [comment]
Ok, without a little more context I can't help you very much. Have you tried setting the `Accept` header to `application/json`?

**Comment by iDeveloperXiaoyao** [comment]
[self.manager.requestSerializer setValue:@"application/json" forHTTPHeaderField:@"Accept"]

**Comment by kcharwood** [comment]
As @gwynantj mentioned, a 403 would come back from your server. Most likely, something is wrong with your request. Could you post the full request that worked previously, and the request being generated here?

This most likely comes down to a configuration issue on your end, so looking at all of the request headers will probably show the difference.

**Comment by kcharwood** [comment]
I'm going to close this out. If find anything that specifically points to AFNetworking as the problem, please feel free to reopen this issue!

Thanks!

:beers:

**Comment by firstpixel** [comment]
Is there any changes on how to send header parameters? I'm having same problem, was working on AFNetworking prior version, just updated the project and got this, I removed the server side check for the header token, and it worked, so it seems something changed on how to send headers parameters.

was using this code :

`- (NSURLSessionDataTask *)dataTaskWithRequest:(NSURLRequest *)request completionHandler:(void (^)(NSURLResponse *, id, NSError *))completionHandler
{
    
    NSMutableURLRequest *req = (NSMutableURLRequest *)request;

    [req setValue:[[GlobalSingleton sharedInstance] accessToken] forHTTPHeaderField:@"x-access-token"];
    return [super dataTaskWithRequest:req completionHandler:completionHandler];
}
`
