### ISSUE TITLE
AFURLSessionManager crashes with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by SeanAsby** [AFNetworking/AFNetworking#3195]
I am trying to upload multiple files in the background in my iOS application. I based my code on the **Creating an Upload Task for a Multi-Part Request, with Progress**, example. When I construct AFURLSessionManager with **[NSURLSessionConfiguration defaultSessionConfiguration]]** everything is working as expected. However when I try to use **[NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:[[NSUUID UUID] UUIDString]]]** to enable background upload, the application crashes with  EXC_BAD_ACCESS in the AFNetworking library. I have attemped to ask for help/insight on stackoverflow without success: http://stackoverflow.com/questions/34048865/afurlsessionmanager-crashes-with-exc-bad-access 

Has anyone else run into this issue before? It seems more and more like a bug. See stackoverflow post for complete code

**Comment by kcharwood** [comment]
Do you have any more information around the crash it self? Can you provide a full stack trace?

**Comment by SeanAsby** [comment]
Here are some screenshots from the stacktrace and where in the library it is crashing. 
![screen shot 2015-12-08 at 09 58 55](https://cloud.githubusercontent.com/assets/3429308/11651641/a6eee982-9d92-11e5-99a9-ba8acd972b62.png)
![screen shot 2015-12-08 at 09 59 10](https://cloud.githubusercontent.com/assets/3429308/11651642/aa4484a2-9d92-11e5-8472-bf19ea1563e5.png)

**Comment by LinkedHK** [comment]
The same issue
https://github.com/AFNetworking/AFNetworking/issues/3203
. Upload with Streamed request is not possible in the background mode. as stated in docs
https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/UsingNSURLSession.html
You have to use the  AFURLSessionManager uploadTaskWithRequest
But it's unclear how to include request parameters. (look in the issue above)

**Comment by SeanAsby** [comment]
I tried changing my code to use ```uploadTaskWithRequest``` instead of ```uploadTaskWithStreamedRequest```, but this produced the same results when using ```[NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:@"MyID"]]```

**Comment by phoney** [comment]
Make sure you use the same identifier each time your app launches. You're expected to use something like @"com.mycompany.myapplication" That's how your app reconnects to the transfers that were started in a previous run of your app but completed when your app is not running.
