### ISSUE TITLE
POST problems when parameters is kind of NSString

### ISSUE THREAD

**Issue by shiyingyan** [AFNetworking/AFNetworking#3200]
Now it has one new problems and the old problem is still there when I post String:

1. Yes ,it still can`t work. I know you fix the problems that the key is null,but the '=' is still there ,it still not work. 
2. new problem is encoding. 

For example, what I post is "Great minds think alike=", but I print the request.HttpBody  is "=Great minds think alike%3D" when the request fails.  I read your code and the reason is you invoke method stringByAddingPercentEncodingWithAllowedCharacters： in 
function static NSString * AFPercentEscapedStringFromString(NSString *string) ;
in  AFURLRequestSericalization.m file.

I don`t know why encoding,so I remove the invocation in function AFPercentEscapedStringFromString and I modify the instance method URLEncodedStringValue :
 then it can meet my needs and work for me .

 codes after modification:

    static NSString * AFPercentEscapedStringFromString(NSString *string) {
    static NSString * const kAFCharactersGeneralDelimitersToEncode = @":#[]@"; // does not include "?" or "/" due to RFC 3986 - Section 3.4
    static NSString * const kAFCharactersSubDelimitersToEncode = @"!$&'()*+,;=";

    NSMutableCharacterSet * allowedCharacterSet = [[NSCharacterSet URLQueryAllowedCharacterSet] mutableCopy];
    [allowedCharacterSet removeCharactersInString:[kAFCharactersGeneralDelimitersToEncode stringByAppendingString:kAFCharactersSubDelimitersToEncode]];
	// FIXME: https://github.com/AFNetworking/AFNetworking/pull/3028
    // return [string stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacterSet];

    static NSUInteger const batchSize = 50;

    NSUInteger index = 0;
    NSMutableString *escaped = @"".mutableCopy;

    while (index < string.length) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wgnu"
        NSUInteger length = MIN(string.length - index, batchSize);
    #pragma GCC diagnostic pop
        NSRange range = NSMakeRange(index, length);

        // To avoid breaking up character sequences such as 👴🏻👮🏽
        range = [string rangeOfComposedCharacterSequencesForRange:range];

        NSString *substring = [string substringWithRange:range];
        
        //remove 2 lines as following .
        //NSString *encoded = [substring stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacterSet];
        //[escaped appendString:encoded];
        [escaped appendString:substring];

        index += range.length;
    }
	return escaped;
    }

    - (NSString *)URLEncodedStringValue {
    if (!self.value || [self.value isEqual:[NSNull null]]) {
        return AFPercentEscapedStringFromString([self.field description]);
    } else {
        //add 3 lines as following to filter field when field is null
        if( !self.field || [self.field isEqual:[NSNull null]] ){
            return AFPercentEscapedStringFromString([self.value description]);
        }
        return [NSString stringWithFormat:@"%@=%@", AFPercentEscapedStringFromString([self.field description]), AFPercentEscapedStringFromString([self.value description])];
     }
    }

**Comment by kcharwood** [comment]
Hi @shiyingyan,

Could you push up a clear example demonstrating the problem? Also, what is the expected output of your POST? Just the raw text `Great minds think alike=`?

**Comment by shiyingyan** [comment]
What  I want to push is "c3VWDPOpupjYjn0S0P6bn0sv8ML+ncPlHLggjK6iVceH24QPhHrsB4ts9E1TkCeJ2/13DM74BfHbGRTbsYDGhFmdnVCD9Qzi8tItQMfHbfleZKXStdvCpO4mafHqKGjru1CRGdfFmQ3FYo64OXby6l4af5v//kxwKzOdnqpFjp0=".  
But the request.HttpBody is "=c3VWDPOpupjYjn0S0P6bn0sv8ML%2BncPlHLggjK6iVceH24QPhHrsB4ts9E1TkCeJ2/13DM74BfHbGRTbsYDGhFmdnVCD9Qzi8tItQMfHbfleZKXStdvCpO4mafHqKGjru1CRGdfFmQ3FYo64OXby6l4af5v//kxwKzOdnqpFjp0%3D"
Because the string I want to push is an encrypted string and then the service get and decrypt it .
 So what I expect out of My POST is what I want to push.

**Comment by kcharwood** [comment]
By default, the `AFHTTPRequestSerializer` will create POSTs that are `application/x-www-form-urlencoded`. If you want plain text to be POST'd, I'd recommend subclassing `AFHTTPRequestSerializer` and overriding `requestWithMethod:URLString:parameters:error:` to get the behavior you need for your specific use case.

**Comment by shiyingyan** [comment]
Obviously, problem is not here. The first equal sign "=" is not reserved if POSTs are application/x-www-form-urlencoded. 
Indeed, following codes were not executed when I tracking
     ` if (![mutableRequest valueForHTTPHeaderField:@"Content-Type"]) {`
             ` [mutableRequest setValue:@"application/x-www-form-urlencoded"        forHTTPHeaderField:@"Content-Type"];`
     ` }`
     in method `requestBySerializingRequest:withParameters:error:`  in file AFURLRequestSerialization.m
because I specify "text/plain" for POSTs  as following      
     `[self.httpRequestOperationManager.requestSerializer setValue:@"text/plain"     forHTTPHeaderField:@"Content-Type"];`

What  do you mean is that what I did not function and  I must overriding  `requstWithMethod:URLString:parameters:error: `?

**Comment by tiantian4tian** [comment]
Have you solve the problem？I come accross the same problem,I have try many methods,but can't figure it out.

**Comment by shiyingyan** [comment]
Default RequestSerialization is AFJSONRequestSerialization , so  parameters  will be parsed by JSON format and following method will be invoked(Attention, equal-sign).

Following method 'URLEncodedStringValue' is in file 'AFURLRequestSerialization.m'.

`- (NSString *)URLEncodedStringValue {
    if (!self.value || [self.value isEqual:[NSNull null]]) {
        return AFPercentEscapedStringFromString([self.field description]);
    } else {
        return [NSString stringWithFormat:@"%@=%@", AFPercentEscapedStringFromString([self.field description]), AFPercentEscapedStringFromString([self.value description])];
    }
}`

**Comment by y1024** [comment]
- (NSString *)URLEncodedStringValue {
    if (!self.value || [self.value isEqual:[NSNull null]]) {
        return AFPercentEscapedStringFromString([self.field description]);
    }
    else if (!self.field) {
        return self.value;
    }
    else {
        return [NSString stringWithFormat:@"%@=%@", AFPercentEscapedStringFromString([self.field description]), AFPercentEscapedStringFromString([self.value description])];
    }
}
