### ISSUE TITLE
Regarding an issue #2436

### ISSUE THREAD

**Issue by LinkedHK** [AFNetworking/AFNetworking#3203]
I'm facing with the same problem as described here
https://github.com/AFNetworking/AFNetworking/issues/2436

an issue was closed without explaining a reason. 

The problem is that an app crashes when upload task is configured to be performed  in the background calling  a method  ```AFURLSessionManager uploadTaskWithStreamedRequest```

NSURLSession Configuration example:
```
NSURLSessionConfiguration * sconfig = [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier: backgroundSessionId];
    sconfig.sessionSendsLaunchEvents = YES;
    sconfig.discretionary = YES;
```
upload in the background works  with the method ``` AFURLSessionManager uploadTaskWithRequest. ```  but for some reason it doesn't include request parameters but only file data itself. Here is the request 
```
NSMutableURLRequest *urlRequest = [[AFHTTPRequestSerializer serializer]multipartFormRequestWithMethod:@"POST" URLString:uploadUrlStr parameters: params constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
       
	[formData appendPartWithFileURL:entity.fileUrl  name:@"data" error:&fileappenderror];

} error:nil];
```
if you make an upload request you will see that all parameters included in request are missing. but only   the file has been uploaded.

**Comment by kcharwood** [comment]
Would you be able to create a test case in the 3.0.0 branch? If we could get a reproducible failure there, that would be very helpful to track down and ensure that isn't a problem going forward.

**Comment by LinkedHK** [comment]
Sure. Thank you for your input. I will report results later

**Comment by LinkedHK** [comment]
@kcharwood  Hi. Done. It's about 150 Lines of code. Shall I submit the pull request or just insert it here (or pastbin) to check the code?

**Comment by kcharwood** [comment]
Yes feel free to up a PR, or just a forked branch and link it here, and I can work off of that!
