### ISSUE TITLE
Help, how to dea with library not found for -lAFNetworking in Xcode

### ISSUE THREAD

**Issue by iZervy** [AFNetworking/AFNetworking#3206]
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kcharwood** [comment]
You are most likely battling a CocoaPods configuration issue here. Please check your Xcode project is properly configured based on the CocoaPods Help information when running `pod install`

:beers:

**Comment by gholias** [comment]
Im having the same issue, no luck so far
