### ISSUE TITLE
'GET:parameters:success:failure:' is deprecated

### ISSUE THREAD

**Issue by ay8s** [AFNetworking/AFNetworking#3212]
Not sure if this is intended and the migration guide is just slightly out of date. Using the AFNetworking 3.x code samples for the new AFHTTPSessionManager returning deprecated message.

https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide

Apologies if I'm missing something here. Using 3.0.0 via Cocoapods.

**Comment by ay8s** [comment]
Looks like may just need to update the migration guide to include the progress API. 

https://github.com/AFNetworking/AFNetworking/commit/2adeda5d44a2374fa2d51f26a9a8f4620297fd8b

**Comment by kcharwood** [comment]
Thanks! I just updated the migration guide. The new methods have a progress progress parameter, the deprecated methods will be removed in a future version.

:beers:

**Comment by ay8s** [comment]
Awesome. Migrated all of our networking in just under 2 hours, great work! :tada:
