### ISSUE TITLE
QUESTION: batchOfRequestOperations and addOperations

### ISSUE THREAD

**Issue by loretoparisi** [AFNetworking/AFNetworking#3213]
I have seen a lot of implementations when queuing ```NSOperation``` like having a batch of operations

```objective-c
NSArray *ops = [AFURLConnectionOperation batchOfRequestOperations:operations progressBlock:^(NSUInteger numberOfFinishedOperations, NSUInteger totalNumberOfOperations) {
                LogDebug(TAG, ([NSString stringWithFormat:@"%lu of %lu downloads copmleted (or an error)",
                                (unsigned long)numberOfFinishedOperations,
                                (unsigned long)totalNumberOfOperations]));
            } completionBlock:^(NSArray *operations) { }];
```

and then adding to the current (or main) ```NSOperationQueue``` like

```objective-c
[[NSOperationQueue mainQueue] addOperations:ops waitUntilFinished:NO];
```

Now, supposed that I have already configured the ```AFHTTPRequestOperationManager``` operation queue like:

```objective-c
self.requestManager = [AFHTTPRequestOperationManager manager];
[[self.requestManager operationQueue] setMaxConcurrentOperationCount:MXMRequestOperationQueueMaxConcurrentOperationCount];
```

My wonder is

- Is ```addOperations``` actually necessary (like to speed up execution)?
- Will the batch of operations handled by the ```self.requestManager operationQueue```?
- There is any better implementation?

Last, but not least, supposed to have something like

```objective-c
- (void)enqueueOperation:(AFHTTPRequestOperation *)operation
{
    [_operarations addObject:operation];
    NSArray *batchOperations = [AFHTTPRequestOperation batchOfRequestOperations:_operations progressBlock:^(NSUInteger numberOfFinishedOperations, NSUInteger totalNumberOfOperations) {
        /*[[MXMLogger sharedLogger] debug:@"Completed %d operations of %d", numberOfFinishedOperations,
         totalNumberOfOperations];*/
    } completionBlock:^(NSArray *_operations) {
        //[[MXMLogger sharedLogger] debug:@"Completed %d operations", [_operations count]];
    }];
    [[self.requestManager operationQueue] addOperations:batchOperations waitUntilFinished:NO];
}
```

Which is the best way to handle a ```NSMutableArray``` (synchronized maybe) of AFHTTPRequestOperation in order to execute the batch of operations on this array, and then remove from it. Is any way for AFHTTPRequestOperation to handle this?

Thank you.

**Comment by kcharwood** [comment]
Hi @loretoparisi

We've now deprecated support for all of the `NSURLConnection` based API's (like `AFHTTPRequestOperation`). It's best to post questions like these on StackOverflow, as we use Github for feature request and bug tracking, allowing us to focus on maintaining the library.

If you haven't migrated over to the 3.0 branch yet, I'd recommend doing so!

:beers:

**Comment by loretoparisi** [comment]
@kcharwood Thanks for the update, hopefully migrating to 3.0 in Q1 2016.
