### ISSUE TITLE
AFHTTPClient Requests Timeout  when flooded with requests

### ISSUE THREAD

**Issue by anishguptaios** [AFNetworking/AFNetworking#3218]
I have been using Afnetworking for one of my application, as per the requirements there could be a scenario when there can be loads of requests at one time. However, while doing that i am getting requests time outs as an error. While searching, i found that by increasing the maxconcurrentoperations value i can resolve the issue. I have done that and it is working fine, but for that i need to add the framework manually and need to do changes manually. I very much like to use cocoapods. Is there any way that i get the maxconcurrentoperations value increased via pods only.TIA

Regards
Anish

**Comment by kcharwood** [comment]
Hi @anishguptaios 

`AFHTTPClient` is part of AFNetworking 1.x, and is no longer explicitly supported and there are no plans to provide any further updates to that line. I'd recommend updating to a newer version of AFNetworking if possible.

:beers:
