### ISSUE TITLE
cannot decode raw data . help！

### ISSUE THREAD

**Issue by mistak** [AFNetworking/AFNetworking#3219]
http、post 、  上传接收数据格式都为二进制，然后现在一直报错as connectionerror = Error Domain=NSURLErrorDomain Code=-1015 "cannot decode raw data" UserInfo={NSUnderlyingError=0x7fad5a77a950 {Error Domain=kCFErrorDomainCFNetwork Code=-1015 "cannot decode raw data ，谁能帮助我吗？

**Comment by kcharwood** [comment]
This most likely is a request/response serializer content type issue. Please ensure they are properly configured.

Please direct these types of questions to StackOverflow or something equivalent. Github is for bugs and feature requests, letting us focus on improving the library.

Thanks!

:beers:
