### ISSUE TITLE
AFNetworking receives responses from SDWebImage's cache

### ISSUE THREAD

**Issue by enwar3** [AFNetworking/AFNetworking#3224]
Really perplexing bug we have.

We're using AFNetworking and Overcoat to make HTTP requests that expect a JSON object back and we're using SDWebImage to prefetch some images. But the strange thing is, sometimes the response that AFNetworking gets is the image that SDWebImage is prefetching.

How is this possible? I assumed that SDWebImage and AFNetworking wouldn't share state.

However, it looks like SDWebImage does use NSURLCache - could this cause issues / conflicts with AFNetworking?

**Comment by kcharwood** [comment]
Yes that is correct. By default, `AFHTTPSessionManager` is [configured](`https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLSessionManager.m#L518`) with a default session configuration, which uses the shared URL cache. You can change the URL cache on the session configuration to a custom one if you so choose.

:beers:
