### ISSUE TITLE
UIRefreshControl+AFNetworking.h File not found error

### ISSUE THREAD

**Issue by srinadhK** [AFNetworking/AFNetworking#3226]
Hi Im getting UIRefreshControl+AFNetworking.h file not found error on my mac and some other Macs, when i change to other MAC, i'm not getting this type of issues. 

 I'm wonder why im facing such error only on my MAC and Some other Macs only. But  its working some other MACs.

**Comment by kcharwood** [comment]
@srinadhK We have [tests](https://github.com/AFNetworking/AFNetworking/blob/master/Tests/Tests/AFUIRefreshControlTests.m) validating those files are available through the framework. This is most likely some sort of project configuration on your end. 

We use the issues list on Github for tracking bugs and feature requests directly related to AFNetworking so we can focus on improving the project.

Thanks!

:beers:
