### ISSUE TITLE
AFImageResponseSerializer no longer serializing images on watchOS

### ISSUE THREAD

**Issue by lessthanyouthink** [AFNetworking/AFNetworking#3228]
Hi folks,

In migrating from AFNetworking 2.6.0 to 3.0.2 I discovered that using ```AFImageResponseSerializer``` with ```AFURLSessionManager``` to download images via ```dataTaskWithRequest:completionHandler:``` no longer returns a non-nil ```responseObject``` on watchOS (2.0). It looks like when the preprocessor platform checks were moved from using ```__IPHONE_OS_VERSION_MIN_REQUIRED``` to ```TARGET_OS_IOS``` and the like some of the checks ended up missing tvOS and watchOS. I'm preparing a pull request that fixes the issue, which I'll attach shortly 🙂.

Here's a snippet of sample code that illustrates the issue:

```
AFURLSessionManager *manager = [[AFURLSessionManager alloc] init];
manager.responseSerializer = [AFImageResponseSerializer serializer];

NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:@"http://example.com/somevalidimage.jpg"]];

NSURLSessionDataTask *task = [manager dataTaskWithRequest:urlRequest completionHandler:^(NSURLResponse * _Nonnull response, id  _Nonnull responseObject, NSError * _Nonnull error) {
        //responseObject is unexpectedly nil here when the response is valid
}];
 
[task resume];

```

**Comment by kcharwood** [comment]
See #3229
