### ISSUE TITLE
Having trouble updating to version 3.0+

### ISSUE THREAD

**Issue by enwar3** [AFNetworking/AFNetworking#3230]
I added `pod 'AFNetworking', '~> 3.0'` to my podfile but keep getting this error:

```
[!] There are only pre-release versions available satisfying the following requirements:

	'AFNetworking/NSURLConnection', '>= 0'

You should explicitly specify the version in order to install a pre-release version
```

Any thoughts on what I could be doing wrong here?

**Comment by kcharwood** [comment]
Have you tried running `pod repo update`? Have you tried using `pod 'AFNetworking', '~> 3.0.0'. It may also be helpful to post your Podfile.

**Comment by enwar3** [comment]
@kcharwood Thanks for the suggestions!! I tried both of those things but got the same behavior.

Here's the podfile, if it helps:
```
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.6'

pod 'Mantle', '~> 1.5'

pod 'Overcoat', '~> 3.0'

pod 'NSDate-Time-Ago'

pod 'APAddressBook'

pod 'RMUniversalAlert'

pod 'SDWebImage'

pod 'Toast', '~> 2.4'

pod 'UICountingLabel'

pod 'Branch'

pod 'HockeySDK'

pod 'MBProgressHUD', '~> 0.9.1'

pod 'DCAnimationKit'
```

**Comment by LinkedHK** [comment]
AFNetworking supports platform :ios, '8.0' and above

**Comment by enwar3** [comment]
@LinkedHK On the main README it says AFNetworking 3.x requires a minimum target of iOS 7. It's possible it's outdated -where did you get the iOS 8 requirement?

**Comment by LinkedHK** [comment]
@enwar3 Yeah. I was wrong. Sorry.

**Comment by kcharwood** [comment]
I'm wondering if you have a dependency that requires 'AFNetworking/NSURLConnection`

**Comment by kcharwood** [comment]
It looks like `Overcoat` is the issue. Looking at their repo, it looks like 3.0 support is now in master.

https://github.com/Overcoat/Overcoat/issues/113

:beers:

**Comment by enwar3** [comment]
Thanks @kcharwood!!

**Comment by kcharwood** [comment]
:beers:
