### ISSUE TITLE
Can't get the response from server for Http status code 500

### ISSUE THREAD

**Issue by Shawkaine** [AFNetworking/AFNetworking#3232]
When using AFNetworking 2.x, I used AFHTTPRequestOperationManager for POST request. The backend will return code 500 for error , and I was able to get the response string from AFHTTPRequestOperation *operation, operation.responseString .

But when it comes to AFNetworking 3.0, using AFHTTPSessionManager, how am I suppsed to get the error response?

**Comment by kcharwood** [comment]
Hi @Shawkaine 

Check the userInfo of the error. There should be a `AFNetworkingOperationFailingURLResponseDataErrorKey` with the data there.

:beers:

**Comment by Shawkaine** [comment]
@kcharwood Thx  :)  I found it by printing the error out. I'm able to access it by doing as following

    NSError *underError = error.userInfo[@"NSUnderlyingError"];
    NSData *responseData = underError.userInfo[@"com.alamofire.serialization.response.error.data"];

Are you planning to wrap it as a property? 'cause I feel like it'll come in handy in various situations. If so, when will that be?

Actually, the real reason driving me updating AFN is this wierd bug recently, which drives me crazy. My app is using AFN 2.x quit well, untill a few clients told me that they've received a lot of error warning telling them the network is down, and they can't get any data in app, while the other apps are working just fine on their devices. Though it happens frequently, sometimes it disappear and all went fine. And I barely can reproduce the bug. 
I put the error warning as displayed 

     - (void)setCompletionBlockWithSuccess:(void (^)(AFHTTPRequestOperation *operation, id responseObject))success
                              failure:(void (^)(AFHTTPRequestOperation *operation, NSError *error))failure
	{
    // completionBlock is manually nilled out in AFURLConnectionOperation to break the retain cycle.
	#pragma clang diagnostic push
	#pragma clang diagnostic ignored "-Warc-retain-cycles"
	#pragma clang diagnostic ignored "-Wgnu"
    self.completionBlock = ^{
        if (self.completionGroup) {
            dispatch_group_enter(self.completionGroup);
        }

        dispatch_async(http_request_operation_processing_queue(), ^{
            if (self.error) {
                if (failure) {
                        dispatch_async(dispatch_get_main_queue(), ^{
                            [MBProgressHUD hideHUD];
                            RTLog(@"-----%@",self.error.localizedDescription);

                            [MBProgressHUD showError:self.error.localizedDescription];
                        });



in case you've connected to the network with bad router or signal, which ReachabilityManager seems can't tell.  

And the error message is "a server with the specified hostname could not be found". I confirmed with them that when it shows, the network is working fine, live streaming, chatting,etc.  

The bug showed around for 2 weeks now. I change the AFN to 3.0, but still exist, one client says the frequency goes down, but another is still bothered so many times a day.

What exactly is going on? Could you please help me out?
Thanks very much for your time! I would really appreciate that if you help me with it ! T T

**Comment by kcharwood** [comment]
As discussed in this [issue](https://github.com/AFNetworking/AFNetworking/issues/2701), Reachability should not be used to gate an initial network request, and AFNetworking does not do that under hood. It is helpful for error reporting, and for triggering retries, but should not be used to block the initial request, per Apple recommendations.

**Comment by Shawkaine** [comment]
Yeah, but my situation isn't about Reachability, my error warning shows that the requests fail  
 even before it reaches out to the server. And it will last for quite a while with user keep trying , mean while , the network is fine, and other apps work just fine.  What's causing it? It seems to happen randomly.
