### ISSUE TITLE
AFNetworking 3.0 , how to handle queue requestOperation?

### ISSUE THREAD

**Issue by AbooJan** [AFNetworking/AFNetworking#3237]
In 2.x ，can use the AFHTTPRequestOperation , and add it to operationQueue. 
In 3.0 , param operationQueue just readonly.

then how to do it like in version 2.x ?
thank you very much!

**Comment by kcharwood** [comment]
Hi @AbooJan. `NSURLSession` and `NSURLSessionConfiguration` manage the tasks. The REST interface in `AFHTTPSessionManager` automatically calls `resume` on tasks created there, which get them added to the session queue. The interface in `AFURLSessionManager` does not, and you as the caller are responsible for calling resume to get it added to the session queue.

I'd recommend reading up on the NSURLSession docs.

:beers:
