### ISSUE TITLE
File downloading 

### ISSUE THREAD

**Issue by urvishagile** [AFNetworking/AFNetworking#3238]
Hello 

I have use afnetworking library for downloading files but last few days i have face the issue of  downloading file with cache data.

How can i get the cache data of perticulare request url.
Also please describe how to use following method with resume data.

[downloadTaskWithResumeData: progress: destination: completionHandler: ]

Please help me 

Thanks

**Comment by kcharwood** [comment]
Hi @urvishagile,

Questions like these are best suited for Stackoverflow. Github is for reporting bugs and feature requests, which allows to focus on maintaining the library.

I'd recommend checking out the download task documentation for [NSURLSession](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/instm/NSURLSession/downloadTaskWithResumeData:completionHandler:).

Thanks!

:beers:
