### ISSUE TITLE
Feature Request: Support GIFs

### ISSUE THREAD

**Issue by bawn** [AFNetworking/AFNetworking#3243]
I use GET method to download a gif 

```
AFImageResponseSerializer* serializer = [[AFImageResponseSerializer alloc] init];
        serializer.acceptableContentTypes = [NSSet setWithObjects:@"image/gif", @"image/jpg", @"image/png", nil];;
        self.manager.responseSerializer = serializer;


[self.manager GET:url parameters:argument progress:^(NSProgress * _Nonnull downloadProgress) {

        } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
           // responseObject is UIIimage 
        } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {

        }];
```

responseObject is must be UIIimage?  I want to be able to return directly NSData，not from UIImage. 

Anyone can help me

**Comment by kcharwood** [comment]
Hmm. That is a good question. I haven't done much work with gifs. It's possible we may need to add support for this. Feel free to put together a PR with any work you have put towards this.

**Comment by Remyoman** [comment]
It would be nice to have the NSData available as well, which would make it easier to support [FLAnimatedImage](https://github.com/Flipboard/FLAnimatedImage) for developers.

**Comment by kcharwood** [comment]
@Remyoman The best approach there would be to write your own response serializer that returns an FLAnimationImage. It would not be that hard to do :)

**Comment by Remyoman** [comment]
@kcharwood Not if using the UIKit extensions for setting the image with an URL. You would need a seperate category and you wouldn't be able to use the shared instance for the AFImageDownloader if I am correct.

**Comment by Remyoman** [comment]
@kcharwood I am still unsure how I would implement a UIKit extension that supports GIF files. This is mostly due to the way the AFImageDownloader does it's caching. Would you advise on just using a response serializer for handling GIF files?
