### ISSUE TITLE
memory leaks with responseObject

### ISSUE THREAD

**Issue by lynn87** [AFNetworking/AFNetworking#3247]
when I use instruments&leaks ，it prompt memory leaks with responseObject in AF，but I can't find any problem in source code，can anyone help me?THX.
<img width="1357" alt="2015-12-25 1 32 12" src="https://cloud.githubusercontent.com/assets/4514961/12000179/256d2c34-ab0c-11e5-8c87-94b4c74337bd.png">
![Uploading 屏幕快照 2015-12-25 下午1.32.20.png…]()
<img width="1363" alt="2015-12-25 1 32 31" src="https://cloud.githubusercontent.com/assets/4514961/12000178/256caf34-ab0c-11e5-9e91-51880d39d0df.png">

**Comment by lynn87** [comment]
It's other problem cause this,

**Comment by abccccc456** [comment]
A New guy for iOS , if I wanna study AFNetworking , what should i to read
