### ISSUE TITLE
执行pod search

### ISSUE THREAD

**Issue by kevin-geng** [AFNetworking/AFNetworking#3248]
执行pod search afnetworking并没有搜索到3.0，最高版本是2.5.4，这是为什么？
Mac 系统版本 10.11.2
![image](https://cloud.githubusercontent.com/assets/12066186/12000268/42167fbe-ab0e-11e5-928e-2b5a4ebfbd56.png)

**Comment by xuchendev** [comment]
try pod setup : ]

**Comment by kevin-geng** [comment]
@xuchendev thanks. I executed the command pod setup. but I got the same result.

**Comment by ShaoXinSen** [comment]
@xuchendev 
try `pod repo update`

**Comment by kevin-geng** [comment]
@thanks, i tried,but
![pod_update](https://cloud.githubusercontent.com/assets/12066186/12047857/7e7657ba-af0d-11e5-9d9c-a655ca84b443.png)

**Comment by ShaoXinSen** [comment]
@kevin-geng 
你的网络不太好, 目前国内的源好像没有很好的, 尝试下VPN代理再连接吧

<img width="707" alt="2015-12-30 16 08 01" src="https://cloud.githubusercontent.com/assets/13616801/12047998/d538722a-af0f-11e5-9cca-501dbef36f55.png">

**Comment by kevin-geng** [comment]
@ShaoXinSen 
好的，我试试。谢谢。

**Comment by kevin-geng** [comment]
@ShaoXinSen 
谢谢，我使用VPN成功了。
![cca037c3-af18-484d-b867-7e993bcbcd4f](https://cloud.githubusercontent.com/assets/12066186/12061893/a830bd74-afcc-11e5-82be-89a5db5bd663.png)

**Comment by kcharwood** [comment]
This appears to be an issue with your cocoapods setup, not an AFNetworking issue.

Thanks!
