### ISSUE TITLE
AFNetworking 3 add dependency?

### ISSUE THREAD

**Issue by fabiosoft** [AFNetworking/AFNetworking#3250]
With AFNetworking 3 how can i add dependency?
These requests must follow a sequence to work...
I have something like this in a for loop, but of course, if a GET request finishes before an other the entire sequence is wrong.

```obj-c
AFHTTPSessionManager *manager = [self sessionManager];
[manager.operationQueue setMaxConcurrentOperationCount:1];
NSString *url = [_hostName.absoluteString stringByAppendingPathComponent:keyboardPath];
[manager GET:url parameters:nil progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {

//do something

} // ... failure block
```

In AFNetworking 2 i used to do something like this:

```obj-c
AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:request];
[operation addDependency... 
```

But now `AFHTTPRequestOperation` doesn't exist anymore...

**Comment by kcharwood** [comment]
There is currently no NSOperation support in the NSURLSession based API's.

You'll need to manage this on your own. I'd certainly be interested in anyones ideas to make NSOperation more accessible for the AF/NSURLSession API's

**Comment by fabiosoft** [comment]
No more useful addDependency?
So i can't use AFNetworking 3.x for my goal... 

Thanks anyway.

**Comment by mohshinshah1903** [comment]
You can use https://github.com/csotiriou/AFNetworking-PromiseKit for sequential API Calls

**Comment by mohshin-shah** [comment]
You can use https://github.com/csotiriou/AFNetworking-PromiseKit for sequential API Calls
