### ISSUE TITLE
setTaskDidSendBodyDataBlock & uploadTaskWithStreamedRequest 's block different between 4s .

### ISSUE THREAD

**Issue by yanglezyq** [AFNetworking/AFNetworking#3251]
why difference between about 4s ?
It course the MBProgressHud stay in screen 4s  with 100% progress
![3333333333333](https://cloud.githubusercontent.com/assets/7953902/12031136/7a895db6-ae43-11e5-9ead-b6fa598bf167.jpg)

**Comment by kcharwood** [comment]
I'm confused? You can see those are clearly two different timestamps in the console from the left there. What are you expecting here?

**Comment by yanglezyq** [comment]
Yeah, It is two  different timestamps. The cause of the problem is that the service side need to be processed for a period of time (about 4 seconds), so, when the progress bar reaches 100%, it will suspend there about 4 seconds, which makes the user experience is very bad. What is the good solution?

**Comment by kcharwood** [comment]
You are tracking two different things. The upload progress _is_ complete, but the response does not come back in a timely manner.

There is no good way to track what you are trying to do, unless you merge together a few NSProgress's and manually calculate your server side delay times into it.
