### ISSUE TITLE
Uploaded PNG file is larger

### ISSUE THREAD

**Issue by crspybits** [AFNetworking/AFNetworking#3252]
http://stackoverflow.com/questions/34517582/how-can-i-prevent-modifications-of-a-png-file-uploaded-using-afnetworking-to-a-n

Any ideas?

Thanks!
Chris.

**Comment by crspybits** [comment]
I've now resolved this. It's not an issue with AFNetworking, but rather an issue with Apple altering PNG files that it copies to the app bundle. Thanks for the great tool guys!

**Comment by kcharwood** [comment]
Thanks!
