### ISSUE TITLE
Request should be nil if image was taken from cache

### ISSUE THREAD

**Issue by aryaxt** [AFNetworking/AFNetworking#3257]
Recently updated to 3,0 and having some issues?

On older version `setImageWithURLRequest` would have a null request in the closure if the image already existed in the cache, which makes sense because the request was not made. On 3.0 ythe request is never nil even if the image was already cached and no request was made to download the image.

```
[self setImageWithURLRequest:request placeholderImage:placeholder success:^(NSURLRequest *request, NSHTTPURLResponse *response, UIImage *image) {
        if (!request) { // image was cached
            [weakSelf setImage:image];
        }
        else {
            // Animate with fade
        }
```

**Comment by kcharwood** [comment]
The response will be nil if the image is pulled from the cache, as cited here in the [documentation](https://github.com/AFNetworking/AFNetworking/blob/master/UIKit%2BAFNetworking/UIImageView%2BAFNetworking.h#L92).

This changed in #2771

:beers:
