### ISSUE TITLE
AFHTTPSessionManager get old data and the header’s transport have two connection

### ISSUE THREAD

**Issue by luke001** [AFNetworking/AFNetworking#3264]
Xcode Version 7.2 (7c68)
Targeting iOS9.2
AFNetworking 3.0.+

Hi, i need u some help.
I use the latest version AF. When i used the class ‘AFHTTPSessionManager’ to get the api data. It return the old data just like cache data, and i captured the http in fiddler, i saw the headers contained two connection that values both are keep-alive.
    my code is below:
    NSString * url = @"http://ip:8000/users/me";
    //请求头
    NSString * token =accessToken;
    AFHTTPSessionManager *AFmanager = [AFHTTPSessionManager manager];
    AFmanager.securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeNone];
   AFmanager.requestSerializer = [AFHTTPRequestSerializer serializer];
  AFmanager.responseSerializer = [AFHTTPResponseSerializer serializer];
    [AFmanager.requestSerializer setValue:[NSString stringWithFormat:@"Bearer %@",token] forHTTPHeaderField:@"Authorization"];
    //[AFmanager.requestSerializer setValue:@"Connection" forHTTPHeaderField:@"Close"];
    [AFmanager GET:url parameters:nil progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        //
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        //
    }];

Thank you very much for the answer!

**Comment by leiyong316** [comment]
@luke001  如果不添加请求头只是普通的get会得到上一次的访问数据吗？

**Comment by pgawlowski** [comment]
Is it connected with cookies? I had a quite similar problem. After failed authorization (bad username/password) I was unable to clear authorization header with     [manager.requestSerializer clearAuthorizationHeader].

I had to use this method.

+ (void)clearAllCookies
{
    NSHTTPCookieStorage *cookieStorage = [NSHTTPCookieStorage sharedHTTPCookieStorage];
    for (NSHTTPCookie *each in cookieStorage.cookies) {
        [cookieStorage deleteCookie:each];
    }
}

and as well 

+ (void)eraseCredentials
{
    NSURLCredentialStorage *credentialsStorage = [NSURLCredentialStorage sharedCredentialStorage];
    NSDictionary *allCredentials = [credentialsStorage allCredentials];
    
    for (NSURLProtectionSpace *protectionSpace in allCredentials)
    {
        NSDictionary *credentials = [credentialsStorage credentialsForProtectionSpace:protectionSpace];
        for (NSString *credentialKey in credentials)
            [credentialsStorage removeCredential:[credentials objectForKey:credentialKey] forProtectionSpace:protectionSpace];
    }
}

**Comment by kcharwood** [comment]
Yes. This is most likely an underlying issue. AFNetworking leverages NSURLCache and the NSHTTPCookieManager, and does not interact directly with them. If you are running into caching issues, it is most likely at this layer.

If you identify a specific AF bug, please feel free to open a new issue.

:beers:
