### ISSUE TITLE
why  execute  the  didFinishEventsForBackgroundURLSession Block  in  dispatch_async(dispatch_get_main_queue()？

### ISSUE THREAD

**Issue by manwithstories** [AFNetworking/AFNetworking#3265]
AFURLSessionManager.m   Line 1162  
Can't wake up the main thread when  app   in  background.  
why  execute  the  didFinishEventsForBackgroundURLSession Block  in  dispatch_async(dispatch_get_main_queue)?

**Comment by kcharwood** [comment]
Are you seeing any issues on this front? The documentation seems to indicate this is ok, but I haven't tested it myself.

**Comment by manwithstories** [comment]
Yes,I was used the backgroundSessionConfigurationWithIdentifier created a AFHTTPSessionManager,and opened a NSURLSessionDownloadTask.
I used to find that Use device debugging  can't execute didFinishEventsForBackgroundURLSessionBlock
but if unused the dispatch_async(dispatch_get_main_queue) called didFinishEventsForBackgroundURLSessionBlock  it is OK.

You can go to try, thanks.

(My systemVersion Of iphone6Plus  is 9.2 )

**Comment by manwithstories** [comment]
?????
