### ISSUE TITLE
Download not resuming after app crash / force close

### ISSUE THREAD

**Issue by zkrige** [AFNetworking/AFNetworking#3267]
I've configured a AFURLSessionManager like this

``` Objective-C
- (AFURLSessionManager *)sharedManager {
    if (!_sharedManager) {
        NSString *sessionConfigurationIdentifier = [[NSBundle mainBundle] bundleIdentifier];
        NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:sessionConfigurationIdentifier];
        [configuration setRequestCachePolicy:NSURLRequestReturnCacheDataElseLoad];
        [configuration setTimeoutIntervalForRequest:kDefaultRequestTimeoutInterval];
        [configuration setTimeoutIntervalForResource:0];
        [configuration setDiscretionary:YES];
        [configuration setSessionSendsLaunchEvents:YES];
        if ([UIDevice currentDevice].majorVersion >= 9) {
            [configuration setShouldUseExtendedBackgroundIdleMode:YES];
        }
        NSURLCache *cache = [NSURLCache sharedURLCache];
        [configuration setURLCache:cache];
        _sharedManager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];
    }
    return _sharedManager;
}
```

If i force close my app or it crashes, and I recreate the download, the download is not using cached data, but instead is restarting from 0 bytes

**Comment by kcharwood** [comment]
Interesting. Would you be able to push up a small example to demo this and let me debug it?

I also haven't used `setShouldUseExtendedBackgroundIdleMode`, so I don't know what that affects here. The docs are scarce, and the link in the header 404's :(

**Comment by zkrige** [comment]
[DownloadTest.zip](https://github.com/AFNetworking/AFNetworking/files/90049/DownloadTest.zip)

This should cover it

**Comment by shantj** [comment]
@kcharwood hi, it has been a year, but the problem still exists!

**Comment by zkrige** [comment]
This issue persists in latest version. I am unable to resume any downloads. I correctly supply resume data, but all downloads are starting from 0
