### ISSUE TITLE
AFNetowrking 3.0 SSL certificate problems

### ISSUE THREAD

**Issue by BaronPod** [AFNetworking/AFNetworking#3269]
SSL error has occurred , unable to establish a secure connection to the server.

The following is part of the code certificate

// Certification Path
    NSString * cerPath = [[NSBundle mainBundle] pathForResource: @ "ssl" ofType: @ "cer"];
    NSLog (@ "SSL certificate path:% @", cerPath);
    // Import Certificate
    NSData * cerData = [NSData dataWithContentsOfFile: cerPath];
    
    // AFSSLPinningModeCertificate use certificate authentication mode
    AFSecurityPolicy * securityPolicy = [AFSecurityPolicy policyWithPinningMode: AFSSLPinningModeCertificate];
    
    // AllowInvalidCertificates whether to allow invalid certificates (ie self certificate), the default is NO
    // If you need to self certificate should be set to YES
    securityPolicy.allowInvalidCertificates = YES;
    
    // ValidatesDomainName need to verify whether the domain name, the default is YES
    // If the domain name with the requested certificate inconsistencies that need to be set to NO, as is set to NO, then, that the use of other agencies certified server certificate, you can establish a connection, this is very dangerous, the proposed open
    // Set to NO, mainly used in this case: the client request is a sub-domain, and is another name on the certificate. Because domain SSL certificate is independent, if the domain name is registered on the certificate www.google.com, then it can not be verified by mail.google.com; and of course, money can register domain wildcard * .google.com, But this is still more expensive.
    // If set to NO, the corresponding proposal to add their own domain validation logic.
    securityPolicy.validatesDomainName = YES;
    
    securityPolicy.pinnedCertificates = [NSSet setWithArray: @ [cerData]];
    
    return securityPolicy;

**Comment by wuqiong** [comment]
I encountered  the same problem this afternoon with AFNetworking(Tag 3.0.4),Xcode 7.2/iOS9.2 Simulator.

**Comment by kcharwood** [comment]
This is most likely related to an issue with App Transport Security, a new feature for iOS 9. Please check Apple's documentation for that.

:beers:
