### ISSUE TITLE
Progress blocks not called on main thread

### ISSUE THREAD

**Issue by wooster** [AFNetworking/AFNetworking#3271]
Similar to issue #411 for the operation based APIs, the progress blocks for the session APIs aren't being called on the main thread.

For session based APIs, the KVO observation callbacks are happening on Apple's work queue (eg `com.apple.NSURLSession-work`), so that is the queue the upload and download progress blocks are being called on.

Instead, it would be good to have these calls happen on the same work queue and group as the completion callbacks. This would be in line with the operation based APIs.

I discovered this problem when refactoring a codebase to use the new API, and hit a threading problem when calling into UIKit from a background queue. I suspect others will encounter this as they move to the session based API.

**Comment by kcharwood** [comment]
See my comments in #3272

:beers:
