### ISSUE TITLE
how can i use a sync request to upload file?

### ISSUE THREAD

**Issue by qiujiaheng2000** [AFNetworking/AFNetworking#3273]
I need a sync request to upload files by chunks in my App,and I need store the information of the unfinished upload file.so I want to make a sync request. tks!

**Comment by kcharwood** [comment]
Hi @qiujiaheng2000,

Synchronous requests are not a pattern we plan to support in AFNetworking. If you need to manage this yourself, you could use something like a `dispatch_group`, although I'd recommend to rethink your architecture and find a path to support async requests. Good luck :beers:

**Comment by qiujiaheng2000** [comment]
hi @kcharwood ,
thank you very much。
Can you give me some help ^_^
This is my old code use ASIRequest,I want to use AFNetworking to replace it.
 [NSObject performBlockOnBackground:^{
        
        @autoreleasepool {
            
            NSInteger nSentCount = 0 ;
            NSInteger nChunkSize = 10*1024 ;
            NSInteger index = -1 ;
            NSString* fileid ;
            
            if ([[ReachabilityMail reachabilityForInternetConnection]isReachableViaWiFi])
            {
                nChunkSize = 50*1024 ;
            }
            
            //get last result of upload 
            {
                NSString* last = [[LocalCache instance]getUploadStatus:filename];
                if (isValidString(last))
                {
                    NSDictionary* tmp = [last JSONValue];
                    fileid = GetStringFromDictionary(tmp, @"id");
                    nSentCount = [GetStringFromDictionary(tmp, @"sent") intValue];
                    index = [GetStringFromDictionary(tmp, @"index") intValue];
                }
            }
            
            [[UploadManager instance]addUpload:filename Request:(ASIHTTPRequest*)[NSNull null]];
            
            NSDate *uploadDate= [NSDate date];
            
            while (nSentCount<fileSize&&
                   ![[UploadManager instance]isUploadCanceled:filename])
            {
                ++index;
                
                //Calculate the current chunk 
               NSInteger nLeftCount = fileSize - nSentCount ;
                NSInteger nToSend = nLeftCount>nChunkSize ? nChunkSize : nLeftCount ;
                BOOL bLastChunk = nLeftCount<= nChunkSize ;
                NSRange subRange ;
                subRange.location = nSentCount ;
                subRange.length = nToSend ;
                
                //read the file
                [fileHandle seekToFileOffset:subRange.location];
                NSData* chunk =  [fileHandle readDataOfLength:subRange.length];
                
                //config http 
                HttpProgress* progressDelegate = [HttpProgress new];
                progressDelegate.fSentPercent = nSentCount/((float)fileSize);
                progressDelegate.fBlockPercentBase = nChunkSize/((float)fileSize);
                progressDelegate.currentTime=[NSDate date];
                progressDelegate.block = progress ;
                [progressDelegate setProgress:0];
                
                {
                    NSDate *currentDate = [NSDate date];
                    double time = [currentDate timeIntervalSinceDate:uploadDate];
                    long long speed = nChunkSize/time;
                    uploadDate=currentDate;
                    progressDelegate.uploadSpeed=speed;
                }
                
                ASIFormDataRequest* request=nil;
                request=[clientinst requestWithMethod:@"files/uploader" withParams:blockParam withData:chunk withFileName:filename withContentType:contentType];
                
                [request setPostValue:(bLastChunk?@"true":@"false") forKey:@"lastChunk"];
                [request setPostValue:[NSString stringWithFormat:@"%ld",(long)index] forKey:@"index"];
                if(isValidString(fileid))
                {
                    [request setPostValue:fileid forKey:@"id"];
                }
                
                
                [request setUploadProgressDelegate:progressDelegate];
                [request setShowAccurateProgress:YES];
                
                [[UploadManager instance]addUpload:filename Request:request];
                [request startSynchronous];
                
                //finished upload
                NSDictionary* dic ;
                NSString* sError ;
                {
                    sError = ParseHttpRequestResult(request, &dic);
                }
                
                [request setUploadProgressDelegate:nil];
                request = nil ;
                
                //下一次
                if (sError)
                {
                    [NSObject performBlockOnMainThread:^{
                        if([YXUser isCurrentUser:curUserId])
                            task(dic,sError,nil);
                    }waitUntilDone:NO];
                    break;
                }else
                {
                    if (bLastChunk)
                    {
                        [NSObject performBlockOnMainThread:^{
                            if([YXUser isCurrentUser:curUserId])
                                task(dic,sError,nil);
                        }waitUntilDone:NO];
                        [[LocalCache instance]removeUploadStatus:filename];
                        break;
                    } else
                    {
                        fileid = GetStringFromDictionary(dic, @"id");
                        
                        nSentCount += nToSend ;
                        
                        NSDictionary* tmp = @{@"id":fileid,@"sent":[NSString stringWithFormat:@"%ld",(long)nSentCount],@"index":[NSString stringWithFormat:@"%ld",(long)index]};
                        [[LocalCache instance]saveUpload:filename Status:[tmp JSONRepresentation]];
                    }
                }
            }
            
            [[UploadManager instance]finishUpload:filename];
            [fileHandle closeFile];
        }
    }];


Hope to be able to support synchronous request at an early date :beers:
