### ISSUE TITLE
Method has not been implemented?

### ISSUE THREAD

**Issue by JxbSir** [AFNetworking/AFNetworking#3276]
POST:parameters:progress:success:failure:

This method has not been implemented yet?

**Comment by kcharwood** [comment]
[Yes](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFHTTPSessionManager.m#L156).

What error are you seeing?

**Comment by JxbSir** [comment]
POST:parameters:progress:success:failure:]: unrecognized selector sent to instance 0x7f93f2606080

**Comment by kcharwood** [comment]
You'll need to provide an example. As you can see, the method _is_ implemented for AFHTTPSessionManager. Are you sure you are messaging the correct object?

**Comment by JxbSir** [comment]
it works now!  Thx
