### ISSUE TITLE
I found a serious bug about UIWebView+AFNetworking 

### ISSUE THREAD

**Issue by snowimba** [AFNetworking/AFNetworking#3277]
<img width="1275" alt="09" src="https://cloud.githubusercontent.com/assets/15967985/12253420/7cb8bb9a-b91a-11e5-85c4-15b915066215.png">

I found a serious bug

this method，use NULL

<img width="979" alt="03" src="https://cloud.githubusercontent.com/assets/15967985/12253191/fd1d15f8-b918-11e5-9057-aee2b9b29ee2.png">

but app crash

<img width="1016" alt="01error" src="https://cloud.githubusercontent.com/assets/15967985/12253202/0eaef7be-b919-11e5-9be8-44c749819c1c.png">

 this way ，use nil

<img width="944" alt="01err" src="https://cloud.githubusercontent.com/assets/15967985/12253209/1b9573ea-b919-11e5-9137-bc4319f1306e.png">

also  crash

<img width="1017" alt="02" src="https://cloud.githubusercontent.com/assets/15967985/12253222/3000a32c-b919-11e5-92b7-445f6fa2864d.png">

solution ：

<img width="1007" alt="08" src="https://cloud.githubusercontent.com/assets/15967985/12253225/33e9213a-b919-11e5-8422-674897d66f20.png">

<img width="1005" alt="04" src="https://cloud.githubusercontent.com/assets/15967985/12253227/38b47746-b919-11e5-8eba-b0b1ecfd0cb5.png">

**Comment by kcharwood** [comment]
Thanks @snowimba. Would you be able to push up a quick example showing this problem so I can debug it? Thanks!

**Comment by kcharwood** [comment]
Thanks so much! I see the issue now. I've patched it in #3289 

:beers:
