### ISSUE TITLE
Unable to read data, Swift Foundation._GenericObjCError thrown when a rest request returns empty body

### ISSUE THREAD

**Issue by luis-ad** [AFNetworking/AFNetworking#3279]
AFNetworking version: 2.6.0
Swift 2.1

AFNetworking handles an empty body (@"") returned for a GET rest request, by returning nil (at line 264) in the method 
```
- (id)responseObjectForResponse:(NSURLResponse *)response
        data:(NSData *)data
        error:(NSError *__autoreleasing *)error
```
form the AFURLResponseSerialization.m file at line 231 (AFJSONResponseSerializer implementation).

The debug info before returning nil:
![screen shot 2016-01-12 at 11 09 57](https://cloud.githubusercontent.com/assets/16648782/12263328/726e5d66-b92e-11e5-9807-45dd6beb5a60.png)

This method is called from the method 
```
- (void)URLSession:(__unused NSURLSession *)session
                task:(NSURLSessionTask *)task
                didCompleteWithError:(NSError *)error
```
in the AFURLSessionManager.m file at line 186 (AFURLSessionManagerTaskDelegate implementation).

At this point, when the first method returns nil, the second method gets an error (called serializationError in the code):
_SwiftNativeNSError  -> domain: unable to read data - code: 0
```
NSError *serializationError = nil;
responseObject = [manager.responseSerializer responseObjectForResponse:task.response data:data error:&serializationError];
```

The debug after that Swift creates error out of the nil result:
![screen shot 2016-01-12 at 11 01 10](https://cloud.githubusercontent.com/assets/16648782/12263403/0edc5f18-b92f-11e5-87c2-c6dd3852bb52.png)

And the GET method called in the AFHTTPSessionManager.m calls back the failure block with an error  (SwiftNativeNSError) **Foundation._GenericObjCError** with code 0.

The debug after that GET method's failure block is executed:
![screen shot 2016-01-12 at 11 02 09](https://cloud.githubusercontent.com/assets/16648782/12263420/35126376-b92f-11e5-8925-bbf09d701c14.png)

The rest call made succeeds with HTTP status 200 and returns empty body. But AFNetworking still calls back the failure block.

As I can see, AFNetworking needs to handle the nil (empty body) in a different way. I quess the problem is coming from Swift's way of handling optionals and errors.

**Comment by kcharwood** [comment]
There hasn't been any activity on this issue recently. I'm closing this now to clean up some old issues. If this issue persists with the latest version of AFNetworking, or you have a reproducible test case, please open a new issue and reference this issue.

Thanks! 🍻
