### ISSUE TITLE
AFURLSessionManager.setDownloadTaskDidWriteDataBlock doesn't called in an order sometimes

### ISSUE THREAD

**Issue by johnnielin** [AFNetworking/AFNetworking#3280]
Basically the problem I am having is inside the block the value of totalBytesWritten is not always received in an increscent order. For instance, it could be 1353.000000 while last received value was 50061.000000.

```
[manager setDownloadTaskDidWriteDataBlock:^(NSURLSession *session,NSURLSessionDownloadTask *downloadTask, int64_t bytesWritten, int64_t totalBytesWritten, int64_t totalBytesExpectedToWrite) {

    CGFloat written = totalBytesWritten;
    CGFloat total = totalBytesExpectedToWrite;
    CGFloat percentageCompleted = written/total;

    //Return the completed progress so we can display it somewhere else in app
    if( progressBlock){
        dispatch_async(dispatch_get_main_queue(), ^{
            progressBlock(percentageCompleted,remoteURLPath);
        });

    }
}];
```

BTW I am on AFNetworking 2.4. Currently I put a condition that it'll skip the update if new progress value is smaller than current progress value

**Comment by kcharwood** [comment]
Do you have any way to reliably reproduce the problem that would aid in debugging this?
