### ISSUE TITLE
iOS8.0, 9.0 is OK, but progress block not called at all，iOS7.0

### ISSUE THREAD

**Issue by emilyZhouwm** [AFNetworking/AFNetworking#3282]
iOS8.0, 9.0 is OK, but progress block not called at all，iOS7.0

    AFURLSessionManager *manager = [EHDownloadNetwork sharedInstance].manager;
    downloadTask.task = [manager downloadTaskWithRequest:request
              progress:^(NSProgress * _Nonnull downloadProgress) {
                  if (progressBlock) {
                      dispatch_async(dispatch_get_main_queue(), ^{
                          progressBlock(downloadProgress.fractionCompleted);
                      });
                  }

**Comment by kcharwood** [comment]
Can you provide more information about the response the server is sending? AFNetworking hooks into the NSURLSession progress update properties, which rely on a response to properly format the expected amount of bytes to be returned by the response.

**Comment by kcharwood** [comment]
It looks like you have chimed in on #3270, so we'll direct comments there.

:beers:
