### ISSUE TITLE
cache In UIImageView+AFNetworking

### ISSUE THREAD

**Issue by HePingLaoSan** [AFNetworking/AFNetworking#3283]
I have noticed that I request Same image URL but Server has changed image， in my device，I can't get new image only if I delete the app，i have clean the cache，but it doesn't work：

 AFImageCache *cache = (AFImageCache *)[UIImageView sharedImageCache];
    [cache removeAllObjects];
    [self removeObjectForKey:AFImageCacheKeyFromURLRequest(request)];

**Comment by kcharwood** [comment]
You should check your NSURLCache policies. AFNetworking leverages the system disk caching provided by NSURLSession and NSURLCache.

:beers:
