### ISSUE TITLE
why called the didFinishEventsForBackgroundURLSession Block in mainThread?

### ISSUE THREAD

**Issue by manwithstories** [AFNetworking/AFNetworking#3285]
AFURLSessionManager.m Line 1162   
called didFinishEventsForBackgroundURLSession Block   in  dispatch_get_main_queue

The App in background can't wakeUp the mainThread.

**Comment by kcharwood** [comment]
Hi @manwithstories 

In the future, please do not open a duplicate issue. It only clutters the list of things to work through.

Please keep this conversation in #3265
