### ISSUE TITLE
SecurityPolicy failed in AFNetworking 3.0.4 (public key mode)

### ISSUE THREAD

**Issue by johnnywjy** [AFNetworking/AFNetworking#3287]
I update AFNetworking from 2.x to 3.0, and when I simulate a man-in-the-middle attack, the request was not stopped.

I put the certificates in the app bundle, use public key as pinning mode.

I didn't change the default values of `allowInvalidCertificates` and `validatesDomainName`. The AFSecurityPolicy works well with `AFHTTPRequestOperationManager` in AFNetworking 2.x.
Here is my code:

```Objective-C
    AFHTTPSessionManager *manager = [[AFHTTPSessionManager alloc] initWithBaseURL:url];
    NSSet *certificates = [AFSecurityPolicy certificatesInBundle:[NSBundle mainBundle]];
    AFSecurityPolicy *policy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModePublicKey withPinnedCertificates:certificates];
    manager.securityPolicy = policy;
```

I noticed in `evaluateServerTrust:forDomain:`, the return value is still `NO`. And in `URLSession:didReceiveChallenge:completionHandler:`, it calls `completionHandler(disposition, credential)` with disposition equals to `NSURLSessionAuthChallengeRejectProtectionSpace` and credential equals to nil. It seems the session should be stopped but it didn't. Am I missing something or writing something wrong?

update: If I change policy mode to `AFSSLPinningModeCertificate`, it works.

**Comment by kcharwood** [comment]
Hi @johnnywjy,

The Security Policy class is our [most tested class](https://codecov.io/github/AFNetworking/AFNetworking/AFNetworking/AFSecurityPolicy.m?ref=d0e5aa0b0c2a6d00e1f7c0d5a44aac26aad1fdd9) in the library, and we have several tests demonstrating both positive and negative cases.

Is there anyway you can push up an example that allows me to debug it directly?

Thanks!

Kevin

**Comment by johnnywjy** [comment]
Hi, @kcharwood ,

I uploaded a simple demo about this: https://github.com/johnnywjy/AFNSecurityTest
I use Charles (install a root certificate on an iPhone) to simulate a man-in-the-middle attack, and the public key mode failed on a real device (iPhone 6 Plus, iOS 8.1.2, jailbroken).
If you need any additional information, or I am using the public key mode incorrectly, please tell me.

Regards,
Johnny

**Comment by martinreichart** [comment]
Hi,

I am having the same issue and can confirm the behaviour @johnnywjy is seeing. I tested it by pinning to the public key of a completely different server than the one I am accessing.
The completionHandler in the security policy is called with the correct disposition to reject the protection space, but the request is not cancelled. I also debugged the code in AFURLSession and from what I can see the challenge is never confirmed with neither NSURLSessionAuthChallengeUseCredential nor NSURLSessionAuthChallengePerformDefaultHandling - so from my understanding it should definitely cancel the request. Tested it on iOS 9.2.

Martin

**Comment by vonderbild** [comment]
Hi,
confirming that behaviour for devices running iOS 8.4.1 and 9.2.1, too. I just tested it with Burp Suite instead of Charles.

**Comment by vijaytholpadi** [comment]
+1

I can confirm the exact behavior/steps that @johnnywjy explained. Was just about to create an issue when I came across this one. Following.

Using:
- Charles
- iOS 9.2
- AFNetworking 3.0

Request go on to execute even after `NSURLSessionAuthChallengeRejectProtectionSpace` is returned by `URLSession:didReceiveChallenge:completionHandler:` in its completion handler.

**Comment by kcharwood** [comment]
Thanks everyone. So to confirm, you are seeing `NSURLSessionAuthChallengeRejectProtectionSpace`, but it is not actually cancelling it?

**Comment by kcharwood** [comment]
@johnnywjy I just pulled down your project, and did the following steps:


1. Setup Charles Proxy on my device, and install the charles certificate
2. Install your sample project, and run it. I see the requests succeed (as expected, since I haven't yet enabled SSL proxy in Charles for that domain.
3. Enable SSL proxy for huihui.cn
4. Rerun the project. I see both requests fail for certificate and public key pinning.

Am I missing anything? Does anyone follow these steps and not get the same behavior?

**Comment by kcharwood** [comment]
The console output from @johnnywjy's example:

```
2016-02-19 09:08:28.279 AFNSecurityDemo[275:7669] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
2016-02-19 09:08:28.280 AFNSecurityDemo[275:7669] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
2016-02-19 09:08:29.798 AFNSecurityDemo[275:7621] AFSSLPinningModeCertificate error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x10035cb80>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=<CFArray 0x100341f90 [0x19f014b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x10035afb0) s: *.huihui.cn i: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016)>
	1 : <cert(0x10035c4f0) s: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016) i: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016)>
)}, NSUnderlyingError=0x100361210 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x10035cb80>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=<CFArray 0x100341f90 [0x19f014b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x10035afb0) s: *.huihui.cn i: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016)>
	1 : <cert(0x10035c4f0) s: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016) i: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016)>
)}}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://app.huihui.cn/app/abroad/top, NSErrorFailingURLStringKey=https://app.huihui.cn/app/abroad/top, NSErrorClientCertificateStateKey=0}
2016-02-19 09:08:30.901 AFNSecurityDemo[275:7621] AFSSLPinningModePublicKey error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x10035e150>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=<CFArray 0x10033d810 [0x19f014b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x10035d0e0) s: *.huihui.cn i: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016)>
	1 : <cert(0x10035d870) s: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016) i: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016)>
)}, NSUnderlyingError=0x100349210 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x10035e150>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=<CFArray 0x10033d810 [0x19f014b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x10035d0e0) s: *.huihui.cn i: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016)>
	1 : <cert(0x10035d870) s: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016) i: Charles Proxy Custom Root Certificate (built on Kevin-Harwoods-MacBook-Pro.local, 19 Feb 2016)>
)}}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://app.huihui.cn/app/abroad/top, NSErrorFailingURLStringKey=https://app.huihui.cn/app/abroad/top, NSErrorClientCertificateStateKey=0}
```

**Comment by vijaytholpadi** [comment]
@kcharwood  Strange, for me the project shared by @johnnywjy works too as you mentioned. Also If I put my certificates in his project and call my API's with SSL proxying through charles, then the SSL Pinning using public key works fine. Still trying to figure out why it does not work in my project and also if there is any conflict with anything else.

**Comment by vijaytholpadi** [comment]
I just realized what went wrong in my case. Looks like this dirty `NSAllowsArbitraryLoads` bit in my info.plist was causing it (I had put it in the first place to circumvent the ATS issue I was facing with iOS 9 while accessing links from various domains. Should have never resorted to this and instead only resorted to individual domain whitelisting which I was already doing)

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

Putting this here for everyone else's reference. Apologies for wasting your time, @kcharwood :)

**Comment by kcharwood** [comment]
Thanks for the update @vijaytholpadi. No apologies needed. I want to make sure there are _no_ issues on the pinning front, so I welcome _everyone_ to test and give feedback. The more, the better :)

**Comment by xn1108100154** [comment]
Hi,
I am having the same issue in my project and @johnnywjy 's demo. 
Using:
Charles v3.10.1 (cracked), 
iPod Touch (iOS 8.1.2, jailbroken), iPhone 4s (7.1.2),
AFNetworking 3.0.4

I don't test on an iOS9 device specifically to prevent the influence of `NSAppTransportSecurity `.

**Comment by kcharwood** [comment]
If you are on a jailbroken phone, I'm not sure what would happen here.

Given I've validated the original issue is not a problem, I'm going to close this out.

If anyone has any specific items that they would like me to look into, please open a new issue, and provide clear, reproducible steps with an example project if possible.

:beers:
