### ISSUE TITLE
Potential Memory Leaks in 3.0.4

### ISSUE THREAD

**Issue by CuiBenyong** [AFNetworking/AFNetworking#3293]
When I called the GET or POST method to get some Json data,there will be so many leaks listed in Instruments->leaks tool. There is my code:

``` Objective-C
    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    [manager GET:@"xxx" parameters:nil progress: nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nonnull responseObject) {
        NSLog(@"%@",responseObject);
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@"%@",error);
    }];
```

IDE: Xcode7.2

**Comment by baidingpan** [comment]
I also use this way Batch requests ,there are so many leaks when use AF3.0.4

**Comment by kcharwood** [comment]
I profiled the example project again this morning, and don't see any leaks occurring. You could save your Instruments trace and attach it here, or create a small sample project that reproduces the problem?

**Comment by kcharwood** [comment]
[ExampleProjectLeaks.trace.zip](https://github.com/AFNetworking/AFNetworking/files/91988/ExampleProjectLeaks.trace.zip)

**Comment by baidingpan** [comment]
i'm found some memory leak,please  MR kcharwood have a look,and tell me the reason,thanks.
[Uploading Instruments2.trace.zip…]()
[Uploading Instruments4.trace.zip…]()

**Comment by al03** [comment]
+1

**Comment by jianzhi2010** [comment]
I have the same problem when I simply use the GET method.Here is my code:

```
    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    [manager GET:@"https://api.app.net/stream/0/posts/stream/global" parameters:nil progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        NSLog(@"response:%@", responseObject);
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@"error:%@", error);
    }];
```
AFNetworking version: 3.1.0 and here is the example trace file
[AFNetworking/ExampleMemoryLeak.trace.zip](https://github.com/jianzhi2010/AFNetworking/blob/master/File/ExampleMemoryLeak.trace.zip)

**Comment by LeeCenY** [comment]
+1

**Comment by rotemtt** [comment]
+1

**Comment by newbbydong** [comment]
I used 3.1.0，and it still leak.Here is my code:
    + (void)get:(NSString *)urlString params:(NSDictionary *)params success:(void (^)(id json))success    failure:(void (^)(NSError *error))failure {
        AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
        manager.requestSerializer = [AFJSONRequestSerializer serializer];
        manager.responseSerializer =  [AFJSONResponseSerializer serializer];
        [manager.requestSerializer setTimeoutInterval:30];
        [manager GET:[kBaseUrl stringByAppendingString:urlString]  parameters:params progress:nil   success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
            if (success) {
                success(responseObject);
            }
        } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {     
            if (failure) {
                failure(error);
            }
        }];
    }

**Comment by foxsin10** [comment]
Do not use a class func.Make sure your manager is a global variable

**Comment by huweidong** [comment]
This is my understanding

**Comment by huweidong** [comment]
This is my understanding.
https://huweidong.github.io/2017/03/30/关于使用AFNetworking内存泄露的问题/

**Comment by wsxiaoluob** [comment]
Here is a leaks demo.  @kcharwood 
[AFNDemo.zip](https://github.com/AFNetworking/AFNetworking/files/1655110/AFNDemo.zip)

The reason is what Apple said in NSURLSession Guide probably :

The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you don’t invalidate the session, your app leaks memory until it exits.

**Comment by wsxiaoluob** [comment]
emmmmm.........
I thinked a lot ,but I can't see any solution to fix this problem IN AFNetworking, 

One solution is make AFHTTPURLSessionManager to a singleton, but I can only config ONE timeoutInterval and some other configuration in manager.

Another solution is when my request task finished ,I called invalidateSessionCancelingTasks: to my manager, but this will cancel other tasks in this manager.
