### ISSUE TITLE
How I start use Http2.0 with AFNetworking?

### ISSUE THREAD

**Issue by AngryLi** [AFNetworking/AFNetworking#3296]
Now my leader tell us to transfer to http2.0,we log the http-header found that AFNetwoking support spdy but no http2.0.I used the ios9 platform,how can I open the http2.0 support?

**Comment by kcharwood** [comment]
NSURLSession has HTTP 2.0 support in iOS 9, so AFNetworking should automatically support HTTP 2.0, although I haven't tried it myself. If you run into any issues, please do let me know 

:beers:
