### ISSUE TITLE
How to set User_Agent's value correctly?

### ISSUE THREAD

**Issue by castial** [AFNetworking/AFNetworking#3300]
I need to collect HTTP requests from different device platforms. How do I set User Agent value using AFNetworking3? and save cookies.

**Comment by kcharwood** [comment]
Questions like these are best suited for StackOverflow. It allows to remain focused on bug fixing and feature requests.

The user agent is simply an HTTP header, so you can override it to whatever value you want:

`[requestSerializer setValue:@"My Agent" for HTTPHeaderField:@"User-Agent"]`

Cookies are managed with `NSHTTPCookieStorage`.
