### ISSUE TITLE
Download progress on UIImageView+AFNetworking category

### ISSUE THREAD

**Issue by knutigro** [AFNetworking/AFNetworking#3301]
It would be nice to have access to the download progress when using the UIImageView+AFNetworking category. 

I did add a question here:  http://stackoverflow.com/questions/34744024/afnetworking-3-0-setimagewithurlrequest-download-progress 

and I also did some experiments by copying some code from `UIProgressView+AFNetworking.h`. The result is here: https://gist.github.com/knutigro/85d3463f06f660d7a67d . My category crashes  in some situations though, so it still need more work :-( 

An other ideas? Are you open for pull requests on this issue?

**Comment by kcharwood** [comment]
It should be possible to expose the progress update. I would certainly be open to a pull request. It should be accessible from the manager on the image downloader, and just needs to be exposed back up through the image view interface.

**Comment by knutigro** [comment]
@kcharwood  Here is my pullrequest. 

I did notice that in both the success block and in the failure block you check against the `activeImageDownloadReceipt.receiptID` before actually calling the block. I did not understand why that should be needed in the progress block so I left it out. Please correct me if I am wrong.

The method I talk about is `- (void)setImageWithURLRequest:(NSURLRequest *)urlRequest
              placeholderImage:(UIImage *)placeholderImage  downloadProgress:(nullable void (^)(NSProgress *downloadProgress)) downloadProgressBlock success:(void (^)(NSURLRequest *request, NSHTTPURLResponse * _Nullable response, UIImage *image))success failure:(void (^)(NSURLRequest *request, NSHTTPURLResponse * _Nullable response, NSError *error))failure`

and the line of code I reference to is:

`if ([strongSelf.af_activeImageDownloadReceipt.receiptID isEqual:downloadID])`...
