### ISSUE TITLE
_AFURLSessionTaskSwizzling breaks NSBundle localizedStringForKey

### ISSUE THREAD

**Issue by astralbodies** [AFNetworking/AFNetworking#3303]
I'm trying to use the launch argument `-NSDoubleLocalizedStrings YES` to have all localizable strings doubled for assistance with layout. For some reason I couldn't get it to work on the WordPress-iOS project. After some digging I found out that the `_AFURLSessionTaskSwizzling` swizzling method breaks `[NSBundle localizedStringForKey..]`.

I'm no expert on swizzling but I can provide the steps to reproduce.
1. Use the iOS Example project straight from GitHub.
2. Change the launch arguments for the iOS scheme and add `-NSDoubleLocalizedStrings YES` as an argument.
3. Launch the app. Notice the title bar doesn't duplicate the text.

Now, remove the entire interface and implementation of `_AFURLSessionTaskSwizzling` from `AFURLSessionManager.m`. Perform the steps above and notice that the title text duplicates as expected.

**Comment by kcharwood** [comment]
Maybe related to #3061?

That's _extremely_ puzzling. I'm assuming swizzling in general would not break that function. So why would swizzling something in NSURLSession cause it?

**Comment by astralbodies** [comment]
The other weird thing is I can set the NSUserDefaults value of true with the key `NSDoubleLocalizedStrings`, synchronize, then restart the app and the strings duplicate as expected. Somehow this method is affecting the NSBundle method and how it pulls the defaults that are in the `NSArgumentDomain` domain.

**Comment by astralbodies** [comment]
So I did more digging - the problem is coming from this single line in the swizzle:

```
[localDataTask cancel];
```

Comment out that line and the localized strings are duplicated.

**Comment by astralbodies** [comment]
The actual class of localDataTask is NSObject. That seems wrong.

**Comment by kcharwood** [comment]
Calling all runtime wizards... :)

**Comment by kcharwood** [comment]
And because I know people who stumble across this issue will ask _why_ are we swizzling, please see #2702

**Comment by kcharwood** [comment]
That's interesting @astralbodies 

I've been absolutely slammed the last 2 weeks here so I havent had a chance to dig in on this. I'm not even sure we require the cancel there, but will need to look in to it.

**Comment by astralbodies** [comment]
I'm just stumped as to how it breaks NSBundle's method! Time to dig into the framework :+1:

**Comment by kcharwood** [comment]
Perhaps cancel immediately fails, which causes an error to be created, which causes the framework to go looking for some strings to early?

**Comment by astralbodies** [comment]
You might be onto something. I did set a breakpoint on that line and dumped out the contents of NSUserDefaults - the launch parameter is listed in there already. Continued execution and now suddenly the strings are duplicated. If I pause execution but don't dump out standardUserDefaults, the strings don't duplicate. So by prematurely loading the standard defaults, the launch param makes it in before the cancel is called.

**Comment by tewha** [comment]
FWIW, I'd really like to read about the KVO crashes that lead to this. Can you provide a link? KVO has been rock solid in my experience.

**Comment by kcharwood** [comment]
I believe this issue has a lot of the history:

https://github.com/AFNetworking/AFNetworking/pull/2411

**Comment by astralbodies** [comment]
Was curious if any time has been spent with this one yet. The few people I've consulted on the side indicate that reaching into UIKit (calling cancel) before the runtime is done loading is probably a bad smell.

**Comment by tewha** [comment]
Are the KVO crashes historical? I really wish AFNetworking 3 had been iOS 9+. The big change in iOS 9 wasn't the deprecation of NSURLConnection, it was the introduction of ATS. AFNetworking should be encouraging ATS use, and dropping iOS 8 would have ben the perfect opportunity to start cleaning things up.

**Comment by kcharwood** [comment]
I believe there were crash reports still associated with iOS 8.

It;s possible we could branch the code path if we believe the KVO crashes have been solved. Unfortunately, I don't think dropping iOS 8 is realistic yet for a library of this size. Once iOS 10 rolls around, I think that will be easier to push through.

Would someone want to work up a branch code path pull request?

**Comment by tewha** [comment]
I think you should have done so with 3.0. The 2.x branch still exists; there should at least be some hint that there's a huge potential security tradeoff for supporting iOS 8. Maybe the README should be updated?

I mean, look at it this way: That terrible SSL bug last year? If something like it happened again in iOS 8 it'd be AFNetworking's vulnerability. If it happened on iOS 9 it would be Apple's. There's almost no excuse for even advanced programmers to be intentionally removing themselves from the umbrella of ATS.

**Comment by nitxc** [comment]
https://github.com/nitxc/XCNetworkClient  这个我是我自己写的网络框基于AFN3.0、YYModel， 仿照猿题库写的。不知道好不好。

**Comment by anderscarling** [comment]
I'm quite sure this is related to the fact that `NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration ephemeralSessionConfiguration];` seems to load `[NSBundle mainBundle]`, this triggering the parsing of configuration options in `NSUserDefaults` before even `main` is called.

This can quite easily be confirmed by dropping something like
`[[NSUserDefaults standardUserDefaults] setObject:@[@"sv"] forKey:@"AppleLanguages"]` before the line in question. Observe that the language will be overridden (in this case to Swedish) for a newly installed app. Dropping the same line just after the configuration initialization will indeed not work for the first launch, but for subsequent launches (as configuration is stored alright, it just wont be parsed until next launch).

One workaround that _should_ work is probably to call the swizzling setup in a `dispatch_once` block when initializing the first `AFURLSessionManager` or something like that, but i do not know enough about the inner workings of `AFURLSessionManager` to know if that is a really bad idea.

**Comment by anderscarling** [comment]
[This branch](https://github.com/anderscarling/AFNetworking/tree/workaround_swizzling_disabling_maybe_crazy) contains the hack/workaround mentioned.

Tests seems to run and some quick testing indicates it works in our application, but as I said, I don't really have the AFNetworking knowledge to know if I'm breaking something.

**Comment by anderscarling** [comment]
#3061 is indeed related, as it's pretty much identical to the issue causing me to look in to this.

**Comment by mohammed-shakeer** [comment]
I had similar issue, where AFURLSessionManager load method was causing issue. UI was not flipping for arabic when the language for UserDefaults was set in main.m. I moved the code from main.m to load method in AppDelegate. It worked !!

**Comment by mildm8nnered** [comment]
I spent a day trying to track down why my pseudo-languages weren't working before I found this but report. Commenting out the `load` method fixes it for me. That's fine as a workaround, but it would be great to have a real fix for this that did not require code changes.

**Comment by stevelandeyasana** [comment]
It seems this is still a problem; I ran into it today and the workaround in the fourth comment worked for me. But it's not a fix, so I'm not really sure what I can do.

**Comment by mildm8nnered** [comment]
> It seems this is still a problem. I ran into it today and the workaround in the fourth comment worked for me. But it's not a fix, so I'm not really sure what I can do. I'm trying to use doubled strings as a CI step so modifying the AFNetworking pod is a no-go.

@stevelandeyasana - could you open a new issue for this, as per the stale bot message above? This seems like it should be fixable, so it's a bit annoying that it's still hitting people today.

See also https://github.com/AFNetworking/AFNetworking/issues/4731, which proposes a new implementation of _AFURLSessionTaskSwizzling - not sure if its any good, or if it would fix this, but maybe ...

**Comment by MaxHasADHD** [comment]
Running into this as well through another library using AFNetworking.
