### ISSUE TITLE
v -3.0.4 method override warning

### ISSUE THREAD

**Issue by llliang** [AFNetworking/AFNetworking#3305]
method override for the designated initializer of the superclass '-init' not found in AFNetworkReachabilityManager and AFURLConnectionOperation 

Null passed to a callee that requires a non-null argument in AFURLSessionManager

**Comment by ktounet** [comment]
:+1: I get the same warnings.

AFNetworking v2.5.4
Xcode 7.2

**Comment by kcharwood** [comment]
`AFURLConnectionOperation` is not in version 3.0.4? Are you sure thats the version you are using?
