### ISSUE TITLE
AFNetworking post request cancel

### ISSUE THREAD

**Issue by emre-g07** [AFNetworking/AFNetworking#3310]
how can i cancel post request? i have try mant thing but did not working for me. i am using AFNetworking version 2

**Comment by kcharwood** [comment]
This question is best suited for StackOverflow. We use Github for reporting bugs and managing feature requests, which allow us to focus on improving the library.

If you are using the NSURLSession API's, you call cancel directly on the task. If you are using the NSURLConnection API's, you call cancel on the operation.

:beers:
