### ISSUE TITLE
error:Module "AFNetworking" not found

### ISSUE THREAD

**Issue by AniOSDeveloper** [AFNetworking/AFNetworking#3311]
There is an error when I run version 3.0.4 branch on xcode7.2:  "Module "AFNetworking" not found  in AFAppDotNetAPIClient.h, how to resolve this issue?

**Comment by kcharwood** [comment]
Have you tried cleaning? I'm able to successfully build the example project locally, and Travis builds the example across multiple versions of Xcode without issue.

**Comment by ekapradityagk** [comment]
Hi, i just download this git, and i've got the same issue, already try cleaning, but still shown the error, could you help? i still didnt modify any code.
![screen shot 2016-03-16 at 2 26 22 pm](https://cloud.githubusercontent.com/assets/6790426/13804874/3924e3c2-eb83-11e5-8e9e-881fd03a888a.png)

**Comment by ekapradityagk** [comment]
just FYI what am i doing is download this git to my github app in my mac, and then run the example xcode project.

**Comment by AniOSDeveloper** [comment]
This issue maybe caused by the lack of some project file. Try this command in your terminal:   git clone --verbose https://github.com/AFNetworking/AFNetworking.git

**Comment by Norcy** [comment]
The same problem happens to me. I download the newest code and didn't modify any code.

**Comment by Norcy** [comment]
i open the "AFNetworking.xcworkspace" instead of "AFNetworking.xcodeproj" or "AFNetworking Example.xcodeproj" and the problem get solved
