### ISSUE TITLE
How to pass CRLF boundry last line in MultipartFormData Request

### ISSUE THREAD

**Issue by parthmind** [AFNetworking/AFNetworking#3314]
Hi All, I am using AFNetworking library in all my apps. And also used it MultipartFormData Task to upload picture on server. That is working everytime on linux server. Right now i am using backend with windows server in .Net. However I am facing one issue like image not getting uploaded because in boundry last line CRLF (Carriage Return and Line Feed --> \r\n) is not passing. I checked with Header request with many clients on browser and finally got know that just that last CRLF line is missing when I call API from my app. Is there any way I could pass CRLF as a last boundry line to API call?

**Comment by kcharwood** [comment]
There hasn't been any activity on this issue recently. I'm closing this now to clean up some old issues. If this issue persists with the latest version of AFNetworking, or you have a reproducible test case, please open a new issue and reference this issue.

Thanks! 🍻
