### ISSUE TITLE
When i analyze the project use command + i in Xcode, it cause memory leak

### ISSUE THREAD

**Issue by zhuochenming** [AFNetworking/AFNetworking#3319]
the memory leak is in AFHTTPSessionManager.m,code is:

+ (instancetype)manager {
    return [[[self class] alloc] initWithBaseURL:nil];
}

i just want to know , if i can change it like this to solve the problem:
+ (instancetype)manager {
    static AFHTTPSessionManager *manager = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        manager = [[self alloc] initWithBaseURL:nil];
    });
    return manager;
}

**Comment by kcharwood** [comment]
No you can not change that. That is not meant to be a singleton accessor method.

**Comment by zhuochenming** [comment]
thank you
