### ISSUE TITLE
AFNetworking 3.0 : AFHTTPRequestOperation operation.responseData equivalent

### ISSUE THREAD

**Issue by VrasidasP** [AFNetworking/AFNetworking#3320]
Hello, firstly, excellent work on this library! Really helpful. :)

I have a problem migrating to 3.0, because of the Wallet Passes.
Our server returns the pkpass data by calling `echo file_get_contents(...)` (it's using a [PHP library for creating PKPasses](https://github.com/tschoffelen/PHP-PKPass)).

In the previous versions (using AFHTTPRequestOperationManager), I could get the pkpass data from the operation.responseData and it was working fine. 
Now I'm trying to migrate to 3.0, but with AFHTTPSessionManager I can only get the NSURLSessionDataTask task and the id responseObject.

responseObject returns null in every case I've tried, and I can't see if there is a way to get the data from the task.

Is this possible at all?
Thank you!

**Comment by kcharwood** [comment]
Take a look at the response serializers. You can easily subclass and create one that has access to the NSData, and you can use to generate any object type you wish.
