### ISSUE TITLE
the first value of NSProgress when "downloadTaskWithResumeData"

### ISSUE THREAD

**Issue by gs01md** [AFNetworking/AFNetworking#3323]
Hi,
    when i resume the download task use "downloadTaskWithResumeData"，i found that the first NSProgress value is not the expected value。for example:
     **Parent: 0x0 / Fraction completed: 1.2339 / Completed: 16185671 of 13117958 **
     and  i  found that  the sum  of  the giving numbers "16185671 of 13117958 "，is the real total length.

good luck!!!

**Comment by kcharwood** [comment]
Can you post an example? I think we have some unit tests verifying this behavior, so just want to compare and contrast.

**Comment by gs01md** [comment]
[example](https://github.com/gs01md/testDownload)
please use ''_VGNetWorkFramework.xcworkspace_“，and push _"暂停" button_ to pause ，push _”启动“button_ to resume。and you will find the output in your Xcode console.

**Comment by kcharwood** [comment]
There hasn't been any activity on this issue recently. I'm closing this now to clean up some old issues. If this issue persists with the latest version of AFNetworking, or you have a reproducible test case, please open a new issue and reference this issue.

Thanks! 🍻
