### ISSUE TITLE
AFAutoPurgingImageCache crash

### ISSUE THREAD

**Issue by crazyjooe** [AFNetworking/AFNetworking#3329]
We are having _NSInvalidArgumentException_ in **AFAutoPurgingImageCache.m** line 45 in the situation when received data is broken image or gif and using _AFCompoundResponseSerializer_. We are using `FLImageResponseSerializer` and _UIImageView_'s `imageResponseSerializer`.
It seems that **AFCompoundResponseSerializer's** `- (id)responseObjectForResponse:data:error:` is doing the following: is trying to serialize response object with each of provided serializers, and in case none of the succeeded, calls `super` implementation. 
It then caches the broken image data without verifying if it actually IS image, and we get the crash at `[AFCachedImage initWithImage:identifier:] ` .
To fix it we implemented always failing `AFImageResponseSerializer` which creates error and returns empty _NSObject_ and added it as the last compound serializer.
So the question is if this is actually a bug or there are any nice solutions for this?

Reproducible on AFNetworking 3.0.4 on any iOS version.

**Comment by kcharwood** [comment]
This sounds like it may be a bug. Would it be possible to create a test demonstrating the issue so we can debug and patch the issue?

**Comment by crazyjooe** [comment]
Yes, I have created a test project with AFNetworking configured the same way we have for our real project. It has one test which is crashing. Also, I've added the workaround we have implemented for for it, it can be seen it test comments.
[https://www.dropbox.com/s/d4u1yo84uxk9lig/AFNetworkingCrashTest.zip?dl=0](url)

**Comment by kcharwood** [comment]
As the documentation states:

> `AFCompoundSerializer` is a subclass of `AFHTTPResponseSerializer` that delegates the response serialization to the first `AFHTTPResponseSerializer` object that returns an object for `responseObjectForResponse:data:error:`, falling back on the default behavior of `AFHTTPResponseSerializer`.

The default behavior is to call super, which validates status codes and content types.

Since `AFCompoundSerializer` is an AFHTTPResponseSerializer, you could set the acceptable content types there and it _should_ fail without having to add a custom response serializer. Thoughts?

**Comment by crazyjooe** [comment]
Great idea!
We solved issue in our project (and in the provided test project) by setting empty set of acceptableContentTypes.
Thanks you.

**Comment by kcharwood** [comment]
Awesome. I'm going to close this issue out as of now. I'll think about a better way long term. :beers:
