### ISSUE TITLE
AFNetworking 3.0 - Code=-1011 "Request failed: length required (411)"

### ISSUE THREAD

**Issue by leosalmaso** [AFNetworking/AFNetworking#3333]
I'm doing a simple post with user and password but apparently the Content-Length header is not sending in the request. I'm using AFHTTPSessionManager. The configutation is:

```
    _sharedInstance.requestSerializer = [AFJSONRequestSerializer serializer];
    _sharedInstance.responseSerializer = [AFJSONResponseSerializer serializer];
    _sharedInstance.responseSerializer.acceptableContentTypes =    
     [_sharedInstance.responseSerializer.acceptableContentTypes setByAddingObjectsFromArray:@[@"text/html", @"application/json", @"text/plain"]];
```

And the request:

NSDictionary *parameters = @{@"account":@{
                                   @"email": email,
                                   @"password": password
                                   }};

```
[self POST:kLoginPath parameters:parameters progress:^(NSProgress * _Nonnull uploadProgress) {
    NSLog(@"Progress: %@", uploadProgress);
} success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
    completionBlock(responseObject, nil);
} failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
    completionBlock(nil, error);
}];
```

I test with Postman and Alamofire, and the request works in both.

**Comment by kcharwood** [comment]
Could you post up your actual example demonstrating the problem?

**Comment by LkSime** [comment]
I encountered similar problems, how to carry on the Https access

**Comment by z234009184** [comment]
I encountered similar problems, Code=-1011 "Request failed: not found (404)"!!

**Comment by chrain** [comment]
I encountered similar problems, only in iPhone 4s discover, iPhone 6s is pass.

**Comment by gancan110** [comment]
I encountered similar problems, Code=-1011 "Request failed: not found (404)",iPhone5

**Comment by yocheved-check-in** [comment]
me too!!
some answers?

**Comment by shantj** [comment]
me too...
