### ISSUE TITLE
AFSecurityPolicyTests is failing

### ISSUE THREAD

**Issue by knutigro** [AFNetworking/AFNetworking#3334]
UnitTests are failing on: 

`-(void)testPolicyWithCertificatePinningAllowsGoogleComServerTrustIncompleteChainWithRootCertificatePinnedAndValidDomainName`

with assertions:  `Policy should allow server trust` for `AFUTGoogleComServerTrustPath`1 & `AFUTGoogleComServerTrustPath2` 

By the way. I have no intention on fixing this (Server security is not my thing)  ... Just reporting it for the record.  :smile: :beer:

**Comment by kcharwood** [comment]
Yeah I'm looking into it. Happy Certificate Expiration Day! :beers:

**Comment by tewha** [comment]
You should put the next one in your calendar. :)
