### ISSUE TITLE
cancelTaskForImageDownloadReceipt doesn't really cancel task

### ISSUE THREAD

**Issue by josipbernat** [AFNetworking/AFNetworking#3338]
Hi,

I'm struggling with canceling image requests when using AFImageDownloader in AFNetworking 3.0.4.
When UIImageView+AFNetworking try's **cancelImageDownloadTask** then AFImageDownloader doesn't really cancel task. Problem is in following **if** condition:

```
        if (mergedTask.responseHandlers.count == 0 && mergedTask.task.state == NSURLSessionTaskStateSuspended) {
            [mergedTask.task cancel];
        }
```

Having following NSLog clears the situation:

`NSLog(@"mergedTask.responseHandlers.count: %d, mergedTask.task.state: %d", mergedTask.responseHandlers.count, mergedTask.task.state);
`
It prints out this: 

> mergedTask.responseHandlers.count: 0, mergedTask.task.state: 0

NSURLSessionTaskState 0 is NSURLSessionTaskStateRunning which should be canceled but it isn't. Is this done by some reason because I would like to cancel all running image requests when UICollectionView makes dequeue process.

**Comment by kcharwood** [comment]
Hi @josipbernat 

As documented [here](https://github.com/AFNetworking/AFNetworking/blob/master/UIKit%2BAFNetworking/AFImageDownloader.h#L147), the image downloader is optimized to let requests currently in flight finish out, and get their response into the cache, so if you come back around in your dequeueable views, you don't have to issue another request. If the request is pending, it is actually cancelled.
