### ISSUE TITLE
swizzle of af_resume caused recursive calls on iOS9.3

### ISSUE THREAD

**Issue by dake** [AFNetworking/AFNetworking#3340]
swizzle of af_resume caused recursive calls on iOS9.3

![a7eb15dd-c5f9-4cb3-bf36-c681233ecae4](https://cloud.githubusercontent.com/assets/657637/13031615/d4ed6654-d30e-11e5-9802-35a7e4e7c542.png)

**Comment by kcharwood** [comment]
hey @dake 

What version of AFNetworking are you using, and are you using any other 3rd party libraries as well?

**Comment by kcharwood** [comment]
I have a travis build already building on 9.3, and passing:

https://travis-ci.org/AFNetworking/AFNetworking/jobs/107815574

**Comment by dake** [comment]
I used AFNetworking 3.0.4, no other third libraries.

Dake

**Comment by dake** [comment]
hey @kcharwood

Finally, I found a earlier version AFNetworking involved in a third library used in my project. so that's the problem. Thank you any way!

**Comment by kcharwood** [comment]
Thanks @dake

**Comment by waynett** [comment]
@dake how to solve the problem, i also face the problem。
