### ISSUE TITLE
AFImageDownloader  identifier  is nil when app crashes

### ISSUE THREAD

**Issue by soulCorw** [AFNetworking/AFNetworking#3343]
![0bbc3f7e-ab79-4b9d-9dba-46dec3cd6a47](https://cloud.githubusercontent.com/assets/11462712/13069308/7f43db00-d4be-11e5-8801-3337ed4e118f.png)

 reason: '*** setObjectForKey: key cannot be nil'

**Comment by xianwenx** [comment]
Check the URL being passed into the request, do you still have it?

**Comment by soulCorw** [comment]
Yes，I've been tracking it，at the beginning of the request, URL was a nil。I suggest that if there is an assertion to URL，we'll be closer to perfection。

**Comment by kcharwood** [comment]
Please see #3385.

We'll direct conversation there for now.

:beers:
