### ISSUE TITLE
why AFHTTPSessionManager has no singleton method

### ISSUE THREAD

**Issue by nicolasiJasica** [AFNetworking/AFNetworking#3346]

**Comment by nicolasiJasica** [comment]
AFHTTPSessionManager.m  
+ (instancetype)manager {
    return [[[self class] alloc] initWithBaseURL:nil];
}
 
this is  not absolutely

**Comment by dingtianran** [comment]
In my opinion, AFHTTPSessionManager can't be singleton 'cause they have different responseSerializer or requestSerilizer which cannot be shared by different usage

And for your case(if responseSerializer & requestSerilizer are identical) you can make it yourself.

**Comment by kcharwood** [comment]
You're free to create a singleton if you so chose. Nothing in AFNetworking prevents that.
