### ISSUE TITLE
[AFHTTPSessionManager GET..] return value NSURLSessionDataTask not dealloc,

### ISSUE THREAD

**Issue by maquannene** [AFNetworking/AFNetworking#3347]
I write code like this：

```
AFHTTPSessionManager *manage = [AFHTTPSessionManager manager];

NSURLSessionDataTask *dataTask = [manage GET:@"https://github.com/AFNetworking"
                                  parameters:nil
                                    progress:nil
                                     success:nil
                                     failure:nil];

[manage invalidateSessionCancelingTasks:YES];

manage = nil;

dataTask = nil;
```

AFHTTPSessionManager `dealloc` called regular，but I use method swizz replace NSURLSessionDataTask `dealloc` method, and I find `dealloc` never called.

If I write wrong?

**Comment by kcharwood** [comment]
NSURLSessionTask is a class cluster, which means you probably swizzled the wrong class. I would _highly_ encourage you to not do that.

This is not an AFNetworking issue.

**Comment by maquannene** [comment]
I use same swizzled, if i write this code 
```
NSURLSessionDataTask *dataTask = [[NSURLSessionDataTask alloc] init];
dataTask = nil;
```
NSURLSessionDataTask `dealloc` called regular, so it  prove I swizzled `dealloc` of  NSURLSessionDataTask successful.

even if [AFHTTPSessionManager GET..] return  is a class cluster of NSURLSessionTask, it is must subclass of NSURLSessionTask, why I swizzled `dealloc` not called?

**Comment by maquannene** [comment]
thx , My fault
