### ISSUE TITLE
completionHandler get call more than once

### ISSUE THREAD

**Issue by dErangaPrasad** [AFNetworking/AFNetworking#3350]
In AFHTTPSessionManager.m line 277 in following method getting called more than once with same response. any Idea how to fix it ?

dataTask = [self dataTaskWithRequest:request
                          uploadProgress:uploadProgress
                        downloadProgress:downloadProgress
                       completionHandler:^(NSURLResponse * __unused response, id responseObject, NSError *error) {
// HERE GETTING CALLED MORE THAN ONCE
}

**Comment by kcharwood** [comment]
Could you post an example demonstrating this behavior?

**Comment by dErangaPrasad** [comment]
I have a sharedInstant by subclassing AFHTTPSessionManager. I use following lines for initialise
  
 _sharedClient = [[AppClient alloc] initWithBaseURL:[NSURL URLWithString:@"URL"];
 _sharedClient.securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeNone];
_sharedClient.requestSerializer = [AFJSONRequestSerializer serializer];
[_sharedClient.requestSerializer setTimeoutInterval:25];

then for request I use as follows,

[[MySharedInstant sharedClient] POST:@"/api/register" parameters:params progress:nil success:^(NSURLSessionDataTask *__unused task, id JSON) {
        if (JSON) {
            if (JSON[@"error"]) {
                block([NSArray array], apiError);
            } else if (JSON[@"success"]) {
                NSMutableDictionary *dic = [[NSMutableDictionary alloc] initWithDictionary:[JSON valueForKeyPath:@"success"]];
                NSError *insertError = nil;
                User *user = [[User alloc] initWithDictionary:dic error:&insertError];
                if ([user updateDetails]) {
                    if (block) {
                        block(@[user], nil);
                    }
                } else {
                    block([NSArray array], insertError);
                }
            }
        }
    } failure:^(NSURLSessionDataTask *__unused task, NSError *error) {
        if (block) {
            block([NSArray array], error);
        }
    }];

Problem is instead on one response I get more than one response. hope this will help

**Comment by dErangaPrasad** [comment]
@kcharwood sorry it was my fault. location manager get updated more than once. thats was the issue. thanks for your concern.
