### ISSUE TITLE
Repeated judgment in AFURLSessionManager

### ISSUE THREAD

**Issue by Yuzeyang** [AFNetworking/AFNetworking#3354]
`- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSString *,id> *)change context:(void *)context {
    if ([object isKindOfClass:[NSURLSessionTask class]] || [object isKindOfClass:[NSURLSessionDownloadTask class]]) {
        // ...
    }
}`

NSURLSessionDownloadTask is subclass of  NSURLSessionTask,i think it just judge object isKindOfClass:[NSURLSessionTask class] is ok

**Comment by kcharwood** [comment]
Check out #2702 for why this is important.
