### ISSUE TITLE
Make dataTaskWithHTTPMethod:... public?

### ISSUE THREAD

**Issue by timothycosta** [AFNetworking/AFNetworking#3361]
I'm trying to ensure that my URLs always get percent encoded as my app frequently deals with URLs with spaces and special characters from many languages.  I know I can always encode each URL before I send it to AFNetworking, but I'd like to solve the problem once.

Overriding `dataTaskWithHTTPMethod:URLString:parameters...` in AFHTTPSessionManager would do the job nicely, but it's private.  I just wanted to suggest that that method be made public.  This would be similar to how AFURLSessionManager has the two public `dataTaskWithRequest:...` methods for overriding.

**Comment by tewha** [comment]
I agree with you, I think this should be public.

That said, we've asked before: See #2862, #2404, #2379, #2380.

**Comment by kcharwood** [comment]
Whip something up with tests, and I'll re-evaluate my position :) :beers:

**Comment by bar2** [comment]
I agree with you as well. Making it public everytime I open a new project and its hard to handle over CocoaPods while working with someone else.

**Comment by martins-p-sergio** [comment]
+1 for this. Should be public.
