### ISSUE TITLE
ETag is not working in iOS 8 with GZIP content

### ISSUE THREAD

**Issue by davidrissato** [AFNetworking/AFNetworking#3364]
When using AFNetworking in iOS 8, it seems to ignore ETag response header when the response is GZIPed. When you turn off GZIP compression on server, it behaves as expected (304 responses).

If we run the same code, just switching to iOS 9, everything works fine, even if being compressed on server.

We had checked the response object in iOS 8 and it receives the ETag value, so it is not a problem regarding response headers.

We tried to set the "If-None-Match" value by hand using the previous response ETag header and it worked fine in iOS 8.

This way I conclude the problem related to AFNetworking library, not an iOS bug.

**Comment by kcharwood** [comment]
Hi @davidrissato 

I'm not aware of anything AFNetworking is doing specifically for caching (outside of our custom image cache for the downloader). Are you trying to cache an image, or some other piece of content? Can you post up an example?
