### ISSUE TITLE
Undefined symbols for architecture x86_64 and arm64...

### ISSUE THREAD

**Issue by kevinva** [AFNetworking/AFNetworking#3368]
I use AFnetworking via cocoapod.
Complie and run on simulator or iPhone, the problem(as title says) comes out.
Any idea?

**Comment by MatthewYe** [comment]
"Undefined symbols for architecture x86_64 and arm64...", there is more detail in the "..." will tell what is missing.
Usually it happens when some lib or framework which code depends was missing.

**Comment by kevinva** [comment]
@MatthewYe 
I try to pod install again and again~~~ then it suggest me that I should add "$(inherited)" to" Build settings -> Linking ->  Other Linker Flags".

Problem solved!
