### ISSUE TITLE
How do I get statusCode 

### ISSUE THREAD

**Issue by Evana** [AFNetworking/AFNetworking#3373]
I am using AFNetworking 3.0 in my new app. But I am wondering how can I get statusCode in 

`[[AFHTTPSessionManager manager] GET:urlStr parameters:nil progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) { 
} failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) { 
}];`

OR

`[manager dataTaskWithRequest:req completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
}` 

Sorry thats might be a stupid question but I cant find a way get statusCode.

**Comment by Evana** [comment]
Got the solution 
`failure:^(NSURLSessionTask *operation, NSError *error) {
    NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse *)operation.response;
    httpResponse.statusCode;
    NSLog(@"status code: %li", (long)httpResponse.statusCode);
}`

**Comment by amirpervaiz086** [comment]
@Evana  NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse *)operation.response; httpResponse.statusCode; its giving me nil. cant cast to NSHTTPURLResponse in iOS 10. any other fix please?
