### ISSUE TITLE
Different Boundaries in multipart form

### ISSUE THREAD

**Issue by SebastianMecklenburg** [AFNetworking/AFNetworking#3374]
When I create a url requests using multipartFormRequestWithMethod:URLString:parameters: constructingBodyWithBlock:error: they are occasionally rejected by the server because of "no Content-Disposition header within part'". Looking at the sent data with a network sniffer revealed that the boundary is indeed wrong. In the header it says:
 
    Content-Type: multipart/form-data; boundary=Boundary+D87993F14D11D1AD

and later on in the content there is a different boundary:

    --Boundary+6F1F86719876A27B
    Content-Disposition: form-data; name="filename"
    IMG_2986.JPG

For the multipart forms that are accepted by the server the boundaries in the header and in the content are identical. Does someone have an idea what could cause this weird behaviour?

Thanks and regards,
Sebastian Mecklenburg

**Comment by kcharwood** [comment]
Have you been able to setup a test case demonstrating this problem?

**Comment by kcharwood** [comment]
There hasn't been any activity on this issue recently. I'm closing this now to clean up some old issues. If this issue persists with the latest version of AFNetworking, or you have a reproducible test case, please open a new issue and reference this issue.

Thanks! 🍻
