### ISSUE TITLE
Empty dictionary with withParameters 

### ISSUE THREAD

**Issue by cbornet** [AFNetworking/AFNetworking#3376]
If you call ```requestBySerializingRequest:request withParameters:parameters error:error``` with parameters as empty NSDictionary, a ```?``` will be appended to the request URL with no URL parameters behind. It would be better to not have this ```?``` like with a nil withParameters.

Behavior seen on v2.5.4 but I think it is the same on v3.x.

**Comment by kcharwood** [comment]
Checkout #3386 :beers:
