### ISSUE TITLE
No credential in AFHTTPSessionManager in 3.x?

### ISSUE THREAD

**Issue by ycy1164656** [AFNetworking/AFNetworking#3378]
Can't use digest access authentication?I can only find credential in AFURLSessionManager,but seems like not for digest access authentication.

**Comment by kcharwood** [comment]
Hi @ycy1164656 

AFNetworking exposes all of the authentication callbacks from NSURLSession, and you can set any header you would like through AFURLRequestSerialization.

Cheers

:beers:
