### ISSUE TITLE
Failed Background Task Causes Crash (3.x)

### ISSUE THREAD

**Issue by Hackmodford** [AFNetworking/AFNetworking#3380]
I've noticed if my app is suspended while downloading in a background session, and the download fails (I think) I get this error message.

```
2016-03-10 22:29:05.172 Big Finish[516:130343] *** -[NSLock unlock]: lock (<NSLock: 0x13dd8ba70> 'com.alamofire.networking.session.manager.lock') unlocked when not locked
2016-03-10 22:29:05.173 Big Finish[516:130343] *** Break on _NSLockError() to debug.
2016-03-10 22:29:05.176 Big Finish[516:130343] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x13dddd800 of class __NSCFBackgroundDataTask was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x13f1b0570> (
<NSKeyValueObservance 0x13de4fd30: Observer: 0x13ddd65f0, Key path: countOfBytesReceived, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x13de4f0a0>
<NSKeyValueObservance 0x13f1aee60: Observer: 0x13ddd65f0, Key path: countOfBytesExpectedToReceive, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x13dde66a0>
<NSKeyValueObservance 0x13def1870: Observer: 0x13ddd65f0, Key path: countOfBytesSent, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x13f1af4a0>
<NSKeyValueObservance 0x13f1b0540: Observer: 0x13ddd65f0, Key path: countOfBytesExpectedToSend, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x13def28a0>
)

*** First throw call stack:
(0x182b5d900 0x1821cbf80 0x182b5d848 0x18349f5c0 0x182a45380 0x18260d8e8 0x18345881c 0x18350680c 0x1006d1bb0 0x1006de6c8 0x1006d58a0 0x1006e07e0 0x1006e04d8 0x1827c5470 0x1827c5020)
libc++abi.dylib: terminating with uncaught exception of type NSException`
```

I think this is caused by a failed download because Crashlytics always seems to log a failed download.

Here's an example:

`__51-[AwesomeApp configureTaskDidCompleteBlock]_block_invoke line 237 $ Error Domain=NSURLErrorDomain Code=-997 "Lost connection to background transfer service" UserInfo={NSErrorFailingURLStringKey=https://www.blurredurl.com, NSLocalizedDescription=Lost connection to background transfer service, NSErrorFailingURLKey=https://www.blurredurl.com}`

**Comment by Hackmodford** [comment]
I've uncommented all of the setBackgroundSessionFinishedBlock/setTaskDidCompleteBlock/etc blocks, so I basically just have a session manager that starts a download. I've finally been able to cause this bug to happen consistently.

Steps to reproduce

1) Start a background urlsession task (in my case, I'm asking an API for a JSON list of albums)
2) Stop the app in xCode (or get iOS to suspend the app. I'm assuming this because I get this crash in the wild)
3) Give the session enough time to finish
4) Start the app

Doing these steps consistently causes it to happen. I think this is happening in the wild because my app is starting background downloads that are in the hundreds of megabytes. That gives the system plenty of time to suspend the app but continue downloading.

Is there a way to fix this? Maybe I'm doing something wrong?

**Comment by Hackmodford** [comment]
Could this be caused my duplicate GET requests? I was able to trigger this by making an identical request (I did it 2 or 3 times), then stopping the app, then starting.

**Comment by mrgerh** [comment]
Crashes at AFUTLSessionManager.m, on:
`- (instancetype)initWithSessionConfiguration:(NSURLSessionConfiguration *)configuration {`
...
```
[self.session getTasksWithCompletionHandler:^(NSArray *dataTasks, NSArray *uploadTasks, NSArray *downloadTasks) {
        for (NSURLSessionDataTask *task in dataTasks) {
            [self addDelegateForDataTask:task uploadProgress:nil downloadProgress:nil completionHandler:nil];
        }

        for (NSURLSessionUploadTask *uploadTask in uploadTasks) {
            [self addDelegateForUploadTask:uploadTask progress:nil completionHandler:nil];
        }

        for (NSURLSessionDownloadTask *downloadTask in downloadTasks) {
            [self addDelegateForDownloadTask:downloadTask progress:nil destination:nil completionHandler:nil];
        }
    }];
```







You just need to start some long term request and restart app (request that will not be finished soon). Or request to died host, or unregistered domain name.
At the next launch you will get this crash.

**Comment by Hackmodford** [comment]
Any ideas how to fix or avoid this?

**Comment by mrgerh** [comment]
I am using default session configuration and begin and end background tasks
manually. Before starting data task I create
​ single​
​​
background task, and wh
​en
​​all tasks were finished I end b
​​
ackground task.

As well you may
​begin dedicated
background task
​ for each ​data task.

26.04.2016 2:17 пользователь "Brandon Butler" <notifications@github.com>
написал:

**Comment by IMSymbal** [comment]
if ([self.manager respondsToSelector:@selector(removeDelegateForTask:)]) {
      [self.manager performSelector:@selector(removeDelegateForTask:) withObject:self.downloadTasks afterDelay:0];
    } 

This is my temporary solution

**Comment by Hackmodford** [comment]
@IMSymbal Where do you put this snippet?

**Comment by mrgerh** [comment]
OK, thank's for advice. Are you sure that nothing was broken and works
properly?
27.04.2016 5:53 пользователь "IMSymbal" <notifications@github.com> написал:

**Comment by IMSymbal** [comment]
put it at the cancel method

- (void)downLoadShouldCancel{
    [self.manager invalidateSessionCancelingTasks:YES];
    [self.downloadTasks cancel];
    if ([self.manager respondsToSelector:@selector(removeDelegateForTask:)]) {
      [self.manager performSelector:@selector(removeDelegateForTask:) withObject:self.downloadTasks afterDelay:0];
    }
}

**Comment by coreyfloyd** [comment]
@Hackmodford @mrgerh is the above fix working for you?

**Comment by sspitzer** [comment]
@coreyfloyd @Hackmodford 

This was hitting us with AFNetworking 3.1.0 and your patch fixed it, thank you!

This was really helpful reproducing the crash and verifying the fix:

```
1) Start a background urlsession task (in my case, I'm asking an API for a JSON list of albums)
2) Stop the app in xCode (or get iOS to suspend the app. I'm assuming this because I get this crash in the wild)
3) Give the session enough time to finish (Not sure if this is necessary)
4) Start the app
```

For step 1, I did:

```
[self GET:@"http://httpbin.org/delay/10" parameters:nil progress:nil success:nil failure:nil];
```

I backported https://github.com/AFNetworking/AFNetworking/commit/ff228fad3addd141cc668891b6c3bb9b1b1c4271.patch to AFNetworking 3.1.0 locally to fix this.

Thanks again!

**Comment by josluimg** [comment]
Some fix to AFNetwroking 3.1.1?  My apps crash for the same reason

**Comment by timothycosta** [comment]
I'm also experiencing this crash, but the above patch fixes it.  Would be great to get it accepted.

**Comment by jvieiraABC** [comment]
@sspitzer how can I backport?
