### ISSUE TITLE
Not sure why I'm getting a nil response object in GET method of AFHTTPSessionManager.

### ISSUE THREAD

**Issue by fysteven** [AFNetworking/AFNetworking#3381]
Not sure why I'm getting a nil response object in GET method of AFHTTPSessionManager.

By the way, it works for me on some APIs, but not all.
I do have some Chinese and Japanese characters in the return of the API that has the problem.

the version of the library is 3.0.4

**Comment by fysteven** [comment]
By the way, it works for me on some APIs, but not all.
I do have some Chinese and Japanese characters in the return of the API that has the problem.

**Comment by kcharwood** [comment]
Could you post an example demonstrating the problem?

**Comment by fysteven** [comment]
It turns out to be a broken JSON returned from the server. I checked with Apple's built-in library and Python.

**Comment by kcharwood** [comment]
Thanks!
