### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by LiuPengBty** [AFNetworking/AFNetworking#3383]
I have some questions about AFNetWorking. That's my using code:

`for (int i = 0; i < 1000; i++) {
        AFURLSessionManager *manager = [[AFURLSessionManager alloc] init];
    }`

And i find i can't release the AFURLSessionManager in ARC.

**Comment by dingtianran** [comment]
In general scenario, if the requests share the same host and similar pattern, they should use the same AFURLSessionManager instead, or a few of that, rather than make 1000 copies.

**Comment by LiuPengBty** [comment]
Oh, thanks.
