### ISSUE TITLE
A description of the header file appears small mistakes need to be corrected

### ISSUE THREAD

**Issue by XiangqiTu** [AFNetworking/AFNetworking#3389]
Hi,I recently read your code and found that there is a description of the header file appears small mistakes need to be corrected. 

——By Your loyal fans

**AFImageDownloader.h**
**Line 132**

/**
 Creates a data task using the `sessionManager` instance for the specified URL request.

 If the same data task is already in the queue or currently being downloaded, the success and failure blocks are
 appended to the already existing task. Once the task completes, all success or failure blocks attached to the
 task are executed in the order they were added.

 @param request The URL request.
- - -
 @param request The identifier to use for the download receipt that will be created for this request. This must be a unique identifier that does not represent any other request.
- - -
 @param success A block to be executed when the image data task finishes successfully. This block has no return value and takes three arguments: the request sent from the client, the response received from the server, and the image created from the response data of request. If the image was returned from cache, the response parameter will be `nil`.
 @param failure A block object to be executed when the image data task finishes unsuccessfully, or that finishes successfully. This block has no return value and takes three arguments: the request sent from the client, the response received from the server, and the error object describing the network or parsing error that occurred.

 @return The image download receipt for the data task if available. `nil` if the image is stored in the cache.
 cache and the URL request cache policy allows the cache to be used.
 */
```Objective-C
- (nullable AFImageDownloadReceipt *)downloadImageForURLRequest:(NSURLRequest *)request
                                                 withReceiptID:(NSUUID *)receiptID
                                                        success:(nullable void (^)(NSURLRequest *request, NSHTTPURLResponse  * _Nullable response, UIImage *responseObject))success
                                                        failure:(nullable void (^)(NSURLRequest *request, NSHTTPURLResponse * _Nullable response, NSError *error))failure;
```

**Comment by kcharwood** [comment]
Thanks! These have been taken care of in a few PR's. :beers:
