### ISSUE TITLE
Using NSOutputStream with AFNetworking 3.x

### ISSUE THREAD

**Issue by K-Be** [AFNetworking/AFNetworking#3394]
I want to download some data to a NSOutputStream instance.
Is there a way achieve this in the 3.x without writing some custom  code to manage NSOutputStream?
(There is outputStream property in the 2.x).

**Comment by dorsafamara50** [comment]
I am also stuck in this problem. In the older version there was a file named "AFURLConnectionOperation.h" that gives access to the outputstream but it doesn't exist in the new release. How can we get solve this problem please?

**Comment by dorsafamara50** [comment]
using the older versio. I downloaded data in order to put it in a mp3 file later just like this;

 NSURL *URL = [NSURL URLWithString:@"http://radio.mosaiquefm.net:8000/mosalive"];
    NSURLRequest *request = [NSURLRequest requestWithURL:URL cachePolicy:NSURLRequestReturnCacheDataElseLoad timeoutInterval:20];
    
    AFURLConnectionOperation * operation = [[AFHTTPRequestOperation alloc] initWithRequest:request];
    
    NSArray *docPaths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *docPath = [[docPaths objectAtIndex:0] stringByAppendingPathComponent:@"final1.mp3"];
    NSLog(@"file %@", docPath);
    
    operation.outputStream = [NSOutputStream outputStreamToFileAtPath:docPath append:NO];
    
    [operation start];


how can we do this using the  new version. Help Please

**Comment by binnilal** [comment]
I have the same problem. have any alternative solution for this new version for stream download??

**Comment by K-Be** [comment]
I think we can use NSURLSessionStreamTask to achieve the same behaviour. But now I'm working on other project, and can't check this solution.

**Comment by SunnySunning** [comment]
I have the same problem...help me...

**Comment by manishpathak99** [comment]
@here Does anyone has the solution of this problem ?
