### ISSUE TITLE
"Linking against dylib not safe for..." when framework is installed through Carthage 

### ISSUE THREAD

**Issue by ivan-konov** [AFNetworking/AFNetworking#3398]
Hello guys,

Xcode gives me the following warning for my watchOS extension when AFNetworking is added to the project through Carthage:

> (null): Linking against dylib not safe for use in application extensions: /Users/ivankonov/Documents/work/ios-fan-app-5/Carthage/Build/watchOS/AFNetworking.framework/AFNetworking

This is the script for the iOS target:

> $(SRCROOT)/Carthage/Build/iOS/AFNetworking.framework

and this is the script for the wathcOS target:

> $(SRCROOT)/Carthage/Build/watchOS/AFNetworking.framework

I have read some suggestions to disable the "Require Only App-Extension-Safe API" option but it does not seem like the best idea to me.

Thank you in advance!

**Comment by ethansinjin** [comment]
I have the same problem. I believe that enabling "Require Only App-Extension-Safe API" on the watchOS and tvOS targets of AFNetworking would fix this problem.

**Comment by kcharwood** [comment]
There hasn't been any activity on this issue recently. I'm closing this now to clean up some old issues. If this issue persists with the latest version of AFNetworking, or you have a reproducible test case, please open a new issue and reference this issue.

Thanks! 🍻

**Comment by ivan-konov** [comment]
The warning is still there if "Require Only App-Extension-Safe API" is set to YES
