### ISSUE TITLE
[Feature Request] Improve the Watch Example Project

### ISSUE THREAD

**Issue by lolgear** [AFNetworking/AFNetworking#3399]
How did you test framework for watchOS?
It seems that Apple doesn't have xctest for watchOS and also you don't have test cases for watchOS.
I suppose that you build crossplatform framework, test it and pouring watchOS example with it.

However, maybe it is necessary to put information about this technique in blog or documentation? ( sic )
( If it doesn't exists yet on some blogs that I did not find. )

**Comment by kcharwood** [comment]
I personally haven't done much work with the Watch. We have a target in the example project that verifies the framework can be compiled and deployed there, but we don't have anything exercising the functionality. I'd love to see someone take that work on!
