### ISSUE TITLE
I have get an error when I use  the following method "[AFHTTPSessionManager GET:parameters:progress:success:failure:]"

### ISSUE THREAD

**Issue by upleave** [AFNetworking/AFNetworking#3401]
when i use [AFHTTPSessionManager GET:parameters:progress:success:failure:] , i get the following eorro:
"-[AFHTTPSessionManager GET:parameters:progress:success:failure:]: unrecognized selector sent to instance "

but , if i use [AFHTTPSessionManager GET: parameters: success:failure:] , it work

**Comment by kcharwood** [comment]
Have you tried completely cleaning your dev environment? These issues are typically related to a bad cache locally.

**Comment by upleave** [comment]
Thanks for your reply!

**Comment by cauthy** [comment]
I fix the issue by remove the bulid finder  and  than   install  pods    
sometime there will be  not found for  lAFNetwork
for this  you can choose  another simulators to fix it
