### ISSUE TITLE
about convert json to NSDictioanry (error if json string contains double field)

### ISSUE THREAD

**Issue by icoco** [AFNetworking/AFNetworking#3405]
I face a problem, if response json string contains some double value , then while got the NSDictionary , the value is not normal ...

example : 
{ 
    "int": 12,
    "double": 67860.04,
   
    
  
}

then got the Dictionary that will be :  

double = "67860.03999999999";

the filed 'double' value is not original data..... 

how to fix it ?

**Comment by kcharwood** [comment]
AFNetworking is simply using NSJSONSerialization under the hood to parse objects. If you are not seeing the desired behavior, I'd recommend creating your own response serializer for your needed usage.

**Comment by icoco** [comment]
thanks for comment, 

I know it can be customized, but since it produced and shared online, I think that it may be perfect as possible.

**Comment by icoco** [comment]
please check https://github.com/icoco/JSONKit
