### ISSUE TITLE
[Question] Long term on disk images caching?

### ISSUE THREAD

**Issue by Sh1mor1nka** [AFNetworking/AFNetworking#3408]
Sorry for this question here, but on [stackoverflow](http://stackoverflow.com/questions/36270552/afnetworking-on-disk-image-caching) nobody helped me.

Sometime I used **SDWebImage**, but few days ago I'he found that **AFNetworking** has the same functionality, so i removed **SDWebImage** from my project and try to cache images on disk by **AFNetworking**, code examples you can see on link above. But as I understand **AFNetworking** caches images only per session. Is there a possibility to cache images for longer than session, for week, month? Thank you!

**Comment by kcharwood** [comment]
Images are cached to disk using standard NSURLCache built in to iOS, meaning that if your responses include proper cache headers, those items should end up on disk in the cache.

The in memory cache is used for scrolling performance, and is only good "per session".

:beers:

**Comment by Sh1mor1nka** [comment]
@kcharwood What is wrong with this code? Because in simulator I open app, see images, then turn off internet reopen app and there are no images...
```Objective-C
NSURLRequest *imageRequest = [NSURLRequest requestWithURL:[NSURL URLWithString:url]
                                              cachePolicy:NSURLRequestReturnCacheDataElseLoad 
                                          timeoutInterval:60];
[imageView setImageWithURLRequest:imageRequest placeholderImage:placeholderImage success:nil failure:nil];
```

**Comment by kcharwood** [comment]
You need to set the look at the response headers, not the request headers. You can override this behavior with `URLSession:dataTask:willCacheResponse:completionHandler:`

**Comment by Sh1mor1nka** [comment]
@kcharwood Oh sorry, response headers, okay, that's fun because manuals in web says that request cachePolicy do on disk caching. 

So i found `URLSession:dataTask:willCacheResponse:completionHandler:` in `AFURLSessionManager` and i don't really understand what i should override here, but as you say i look at response headers but in such way:
```Objective-C
 __weak __typeof(UIImageView *)weakView = imageView;
[imageView setImageWithURLRequest:imageRequest placeholderImage:placeholderImage success:^(NSURLRequest * _Nonnull request, NSHTTPURLResponse * _Nullable response, UIImage * _Nonnull image) {
                NSLog(@"responce headers %@", response.allHeaderFields);
                weakView.image = image;
            } failure:nil];
```
Here is header i got
```log
    "Accept-Ranges" = bytes;
    "Cache-Control" = "max-age=604800";
    Connection = close;
    "Content-Length" = 3808;
    "Content-Type" = "image/png";
    Date = "Tue, 29 Mar 2016 19:55:52 GMT";
    Etag = "\"5630989d-ee0\"";
    Expires = "Tue, 05 Apr 2016 19:55:52 GMT";
    "Last-Modified" = "Wed, 28 Oct 2015 09:42:53 GMT";
    Server = nginx;
```

So what should i do with response to store image on disk and after get image from cache?

**Comment by Sh1mor1nka** [comment]
@kcharwood help please :)

**Comment by kysokzla** [comment]
@kcharwood help please too - would be very great

**Comment by rsimenok** [comment]
@kysokzla i found that caching not always working in simulator, try real device.
