### ISSUE TITLE
DOCS method need fixed

### ISSUE THREAD

**Issue by jhaoheng** [AFNetworking/AFNetworking#3411]
http://cocoadocs.org/docsets/AFNetworking/3.0.4/
## URL FORM PARAMETER ENCODING

`[[AFHTTPRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters];
`
-> 
`[[AFHTTPRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters error:nil];
`

and 
## JSON PARAMETER ENCODING

`[[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters];
` 
->
 `[[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters error:nil];
`

**Comment by kcharwood** [comment]
Would you like to submit a PR to fix this?
