### ISSUE TITLE
AF_APP_EXTENSIONS no working to exclude AFNetworking framework insdie App Extension

### ISSUE THREAD

**Issue by Oscargp1986** [AFNetworking/AFNetworking#3424]
I have read the thread [#2321](https://github.com/AFNetworking/AFNetworking/issues/2321) and I can't make my project work. I have a very simple project: single view application, with a simple widget. This is my pod file:

`target 'WidgetTest' do
link_with 'WidgetTest', 'Widget'
pod 'RestKit'
end
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        puts "=== #{target.name}"
        if target.name == "AFNetworking"
            puts "Setting AFNetworking Macro AF_APP_EXTENSIONS so that it doesn't use UIApplication in extension."
            target.build_configurations.each do |config|
                puts "Setting AF_APP_EXTENSIONS macro in config: #{config}"
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AF_APP_EXTENSIONS=1']
            end
        end
    end
end`

And this is the output when I do "pod install":
`Updating local specs repositories

CocoaPods 1.0.0.beta.6 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing AFNetworking (1.3.4)
Installing ISO8601DateFormatterValueTransformer (0.6.1)
Installing RKValueTransformers (1.1.3)
Installing RestKit (0.26.0)
Installing SOCKit (1.1)
Installing TransitionKit (2.2.1)
Generating Pods project
=== AFNetworking
Setting AFNetworking Macro AF_APP_EXTENSIONS so that it doesn't use UIApplication in extension.
Setting AF_APP_EXTENSIONS macro in config: Release
Setting AF_APP_EXTENSIONS macro in config: Debug
=== ISO8601DateFormatterValueTransformer
=== RKValueTransformers
=== RestKit
=== SOCKit
=== TransitionKit
=== Pods-WidgetTest
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 6 total pods installed.`

WidgetTest is my project/target name and Widget is the app extension

I have tried creating a Prefix Header file for the widget too and many other solutions (different versions of cocoapods, different code in podfile...), but nothing works. I'm using cocoapods 0.39.0

What I do is:

Pod install, open the project, try to run Widget on my ipad. And get:

'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

Can somebody help me? Thanks.

**Comment by kcharwood** [comment]
AFNetworking 1.3.4 is not supported.

We recommend updating to AFNetworking 3.x to use in App Extensions.

🍻
