### ISSUE TITLE
UIButton has no member cancelBackgroundImageRequestOperation but autocomplete works

### ISSUE THREAD

**Issue by jkbreunig** [AFNetworking/AFNetworking#3428]
I'm adding AFNetworking with cocoapods, Xcode autocompletes the AFNetworking UIButton extension methods but I receive 'UIButton has no member cancelBackgroundImageRequestOperation' when compiling.
![screen shot 2016-04-05 at 6 17 30 pm](https://cloud.githubusercontent.com/assets/1190977/14301111/b1518d6e-fb5a-11e5-8c78-b6fcebc50fd6.png)

**Comment by kcharwood** [comment]
Have you tried clearing your derived data cache? That method was there in 2.x, but not 3.x.

🍻
