### ISSUE TITLE
Do we have Http 2 support already?

### ISSUE THREAD

**Issue by AntiMoron** [AFNetworking/AFNetworking#3430]
As the post title.

**Comment by AntiMoron** [comment]
I've read this issue:

https://github.com/AFNetworking/AFNetworking/issues/3296

I know that it's supported on iOS 9+

But my app(iOS 8+) wants to communicate with http2 server. Do we have a iOS version-free support?

**Comment by kcharwood** [comment]
I believe NSURLSession supports HTTP 2 in iOS 9, which we use under the hood. I think there is full support for you there now.

🍻
