### ISSUE TITLE
Instrument Analyse Circle Leaks

### ISSUE THREAD

**Issue by Nihility-Ming** [AFNetworking/AFNetworking#3439]
![g iv8mtos64p 8 uusq ucm](https://cloud.githubusercontent.com/assets/9312174/14516669/0b8e7092-0238-11e6-95b7-957603142337.jpg)

**Comment by jasonhotsauce** [comment]
There are actually no retain cycles in AFNetworking because the completion block is nil out after finish calling by `removeDelegateForTask:(NSURLSessionTask *)task`

**Comment by jasonhotsauce** [comment]
What tool are you using BTW? I haven't seen this in instrument. 😈

**Comment by chinapq** [comment]
> 在 2016年4月21日，13:08，Wenbin Zhang <notifications@github.com> 写道：
> 
> What tool are you using BTW? I haven't seen this in instrument
Can you ?

**Comment by jasonhotsauce** [comment]
@chinapq That's why I asked. 😈

**Comment by chinapq** [comment]
Are you Chinese?
> 在 2016年4月21日，22:20，Wenbin Zhang <notifications@github.com> 写道：
> 
> That's why I asked

**Comment by kcharwood** [comment]
As documented in https://github.com/AFNetworking/AFNetworking/issues/1528, this is because NSURLSession maintains a strong reference to its delegate.

You should call `invalidateSessionCancelingTasks` if you want to ensure your manager gets deallocated.
