### ISSUE TITLE
Many nullability warnings

### ISSUE THREAD

**Issue by nrbrook** [AFNetworking/AFNetworking#3443]
AFNetworking has many nullability warnings when 'Incorrect use of nullability values'  is enabled. See screenshot. I'd do a pull request but I think some of them may need careful consideration from an existing developer.
<img width="328" alt="screen shot 2016-04-15 at 00 30 12" src="https://cloud.githubusercontent.com/assets/1141167/14551472/9da15f8a-02a1-11e6-8131-1070e802120c.png">

**Comment by kcharwood** [comment]
Thanks @nrbrook! I'd be happy to review your pull request in detail!

**Comment by nrbrook** [comment]
It's probably easiest just to enable nullability warnings and go through them yourself. The changes are usually trivial but changes I make might not be the right thing to do.

**Comment by kcharwood** [comment]
There hasn't been any activity on this issue recently. I'm closing this now to clean up some old issues. If this issue persists with the latest version of AFNetworking, or you have a reproducible test case, please open a new issue and reference this issue.

Thanks! 🍻
