### ISSUE TITLE
DOC need fix

### ISSUE THREAD

**Issue by weng1250** [AFNetworking/AFNetworking#3449]
http://cocoadocs.org/docsets/AFNetworking/3.0.4/
URL FORM PARAMETER ENCODING

[[AFHTTPRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters];
->
[[AFHTTPRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters error:nil];

and
JSON PARAMETER ENCODING

[[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters];
->
[[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters error:nil];

**Comment by kcharwood** [comment]
dupe of #3411
