### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by zjszyms** [AFNetworking/AFNetworking#3453]
![yaii8lymr6rjwh qj zfggb](https://cloud.githubusercontent.com/assets/5733794/14732696/bc6376bc-088f-11e6-8268-b6b0dbfdf1a2.jpg)

**Comment by vienvu89** [comment]
I have the same issue when check with tool. ![Image of Leak](https://i.gyazo.com/4bfcdc416c9074e987dd4d6026a69aff.png)

**Comment by jasonhotsauce** [comment]
I got this one also. I am looking into it.
