### ISSUE TITLE
Multiple Response Type When Using AFHTTPSessionManager

### ISSUE THREAD

**Issue by jhoongo** [AFNetworking/AFNetworking#3455]
Hi,

I'm having some issue with handling multiple response serializer.
Background information is that

I am using AFHTTPSessionManager as singleton object to process all CRUD services.
There are multiple services that return different response types (plain text/json/xml).

When I use compoundResponseSerializer, the problem comes when the service returns certain type of response, as long as the response type is in the compoundResponseSerializer it accepts without throwing a serialization error.

When I change the responseSerializer individually for each call, the validation for each request is working fine; however, when the multiple responses are returned at the same time, as a race condition, the responseSerializer is mixed up, so it returns a serialization error even though the response is in a correct format as I requested.

In this kind of scenario, could you please clarify if I am using the AFNetworking inappropriately? and there is more proper way of using it in this scenario?

Few possible solution is that I make a queue for each request and change the response serializer for each request; however, it only works if the concurrent operation is limited to one request per time.  Which is not quite what I wanted; I wanted to process multiple requests at the same time.

Another solution is to use compoundResponseSerializer and validate once again after AFNetworking returns the response?

Thanks for your help in advance.

**Comment by kcharwood** [comment]
The compound response serializer is the correct serializer to be using. I'd suggest reviewing your acceptable content types for each, and validating your response serializers handle only the specific types they need to be handling
