### ISSUE TITLE
Wait for multiple requests to complete

### ISSUE THREAD

**Issue by guidev** [AFNetworking/AFNetworking#3467]
I need to wait for several AFNetworking requests to complete, i tried using dispatch groups, but I can't seem to get it right.

Here's my code:

```
dispatch_group_t group = dispatch_group_create();

for (int k = 0; k < 10 ; k++) {
    dispatch_group_enter(group);

    [[AFHTTPSessionManager manager] GET:@"http://google.com/" parameters:nil progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        NSLog(@"success");
        dispatch_group_leave(group);
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@"failure");
        dispatch_group_leave(group);
    }];
}

dispatch_group_wait(group, DISPATCH_TIME_FOREVER);

NSLog(@"DONE");
```

The problem is that it gets stuck on dispatch_group_wait, because neither the success block, nor the failure blocks are called.

How can I solve it?

**Comment by siddharthsuneel** [comment]
hi @guidev ,
I am also having the same kind of problem.
have you got the solution yet ?
if so, then please share it with all of us.

**Comment by huangqiaobo** [comment]
by default，the  success block and failure blocks are run in main thread. 
if the main thread is waiting forever, it will never run dispatch_group_leave(group)
: )
