### ISSUE TITLE
AFURLSessionManager downloadTaskWithRequest return filePath nil on real device

### ISSUE THREAD

**Issue by vanhungframgia** [AFNetworking/AFNetworking#3473]
AFURLSessionManager downloadTaskWithRequest return filePath nil on real device, work ok on simulator

ios 9.3.1
Allow Arbitrary Loads YES

**Comment by jschwendt** [comment]
I'm running into this very same issue.  I'm using iOS 10.2.1, and everything works fine on a simulator, however on a real device, filePath comes back nil.  I actually don't see the destination block getting called on the real device either, so I think that it all stems from that.  When I enumerate the temp directory, I see a file in the pattern of CFNetworkDownload_*.tmp, and I see progress updates of the file being downloaded and can confirm that the file reaches 100% each time.  I also added observers for all of the notifications that are possibly posted, and the only 2 which are firing on device are AFNetworkingTaskDidResumeNotification and AFNetworkingTaskDidCompleteNotification.  

I'm pulling my hair out on this one.  Spent a full day trying to figure this out.  Everything works perfectly on the simulator, just not the actual device.  Note that I'm also use .path for NSURLs, not .absoluteString which is another gotcha many seem to have fallen victim to.
