### ISSUE TITLE
AFNetworking 3.x - Logging

### ISSUE THREAD

**Issue by nzmb** [AFNetworking/AFNetworking#3474]
It would be nice to have access to the Logging of progress AFNetworking 3.x. It seams it is very important. Off course that is not an issue and is some of kind "feature request"

**Comment by kcharwood** [comment]
Feel free to put together a PR with your ideas!

**Comment by Skornos** [comment]
I was really satisfied with this extension: https://github.com/AFNetworking/AFNetworkActivityLogger
Unfortunately it doesn't work with 3.x

**Comment by skyline75489** [comment]
Is the AFNetworkActivityLogger 3.0.0 branch [here](https://github.com/AFNetworking/AFNetworkActivityLogger/tree/3_0_0) working as expected?
