### ISSUE TITLE
AFNetWorking 3.x Leak

### ISSUE THREAD

**Issue by wjzhlo** [AFNetworking/AFNetworking#3475]
I use AFNetWorking 3.x in the project when it came to memory leaks. Specifically,
1.AFSecurityPolicy.m -> + (instancetype) defaultPolicy -> AFSecurityPolicy \* securityPolicy = [[self alloc] init];
2.AFURLResponseSerialization.m -> - (instancetype) init -> self.acceptableStatusCodes = [NSIndexSet indexSetWithIndexesInRange: NSMakeRange (200, 100)];
3.AFURLSessionManager.m -> - (void) setDelegate: (AFURLSessionManagerTaskDelegate *) delegate -> self.mutableTaskDelegatesKeyedByTaskIdentifier [@ (task.taskIdentifier)] = delegate;
I do not know how to modify.

**Comment by skyline75489** [comment]
Can you be more specific about where the leak happens?
