### ISSUE TITLE
Why not add @"text/html" ?

### ISSUE THREAD

**Issue by QinghaoGuan** [AFNetworking/AFNetworking#3477]
file:AFURLResponseSerialization.m
row:228
why not add @"text/html" ?

**Comment by KBvsMJ** [comment]
你手动改的时候 会弹框提示 选择unlock 按钮后就可以手动添加进去

**Comment by kcharwood** [comment]
Please use `setAcceptableContentTypes` to get any custom serialization you may need.

**Comment by QinghaoGuan** [comment]
OK，thank you。
