### ISSUE TITLE
Comiple error Afnetworking 3.0 Swift

### ISSUE THREAD

**Issue by TheEngineerz** [AFNetworking/AFNetworking#3489]
![screen shot 2016-05-03 at 10 05 22 am](https://cloud.githubusercontent.com/assets/5149947/14975027/a3228db6-1116-11e6-8c11-454a5a0308c1.png)

NSURLSessionDataTask or NSURLSessionTask both are giving same problem . kindly update the document or help me how to resolve it

**Comment by QoT** [comment]
I have similar issue. Do not know what is the root of the problem but you can help yourself by not specifying some parameter's type, in this case 'error' in POST method call:

>         manager.post("http://...", parameters: [:], progress: nil, success: { (operation: URLSessionDataTask, responseObject: Any?) in
>             print("Success")
>         }, failure: { (operation: URLSessionDataTask?, error) in
>             let error = error as? Error
>             print("Failure, error is \(error?.description)")
>         })
>
