### ISSUE TITLE
PUT Normal request processing,DELETE  But not ,

### ISSUE THREAD

**Issue by DevDragonLi** [AFNetworking/AFNetworking#3492]
If I PUT an array as a parameter, the PUT request processing, to print the header, URL parameter is normal, but the DELETE, will the internal processing of the parameter, cause the failure of the request.

**Comment by kcharwood** [comment]
Can you provide a more clear example of what you are describing?

**Comment by LFL2018** [comment]
1.PUT an array as a parameter.
NSString * IDStr = @"fffff"; 
 [tool PUT:path parameters: @[IDStr] success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) 
URL is normal.
2. DELETE With an array as a parameter.
NSString * IDStr = @"fffff"; 
 [tool PUT:path parameters: @[IDStr] success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) 
Url Stitching at the back of the array and the garbled, lead to errors
