### ISSUE TITLE
Why AFNetworkReachabilityManager support IPv6 need to do conditional compile?

### ISSUE THREAD

**Issue by wtlucky** [AFNetworking/AFNetworking#3498]
I don't understand why there needs to check the OS_VERSION_MIN_REQUIRED. This mean only the iOS version over 9.0 and OSX version over 10.11 supported IPv6. Is this right?  #3174 

``` objc
+ (instancetype)manager
{
#if (defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && __IPHONE_OS_VERSION_MIN_REQUIRED >= 90000) || (defined(__MAC_OS_X_VERSION_MIN_REQUIRED) && __MAC_OS_X_VERSION_MIN_REQUIRED >= 101100)
    struct sockaddr_in6 address;
    bzero(&address, sizeof(address));
    address.sin6_len = sizeof(address);
    address.sin6_family = AF_INET6;
#else
    struct sockaddr_in address;
    bzero(&address, sizeof(address));
    address.sin_len = sizeof(address);
    address.sin_family = AF_INET;
#endif
    return [self managerForAddress:&address];
}
```

**Comment by balloonsys** [comment]
Maybe you can refer "Use System APIs to Synthesize IPv6 Addresses" section in following page -
[https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16](url)

**Comment by kcharwood** [comment]
Take a look at this issue: https://github.com/Alamofire/Alamofire/issues/1228.

We need to make sure we are consistent in both places.

**Comment by taylesworth** [comment]
Except AlamoFire uses a run-time check rather than a compile-time check, right?

**Comment by kcharwood** [comment]
Yes, that rights, mainly due to some bugs with how iOS 8 work with IPv6

**Comment by wtlucky** [comment]
Yes，I have found this bug both iOS 7 and iOS 8 works with IPv6. But why not use run-time check there? If I use the iOS 9 SDK compile the project and running it on iOS 7, the bug still exist.

**Comment by kcharwood** [comment]
Right. I'm agreeing with you. We should probably migrate to a runtime check.

**Comment by hei9gag** [comment]
I am using iOS 9 and connect to a NAT64 network hotspot share from my Mac. I try to test the AFNetworking Reachability without ipv6 setting and it still works. Can someone explain? Many thanks.

**Comment by cezheng** [comment]
However in the [README](https://developer.apple.com/library/ios/samplecode/Reachability/Listings/ReadMe_md.html#//apple_ref/doc/uid/DTS40007324-ReadMe_md-DontLinkElementID_11) of the [Reachability sample](https://developer.apple.com/library/ios/samplecode/Reachability/Listings/Reachability_Reachability_m.html#//apple_ref/doc/uid/DTS40007324-Reachability_Reachability_m-DontLinkElementID_9), it says

```
Reachability fully supports IPv6.  More specifically, each of the APIs handles IPv6 in the following way:

...

- reachabilityForInternetConnection:  This monitors the address 0.0.0.0, which reachability treats as a special token that causes it to actually monitor the general routing status of the device, both IPv4 and IPv6.
```

So what is the actual reason to use `sockaddr_in6` on iOS 9 or later? I just worry that it will cause problems when connected to a IPv4-only network

**Comment by hei9gag** [comment]
It seems the Reachability function is not compatible to iOS 7. The function returns no reachable status even I have connected to a NAT64 share network. Is this a bug or iOS 7 isn't support NAT64? 

Also I found that reachabilityDidChange is slightly delay to trigger in iOS 8 (compare to iOS 9) when I try to connect to a IPv6 network from no network status.

**Comment by dustturtle** [comment]
I agree with cezheng. Demo by apple maybe right. I will just use the sockaddr_in in my app. @cezheng

**Comment by KenShin-Tang** [comment]
There is no need to change anything if you just want to check whether the internet is avaliable,just like the Sample by Apple: `reachabilityForInternetConnection //This monitors the address 0.0.0.0, which reachability treats as a special token that causes it to actually monitor the general routing status of the device, both IPv4 and IPv6.` ,  is it right?

**Comment by KenShin-Tang** [comment]
There is no need to change anything if you just want to check whether the internet is avaliable,just like the Sample by Apple:
` reachabilityForInternetConnection //This monitors the address 0.0.0.0, which reachability treats as a special token that causes it to actually monitor the general routing status of the device, both IPv4 and IPv6`  is it right?

**Comment by cezheng** [comment]
@kcharwood Shall we draw to a conclusion yet? I think we should remove the `sockaddr_in6 address` part of the code.

**Comment by dustturtle** [comment]
But I think the solution used here is also correct. We can use ipv4/ipv6 either under iOS9 in this condition.

**Comment by AdrianaPineda** [comment]
@kcharwood do you have any updates on this? Should the os version check be removed as Alamofire?

**Comment by xx-li** [comment]
My app minimum supported version of the app is iOS9,  use AFNetworking by cocoapods, when run at any device, `__IPHONE_OS_VERSION_MIN_REQUIRED` value is `70000`，Causing  works with IPv4 all the time。

**Comment by shumintao** [comment]
can you tell me  how  to  use  AlamoFire for  swift  in  IVP6
