### ISSUE TITLE
why excute self.session getTasksWithCompletionHandler in initWithSessionConfiguration?

### ISSUE THREAD

**Issue by mamingzxc** [AFNetworking/AFNetworking#3499]
i see that  self.session getTasksWithCompletionHandler on initWithSessionConfiguration method in AFURLSessionManager class, is the tasks of self.session when was inited nil?

**Comment by kcharwood** [comment]
I believe this for restoring a session from the background.

**Comment by ccwinner** [comment]
Sorry for asking a question in closed issue. I'm quite confused about "I believe this for restoring a session from the background". The 'background' means after the duration when app
is suspended by the system or from another thread?

**Comment by ptlCoder** [comment]
为了防止后台回来，重新初始化这个session，一些之前的后台请求任务，导致程序的crash。
