### ISSUE TITLE
Version defines

### ISSUE THREAD

**Issue by mateuszmackowiak** [AFNetworking/AFNetworking#3503]
Please add a define or other declaration of the current framework release version. With that frameworks can adjust to multiple versions of the code. Like in the Availability.h or something.

**Comment by kcharwood** [comment]
This is a good idea. Would you like to put together a PR?

**Comment by mateuszmackowiak** [comment]
Created one but not sure why it didn't pass the tests.
https://github.com/AFNetworking/AFNetworking/pull/3512
