### ISSUE TITLE
Does not support 32-bi in upload callback

### ISSUE THREAD

**Issue by yuhanle** [AFNetworking/AFNetworking#3507]
The latest version of the callback upload file does not support 32-bit systems.

When I upload some pictures, the progress callback can not be loaded. 

ps:
maybe less than iOS 8.0 in 32-bit systems

**Comment by kcharwood** [comment]
Can you create a test demonstrating this problem? This would show up on a iPhone 4s, correct?

**Comment by yuhanle** [comment]
https://github.com/yuhanle/BSWAFNUploadPicDemo

This is a demo @kcharwood 

![qq20160517-0 2x](https://cloud.githubusercontent.com/assets/10498756/15314131/9e6391ee-1c42-11e6-8911-a12227060e4c.png)
