### ISSUE TITLE
AFURLSessionManager in AFNetworking3.0

### ISSUE THREAD

**Issue by wangfanglyf** [AFNetworking/AFNetworking#3508]
(void)URLSession:(__unused NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error in NSURLSessionTaskDelegate .It uses dispatch_group_async.why?Why put all the "completionHandler" together? Does that mean all the "comletionHandler" back at the same time,it should wait all of them executing over?

**Comment by kcharwood** [comment]
That's actually a good question. Looking back through the history, this appears to be a part of the initial 2.0 branch, and I can't find a specific issue referencing the implementation. For now, better to leave as is :)

🍻

**Comment by wangfanglyf** [comment]
haha ok~
