### ISSUE TITLE
downloadProgress block in downloadTaskWithRequest is not called under AFNetworking 3.1.0 When downloading a gzip file

### ISSUE THREAD

**Issue by AWDGroup** [AFNetworking/AFNetworking#3509]
``` Objective-C
NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];

NSURL *URL = [NSURL URLWithString:@"https://s3.amazonaws.com/awdtest/fullzip.pdf"];
NSURLRequest *request1 = [NSURLRequest requestWithURL:URL];

NSURLSessionDownloadTask *downloadTask1 = [manager downloadTaskWithRequest:request1 progress:^(NSProgress * _Nonnull downloadProgress)
{
    NSLog(@"Progress: %f", downloadProgress.fractionCompleted);
} destination:^NSURL *(NSURL *targetPath, NSURLResponse *response)
{
    NSURL *documentsDirectoryURL = [[NSFileManager defaultManager] URLForDirectory:NSDocumentDirectory inDomain:NSUserDomainMask appropriateForURL:nil create:NO error:nil];
    return [documentsDirectoryURL URLByAppendingPathComponent:[response suggestedFilename]];
} completionHandler:^(NSURLResponse *response, NSURL *filePath, NSError *error)
{
    NSLog(@"File downloaded to: %@", filePath);
}];
[downloadTask1 resume];
```

Response headers:

```
HTTP/1.1 200 OK
x-amz-id-2: CW06YcgIycOHZQy8bCJrT3aNfhatM9pty1mOjgYHumjCxRmNAQ+jhJHRQwl7mDIaQeTHI0fyrnU=
x-amz-request-id: 105E010DECC91897
Date: Sat, 14 May 2016 09:26:38 GMT
Content-Encoding: gzip
Last-Modified: Sat, 14 May 2016 09:21:29 GMT
ETag: "88bbe0b318bf11dd56a31176d3384e78"
Accept-Ranges: bytes
Content-Type: application/pdf
Content-Length: 1243325
Server: AmazonS3
```

it works if I use this file which is not gzipped: https://s3.amazonaws.com/awdtest/full.pdf

Response headers:

```
HTTP/1.1 200 OK
x-amz-id-2: gFOVfhheaMdeJOBb+7H8oaXjLLeOqlQl616XnYx6C2Gj7PBVLKZ9kMIN2fJOrGBcSgQ/7nbQOc0=
x-amz-request-id: 26669D9B576E300A
Date: Sat, 14 May 2016 09:54:58 GMT
Last-Modified: Fri, 16 May 2014 05:42:35 GMT
ETag: "6f16d7e09023ce8b50fd67abba7825c4"
Accept-Ranges: bytes
Content-Type: application/pdf
Content-Length: 1411131
Server: AmazonS3
```

**Comment by AWDGroup** [comment]
Any update on this?

**Comment by kamrankhan07** [comment]
i am also facing this issue.

**Comment by kamrankhan07** [comment]
i am also facing similar issue with .txt and .mp3 files.

**Comment by shantj** [comment]
now，me too

**Comment by AWDGroup** [comment]
If you want to get an approximate progress you can add the following code to get the totalUnitCount from the Content-Length in the response header

AFURLSessionManager:
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSString *,id> *)change context:(void *)context

          .....

          else if ([keyPath isEqualToString:NSStringFromSelector(@selector(countOfBytesExpectedToReceive))]) {

            self.downloadProgress.totalUnitCount = [change[NSKeyValueChangeNewKey] longLongValue];

            if (self.downloadProgress.totalUnitCount == NSURLSessionTransferSizeUnknown) {

                NSURLResponse * response = [((NSURLSessionDownloadTask *)object) response];

                if ([response isKindOfClass:[NSHTTPURLResponse class]]) {

                    NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse*)response;

                    if ([httpResponse respondsToSelector:@selector(allHeaderFields)]) {

                        NSDictionary *dictionary = [httpResponse allHeaderFields];

                        if ([dictionary valueForKey:@"Content-Length"] != [NSNull null]) {

                            self.downloadProgress.totalUnitCount = [[dictionary valueForKey:@"Content-Length"] longLongValue];

                        }

                    }

                }

            }

        }

        .....

**Comment by Yienders** [comment]
me too~

**Comment by Yienders** [comment]
i have solved it, because the file is too small,you  can download a large file,then the block will run.

**Comment by Ackerman64** [comment]
When you download some binary file like zip, build the request like this:

`NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
[request addValue:@"" forHTTPHeaderField:@"Accept-Encoding"];`

Setting blank for "Accept-Encoding" tells the the server that the client is not ready to accept the response in any specific format. So server simply bypasses "gzip" ping the response stream and returns the raw bytes. NSURLSession delegate expected length will not return NSURLSessionTransferSizeUnknown any more.
