### ISSUE TITLE
AFNetworking 3.0 upload image time out

### ISSUE THREAD

**Issue by lvsht** [AFNetworking/AFNetworking#3511]
I use afnetworking http put method to upload image with image base64 code as parameter put in paramDic but  when i upload some image bigger than about 100kb ,the api call time out . while a smaller image uploading is ok.  

the code is like bellow:
                 for (NSString * imageString in imagesDic) {
                    
                    UIImage * image = [imagesDic objectForKey:imageString];
                    NSDictionary * imageDic = @{ @"mimetype":@"image/png",@"content":[UIImage getImageBase64Data:image]};
                    
                    [files addObject:imageDic];
                }
                
                NSDictionary * putDic = @{@"type":@(type) , @"files":files};
                
                
                                [[NetworkManager shareInstance] executeRequest:url urlType:ePutRequest getDict:nil postData:putDic
                                                                       success:^(NSURLSessionDataTask * task, id _Nullable error) {
                                                                           NSLog(@"uploadImages successful");
                                                                           NSURL * url = task.response.URL;
                                                                           
                                                                           [urlArray addObject:url.absoluteString];
                                                                           
                                                                           NSString * jsonString = [NSString dicOrArrayToJsonString:@{@"files":urlArray}];
                //                                                           [weakSelf webViewEvaluateJavaScriptWithActionString:action paramsJsonString:jsonString];
                                                                           
                                                                           [weakSelf hideProgressBar];  
                                                                       } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
                                                                           NSLog(@"uploadImages error with %@",error.description);
                                                                           [self showMessage:error.localizedDescription];
                                                                           [weakSelf hideProgressBar];
                                                                       }];

while the executeRequest method called the 

- (NSURLSessionDataTask *)PUT:(NSString *)URLString
                   parameters:(id)parameters
                      success:(void (^)(NSURLSessionDataTask *task, id responseObject))success
                      failure:(void (^)(NSURLSessionDataTask *task, NSError *error))failure

method in AFHTTPSessionManager

the curl command is like this: 

 curl -X PUT -H 'User-Agent: sales/1.0 (iPhone; iOS 9.2.1; Scale/2.00)' -H 'Accept-Language: zh-Hans-CN;q=1' -H 'Content-Type: application/json' -H 'access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IkM3QTczRjJFLThBOUMtNEVCRC05NUJELURCQzZGMDJCODZGRSIsInVzZXJJZCI6IkVGRTg5OUU2LTY1QzYtRTUxMS05MDlDLUQ4OUQ2NzJCMzUyQiIsImlhdCI6MTQ2MjUyNzc0NH0.7Maqykze7X4oIWooRNzoHaW8TDoOo5uc5EigkqmVy5o' 'http://120.26.55.59:9877/api//sales/dealer/d235d481-8213-491a-8cc7-a55c27e7fb12/picInfo?appId=3c07d472-f9f0-4246-9add-cfe26c4f1644&files%5B%5D%5Bcontent%5D=iasdfadf”,”mimetype":"image\/png"}]}'

when the content string is much longer then the put request time out.

and when i use MKNetworkKit , there is no error.
who please tell me why this situation happened and how to solve this.
thank you ~~

**Comment by kcharwood** [comment]
Would you be able to put together a failing test hitting http://httpbin.org/gzip?

**Comment by kcharwood** [comment]
There hasn't been any activity on this issue recently. I'm closing this now to clean up some old issues. If this issue persists with the latest version of AFNetworking, or you have a reproducible test case, please open a new issue and reference this issue.

Thanks! 🍻
