### ISSUE TITLE
embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/AFNetworking.framework/AFNetworking) for architecture x86_64

### ISSUE THREAD

**Issue by VictorZhang2014** [AFNetworking/AFNetworking#3513]
Hi~  Mr.kCharWood.
I got an error below it is a detail issue when I upgraded this framework to 3.0 version.
Because of supporting iOS7.0 . This project that my company's demand so I really help you can help me.
If I wanna support iOS7.0 when I'm using the latest version of AFN v3.0 . How can I do?
I'm really appreciate you can help me with.

embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/AFNetworking.framework/AFNetworking) for architecture x86_64

**Comment by VictorZhang2014** [comment]
I have solved this issue . The reason is My project's Podfile below 
platform :ios, '7.0'
use_frameworks!

target 'AFNetwork_DEMO' do
pod 'AFNetworking', '~> 3.0'
end

If developers add this use_frameworks!   , and then Xcode compile the minimum target is iOS 8.
If developers remove this use_frameworks!, everything will be okay.

Thanks for AFN team!

**Comment by kpower** [comment]
'use_frameworks!' is mandatory in some situations (hello, 'libextobjc' + modules enabled). So, it's better to have fixed minimum target for framework-based setup.
