### ISSUE TITLE
Does AF support IPv6-only?

### ISSUE THREAD

**Issue by iamqk** [AFNetworking/AFNetworking#3514]
as apple says:
https://developer.apple.com/news/?id=05042016a

does AF already support this function?

thx

**Comment by VictorZhang2014** [comment]
Yeah! AFN v3.0 have already supported IPv6  within compatibility IPv4

**Comment by iamqk** [comment]
thank goodness

**Comment by megarzzy** [comment]
@VictorZhang2014   how to test,maybe i make a mistake ,i construct a ipv6 only hotspot as apple say.
i test like this:
- (IBAction)onafn1:(id)sender {
    
#if 1
    // show result
    //    labeltext.numberOfLines = 0;
    [mytextview setText:@""];
    NSURL *URL = [NSURL URLWithString:@"http://xxx/app/list/14005_6418_2_10.json"];
    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    __block NSMutableString * errosrstring = nil;
    [manager GET:URL.absoluteString parameters:nil success:^(NSURLSessionTask *task, id responseObject) {
        NSLog(@"success JSON: %@", responseObject);
        errosrstring = [NSMutableString stringWithFormat:@"success json:%@", responseObject];
        [mytextview setText:errosrstring];
    } failure:^(NSURLSessionTask *operation, NSError *error) {
        NSLog(@"fail  Error: %@", error);
        errosrstring = [NSMutableString stringWithFormat:@"fail error:%@",[error localizedDescription]];
        [mytextview setText:errosrstring];
    }];
NO set NAT64 is ok,but is Set NAT64 ,it reports connectin lost ?could you guide me ?

**Comment by VictorZhang2014** [comment]
http://xxx/app/list/14005_6418_2_10.json

**Comment by VictorZhang2014** [comment]
http://xxx/app/list/14005_6418_2_10.json
This url is a IPv4 URL IP ADDRESS or IPv6 URL IP ADDRESS.
Check it out please! 
And your writing code is correct!

**Comment by bravebang** [comment]
Does version 2.6.3 support ipv6?

**Comment by VictorZhang2014** [comment]
@bravebang No ,it doesn't support IPv6 when you're using version 2.6.3.

**Comment by bravebang** [comment]
Got it, thank you.

**Comment by taylesworth** [comment]
@bravebang @VictorZhang2014 Why do you say that when others have reported that IPv6-only networks work fine on version 2.6.3?

https://github.com/AFNetworking/AFNetworking/issues/3517

**Comment by HemantRMali** [comment]
How to get ipv6 support on version 2.6.3?

**Comment by HemantRMali** [comment]
If I switch to version  3.0 there are a lot of syntax errors.
