### ISSUE TITLE
AFNetworking + expected identifer or '('

### ISSUE THREAD

**Issue by kpraveen45** [AFNetworking/AFNetworking#3515]
I am using cocoapods for AFNetworking. I am using AFNetworking v2.6.1. XCode 7.3.1, OSX 10.11.4.
iOS 8.0+

I am getting following error while compilation: AFHTTPRequestOperation.h (this file contains following line only) ../../../AFNetworking/AFNetworking/AFHTTPRequestOperation.h -> Expected Identifier or '('

I am sure i am using xcworkspace file to open in xcode. is there anything i am missing

**Comment by VictorZhang2014** [comment]
Sticking your error message in detail.

**Comment by kpraveen45** [comment]
Error Message in detail:

 Pods/Headers/Private/AFNetworking/AFHTTPRequestOperation.h
 Pods/Headers/Private/AFNetworking/AFHTTPRequestOperation.h:1:1: Expected identifier or '('
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:35:47: Use of undeclared identifier 'AFURLConnectionOperation'
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:36:44: Expected expression
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:36:18: Use of undeclared identifier 'AFURLConnectionOperation'
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:36:59: Expected ']'
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:80:109: Use of undeclared identifier 'AFNetworkingOperationDidStartNotification'
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:81:110: Use of undeclared identifier 'AFNetworkingOperationDidFinishNotification'
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:84:109: Use of undeclared identifier 'AFNetworkingTaskDidResumeNotification'
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:85:110: Use of undeclared identifier 'AFNetworkingTaskDidSuspendNotification'
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:86:110: Use of undeclared identifier 'AFNetworkingTaskDidCompleteNotification'
 Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:103:84: Use of undeclared identifier 'kAFNetworkActivityIndicatorInvisibilityDelay'

**Comment by VictorZhang2014** [comment]
You should upgrade AFN framework to the latest. 
The detail shows all are undeclared . Because  they have been removed from the latest version of AFN.

**Comment by VictorZhang2014** [comment]
You'll see it in the cocoapods recording while you have already upgraded AFN framework .
