### ISSUE TITLE
Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7fb72a411c00> { URL: http://www.apple.com/ }

### ISSUE THREAD

**Issue by VictorZhang2014** [AFNetworking/AFNetworking#3516]
**# When I request a GET  and then it returned an error in error block. The following is error message**

Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7fb72a411c00> { URL: http://www.apple.com/ }

## **And My code below**

    NSString *url = @"http://www.apple.com"; 
 
    AFHTTPSessionManager *manager = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:url]];
    [manager GET:@"" parameters:nil progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        NSLog(@"response = %@", responseObject);
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@"error = %@", error);
    }];
    

I wanna know how to send a request with GET or POST in right code.
Thanks!

**Comment by pwsmobileaccount** [comment]
This means that your server is sending "text/html" instead of the already supported types. My solution was to add "text/html" to acceptableContentTypes set in AFURLResponseSerialization class. Just search for "acceptableContentTypes" and add @"text/html" to the set manually.

**Comment by VictorZhang2014** [comment]
Yep. I solved this problem.
When we created an object with initialized two serializer object that can okay to request.

Part of code below
 
_manager = [AFHTTPSessionManager manager];
        _manager.requestSerializer = [AFHTTPRequestSerializer serializer];
        _manager.responseSerializer = [AFHTTPResponseSerializer serializer];

**Comment by zsading** [comment]
@VictorZhang2014 It works for me

**Comment by lizhaojie001** [comment]
<7b22746f 74616c22 3a20302c 22726f77 73223a20 5b5d7d>

**Comment by lizhaojie001** [comment]
manager.requestSerializer = [AFHTTPRequestSerializer serializer];
_manager.responseSerializer = [AFHTTPResponseSerializer serializer];

加了上面的之后

**Comment by Haibo-Zhou** [comment]
Per your error log, you need this one `text/html`.

```
// fix error "Code=-1016
manager.responseSerializer.acceptableContentTypes = [[NSSet alloc] initWithObjects:@"text/plain", @"text/html", @"application/json", @"audio/wav", @"application/octet-stream", @"text/javascript", nil];
```
