### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by haoyongxin** [AFNetworking/AFNetworking#3517]
Does 3.0 support ipv6?

**Comment by VictorZhang2014** [comment]
Off course! It supports IPv6 while you're using AFN v3.0.

**Comment by Sky891028** [comment]
Does version~2.6.3 support ipv6?

**Comment by VictorZhang2014** [comment]
No. It doesn't. Only AFN v3.0.

在 2016-05-20 13:39:33，"Sky891028" <notifications@github.com> 写道：


Does version~2.6.3 support ipv6?

**Comment by taylesworth** [comment]
> No. It doesn't. Only AFN v3.0.

Given the discussion [here](https://github.com/AFNetworking/AFNetworking/issues/3496), I don't think that's clear. 

It appears that AFNetworking 2.6.3 uses the same mechanism as Apple's Reachability sample code, which does support IPv6-only networks. Also posters say they tested it themselves and claim it works in an IPv6-only environment.

**Comment by kmilitagaitanm** [comment]
Yesterday,  I tested our app  and  it's working perfectly with AFNetworking  2.6.3 and ipv6

**Comment by wtuyp** [comment]
I tested my apps too and they work OK with AFNetworking 2.6.3 in IPv6 and iOS9. But didn't work in IPv6 and iOS7, I think iOS7 do not support IPv6, maybe iOS8 too.

a comment here [link](https://github.com/Alamofire/Alamofire/issues/1228) says,

> iOS 8 didn't have NAT64 support, so any iOS 8 device on an IPv6-only network would be hopelessly crippled. Based on that, I'm pretty sure that as long as your code uses the IPv4 APIs only when actually running on iOS 8 and earlier (i.e. run-time checks, not build-time checks), you should be fine.

**Comment by kcharwood** [comment]
Its still a bit unclear how Apple is going to enforce this, and what their app store minimum requirements are going to be. We're still playing by ear a little bit right now.

**Comment by panhao19920317** [comment]
When I use it in IOS 7,the device can not get the data

**Comment by jingn** [comment]
if use AFN3.0, CocosPods have to update to 1.0,  Is't ?

**Comment by Tinghui** [comment]
in AFNetworkReachabilityManager.m, the code `#if (defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && __IPHONE_OS_VERSION_MIN_REQUIRED >= 90000)` checks minimum OS version being targeted >= 9.0. So does it means if the iOS Deployment Target is 8.0 then even if the final app runs on an iOS 10 device, it is still not support ipv6?
