### ISSUE TITLE
Incorrect parameters encoding when using constructingBodyWithBlock

### ISSUE THREAD

**Issue by revolter** [AFNetworking/AFNetworking#3518]
I am creating a `POST` request with parameters like:

```
NSDictionary *parameters = @{
    @"key": @[@{
        @"subkey1_1": @"value1_1",
        @"subkey1_2": @"value1_2"
    }, @{
        @"subkey2_1": @"value2_1",
        @"subkey2_2": @"value2_2"
        }
    ]
};
```

and on the (PHP) server-side, the `$_POST` variable is correctly empty, and it uses a Yii utility method to extract the parameters as nested arrays from the request's raw body like this:

![screen shot 2016-05-17 at 17 08 58](https://cloud.githubusercontent.com/assets/5748627/15325184/425504e0-1c52-11e6-8a56-c53a03c3710a.png)

When I use the `POST:parameters:constructingBodyWithBlock:progress:success:failure:` method, with this block:

```
[formData appendPartWithFileData:pictureData name:@"picture" fileName:@"picture.jpg" mimeType:@"picture/jpeg"];
```

the rest of the parameters are showing up in the `$_POST` variable instead.

The problem arises when the parameters object contains nested arrays/dictionaries like in the given example, in which case the `$_POST` variable looks like this:

![screen shot 2016-05-17 at 17 08 49](https://cloud.githubusercontent.com/assets/5748627/15325200/52f88a06-1c52-11e6-8a95-f8d402d6fc12.png)

and you can't tell which key belongs to which array dictionary element.

How can I force the parameters to be sent like in the first case, while attaching form data too?

I'm sorry if the description is not clear enough or I forgot to add necessary information. Please ask me about it and I will gladly add them.

**Comment by trylovetom** [comment]
#619
