### ISSUE TITLE
Upgrade AFHTTPClient in version 3.0

### ISSUE THREAD

**Issue by JOjha** [AFNetworking/AFNetworking#3519]
Hey Matt,

Thanks for a nice networking Library and your effort is awesome.
I am using AFNetworking from long time now I am updating my pod to 3.0.I have changed complete code to AFHTTPSessionManager.

I also want to convert AFHTTPClient in 3.0 and get the NSMutableRequest return type.I did it but not getting proper return type.Below are my code which I am using in 1.0 version.

```
AFHTTPClient *httpClient = [[AFHTTPClient alloc] initWithBaseURL:[NSURL URLWithString:host]];
NSMutableURLRequest *request = [httpClient requestWithMethod:@"GET" path:path parameters:params];
return request;
```

My changes

```
AFHTTPSessionManager *manager = [[AFHTTPSessionManager alloc]initWithBaseURL:[NSURL URLWithString:host]];
NSMutableURLRequest *request = [[AFJSONRequestSerializer serializer] requestWithMethod:method URLString:path parameters:params error:nil];
return request;
```

This is not working for me.

Can you please help me for converting above code to 3.0.
Waiting for your positive response.

Thanks

**Comment by kcharwood** [comment]
This second line should generate a valid `NSURLRequest`. You are saying you see otherwise?

You can see here in `AFHTTPSessionManager` this is exactly how requests are created.

**Comment by kcharwood** [comment]
There hasn't been any activity on this issue recently. I'm closing this now to clean up some old issues. If this issue persists with the latest version of AFNetworking, or you have a reproducible test case, please open a new issue and reference this issue.

Thanks! 🍻
