### ISSUE TITLE
https challenge for IP requests

### ISSUE THREAD

**Issue by wangyutao0424** [AFNetworking/AFNetworking#3523]
what do u think about this? 
we use IP requests, bu it can't passed evaluate : (
we use tag 2.6.3

- (void)connection:(NSURLConnection *)connection
willSendRequestForAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge
{
    if (self.authenticationChallenge) {
        self.authenticationChallenge(connection, challenge);
        return;
    }

    if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {

        NSString* host = [[self.request allHTTPHeaderFields] objectForKey:@"host"];
        if (!host) {
            host = self.request.URL.host;
        }

        if ([self.securityPolicy evaluateServerTrust:challenge.protectionSpace.serverTrust forDomain:host]

……

**Comment by wangyutao0424** [comment]
or like this：

NSString* host = [[self.request allHTTPHeaderFields] objectForKey:@"host"];
if (!host) {
    host = challenge.protectionSpace.serverTrust;
}

**Comment by kcharwood** [comment]
I'm not sure what error you are trying to solve. Perhaps this is related to App Transport Security?

**Comment by kcharwood** [comment]
There hasn't been any activity on this issue recently. I'm closing this now to clean up some old issues. If this issue persists with the latest version of AFNetworking, or you have a reproducible test case, please open a new issue and reference this issue.

Thanks! 🍻
