### ISSUE TITLE
Domain switching problem

### ISSUE THREAD

**Issue by KuratasZ** [AFNetworking/AFNetworking#3528]
域名切换问题
我的项目中使用了AFN3.0，后来切换了服务器的域名，但是部分app出现问题，原始域名 post 请求，会变成新域名的get请求，导致服务器无法处理给出了错误的返回，而重新下载app后问题就消失了
我的疑问是，AFN内部实现中是否对DNS解析做了缓存，我的水平很低，英语也不是太好，不是太能看懂AFN的实现代码，希望有人能解决我的疑问，我是中国人
这个问题对我很重要，有任何答案都可以直接邮件我z.o.e@outlook.com

Domain switching problem
My project in the use of AFN3.0 and later switched the domain name of the server, but part of the app appears problem, original domain name post request, will become the new domain name get request, lead to the server was unable to process gives the error returned, and re download the app after problems have disappeared
I doubt, AFN internal implementation whether to DNS caching, my level is very low, English is not so good, not too can understand AFN the code, I hope someone can answer my question, I am Chinese
This question is very important to me, there are any answers can be directly mail me z.o.e@outlook.com

**Comment by kcharwood** [comment]
Hi @KuratasZ. AFNetworking uses NSURLSession for the actual request transmission, and does nothing specific with DNS caching. This sounds like an issue with logic in your codebase.

**Comment by KuratasZ** [comment]
Thank you，maybe is my codebase
