### ISSUE TITLE
Possible missing empty line between headers and body

### ISSUE THREAD

**Issue by revolter** [AFNetworking/AFNetworking#3529]
Is there any possibility in which AFNetworking would not insert an empty line between the headers and the body? Something like:

	POST /api/user/signup HTTP/1.1
	Content-Type: application/json; charset=utf-8
	Host: localhost
	Connection: close
	User-Agent: Paw/2.3.4 (Macintosh; OS X/10.11.4) GCDHTTPRequest
	Content-Length: 126
	{"user":{"name":"Test name","email":"test@email.com"}}

instead of:

	POST /api/user/signup HTTP/1.1
	Content-Type: application/json; charset=utf-8
	Host: localhost
	Connection: close
	User-Agent: Paw/2.3.4 (Macintosh; OS X/10.11.4) GCDHTTPRequest
	Content-Length: 126

	{"user":{"name":"Test name","email":"test@email.com"}}

?

I get an error on the server that looks like it is trying to JSON parse the whole raw request content, starting from `POST  /api/user/signup HTTP/1.1`.

**Comment by kcharwood** [comment]
AFNetworking uses `NSURLRequest` and `NSURLSession`, so you are getting default system behavior for the actual request format sent over the wire.
