### ISSUE TITLE
The dependency `AFNetworking (~> 3.0)` is not used in any concrete target

### ISSUE THREAD

**Issue by infinZero** [AFNetworking/AFNetworking#3531]
I am on mac OS X EI Capitan, version 10.11.3 and using Xcode version 7.2.1, 
I created a pod file in my project directory & write following lines in pod file as mentioned in AFNetworking pod file installation

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'

after writing those above lines in podfile I tried to install pod with this command line.
pod install
and getting following error each & every-time

"The dependency `AFNetworking (~> 3.0)` is not used in any concrete target"

I also tried using cocoaPods software available with 1.0.0 but same error again & again.
could anyone help me to sort out this issue???
Thanks

**Comment by richardgroves** [comment]
As of CocoaPods 1.0 you have to have a 'target' section in your PodFile.

So your example would become:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target '<Your Target Name>' do

pod 'AFNetworking', '~> 3.0'

end

Your problem has nothing to do with AFNetworking - it is the breaking
changes in CocoaPods 1.0 - see
http://blog.cocoapods.org/CocoaPods-1.0-Migration-Guide/ for details.

Using the new CocoaPods app - https://cocoapods.org/app - I got it to
update my PodFiles for me to the new spec.

On Sat, May 21, 2016 at 4:50 PM, infinZero <notifications@github.com> wrote:

> I am on mac OS X EI Capitan, version 10.11.3 and using Xcode version
> 7.2.1,
> I created a pod file in my project directory & write following lines in
> pod file as mentioned in AFNetworking pod file installation
>
> source 'https://github.com/CocoaPods/Specs.git'
> platform :ios, '8.0'
>
> pod 'AFNetworking', '~> 3.0'
>
> after writing those above lines in podfile I tried to install pod with
> this command line.
> pod install
> and getting following error each & every-time
>
> "The dependency AFNetworking (~> 3.0) is not used in any concrete target"
>
> I also tried using cocoaPods software available with 1.0.0 but same error
> again & again.
> could anyone help me to sort out this issue???
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AFNetworking/AFNetworking/issues/3531>
>



-- 
Richard Groves
Technical Director | NoodlFroot

M: +44 (0)7962 054 163

www.noodlfroot.com

NoodlFroot Limited is a company registered in England and Wales with
registration number 07245048.
Registered office: 20-22 Wenlock Road, London, N1 7GU.

**Comment by kcharwood** [comment]
Thanks!
