### ISSUE TITLE
tasks and dataTasks array's are always empty in afnetworking 3?

### ISSUE THREAD

**Issue by kushal297** [AFNetworking/AFNetworking#3532]
can anyone help me with this? 

[tasks and dataTasks array's are always empty in afnetworking 3?](http://stackoverflow.com/questions/37219746/tasks-and-datatasks-arrays-are-always-empty-in-afnetworking-3)

**Comment by kcharwood** [comment]
If you peak into the code, you can see `AFURLSessionManager` is just calling `getTasksWithCompletionHandler` on the `NSURLSession` itself. You could start there, and work backwards to see why you have no tasks.
