### ISSUE TITLE
How can i get responseString which at AFNetworking 3.0 .

### ISSUE THREAD

**Issue by devtofu** [AFNetworking/AFNetworking#3534]
like `operation.responseString` ..

**Comment by devtofu** [comment]
Sometimes, the server returns an invalid JSON format, I need to know what is responseString, but i can't find it in the AFNetworking 3.0

**Comment by Mekor** [comment]
```
NSError *underError = error.userInfo[@"NSUnderlyingError"];
NSData *responseData = underError.userInfo[@"com.alamofire.serialization.response.error.data"];
```

**Comment by devtofu** [comment]
@Mekor thank you ！

**Comment by nickenchev** [comment]
How do you actually get the raw response string in the success callback, is that not what the OP said?

**Comment by caoMingLiang** [comment]
只有error的的描述。没有operation.responseString
