### ISSUE TITLE
Is AFNetworking support ProtocolBuf?

### ISSUE THREAD

**Issue by brilliance-boy** [AFNetworking/AFNetworking#3536]
Is AFNetworking support ProtocolBuf?

Thank you very much.

**Comment by kcharwood** [comment]
Protocol Buffers are not something on the roadmap for this library. This potentially makes sense as an extension or a separate library all together.

🍻 

[Reference](https://github.com/AFNetworking/AFNetworking/pull/1992#issuecomment-40314651) to another issue.
