### ISSUE TITLE
AFJSONResponseSerializer incorrect NSCopying support

### ISSUE THREAD

**Issue by ogubariev** [AFNetworking/AFNetworking#3537]
AFJSONResponseSerializer class supports NSCopying protocol and we can see follow implementation:
```
- (instancetype)copyWithZone:(NSZone *)zone {
    AFJSONResponseSerializer *serializer = [[[self class] allocWithZone:zone] init];
    serializer.readingOptions = self.readingOptions;
    serializer.removesKeysWithNullValues = self.removesKeysWithNullValues;
    return serializer;
}
```
May be, here you should call method from parent class '**[super copyWithZone:zone]**' instead the code '**[[[self class] allocWithZone:zone] init]**'?  Because in current implementation follow fields '**acceptableStatusCodes**' and '**acceptableContentTypes**' aren't copied.

**Comment by kcharwood** [comment]
Thanks for pointing this out. I think this in fact a bug here.

The NSCopying docs state the following:

> Implement NSCopying by invoking the superclass’s copyWithZone: when NSCopying behavior is inherited. If the superclass implementation might use the NSCopyObject function, make explicit assignments to pointer instance variables for retained objects.

**Comment by kcharwood** [comment]
Lets move discussion to #3559.

Would appreciate you reviewing those changes @ogubariev 

Thanks! 🍻
