### ISSUE TITLE
When I use test with ios8.4.1 and IPv6 and AFN2.6.3, it doesn't work, I need some help.

### ISSUE THREAD

**Issue by guoranliaoran** [AFNetworking/AFNetworking#3538]
My AFN version is 2.6.3, When I use ios8.4.1 and IPv6,it doesn't work,I don't no why. But it works when change IPv6 to IPv4 in ios8.4.1. 
 iOS9.x doesn't have this problem, it works no matter in IPv6 or IPv4.
I just want to know if AFN(2.6.3)  support iOS8.x  or iOS7.x in IPv6 now. Thanks a lot.

**Comment by bravebang** [comment]
Me too

**Comment by ftxbird** [comment]
me too

**Comment by hei9gag** [comment]
same here

**Comment by AravinthChandran** [comment]
Guys, a comment in this [link] (https://github.com/Alamofire/Alamofire/issues/1228) says,

> iOS 8 didn't have NAT64 support, so any iOS 8 device on an IPv6-only network would be hopelessly crippled. Based on that, I'm pretty sure that as long as your code uses the IPv4 APIs only when actually running on iOS 8 and earlier (i.e. run-time checks, not build-time checks), you should be fine.
