### ISSUE TITLE
When I  Use AFN3.0, it does not working

### ISSUE THREAD

**Issue by WWLJ** [AFNetworking/AFNetworking#3539]
when i  use AFN3.0, then response error

In order to validate a domain name for self signed certificates, you MUST use pinning.
Error Domain=NSURLErrorDomain Code=-999 "cancelled"
UserInfo={NSErrorFailingURLKey=https://kyfw.12306.cn/otn/lcxxcx/query?purpose_codes=ADULT&queryDate=2016-05-25&from_station=BJP&to_station=SHH, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://kyfw.12306.cn/otn/lcxxcx/query?purpose_codes=ADULT&queryDate=2016-05-25&from_station=BJP&to_station=SHH} 

but i open this url on safari , it work

when i use AFN 2.0    no this question.

**Comment by computerion** [comment]
I think this should answer your question:
http://stackoverflow.com/questions/27808249/problems-with-ssl-pinning-and-afnetworking-2-5-0-nsurlerrordomain-error-1012

**Comment by WWLJ** [comment]
OK
I set a certificates, it work
