### ISSUE TITLE
How to achieve synchronous request

### ISSUE THREAD

**Issue by WWLJ** [AFNetworking/AFNetworking#3542]
When i use AFN3.0 
How to achieve synchronous request

same 

    NSMutableURLRequest *request = [requestSerializer requestWithMethod:@"GET" URLString:urlString parameters:requestParms error:nil];
    AFHTTPRequestOperation *requestOperation = [[AFHTTPRequestOperation alloc] initWithRequest:request];
    AFHTTPResponseSerializer *responseSerializer = [AFJSONResponseSerializer serializer];
    [requestOperation setResponseSerializer:responseSerializer];
    [requestOperation start];
    [requestOperation waitUntilFinished];

I no find a methods to achieve

**Comment by kcharwood** [comment]
AFN has no plans to support synchronous network requests.

🍻

**Comment by paulmelnikow** [comment]
I wrote a category for this:

https://github.com/paulmelnikow/AFNetworking-Synchronous
