### ISSUE TITLE
AFNetworking v3.1.0 multipartFormRequestWithMethod Uploads JSON Numeric Values With Quotes

### ISSUE THREAD

**Issue by crspybits** [AFNetworking/AFNetworking#3544]
I've written up an SO post describing what appears to be an AFNetworking bug: See https://stackoverflow.com/questions/37449472/afnetworking-v3-1-0-multipartformrequestwithmethod-uploads-json-numeric-values-w

**Comment by kcharwood** [comment]
@crspybits Would you be able to create a unit test demonstrating the issue so we can hone in on the problem?

**Comment by crspybits** [comment]
:) He who raises an issue gets to help with the issue? :)
I'd have to (a) figure out the structure of your unit tests, and (b) figure out how to simulate the receiving of such a `multipartFormRequestWithMethod` request by a server. Any pointers in the right direction? Thanks!

**Comment by kcharwood** [comment]
You should just be able to exercise the creation of the request and inspecting the body.

And yes! That helps focus on the problem if you can provide a specific failing test condition!

**Comment by Matt-hew** [comment]
@crspybits I believe you are misusing the `AFJSONRequestSerializer ` with a call to `multipartFormRequestWithMethod...`. The final result of that call will create a http request whose body is not JSON, but a `multipart/form-data`. Instead you should convert your params to JSON string yourself, and put that string as a value of your params dict, like `let params = ["somekey": jsonstring]`. In your server code, read the JSON string like `const jsonstring = request.body['jsonstring']`, and parse that to JSON.

**Comment by crspybits** [comment]
Good call! I just did some poking around with this and completely agree with this. If on my client, I send the dictionary: 

    ["Test" : 1, "Test2": 2]

on my server I get (after pulling the data out of the body stream):

--Boundary+162CCC2FB7259822
Content-Disposition: form-data; name="Test"

1
--Boundary+162CCC2FB7259822
Content-Disposition: form-data; name="Test2"

2
--Boundary+162CCC2FB7259822--

as you point out `multipart/form-data` is received , not JSON data. Interesting. It seems clear that what's going on is that some of the 3rd party Node.js packages I'm using are being smarter than I expected. It looks like body-parser is converting this form data into JSON. On the client side, `multipartFormRequestWithMethod` must be mapping the parameters into this form data structure. 

The AFNetworking documentation for `multipartFormRequestWithMethod` in terms of the parameters reads: "The parameters to be encoded and set in the request HTTP body". I'm not sure if I read this documentation originally, but I'm also not sure if I'd have interpreted that as creating the encoding I observe. I'll add in changes as you recommend.

In a bigger picture, when uploading a file with AFNetworking and wanting at the same time to ship JSON data up to the server, is there a better technique? Thanks!!

**Comment by Matt-hew** [comment]
In my project where I use AFNetworking, I also need to upload images along with some JSON data. I used the same method as I described above.
I'm not aware of other techniques due to limited knowledge. Keep our minds open though.

**Comment by crspybits** [comment]
Thanks, and thanks to you folks for helping me resolve this issue!!
