### ISSUE TITLE
Allowing Invalid SSL Certificates on WebView

### ISSUE THREAD

**Issue by MarkMolina** [AFNetworking/AFNetworking#3548]
Even after setting:

```
AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
manager.securityPolicy.allowInvalidCertificates = YES; // not recommended for production
```

UIWebviews `loadRequest:progress:success:failure:` still returns a 310 error when trying to access a url with an untrusted certificate (needed for our dev environment).

Printed out the sessionManager in this request to double check if `allowInvalidCertificates` was set to YES and unfortunately it is. Any reason why my request fails even after allowing invalid certificates?

**Comment by kcharwood** [comment]
Can you provide the whole 310 error?

**Comment by SlaunchaMan** [comment]
The UIWebView isn’t using AFNetworking to load. Are you still having this issue? You may need to implement UIWebViewDelegate methods to allow these requests. Feel free to re-open if this persists and is AFNetworking-related.
