### ISSUE TITLE
why  'AFURLConnectionOperation.h' file not found   ?

### ISSUE THREAD

**Issue by wff-** [AFNetworking/AFNetworking#3550]
![default](https://cloud.githubusercontent.com/assets/8870484/15696551/124d6e02-27e4-11e6-8366-31a5c98d91fd.png)

pod update 

AFNetworking (3.1.0)

**Comment by wff-** [comment]
solve the problem
once again pod update

**Comment by hanweixing** [comment]
it doesn't work for me. I search for the word "AFURLConnectionOperation", but there is no this word in the foundation of AFNetworking. pod update seveval times, but it do not effect.
