### ISSUE TITLE
how to get response body in failure block?

### ISSUE THREAD

**Issue by xuyouhong** [AFNetworking/AFNetworking#3551]
how to get response body in failure block?

**Comment by Mekor** [comment]
NSError *underError = error.userInfo[@"NSUnderlyingError"];
NSData *responseData = underError.userInfo[@"com.alamofire.serialization.response.error.data"];

**Comment by StanOz** [comment]
Add `NSData *data = error.userInfo[AFNetworkingOperationFailingURLResponseDataErrorKey];` into your failure block.

**Comment by bf4** [comment]
Should this go in the docs somewhere?

**Comment by kcharwood** [comment]
It is documented in `AFURLResponseSerialization`
