### ISSUE TITLE
Issue with AFNetworking and ReactiveCocoa

### ISSUE THREAD

**Issue by Lubakis** [AFNetworking/AFNetworking#3553]
Hello,

I'm using CocoaPods. I'm integrating ReactiveCocoa in an existing project. Before the integration of ReactiveCocoa I can Archive my project and export release builds. After I install the ReactiveCocoa Pod the project cannot be archived with the following error: **ld: library not found for -lAFNetworking**
I also get a warning, which says: **Duplicate definition of category 'AFNetworking' on interface 'UIImageView'**

My pod file has the following entries:

``` Ruby
platform :ios, '8.0'
use_frameworks!

target 'target_name' do
    pod 'AFNetworking', '~> 2.6'
    pod 'ReactiveCocoa'
    ...... (other pods)
end
```

**Comment by james-ff** [comment]
I'm also getting the warning (Using CocoaPods only)
