### ISSUE TITLE
Error: The Travis CI build could not complete...

### ISSUE THREAD

**Issue by hulizhen** [AFNetworking/AFNetworking#3556]
Hi.
I just added two lines in the file README.md,  and then pulled a  request[#3555]. Why i am given the following error from [Travis CI](https://travis-ci.org/AFNetworking/AFNetworking/builds/135184128):

```
Some checks were not successful:
The Travis CI build could not complete...
```

**Comment by kcharwood** [comment]
Thanks @hulizhen. We've been battling Travis for quite a while. Nothing to worry on your PR.

Thanks! 🍻
