### ISSUE TITLE
unacceptable content-type: text/plain

### ISSUE THREAD

**Issue by eveloson** [AFNetworking/AFNetworking#3557]
Find AFNetworking/Serialization/AFURLResponseSerialization.m 

change
 self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript",  nil];  
to 
self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/plain", nil];

Some servers just response content-type:text/plain,maybe the auther add "text/plain" as default MIME type ,thanks

**Comment by kcharwood** [comment]
`text/plain` is not JSON. If you have a server returning an incorrect content type, you can it to the set by using `setAcceptableContentTypes` on the serializer.
