### ISSUE TITLE
Shared NSURLSession instance, multiple responseSerializers ?

### ISSUE THREAD

**Issue by DDamian** [AFNetworking/AFNetworking#3558]
Hi,

In the app we have mutliple connections to our server, all of them return JSON format, but in most cases, I expected response to contain status=ok in json, while in others requests this doesn't have to happen. It must just be not emtpy json response.

So I created 2 subclasses of JSON response serializers, one that checks if response json is not empty and second that additionally checks if response json has status=ok value.

How do I use 2 separate response serializers with ONE AFHTTPSessionManager and more importantly with one instance of NSURLSession ?? Is this correct approach, to have 2 separate NSURLSessions just to be able to use 2 different response serializers ?? Is this somehow possible to define responseSerializer per task, not per session/sessionManager ??

Many thanks

**Comment by kcharwood** [comment]
Take a look at [AFCompoundSerializer](https://github.com/AFNetworking/AFNetworking/blob/32cf30a2451917c25d853fccb9e112b64415595e/AFNetworking/AFURLResponseSerialization.h#L257)

**Comment by DDamian** [comment]
Hi,
Thanks for you answer, I didn't mean to ask questions regarding current existing AFNetworking functionality, tough I still think what I need is not possible to do at the moment with AFNetworking.

AFCompoundSerializer doesn't seem to solve the problem for me. From what I understand, it will return success if ANY of responseSerializers validate the response correctly. (the one which return object from responseObjectForResponse:) In my case, one response will be non-empty json array - and this is valid response, but in other case, it must be non-empty json array + it must have status=ok. How do I know which responseSerializer should return object from responseObjectForResponse: based only on NSURLResponse and Data, if data in both cases will be a json string ??

**Comment by kcharwood** [comment]
You could create two custom subclass response serializers that do the specific type of validation you are looking for, and return false otherwise.

**Comment by DDamian** [comment]
Yes, I already have 2 subclasses. One validate non-empty json.  Second is subclass of first and validate in addition json with status=ok.

But how do I know if First one should return true or Second one ? This decision has to be made in responseObjectForResponse: I assume, and I'm not able to guess that based on parameters given in this method, right ? Or am I overlooking something ?
