### ISSUE TITLE
AFNetworking 2.5.0 - Error Domain=NSURLErrorDomain Code=-1012 "(null)"

### ISSUE THREAD

**Issue by joaocruz04** [AFNetworking/AFNetworking#3560]
Hi,

I know there are many threads regarding this issue, but I tried all the solutions and none fixed my problem.

I have a certificate, an intermediate certificate and a root certificate. I added all three as you can see in the code below. It allways gives the error:

Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLKey=https://myurl, NSErrorFailingURLStringKey=https://myurl}

The method:

```
- (AFSecurityPolicy*)customSecurityPolicy {
    AFSecurityPolicy* securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];

    NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"certificate_server" ofType:@"cer"];
    NSData *certData = [NSData dataWithContentsOfFile:cerPath];

    NSString *cerPath2 = [[NSBundle mainBundle] pathForResource:@"certificate_intermediate" ofType:@"cer"];
    NSData *certData2 = [NSData dataWithContentsOfFile:cerPath2];

    NSString *cerPath3 = [[NSBundle mainBundle] pathForResource:@"certificate_root" ofType:@"cer"];
    NSData *certData3 = [NSData dataWithContentsOfFile:cerPath3];

    [securityPolicy setAllowInvalidCertificates:NO];
    [securityPolicy setValidatesDomainName:YES];


    [securityPolicy setPinnedCertificates:@[certData, certData2, certData3]];
    return securityPolicy;
}

```

This only works if I set the allowInvalidCertificates to YES, but the certificates are NOT self-signed. Since I'm using version 2.5 I don't have access to the setValidatesCertificateChain method. My code heavily relies on this version, so I'm not going to update to 3.0 yet.

I tried  adding only the server certificate, tried the three of them, using AFSSLPinningModeCertificate or AFSSLPinningModePublicKey, and none works....

Can someone point me to a possible solution?

Best regards,
João

[edit: myurl is an alias to my url, it's just I don't want to post it here]

**Comment by kcharwood** [comment]
Several changes and bug fixes were applied to the pinning logic post version 2.5.

I'd recommend at least trying to get to 2.6.3.

**Comment by joaocruz04** [comment]
The problem persists. I use the same certificates in Android and it runs flawlessly. Debugging further, this method returns FALSE: 

AFServerTrustIsValid(serverTrust)

Since I'm putting all certificates from leaf to root, why does it return FALSE? If I left just the server certificate, why aren't the upper level certificates checked? The logs are not helping..

**Comment by joaocruz04** [comment]
I found that AFCertificateTrustChainForServerTrust > SecTrustGetCertificateCount returns 1.

Since I have an intermediate certificate and a root certificate, shouldn't this be 3?

**Comment by memovillalobos** [comment]
Hello @joaocruz04, I'm having this exact same problem; the app on the production environment was working fine up until yesterday when this started happening. Did you get this sorted out?

**Comment by joaocruz04** [comment]
@memovillalobos So I found out I didn't need to add the certificates the way I was adding. By just adding the cert files to the project, the AFNetworking library did the rest. My custom policy became:

```
- (AFSecurityPolicy*)customSecurityPolicy {
    AFSecurityPolicy* securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModePublicKey];
    [securityPolicy setAllowInvalidCertificates:YES];
    [securityPolicy setValidatesDomainName:NO];
    return securityPolicy;
}
```

**Comment by Asif332** [comment]
I am facing the same issue 

Error: Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLStringKey=https://github.com, NSErrorFailingURLKey=https://github.com}

Can anyone help, How to integrate SSL pinning in networking?

**Comment by Asif332** [comment]
I tested this on a sample code cloned from GitHub.

https://github.com/antekarin/ios-ssl-pinning
