### ISSUE TITLE
Get response data when fail in downloadTaskWithRequest of AFURLSessionManager

### ISSUE THREAD

**Issue by hxdev** [AFNetworking/AFNetworking#3563]
Hi,

At first, thanks for amazing fw. 

I'm creating a download class which allow to download some file (music) from my server. For some time, the server return error (error code 500 or something) and the description of error will be in the data of the response.

The completionHandler only return NSURLResponse so it's just contain the header of response. How to get the body content in this case?

Thanks alot!

**Comment by iDevelopper** [comment]
```
    // Initialize Session Manager
    self.sessionManager = [[AFURLSessionManager alloc] initWithSessionConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];

...

    NSString *url = @"yourURL";
    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:url]];
    __block NSString *fileName = @"yourFileName";
    // Initialize Download Task
    NSURLSessionDownloadTask *downloadTask = [_sessionManager downloadTaskWithRequest:request progress:nil destination:^NSURL *(NSURL *targetPath, NSURLResponse *response) {
        // Handle Success
        return [NSURL fileURLWithPath:fileName];
    } completionHandler:^(NSURLResponse *response, NSURL *filePath, NSError *error) {
        // Handle Failure
        NSLog(@"Error : %@", error.localizedDescription);
    }];
    
    [downloadTask resume];
```

Error is describe in the error parameter of completionHandler.

**Comment by hxdev** [comment]
@iDevelopper Thank for the explain, I know that I can get the error in the completionHandler but like I said, the server return other error description inside the response data when they detect something wrong with token or something.

For example, they return status code 500 and in the body content they return the: "result":"0","reason":"You reach the limit devices..."

**Comment by iDevelopper** [comment]
NSInteger statusCode = [((NSHTTPURLResponse *)response) statusCode];
        NSLog(@"Response: %@", [NSHTTPURLResponse localizedStringForStatusCode:statusCode]);

**Comment by hxdev** [comment]
@iDevelopper 

localizedStringForStatusCode:statusCode same with error.localizedDescription

I think we cannot get the response data from the NSHTTPURLResponse, it's just contain the header of the response.

**Comment by iDevelopper** [comment]
You can but your server have to return a page with the error description.

        NSString *body = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
        NSLog(@"Body: %@",body);

**Comment by hxdev** [comment]
I didn't got what you mean, where is the data come from?

**Comment by iDevelopper** [comment]
Ah yes, I 'm looking the NSURLSessionDataTask method from Apple!

**Comment by iDevelopper** [comment]
#2410 could be useful also!

**Comment by hxdev** [comment]
After debug carefully, I see that we can get the response data when fail only on OS >= 9.0. Does is it a bug of AFURLSessionManager?

Anyway, I blog it here https://hantran.info/ios-different-action-of-afurlsessionmanager-for-different-os-version/
