### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by luckwxx** [AFNetworking/AFNetworking#3568]
crash at [self af_resume];    self=nil

AFURLSessionManager.m
- (void)af_resume {
  NSAssert([self respondsToSelector:@selector(state)], @"Does not respond to state");
  NSURLSessionTaskState state = [self state];
  [self af_resume];
  
  if (state != NSURLSessionTaskStateRunning) {
      [[NSNotificationCenter defaultCenter] postNotificationName:AFNSURLSessionTaskDidResumeNotification object:self];
  }
  }

**Comment by josluimg** [comment]
Me too sometimes

**Comment by evelyne96** [comment]
Why was this issue closed?
