### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-1001 

### ISSUE THREAD

**Issue by codesourse** [AFNetworking/AFNetworking#3569]
Error Domain=NSURLErrorDomain Code=-1001 "请求超时。" UserInfo={NSUnderlyingError=0x13850aca0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "请求超时。" UserInfo={NSErrorFailingURLStringKey=http://xhyz.yunzuoye.net/interfaces_exam/manage_client_exam_interfaces.php, NSErrorFailingURLKey=http://xhyz.yunzuoye.net/interfaces_exam/manage_client_exam_interfaces.php, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=请求超时。}}, NSErrorFailingURLStringKey=http://xhyz.yunzuoye.net/interfaces_exam/manage_client_exam_interfaces.php, NSErrorFailingURLKey=http://xhyz.yunzuoye.net/interfaces_exam/manage_client_exam_interfaces.php, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=请求超时。}

**Comment by veryitman** [comment]
I hit this case too.
But I can't why and how do resolve it?

**Comment by codesourse** [comment]
I think it is a bug

**Comment by adman44** [comment]
I get this error too. But I found cause. In my case if I make requests by NSTimer, periodicity 1m for example, and when app goes in background mode, all requests after some time returns:

The request timed out.
The network connection was lost.
A server with the specified hostname could not be found.
An SSL error has occurred and a secure connection to the server cannot be made.

How can I resolve this issue?

**Comment by ChenJian345** [comment]
Same issue I met. Any solution?

**Comment by adman44** [comment]
Maybe can be helpful 
https://github.com/AFNetworking/AFNetworking/issues/3663

**Comment by xx-li** [comment]
Same issue I met. Any solution?
