### ISSUE TITLE
Clear cached response or cached images not working, still showing old image.

### ISSUE THREAD

**Issue by roman-yu** [AFNetworking/AFNetworking#3571]
In my case, I need set the ImageView with the same url but different image data. I tried to clear all the cache with following code:

```
NSURLCache.sharedURLCache().removeAllCachedResponses()        
AFImageDownloader.defaultURLCache().removeAllCachedResponses()
AFImageDownloader.defaultInstance().imageCache?.removeAllImages()
```

After calling these lines, `memoryUsage` of `imageCache` and `NSURLCache.sharedURLCache().currentMemoryUsage` print 0 in the console. Then I updated the image on s3 with the same url and reload TableView after that. The old image returned from `setImageWithURLRequest`. The code below is what I use to display the image.

```
let imageUrl = "https://s3.ap-northeast-2.amazonaws.com/xxx/yyy.jpg"
let request = NSURLRequest(URL: NSURL(string: imageUrl)!, cachePolicy: NSURLRequestCachePolicy.ReturnCacheDataElseLoad, timeoutInterval: 10)
cell.cellImageView.setImageWithURLRequest(request, placeholderImage: UIImage(named: "placeholder"), success: { (request, response, image) in
    cell.cellImageView.image = image
}) { (request, response, error) in
    // error handling
}
```

Besides, if I changed the `cachePolicy` to `NSURLRequestCachePolicy.ReloadIgnoringLocalCacheData`, I can get the updated image after clearing image caches.

**Comment by rahulvyas** [comment]
I am having the same issue

**Comment by Dmxy** [comment]
I used these func in Objective-c:
 [[NSURLCache sharedURLCache] removeAllCachedResponses];
 [[AFImageDownloader defaultURLCache] removeAllCachedResponses];
 [[[AFImageDownloader defaultInstance] imageCache] removeAllImages];
 AFAutoPurgingImageCache *imageCache = [[AFAutoPurgingImageCache alloc] init];
 [imageCache removeAllImages];
I hope you will find these helpful.

**Comment by roman-yu** [comment]
@Dmxy 
Thanks for your help, I have tried these methods with swift but seems not work. The UIImageView still uses the cached image not fetching it again from Internet.

**Comment by rahulvyas** [comment]
I had the same issue. What we do to fix these is change the name of image everytime when updated on server b adding timestamp in name of the image. This way the app downloads the new image.

**Comment by Maxim-Inv** [comment]
This code works for me:

`            [[NSURLCache sharedURLCache] removeAllCachedResponses];
			
			AFImageDownloader *imageDownloader = [AFImageDownloader defaultInstance];
			NSURLCache *urlCache = imageDownloader.sessionManager.session.configuration.URLCache;
			[urlCache removeAllCachedResponses];
			
            [imageDownloader.imageCache removeAllImages];
`

**Comment by lfournierbsf** [comment]
Thanks, @Maxim-Inv! This is the same code in Swift and last version of Alamofire (4.5):

`URLCache.shared.removeAllCachedResponses()
        
        let imageDownloader = ImageDownloader.default
        let urlCache = imageDownloader.sessionManager.session.configuration.urlCache
        urlCache?.removeAllCachedResponses()
        
        imageDownloader.imageCache?.removeAllImages()`
