### ISSUE TITLE
AFN 3.1 error and crash A background URLSession with identifier "com.abc.test.demo1" already exists!

### ISSUE THREAD

**Issue by viral105** [AFNetworking/AFNetworking#3573]
```
-(void)viewDidLoad{
 self.currentcnt = 0;
 [self InitiateDownload];

}

-(void)InitiateDownload{
if(self.currentcnt<self.arrAll.count){
NSDictionary *parameters = [self.arrAll objectAtIndex:self.currentcnt];
NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:@"com.abc.test.demo1"];

AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];

NSMutableRequest *request;
// My request code

NSURLSessionDownloadTask *downloadTask = [manager downloadTaskWithRequest:request  progress:nil destination:^NSURL *(NSURL *targetPath, NSURLResponse *response) {
    NSURL *documentsDirectoryPath = [NSURL fileURLWithPath:[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0]];

    return [documentsDirectoryPath URLByAppendingPathComponent:[parameters objectForKey:@"Pic"]];
} completionHandler:^(NSURLResponse *response, NSURL *filePath, NSError *error) {
    if(error) {
        NSLog(@"error %@",error)
    }
    else {

    NSLog(@"Success");
    self.currentcnt++;
    [self InitiateDownload];
   }
}];
}
}
```

for self.currentcnt=0 code executes good and log Success but for self.currentcnt =1 it gives following error and getting crash
A background URLSession with identifier "com.abc.test.demo1" already exists!

if i write 
NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration]

instead of following
NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:@"com.abc.test.demo1"];

then code works. but i want to work it with backgroundSessionConfigurationWithIdentifier
any idea ?

**Comment by skyline75489** [comment]
I think Apple makes it pretty clear here, that you can not have more than one background URLSession with the same identifier. Here you shouldn't try to create `NSURLSessionConfiguration` or `AFURLSessionManager` for every request. That's not how NSURLSession is designed to be working. Instead you should just use a shared manager with the same background configuration.

By the way, this isn't really an AFN problem in my opinion. If you try this on NSURLSession I bet you'll get the same result. Please take very close look at the error that Apple gives you. Sometimes it's more valuable than you think.
