### ISSUE TITLE
Upload array error

### ISSUE THREAD

**Issue by xuguangming** [AFNetworking/AFNetworking#3577]
使用AFNNetworking 3.0版本

`"field_ezc_file" =     {
        und =         (
                        {
                display = 1;
                fid = 2458;
            }
        );
    }`

在调用

`AFQueryStringFromParameters()`

返回的数据结构为 field_ezc_file[und][][display]=1& field_ezc_file[und][][fid]= 2458，截获请求包发现数组中元素被覆盖了，实际发出的只有一个field_ezc_file[und][][fid]= 2458，与其它系统数据对比，发现
`NSArray * AFQueryStringPairsFromKeyAndValue(NSString *key, id value);`
这个方法中导致的，因为没有序列话数组导致，修改如下：

原始：

`
 for (id nestedValue in array) 
{
            [mutableQueryStringComponents addObjectsFromArray:AFQueryStringPairsFromKeyAndValue([NSString stringWithFormat:@"%@[]", key], nestedValue)];
}
`
修改：

`  
[array enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL \* _Nonnull stop) {

```
        [mutableQueryStringComponents addObjectsFromArray:AFQueryStringPairsFromKeyAndValue([NSString stringWithFormat:@"%@[%d]", key, (int)idx], obj)];
```

}];`

解决了数组上传的问题

**Comment by styleJie** [comment]
现在还是原始这样  手动修改。。。还是有别的解决办法
