### ISSUE TITLE
 There is not exist 'operation class' in 3.0 like AFHTTPRequestOperation, how can I cancel a http request now?

### ISSUE THREAD

**Issue by jiangzhibin** [AFNetworking/AFNetworking#3578]
thank you!

**Comment by Meonardo** [comment]
Assume you create an AFHTTPSessionManager object named manager, call  like this " [manager.operationQueue cancelAllOperations] ".

**Comment by jiangzhibin** [comment]
@Meonardo I got it,thank you!

**Comment by yanchaoGan** [comment]
@Meonardo no it 's just not call back.  if you want cancel . maybe  u need 

   for (NSURLSessionTask * task in self.sessionManager.tasks) {
        [task cancel];
    }

**Comment by zhenyiyi** [comment]
@yanchaoGan you are right.
