### ISSUE TITLE
AFN 3 manage HTTP 304

### ISSUE THREAD

**Issue by ghost** [AFNetworking/AFNetworking#3579]
I can't find a way to manage http 304.
AFN return always http 200.
Someone can help me ?
Thanks in advance

**Comment by maksimusenko** [comment]
The same thing here.
Could you provide any solution? 
@ghost, did you manage that?

**Comment by songxing10000** [comment]
it works,
 [manager.requestSerializer setCachePolicy:NSURLRequestReloadIgnoringLocalCacheData];
