### ISSUE TITLE
How can I POST raw data without using a key value pair

### ISSUE THREAD

**Issue by winterWD** [AFNetworking/AFNetworking#3583]

**Comment by JeansHuang** [comment]
`request = [[AFHTTPRequestSerializer serializer]
                   requestWithMethod:aMethod
                   URLString:aUrlString
                   parameters:nil
                   error:nil];
        NSError *parseError = nil;
        NSData *jsonData = [NSJSONSerialization dataWithJSONObject:aParams
                                                           options:NSJSONWritingPrettyPrinted
                                                             error:&parseError];
        NSLog(@"body:%@", [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding]);
        [request setHTTPBody:jsonData];`

**Comment by JeansHuang** [comment]
```
request = [[AFHTTPRequestSerializer serializer]
                   requestWithMethod:aMethod
                   URLString:aUrlString
                   parameters:nil
                   error:nil];
        NSError *parseError = nil;
        NSData *jsonData = [NSJSONSerialization dataWithJSONObject:aParams
                                                           options:NSJSONWritingPrettyPrinted
                                                             error:&parseError];
        NSLog(@"body:%@", [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding]);
        [request setHTTPBody:jsonData];
```

**Comment by winterWD** [comment]
@JeansHuang 只有这种方式？AF内部不支持这种参数传递？我是做了一个AFHTTPRequestSerializer的分类扩展来实现的
