### ISSUE TITLE
_OBJC_CLASS_$_AFHTTPResponseSerializer", referenced from:

### ISSUE THREAD

**Issue by weiweiwoep** [AFNetworking/AFNetworking#3586]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AFHTTPResponseSerializer", referenced from:
      objc-class-ref in AFNetworkingUtil.o
      objc-class-ref in MDETaskManager.o
  "_OBJC_CLASS_$_AFHTTPSessionManager", referenced from:
      objc-class-ref in AFNetworkingUtil.o
      objc-class-ref in MDETaskManager.o
      objc-class-ref in NDSCDWorkManager.o
      objc-class-ref in NDSCDPersonalManager.o
  "_OBJC_CLASS_$_AFJSONResponseSerializer", referenced from:
      objc-class-ref in MDETaskManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shivam-ucreate** [comment]
Same issue after updating the cocoa pods. :(

**Comment by SlaunchaMan** [comment]
Are you still having this issue?

**Comment by ehlersd** [comment]
@SlaunchaMan I'm having this issue, but just with the Serializers.  I have tried everything I can think of.  

I'm using the latest CocoaPods production executable, along with v3.1.0 of AFNetworking.

I've tried everything short of not using CocoaPods.

Any ideas?

![screenshot 2017-12-15 12 52 33](https://user-images.githubusercontent.com/2302997/34055924-dabe0a8c-e196-11e7-9fe0-e3ecdcf3e17f.png)

**Comment by ehlersd** [comment]
I don't think it's related at all, but I did have to modified the AFURLSessionManager.h file to fix a compiler error:

```
/**
 The dispatch queue for `completionBlock`. If `NULL` (default), the main queue is used.
 */
#if OS_OBJECT_HAVE_OBJC_SUPPORT
@property (nonatomic, strong, nullable) dispatch_queue_t completionQueue;
#else
@property (nonatomic, assign, nullable) dispatch_queue_t completionQueue;
#endif

/**
 The dispatch group for `completionBlock`. If `NULL` (default), a private dispatch group is used.
 */
#if OS_OBJECT_HAVE_OBJC_SUPPORT
@property (nonatomic, strong, nullable) dispatch_group_t completionGroup;
#else
@property (nonatomic, assign, nullable) dispatch_group_t completionGroup;
#endif

```
