### ISSUE TITLE
How about add an API for breakpoint download?

### ISSUE THREAD

**Issue by kuah** [AFNetworking/AFNetworking#3587]
My project required  breakpoint download,and I view the code deeply , I found that there is no way to archive breakpoint download In the case of forced exit my app when the download task is running .

So,I temporarily modify the code as follow：
1. in AFURLSessionManager
   `/**
   -   modify by 陈世翰
     */
     @property (nonatomic,copy)AFURLSessionDataTaskDidReceiveDataBlock downloadDidReceiveDataBlock;`
     I add a block for receiveData

2.
`#pragma clang diagnostic pop
}
# pragma mark - NSURLSessionDataTaskDelegate
- (void)URLSession:(__unused NSURLSession *)session
        dataTask:(__unused NSURLSessionDataTask *)dataTask
  didReceiveData:(NSData *)data
  {
  [self.mutableData appendData:data];
  if (self.downloadDidReceiveDataBlock) {
      self.downloadDidReceiveDataBlock(session,dataTask,data);
  }
  }`
  Call the block at Line _331

3.handle the data in the block 
`        long long totalContentLength=0;
        //handle for status code
        NSHTTPURLResponse _response = (NSHTTPURLResponse_)dataTask.response;
        if (response.statusCode ==200) {

```
       totalContentLength = dataTask.countOfBytesExpectedToReceive;

    }else if (response.statusCode ==206){
        NSString *contentRange = [response.allHeaderFields valueForKey:@"Content-Range"];
        if ([contentRange hasPrefix:@"bytes"]) {
            NSArray *bytes = [contentRange componentsSeparatedByCharactersInSet:[NSCharacterSet characterSetWithCharactersInString:@" -/"]];
            if ([bytes count] == 4) {
                totalContentLength = [[bytes objectAtIndex:3]longLongValue];
            }
        }
    }else if (response.statusCode ==416){//Requested Range Not Satisfiable 

        NSString *contentRange = [response.allHeaderFields valueForKey:@"Content-Range"];
        if ([contentRange hasPrefix:@"bytes"]) {
            NSArray *bytes = [contentRange componentsSeparatedByCharactersInSet:[NSCharacterSet characterSetWithCharactersInString:@" -/"]];
            if ([bytes count] == 3) {

                totalContentLength = [[bytes objectAtIndex:2]longLongValue];
                if (downloadedBytes==totalContentLength) {

                    //finish
                   //progress
                    if (progress) {
                        progress(1);
                    }
                }else{

                    if (failureBlock) {
                        failureBlock(@"416:wrong");
                    }

                }
            }
        }else{
            if (successBlock) {
                successBlock(nil);
            }
        }
        return;
    }
    if (response.statusCode == 404) {
        if (failureBlock) {
            failureBlock(@"404:url no exit");
        }
    }

    NSFileHandle *fileHandle = [NSFileHandle fileHandleForUpdatingAtPath:savePath];
    [fileHandle seekToEndOfFile]; 

    [fileHandle writeData:data];
    [fileHandle closeFile];`
```

**Comment by ben1226q** [comment]
good
