### ISSUE TITLE
Array parameters' payload is changed when upgrade from 2.6.3 to 3.1.0

### ISSUE THREAD

**Issue by imadeit** [AFNetworking/AFNetworking#3588]
Hi,

I recently encountered a problem that payload was changed by just upgrading from 2.6.3 to 3.1.0.
Parameter in swift is
{
"data": [
  [Double, Double],
  [Double, Double]
]
}
||
||
v
Through AFNetworking 3.1.0
||
||
v
But what received by server becomes
{
"data": [
  [Double],
  [Double],
  [Double],
  [Double]
]
}

I did not change the logic by upgrading the library, so I wonder why such kind of phenomenon would happen.

Hope some can help!

Thanks!

Leon

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
