### ISSUE TITLE
iOS7 NSURLSessionTask currentRequest HTTP header fields different from originalRequest

### ISSUE THREAD

**Issue by wuweili** [AFNetworking/AFNetworking#3591]
hi,

Now I'm use AFNetworking 3.0 in iPhone app ,i have a problem when use follow method
- (NSURLSessionUploadTask *)uploadTaskWithStreamedRequest:(NSURLRequest *)request
                                               progress:(void (^)(NSProgress *uploadProgress)) uploadProgressBlock
                                      completionHandler:(void (^)(NSURLResponse *response, id responseObject, NSError *error))completionHandler
  {
  __block NSURLSessionUploadTask *uploadTask = nil;
  url_session_manager_create_task_safely(^{
      uploadTask = [self.session uploadTaskWithStreamedRequest:request];
  });
  
  [self addDelegateForUploadTask:uploadTask progress:uploadProgressBlock completionHandler:completionHandler];
  
  /**test**/
  
  NSURL *taskRequestUrl = [uploadTask.currentRequest URL];
  
  NSDictionary *originalRequestHeaderFields = [uploadTask.originalRequest allHTTPHeaderFields];
  
  NSDictionary *currentRequestHeaderFields = [uploadTask.currentRequest allHTTPHeaderFields];
  
  /****/
  
  return uploadTask;
  }

in iOS 8  or iOS  9,NSURLSessionTask   originalRequest and  currentRequest  HTTP header fields stay the same:
Printing description of originalRequestHeaderFields:
{
    "Accept-Language" = "zh-Hans;q=1, en;q=0.9";
    "Content-Length" = 470;
    "Content-Type" = "multipart/form-data; boundary=Boundary+6E6AB917D9252E24";
    "User-Agent" = “xxx/3.0.0 (iPhone; iOS 8.3; Scale/2.00)";
}

Printing description of currentRequestHeaderFields:
{
    "Accept-Language" = "zh-Hans;q=1, en;q=0.9";
    "Content-Length" = 470;
    "Content-Type" = "multipart/form-data; boundary=Boundary+6E6AB917D9252E24";
    "User-Agent" = “xxx/3.0.0 (iPhone; iOS 8.3; Scale/2.00)";
}

but in iOS 7 

NSURLSessionTask currentRequest HTTP header fields different from originalRequest 
(lack "Content-Length"):

Printing description of originalRequestHeaderFields:
{
    "Accept-Language" = "zh-Hans;q=1, it;q=0.9, en;q=0.8, fr;q=0.7, de;q=0.6, ja;q=0.5";
    "Content-Length" = 470;
    "Content-Type" = "multipart/form-data; boundary=Boundary+2DB9A77E719A67ED";
    "User-Agent" = “xxx/3.0.0 (iPhone; iOS 7.1.2; Scale/2.00)";
}

Printing description of currentRequestHeaderFields:

{

```
"Accept-Language" = "zh-Hans;q=1, it;q=0.9, en;q=0.8, fr;q=0.7, de;q=0.6, ja;q=0.5";

"Content-Type" = "multipart/form-data; boundary=Boundary+2DB9A77E719A67ED";

"User-Agent" = “xxx/3.0.0 (iPhone; iOS 7.1.2; Scale/2.00)";
```

}

why currentRequestHeaderFields   "Content-Length" lost? please help me,thanks!

**Comment by ahmetkgunay** [comment]
I have the same issue !
