### ISSUE TITLE
CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork_Sim/CFNetwork-758.3.15/Loading/URLConnectionLoader.cpp:289)

### ISSUE THREAD

**Issue by PiscesZjc** [AFNetworking/AFNetworking#3595]
CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork_Sim/CFNetwork-758.3.15/Loading/URLConnectionLoader.cpp:289)

i occur this error  but it not aways  sometimes it's ok sometimes it's wrong

**Comment by PiscesZjc** [comment]
i'm AF 3.0

**Comment by KBvsMJ** [comment]
I also encountered the same problem

**Comment by Chiliec** [comment]
I have the same.

**Comment by AidenWK** [comment]
I have the same. nothing can be found

**Comment by littleSun** [comment]
I have the same. someone help?

**Comment by AidenWK** [comment]
I solved my situation, it is not AFNetwork's issue, I use a invalid SSL certification and SDWebImage,  when use the option 'SDWebImageAllowInvalidSSLCertificates' in SDWebImage and get a http image (not https image), you will get this error. the protocol (http or https) not being recognized automaticly by SDWebImage

**Comment by kpavankotesh** [comment]
Is there a solution to fix this to use https image urls?

**Comment by KBvsMJ** [comment]
@AidenWK  
Your solution is this?https://github.com/rs/SDWebImage/pull/582/files/fbe3b95e8cdec7d3ee27a30035315c80a2c08109..706c57308e6d3af422dd375cc35bd058be7dbc34

**Comment by AidenWK** [comment]
@KBvsMJ 
I not change SDWebImage‘s code, I just write a wrapper for recognized protocol (http or https). 
I use '0' option for http images and 'SDWebImageAllowInvalidSSLCertificates' option for https images (my https certification is self signed or invalid).  If yours cer is valid , I think  SDWebImage work well.

**Comment by KBvsMJ** [comment]
@AidenWK 
As you say so！
 I find this error log in a test environment, but not in a formal environment error log.

**Comment by patelmayank** [comment]
any solution ?

**Comment by MineJ** [comment]
I think it's not SDWebImage, because I visited the local server address

**Comment by aleczadikian** [comment]
Where is `URLConnectionLoader.cpp` exactly? Haven't found it on my machine.

**Comment by SlaunchaMan** [comment]
`URLConnectionLoader.cpp` looks to be Apple’s source code. I don’t see anything here that points to an AFNetworking problem, but if you can find something concrete, feel free to open a new issue.
