### ISSUE TITLE
How to use AFNetworking  without URLEncode ?

### ISSUE THREAD

**Issue by CokeBear** [AFNetworking/AFNetworking#3601]
How to use AFNetworking  without URLEncode ?
Please help me .    

eyJhZGRyIjoiMjEyNmQ4MWEtMWYwOC00YTY4LWJmNGQtNTZhOTkzYTdiNWIwIiwiY29kZSI6IjQ5OTcwNSIsImlkIjo2MzMsIm1ldGhvZCI6MTMsInZjb2RlIjoiYTlhODI4ZDRjMDg2ODBkZjZkZWZhMjc1ZmIyMjg5NTUifQ%3D%3D

This is what I want:

eyJhZGRyIjoiMjEyNmQ4MWEtMWYwOC00YTY4LWJmNGQtNTZhOTkzYTdiNWIwIiwiY29kZSI6IjQ5OTcwNSIsImlkIjo2MzMsIm1ldGhvZCI6MTMsInZjb2RlIjoiYTlhODI4ZDRjMDg2ODBkZjZkZWZhMjc1ZmIyMjg5NTUifQ==

**Comment by skyline75489** [comment]
What is your issue here exactly? If you trying to use this as URL, it has to be encoded.
