### ISSUE TITLE
A terrible bug： when i use NSURLSessionDataTask call resume drop in endless loop

### ISSUE THREAD

**Issue by juvham** [AFNetworking/AFNetworking#3605]
```
NSURLSessionDataTask *task = [[NSURLSession sharedSession] dataTaskWithRequest:requet completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
}];
    [task resume];
```

not always occurr

call stack show message like that

0-[NSURLSessionTask(_AFStateObserving) af_resume]
1-[NSURLSessionTask(_AFStateObserving) af_resume]
2-[NSURLSessionTask(_AFStateObserving) af_resume]
3-[NSURLSessionTask(_AFStateObserving) af_resume]
4--[NSURLSessionTask(_AFStateObserving) af_resume]
....
30000--[NSURLSessionTask(_AFStateObserving) af_resume]

look forward you reply ，

**Comment by kcharwood** [comment]
What version of AFNetworking are you using, and do any of your dependencies include a hard coded copy of AFNetworking within them?
