### ISSUE TITLE
Https request with .cer. [__NSArrayM insertObject:atIndex:]: object cannot be nil

### ISSUE THREAD

**Issue by misuqian** [AFNetworking/AFNetworking#3608]
```
        request.HTTPMethod = "POST"
        request.HTTPBody = bodyData
        request.timeoutInterval = 10.0
        request.cachePolicy = NSURLRequestCachePolicy.ReturnCacheDataElseLoad

        let securityPolicy = AFSecurityPolicy(pinningMode: .Certificate)
        let localCertData = NSData(contentsOfFile: NSBundle.mainBundle().pathForResource("hehe", ofType: "cer")!)
        securityPolicy.pinnedCertificates = [localCertData!]
//        print("localdata \(localCertData)")
        securityPolicy.allowInvalidCertificates = true
        securityPolicy.validatesDomainName = false
        session.securityPolicy = securityPolicy
```

localCertData is not nil but i got something was nil.why?

**Comment by wanyancan** [comment]
same problem with - AFNetworking, 3.1.0

**Comment by hdoria** [comment]
Same here.

**Comment by reni99** [comment]
same here

**Comment by fedesenmartin** [comment]
same here

**Comment by SlaunchaMan** [comment]
Are you still experiencing this? If so, feel free to re-open with crash logs that show where you’re getting this crash.

**Comment by Sivagami-Sundari** [comment]
Hi, I'm facing this crash issue, "[__NSArrayM insertObject:atIndex:]: object cannot be nil", Is this issue fixed?

        NSString *certificatePath = [[NSBundle mainBundle] pathForResource:@"sslFileName" ofType:@"crt"];
        NSSet *set = [NSSet setWithObjects:[NSData dataWithContentsOfFile:certificatePath], nil];
        AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
        [securityPolicy setValidatesDomainName:NO];
        [securityPolicy setAllowInvalidCertificates:NO];
        [securityPolicy setPinnedCertificates:set];
        manager.securityPolicy = securityPolicy;
