### ISSUE TITLE
Append decimal in my Jason return

### ISSUE THREAD

**Issue by Canmmy** [AFNetworking/AFNetworking#3611]
Hi,

I had problem in getting correct Jason return. 
I'm using AFNetworking version 3.1 in CocoaPods.
My response should be

{
      "RewardTopUp": 150,
      "RewardTopupGiven": 9.015
    }

But 

I received from AFNetwork responseObject is 

{
      "RewardTopUpValue": 150,
      "RewardTopupValueGiven": 9.015000000000001
    }

Can someone help?

**Comment by skyline75489** [comment]
I don't think this is an AFN issue. Float numbers are born with precision problem. In this case, `9.015000000000001` is a perfectly reasonable representation of float value `9.015` in the computer world.
