### ISSUE TITLE
Do we need to Handle error like 422

### ISSUE THREAD

**Issue by TIEmerald** [AFNetworking/AFNetworking#3613]
Hi,

My AFNetworking version is 2.5.0. 

Recently, I am trying to negotiate with a payment API (https://test-api.pin.net.au/1/cards) via AFHTTPRequestOperationManager and find out that if I pass any invalid parameter to this API it will return a response with Headers (Status →422 Unprocessable Entity) (You can also check it in their [document](https://pin.net.au/docs/api/cards))

And I find out that AFHTTPRequestOperationManager will treat Status 422 as an error. And it is very hard for me to retrieve the response data.

Actually, in the error handler, I can get the data passed by server under userInfo (key is "**com.alamofire.serialization.response.error.data**" ) I think I can convert it into an Error Response JSModel. But still, it is very annoying.

`Printing description of _userInfo:
{
    NSErrorFailingURLKey = "https://test-api.pin.net.au/1/cards";
    NSLocalizedDescription = "Request failed: client error (422)";
    "com.alamofire.serialization.response.error.data" = <7b226572 726f7222 3a22696e 76616c69 645f7265 736f7572 6365222c 22657272 6f725f64 65736372 69707469 6f6e223a 224f6e65 206f7220 6d6f7265 20706172 616d6574 65727320 77657265 206d6973 73696e67 206f7220 696e7661 6c696422 2c226d65 73736167 6573223a 5b7b2270 6172616d 223a226e 756d6265 72222c22 636f6465 223a226e 756d6265 725f696e 76616c69 64222c22 6d657373 61676522 3a224e75 6d626572 2063616e 27742062 6520626c 616e6b22 7d2c7b22 70617261 6d223a22 65787069 72795f6d 6f6e7468 222c2263 6f646522 3a226578 70697279 5f6d6f6e 74685f69 6e76616c 6964222c 226d6573 73616765 223a2245 78706972 79206d6f 6e746820 63616e27 74206265 20626c61 6e6b227d 2c7b2270 6172616d 223a2265 78706972 795f7965 6172222c 22636f64 65223a22 65787069 72795f79 6561725f 696e7661 6c696422 2c226d65 73736167 65223a22 45787069 72792079 65617220 63616e27 74206265 20626c61 6e6b227d 2c7b2270 6172616d 223a226e 616d6522 2c22636f 6465223a 226e616d 655f696e 76616c69 64222c22 6d657373 61676522 3a224e61 6d652063 616e2774 20626520 626c616e 6b227d2c 7b227061 72616d22 3a226164 64726573 735f6c69 6e653122 2c22636f 6465223a 22616464 72657373 5f6c696e 65315f69 6e76616c 6964222c 226d6573 73616765 223a2241 64647265 7373206c 696e6531 2063616e 27742062 6520626c 616e6b22 7d2c7b22 70617261 6d223a22 63766322 2c22636f 6465223a 22637663 5f696e76 616c6964 222c226d 65737361 6765223a 22437663 2063616e 27742062 6520626c 616e6b22 7d5d7d>;
    "com.alamofire.serialization.response.error.response" = "<NSHTTPURLResponse: 0x7f9945f72c30> { URL: https://test-api.pin.net.au/1/cards } { status code: 422, headers {\n    \"Cache-Control\" = \"no-cache\";\n    Connection = \"keep-alive\";\n    \"Content-Length\" = 611;\n    \"Content-Type\" = \"application/json; charset=utf-8\";\n    Date = \"Tue, 19 Jul 2016 01:21:39 GMT\";\n    Server = Apache;\n    Status = \"422 Unprocessable Entity\";\n    \"Strict-Transport-Security\" = \"max-age=31536000\";\n    Vary = \"User-Agent\";\n    \"X-Rack-Cache\" = \"invalidate, pass\";\n    \"X-Request-Id\" = 48e7f638c560c4108ec9c13f06636883;\n    \"X-Runtime\" = \"0.036463\";\n    \"X-UA-Compatible\" = \"IE=Edge,chrome=1\";\n} }";`

I have searched the definition of "422" in Google and get this:

**The 422** (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415(Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions. For example, this error condition may occur if an XML request body contains well-formed (i.e., syntactically correct), but semantically erroneous, XML instructions. (from [REST Patterns](http://www.restpatterns.org/HTTP_Status_Codes/422_-_Unprocessable_Entity))

Find out it does make sense to set status to 422 in server-end.

Therefore, I am wondering, do you think it make sense to add a new error handler to handle error like "422"? (the error that server told us it is not successful, but also return a response to us)

Regards.

**Comment by skyline75489** [comment]
You can just use your own response serializer with custom `acceptableStatusCodes` which accepts 422.
