### ISSUE TITLE
I found that you fail to get the HTTP request, the server can not get the data, can only get the server "code" status code, you can not optimize the framework of this piece, I this project is in urgent need of this, thank you!

### ISSUE THREAD

**Issue by HB520XQ** [AFNetworking/AFNetworking#3618]
I found that you fail to get the HTTP request, the server can not get the data, can only get the server "code" status code, you can not optimize the framework of this piece, I this project is in urgent need of this, thank you!

**Comment by SlaunchaMan** [comment]
Can you be more specific? What is the problem you’re experiencing?
