### ISSUE TITLE
Is it possible to let responseSerializer know the origin requestBody?

### ISSUE THREAD

**Issue by aelam** [AFNetworking/AFNetworking#3623]
We have very special weird binary response structures, some responses isn't parseable  if we don't know the requestData. It's really terrible, but I have to accept the fact.
Since the responseSerializerClasses in AFNetworking are aimed to parse without knowing the 'context', like JSON, XML. But I am wandering if it is still possible to accept some parameters or pass the requestData to  responseSerializerClasses then I can handle my case without struggling

**Comment by StanOz** [comment]
`AFHTTPResponseSerializer` returns original data after validation via `-validateResponse:data:error:`.

**Comment by aelam** [comment]
I know that, but I just know the responseData, I don't know the requestData 


发自我的 iPhone

**Comment by StanOz** [comment]
Oops, my mistake. I thought you just want the original response...   :)

There is a task object in both success and failure block. How about accessing requestBody in block by `task.originalRequest.HTTPBody`? Now you got both original response and request body then you can parse it.

**Comment by aelam** [comment]
@Kam-To , It's OK but not the best way. just like some response serializing depend on requestData, it won't be able to write an independent ResponseSerializer
