### ISSUE TITLE
network requests error

### ISSUE THREAD

**Issue by jsonliu** [AFNetworking/AFNetworking#3624]
AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    
       manager.securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeNone];
    
        NSURL *URL = [NSURL URLWithString:@"https://api.app.net/stream/0/posts/stream/global"];
        NSURLRequest *request = [NSURLRequest requestWithURL:URL];
    
        NSURLSessionDataTask *dataTask = [manager dataTaskWithRequest:request completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
            if (error) {
                NSLog(@"Error: %@", error);
            } else {
                NSLog(@"%@ %@", response, responseObject);
            }
        }];
        [dataTask resume];

reason: '-[NSHTTPURLResponse httpInternal]: unrecognized selector sent to instance 0x7f8ee0e09a00'

**Comment by StanOz** [comment]
It seems not a error thrown out in AFNetworking. Did you try to make an breakpoint to see what exactly going on here?

**Comment by skyline75489** [comment]
Agreed. This doesn't seem to be AFN's fault.

**Comment by sunbohong** [comment]
Which version of AFN are you using?

**Comment by jsonliu** [comment]
Thank you for your attention ！The problem is that I use  HYBUnicodeReadable  Print Chinese，AFN is not the problem.

**Comment by skyline75489** [comment]
Please close the issue then.



发自我的小米手机
在 jsonliu <notifications@github.com>，2016年9月3日 17:27写道：

Thank you for your attention ！The problem is that I use HYBUnicodeReadable Print Chinese，AFN is not the problem.
