### ISSUE TITLE
managerForAddress method of AFNetworkReachabilityManager class for reachability is always giving value as zero.

### ISSUE THREAD

**Issue by syamalach** [AFNetworking/AFNetworking#3626]
This is code snippet i used
AFNetworkReachabilityManager *addressCheck=[AFNetworkReachabilityManager managerForAddress:@"192.168.1.45"];
[addressCheck startMonitoring];
NSLog(@"%hhd",addressCheck.reachable);

**Comment by michaelmou** [comment]
YES,there is no a init network status .

**Comment by michaelmou** [comment]
I init it with a current status in my branch
