### ISSUE TITLE
SSL pining in ios9

### ISSUE THREAD

**Issue by ghazi256** [AFNetworking/AFNetworking#3628]
I am using latest AFNetworking Library. Trying to access https with no certificates AFSSLPinningModeNone and allowInvalidCertificates = YES but it is not working. and giving me SSL certificate error. I add NSAppTransportSecurity NSAllowsArbitraryLoads to yes and allowInvalidCertificates = NO it works. That is very strange behaviors going on.

**EDIT**
even when using https i have to set NSAllowsArbitraryLoads = YES otherwise AFNetwork will give error. 

It needs to be fixed #

**Comment by kcharwood** [comment]
@ghazi256 We have quite a few test cases around the security policy manager, and are still running them on Xcode 7 and iOS 9. Can you create a reproducible case showing this problem?
