### ISSUE TITLE
framework not found FBSDKCoreKit for architecture x86_64

### ISSUE THREAD

**Issue by kumar-aakash86** [AFNetworking/AFNetworking#3629]
Hi
I am new to iOS programming & trying this library but when I am adding AFNetworking in my project using pod, I am getting this strange error on build.
"framework not found FBSDKCoreKit for architecture x86_64"

I tried adding AFNetworking manually but still same issue. Not using FBSDK in my project but its keep giving me FBSDK related error. I have a fresh project and trying to add AFNetworking via pod. I updated my cocoapod version to recent and tried adding AFNetworking 2.6 but still no success.
 
Am I doing something wrong or AFNetworking needs FBSDK dependancy?

My XCode version is Version 7.2.1 (7C1002)

**Comment by kumar-aakash86** [comment]
I just tried adding FBSDKCoreKit to my project. After that its showing 
"framework not found FBSDKLoginKit"

Trying adding FBSDKLoginKit as well but then a new error pops up stating
framework not found Bolts for architecture x86_64

**Comment by taylesworth** [comment]
We use AFNetworking 2.6 and do not have any dependencies on FBSDK. Are you sure you don't have a reference to it in your project file?

**Comment by kumar-aakash86** [comment]
I search "FBSDK" keyword every where in my project from every search option I know & checked some references files. Can you suggest where that reference can be so I can check if I missed that.

**Comment by taylesworth** [comment]
Look at the target you are building and go to "Build Phases" and look at the section titled "Link Binary with Libraries"

**Comment by kumar-aakash86** [comment]
I am using AWS analytics with my project. "Link Binary with Libraries" contains only 3 "AWS" frameworks.

**Comment by taylesworth** [comment]
Is it possible that AWS analytics relies on FBSDK? Try a completely blank project with only AFNetworking installed via pod.

**Comment by kumar-aakash86** [comment]
Ok a blank project build successfully. But AWS is running fine until I add AFNetworking. May be some code which clashed between AWS & AFNetworking causing this issue. But still no specific reason found which I try to solve.

**Comment by kcharwood** [comment]
I'm going to close this out since I don't feel its related to AFNetworking.

🍻
