### ISSUE TITLE
OH MY GOD!!!

### ISSUE THREAD

**Issue by Midzero** [AFNetworking/AFNetworking#3632]
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/AFNetworking.framework/AFNetworking) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Midzero** [comment]
AFNetworking does not support ios7.0???

**Comment by gwynantj** [comment]
Where are you seeing this error? AFNetworking does indeed support iOS 7.0. See: https://github.com/AFNetworking/AFNetworking#requirements

**Comment by skyline75489** [comment]
You are trying to use embedded framework on iOS 7.0 target. This is not possible currently.

**Comment by kcharwood** [comment]
@skyline75489 is right. Embedded Frameworks are not supported on iOS 7
