### ISSUE TITLE
Failed for synchronous call

### ISSUE THREAD

**Issue by erfanhossainshoaib** [AFNetworking/AFNetworking#3633]
I tried to synchronous request and response but failed. How can I change the asynchronous call to synchronous.

Has here any interceptor concept like retrofit, android ??

**Comment by skyline75489** [comment]
AFNetworking does not support sync called. Can you post some code?

**Comment by kcharwood** [comment]
Correct. AFNetworking does not support synchronous network requests, and there are no plans to add that feature.

If you need support it for, I would recommend looking into Dispatch Groups and wrapping your network calls with them.

**Comment by paulmelnikow** [comment]
I wrapped this up in a category:

https://github.com/paulmelnikow/AFNetworking-Synchronous
