### ISSUE TITLE
How to get " responseObject" use "NSURLSessionDataTask *task"

### ISSUE THREAD

**Issue by LittleCurry** [AFNetworking/AFNetworking#3637]
failure:^(NSURLSessionDataTask *task, NSError *error) {
        // responseString or responseObject?
    }]

**Comment by skyline75489** [comment]
The responseObject should be something like NSData or JSON object based on `responseSerializer` you are using. However, nothing would actually returns if your request failed. Thus you cannot cate `responseObject` in failure handler.

**Comment by LittleCurry** [comment]
This problem has been solved:
failure:^(NSURLSessionDataTask *task, NSError *error) {
NSData *responseData = (NSData *)error.userInfo[AFNetworkingOperationFailingURLResponseDataErrorKey];
}]

**Comment by skyline75489** [comment]
If you want the raw data, you can use `AFNetworkingOperationFailingURLResponseDataErrorKey` as above.
