### ISSUE TITLE
AFNetworking call is considerably slower than from PC

### ISSUE THREAD

**Issue by harveyslash** [AFNetworking/AFNetworking#3638]
I wanted to test latency for my server, so I sent a rest request. Using a rest api client, i got around 500 ms latency from desktop, but when i do the same request on iOS Simulator and also physical device (using AFNetworking) , I am getting latency of 1.8 seconds.

My server sends keep alive headers, and I noticed that the first request from my PC is of a similar latency as IOS. How do I make iOS honour keep alive , or reduce latency ? Since I am making a realtime app , it is a must that I have low latency. From the same computer , my rest client is about 3x faster than iOS. How may I fix this issue ?

**Comment by Whirlwind** [comment]
I have same problem. The response did cost 3s~15s, but I check the duration of the request is just 30ms.

**Comment by shaohung001** [comment]
me too,leave a tag to meet answers

**Comment by kcharwood** [comment]
AFNetworking is simply using NSURLSession under the hood to manage the request. There is nothing custom being done at the AF layer.
