### ISSUE TITLE
AFNetworking, missing required architecture x86_64 in file 

### ISSUE THREAD

**Issue by tan2547** [AFNetworking/AFNetworking#3650]
1.Deployment target 调整为7.0  生成的AFNetworking.framework. 导入一个空项目后，测试POST请求。    在编译时报错，我需要怎么样生成AFNetworing.framework 使其可以解决如下问题。
2.AF3.0只能使用在以最低支持版本为iOS8.0的项目中吗？

ignoring file /Users/tanchunjiang/Documents/aftest/aftest/AFNetworking.framework/AFNetworking, missing required architecture x86_64 in file /Users/tanchunjiang/Documents/aftest/aftest/AFNetworking.framework/AFNetworking (3 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AFHTTPSessionManager", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by adammendoza** [comment]
tan2547, did you solve this problem? I had added AFNetworking as a framework after building with Carthage. What solved it for me was to add the framework in four or five places on the project. 
Project -> General -> Embedded Binaries
Project -> General -> Linked Frameworks and Libraries
Project -> Build Phases -> Link Binary with Libraries
Project -> Build Phases -> Embed Frameworks

May need this one too
Project -> Build Phases -> Target Dependencies
