### ISSUE TITLE
Can't build iOS Example

### ISSUE THREAD

**Issue by tewha** [AFNetworking/AFNetworking#3652]
When I build the iOS Example with Xcode 7.3.1 to device (the default) or generic build device, I get this error:

> error: WatchKit App doesn't contain any WatchKit Extensions. Verify that the value of NSExtensionPointIdentifier in your WatchKit Extension's Info.plist is set to com.apple.watchkit.

This is probably the same issue as #3639.

Needless to say, test coverage isn't worth much if your sample app doesn't build. :)

**Comment by skyline75489** [comment]
Are you using `AFNetworking.xcworkspace`?
