### ISSUE TITLE
Providing nil destination block for a download task does not seem to make much sense

### ISSUE THREAD

**Issue by tclementdev** [AFNetworking/AFNetworking#3654]
It seems that providing a nil destination block to `-downloadTaskWithRequest:progress:destination:completionHandler` causes the completion handler to be called with a nil `filePath` and nil `error`.

Wouldn't it make more sense to either:
- change the `destination` block to be non-null
- provide the downloaded file at a random temporary location if the passed `destination` block is nil (similar to what NSURLSession does)

What do you think?

**Comment by skyline75489** [comment]
I think it'd make more sense to mark `destination` as non-null. `NSURLSessionDownloadTask` itself does the "provide the downloaded file at a random temporary location" thing. I think it wouldn't be very meaningful for AFN to repeat this process. Besides, the `nonnull` annotation could also produce warnings if `nil` is accidentally passed in.

**Comment by tclementdev** [comment]
How would one proceed in order to just get the file at a random location? It doesn't seem possible with AFN right now (since the code will try to move the file to the URL returned by the `destination` block).

**Comment by skyline75489** [comment]
Seems to me you don't actually need to download the file as you try to "get the file at a random location". If you just need the data and not the file itself, I think you should just use `NSURLSessionDataTask`. `NSURLSessionDownloadTask` is devoted to downloading files.

**Comment by tclementdev** [comment]
That's not alway true. Some apps need to download (potentially large) files and consume them once downloaded without having them placed at a particular location.

**Comment by skyline75489** [comment]
I believe that essentially what you worry about is that `NSURLSessionDataTask` can not be resumed like `NSURLSessionDownloadTask`. So you want to download it at a temporary position and can be resumed. Am I missing anything here?

**Comment by tclementdev** [comment]
I'm thinking about apps that need to download files and consume them in place. These apps currently need to re-implement the random temporary location code. It could be more convenient if AFN would implement that part (in case of a nil `destination` block).

An example that come to mind is the download of encrypted/signed files that need decryption/validation before going to their final destination.

Though if we don't care about that, marking the `destination` block as non-null should be fine.

**Comment by skyline75489** [comment]
Now I get it. It surely make sense that a nil `destination` causing AFN to return the random path the `NSURLSession` returns.

**Comment by tclementdev** [comment]
That'd be the idea. Though in practice I don't think we can return the path given to us by `NSURLSession` since Apple made the questionable choice of deleting the file once the delegate call returns, as described in the header:

    /* Sent when a download task that has completed a download.  The delegate should 
     * copy or move the file at the given location to a new location as it will be 
     * removed when the delegate message returns. URLSession:task:didCompleteWithError: will
     * still be called.
     */
    - (void)URLSession:(NSURLSession *)session downloadTask:(NSURLSessionDownloadTask *)downloadTask didFinishDownloadingToURL:(NSURL *)location;

So we probably need to either just tweak the filename and move it there, or construct a new random temporary path and move it there.
