### ISSUE TITLE
AFHTTPSession manager caching If-Modified-Since

### ISSUE THREAD

**Issue by kysokzla** [AFNetworking/AFNetworking#3657]
Hi there! I'm totally stuck with caching requests using AF 3.0- absolutely no info in wiki no info in google, no articles... i use Obj-C.
I have a web- service it gives me Last-Modified header for each request, when i send the same request i should add If-Modified-Since with the date from Last-Modified. If no changes i got status code = 304, if any changes- 200 with the corresponding responseObject. 
I have been playing with cachingPolicies and NSURLCache subclasses- but no effect( I figured out terrible custom solution to provide needed logic. 
But i'm very interested exactly which caching mechanism AFNetworking > 3.0 supports. I assume that it can only support caching with max- age headers. 
If u solved the same issue i would appreciate ur comment very much.

**Comment by skyline75489** [comment]
What is your issue here exactly?

**Comment by maksimusenko** [comment]
@skyline75489 `setDataTaskWillCacheResponseBlock` calls each time, even if I get the HTTP status code 304. As far as I understand it should be called only when I get the status code 200 not 304

**Comment by kcharwood** [comment]
AFNetworking does nothing custom here in regards to caching. It uses NSURLSession and NSURLCache by default, and uses the OS caching behavior. You have the hooks exposed to do whatever custom caching you would like to do.
