### ISSUE TITLE
why do use dispatch_sync(url_session_manager_creation_queue) create Task?

### ISSUE THREAD

**Issue by KayonYang** [AFNetworking/AFNetworking#3658]
dispatch_asyn could block the contentext thread. because the [self.session dataTaskWithRequest:request] is not thread-safe? I thought it may block the main thread.

**Comment by KayonYang** [comment]
anybody know why?

**Comment by HoneyLuka** [comment]
In method url_session_manager_create_task_safely() has some comments, maybe is the answer ?

`// Fix of bug
  // Open Radar:http://openradar.appspot.com/radar?id=5871104061079552 (status: Fixed in iOS8)
  // Issue about:https://github.com/AFNetworking/AFNetworking/issues/2093`

**Comment by KayonYang** [comment]
@HoneyLuka thanks a lot. I got the answer.
