### ISSUE TITLE
Clear `AFAutoPurgingImageCache` when entering background?

### ISSUE THREAD

**Issue by rsaunders100** [AFNetworking/AFNetworking#3659]
I noticed that when entering the background a `NSCache` will clear all of its contents.  This is   presumably so that the memory footprint is low when in the background so that there is less chance the app will be purged from memory.  

Most of the time while in the background the app will not be running (I believe most apps only get ~10s of background execution now) and I think they will not be woken up to receive a memory warning.  So the only way to clear the cache memory is to do it before entering the background.

On a related note, does anyone know why AFNetworking does not use a `NSCache` anymore for images?

**Comment by kcharwood** [comment]
The behavior of `NSCache` was simply not deterministic enough for us.

`AFAutoPurgingImageCache` will respond to low memory conditions and purge itself automatically. If you wanted to purge yourself on background, you can call`removeAllImages` on the image cache to clear it yourself.

**Comment by zhihuitang** [comment]
I have an App, the images consume 40+ MB memory. When the App went background, it released only 4M memory.
After I changed the AFNetworking to SDWebImage, it released 25M memory when the App went to the background.

I quite doubt the AFAutoPurgingImageCache is doing its job properly.

**Comment by zhihuitang** [comment]
Hi @kcharwood ,

I tested it Simulator with "Simulate Memory Warning". 
I added a breakpoint inside `removeAllImages`. I found that the it did go to `removeAllImages`,
but no memory released at all.

Could you please give some explanation? Thank you very much.

```
- (BOOL)removeAllImages {
    __block BOOL removed = NO;
    dispatch_barrier_sync(self.synchronizationQueue, ^{
        if (self.cachedImages.count > 0) {
            [self.cachedImages removeAllObjects];
            self.currentMemoryUsage = 0;
            removed = YES;
        }
    });
    return removed;
}

```
