### ISSUE TITLE
我在上传文件的时候，上传的文件大小大于实际大小，文件可以正常使用/uploadProgress.totalUnitCount  is 153more the real lenth

### ISSUE THREAD

**Issue by chuanzhe** [AFNetworking/AFNetworking#3660]
[manger POST:url parameters:nil constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
        
        //Init the inputStream with given data.
    NSInputStream *inputSteam = [NSInputStream inputStreamWithFileAtPath:testPath];
        // Set the offset for the inputStream.
    [inputSteam setProperty:@(0) forKey:NSStreamFileCurrentOffsetKey];
    [formData appendPartWithInputStream:inputSteam name:@"file" fileName:model.packageName length:model.filelength.longLongValue mimeType:@"zip/zip"];
        
        
    } progress:^(NSProgress * _Nonnull uploadProgress) {
        
        NSLog(@"-----%llu-----%llu---",uploadProgress.completedUnitCount,uploadProgress.totalUnitCount);
        
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        
        NSLog(@"%@",responseObject);
        
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        
        NSLog(@"%@",error);
        
    }];

**Comment by Huang-Libo** [comment]
@chuanzhe Please use English to write title..

**Comment by chuanzhe** [comment]
Sorry, no English yesterday, I looked in detail at today, the problem is solved, thank you！
