### ISSUE TITLE
 PUT to submit FormData

### ISSUE THREAD

**Issue by ZZKll** [AFNetworking/AFNetworking#3661]
How are you 
how to use the PUT to submit FormData 
excuse me

**Comment by skyline75489** [comment]
What's your questions exactly?

**Comment by jcesarmobile** [comment]
I think he means that PUT doesn't have constructingBodyWithBlock

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
