### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed.

### ISSUE THREAD

**Issue by VictorLiChou** [AFNetworking/AFNetworking#3666]
Hi there，I have a json string with ‘Tab’ in it, when I tried to prase it, I got this Error. After search in the internet, there is a resolve at 'http://stackoverflow.com/questions/11177661/unescaped-control-characters-in-nsjsonserialization', But I'd like to known, How could I handle this without any modify in AFNetworking, cause I don't want to change the logical that will affect any other problems.  If there is a way to handle this when my request callback? 
Hope your answer, best wishes!

**Comment by kcharwood** [comment]
You can always subclass your response serialization do whatever you need to for your application.

🍻
