### ISSUE TITLE
Methods erring without returning NO/nil

### ISSUE THREAD

**Issue by tclementdev** [AFNetworking/AFNetworking#3671]
I'm not sure if this is a voluntary choice in AFNetworking but some methods are not returning nil when an error occurs. This is very confusing since the Cocoa convention is to always look at the return value of a method (for a `NO` or `nil` value) before looking at the passed `NSError **`. Following that convention here does not allow to handle errors since the return value may not be NO/nil.

Such method is `-[AFURLRequestSerialization multipartFormRequestWithMethod:URLString:parameters:constructingBodyWithBlock:error:]`.

**Comment by kcharwood** [comment]
Addressed in #3653
