### ISSUE TITLE
file upload not work in AFNetworking 3.0

### ISSUE THREAD

**Issue by rushabh0999** [AFNetworking/AFNetworking#3674]
Hello Team,

I want to upload .zip file on server so i am using AFNetworking 3.0 but i can't able to upload using it but same code works in AFNetworking 2.0  for more details i did ask question on SO check below link 
[Question Link On Stackoverflow](http://stackoverflow.com/questions/39325058/upload-zip-file-in-afnetwoking-3-0)

Waiting for yr reply :)

**Comment by skyline75489** [comment]
It seems your problem has been solved on SO. Can you please close this issue?
