### ISSUE TITLE
AFNetworking old version: [self.outputStream close]; crash on iOS 10

### ISSUE THREAD

**Issue by chinhnd** [AFNetworking/AFNetworking#3678]
I'm using old version of iOS AFNetworking which has class AFURLConnectionOperation.

My app work fine on iOS 9x, but when i run my app on iOS 10, it crash immediately on this function:

- (void)connectionDidFinishLoading:(NSURLConnection __unused *)connection {
    self.responseData = [self.outputStream propertyForKey:NSStreamDataWrittenToMemoryStreamKey];

    [self.outputStream close];
    if (self.responseData) {
       self.outputStream = nil;
    }

    self.connection = nil;

    [self finish];
}

The crash EXC_BAD_ACCESS happens on this line:
[self.outputStream close];

Does anyone know why?

Thanks

**Comment by kcharwood** [comment]
We are no longer supporting that version of AFNetworking, and Apple has advised developers to update all code from NSURLConnection to NSURLSession. I'd recommend you do the same by using AFN 3.x.
