### ISSUE TITLE
Crash on AFHTTPRequestSerializer 

### ISSUE THREAD

**Issue by martinobonfiglioli** [AFNetworking/AFNetworking#3684]
I got an error with the latest release, hope this stack trace can help:

> Crashed: com.apple.root.background-qos
> 0  CoreFoundation                 0x188768af8 -[__NSSetM member:] + 108
> 1  CoreFoundation                 0x188757358 -[NSSet containsObject:] + 24
> 2  MusixmatchCore                 0x100be8944 -[AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:] + 568
> 3  MusixmatchCore                 0x100b9e0d8 -[MXMRequestQueue createRequest:requestURL:parameters:requestContentType:] + 472
> 4  MusixmatchCore                 0x100b98d84 -[MXMRequest initWithAction:params:] + 624
> 5  MusixmatchCore                 0x100b05c14 -[MXMEventPostLoader initWithOptions:completionHandler:] + 328
> 6  MusixmatchCore                 0x100bf7f4c __50-[MXMMusixmatchCoreService queueEvent:parameters:]_block_invoke + 288
> 7  libdispatch.dylib              0x1876fd200 _dispatch_call_block_and_release + 24
> 8  libdispatch.dylib              0x1876fd1c0 _dispatch_client_callout + 16
> 9  libdispatch.dylib              0x18770d558 _dispatch_root_queue_drain + 1032
> 10 libdispatch.dylib              0x18770d0ec _dispatch_worker_thread3 + 124
> 11 libsystem_pthread.dylib        0x1879052c8 _pthread_wqthread + 1288
> 12 libsystem_pthread.dylib        0x187904db4 start_wqthread + 4

**Comment by kcharwood** [comment]
Do you have way to provide a reproducible case here?

**Comment by martinobonfiglioli** [comment]
Full report here: http://crashes.to/s/865cc699a6a

Hope this can help

**Comment by skyline75489** [comment]
Any way to reproduce this?

**Comment by martinobonfiglioli** [comment]
Not yet I'm sorry. It happened to me two times during debug and always at the app startup.

**Comment by kongchenyang** [comment]
I also encountered the same problem, it is not easy to reproduce
