### ISSUE TITLE
Cookies are always empty in WatchOS 3

### ISSUE THREAD

**Issue by madmet** [AFNetworking/AFNetworking#3686]
Hi,
Using AFNetworking my cookieStorage is empty ONLY for WatchOS 3 calls (it works with no problems for older versions).
Using NSURLSession call it's all ok.
Have you any solution for this issue, please?

**Comment by wlisac** [comment]
@madmet I'm seeing the same issue in watchOS 3. I haven't tried using `NSURLSession` directly to see if that fixes it. 

Have you been able to find the root issue here?

**Comment by madmet** [comment]
@wlisac I've just tried using `NSURLSession` but it doesn't fix the problem. 
I've tried to ask a technical support via iTunes Connect, they said me to open a Bug and I did it but still waiting for an answer.

**Comment by wlisac** [comment]
I believe I've found a _totally silly_ workaround to this issue on watchOS 3.

The basic idea is to shim the `sharedHTTPCookieStorage` and set the `sessionConfiguration`'s cookie storage to the shim object.


```objc
    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
    configuration.HTTPCookieStorage = [[HTTPCookieStorageShim alloc] init];
    self.client = [[AFHTTPSessionManager alloc] initWithBaseURL:url sessionConfiguration:configuration];
```


```objc

#import "HTTPCookieStorageShim.h"

@implementation HTTPCookieStorageShim

- (NSArray<NSHTTPCookie *> *)cookies
{
    return [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookies];
}

- (void)deleteCookie:(NSHTTPCookie *)cookie
{
    [[NSHTTPCookieStorage sharedHTTPCookieStorage] deleteCookie:cookie];
}

- (void)removeCookiesSinceDate:(NSDate *)date
{
    [[NSHTTPCookieStorage sharedHTTPCookieStorage] removeCookiesSinceDate:date];
}

- (NSArray<NSHTTPCookie *> *)cookiesForURL:(NSURL *)URL
{
    return [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookiesForURL:URL];
}

- (void)setCookies:(NSArray<NSHTTPCookie *> *)cookies forURL:(NSURL *)URL mainDocumentURL:(NSURL *)mainDocumentURL
{
    [[NSHTTPCookieStorage sharedHTTPCookieStorage] setCookies:cookies forURL:URL mainDocumentURL:mainDocumentURL];
}

- (NSHTTPCookieAcceptPolicy)cookieAcceptPolicy
{
    return [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookieAcceptPolicy];
}

- (void)setCookieAcceptPolicy:(NSHTTPCookieAcceptPolicy)cookieAcceptPolicy
{
    [[NSHTTPCookieStorage sharedHTTPCookieStorage] setCookieAcceptPolicy:cookieAcceptPolicy];
}

- (NSArray<NSHTTPCookie *> *)sortedCookiesUsingDescriptors:(NSArray<NSSortDescriptor *> *)sortOrder
{
    return [[NSHTTPCookieStorage sharedHTTPCookieStorage] sortedCookiesUsingDescriptors:sortOrder];
}

- (void)storeCookies:(NSArray<NSHTTPCookie *> *)cookies forTask:(NSURLSessionTask *)task
{
    [[NSHTTPCookieStorage sharedHTTPCookieStorage] storeCookies:cookies forTask:task];
}

- (void)getCookiesForTask:(NSURLSessionTask *)task completionHandler:(void (^)(NSArray<NSHTTPCookie *> * _Nullable))completionHandler
{
    [[NSHTTPCookieStorage sharedHTTPCookieStorage] getCookiesForTask:task completionHandler:completionHandler];
}

@end
```

**Comment by wlisac** [comment]
@madmet I'd also suggest renaming this issue. It's not that the `sharedHTTPCookieStorage` is `null`, it's more that the `sharedHTTPCookieStorage`'s `cookies` are always empty in watchOS 3.

**Comment by kcharwood** [comment]
Sounds like this is an issue with NSURLSession on Watch OS 3, not AFNetworking, right?

cc @cnstoll

**Comment by madmet** [comment]
@kcharwood right! It seems to be an `NSURLSession` issue.
@wlisac i've made the same work around and it works like a charm! I've just noticed it to Apple on my bug history.

**Comment by wlisac** [comment]
@kcharwood it appears so. I'm currently working on a sample project for Apple / radar. @madmet would you mind providing me with your radar number (or even better, a link to openradar) and maybe share your sample project?

**Comment by wlisac** [comment]
Radar filed with sample project here:

https://github.com/ServiceNow/radar.apple.com/tree/master/28675451%20-%20watchOS%203%20not%20setting%20some%20cookies

**Comment by chaseacton** [comment]
@wlisac Thank you so much for this. This issue still exists in watchOS 4 and your shim solution is working.

**Comment by wlisac** [comment]
@chaseacton No problem. Unfortunate to hear that this is still a problem, though. We've been using the shim for a while now with no known issues.

**Comment by jverkoey** [comment]
fwiw in case anyone else stumbles upon this issue through search, I was still running into this buggy behavior on watchOS 9.1 and was able to fix it with the changes in https://github.com/driven-app/porsche-connect/pull/108
