### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by ACommonChinese** [AFNetworking/AFNetworking#3711]
Hi, I just run into a bug(may be), the code just like this:

```
NSArray *array = @[@"arr_obj_1", @"arr_obj_2"];
NSSet *set = [NSSet setWithObjects:@"set_value_1", @"set_value_2", array, nil];
NSDictionary *dict = @{@"key" : set};
// .... POST
```

I know, may be no people write it like this except myself, but it is crash if I did this.

**Comment by 0xced** [comment]
`NSSet` is not serializable as JSON, you should try using an `NSArray` instead.
