### ISSUE TITLE
CRASH - dispatch_async in AFURLSessionManager.m

### ISSUE THREAD

**Issue by CMathgician** [AFNetworking/AFNetworking#3712]
![screen shot 2016-09-27 at 6 37 46 pm](https://cloud.githubusercontent.com/assets/6632239/18871921/fb1f0a1e-84e1-11e6-8fc2-018e73812d5c.png)

How to fix it?

**Comment by cjjimenez** [comment]
Having same issue.

**Comment by passerbied** [comment]
The same issue...

**Comment by gmcerveny** [comment]
Same. Reproducible on iOS10. Works fine on iOS9.

**Comment by kcharwood** [comment]
Any idea how to reproduce this? Can some generate a test case showing the failure? We have Xcode 8 on Travis now, so it should be able to run and catch it there.

**Comment by gmcerveny** [comment]
If it's any help to someone putting together a test, the issue for me presented itself on download requests.  I had a "test" that would run 10 consecutive downloads (> 400mb) and it would produce this error at varying points. I wrote some code to switch to NSURLSesssion and it crashed as well on iOS 10 (but not 9).

**Comment by kcharwood** [comment]
@gmcerveny Does that lead you to believe its a bug in NSURLSession?

**Comment by rudysuharyadi** [comment]
Is it related to this?

https://forums.developer.apple.com/thread/60622

because my crashlog says something about 'BUG IN CLIENT OF LIBPLATFORM: Unlock of an os_unfair_lock not owned by current thread'
