### ISSUE TITLE
In order to validate a domain name for self signed certificates, you MUST use pinning 

### ISSUE THREAD

**Issue by a598799539** [AFNetworking/AFNetworking#3713]
When I request a https url, it comes `-999 error` and log `In order to validate a domain name for self signed certificates, you MUST use pinning`

afnetworking version: 3.1.0 (It works fine if the version is 3.0.0)
ios: 10.0.1
xcode: 8.0
swift: 2.3.0

---

other settings:

```
Static.instance?.securityPolicy = AFSecurityPolicy(pinningMode: AFSSLPinningMode.Certificate)
Static.instance?.securityPolicy.allowInvalidCertificates = true
```

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
