### ISSUE TITLE
afnetworking reachability ios 10 simulator

### ISSUE THREAD

**Issue by semenag01** [AFNetworking/AFNetworking#3714]
reachability doesn't handle state from wifi Off to wifi On.

**Comment by Jeff-F** [comment]
+1, has same issue, any progress?

**Comment by paulharter** [comment]
I found I was getting a similar problem in 9.3 if I had more than one session manager and had set more than one setReachabilityStatusChangeBlock as all the session managers share a singleton reachability manager and it has a single networkReachabilityStatusBlock. So if you set two you delete the first.

**Comment by vtaneeru** [comment]
same issue. Any luck?
