### ISSUE TITLE
Can't save in custom directory in Library, but can in Documents

### ISSUE THREAD

**Issue by CMathgician** [AFNetworking/AFNetworking#3717]
Hi, can someone help me?
I use AFURLSessionManager
`downloadTaskWithRequest:progress:destination:completionHandler:`

But the file doesn't exist.
When I change the destination to 
`[[NSFileManager defaultManager] URLForDirectory:NSDocumentDirectory inDomain:NSUserDomainMask appropriateForURL:nil create:NO error:nil];`
the file created.

the path that I want to is Library/{custom_dir}/{file.zip}

**Comment by 0xced** [comment]
Have you created the `Library/{custom_dir}` directory before trying to download `{file.zip}` into that directory?

**Comment by CMathgician** [comment]
Yes, the `Library/{custom_dir}` has created.

Its worked with :
`NSURL *documentsDirectoryURL = [[NSFileManager defaultManager] URLForDirectory:NSLibraryDirectory inDomain:NSUserDomainMask appropriateForURL:nil create:NO error:nil];

NSURL *fullURL = [documentsDirectoryURL URLByAppendingPathComponent:[NSString stringWithFormat:@"%@/%@.zip", customDir, fileName]];

return fullURL;
`

But, doesn't work with :
`return [NSURL URLWithString:fullPathString];`
fullPathString is {root}/Library/{custom_dir}/{file.zip}

when I log them, it's same.

**Comment by 0xced** [comment]
That's because you have to use [`fileURLWithPath:`](https://developer.apple.com/reference/foundation/nsurl/1410828-fileurlwithpath?language=objc)instead of `URLWithString:` for local file URLs.

Anyway, using `URLForDirectory:inDomain:appropriateForURL:create:error:` is indeed the best solution for this issue.

**Comment by CMathgician** [comment]
Wow. Thanks for your advice, @0xced.

**Comment by Fouda** [comment]
thanks it helped me: 👍
