### ISSUE TITLE
operationQueue property is misleading and should not be exposed public

### ISSUE THREAD

**Issue by peterpaulis** [AFNetworking/AFNetworking#3720]
Based on my question
http://stackoverflow.com/questions/39807300/how-does-the-maxconcurrentoperationcount-of-the-nsurlsession-delegatequeue-effec/39807607#39807607

the operationQueue property **does not reflect** any network operations, just the delivery of delegate messages as it is equal to the delegateQueue...

in fact this property doesn't even need to be exposed as it can lead to misleading assumptions (i noticed several wrong codes, assuming setting the maxConcurrentOperationCount, which is also the result, than in AF 2.0 this property did in fact allowed to set the number of concurrent network operations, but since 3. it's role changed)

setting it's concurrency doesn't effect the concurrency of the operations or task, and this should be done via `HTTPMaximumConnectionsPerHost` of the `NSURLSessionConfiguration`

**Comment by skyline75489** [comment]
+1 on this. I've once used this wrongly until one of my colleagues pointed it out.

**Comment by skyline75489** [comment]
#3647 as a exmple

**Comment by DuncanMC** [comment]
I don't necessarily agree that it should not be exposed as public. Rather, this is the queue on which your delegate methods get called, and it needs to be renamed and documented to make it clear what this property does. There are cases where you DO want to send delegate messages to a different operation queue, and in that case this property is useful. `sessionDelegateMessageOperationQueue` would be a better name for the property, and it needs documentation.

**Comment by peterpaulis** [comment]
Renamed for sure!

But why would you need to handle the session delegate messages on another thread anyway? This will make no performance gain if i'am not mistaken (the network operation & parsing is not executed on this queue anyway, just the delegate calls...) (if you want to later do custom parsing, you can execute this as a async block inside the completion block)
