### ISSUE TITLE
Xcode 8.1/iOS 10.1 Cert pinning fails

### ISSUE THREAD

**Issue by jdrobert** [AFNetworking/AFNetworking#3723]
This morning I started testing the iOS 10.1 beta and I ran into this issue where cert pinning now fails. 

I'm using AFNetworking 3.1.0 and the exact same code in Xcode 8.0/iOS 10 runs fine. Everything also works when I disable cert pinning. 

Any insight as to what is going on would be appreciated. If I left something out or you need more info, please let me know. 

Manager setup
```objc
AFHTTPSessionManager *manager = [[AFHTTPSessionManager alloc] init];
manager.requestSerializer = [AFJSONRequestSerializer serializer];
            
AFSecurityPolicy *policy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModePublicKey];
policy.allowInvalidCertificates = NO;
policy.validatesDomainName = NO;
policy.pinnedCertificates = [AFSecurityPolicy certificatesInBundle:[NSBundle mainBundle]];
            
manager.securityPolicy = policy;
```

Info.plist
```xml
    <key>NSAppTransportSecurity</key>
	<dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>abc.domain.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSExceptionMinimumTLSVersion</key>
                <string>TLSv1.2</string>
                <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                <false/>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <true/>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.2</string>
                <key>NSRequiresCertificateTransparency</key>
                <false/>
            </dict>
        </dict>
	</dict>
```

Error from failure response
```
Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=abc.domain.com, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=abc.domain.com}
```

Edit: 
It looks like `AFSecKeyIsEqualToKey` is returning false in 8.1. It seem to be because `SecTrustGetCertificateCount` in`AFPublicKeyTrustChainForServerTrust` isn't returning the same number of certificates as in 8.0. I get 3 in XC8.1 and 4 in 8.0. It is ignoring the root which we pin to. Using the exact cert of the subdomain made everything work. Thanks!

~~Also, I made a simple client with Alamofire and was able to get a successful response using cert pinning in Xcode 8.1/iOS 10.1. While this is a possible solution, replacing the networking library isn't ideal.~~

**Comment by anthonymlagrange** [comment]
Hi @jdrobert - did you close this issue because it was resolved due to a change in AFNetworking, or for some other reason? 

I'm also seeing certificate pinning fail in iOS 10.1 (but not prior) due to `SecTrustGetCertificateCount` returning a different number of certificates (in a different project).

Thanks

**Comment by jdrobert** [comment]
@anthonymlagrange I closed it because I figured the problem was with iOS and not AFNetworking. The same code works differently in two different versions of iOS. 

The temporary fix was to pin to a cert closer to the domain (I was using the root cert). The full fix was to move to Alamofire which for some reason didn't have the problem.
