### ISSUE TITLE
Parameter set to nil on UIWebView+AFNetworking.m

### ISSUE THREAD

**Issue by mrjimoy** [AFNetworking/AFNetworking#3724]
I just upgrade my AFNetworking version from 2.5.4 to 3.1.0, and after test some feature on my app, my UIWebView doesn't work with a 401 error (Authentication Error). I have passing the Authentication header to the request, but then after checking the lib's code, I found this:

![image](https://cloud.githubusercontent.com/assets/6197219/19066512/d953d07e-8a43-11e6-876a-5b676bc91e12.png)

The parameters that supposed to be where the authentication header is, is set to nil. When I tried to debug the value of request, the header does exists, but since the code set the parameters to nil, then it return 401 error.

Any idea? Thanks.

**Comment by kcharwood** [comment]
Yes this does look a bug. Would you want to put together a PR to address it?
