### ISSUE TITLE
why AFURLSessionManager setTaskDidComplete method doesn't support set different completion block for different task. 

### ISSUE THREAD

**Issue by 859988748** [AFNetworking/AFNetworking#3746]
setTaskDidComplete (line 856 AFURLSessionManager.m), why doesn't this method support set different completion block for different task. 

If I have multiple data downloaded tasks managed by a session manager running at the same time, I want to set separate completion block for different task. It seems all task executing the same completion block after accomplished. I see there is a task parameter passed to completion block. I thought it was used to set different completion block for different task.

It seems other completion block has the same problem.

And maybe AFNetworking support set downloading progress after the download task resumed.

**Comment by skyline75489** [comment]
I think you misunderstand the usage here. As the documentation mentions, `setTaskDidComplete` means:

>Sets a block to be executed as the last message related to a specific task, as handled by the `NSURLSessionTaskDelegate` method `URLSession:task:didCompleteWithError:

And [here] you can clearly see that the `taskDidComplete` is called *after* individual delegate callback is called.

For a single request you should use `dataTaskWithRequest` in `AFURLSessionManager`, or methods in `AFHTTPSessionManager`.

**Comment by skyline75489** [comment]
BTW, please read as much documentation as you can before asking a question on SO or file a issue on Github. It'll truly shows your respect and your appreciation for this amazing project along with those who cares about it.

**Comment by kcharwood** [comment]
🍻
