### ISSUE TITLE
how to clear cache in AFNetworking 3.0 ?

### ISSUE THREAD

**Issue by hebiao6446** [AFNetworking/AFNetworking#3749]
before  AFNetworking 3.0  
- (void)clearCache
  {
  AFImageCache *cache = (AFImageCache *)[UIImageView sharedImageCache];
  [cache removeAllObjects];
  return;
  }
- (void)clearCacheWithURL:(NSURL _)url
  {
  NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
  [request addValue:@"image/_" forHTTPHeaderField:@"Accept"];
  
  AFImageCache *cache = (AFImageCache *)[UIImageView sharedImageCache];
  [cache removeObjectForKey:[[request URL] absoluteString]];
  }

but  after  AFNetworking 3.0  
OK , it does not work !!!!!

how to ...... 
OK .. 
YOU KNOW ....

**Comment by skyline75489** [comment]
I think what you're looking for is `removeAllImages`.

**Comment by hebiao6446** [comment]
Yes , Thanks ...  GET it  !

**Comment by Maxim-Inv** [comment]
This code works for me:
`            [[NSURLCache sharedURLCache] removeAllCachedResponses];
			
			AFImageDownloader *imageDownloader = [AFImageDownloader defaultInstance];
			NSURLCache *urlCache = imageDownloader.sessionManager.session.configuration.URLCache;
			[urlCache removeAllCachedResponses];
			
            [imageDownloader.imageCache removeAllImages];
`

**Comment by futuretap** [comment]
As of iOS 10.2 (and 10.3 beta 1) it is actually needed to clean the cache manually because [NSURLCache does not respect diskCapacity](http://www.openradar.me/30312749).
