### ISSUE TITLE
MultipleForm Request Concurrency

### ISSUE THREAD

**Issue by nickwu123** [AFNetworking/AFNetworking#3755]
Hi, i got issue about "requestWithMultipartFormRequest".
there is a singleton method name like "NetworkManager" i call the "requestWithMultipartFormRequest" method by it. But when i send two requests at once. i found the sever got the wrong boundary. Actually, it should be two different form, but there are confusion.
Seem like 
First one:
 "--Boundary+6240A25291D8C205 
....
....
...
--Boundary+6240A25291D8C205--
"
Second One:
 "--Boundary+738D25431A8B741
....
....
...
--Boundary+6240A25291D8C205--
"
I found about generate Boundary Using "Self.boundary". So if there two requests are called, first request didn't finish about the assemble the form, the second request is called, the boundary will be generate a new one. So the first form will use the new one. the problem comes up.
So what i thought is correct ? is the MultipleForm request issues?

**Comment by skyline75489** [comment]
This looks like a reproducible bug. Can you post some code that can demonstrates this error?

**Comment by nickwu123** [comment]
Thank U for your reply. i have got where the issue happen.it is not about AFNetworking. there is a man , he wrote the singleton method . But he made a mistake. he put the parameter into the specify file path. So if there is a multiple request, different parameter will be wrote into the file in the different time. So at last when the afnetworking sent the request , the body will be wrong.

**Comment by skyline75489** [comment]
Great. Seems like a false alarm. I think this can be closed for now.
