### ISSUE TITLE
user Cellular request failed

### ISSUE THREAD

**Issue by zzffyy** [AFNetworking/AFNetworking#3756]
use AFHTTPSessionManage POST request in Wireless no problem,but in cellular cannot 
visit

**Comment by zzffyy** [comment]
plz help me!!!

**Comment by skyline75489** [comment]
Github 不是技术支持论坛，issues 只负责 AFNetworking 本身有关的问题，如果需要使用帮助，请去 [StackOverflow](http://stackoverflow.com/) 提问。

Github is not a technical support forum. Issues should only be about AFNetworking itself. If you need help about using this library, you can ask a question on [StackOverflow](http://stackoverflow.com/).
