### ISSUE TITLE
Implementing custom framework-"Undefined symbols for architecture x86_64:"

### ISSUE THREAD

**Issue by sachinakhaire** [AFNetworking/AFNetworking#3757]
"_OBJC_CLASS_$_SocialAnnexProvider", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in DetailViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This custom framework build for simulators and devices on release mode instead debug.

**Comment by skyline75489** [comment]
Perhaps you actually didn't build for x86_64?

**Comment by sachinakhaire** [comment]
When I check the "lipo -info xyz.framework"

terminal showing me build for - i386, x86_64, armv7, armv7s, arm64 all these architectures.

**Comment by skyline75489** [comment]
Have you tried clean `DerivedData`?

**Comment by sachinakhaire** [comment]
yep I cleaned it also!

**Comment by SlaunchaMan** [comment]
Is this an AFNetworking issue? Closing because it doesn't seem like it; feel free to reopen if you have AFNetworking bugs to report. For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
