### ISSUE TITLE
why my request do not return error when no net state.

### ISSUE THREAD

**Issue by jhhnjhhn** [AFNetworking/AFNetworking#3763]
When no net. Java ports can return error but PHP ports can not return.

**Comment by skyline75489** [comment]
Github 不是技术支持论坛，issues 只负责 AFNetworking 本身有关的问题，如果需要使用帮助，请去 [StackOverflow](http://stackoverflow.com/) 提问。

Github is not a technical support forum. Issues should only be about AFNetworking itself. If you need help about using this library, you can ask a question on [StackOverflow](http://stackoverflow.com/).
