### ISSUE TITLE
Huge memory leaks in AFJSONObjectByRemovingKeysWithNullValues method.

### ISSUE THREAD

**Issue by parasappafluke** [AFNetworking/AFNetworking#3766]
Hi,
My application has huge amount of JSON data and large number of web services calls. AFJSONObjectByRemovingKeysWithNullValues leaking huge amount of memory when i enable response serializer to remove null values. Its leaking around 8MB of memory.See attached instrument screenshot. 
<img width="1280" alt="screen shot 2016-10-24 at 11 22 07 am" src="https://cloud.githubusercontent.com/assets/1881376/19635043/07cf593e-99dd-11e6-932f-10e24bb02568.png">

**Comment by tewha** [comment]
That's where the memory is being allocated, not where it's being leaked. If you expand your search, you'll likely find a leaked object that maintains a reference to a response.

**Comment by skyline75489** [comment]
I agree with @tewha . Prove me wrong, but I don't see a potential leak in `AFJSONObjectByRemovingKeysWithNullValues`, either.

**Comment by parasappafluke** [comment]
See attached screenshot. In my application i'm not holding any reference to a response object i just use this response to create core data objects.
<img width="1032" alt="screen shot 2016-10-25 at 9 35 43 am" src="https://cloud.githubusercontent.com/assets/1881376/19698567/6d4cd90e-9b0d-11e6-895a-3f906a1e6480.png">

**Comment by tewha** [comment]
I'm sure it's not what you wanted, but that screenshot proves there's no leak in `AFJSONObjectByRemovingKeysWithNullValues`.

**Comment by SlaunchaMan** [comment]
Closing this as it’s pretty old; feel free to re-open if you can follow @tewha’s instructions and find something.
