### ISSUE TITLE
-[AFSecurityPolicy evaluateServerTrust:forDomain:] crash

### ISSUE THREAD

**Issue by fysteven** [AFNetworking/AFNetworking#3768]
Hi there,
I recently tried to add certificate file to my iOS project. I'm getting crash.

It seems that it can find the correct .cer file, but it's failing to add a NSData object to a mutable array.

`           
 for (NSData *certificateData in self.pinnedCertificates) {
                [pinnedCertificates addObject:(__bridge_transfer id)SecCertificateCreateWithData(NULL, (__bridge CFDataRef)certificateData)];
            }
` 
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f2e234b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010e92621e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f21338f -[__NSArrayM insertObject:atIndex:] + 1375
	3   AFNetworking                        0x000000010a2713a2 -[AFSecurityPolicy evaluateServerTrust:forDomain:] + 1378
	4   AFNetworking                        0x000000010a290bb1 -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] + 1089
	5   Foundation                          0x000000010e42a2cd __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	6   Foundation                          0x000000010e429faf -[NSBlockOperation main] + 101
	7   Foundation                          0x000000010e4286ac -[__NSOperationInternal _start:] + 672
	8   Foundation                          0x000000010e4245ef __NSOQSchedule_f + 201
	9   libdispatch.dylib                   0x000000010fe760cd _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010fe53e6b _dispatch_queue_serial_drain + 236
	11  libdispatch.dylib                   0x000000010fe54b9f _dispatch_queue_invoke + 1073
	12  libdispatch.dylib                   0x000000010fe573b7 _dispatch_root_queue_drain + 720
	13  libdispatch.dylib                   0x000000010fe5708b _dispatch_worker_thread3 + 123
	14  libsystem_pthread.dylib             0x0000000110225736 _pthread_wqthread + 1299
	15  libsystem_pthread.dylib             0x0000000110225211 start_wqthread + 13

**Comment by skyline75489** [comment]
Could it be that your cer file is broken?

**Comment by Chuckytuh** [comment]
make sure your certificate is in DER format

**Comment by fysteven** [comment]
It turned out that the certificate was not in DER format. After I converted the format, it doesn't crash now.

**Comment by RPallas92** [comment]
Same issue here. We were using a PEM encoded cert and the app crashed. We fix it converting the PEM encode to DER:

`PEM to DER

openssl x509 -in cert.crt -outform der -out cert.der`

More info: https://support.ssl.com/Knowledgebase/Article/View/19/0/der-vs-crt-vs-cer-vs-pem-certificates-and-how-to-convert-them
