### ISSUE TITLE
An instance of class __NSCFBackgroundDownloadTask was deallocated while KVO still registered with it

### ISSUE THREAD

**Issue by fighting300** [AFNetworking/AFNetworking#3769]
An instance of class __NSCFBackgroundDownloadTask was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo > (<NSKeyValueObservance : Observer: , Key path: countOfBytesReceived, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: ><NSKeyValueObservance : Observer: , Key path: countOfBytesExpectedToReceive, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: ><NSKeyValueObservance : Observer: , Key path: countOfBytesSent, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: ><NSKeyValueObservance : Observer: , Key path: countOfBytesExpectedToSend, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: >)

0 CoreFoundation 0x000000018b9ac1d8 <redacted> + 148
1 libobjc.A.dylib 0x000000018a3e455c objc_exception_throw + 56
2 CoreFoundation 0x000000018b9ac108 <redacted> + 0
3 Foundation 0x000000018c3f9df4 <redacted> + 300
4 libsystem_blocks.dylib 0x000000018a88aa28 _Block_release + 144
5 libdispatch.dylib 0x000000018a8351c0 <redacted> + 16
6 libdispatch.dylib 0x000000018a843444 <redacted> + 928
7 libdispatch.dylib 0x000000018a8389a8 <redacted> + 652
8 libdispatch.dylib 0x000000018a843940 <redacted> + 360
9 libdispatch.dylib 0x000000018a84538c <redacted> + 572
10 libdispatch.dylib 0x000000018a8450ec <redacted> + 124
11 libsystem_pthread.dylib 0x000000018aa3d2c8 _pthread_wqthread + 1288
12 libsystem_pthread.dylib 0x000000018aa3cdb4 start_wqthread + 4

I have this problem when using background Fetch and download file from internet.

**Comment by skyline75489** [comment]
Probably duplicate of #3681 ?
