### ISSUE TITLE
response: cache the post response

### ISSUE THREAD

**Issue by mxyolande** [AFNetworking/AFNetworking#3770]
**in AppDelegate i use the code :** 
    `NSURLCache *urlCache = [[NSURLCache alloc] initWithMemoryCapacity:4 * 1024 * 1024 diskCapacity:20 * 1024 * 1024 diskPath:nil];
    [NSURLCache setSharedURLCache:urlCache];
`

**then i inherit AFHTTPSessionManager to use a private method of AFN i define a protocol** 
    `- (NSURLSessionDataTask *)dataTaskWithHTTPMethod:(NSString *)method
                                       URLString:(NSString *)URLString
                                      parameters:(id)parameters
                                  uploadProgress:(nullable void (^)(NSProgress *uploadProgress)) uploadProgress
                                downloadProgress:(nullable void (^)(NSProgress *downloadProgress)) downloadProgress
                                         success:(void (^)(NSURLSessionDataTask *, id))success
                                         failure:(void (^)(NSURLSessionDataTask *, NSError *))failure;
`

**in initWithBaseURL i call this method and startMonitoring** 

```
- (void)setNetworkMonitor {
WeakSelf;
AFNetworkReachabilityManager *manager = [AFNetworkReachabilityManager sharedManager];
[manager setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {
    //当网络状态发生变化时会调用这个block
    switch (status) {
        case AFNetworkReachabilityStatusReachableViaWiFi:
            LogInfo(@"WiFi");
            weakSelf.requestSerializer.cachePolicy = NSURLRequestUseProtocolCachePolicy;
            break;
        case AFNetworkReachabilityStatusReachableViaWWAN:
            LogInfo(@"手机网络");
            weakSelf.requestSerializer.cachePolicy = NSURLRequestUseProtocolCachePolicy;
            break;
        case AFNetworkReachabilityStatusNotReachable:
            LogInfo(@"没有网络");
            weakSelf.requestSerializer.cachePolicy = NSURLRequestReturnCacheDataElseLoad;
            break;
        case AFNetworkReachabilityStatusUnknown:
            LogInfo(@"未知网络");
            weakSelf.requestSerializer.cachePolicy = NSURLRequestReturnCacheDataElseLoad;
            break;
        default:
            LogError(@"其他网络");
            weakSelf.requestSerializer.cachePolicy = NSURLRequestUseProtocolCachePolicy;
            break;
    }
}];
}
```

**question is that when i call a post request with success. I open flight mode with wifi closing. i just get the last success response.**

**Comment by skyline75489** [comment]
You should know that `cachePolicy` is not something that can alter on the fly. It's only useful for creating `NSURLRequest`.
