### ISSUE TITLE
about response json value

### ISSUE THREAD

**Issue by tianzhihen521** [AFNetworking/AFNetworking#3773]
I use this code.

`self.httpManager.responseSerializer = [AFJSONResponseSerializer serializer];`

    NSURLSessionDataTask *task = [self.httpManager POST:url parameters:[request requestPostParams] progress:^(NSProgress * _Nonnull uploadProgress) {
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        request.responseObject = responseObject;
        [self handlerResultWithOperation:task];
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        [self handlerResultWithOperation:task];
    }];

This url response value is JSON format.
But the response contentType is   "text/html; charset=UTF-8";   
Then this request  faild. ( contentType error. )
I know the contentType must be "application/json".
But i think you should try a  JSON parse , and if get right result ,you should ignore the contentType.

I do not know what I think is right.
Looking forward to reply.

**Comment by skyline75489** [comment]
This doesn't make sense. Content-Type should always be respected.

**Comment by flexih** [comment]
@tianzhihen521 
@interface AFHTTPResponseSerializer 
@property (nonatomic, copy, nullable) NSSet <NSString *> *acceptableContentTypes;

is what you need
