### ISSUE TITLE
Do not save downloaded file upon failure response

### ISSUE THREAD

**Issue by skyline75489** [AFNetworking/AFNetworking#3775]
The implementation [here](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLSessionManager.m#L297) in `AFURLSessionManager` saves downloaded file immediately after `didFinishDownloadingToURL` delegate method gets called. However, this delegate method will gets called even server returns error response like `500`. If there is such a failure response saved to destination path, the following attempt to save to the same path will all fail because `moveItemAtURL` doesn't overwrite. Thus the effort of retrying will be in vain.

**Comment by lancy** [comment]
Maybe another solution is remove the exist file before `moveItemAtURL`.

**Comment by skyline75489** [comment]
Or just use `replaceItemAtURL`, which also makes sense to me.
