### ISSUE TITLE
The operation couldn’t be completed. (NSURLErrorDomain error -1004.)

### ISSUE THREAD

**Issue by zhumeiteng** [AFNetworking/AFNetworking#3779]
little-probability,

I have setTimeoutInterval ,but it is still not solve.

**Comment by techrishdev** [comment]
Me too have same problem. Please, is there have any solution for this?

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
