### ISSUE TITLE
Why this networking framework can't support the request of synchronous?

### ISSUE THREAD

**Issue by yrx0910** [AFNetworking/AFNetworking#3780]
Why this networking framework can't support the request of synchronous?

**Comment by tewha** [comment]
https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/CommonPitfalls/CommonPitfalls.html#//apple_ref/doc/uid/TP40010220-CH4-SW9

**Comment by yrx0910** [comment]
@tewha Thanks! As letting users have good experience for our Apps ,we need avoid synchronous networking calls on the main thread .But asynchronous networking can let persons, using this framework, to operation.If this framework has synchronous and asynchronous networking , They can use this framework more free.For example,they can use synchronous networking by GCD  as asynchronous.If there has A,B,C or more things to do,which the latter depends on the former,we need to nest our codes after success.I think this is terrible.

**Comment by tewha** [comment]
If you're confident with synchronous networking off the main thread, you can wrap the asynchronous calls in a synchronous category into AFHTTPSessionManager pretty easily. Use a semaphore in each of those wrapping methods to determine when success or failure is called, then wait on the semaphore in the main function body.

I used something like this (though *this* code is untested):

ServiceResult.h:

	@interface ServiceResult : NSObject
	@property (nonatomic, readwrite, assign) NSInteger statusCode;
	@property (nonatomic, readwrite, copy) NSDictionary *responseObject;
	@property (nonatomic, readwrite, copy) NSError *error;
	@end

Then add the synchronous methods:

	@interface AFHTTPSessionManager(synchronous)

	- (ServiceResult *)GET:(NSString *)path
				parameters:(id)parameters
					 error:(NSError **)error;

	@end

Finally, add the implementations:

	@implementation AFHTTPSessionManager(synchronous)

	- (void)setupResult:(ServiceResult *)result task:(NSURLSessionTask *)task responseObject:(id)responseObject error:(NSError *)error {
		NSURLResponse *genericResponse = task.response;
		NSHTTPURLResponse *httpResponse = [genericResponse isKindOfClass:[NSHTTPURLResponse class]] ? (NSHTTPURLResponse *)genericResponse : nil;
		result.statusCode = httpResponse.statusCode;
		result.responseObject = responseObject;
		result.error = nil;
	}

	- (ServiceResult *)GET:(NSString *)path
				parameters:(id)parameters
					 error:(NSError **)error
	{
		NSAssert(![NSThread isMainThread], @"Synchronous API is only supported on secondary threads.");
	
		ServiceResult *result = [[ServiceResult alloc] init];
		dispatch_semaphore_t wait = dispatch_semaphore_create(0);
		[self GET:path parameters:parameters success:^(NSURLSessionTask *task, id responseObject) {
			[self setupResult:result task:task responseObject:responseObject error:nil];
			dispatch_semaphore_signal(wait);
		} failure:^(NSURLSessionTask *task, NSError *error) {
			[self setupResult:result task:task responseObject:nil error:error];
			dispatch_semaphore_signal(wait);
		}];
		dispatch_semaphore_wait(wait, DISPATCH_TIME_FOREVER);
	
		if (result.error) {
			if (error) *error = result.error;
			return nil;
		}
		return result;
	}

	@end

**Comment by yrx0910** [comment]
@tewha Thank you!

**Comment by yrx0910** [comment]
@tewha I sorry to ask you again! It is good to use like above!

_- (ServiceResult *)GET:(NSString *)path
            parameters:(id)parameters
                 error:(NSError **)error
{
    NSAssert(![NSThread isMainThread], @"Synchronous API is only supported on secondary threads.");

    ServiceResult *result = [[ServiceResult alloc] init];
    dispatch_semaphore_t wait = dispatch_semaphore_create(0);
    [self GET:path parameters:parameters success:^(NSURLSessionTask *task, id responseObject) {
        [self setupResult:result task:task responseObject:responseObject error:nil];
        dispatch_semaphore_signal(wait);
    } failure:^(NSURLSessionTask *task, NSError *error) {
        [self setupResult:result task:task responseObject:nil error:error];
        dispatch_semaphore_signal(wait);
    }];
    dispatch_semaphore_wait(wait, DISPATCH_TIME_FOREVER);

    if (result.error) {
        if (error) *error = result.error;
        return nil;
    }
    return result;
}_

**Comment by tewha** [comment]
If this creates a circular reference due to the use of `self` in the completion blocks (again, I did something *like* this but not exactly this) you might have to move the `setupResult` method to `ServiceResult` instead. I really should write this category, test it, and make it available. One day when I have some spare time. :)

**Comment by yrx0910** [comment]
Thanks!!!

**Comment by paulmelnikow** [comment]
Hey all, I wrote this for AFN 1.x back in the day, and recently added tests and updated it for 3.x:

https://github.com/paulmelnikow/AFNetworking-Synchronous

**Comment by paulmelnikow** [comment]
@tewha If you have any suggestions on how to make it safer, let me know!
