### ISSUE TITLE
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)"

### ISSUE THREAD

**Issue by yocheved-check-in** [AFNetworking/AFNetworking#3782]
my post method:

AFHTTPSessionManager *manager = [[AFHTTPSessionManager alloc]init];
    manager.responseSerializer = [AFJSONResponseSerializer
                                            serializerWithReadingOptions:NSJSONReadingAllowFragments];
    NSString *URL = [NSString stringWithFormat:@"%@%@", [self BaseUrl], urlString] ;
    [manager POST:URL parameters:parameters progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        NSLog(@"success!");
        completionBlock(YES,responseObject);
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@"error: %@", error);
        completionBlock(NO,error);
    }];

failed with those error...
any idea?

**Comment by shantj** [comment]
me too...

**Comment by whn1221** [comment]
me too ,Can you tell me how to solve this problem?

**Comment by guoranliaoran** [comment]
You should check out `AFJSONResponseSerializer`, and you will find it doesn't work. You should You need to try another way by Using `HTTPRequestOperationWithRequest` .You can contact me for more help or [JianShu](http://www.jianshu.com/users/f4d7a9533f5b/latest_articles)

**Comment by yocheved-check-in** [comment]
I just remove it from the pod file and adding it again.
the problem was solved...

Quoting Elwin <notifications@github.com>:

**Comment by yocheved-check-in** [comment]
I just remove it from the pod file and adding it again.
it is solve the problem...
