### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by yanjinquan** [AFNetworking/AFNetworking#3785]
when i update version to 3.1.0,my old function crashed,
```
    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    manager.responseSerializer = [AFHTTPResponseSerializer serializer];
    [manager POST:@"http://xxxxxxx:xxxx/home/user/login" parameters:@{@"name": @"kk"} progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {  
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
    }];
```
and the error say that : 
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AFHTTPSessionManager POST:parameters:progress:success:failure:]: unrecognized selector sent to instance `

**Comment by unregisteredrea** [comment]
Same issue. After updated to AFNetworking version 3.1.0 old working function crashed with this error:

`-[NSProxy doesNotRecognizeSelector:response] called!`

The debugger stop at line 308 of file AFURLSessionManager.h:

```
            dispatch_group_async(manager.completionGroup ?: url_session_manager_completion_group(), manager.completionQueue ?: dispatch_get_main_queue(), ^{
                if (self.completionHandler) {
                    // EXCEPTION
                    self.completionHandler(task.response, responseObject, serializationError); 
                }

                dispatch_async(dispatch_get_main_queue(), ^{
                    [[NSNotificationCenter defaultCenter] postNotificationName:AFNetworkingTaskDidCompleteNotification object:task userInfo:userInfo];
                });
            });
```

**Comment by unregisteredrea** [comment]
In my case AFNetworking is conflicted with a pod named CrittercismSDK v5.6.3. After remove that pod or downgrade to version 5.6.2 everything is OK

**Comment by yanjinquan** [comment]
Thank you ,i had solved that With delete the file "~~~/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/AFNetworking"
@unregisteredrea
