### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by codesourse** [AFNetworking/AFNetworking#3787]
![image](https://cloud.githubusercontent.com/assets/6462119/20336419/d2249b52-ac04-11e6-8876-37a8f8283041.png)

    AFHTTPSessionManager *manager=[AFHTTPSessionManager manager];
    [manager setSessionDidBecomeInvalidBlock:^(NSURLSession * _Nonnull session, NSError * _Nonnull error) {
        
    }];
    manager.completionQueue=dispatch_get_main_queue();
    manager.responseSerializer.acceptableContentTypes= [NSSet setWithObjects:@"text/html", nil];
    manager.responseSerializer=[AFHTTPResponseSerializer serializer];

**Comment by tewha** [comment]
Leaks are attributed to where an object is created, not where it is leaked. You should be looking for where you leak these objects, not where you allocate them.

**Comment by tewha** [comment]
I see in Apple's headers that `NSURLSession` maintains a strong reference to the delegate, which might explain this. I don't think that makes this an AFNetworking leak, though, just makes it important that you don't casually drop an `AFHTTPSessionManager`. Does this help?

https://github.com/AFNetworking/AFNetworking/issues/1528
