### ISSUE TITLE
HTTP POST consistently crashing/hanging on WatchOS

### ISSUE THREAD

**Issue by grahamparks** [AFNetworking/AFNetworking#3788]
The following code to do a simple HTTP POST consistently either crashes (or hangs without result) on WatchOS (3.1). The same code works as expected on iOS (10.1.1). I'm using AFNetworking 3.1 and Xcode 8.1.

```
    manager = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:@"https://www.apple.com/"]];
    
    [manager POST:@"/" parameters:nil constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
        NSLog(@"ConstructingBody");
        
        [formData appendPartWithFormData:[@"foo" dataUsingEncoding:NSUTF8StringEncoding] name:@"bar"];
        
    } progress:^(NSProgress * _Nonnull uploadProgress) {
        NSLog(@"Progress %@", uploadProgress);
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        NSLog(@"Success %@", responseObject);
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@"Failure %@", error);
    }];

```
The stack trace is always this:
```
#0	0x016705e7 in _CFStreamSetDispatchQueue ()
#1	0x0168bc81 in CFReadStreamSetDispatchQueue ()
#2	0x035e29bc in -[__NSCFBackgroundDataTask _onqueue_captureStream:] ()
#3	0x035e2bc2 in __70-[__NSCFBackgroundDataTask _onqueue_needNewBodyStream:withCompletion:]_block_invoke_2 ()
#4	0x03ddbc4f in _dispatch_call_block_and_release ()
#5	0x03dfe50f in _dispatch_client_callout ()
#6	0x03de2d82 in _dispatch_queue_serial_drain ()
#7	0x03de3570 in _dispatch_queue_invoke ()
#8	0x03de5304 in _dispatch_root_queue_drain ()
#9	0x03de511c in _dispatch_worker_thread3 ()
#10	0x0417bd6e in _pthread_wqthread ()
#11	0x0417b91a in start_wqthread ()
```

After various debugging I traced it as far as the call to `-[NSURLSession uploadTaskWithStreamedRequest:]`. Replacing this with a non-streamed variant of the call (and converting the stream to NSData ahead of time) works perfectly.

Interestingly, Apple's documentation for this method says _"The previously set body stream of the request (if any) is ignored and the URLSession:task:needNewBodyStream: delegate will be called when the body payload is required"_. Even with much hacking around, I have never seen this delegate method being called (even on iOS, where the code works) and the HTTPBodyStream parameter appears to be what's being used.

I feel this may be an Apple bug, and I think I've hit a brick wall as far as debugging / fixing it. Any thoughts?

**Comment by SlaunchaMan** [comment]
Are you still experiencing this?
