### ISSUE TITLE
Carthage is not using AFNetworking.framework.zip

### ISSUE THREAD

**Issue by veeamd** [AFNetworking/AFNetworking#3789]
Hi,
I'm using Carthage 1.18.1, and XCode 8.1.
You guys are so nice that you support Carthage, but carthage is not using the zipped framework attached with the release, it's compiling the framework after checking out.
We are also using CircleCI for builds, if carthage can use the downloaded framework directly this will saves a lot building time. This should be a very easy fix, hope you guys can fix it.
Thanks,

Wei

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
