### ISSUE TITLE
 Why CFData don't release  in red rect , I need your help,please!

### ISSUE THREAD

**Issue by fengli12321** [AFNetworking/AFNetworking#3790]
![group1111](https://cloud.githubusercontent.com/assets/19203612/20418654/c079927c-ad8a-11e6-9bb6-bfb686ce7330.png)
In my project, I upload pictures by AFNetworing 3.0,but why CFData don't release  in red rect , I need your help,please!

**Comment by jenny0616** [comment]
??

**Comment by jenny0616** [comment]
You can do it by yourself. Think of it more.

**Comment by doublecheese** [comment]
How do you release it? Instead of just saying you can do it yourself, why don't you give a solution!

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).

**Comment by fengli12321** [comment]
I have resolved my problem,Thanks anyway!
