### ISSUE TITLE
A slight clerical error at AFHTTPSessionManager

### ISSUE THREAD

**Issue by lovesunstar** [AFNetworking/AFNetworking#3791]
// Ensure terminal slash for baseURL path, so that NSURL +URLWithString:relativeToURL: works as expected
    if ([[url path] length] > 0 && ![[url absoluteString] hasSuffix:@"/"]) {
        url = [url URLByAppendingPathComponent:@""];
        // should be  
        url = [url URLByAppendingPathComponent:@"/"];
    }

**Comment by skyline75489** [comment]
Actually it's working with `@""`.
