### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=3840 when pass param in Dictionary

### ISSUE THREAD

**Issue by Hoangtaiki** [AFNetworking/AFNetworking#3795]
I have an API to login. 
When I try to use AFNetworking POST to log and all parameters I store in a dictionary:

NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
    AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];

    NSString *urlSearch = @"http://124.158.5.133:8186/api/login";
    NSDictionary *dic = @{
                          @"lang_code":@"vi",
                          @"mobile": @"84901111580",
                          @"password": @"oppp"};
    NSMutableURLRequest *req = [[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:urlSearch parameters:dic error:nil];

    NSLog(@"Request : %@",req);

    req.timeoutInterval= [[[NSUserDefaults standardUserDefaults] valueForKey:@"timeoutInterval"] longValue];
    [req setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    [req setValue:@"application/json" forHTTPHeaderField:@"Accept"];
    manager.responseSerializer = [AFJSONResponseSerializer serializerWithReadingOptions:NSJSONReadingAllowFragments];

    AFJSONResponseSerializer *responseSerializer = [AFJSONResponseSerializer serializerWithReadingOptions:NSJSONReadingAllowFragments];
    [manager setResponseSerializer:responseSerializer];

    NSURLSessionDataTask *dataTask = [manager dataTaskWithRequest:req completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {

        if (!error) {
            NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse*)response;
            if (httpResponse.statusCode == 200) {
                NSLog(@"Response: %@" , responseObject);
            }
        }
    }];

I get error:

Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}

But if I also use this api and apend all parameters in url

    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
    AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];

    NSString *urlt = [NSString stringWithFormat:@"http://124.158.5.133:8186/api/login?lang_code=%@&mobile=%@&password=%@, @"vi", @"84901111580", @"oppp"];

    NSMutableURLRequest *req = [[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:urlt parameters:nil error:nil];

    NSLog(@"Request : %@",req);

    req.timeoutInterval= [[[NSUserDefaults standardUserDefaults] valueForKey:@"timeoutInterval"] longValue];
    [req setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    [req setValue:@"application/json" forHTTPHeaderField:@"Accept"];
    manager.responseSerializer = [AFJSONResponseSerializer serializerWithReadingOptions:NSJSONReadingAllowFragments];

    AFJSONResponseSerializer *responseSerializer = [AFJSONResponseSerializer serializerWithReadingOptions:NSJSONReadingAllowFragments];
    [manager setResponseSerializer:responseSerializer];

    NSURLSessionDataTask *dataTask = [manager dataTaskWithRequest:req completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {

        if (!error) {
            NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse*)response;
            if (httpResponse.statusCode == 200) {
                NSLog(@"Response: %@" , responseObject);
            }
        }
    }];

I will get true JSON:

{
    "status": {
        "code": "200",
        "message": "Đăng nhập thành công."
    },
    "data": {
        "info": {
            "code": 3,
            "id": "57f4aa07781ecf7771ef4543",
            "mobile": 84901111580,
            "username": "84901111580",
            "name": null,
            "email": "",
            "gender": 0,
            "birthday": "",
            "avatar": "http://124.158.5.133:8182/filemanager/57f4aa07781ecf7771ef4543/avatar.jpg",
            "packages": {
                "PHIM": {
                    "status": 1,
                    "status_charge": 0,
                    "channel_code": 0,
                    "channel": "SYSTEM",
                    "date_register_first": {
                        "sec": 1479954573,
                        "usec": 604000
                    },
                    "date_register": {
                        "sec": 1479954573,
                        "usec": 604000
                    },
                    "date_deactive_first": null,
                    "date_deactive": null,
                    "date_charge": null,
                    "auto_renew": 1,
                    "retry": 0,
                    "date_expire": {
                        "sec": 1480179599,
                        "usec": 0
                    },
                    "donate_num_free": 0
                }
            }
        },
        "token": ""
    }
}

Someone can tell me why I get this problem? Maybe it is a AFnetworking bug?

**Comment by guoranliaoran** [comment]
You should check out `AFJSONResponseSerializer`, and you will find it doesn't work. You should You need to try another way by Using `HTTPRequestOperationWithRequest`.You can contact me for more help by [email:](hnsptlx@gmail.com)
