### ISSUE TITLE
Migration from 2.0 ->3.1.1

### ISSUE THREAD

**Issue by iHunterX** [AFNetworking/AFNetworking#3798]
Hi guys i have to maintain an app that i didnt write the code

They used AFNetworking 2.0 and another just upgrade the AFNetworking to 3.0
Can you guys help me to migrate those code to 3.0? 

`
AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:request];
        // 保存先指定
        operation.outputStream = [NSOutputStream outputStreamToMemory];
        operation.responseSerializer.acceptableContentTypes = [NSSet setWithObjects:ImageMimeTypeName, nil];

        [operation setCompletionBlockWithSuccess:^(AFHTTPRequestOperation *retOperation, id responseObject) {
            NSData *imageData = retOperation.responseData;
            UIImage *image =[[UIImage alloc] initWithData:imageData];
            // ダウンロードデータ記録
            _collectionCellInfo[no][@"image"] = image;
            [self singleRequest:requests withNo:no + 1];
        } failure:^(AFHTTPRequestOperation *retOperation, NSError *error) {
            [MKOLogger log:self.class level:SFLogLevelError format:@"写真のダウンロード失敗:",error.localizedDescription];
            // 成功しても失敗しても呼び出す。
            [self singleRequest:requests withNo:no + 1];
        }];
        [operation start];
`
I cant find the AFHTTPRequestOperation anywhere thanks for your help.

**Comment by iDevelopper** [comment]
https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide#afnetworking-2x-1

**Comment by zhangfurun** [comment]
but version 2.0 , we can use "retOperation.responseData", so in 3.0, can't get ,or other method
