### ISSUE TITLE
downloadTaskWithRequest creates a file even in case of error

### ISSUE THREAD

**Issue by vikram-gupta** [AFNetworking/AFNetworking#3799]
In case the URL provided to `downloadTaskWithRequest` does not exist, a file gets created with the error message as the content. 

Is there a way to avoid creation of this error file to save some time and space? We can obviously delete these files by checking the error in the `completionHandler` but it would be good to avoid this unnecessary IO operation.

```
NSURLSessionDownloadTask *downloadTask = [afUrlSessionManager downloadTaskWithRequest:request progress:nil destination:^NSURL *(NSURL *targetPath, NSURLResponse *response) {
        return destinationUrl;
    } completionHandler:^(NSURLResponse *response, NSURL *filePath, NSError *error) {
        NSLog(@"AssetDownloader:Asset downloaded to: %@", [destinationUrl path]);
    }];
    [downloadTask resume];
```

**Comment by skyline75489** [comment]
I think this is the same as #3775 .

**Comment by vikram-gupta** [comment]
@skyline75489 Yes its the same! Thanks for pointing. I think deleting or replacing the files is the best option for now.
