### ISSUE TITLE
Authorization Header Error - Not setting Authorization header in request

### ISSUE THREAD

**Issue by UnitSol** [AFNetworking/AFNetworking#3805]
Hi All,

I facing issue of sending post header Authorization field like:
`AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
        manager.responseSerializer = [AFHTTPResponseSerializer serializer];
        
        AFJSONRequestSerializer *requestSerializer = [AFJSONRequestSerializer serializer];
        manager.requestSerializer = requestSerializer;
        
        [manager.requestSerializer setValue:@"LoginToken jbEHn8LBhIidKyGfpitslFvW8IIcyabS0LCoxHmNdV2GOdD162lGlZgF3IlE"
                         forHTTPHeaderField:@"Authorization"];`

I got this Error:
Error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x170037aa0> { URL: http://ip:port/get_settings } { status code: 404, headers {
    "Access-Control-Allow-Headers" = "Content-Type";
    "Access-Control-Allow-Methods" = "OPTIONS,GET,PUT,POST,DELETE";
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 21;
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Thu, 01 Dec 2016 19:26:36 GMT";
    Etag = "W/\"15-myOuc/WzKwDBZ6gilXw65w\"";
    "X-Powered-By" = Express;
} }, NSErrorFailingURLKey=http://ip:port/get_settings, com.alamofire.serialization.response.error.data=<536f7272 79206361 6e742066 696e6420 74686174 21>, NSLocalizedDescription=Request failed: not found (404)}

Kindly help me in setting Authorization Header.

Thanks

**Comment by guoranliaoran** [comment]
Do you want post json to sever with Authorization? I just encountered this problem, and just resolved.

**Comment by razvanpaul** [comment]
I know this topic is quite old, but I stumbled upon the same issue. My solution was to replace "Authorization" with "Token" or any other string. Apparently, the server has something with this specific key.

Furthermore, to get the header value of your key, just do: $_SERVER['HTTP_YOUR_KEY'] (the dashes, if any, are replaced with underscores).
