### ISSUE TITLE
Unable to get the download progress

### ISSUE THREAD

**Issue by fengyun911** [AFNetworking/AFNetworking#3806]
Adopting Afnetworking3.1.0  Progress is not executed

 NSMutableURLRequest *PDFRequest = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:self.PDFURL]];
    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    self.requestOperation=[manager downloadTaskWithRequest:PDFRequest progress:^(NSProgress * _Nonnull downloadProgress) {
        [[NSOperationQueue mainQueue] addOperationWithBlock:^{
      #  **_Here does not perform_**
            @strongify(self)
            [self updateProgress:downloadProgress];
         
        }];
    } destination:^NSURL * _Nonnull(NSURL * _Nonnull targetPath, NSURLResponse * _Nonnull response) {
        return [NSURL fileURLWithPath:self.tempPDFPath];
    } completionHandler:^(NSURLResponse * _Nonnull response, NSURL * _Nullable filePath, NSError * _Nullable error) {
        @strongify(self)
        [self displayPDFFile];
    }];
    [self.requestOperation resume];

**Comment by columbusLGEN** [comment]
I have the same problem, dude, do you fix it ? Thanks

**Comment by inputfuture** [comment]
same problem here
