### ISSUE TITLE
File missing from working copy

### ISSUE THREAD

**Issue by chungfk** [AFNetworking/AFNetworking#3807]
Hi, I'm not sure if I should post this here. I've just update from v2.6 -> 3.1.0. When i run my project, even though it doesn't crash, but I'm getting missing file warning for these files:

UIAlertView+AFNetworking.h
UIAlertView+AFNetworking.m
AFHTTPRequestOperationManager.h
AFHTTPRequestOperationManager.m
AFURLConnectionOperation.m
AFURLConnectionOperation.h

How can I eliminate all these warnings? I've tried cleaning project but it doesn't work.
I'm using Xcode 8.0, cocoa pod 1.1.0

**Comment by abhinay-balusu** [comment]
Hi @chungfk, I'm getting the same issue. Can you please help me with that?
