### ISSUE TITLE
AFURLSessionManager.discretionary = YES, unable to download

### ISSUE THREAD

**Issue by lionel-SF** [AFNetworking/AFNetworking#3809]
i meet an BUG which cost me a lot time. By set AFURLSessionManager.discretionary = YES doing an background download task, with DEBUG on my iPad connected with mac by lighting cable , the download task is OK.

However, when i disconnected iPad with mac, the download task do not start. 

i check the download thread, they were stop when iPad disconnected.

At end, i set AFURLSessionManager.discretionary = NO; EVERYTHING THING IS FIND.

Pls who can check weather  "AFURLSessionManager.discretionary = YES" for background download works good, on iOS 10.1.1; and OS 10.11.6

**Comment by lionel-SF** [comment]
AFURLSessionManager.discretionary = YES, unable to download, with lighting cable disconnected with mac

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
