### ISSUE TITLE
Hello,i have a question.

### ISSUE THREAD

**Issue by laughing25** [AFNetworking/AFNetworking#3812]
excuse me,in the afnet, Why AFNetworking maximum concurrency is set to 1

self.sessionConfiguration = configuration;
self.operationQueue = [[NSOperationQueue alloc] init];
self.operationQueue.maxConcurrentOperationCount = 1;

tks!

**Comment by icodebuster** [comment]
@laughing25 

Questions like this is probably best suited for [Stackoverflow](http://stackoverflow.com/). Use Github to track bugs and feature requests.

**Comment by skyline75489** [comment]
See #3720 for discussion.
