### ISSUE TITLE
Pod file 

### ISSUE THREAD

**Issue by qzc77** [AFNetworking/AFNetworking#3814]
develop MAC OS Program
Pod file :platform :ios, '8.0',how to write?

**Comment by icodebuster** [comment]
@qzc77 

Questions like this is probably best suited for [Stackoverflow](http://stackoverflow.com/). Use Github to track bugs and feature requests.

Refer this for getting started with [CocoaPods](https://guides.cocoapods.org/using/getting-started.html)
