### ISSUE TITLE
Request getting timed out or become very slow while downloading file using NSURLSessionDownloadTask

### ISSUE THREAD

**Issue by amirpervaiz086** [AFNetworking/AFNetworking#3816]
I found strange issue using AFINetworking for making simple get/post api calls. when I use NSURLSessionDownloadTask for downloading big files ranging from 300-1 GB, all other api's calls made by AFINetworing library seems to be slow down and some calls give request timed out exception. Api calls seemed to be choked down or throttled by network while downloading file aysnchronously. 

What could be issue? As I believe, in aysn calls bandwidth are shared not blocked by other calls. Kindly give me your insight over this issue. I am suing latest iOS 10.2 for testing.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
