### ISSUE TITLE
dispatch_group_async(manager.completionGroup ?: url_session_manager_completion_group(), manager.completionQueue ?: dispatch_get_main_queue(), ^{             if (self.completionHandler) {                 self.completionHandler(task.response, responseObject, error);             }              dispatch_async(dispatch_get_main_queue(), ^{                 [[NSNotificationCenter defaultCenter] postNotificationName:AFNetworkingTaskDidCompleteNotification object:task userInfo:userInfo];             });         });

### ISSUE THREAD

**Issue by 13428282503** [AFNetworking/AFNetworking#3821]
dispatch_group_async(manager.completionGroup ?: url_session_manager_completion_group(), manager.completionQueue ?: dispatch_get_main_queue(), ^{
            if (self.completionHandler) {
                self.completionHandler(task.response, responseObject, error);
            }
            dispatch_async(dispatch_get_main_queue(), ^{
                [[NSNotificationCenter defaultCenter] postNotificationName:AFNetworkingTaskDidCompleteNotification object:task userInfo:userInfo];
            });
        });

There are the following problems

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1833b1b90 objc_msgSend + 16
1  CoreFoundation                 0x183d6fc64 __CFBasicHashDrain + 276
2  CoreFoundation                 0x183c14c34 CFRelease + 256
3  CFNetwork                      0x184302538 HTTPHeaderDict::~HTTPHeaderDict() + 44
4  CoreFoundation                 0x183c14c34 CFRelease + 256
5  CFNetwork                      0x1842fee40 HTTPMessage::~HTTPMessage() + 152
6  CoreFoundation                 0x183c14c34 CFRelease + 256
7  CFNetwork                      0x1842fef7c URLRequest::~URLRequest() + 152
8  CoreFoundation                 0x183c14c34 CFRelease + 256
9  CFNetwork                      0x1844ad798 -[__NSCFURLSessionTask dealloc] + 420
10 CFNetwork                      0x184338cd0 -[__NSCFLocalSessionTask dealloc] + 424
11 Buyer                          0x100bcc6f8 __destroy_helper_block_152 (AFURLSessionManager.m:313)
12 libsystem_blocks.dylib         0x1837e18e8 _Block_release + 156
13 libdispatch.dylib              0x18378547c _dispatch_client_callout + 16
14 libdispatch.dylib              0x18378ab84 _dispatch_main_queue_callback_4CF + 1844
15 CoreFoundation                 0x183cf0d50 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
16 CoreFoundation                 0x183ceebb8 __CFRunLoopRun + 1628
17 CoreFoundation                 0x183c18c50 CFRunLoopRunSpecific + 384
18 GraphicsServices               0x185500088 GSEventRunModal + 180
19 UIKit                          0x188f02088 UIApplicationMain + 204
20 Buyer                          0x100a27ffc main (main.m:15)
21 libdyld.dylib                  0x1837b68b8 start + 4

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).

**Comment by apcui** [comment]
hello, have you solved this question? can you tell me how to fix it?
