### ISSUE TITLE
AFHTTPSessionManager GET method syntax error?

### ISSUE THREAD

**Issue by ShawnRong** [AFNetworking/AFNetworking#3822]
Here's my code
```
AFHTTPSessionManager *manger = [[AFHTTPSessionManager alloc] init];
[manger GET:requestUrl parameters:params progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {

} failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {

}];
```
I got two errors from Xcode.

1. `Unknown type name 'id'`

2. `Incompatible block pointer types sending 'void (^)(NSURLSessionDataTask * _Nonnull __strong, int)' to parameter of type 'void (^ _Nullable)(NSURLSessionDataTask * _Nonnull __strong, id  _Nullable __strong)'`.

Why is this happen?I had imported AFNetworking file in my header file.My Xcode version is 8.2,and AFNetworking version is 3.1.When I put this code snippet in my other project,there was no error.That was really confused me.Anyone can help?

[error_pic](http://imgur.com/a/eK6jQ)

**Comment by ShawnRong** [comment]
This issue had been resolved

**Comment by ntnmrndn** [comment]
@ShawnRong You can close it then  :) Bonus point if your post your solution here
