### ISSUE TITLE
3.0的AFHTTPSessionManager只能实现HTTPS自签名证书的访问么

### ISSUE THREAD

**Issue by imWalsh** [AFNetworking/AFNetworking#3823]
公司购买的CA认证证书，就上传文件不行，其他数据访问都可以，用 POST 方法upload总报server error (500) ，但是换回 AFHTTPRequestOperationManager就可以上传，困扰了两天了，头快炸了

**Comment by dabing1022** [comment]
把错误的详细信息贴出来，你的问题越快能得到解答。另外用英语会更快点:)
