### ISSUE TITLE
Cannot convert value of type '(AFMultipartFormData!) -> Void' to expected argument type '((AFMultipartFormData?) -> Void)!'

### ISSUE THREAD

**Issue by fatahzull** [AFNetworking/AFNetworking#3825]
I am trying to upload image using AFNetworking & swift 3.0, but i am getting error like below.
Any help will be appreciated. Thanks in advance.

        let url = "http://localhost:9000/api/content"
        
        var params = [
            "familyId":"10000",
            "contentBody" : "Some body content for the test application",
            "name" : "the name/title",
            "typeOfContent":"photo"
        ]

        let manager = AFHTTPRequestOperationManager()
        manager.post(
            url,
            parameters: params,
            constructingBodyWith: { (formData: AFMultipartFormData!) -> Void in
                formData.appendPartWithFileData(imageData!, name: "Photo", fileName: "photo.jpg", mimeType: "image/jpeg")
        },
            success: { (operation: AFHTTPRequestOperation?, responseObject: Any?) in
                
                self.onSuccess(
                    operation: operation!,
                    responseObject: responseObject! as AnyObject
                )
        },
            failure: { (operation: AFHTTPRequestOperation?, error) in
                print("Error 1: " + error!.localizedDescription)
                
                self.onFailure(operation: operation)
        })

![screen shot 2016-12-21 at 5 43 14 pm](https://cloud.githubusercontent.com/assets/3628888/21384424/7d54548e-c7a5-11e6-95bc-dc5cc4b35528.png)

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
