### ISSUE TITLE
How to get expiry date [valid to] from a certificate?

### ISSUE THREAD

**Issue by SenthilKumarPeriyasamy** [AFNetworking/AFNetworking#3826]
Hello Team, 
I would like to know how to get the expiry date of certificate . This is to check before doing cert pinning .  There are some ways to get using openssl, however I would like know if there is a way in iOS security API to get the expiry date of a certificate. 

Appreciate your input.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
