### ISSUE TITLE
 -[AFHTTPSessionManager GET:parameters:progress:success:failure:]: unrecognized selector sent to instance 0x6000001d2b10

### ISSUE THREAD

**Issue by Lisa1900** [AFNetworking/AFNetworking#3828]
cocoapod update 2.6 to 3.1 crash in -[AFHTTPSessionManager GET:parameters:progress:success:failure:]: unrecognized selector sent to instance 0x6000001d2b10
and   NSScanner: nil string argument

**Comment by skyline75489** [comment]
See [AFNetworking 3 Migration Guide](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide)

**Comment by hornet1990** [comment]
下面的方法解决了我的问题，你可以试一下.
1、由于Xcode4之后build放在系统的资源库隐藏起来了，所以打开终端 输入：“defaults write com.apple.finder AppleShowAllFiles TRUE killall Finder” 的命令 让隐藏的文件夹显示出来
2、然后点到桌面，在左上方的栏目里选择：前往－》个人－》资源库。资源库是半透明状的，你可以点右键，显示简介，然后找里面的developer。这个文件夹里面有个Xcode。点进去。你会发现一个名为：DerivedData的文件夹。把这个删除掉就可以了。
3、在终端中 pod install 这样就好了
4、记得 输入命令 “defaults write com.apple.finder AppleShowAllFiles FALSE killall Finder ” 将显示的隐藏文件 ，再隐藏回去
原因：pod的坑、苹果缓存的坑
