### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by sunnyzl** [AFNetworking/AFNetworking#3829]
When I run AFN on simulator,i find it had some memory leaks.But when I run it on my iPhone,it is not happend

**Comment by MarcSteven** [comment]
You should show more infos and then let some people help you to analyze

**Comment by sunnyzl** [comment]
![afn_leak](https://cloud.githubusercontent.com/assets/11400615/21874865/adc282bc-d8b2-11e6-955b-0fb146fe1174.png)

**Comment by ChiHoc** [comment]
I'm almost sure that it's an OS bug. I wrote a simple demo, and got the same issue.
![1](https://cloud.githubusercontent.com/assets/4478983/22136191/f6b3c0e2-df0d-11e6-90cc-1544f26766fd.png)

**Comment by tewha** [comment]
Doesn't the `[session method:^{[session method2];}]` pattern cause a circular reference?

**Comment by ChiHoc** [comment]
I don't think so. Because I've debugged with weak reference.

**Comment by K-Be** [comment]
[Here](http://stackoverflow.com/questions/21554987/nsurlsession-memory-leaks-occur-when-using-web-services-in-ios) very similar problem. 
They solved it by sending of `finishTasksAndInvalidate` to the session.  I don't think that it is a good idea, but may be we can recreate a instance of AFSessionManager (or the session)  then all tasks are completed.
