### ISSUE TITLE
Use cocopods pod 'AFNetworking', '~ > 3.0, appear the following error, how to solve

### ISSUE THREAD

**Issue by shanyulaile** [AFNetworking/AFNetworking#3832]
Use cocopods pod 'AFNetworking', '~ > 3.0, appear the following error, how to solve

    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    NSMutableDictionary *paramdic = [NSMutableDictionary dictionary];
    [paramdic setObject:self.monthstr forKey:@"A"];
    
    [paramdic setObject:@"41010000" forKey:@"B"];
    
    [paramdic setObject:@"161110094101795003" forKey:@"AC"];

    
    [manager POST:kgetmonthproductdataAPI parameters:paramdic progress:^(NSProgress * _Nonnull uploadProgress) {
        
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        
    }];

![2016-12-26 4 56 08](https://cloud.githubusercontent.com/assets/11886729/21479094/ae55cb40-cb8c-11e6-865b-2a2823b5029d.png)

**Comment by jonybur** [comment]
Hi shanyulaile, did you try deleting and reinstalling your pods?

**Comment by shanyulaile** [comment]
No delete and reinstall the my' pods

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
