### ISSUE TITLE
dyld: Library not loaded???

### ISSUE THREAD

**Issue by BrightBeacon** [AFNetworking/AFNetworking#3833]
dyld: Library not loaded: @rpath/AFNetworking.framework/AFNetworking
  Referenced from: /var/containers/Bundle/Application/5DD447EC-23C3-4AB5-9101-3FEDE929367A/BRTLocationEngineDemo-FF.app/BRTLocationEngineDemo-FF
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/5DD447EC-23C3-4AB5-9101-3FEDE929367A/BRTLocationEngineDemo-FF.app/Frameworks/AFNetworking.framework/AFNetworking: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/5DD447EC-23C3-4AB5-9101-3FEDE929367A/BRTLocationEngineDemo-FF.app/Frameworks/AFNetworking.framework/AFNetworking'
(lldb) 

I just copy AFNetworking.framework to my project, but what's this?can someone help me? Config Target -> Embed Frameworks just work with IOS8.x Devices , when build in IOS9.x Devices, Error Again!!!

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
