### ISSUE TITLE
Security issues in AFNetworking 3.1.0 when assessed with HP Fortify security assessment

### ISSUE THREAD

**Issue by KGouthaman** [AFNetworking/AFNetworking#3835]
Hi Team,
When we did a security assessment using HP Fortify we got the following issues in AFNetworking Library
1. Unreleased Resource: Streams
Class: AFURLRequestSerialization.m
Method: initWithURLRequest:stringEncoding:

The function initWithURLRequest:stringEncoding:() in AFURLRequestSerialization.m sometimes fails to release a system resource allocated by initWithStringEncoding:() on this line.
   self.bodyStream = [[AFMultipartBodyStream alloc] initWithStringEncoding:encoding];
The identified function sometimes fails to release a system resource.

Kindly look into this issue and let me know the resolution.

Thanks

**Comment by limcheepei** [comment]
We also face the same issue with Fortify scan (rated as High). Any plan for fixing this issue?

**Comment by tewha** [comment]
How does it explain that? That assignment is to a strong instance variable.

**Comment by tewha** [comment]
So I looked at the code, and I'm sort of suspicious of this:

```
    __block AFStreamingMultipartFormData *formData = [[AFStreamingMultipartFormData alloc] initWithURLRequest:mutableRequest stringEncoding:NSUTF8StringEncoding];
```

Anyone know why that would be `__block`? There's no inline block.
