### ISSUE TITLE
[AFURLSessionManagerTaskDelegate init] crash

### ISSUE THREAD

**Issue by ck00031** [AFNetworking/AFNetworking#3836]
I got a crash in AFURLSessionManager.h, but i have no idea what happen, there is crash report below and i use singleton to implement afnetworking, could anybody help me to resolve this problem, thanks~

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x185eae808 object_isClass + 28
1  Foundation                     0x187e5a268 -[NSObject(NSKeyValueObserverNotification) willChangeValueForKey:] + 328
2  Foundation                     0x18807aba8 -[NSProgress _setValueForKeys:settingBlock:] + 276
3  Foundation                     0x18807aef8 -[NSProgress setTotalUnitCount:] + 124
4  Dramaster6                     0x100314254 -[AFURLSessionManagerTaskDelegate init] (AFURLSessionManager.m:138)
5  Dramaster6                     0x100317748 -[AFURLSessionManager addDelegateForDataTask:uploadProgress:downloadProgress:completionHandler:] (AFURLSessionManager.m:621)
6  Dramaster6                     0x1003186f8 -[AFURLSessionManager dataTaskWithRequest:uploadProgress:downloadProgress:completionHandler:] (AFURLSessionManager.m:771)
7  Dramaster6                     0x1003185c8 -[AFURLSessionManager dataTaskWithRequest:completionHandler:] (AFURLSessionManager.m:756)
8  Dramaster6                     0x10024de90 -[CLVideoParser parseYoutubeUseLambdaWithUrl:videoType:responseBlock:] (CLVideoParser.m:231)
9  Dramaster6                     0x1000f8670 -[CTPreRollTableViewCell playCenterVideo] (CTPreRollTableViewCell.m:219)
10 Dramaster6                     0x1000b7050 -[CTHomeTableViewController tableView:willDisplayCell:forRowAtIndexPath:] (CTHomeTableViewController.m:641)
11 UIKit                          0x18d60448c -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 900
12 UIKit                          0x18d604604 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 80
13 UIKit                          0x18d5f1bac -[UITableView _updateVisibleCellsNow:isRecursive:] + 2304
14 UIKit                          0x18d609668 -[UITableView _performWithCachedTraitCollection:] + 116
15 UIKit                          0x18d3a5b14 -[UITableView layoutSubviews] + 176
16 UIKit                          0x18d2be54c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1196
17 QuartzCore                     0x18a78640c -[CALayer layoutSublayers] + 148
18 QuartzCore                     0x18a77b0e8 CA::Layer::layout_if_needed(CA::Transaction*) + 292
19 QuartzCore                     0x18a77afa8 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
20 QuartzCore                     0x18a6f7c64 CA::Context::commit_transaction(CA::Transaction*) + 252
21 QuartzCore                     0x18a71f0d0 CA::Transaction::commit() + 512
22 QuartzCore                     0x18a71faf0 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 120
23 CoreFoundation                 0x1874257dc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
24 CoreFoundation                 0x18742340c __CFRunLoopDoObservers + 372
25 CoreFoundation                 0x18742389c __CFRunLoopRun + 1024
26 CoreFoundation                 0x187352048 CFRunLoopRunSpecific + 444
27 GraphicsServices               0x188dd5198 GSEventRunModal + 180
28 UIKit                          0x18d32c628 -[UIApplication _run] + 684
29 UIKit                          0x18d327360 UIApplicationMain + 208
30 Dramaster6                     0x100197d0c main (main.m:14)
31 libdispatch.dylib              0x1863345b8 (Missing)

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
