### ISSUE TITLE
A simple string as body, how to use

### ISSUE THREAD

**Issue by chenfanfang** [AFNetworking/AFNetworking#3841]
![snip20170107_9](https://cloud.githubusercontent.com/assets/13808962/21741194/a61fd854-d509-11e6-91db-528cd4faefd8.png)

**Comment by chenfanfang** [comment]
Methed is Patch

**Comment by rafaellage** [comment]
Hey, try something like this, wo

NSDictionary *body = @{"headPhotoUrl":url}; or NSDictionary *body = @"headPhotoUrl";
NSError *error;
NSData *jsonData = [NSJSONSerialization dataWithJSONObject:body options:0 error:&error];
NSString *jsonString = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];

AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];

NSMutableURLRequest *req = [[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:[NSString stringWithFormat:@"https://blah.com] parameters:nil error:nil];

req.timeoutInterval= 100.0;
[req setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
[req setValue:@"application/json" forHTTPHeaderField:@"Accept"];
[req setHTTPBody:[jsonString dataUsingEncoding:NSUTF8StringEncoding]];


[[manager dataTaskWithRequest:req completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {

    if (!error) {
        NSLog(@"Reply JSON: %@", responseObject);

        if ([responseObject isKindOfClass:[NSDictionary class]]) {
              //blah blah
        }
    } else {
        NSLog(@"Error: %@, %@, %@", error, response, responseObject);
    }
}] resume];

**Comment by skyline75489** [comment]
Github is not for technical support. Please consider asking a question on StackOverflow.
