### ISSUE TITLE
AFNetworking incorrectly retries a failed POST request

### ISSUE THREAD

**Issue by mengjang** [AFNetworking/AFNetworking#3842]
AFNetworking doesn't have built-in retry, and I don't add any retry code of my own.  However, I see retries happen incorrectly, when I use either Version 3.1.0 or the current master version (with default configuration).

 _manager = [AFHTTPSessionManager manager];
[_manager POST:@"my-url" parameters:params progress:nil success:success failure:failure];

I turn on Network Link Conditioner '100% loss' to create a timeout to test the failure block.  Then I kill the process of my app (by swiping it up from the multitasking app switcher screen), turn off Network Link Conditioner.  Then I see a POST request with the same body go through.

This incorrect retry issue doesn't arise when I implement the POST request with NSMutableURLRequest and NSURLSession, instead of AFNetworking.  It only arises with AFNetworking.

I'd appreciate an explanation or resolution of this issue.  Thanks.

**Comment by cmrocha** [comment]
I noticed this same issue recently.

**Comment by shoon** [comment]
We're seeing the same thing - our requests have a date parameter that the server will reject if too old. We're seeing random retries 10+ minutes after we build the request with the date.
