### ISSUE TITLE
iOS 10.2 [NSConcreteMutableData appendBytes:length:]: unable to allocate memory for length

### ISSUE THREAD

**Issue by Kinphi** [AFNetworking/AFNetworking#3844]
![image](https://cloud.githubusercontent.com/assets/4626564/21756110/ad72a8da-d657-11e6-9d52-45f0047df02a.png)

**Comment by PlayDevelop** [comment]
I have similar issue

**Comment by ddaddy** [comment]
Same here

**Comment by justin999** [comment]
same here

**Comment by SlaunchaMan** [comment]
Hard to say what’s going on from that screenshot; there isn’t any AFNetworking code there. Is this reproducible? If so, please re-open with more information.
