### ISSUE TITLE
Download a file not exist on server is succeed

### ISSUE THREAD

**Issue by elsenpan** [AFNetworking/AFNetworking#3845]
When download a file which does not exist on server, it is succeed to create file at destination location, but the file content is the error info about status code 404.
Following is the code snippet:

    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
    AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];
    
    NSURL *URL = [NSURL URLWithString:@"https://google.com/404.txt"];
    NSURLRequest *request = [NSURLRequest requestWithURL:URL];
    
    NSURLSessionDownloadTask *downloadTask = [manager downloadTaskWithRequest:request progress:nil destination:^NSURL *(NSURL *targetPath, NSURLResponse *response) {
        NSURL *documentsDirectoryURL = [[NSFileManager defaultManager] URLForDirectory:NSDocumentDirectory inDomain:NSUserDomainMask appropriateForURL:nil create:NO error:nil];
        return [documentsDirectoryURL URLByAppendingPathComponent:[response suggestedFilename]];
    } completionHandler:^(NSURLResponse *response, NSURL *filePath, NSError *error) {
        // content is error info
        NSString *content = [[NSString alloc] initWithData:[NSData dataWithContentsOfURL:filePath] encoding:NSUTF8StringEncoding];
        NSLog(@"File content: %@", content);
    }];
    [downloadTask resume];

This is not what i want, all i want is only create file at local when it does exist on server, not the wrong file as we only check if file exists to confirm we got the file.

I go through the code and find method '- (void)URLSession:(NSURLSession *)session
      downloadTask:(NSURLSessionDownloadTask *)downloadTask
didFinishDownloadingToURL:(NSURL *)location’ in ‘AFURLSessionManager.m’ file, it does not check if the response status code is 200, please let me know if this is a issue, or just i missed using the API.

Here is my versions for test:
The version of Xcode:8.1 (8B62)
The version of iOS: 10.1

At last, thank you for providing AFNetworking, it is really awesome.

**Comment by skyline75489** [comment]
This looks like a duplicate (and follow-up) of #3775 .

**Comment by elsenpan** [comment]
@skyline75489 Yes, it’s duplicate of #3775 ,so the issue is still there.
