### ISSUE TITLE
how to upload a big file with "PUT"

### ISSUE THREAD

**Issue by shantj** [AFNetworking/AFNetworking#3847]
i know how to upload a big file with "POST"
`- (NSURLSessionDataTask *)POST:(NSString *)URLString
                    parameters:(id)parameters
     constructingBodyWithBlock:(void (^)(id <AFMultipartFormData> formData))block
                      progress:(nullable void (^)(NSProgress * _Nonnull))uploadProgress
                       success:(void (^)(NSURLSessionDataTask *task, id responseObject))success
                       failure:(void (^)(NSURLSessionDataTask *task, NSError *error))failure`

but how to do it with "PUT"??

**Comment by Shin1122** [comment]
try to use "Creating an Upload Task for a Multi-Part Request, with Progress".
change "POST" with "PUT".
