### ISSUE TITLE
NSInternalInconsistencyException

### ISSUE THREAD

**Issue by yx-mike** [AFNetworking/AFNetworking#3848]
An instance 0x13c6d5cb0 of class __NSCFLocalDataTask was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x13db25fb0> ( <NSKeyValueObservance 0x13c537880: Observer: 0x13c6cd130, Key path: operationCount, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x13c537850> )

0 CoreFoundation	___exceptionPreprocess + 124
1 libobjc.A.dylib	objc_exception_throw + 56
2 CoreFoundation	-[NSException initWithCoder:]
3 Foundation	_NSKVODeallocate + 300
4 WDBuyerUniv	__destroy_helper_block_ (AFURLSessionManager.m:0)
5 libsystem_blocks.dylib	_Block_release + 156
6 libdispatch.dylib	__dispatch_client_callout + 16
7 libdispatch.dylib	_dispatch_main_queue_callback_4CF + 1844
8 CoreFoundation	___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
9 CoreFoundation	___CFRunLoopRun + 1628
10 CoreFoundation	CFRunLoopRunSpecific + 384
11 GraphicsServices	GSEventRunModal + 180
12 UIKit	UIApplicationMain + 204
13 libdyld.dylib	_start + 4

**Comment by 0xced** [comment]
This should be fixed in the upcoming 3.2.0 release thanks to #3718.

**Comment by yx-mike** [comment]
It crash on the main thread. Key path is 'operationCount'.
Maybe,  
![2017-01-17 16 26 27](https://cloud.githubusercontent.com/assets/4413224/22012994/bd6e9c50-dcd1-11e6-8b0b-9dc3f2dd8dee.png)
see this
