### ISSUE TITLE
UIImageView setImageWithURLRequest caching images even with NSURLRequestReloadIgnoringCacheData policy

### ISSUE THREAD

**Issue by tzzoug** [AFNetworking/AFNetworking#3852]
I am using the following code.

- (NSMutableURLRequest *)imageRequestWithURL:(NSURL *)url {
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
    [request addValue:@"image/*" forHTTPHeaderField:@"Accept"];
    [request setCachePolicy:NSURLRequestReloadIgnoringCacheData];
    return request;
}

[self.avatarImageView setImageWithURLRequest:urlRequest placeholderImage:[UBAppearance randomPlaceholderWithName:[user email] smallFormat:YES] success:nil failure:nil];

The reason I am doing this is because I don't want the image to be cached for this particular case.
However, it seems like the image is being cached nonetheless.

Thanks for any help.
Tzzoug

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
