### ISSUE TITLE
Post Plaint Text in Request Body

### ISSUE THREAD

**Issue by ansari-acacusgroup** [AFNetworking/AFNetworking#3853]
I am using AFHTTPSessionManager's POST method to send plaint text e.g. "Test String" in request body, but AFHTTPRequestSerializer turns it into a pair and sending text is converted into "=Test String".
`_path = @"http://mywebservice.com/api?v=1";`
`parameters = @"Test String";`
`  [sessionManager setRequestSerializer:[AFHTTPRequestSerializer serializer]];`
`  [sessionManager setResponseSerializer:[AFJSONResponseSerializer serializer]];`
`[sessionManager POST:_path`
`                  parameters:parameters`
`                    progress:nil`
`                     success:^(NSURLSessionDataTask *_Nonnull task,`
`                               id _Nullable responseObject) {`
`                         successBlock(responseObject);`
`                     }`
`                     failure:^(NSURLSessionDataTask *_Nullable task, NSError *_Nonnull error) {`
`                         failureBlock(error);`
`                     }];`

Is it possible to sent simple string in request body, not key value pairs using above technique.

**Comment by skyline75489** [comment]
If you need to post plain text, you may want to use `constructingBodyWithBlock`.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
