### ISSUE TITLE
Crash on com.apple.root.default-qos

### ISSUE THREAD

**Issue by prabhums** [AFNetworking/AFNetworking#3855]
My app crashing on com.apple.root.default-qos. As i have analysed my crash log, i found that the issue was caused by the AFNetworking library i have added to my project. How could i resolve this issue. I have attached a part of my crash log below for reference.
[crash_log.txt](https://github.com/AFNetworking/AFNetworking/files/710999/crash_log.txt)

**Comment by tewha** [comment]
Why do you think that's AFNetworking? It looks like you just failed to add privacy strings for iOS 10.

**Comment by prabhums** [comment]
yes thats an issue with privacy strings for iOS 10.
