### ISSUE TITLE
Issue for AFURLRequestSerialization

### ISSUE THREAD

**Issue by kinglezhuang** [AFNetworking/AFNetworking#3857]
} else if ([value isKindOfClass:[NSArray class]]) {
        NSArray *array = value;
        for (id nestedValue in array) {
            [mutableQueryStringComponents addObjectsFromArray:AFQueryStringPairsFromKeyAndValue([NSString stringWithFormat:@"%@[]", key], nestedValue)];
        }

should be @"[%@]", key]

**Comment by skyline75489** [comment]
This part of code doesn't seem to be covered by test cases. Perhaps this indeed is wrong. I think we need more investigation.

**Comment by aopod** [comment]
I think this part of code is right(At least in some cases). It generates url with list as queries. For example:

```
NSDictionary *parameters = @{
	@"list": @[@"value1", @"value2", @"value3"]
};
```
Above parameters will generate url like this:

`http://example.com/path?list[]=value1&list[]=value2&list[]=value3`

In this way list is usually regarded as an array in PHP. But some other languages may not.

**Comment by kinglezhuang** [comment]
For this case http://example.com/path?list[]=value1&list[]=value2&list[]=value3
server only can get the last value.

**Comment by aopod** [comment]
It depends. Different languages have different behaviours. Link below mentions something about this. 
http://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string

**Comment by SlaunchaMan** [comment]
If someone can point to a standard that defines this behavior, please open a new issue; as @aopod says, different backends will parse query parameters differently, so there’s no one answer here. Perhaps we could add a new option for this behavior—PRs are open!
