### ISSUE TITLE
testPolicyWithCertificatePinningAllowsHTTPBinOrgServerTrustWithEntireCertificateChainPinned is failing

### ISSUE THREAD

**Issue by gototen** [AFNetworking/AFNetworking#3859]
Certificate pinning tests in *Tests/Tests/AFNetworking Tests/AFSecurityPolicyTests.m*, such as testPolicyWithCertificatePinningAllowsHTTPBinOrgServerTrustWithEntireCertificateChainPinned, are failing with the assert:

```
Policy should allow HTTPBinOrg server trust because at least one of the pinned certificates is valid
```

**Comment by gototen** [comment]
This is blocking PRs.

**Comment by SlaunchaMan** [comment]
Should be fixed with my most recent PR.
