### ISSUE TITLE
`AFHTTPRequestSerializer` conforms to the `AFURLResponseSerialization` protocols

### ISSUE THREAD

**Issue by broccolii** [AFNetworking/AFNetworking#3860]
I see this comment in line 92 of [AFURLRequestSerialization.h](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLRequestSerialization.h#L92).

Is it wrong here❓
Or where I did not figure it out...

Please help me, thx

**Comment by skyline75489** [comment]
I think this is probably a typo.
