### ISSUE TITLE
Why not `copy` keyword modifier NSSet

### ISSUE THREAD

**Issue by broccolii** [AFNetworking/AFNetworking#3861]
I read the source ofAFNetworking , found in the [AFURLRequestSerialization.h line 203](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLRequestSerialization.h#L203)use of `Strong` to modify NSSet.

Why not `copy` keyword modifier NSSet

**Comment by aopod** [comment]
Doesn't need to, cause it's initialized in the -init method, and will not be changed.

**Comment by tewha** [comment]
`copy` is used to guarantee that if a mutable value is passed in, it won't mutate under the instance. The instance takes an immutable copy of it.

`copy` is probably appropriate here; if it's intended that nobody outside the class change its value, `readonly` might be appropriate instead.

Some insight into the intent would help here.
