### ISSUE TITLE
AFNetworking errors with more the 2 simultaneous connections

### ISSUE THREAD

**Issue by popularizan** [AFNetworking/AFNetworking#3863]
How many simultaneous connections can I make with AFNetworking 2.0 ?

I have errors when I make more than 2 simultaneous connections

**Comment by skyline75489** [comment]
AFNetworking 2.0  has already been deprecated. That being said, AFNetworking 2.0 should still work fine with simultaneous connections. Can you post some code?

**Comment by popularizan** [comment]
My main code is the following:

`if ([table1 all].count == 0) 
    [[NetworkController sharedInstance] downloadTable1WithCompletion:^(NSError *error) {
         if (error) NSLog(@"Downloading table1 error..."); else  NSLog(@"Downloading table1 ok...");
     }];

if ([table2 all].count == 0) 
    [[NetworkController sharedInstance] downloadTable2WithCompletion:^(NSError *error) {
         if (error) NSLog(@"Downloading table2 error..."); else  NSLog(@"Downloading table2 ok...");
     }];

if ([table3 all].count == 0) 
    [[NetworkController sharedInstance] downloadTable3WithCompletion:^(NSError *error) {
         if (error) NSLog(@"Downloading table3 error..."); else  NSLog(@"Downloading table3 ok...");
     }];

if ([table4 all].count == 0) 
    [[NetworkController sharedInstance] downloadTable4WithCompletion:^(NSError *error) {
         if (error) NSLog(@"Downloading table4 error..."); else  NSLog(@"Downloading table4 ok...");
     }];`

In table1, table2 Donwloading is ok
In table 3, table 4 Downloading is error
             
If I download the following table when I just downloaded the previous one then table1, table2, table3, table4 Downloading is ok

**Comment by iDevelopper** [comment]
It is rather the code of the singleton that should be shown.
