### ISSUE TITLE
HTTP2 memory leaks

### ISSUE THREAD

**Issue by zupper** [AFNetworking/AFNetworking#3864]
Problem also described here - http://stackoverflow.com/questions/42021075/http2-memory-leak-on-ios-10-2-with-afnetworking-3-1-0

* AFNetworking 3.1.0
* iOS 10.2
* nginx version: nginx/1.10.0 (Ubuntu 16.04.1)

We have an uploads web service, to which our application uploads files. We found a problem when we transitioned to HTTP2 - our application started crashing. After we investigated, we found that the application was running out of memory when uploading large video files (1GB+).

We performed several tests and we isolated the problem:

![screen shot 2017-02-03 at 11 23 58 am](https://cloud.githubusercontent.com/assets/1444508/22587524/a6df853a-ea0a-11e6-9325-640fc6bcbb73.png)

We ran the app, with HTTP2 enabled on the test server. We uploaded a video 2 times and observed the memory increase. After that, we disabled HTTP2 on the webserver, and re-uploaded the same  video (without restarting the app) - the memory stopped increasing.

We used Instruments and it seems that AFNetworking opens streams to read the body data, which then remain open indefinitely (or so it seems):

![screen shot 2017-02-03 at 12 07 04 pm](https://cloud.githubusercontent.com/assets/1444508/22587501/94d934e4-ea0a-11e6-8d71-aa37273babf9.png)

![screen shot 2017-02-03 at 12 08 59 pm](https://cloud.githubusercontent.com/assets/1444508/22587509/98ed2dd8-ea0a-11e6-8e05-52c6eb000a22.png)

**Comment by zupper** [comment]
Not really familiar with the lib architecture, but it seems that the resources that are used for a request don't get cleaned up immediately after. It seems to me that AFNetworking expects that the connection will have to be reopened for the next request, which seems to not happen with HTTP2 (by design, it reuses the same connection). As a result, all the allocated resources build up and are never freed, unless the used connection dies for some reason. However, by that time, the app has already crashed due to memory usage.

Again, not sure if the above is correct, since I am not very familiar with this project.

**Comment by tewha** [comment]
Have you got a test case that demonstrates this? I can see where the inputStraem is closed and deallocated here. Unless multiple ones are instantiated (there's no thread locking here?), I don't really see how that could leak. However, if your code were retaining the stream or data somehow, that might do it. Or it might be something totally different; I'm by no means an expert. :)

**Comment by zupper** [comment]
We have the following setup:

- We have an UploadManager class, which receives a list of files
- The manager then starts with the first file. It creates an instance of a reader class, designated to that file. Each file will get its own reader, and the readers are discarded after the file is read fully.
- The reader opens an input stream for the file, and reads the first 5MB chunk
- The read chunk is passed back to the UploadManager, which proceeds to upload it to the server. It uses the following implementation (we're uploading to a flow.js server):

```
+ (void)makeUploadRequestWithData:(NSData *)data
                         fileName:(NSString *)fileName
                         filePath:(NSURL *)filePath
               currentChunkNumber:(NSInteger)currentChunkNumber
                 currentChunkSize:(NSUInteger)currentChunkSize
                        totalSize:(long long)totalSize
                   numberOfChunks:(NSInteger)numberOfChunks
                           toPath:(NSString *)path
                           method:(NSString *)method
                          success:(UploadSuccessBlock)success
                          failure:(FailureBlock)failure {
    
    NSString *URLString = [self URLStringWithPath:path];

    NSMutableURLRequest *request = [[AFHTTPRequestSerializer serializer] multipartFormRequestWithMethod:method URLString:URLString parameters:nil constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        
        NSString *flowChunkNumber = [NSString stringWithFormat:@"%ld", (long)currentChunkNumber];
        NSData *payload = [flowChunkNumber dataUsingEncoding:NSUTF8StringEncoding];
        [formData appendPartWithFormData:payload name:@"flowChunkNumber"];
        
        NSString *flowChunkSize = [NSString stringWithFormat:@"%ld", (long)kChunkSize];
        NSData *payload1 = [flowChunkSize dataUsingEncoding:NSUTF8StringEncoding];
        [formData appendPartWithFormData:payload1 name:@"flowChunkSize"];
        
        NSString *flowCurrentChunkSize = [NSString stringWithFormat:@"%ld", (unsigned long)currentChunkSize];
        NSData *payload2 = [flowCurrentChunkSize dataUsingEncoding:NSUTF8StringEncoding];
        [formData appendPartWithFormData:payload2 name:@"flowCurrentChunkSize"];
        
        NSString *flowTotalSize = [NSString stringWithFormat:@"%lld", totalSize];
        NSData *payload3 = [flowTotalSize dataUsingEncoding:NSUTF8StringEncoding];
        [formData appendPartWithFormData:payload3 name:@"flowTotalSize"];
        
        NSString *flowTotalChunks = [NSString stringWithFormat:@"%ld", (long)numberOfChunks];
        NSData *payload4 = [flowTotalChunks dataUsingEncoding:NSUTF8StringEncoding];
        [formData appendPartWithFormData:payload4 name:@"flowTotalChunks"];
        
        NSString *flowFilename = fileName;
        NSData *payload5 = [flowFilename dataUsingEncoding:NSUTF8StringEncoding];
        [formData appendPartWithFormData:payload5 name:@"flowFilename"];
        
        [formData appendPartWithFileData:data name:@"file" fileName:flowFilename mimeType:@"application/octet-stream"];
        
    } error:nil];
    
    [request setValue:[LoginManager currentUserIdentifier].stringValue forHTTPHeaderField:@"TubeWay-Auth-UserId"];
    [request setValue:[LoginManager authenticationToken] forHTTPHeaderField:@"TubeWay-Auth-Token"];
    [request setValue:@([ClientsManager currentClientIdentifier]).stringValue forHTTPHeaderField:@"TubeWay-Active-Client-Id"];

    request.timeoutInterval = 120;
    
    AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];
    
    uploadTask = [manager
                  uploadTaskWithStreamedRequest:request
                  progress:^(NSProgress * _Nonnull uploadProgress) {
                      // This is not called back on the main queue.
                      // You are responsible for dispatching to the main queue for UI updates
                      dispatch_async(dispatch_get_main_queue(), ^{
                          //Update the progress view
                          for (id<UploadProgressObserver> observer in observers) {
                              [observer currentChunkProgress:uploadProgress.fractionCompleted];
                          }
                      });
                  }
                  completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
                      if (error) {
                          failure(error);
                      } else {
                          success(YES);
                      }
                  }];
    
    [uploadTask resume];
}
```

- After the upload completes, the UploadManager asks the reader for the next chunk
- When the last chunk is read, the input stream for that file is closed. _We maintain a reference to the reader, but that reference is kept within the file object, which gets discarded when the upload queue finishes._
- After all chunks for the first file are uploaded, the process is repeated for the next file
- After all files are uploaded, the queue with files to upload is cleared (we empty the array with the files pending for upload, and we have no further references to these objects, which gets rid of the readers for those files), and general cleanup is performed in preparation for the next upload.

We debugged `AFURLRequestSerialization.m`, setting a breakpoint in the `dealloc` method of the `AFHTTPBodyPart` class. When using HTTP1.1, the `dealloc` method gets called multiple times. When using HTTP2, this method never gets called. We observe this within the same session (no application restart) by switching HTTP2 on/off on the server. Also, to make a distinction between HTTP2 on/off, we create separate upload queues, so it goes like this:

- set the server to use HTTP1.1, create an upload queue - observe `dealloc` being called
- wait for the above to finish
- set the server to use HTTP2, create a new upload queue (no references to the old queue are maintained) - observe `dealloc` NOT being called.


Hope this is enough to help with sorting this issue. If you need anything more specific, I would be happy to provide more info.

**Comment by zupper** [comment]
Anyone interested in looking into this?

**Comment by doublecheese** [comment]
I am having the same issue too
