### ISSUE TITLE
UIWebView+AFNetworking - UIWebview loaddata error?

### ISSUE THREAD

**Issue by GopiK14** [AFNetworking/AFNetworking#3865]
Hi All,
I got a new error "No visible @interface for 'UIWebView' declares the selector 'loadData:MIMEType:textEncodingName:baseURL:'" in AFNetwork UIWebView+AFNetworking class, Please help me to resolve this? I can able to run in device. Same code runs in Simulator.

Thanks

**Comment by skyline75489** [comment]
It seems you have some compilation caching that needs to be cleared. Try clearing `DerivedData`.
