### ISSUE TITLE
AFnetworking Results not ordered same as POSTMAN ?

### ISSUE THREAD

**Issue by GopiK14** [AFNetworking/AFNetworking#3866]
Hi,
I am using below method to get response from server(using 3.0),

 AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    manager.requestSerializer = [AFJSONRequestSerializer serializer];
    [manager POST:url parameters:parameters constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
    } progress:^(NSProgress * _Nonnull uploadProgress) {
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        [MBProgressHUD hideHUDForView:[UIApplication sharedApplication].keyWindow.rootViewController.view animated:YES];
        NSLog(@"APi Success : %@",responseObject);
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@" APi Failed : %@",[error description]);
    }];

and I got a result but results not in same order as postman result. Why it differs from POSTMAN? Any idea? Please give some suggestion to over come order issue.

Thanks!

**Comment by skyline75489** [comment]
What "order" of result are you talking about here exactly?

**Comment by tewha** [comment]
I'm going to assume you're talking about the JSON object, i.e. `{"1":"a","2","b"}`.

The key-values in a JSON object are considered unordered, and `NSDictionary` (which is what Apple's JSON deserializer produces) does not maintain the order.

This is certainly inconvenient. There's a number of places I'd love to get JSON objects in a consistent order, like comparing test results. But if you need them in order, you'll have to get the dictionary's keys, sort them, and loop through the keys extracting values.
