### ISSUE TITLE
Two network requests simultaneously

### ISSUE THREAD

**Issue by Milker90** [AFNetworking/AFNetworking#3868]
I have two network requests for A and B, at the end of A, B is being prepared; then AFHTTPRequestSerializerObservedKeyPaths objects are removed, but the B request and need to use the AFHTTPRequestSerializerObservedKeyPaths object, need to use such as observeValueForKeyPath:ofObject in:change:context keyPath. Does anyone have such a problem?Thanks!

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
