### ISSUE TITLE
 send post request with xml body withafnetworking3x ？

### ISSUE THREAD

**Issue by zhangkn** [AFNetworking/AFNetworking#3875]
code：
nsstring *strXML=  "<?xml version='1.0' encoding='UTF-8'?>    <ROOT>    <HEAD>    <TXNCD>700000</TXNCD>";
    NSData * params = [strXML dataUsingEncoding:NSUTF8StringEncoding];

  // 1.创建请求管理对象     AFHTTPSessionManager
    
    AFHTTPSessionManager *mgr = [AFHTTPSessionManager manager];
    mgr.responseSerializer = [AFXMLParserResponseSerializer serializer];//返回数据以xml格式接收
    
    mgr.requestSerializer = [AFHTTPRequestSerializer serializer];
    [mgr.requestSerializer setValue:@"application/xml" forHTTPHeaderField:@"Content-Type"];

//    [mgr.requestSerializer setValue:@"application/xml" forHTTPHeaderField:@"Content-Type"];
//    [mgr.requestSerializer setValue:[NSString stringWithFormat:@"%zd", params.length] forHTTPHeaderField:@"Content-Length"];
    [mgr.requestSerializer setValue:@"gzip" forHTTPHeaderField:@"Accept-Encoding"];

    
   
    
//    mgr.responseSerializer.acceptableContentTypes = [NSSet setWithObject:@"application/xml"];
    
    mgr.responseSerializer.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript",@"text/html", nil];

 
    mgr.requestSerializer.stringEncoding = NSUTF8StringEncoding;
    // 设置超时时间
    mgr.requestSerializer.timeoutInterval = 30.f;
    
    
    
    
    [mgr POST:url parameters:params progress:^(NSProgress * _Nonnull uploadProgress) {
        
        
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        
        
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        
        
    }];

**Comment by skyline75489** [comment]
Github is not a place for technical support. If it's not a issue about the library itself, you should ask the question on StackOverflow.
