### ISSUE TITLE
Log multipart Post Request Body

### ISSUE THREAD

**Issue by mwaqasbhati** [AFNetworking/AFNetworking#3879]
I am working on a project, I have to use multipart form data some where in the app. I have to provide my request body to the backend guy, I did use AfNetworking logger to print my body but it is not logging my request body. 

By the way this is my request body.

                 
             NSDictionary *params = @{@"Name":self.textFieldTitle.text,
                                     @"DateCreated":self.textFieldDate.text,
                                     @"DateEnd":self.endTime,
                                     @"DateStart":self.startTime,
                                     @"Description":self.textFieldServiceRequired.text,
                                     @"Location":self.textFieldLocation.text,
                                     @"Status":@"1",
                                     @"PreferredGenres":@[@"1",@"2"],//[self.textFieldGenre.text componentsSeparatedByString:@","],
                                     @"PreferredSkills":@[@"1",@"2"],//[self.textFieldSkills.text componentsSeparatedByString:@","],
                                     @"Talents":@[],
                                     @"Planners":@[@{@"UserId": @"Planner2"}],
                                     @"Title":self.textFieldTitle.text,
                                     @"Type":@{ @"Id": [self getIdFromEventType:self.textFieldEventType.text]}};
        NSData *profileImage = UIImagePNGRepresentation(self.imageViewPic.image);
        AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
        manager.requestSerializer = [AFJSONRequestSerializer serializer];
        manager.responseSerializer = [AFJSONResponseSerializer serializer];
        [manager POST:@"http://104.40.7.133/subway/events/AddEventMultiPart" parameters:params constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
            
            [formData appendPartWithFileData:profileImage name:@"Picture" fileName:@"profileImage.jpg" mimeType:@"image/jpeg"];
            
        } progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
            NSDictionary *data = responseObject;
            if ([data[@"Status"] integerValue] == 1) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    [self hideAlertLoading];
                    [self dismissViewControllerAnimated:true completion:nil];
                });
                
            }
            else{
                //ErrorMessage
                if (data[@"ErrorMessage"] != nil) {
                    dispatch_async(dispatch_get_main_queue(), ^{
                        [self showAlertError:@"Alert" body:data[@"ErrorMessage"] closeButton:@"OK"];
                        [self hideAlertLoading];
                    });
                }
                
            }
            
            
        } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
            
            dispatch_async(dispatch_get_main_queue(), ^{
                [self showAlertError:@"Alert" body:error.localizedDescription closeButton:@"OK"];
                [self hideAlertLoading];
            });
            
        }];
I did follow StackoverFlow this answer -  (http://stackoverflow.com/questions/29776430/afnetworking-log-request-body-of-multipart-form-data) but this one also did not help me.

**Comment by skyline75489** [comment]
Multipart body will not be very human-readable because it's binary. If you just want to see what it looks like you could try something like Charles or Fiddler.
