### ISSUE TITLE
AFHTTPRequestSerializer crash

### ISSUE THREAD

**Issue by LongKangYao** [AFNetworking/AFNetworking#3881]
Can you tell me how to change?
![af](https://cloud.githubusercontent.com/assets/9363434/23347623/82003e76-fcde-11e6-8c07-baf40f21bcc3.png)

**Comment by tewha** [comment]
Tough to tell without code, but it kinda looks like your data contains something that can't be serialized. Given the selector name, maybe a UUID? If so, convert it to a string.

But I'm mostly guessing here. :)

**Comment by DanielYK** [comment]
Could it be that the parameters of the request header error?
![header](https://cloud.githubusercontent.com/assets/15338120/23448850/57a7af18-fe8e-11e6-84b0-aa38d7953a18.png)
![param](https://cloud.githubusercontent.com/assets/15338120/23448852/581d4160-fe8e-11e6-9803-cb19452680ba.png)

**Comment by tewha** [comment]
Looks like you're converting to a string there using `UUIDString`. Can you see what's around in the block where it's crashing? Maybe one of the parameters it's trying to add there is obviously wrong.

**Comment by tewha** [comment]
Let me be more specific here. You're looking for a non-string being assigned to an HTTP header. The biggest clue here is the **unrecognized selector sent to instance**, where the selector is `length`.

So the question is: How do you find the non-string? Odds are, it's being set by you calling `setValue:forHTTPHeaderField:`. So I think you should **temporarily** add something to make sure the values passed into that function are actually strings.

Try this:

```
- (void)setValue:(NSString *)value
forHTTPHeaderField:(NSString *)field
{
	[value length];
	[self.mutableHTTPRequestHeaders setValue:value forKey:field];
}
```

Once you find the bad value, you should be able to change it to a string pretty easily. When you're sure you haven't got any non-string values being passed in there, you can remove the extra line.
