### ISSUE TITLE
using self inside the block in AFUrlConnectionOperation.m

### ISSUE THREAD

**Issue by cw-akshaymehta** [AFNetworking/AFNetworking#3885]
Code : 
    dispatch_async(dispatch_get_main_queue(), ^{
        [[NSNotificationCenter defaultCenter] postNotificationName:AFNetworkingOperationDidFinishNotification object:self];
    });
So  you are using self inside block , so in some cases it creates retain cycle and leads to crash

**Comment by tewha** [comment]
AFUrlConnectionOperation is ancient history at this point.

However, I don't think this will cause a retain cycle. Someone please correct me if I'm wrong, but as I read this code the `disaptch_async` contains a reference to `self`. However, the only reference to the unnamed block is released after it's executed. That will, in turn, release the extra reference to `self`. No circular reference/retain cycle.

**Comment by cw-akshaymehta** [comment]
I am getting this crash in my application . While debugging I found that 

Crashed: com.apple.network.connections
0  libobjc.A.dylib                0x18a441704 objc_object::release() + 8
1  libnetwork.dylib               0x19822cfe4 -[NWConcrete_nw_endpoint_resolver cancelWithHandler:forced:] + 220
2  libnetwork.dylib               0x198217b1c nw_endpoint_handler_cancel + 520
3  libnetwork.dylib               0x1982356a8 __nw_connection_cancel_inner_block_invoke + 132
4  libdispatch.dylib              0x18a87a1fc _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x18a87a1bc _dispatch_client_callout + 16
6  libdispatch.dylib              0x18a8883dc _dispatch_queue_serial_drain + 928
7  libdispatch.dylib              0x18a87d9a4 _dispatch_queue_invoke + 652
8  libdispatch.dylib              0x18a88a34c _dispatch_root_queue_drain + 572
9  libdispatch.dylib              0x18a88a0ac _dispatch_worker_thread3 + 124
10 libsystem_pthread.dylib        0x18aa832a0 _pthread_wqthread + 1288
11 libsystem_pthread.dylib        0x18aa82d8c start_wqthread + 4
