### ISSUE TITLE
App crashes in internal implementation of class AFURLRequestSerialization.m

### ISSUE THREAD

**Issue by monisdev** [AFNetworking/AFNetworking#3886]
I'm pasting Fabric / crashlytic log here. Can anyone suggest why this might be happening? 

#0. Crashed: com.twitter.crashlytics.ios.exception
0  House Of God                   0x1003b8a74 CLSProcessRecordAllThreads + 4299459188
1  House Of God                   0x1003b8a74 CLSProcessRecordAllThreads + 4299459188
2  House Of God                   0x1003b8930 CLSProcessRecordAllThreads + 4299458864
3  House Of God                   0x1003a90e0 CLSHandler + 4299395296
4  House Of God                   0x1003b6b38 __CLSExceptionRecord_block_invoke + 4299451192
5  libdispatch.dylib              0x185a061bc _dispatch_client_callout + 16
6  libdispatch.dylib              0x185a137f0 _dispatch_barrier_sync_f_invoke + 84
7  House Of God                   0x1003b65dc CLSExceptionRecord + 4299449820
8  House Of God                   0x1003b6410 CLSExceptionRecordNSException + 4299449360
9  House Of God                   0x1003b6030 CLSTerminateHandler() + 4299448368
10 libc++abi.dylib                0x1855a366c std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x1855a2f84 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
12 libobjc.A.dylib                0x1855b4690 _objc_exception_destructor(void*) + 362
13 CoreFoundation                 0x186b7d100 -[NSException initWithCoder:] + 114
14 Foundation                     0x187717f80 _writeJSONValue + 700
15 Foundation                     0x18771a0d8 ___writeJSONObject_block_invoke + 236
16 CoreFoundation                 0x186ac3548 __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 88
17 CoreFoundation                 0x186ab13fc -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 224
18 Foundation                     0x187719864 _writeJSONObject + 340
19 Foundation                     0x187717e4c _writeJSONValue + 392
20 Foundation                     0x187717c7c -[_NSJSONWriter dataWithRootObject:options:error:] + 140
21 Foundation                     0x187718cc0 +[NSJSONSerialization dataWithJSONObject:options:error:] + 348
22 House Of God                   0x10014edc4 -[AFJSONRequestSerializer requestBySerializingRequest:withParameters:error:] (AFURLRequestSerialization.m:1260)
23 House Of God                   0x10014a2a0 -[AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:] (AFURLRequestSerialization.m:368)
24 House Of God                   0x100141310 -[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:] (AFHTTPSessionManager.m:262)
25 House Of God                   0x1001408fc -[AFHTTPSessionManager POST:parameters:progress:success:failure:] (AFHTTPSessionManager.m:162)
26 House Of God                   0x10013035c -[SSAPIWebWrapper createPostRequestWithParameters:withRequestPath:withCompletionBlock:] (SSAPIWebWrapper.m:55)
27 House Of God                   0x1000533b8 -[SSAPIManager loginWithFacebookWithParameters:accessToken:completionBlock:] (SSAPIManager.m:554)
28 House Of God                   0x1000cf13c __41-[SSHomeViewController getTokenForGuest:]_block_invoke.93 (SSHomeViewController.m:133)
29 House Of God                   0x1000574a0 __57-[SSAPIManager hogStartupWithParameters:completionBlock:]_block_invoke (SSAPIManager.m:1127)
30 House Of God                   0x100131068 __93-[SSAPIWebWrapper createHogStartUpRequestWithParameters:withRequestPath:withCompletionBlock:]_block_invoke (SSAPIWebWrapper.m:168)
31 House Of God                   0x1001416a4 __116-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:]_block_invoke.80 (AFHTTPSessionManager.m:290)
32 House Of God                   0x100154a3c __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 (AFURLSessionManager.m:308)
33 libdispatch.dylib              0x185a061fc _dispatch_call_block_and_release + 24
34 libdispatch.dylib              0x185a061bc _dispatch_client_callout + 16
35 libdispatch.dylib              0x185a0ab2c _dispatch_main_queue_callback_4CF + 428
36 CoreFoundation                 0x186b2a810 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
37 CoreFoundation                 0x186b283fc __CFRunLoopRun + 1660
38 CoreFoundation                 0x186a562b8 CFRunLoopRunSpecific + 444
39 GraphicsServices               0x18850a198 GSEventRunModal + 180
40 UIKit                          0x18ca9d7fc -[UIApplication _run] + 684
41 UIKit                          0x18ca98534 UIApplicationMain + 208
42 House Of God                   0x10013e788 main (main.m:14)
43 libdispatch.dylib              0x185a395b8 (Missing)

--

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x186b7d1b8 __exceptionPreprocess
1  libobjc.A.dylib                0x1855b455c objc_exception_throw
2  CoreFoundation                 0x186b7d100 -[NSException initWithCoder:]
3  Foundation                     0x187717f80 _writeJSONValue
4  Foundation                     0x18771a0d8 ___writeJSONObject_block_invoke
5  CoreFoundation                 0x186ac3548 __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke
6  CoreFoundation                 0x186ab13fc -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]
7  Foundation                     0x187719864 _writeJSONObject
8  Foundation                     0x187717e4c _writeJSONValue
9  Foundation                     0x187717c7c -[_NSJSONWriter dataWithRootObject:options:error:]
10 Foundation                     0x187718cc0 +[NSJSONSerialization dataWithJSONObject:options:error:]
11 House Of God                   0x10014edc4 -[AFJSONRequestSerializer requestBySerializingRequest:withParameters:error:] (AFURLRequestSerialization.m:1260)
12 House Of God                   0x10014a2a0 -[AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:] (AFURLRequestSerialization.m:368)
13 House Of God                   0x100141310 -[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:] (AFHTTPSessionManager.m:262)
14 House Of God                   0x1001408fc -[AFHTTPSessionManager POST:parameters:progress:success:failure:] (AFHTTPSessionManager.m:162)
15 House Of God                   0x10013035c -[SSAPIWebWrapper createPostRequestWithParameters:withRequestPath:withCompletionBlock:] (SSAPIWebWrapper.m:55)
16 House Of God                   0x1000533b8 -[SSAPIManager loginWithFacebookWithParameters:accessToken:completionBlock:] (SSAPIManager.m:554)
17 House Of God                   0x1000cf13c __41-[SSHomeViewController getTokenForGuest:]_block_invoke.93 (SSHomeViewController.m:133)
18 House Of God                   0x1000574a0 __57-[SSAPIManager hogStartupWithParameters:completionBlock:]_block_invoke (SSAPIManager.m:1127)
19 House Of God                   0x100131068 __93-[SSAPIWebWrapper createHogStartUpRequestWithParameters:withRequestPath:withCompletionBlock:]_block_invoke (SSAPIWebWrapper.m:168)
20 House Of God                   0x1001416a4 __116-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:]_block_invoke.80 (AFHTTPSessionManager.m:290)
21 House Of God                   0x100154a3c __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 (AFURLSessionManager.m:308)
22 libdispatch.dylib              0x185a061fc _dispatch_call_block_and_release
23 libdispatch.dylib              0x185a061bc _dispatch_client_callout
24 libdispatch.dylib              0x185a0ab2c _dispatch_main_queue_callback_4CF
25 CoreFoundation                 0x186b2a810 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
26 CoreFoundation                 0x186b283fc __CFRunLoopRun
27 CoreFoundation                 0x186a562b8 CFRunLoopRunSpecific
28 GraphicsServices               0x18850a198 GSEventRunModal
29 UIKit                          0x18ca9d7fc -[UIApplication _run]
30 UIKit                          0x18ca98534 UIApplicationMain
31 House Of God                   0x10013e788 main (main.m:14)
32 libdispatch.dylib              0x185a395b8 (Missing)

#0. Crashed: com.twitter.crashlytics.ios.exception
0  House Of God                   0x1003b8a74 CLSProcessRecordAllThreads + 4299459188
1  House Of God                   0x1003b8a74 CLSProcessRecordAllThreads + 4299459188
2  House Of God                   0x1003b8930 CLSProcessRecordAllThreads + 4299458864
3  House Of God                   0x1003a90e0 CLSHandler + 4299395296
4  House Of God                   0x1003b6b38 __CLSExceptionRecord_block_invoke + 4299451192
5  libdispatch.dylib              0x185a061bc _dispatch_client_callout + 16
6  libdispatch.dylib              0x185a137f0 _dispatch_barrier_sync_f_invoke + 84
7  House Of God                   0x1003b65dc CLSExceptionRecord + 4299449820
8  House Of God                   0x1003b6410 CLSExceptionRecordNSException + 4299449360
9  House Of God                   0x1003b6030 CLSTerminateHandler() + 4299448368
10 libc++abi.dylib                0x1855a366c std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x1855a2f84 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
12 libobjc.A.dylib                0x1855b4690 _objc_exception_destructor(void*) + 362
13 CoreFoundation                 0x186b7d100 -[NSException initWithCoder:] + 114
14 Foundation                     0x187717f80 _writeJSONValue + 700
15 Foundation                     0x18771a0d8 ___writeJSONObject_block_invoke + 236
16 CoreFoundation                 0x186ac3548 __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 88
17 CoreFoundation                 0x186ab13fc -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 224
18 Foundation                     0x187719864 _writeJSONObject + 340
19 Foundation                     0x187717e4c _writeJSONValue + 392
20 Foundation                     0x187717c7c -[_NSJSONWriter dataWithRootObject:options:error:] + 140
21 Foundation                     0x187718cc0 +[NSJSONSerialization dataWithJSONObject:options:error:] + 348
22 House Of God                   0x10014edc4 -[AFJSONRequestSerializer requestBySerializingRequest:withParameters:error:] (AFURLRequestSerialization.m:1260)
23 House Of God                   0x10014a2a0 -[AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:] (AFURLRequestSerialization.m:368)
24 House Of God                   0x100141310 -[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:] (AFHTTPSessionManager.m:262)
25 House Of God                   0x1001408fc -[AFHTTPSessionManager POST:parameters:progress:success:failure:] (AFHTTPSessionManager.m:162)
26 House Of God                   0x10013035c -[SSAPIWebWrapper createPostRequestWithParameters:withRequestPath:withCompletionBlock:] (SSAPIWebWrapper.m:55)
27 House Of God                   0x1000533b8 -[SSAPIManager loginWithFacebookWithParameters:accessToken:completionBlock:] (SSAPIManager.m:554)
28 House Of God                   0x1000cf13c __41-[SSHomeViewController getTokenForGuest:]_block_invoke.93 (SSHomeViewController.m:133)
29 House Of God                   0x1000574a0 __57-[SSAPIManager hogStartupWithParameters:completionBlock:]_block_invoke (SSAPIManager.m:1127)
30 House Of God                   0x100131068 __93-[SSAPIWebWrapper createHogStartUpRequestWithParameters:withRequestPath:withCompletionBlock:]_block_invoke (SSAPIWebWrapper.m:168)
31 House Of God                   0x1001416a4 __116-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:]_block_invoke.80 (AFHTTPSessionManager.m:290)
32 House Of God                   0x100154a3c __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 (AFURLSessionManager.m:308)
33 libdispatch.dylib              0x185a061fc _dispatch_call_block_and_release + 24
34 libdispatch.dylib              0x185a061bc _dispatch_client_callout + 16
35 libdispatch.dylib              0x185a0ab2c _dispatch_main_queue_callback_4CF + 428
36 CoreFoundation                 0x186b2a810 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
37 CoreFoundation                 0x186b283fc __CFRunLoopRun + 1660
38 CoreFoundation                 0x186a562b8 CFRunLoopRunSpecific + 444
39 GraphicsServices               0x18850a198 GSEventRunModal + 180
40 UIKit                          0x18ca9d7fc -[UIApplication _run] + 684
41 UIKit                          0x18ca98534 UIApplicationMain + 208
42 House Of God                   0x10013e788 main (main.m:14)
43 libdispatch.dylib              0x185a395b8 (Missing)

#1. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f344 _pthread_wqthread + 1452
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#2. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f160 _pthread_wqthread + 968
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#3. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f344 _pthread_wqthread + 1452
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#4. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x185b2d188 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185b2cff8 mach_msg + 72
2  CoreFoundation                 0x186b2a5d0 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186b281ec __CFRunLoopRun + 1132
4  CoreFoundation                 0x186a562b8 CFRunLoopRunSpecific + 444
5  Foundation                     0x18759326c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1875b3dd0 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x18d411c38 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x187690e68 __NSThread__start__ + 1024
9  libsystem_pthread.dylib        0x185c11850 <redacted> + 240
10 libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
11 libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

#5. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f344 _pthread_wqthread + 1452
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#6. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f344 _pthread_wqthread + 1452
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#7. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x185b2d188 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185b2cff8 mach_msg + 72
2  CoreFoundation                 0x186b2a5d0 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186b281ec __CFRunLoopRun + 1132
4  CoreFoundation                 0x186a562b8 CFRunLoopRunSpecific + 444
5  CFNetwork                      0x18725ba70 <redacted> + 336
6  Foundation                     0x187690e68 __NSThread__start__ + 1024
7  libsystem_pthread.dylib        0x185c11850 <redacted> + 240
8  libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
9  libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

#8. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x185b2d188 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185b2cff8 mach_msg + 72
2  CoreFoundation                 0x186b2a5d0 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186b281ec __CFRunLoopRun + 1132
4  CoreFoundation                 0x186a562b8 CFRunLoopRunSpecific + 444
5  AVFAudio                       0x1a06f7d24 GenericRunLoopThread::Entry(void*) + 164
6  AVFAudio                       0x1a071dd9c CAPThread::Entry(CAPThread*) + 84
7  libsystem_pthread.dylib        0x185c11850 <redacted> + 240
8  libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
9  libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

#9. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f344 _pthread_wqthread + 1452
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#10. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f344 _pthread_wqthread + 1452
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#11. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f344 _pthread_wqthread + 1452
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#12. GAIThread
0  libsystem_kernel.dylib         0x185b2d188 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185b2cff8 mach_msg + 72
2  CoreFoundation                 0x186b2a5d0 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186b281ec __CFRunLoopRun + 1132
4  CoreFoundation                 0x186a562b8 CFRunLoopRunSpecific + 444
5  Foundation                     0x18759326c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1875e7aa0 -[NSRunLoop(NSRunLoop) run] + 88
7  House Of God                   0x10027e588 +[GAI threadMain:] + 4298171784
8  Foundation                     0x187690e68 __NSThread__start__ + 1024
9  libsystem_pthread.dylib        0x185c11850 <redacted> + 240
10 libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
11 libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

#13. Thread
0  libsystem_pthread.dylib        0x185c0ed88 pthread_workqueue_addthreads_np + 126

#14. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x185b2d188 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185b2cff8 mach_msg + 72
2  House Of God                   0x1003a3f40 CLSMachExceptionServer + 4299374400
3  libsystem_pthread.dylib        0x185c11850 <redacted> + 240
4  libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
5  libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

#15. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f344 _pthread_wqthread + 1452
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#16. Thread
0  libsystem_kernel.dylib         0x185b4ba88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185c0f344 _pthread_wqthread + 1452
2  libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#17. com.apple.CFNetwork.Connection
0  libsystem_kernel.dylib         0x185b2d188 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185b2cff8 mach_msg + 72
2  libdispatch.dylib              0x185a21ac4 _dispatch_mach_msg_send + 860
3  libdispatch.dylib              0x185a21204 _dispatch_mach_send_drain + 412
4  libdispatch.dylib              0x185a22418 _dispatch_mach_send_push_and_trydrain + 380
5  libdispatch.dylib              0x185a1c498 _dispatch_mach_send_msg + 424
6  libdispatch.dylib              0x185a1c764 _dispatch_mach_send_and_wait_for_reply + 256
7  libdispatch.dylib              0x185a1ccb0 dispatch_mach_send_with_result_and_wait_for_reply + 60
8  libxpc.dylib                   0x185c50f90 xpc_connection_send_message_with_reply_sync + 196
9  Security                       0x186f91874 securityd_message_with_reply_sync + 212
10 Security                       0x186f91b28 securityd_send_sync_and_do + 80
11 Security                       0x186fcf354 __SecTrustEvaluateIfNecessary_block_invoke_2 + 404
12 Security                       0x186fac808 SecOSStatusWith + 56
13 Security                       0x186fcf19c __SecTrustEvaluateIfNecessary_block_invoke + 308
14 libsystem_trace.dylib          0x185c2a204 _os_activity_initiate + 76
15 Security                       0x186fcce78 SecTrustEvaluateIfNecessary + 232
16 Security                       0x186fccf00 SecTrustEvaluate + 64
17 CFNetwork                      0x187315018 <redacted> + 32
18 CFNetwork                      0x18732a71c <redacted> + 552
19 CFNetwork                      0x187329f08 <redacted> + 148
20 libdispatch.dylib              0x185a061fc _dispatch_call_block_and_release + 24
21 libdispatch.dylib              0x185a061bc _dispatch_client_callout + 16
22 libdispatch.dylib              0x185a143dc _dispatch_queue_serial_drain + 928
23 libdispatch.dylib              0x185a099a4 _dispatch_queue_invoke + 652
24 libdispatch.dylib              0x185a1634c _dispatch_root_queue_drain + 572
25 libdispatch.dylib              0x185a160ac _dispatch_worker_thread3 + 124
26 libsystem_pthread.dylib        0x185c0f2a0 _pthread_wqthread + 1288
27 libsystem_pthread.dylib        0x185c0ed8c start_wqthread + 4

#18. com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x185b2d188 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185b2cff8 mach_msg + 72
2  CoreFoundation                 0x186b2a5d0 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186b281ec __CFRunLoopRun + 1132
4  CoreFoundation                 0x186a562b8 CFRunLoopRunSpecific + 444
5  CoreFoundation                 0x186aa3b44 CFRunLoopRun + 112
6  CoreMotion                     0x18d919120 (null) + 203196
7  libsystem_pthread.dylib        0x185c11850 <redacted> + 240
8  libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
9  libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

#19. Thread
0  libsystem_kernel.dylib         0x185b4b314 __semwait_signal + 8
1  libsystem_c.dylib              0x185a6925c nanosleep + 212
2  libc++.1.dylib                 0x185579994 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 80
3  JavaScriptCore                 0x18b35a40c <redacted> + 76
4  JavaScriptCore                 0x18b359458 <redacted> + 128
5  JavaScriptCore                 0x18b359294 <redacted> + 60
6  JavaScriptCore                 0x18b359134 <redacted> + 80
7  JavaScriptCore                 0x18b35a4f8 <redacted> + 92
8  JavaScriptCore                 0x18b35a424 <redacted> + 10
9  JavaScriptCore                 0x18b35a6d4 <redacted> + 92
10 libsystem_pthread.dylib        0x185c11850 <redacted> + 240
11 libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
12 libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

#20. WebThread
0  WebCore                        0x18b85aa84 <redacted> + 2
1  WebCore                        0x18b68f988 <redacted> + 324
2  WebCore                        0x18b68f3a4 <redacted> + 4228
3  WebCore                        0x18bb8fb9c <redacted> + 12
4  JavaScriptCore                 0x18b1aeb30 <redacted> + 332
5  JavaScriptCore                 0x18aa91a00 <redacted> + 72
6  JavaScriptCore                 0x18aa950e8 <redacted> + 124
7  JavaScriptCore                 0x18aa92310 <redacted> + 212
8  CoreFoundation                 0x186b2b1d8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
9  CoreFoundation                 0x186b2aeec __CFRunLoopDoTimer + 872
10 CoreFoundation                 0x186b2a7a8 __CFRunLoopDoTimers + 244
11 CoreFoundation                 0x186b283a4 __CFRunLoopRun + 1572
12 CoreFoundation                 0x186a562b8 CFRunLoopRunSpecific + 444
13 WebCore                        0x18b65c490 <redacted> + 456
14 libsystem_pthread.dylib        0x185c11850 <redacted> + 240
15 libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
16 libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

#21. JIT Worklist Worker Thread
0  libsystem_kernel.dylib         0x185b4ae1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x185c109c0 <redacted> + 640
2  libc++.1.dylib                 0x1855393ec std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  JavaScriptCore                 0x18b342d64 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 2132
4  JavaScriptCore                 0x18b11aa5c <redacted> + 192
5  JavaScriptCore                 0x18b11aeac <redacted> + 14
6  JavaScriptCore                 0x18aa8b00c <redacted> + 212
7  JavaScriptCore                 0x18aa8af1c <redacted> + 24
8  libsystem_pthread.dylib        0x185c11850 <redacted> + 240
9  libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
10 libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

#22. WTF Parallel Helper Thread
0  libsystem_kernel.dylib         0x185b4ae1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x185c109c0 <redacted> + 640
2  libc++.1.dylib                 0x1855393ec std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  JavaScriptCore                 0x18b342d64 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 2132
4  JavaScriptCore                 0x18b3422e8 <redacted> + 288
5  JavaScriptCore                 0x18b342088 <redacted> + 76
6  JavaScriptCore                 0x18aa8b00c <redacted> + 212
7  JavaScriptCore                 0x18aa8af1c <redacted> + 24
8  libsystem_pthread.dylib        0x185c11850 <redacted> + 240
9  libsystem_pthread.dylib        0x185c11760 _pthread_start + 282
10 libsystem_pthread.dylib        0x185c0ed94 thread_start + 4

**Comment by tewha** [comment]
```14 Foundation 0x187717f80 _writeJSONValue + 700
15 Foundation 0x18771a0d8 ___writeJSONObject_block_invoke + 236
16 CoreFoundation 0x186ac3548 __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 88
17 CoreFoundation 0x186ab13fc -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 224
18 Foundation 0x187719864 _writeJSONObject + 340
19 Foundation 0x187717e4c _writeJSONValue + 392
20 Foundation 0x187717c7c -[_NSJSONWriter dataWithRootObject:options:error:] + 140
```

It looks like you're deep in JSON serialization. I'd be looking at what kind of objects you're passing, and whether they can be serialized.
