### ISSUE TITLE
warning: code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval

### ISSUE THREAD

**Issue by Coeur** [AFNetworking/AFNetworking#3887]
Like many people, I received this today:

> Dear Developer,
> 
> Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with section 3.3.2 of the Apple Developer Program License Agreement and App Store Review Guideline 2.5.2. This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. 
> 
> This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.
> 
> Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review.
> 
> Best regards,
> 
> App Store Review

But [I do **not** use Rollout.io](https://forums.developer.apple.com/thread/73640),  [I do **not** use JSPatch](https://github.com/bang590/JSPatch/issues/746), I do **not** use weex: [incubator-weex](https://github.com/apache/incubator-weex) or [weex-devtool-iOS](https://github.com/weexteam/weex-devtool-iOS),  I do **not** use javascript or javascript frameworks like React Native or Ionic, I do **not** use any of the quoted methods in my Swift 3 app.

The only dependency that I use with a `method_exchangeImplementations` in its source is... **AFNetworking**. Here is the list of all what I use:

    pod 'MagicalRecord', '~> 2.3'
    pod 'SSZipArchive', '~> 1.6'
    pod 'TSMarkdownParser', :git => 'https://github.com/laptobbe/TSMarkdownParser.git', :branch => '3.x'
    pod 'AFNetworking'
    pod 'SwiftLint', '~> 0.16'
    pod 'Toaster', '~> 2.0'
    pod 'AdobeMobileSDK', '~> 4.13'
    #(And [OpenEars](https://www.politepix.com/openears/))

Is it possible to provide a version of AFNetworking without `method_exchangeImplementations`?

**Comment by zidaneno5** [comment]
Maybe consider using Alamofire if you are using Swift

**Comment by CocoaBob** [comment]
How do you know `AdobeMobileSDK` isn't using some of them?

**Comment by langyapojun** [comment]
i think the pro is `AdobeMobileSDK`,maybe i was wrong😂

**Comment by Coeur** [comment]
@zidaneno5 at the time we started the app, Alamofire made the move to stop support for iOS8 when using Swift 3. They re-introduced support for it months later, but we can't take the risk that, when moving to Swift 4, we lose support of iOS8 because of over-restrictive decisions made by AlamoFire.

**Comment by akixie** [comment]
m

**Comment by Coeur** [comment]
My apologies. We had a non-pod dependency on Amap that I didn't notice earlier, and Amap just acknowledged using JSPatch.

**Comment by full-of-fire** [comment]
@Coeur Excuse me, so, is it because of Amap include respondsToSelector etc. that app will be rejected?

Is AFNetworking ok to use in project?

**Comment by Coeur** [comment]
yes, AF is OK, app was approved by Apple last week
