### ISSUE TITLE
Disable error alerts

### ISSUE THREAD

**Issue by vbklv** [AFNetworking/AFNetworking#3889]
Hi and thanks for the awesome project!
I wonder how can man disable error alerts?
Some users of our app are reporting "Network error (-1009)", "Network error (-1005)", etc.
and I would like to disable alert notifications for those errors.

**Comment by iDevelopper** [comment]
Check error.code in the completion handler block

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
