### ISSUE TITLE
iOS8 SPDY CFReadStreamHasBytesAvailable crash？？

### ISSUE THREAD

**Issue by dabing1022** [AFNetworking/AFNetworking#3890]
> AFNetworking Version: 3.1.0

I'm getting a lot of crash reports on iOS 8 with this stack trace:

```c
#5 Thread
SIGSEGV
SEGV_ACCERR

0 CoreFoundation    CFReadStreamHasBytesAvailable + 28
1 CFNetwork SPDYStream::requestBodyStreamRead() + 32
2 CFNetwork SPDYStream::requestBodyStreamRead() + 32
3 CFNetwork RunloopBlockContext::_invoke_block(void const*, void*) + 76
4 CoreFoundation    CFArrayApplyFunction + 68
5 CFNetwork RunloopBlockContext::perform() + 136
6 CFNetwork MultiplexerSource::perform() + 312
7 CFNetwork MultiplexerSource::_perform(void*) + 68
8 CoreFoundation    ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
9 CoreFoundation    ___CFRunLoopDoSources0 + 264
10 CoreFoundation   ___CFRunLoopRun + 712
11 CoreFoundation   CFRunLoopRunSpecific + 396
12 CFNetwork    +[NSURLConnection(Loader) _resourceLoadLoop:] + 440
13 Foundation   ___NSThread__main__ + 1072
14 libsystem_pthread.dylib  __pthread_body + 164
15 libsystem_pthread.dylib  __pthread_body

```

We know that NSURLSession goes with SPDY protocol on iOS8，http2.0 protocol on iOS9+，so this bug only shows on iOS8. We app record user's page operations, and we found this crash happens when UIApplication DidEnterBackground.

Maybe it's apple's spdy bug on iOS8?

Do you have any ideas?

Thanks.

[http://stackoverflow.com/questions/42689080/ios8-spdy-cfreadstreamhasbytesavailable-crash](http://stackoverflow.com/questions/42689080/ios8-spdy-cfreadstreamhasbytesavailable-crash)

**Comment by SlaunchaMan** [comment]
Yes, this seems like a bug on iOS 8. Please file a report with Apple.
