### ISSUE TITLE
How to handle a POST request redirection problem?

### ISSUE THREAD

**Issue by ChengMoon** [AFNetworking/AFNetworking#3895]
Hellow everybody. I have a question.When I call requests for network AFNetworking POST request redirect, parameters are lost..How to deal with to make the parameters of the POST request redirection is not lost?Or POST to redirect network request, how to ensure the request parameters in httpBody inside is not lost, and can continue to use the POST method makes the redirection request is successful?
The following is my request method:
        operation = [manager POST:url parameters:params success:^(NSURLSessionDataTask * _Nonnull task, NSMutableDictionary *responseObject) {
        block(responseObject,task);//
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        block(nil,error);
    }];

**Comment by euroboy** [comment]
Have you found a solution?

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
