### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by AlbertCamusSZB** [AFNetworking/AFNetworking#3896]
![2017-03-16 12 47 16](https://cloud.githubusercontent.com/assets/23630496/23982237/187b7b66-0a47-11e7-9882-4baaae358da9.png)

 invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.

**Comment by SlaunchaMan** [comment]
We need more information to be able to diagnose this; if you can provide more context, please re-open.
