### ISSUE TITLE
AFQueryStringFromParameters performance issues

### ISSUE THREAD

**Issue by michaeleiselsc** [AFNetworking/AFNetworking#3898]
AFQueryStringFromParameters is taking hundreds of milliseconds on the background for a typical app session, is there any way we could reduce that? Perhaps we could drop down to the C level, or at least avoid creating so many intermediate objects.

**Comment by michaeleiselsc** [comment]
AFPercentEscapedStringFromString seems the most costly part

**Comment by michaeleiselsc** [comment]
One thing for that method is to get a UTF-8 representation (with fallback logic in the very rare cases that we can't, in which case revert to something really safe) and then determine if each character is in one of our sets with a big switch case. Keep putting the results into a C string, then at the end return an NSString from it.

**Comment by michaeleiselsc** [comment]
The nice thing about UTF-8 is, AFAIK, we can do a simple comparison of characters with those in our set, because anytime weird stuff is going on, the bytes will have the most significant bit set to 1, but correct me if I'm wrong.

**Comment by tewha** [comment]
I'm not sure it's the best approach, but perhaps you could supply your own request serializer that makes more assumptions?

**Comment by michaeleiselsc** [comment]
i'm bringing up to you guys because it seems like low-hanging fruit for a perf issue that would affect any user. we could get gains with very quick fixes too like just having an NSString literal with the two string literals appended, rather than calling a string append method.

**Comment by tewha** [comment]
Hey, I'm just a guy, not a project runner or anything. :)
I just haven't noticed a lot of activity lately.

**Comment by SlaunchaMan** [comment]
PRs are open! 😄
