### ISSUE TITLE
Suddenly Large file uploading stop (Multipart)

### ISSUE THREAD

**Issue by kuldeep13990** [AFNetworking/AFNetworking#3899]
i am uploading large file on server with multipart, around 50 % of file is uploading successfully & suddenly the below error Occurs.

**[] nw_endpoint_flow_prepare_output_frames [12.1 103.195.185.118:80 ready socket-flow (satisfied)] Failed to use 1 frames, marking as failed
2017-03-20 17:58:20.173023 XXXXXX[2984:869007] [] nw_endpoint_handler_add_write_request [12.1 103.195.185.118:80 failed socket-flow (satisfied)] cannot accept write requests
2017-03-20 17:58:20.175510 XXXXXX[2984:868739] [] __tcp_connection_write_eof_block_invoke Write close callback received error: [22] Invalid argument** 

Why i am getting this error? Please help me.

**Comment by anselPeng** [comment]
I have the same problem, have you solved it?

**Comment by anselPeng** [comment]
Delete the NSLog in the request

**Comment by yangyu2010** [comment]
It doesn't work @anselPeng

**Comment by anselPeng** [comment]
其实主要原因就是在发送请求之后主线程被占用，或者堵塞引起的

**Comment by SlaunchaMan** [comment]
If you can provide more information that shows a bug in AFNetworking, please re-open. For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
