### ISSUE TITLE
Crash in the AFURLSessionManager

### ISSUE THREAD

**Issue by manpreetg** [AFNetworking/AFNetworking#3900]
Fatal Exception: NSGenericException
0  CoreFoundation                 0x21aab91b __exceptionPreprocess
1  libobjc.A.dylib                0x21246e17 objc_exception_throw
2  CFNetwork                      0x21fb3091 -[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]
3  CFNetwork                      0x21fb3d9f -[__NSURLSessionLocal dataTaskForRequest:completion:]
4  SignOnTheGo                    0x24e39d __93-[AFURLSessionManager dataTaskWithRequest:uploadProgress:downloadProgress:completionHandler:]_block_invoke (AFURLSessionManager.m:766)
5  SignOnTheGo                    0x24e33d url_session_manager_create_task_safely (AFURLSessionManager.m:50)
6  SignOnTheGo                    0x24e231 -[AFURLSessionManager dataTaskWithRequest:uploadProgress:downloadProgress:completionHandler:] (AFURLSessionManager.m:769)
7  SignOnTheGo                    0x23adf5 -[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:] (AFHTTPSessionManager.m:277)
8  SignOnTheGo                    0x23a2cd -[AFHTTPSessionManager GET:parameters:progress:success:failure:] (AFHTTPSessionManager.m:119)
9  SignOnTheGo                    0x216b29 -[SGSelectPartnerViewController searchBar:textDidChange:] (SGSelectPartnerViewController.m:509)
10 UIKit                          0x2622c757 -[UISearchBar(UISearchBarStatic) _searchFieldEditingChanged]
11 UIKit                          0x2605e755 -[UIApplication sendAction:to:from:forEvent:]
12 UIKit                          0x2605e6e1 -[UIControl sendAction:to:forEvent:]
13 UIKit                          0x260466d3 -[UIControl _sendActionsForEvents:withEvent:]
14 UIKit                          0x2622c505 -[UITextField fieldEditorDidChange:]
15 UIKit                          0x26068f2b -[UITextInputController _sendDelegateChangeNotificationsForText:selection:]
16 UIKit                          0x261fb65f -[UITextInputController _insertText:fromKeyboard:]
17 UIKit                          0x261fa9f5 -[UITextInputController insertText:]
18 UIKit                          0x26382dbb -[UIFieldEditor insertFilteredText:]
19 UIKit                          0x2693c58b -[UITextField insertFilteredText:]
20 UIKit                          0x261fa75f -[UIKeyboardImpl insertText:]
21 UIKit                          0x264271f3 -[UIKeyboardImpl performKeyboardOutput:]
22 UIKit                          0x26426e23 __55-[UIKeyboardImpl handleKeyboardInput:executionContext:]_block_invoke_2
23 UIKit                          0x26051615 -[UIKeyboardTaskQueue continueExecutionOnMainThread]
24 Foundation                     0x222d56df __NSThreadPerformPerform
25 CoreFoundation                 0x21a6ddff __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
26 CoreFoundation                 0x21a6d9ed __CFRunLoopDoSources0
27 CoreFoundation                 0x21a6bd5b __CFRunLoopRun
28 CoreFoundation                 0x219bb229 CFRunLoopRunSpecific
29 CoreFoundation                 0x219bb015 CFRunLoopRunInMode
30 GraphicsServices               0x22fabac9 GSEventRunModal
31 UIKit                          0x2608f189 UIApplicationMain
32 SignOnTheGo                    0x18e91b main (main.m:14)
33 libdispatch.dylib              0x21663873 (Missing)

**Comment by SlaunchaMan** [comment]
Can you provide more information?
