### ISSUE TITLE
Progressive download

### ISSUE THREAD

**Issue by ArtikBhorn** [AFNetworking/AFNetworking#3903]
Is there any way to make a progressive download to initiate video playing before the video is fully loaded? If not, I would like to issue a feature request. At this time I am using the code below, but the response object is not available until the download is complete.

    NSMutableURLRequest *request = [[AFHTTPRequestSerializer serializer] multipartFormRequestWithMethod:@"POST" URLString:url parameters:nil constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        
            [formData appendPartWithFormData:[pwd dataUsingEncoding:NSUTF8StringEncoding] name:@"password"];
            [formData appendPartWithFormData:[user_id dataUsingEncoding:NSUTF8StringEncoding] name:@"userid"];

    } error:nil];
    
    AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];
    manager.responseSerializer = [AFHTTPResponseSerializer serializer];

    NSURLSessionUploadTask *uploadTask = [manager uploadTaskWithStreamedRequest:request progress:^(NSProgress * _Nonnull uploadProgress) {
        dispatch_async(dispatch_get_main_queue(), ^{
              NSLog(@"Fraction completed: %f", uploadProgress.fractionCompleted);
        });
        
    } completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {

    // Here I save the responseObject to the drive and convert it to an AVPlayer asset for playing

    }];
    [uploadTask resume];

**Comment by SlaunchaMan** [comment]
Streaming video is out of the scope of AFNetworking—you’d need to stream the response to something that plays video. For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
