### ISSUE TITLE
Interceptor in Alamofire/AFNetworking

### ISSUE THREAD

**Issue by sunilkumarj** [AFNetworking/AFNetworking#3904]
I am working on SDK project which requires Interceptor. Which means When ever the developer calls AFNetwroking , before it calls to server I want to change the url and params based on condition. I have done successfully in Android using Okhttp. 

Without changing too many codes I want to handle in the SDK. Please help me for my problem. 

OkHttp Example  in Android

OkHttpClient client = new OkHttpClient.Builder()
.addInterceptor(new LoggingInterceptor()) //Adding of addInterceptor
.build();

**Comment by sunilkumarj** [comment]
Please respond AFnetworking people. Its working in swift Alamofire using requestAdapter. I am not able to get it done for AFNetworking..

**Comment by kevinvanmierlo** [comment]
Don't know why there is no answer yet. But you can use a RequestAdapter https://github.com/Alamofire/Alamofire#requestadapter. Corresponding issue: https://github.com/Alamofire/Alamofire/issues/1331

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
