### ISSUE TITLE
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: service unavailable (503)"

### ISSUE THREAD

**Issue by amitabh1978** [AFNetworking/AFNetworking#3907]
Dear Folks,

I am trying to send a message from my iPhone 6 / iOS 10.2.1 via Sensor Phone app. But I am getting this error. I have tried with both v1 and v2 versions. I get the same error. I have redeployed MMS twice and simulated this.
I am using below path to hit the mms server on HANA.

https://iotmmsiotservices-p194XXXXXXXtrial.hanatrial.ondemand.com/com.sap.iotservices.mms/v1/api/http/data/17a8f9d4-cdbd-4a4b-b67c-0000000000

I am working on a trial account.

Can some please help.

Regards
Amitabh

**Comment by andr-ggn** [comment]
This error code means that backend is unavailable now. 
Try to make request via Postman or Paw. And than use a library.

**Comment by amitabh1978** [comment]
Issue resolved. Was calling the wrong MMS path.

Thanks
Amitabh
