### ISSUE TITLE
AFNetworkingReachibility Settings App Crash

### ISSUE THREAD

**Issue by serjooo** [AFNetworking/AFNetworking#3909]
As the title suggests, when I use AFNetworkingReachability and I get that the app is not connected to an internet connection I use:
 ```
[Utilities showAlertViewWithTitle:@"No Internet Connection" message:@"VPN requires a working internet connection to work" sender:self positiveButtonTitle:@"Ok" negativeButtonTitle:nil completion:^(BOOL allow) {
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString] options:@{} completionHandler:nil];
    }];
```

And when the Settings app is launching the Setting app crashes, and the user is unable to go to the Settings app from my application.

I tried implementing the AFNetworkingReachibility several ways. 

1. I have an APIManager class, where I wrote checkInternetConnection method where it returns the value of [AFNetworkReachabilityManager sharedManager].reachable. Also, I have registered the [[AFNetworkReachabilityManager sharedManager] startMonitoring]; in the app delegate. My app started crashing after I added the startMonitoring in the app delegate. So I thought maybe I should change the way the code is setup.
2. I went to the documentation and saw this piece of code:

```
[[AFNetworkReachabilityManager sharedManager] setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {
    NSLog(@"Reachability: %@", AFStringFromNetworkReachabilityStatus(status));
}];
[[AFNetworkReachabilityManager sharedManager] startMonitoring];
```
So I decided okay, let me just add this to my ViewController and just show an alert in the callback according to the status. So I did something like this.

View will appear:
`[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(checkInternetConnection) name:UIApplicationWillEnterForegroundNotification object:nil];`

```
#pragma Mark - Check Internet Connection 

- (void) checkInternetConnection {
    //Check internet connectivity
    [[AFNetworkReachabilityManager sharedManager] setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {
        NSLog(@"Reachability: %@", AFStringFromNetworkReachabilityStatus(status));
        if(status == AFNetworkReachabilityStatusNotReachable || status == AFNetworkReachabilityStatusUnknown) {
            [Utilities showAlertViewWithTitle:@"No Internet Connection" message:@"VPN requires a working internet connection to work" sender:self positiveButtonTitle:@"Ok" negativeButtonTitle:nil completion:^(BOOL allow) {
                [[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString] options:@{} completionHandler:nil];
            }];
        }
    }];
    
    [[AFNetworkReachabilityManager sharedManager] startMonitoring];
}
```

This still causes the Settings app to crash.. I'm not sure if what I'm doing is wrong. Or this is from the AFNetworking, since in my first case when I never had done the monitoring it was working fine, but the thing was when I was coming back to the app after turning on the internet connection the value of [AFNetworkReachabilityManager sharedManager].reachable was still returning false and showing me the alert. Thank you for your time.

Best,
Serj.

**Comment by kyungkoo** [comment]
Could you upload error message printed on Console?

**Comment by serjooo** [comment]
There was no message being printed in console since the Settings App was the one being crashed and not my app itself. But at one place I did put a breakpoint somewhere was getting something about a batch or something like that. 

Anyways I think I should close this issue, because even after I removed the original code that created the problem, the settings app kept on crashing. I think it might be somewhere xcode messed up the project somehow or something. To fix my issue without having to make a clean project, I resorted to using this code:

`[[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"App-Prefs:root"] options:@{} completionHandler:nil]; `

instead of this

`[[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString] options:@{} completionHandler:nil];`

There was something internal I guess from Apple that caused the Settings app to persist crashing

**Comment by ajumalebrahim** [comment]
Am also getting the same issue for only iOS - 9.


# Date: 2017-10-29T08:38:00Z
# OS Version: 9.1.0 (13B143)
# Device: iPhone 6s Plus
# RAM Free: 33.6%
# Disk Free: 44.3%

#18. Crashed: XPC API Misuse: Given object not of required type.
0  libxpc.dylib                   0x19932e8fc _xpc_api_misuse + 52
1  libxpc.dylib                   0x19932e8fc _xpc_api_misuse + 52
2  libxpc.dylib                   0x19931f338 _xpc_dictionary_apply_apply + 138
3  libsystem_network.dylib        0x1992a5aac nw_path_agents_are_satisfied_update_reason + 132
4  libsystem_network.dylib        0x1992a5974 nw_path_uses_interface_type + 84
5  SystemConfiguration            0x1889460a8 __SCNetworkReachabilityGetFlagsFromPath + 240
6  SystemConfiguration            0x188947214 SCNetworkReachabilityGetFlags + 148
7  Talabat                        0x1002ccbbc __47-[AFNetworkReachabilityManager startMonitoring]_block_invoke.50 (AFNetworkReachabilityManager.m:226)
8  libdispatch.dylib              0x1990d56e8 _dispatch_call_block_and_release + 24
9  libdispatch.dylib              0x1990d56a8 _dispatch_client_callout + 16
10 libdispatch.dylib              0x1990e3b40 _dispatch_root_queue_drain + 2140
11 libdispatch.dylib              0x1990e32dc _dispatch_worker_thread3 + 112
12 libsystem_pthread.dylib        0x1992e9470 _pthread_wqthread + 1092
13 libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

--

#0. com.apple.main-thread
0  libmis.dylib                   0x19885f2fc (Missing)
1  CoreFoundation                 0x1832f7dc0 CFGetAllocator + 88
2  CoreFoundation                 0x18344c750 __CFBasicHashAddValue + 320
3  CoreFoundation                 0x1832faff8 CFBasicHashAddValue + 288
4  CoreFoundation                 0x1832fc2b0 CFDictionaryAddValue + 248
5  CoreFoundation                 0x183313bc8 __CFDictionaryApplyFunction_block_invoke + 24
6  CoreFoundation                 0x1832fbfdc CFBasicHashApply + 128
7  CoreFoundation                 0x18330535c CFDictionaryApplyFunction + 200
8  CoreFoundation                 0x1834564f8 -[CFPrefsSource mergeIntoDictionary:] + 88
9  CoreFoundation                 0x1833c7c28 -[CFPrefsSearchListSource alreadylocked_copyDictionary] + 828
10 CoreFoundation                 0x1833c6a44 -[CFPrefsSearchListSource alreadylocked_copyValueForKey:] + 72
11 CoreFoundation                 0x183458524 ___CFPreferencesCopyAppValueWithContainer_block_invoke + 68
12 CoreFoundation                 0x1833c5c00 +[CFPrefsSearchListSource withSearchListForIdentifier:container:perform:] + 572
13 CoreFoundation                 0x18345849c _CFPreferencesCopyAppValueWithContainer + 188
14 Foundation                     0x184275618 -[NSUserDefaults(NSUserDefaults) objectForKey:] + 40
15 Foundation                     0x18435d3b8 -[NSUserDefaults(NSUserDefaults) dictionaryForKey:] + 24
16 Talabat                        0x100101444 -[AuthManager authData] (AuthManager.m:101)
17 Talabat                        0x1001015f0 -[AuthManager hasToken] (AuthManager.m:126)
18 Talabat                        0x10015651c -[Customer userLoggedIn] (Customer.m:365)
19 Talabat                        0x100144534 -[AppDelegate createItemsWithIcons] (AppDelegate.m:837)
20 Talabat                        0x100141100 -[AppDelegate application:didFinishLaunchingWithOptions:] (AppDelegate.m:169)
21 UIKit                          0x188a21324 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 400
22 UIKit                          0x188c4facc -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2904
23 UIKit                          0x188c53e0c -[UIApplication _runWithMainScene:transitionContext:completion:] + 1656
24 UIKit                          0x188c50f50 -[UIApplication workspaceDidEndTransaction:] + 168
25 FrontBoardServices             0x18d57f7c4 -[FBSSerialQueue _performNext] + 184
26 FrontBoardServices             0x18d57fb44 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
27 CoreFoundation                 0x1833d0544 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
28 CoreFoundation                 0x1833cffd8 __CFRunLoopDoSources0 + 540
29 CoreFoundation                 0x1833cdcd8 __CFRunLoopRun + 724
30 CoreFoundation                 0x1832fcca0 CFRunLoopRunSpecific + 384
31 UIKit                          0x188a1a1c8 -[UIApplication _run] + 460
32 UIKit                          0x188a14ffc UIApplicationMain + 204
33 Talabat                        0x100150a5c main (main.m:14)
34 libdyld.dylib                  0x1991068b8 start + 4

#1. com.twitter.crashlytics.ios.work-queue :: NSOperation 0x1256b3360 (QOS: LEGACY)
0  libsystem_kernel.dylib         0x199222578 __getdirentries64 + 8
1  libsystem_c.dylib              0x19913f410 _readdir_unlocked + 92
2  libsystem_c.dylib              0x19913f398 readdir + 40
3  libsystem_c.dylib              0x199147a7c fts_build + 420
4  libsystem_c.dylib              0x199141a9c fts_read + 812
5  libremovefile.dylib            0x1991156a4 __removefile_tree_walker + 160
6  libremovefile.dylib            0x199115ac8 removefile + 144
7  Foundation                     0x1842b4184 -[NSFilesystemItemRemoveOperation main] + 172
8  Foundation                     0x1842833e8 -[__NSOperationInternal _start:] + 604
9  Foundation                     0x1842b3c2c -[NSFileManager removeItemAtPath:error:] + 84
10 Talabat                        0x100b92630 -[CLSFileManager removeItemAtPath:] + 1331324
11 Talabat                        0x100ba0d88 __71-[CLSReportsController prepareAndSubmitReport:asUrgent:withProcessing:]_block_invoke + 1390548
12 Talabat                        0x100b94938 CLSApplicationAcivity + 1340292
13 Talabat                        0x100ba0a60 -[CLSReportsController prepareAndSubmitReport:asUrgent:withProcessing:] + 1389740
14 Talabat                        0x100b9c730 __72-[CLSCrashReportingController handleDelegateCompletionForReport:submit:]_block_invoke + 1372540
15 Foundation                     0x184340374 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
16 Foundation                     0x1842931a0 -[NSBlockOperation main] + 96
17 Foundation                     0x1842833e8 -[__NSOperationInternal _start:] + 604
18 Foundation                     0x184342768 __NSOQSchedule_f + 224
19 libdispatch.dylib              0x1990d56a8 _dispatch_client_callout + 16
20 libdispatch.dylib              0x1990e16ec _dispatch_queue_drain + 864
21 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
22 libdispatch.dylib              0x1990e35bc _dispatch_root_queue_drain + 728
23 libdispatch.dylib              0x1990e32dc _dispatch_worker_thread3 + 112
24 libsystem_pthread.dylib        0x1992e9470 _pthread_wqthread + 1092
25 libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

#2. com.apple.libdispatch-manager
0  libsystem_kernel.dylib         0x1992244fc kevent_qos + 8
1  libdispatch.dylib              0x1990e8a04 _dispatch_mgr_invoke + 232
2  libdispatch.dylib              0x1990d7874 _dispatch_source_invoke + 50

#3. com.apple.CoreLocation.ConnectionClient.0x126910e70.events
0  libsystem_kernel.dylib         0x199208a94 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x1990e65c0 _dispatch_semaphore_wait_slow + 160
2  CoreLocation                   0x183ba2d94 (null) + 628
3  CoreLocation                   0x183ba7808 (null) + 1176
4  CoreLocation                   0x183be1f28 (null) + 59072
5  CoreLocation                   0x183bdfb7c (null) + 49940
6  CoreLocation                   0x183bdfab0 (null) + 49736
7  CoreLocation                   0x183be0cfc (null) + 54420
8  libxpc.dylib                   0x19931d3b0 _xpc_connection_call_event_handler + 68
9  libxpc.dylib                   0x19931b158 _xpc_connection_mach_event + 2132
10 libdispatch.dylib              0x1990d57a4 _dispatch_client_callout4 + 16
11 libdispatch.dylib              0x1990d9a90 _dispatch_mach_msg_invoke + 656
12 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
13 libdispatch.dylib              0x1990d8ba4 _dispatch_mach_invoke + 600
14 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
15 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
16 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
17 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
18 libdispatch.dylib              0x1990d56a8 _dispatch_client_callout + 16
19 libdispatch.dylib              0x1990e3b40 _dispatch_root_queue_drain + 2140
20 libdispatch.dylib              0x1990e32dc _dispatch_worker_thread3 + 112
21 libsystem_pthread.dylib        0x1992e9470 _pthread_wqthread + 1092
22 libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

#4. com.apple.CoreLocation.ConnectionClient.0x126aa9420.events
0  libsystem_kernel.dylib         0x199208a94 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x1990e65c0 _dispatch_semaphore_wait_slow + 160
2  CoreLocation                   0x183ba2d94 (null) + 628
3  CoreLocation                   0x183ba7808 (null) + 1176
4  CoreLocation                   0x183be1f28 (null) + 59072
5  CoreLocation                   0x183bdfb7c (null) + 49940
6  CoreLocation                   0x183bdfab0 (null) + 49736
7  CoreLocation                   0x183be0cfc (null) + 54420
8  libxpc.dylib                   0x19931d3b0 _xpc_connection_call_event_handler + 68
9  libxpc.dylib                   0x19931b158 _xpc_connection_mach_event + 2132
10 libdispatch.dylib              0x1990d57a4 _dispatch_client_callout4 + 16
11 libdispatch.dylib              0x1990d9a90 _dispatch_mach_msg_invoke + 656
12 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
13 libdispatch.dylib              0x1990d8ba4 _dispatch_mach_invoke + 600
14 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
15 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
16 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
17 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
18 libdispatch.dylib              0x1990d56a8 _dispatch_client_callout + 16
19 libdispatch.dylib              0x1990e3b40 _dispatch_root_queue_drain + 2140
20 libdispatch.dylib              0x1990e32dc _dispatch_worker_thread3 + 112
21 libsystem_pthread.dylib        0x1992e9470 _pthread_wqthread + 1092
22 libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

#5. com.apple.CoreLocation.ConnectionClient.0x12691ccd0.events
0  libsystem_kernel.dylib         0x199208a94 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x1990e65c0 _dispatch_semaphore_wait_slow + 160
2  CoreLocation                   0x183ba2d94 (null) + 628
3  CoreLocation                   0x183ba7808 (null) + 1176
4  CoreLocation                   0x183be1f28 (null) + 59072
5  CoreLocation                   0x183bdfb7c (null) + 49940
6  CoreLocation                   0x183bdfab0 (null) + 49736
7  CoreLocation                   0x183be0cfc (null) + 54420
8  libxpc.dylib                   0x19931d3b0 _xpc_connection_call_event_handler + 68
9  libxpc.dylib                   0x19931b158 _xpc_connection_mach_event + 2132
10 libdispatch.dylib              0x1990d57a4 _dispatch_client_callout4 + 16
11 libdispatch.dylib              0x1990d9a90 _dispatch_mach_msg_invoke + 656
12 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
13 libdispatch.dylib              0x1990d8ba4 _dispatch_mach_invoke + 600
14 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
15 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
16 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
17 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
18 libdispatch.dylib              0x1990d56a8 _dispatch_client_callout + 16
19 libdispatch.dylib              0x1990e3b40 _dispatch_root_queue_drain + 2140
20 libdispatch.dylib              0x1990e32dc _dispatch_worker_thread3 + 112
21 libsystem_pthread.dylib        0x1992e9470 _pthread_wqthread + 1092
22 libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

#6. harvesterQueue
0  libsystem_kernel.dylib         0x199208a7c semaphore_wait_trap + 8
1  libdispatch.dylib              0x1990e6614 _dispatch_semaphore_wait_slow + 244
2  CFNetwork                      0x182b72ac0 CFURLConnectionSendSynchronousRequest + 288
3  CFNetwork                      0x182b9607c +[NSURLConnection sendSynchronousRequest:returningResponse:error:] + 120
4  Talabat                        0x10096fea4 __65+[NRMANSURLConnectionSupport poseImplementationBlockForSelector:]_block_invoke (NRMANSURLConnectionSupport.m:202)
5  Talabat                        0x100986660 -[NRMAHarvesterConnection send:] (NRMAHarvesterConnection.m:80)
6  Talabat                        0x100987374 -[NRMAHarvesterConnection sendData:] (NRMAHarvesterConnection.m:143)
7  Talabat                        0x100969018 -[NRMAHarvester connected] (NRMAHarvester.m:285)
8  Talabat                        0x10096b424 -[NRMAHarvester execute] (NRMAHarvester.m:521)
9  Talabat                        0x10096a9cc -[NRMAHarvester transitionToConnected:] (NRMAHarvester.m:452)
10 Talabat                        0x1009699f8 -[NRMAHarvester disconnected] (NRMAHarvester.m:368)
11 Talabat                        0x10096b3e4 -[NRMAHarvester execute] (NRMAHarvester.m:516)
12 Talabat                        0x100973534 __30+[NRMAHarvestController start]_block_invoke_2 (NRMAHarvestController.m:145)
13 libdispatch.dylib              0x1990d56e8 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x1990d56a8 _dispatch_client_callout + 16
15 libdispatch.dylib              0x1990e16ec _dispatch_queue_drain + 864
16 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
17 libdispatch.dylib              0x1990d56a8 _dispatch_client_callout + 16
18 libdispatch.dylib              0x1990e3b40 _dispatch_root_queue_drain + 2140
19 libdispatch.dylib              0x1990e32dc _dispatch_worker_thread3 + 112
20 libsystem_pthread.dylib        0x1992e9470 _pthread_wqthread + 1092
21 libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

#7. com.twitter.crashlytics.ios.MachExceptionServer
0  Talabat                        0x100ba6f1c CLSProcessRecordAllThreads + 1415528
1  Talabat                        0x100ba6f1c CLSProcessRecordAllThreads + 1415528
2  Talabat                        0x100ba6dd8 CLSProcessRecordAllThreads + 1415204
3  Talabat                        0x100b96f04 CLSHandler + 1349968
4  Talabat                        0x100b91f18 CLSMachExceptionServer + 1329508
5  libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
6  libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
7  libsystem_pthread.dylib        0x1992e9028 thread_start + 4

#8. Thread
0  libsystem_kernel.dylib         0x199223b6c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1992e9530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

#9. Thread
0  libsystem_kernel.dylib         0x199223b6c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1992e9530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

#10. com.apple.CoreLocation.ConnectionClient.0x126908570.events
0  libsystem_kernel.dylib         0x199208a94 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x1990e65c0 _dispatch_semaphore_wait_slow + 160
2  CoreLocation                   0x183ba2d94 (null) + 628
3  CoreLocation                   0x183ba7808 (null) + 1176
4  CoreLocation                   0x183be1f28 (null) + 59072
5  CoreLocation                   0x183bdfb7c (null) + 49940
6  CoreLocation                   0x183bdfab0 (null) + 49736
7  CoreLocation                   0x183be0cfc (null) + 54420
8  libxpc.dylib                   0x19931d3b0 _xpc_connection_call_event_handler + 68
9  libxpc.dylib                   0x19931b158 _xpc_connection_mach_event + 2132
10 libdispatch.dylib              0x1990d57a4 _dispatch_client_callout4 + 16
11 libdispatch.dylib              0x1990d9a90 _dispatch_mach_msg_invoke + 656
12 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
13 libdispatch.dylib              0x1990d8ba4 _dispatch_mach_invoke + 600
14 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
15 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
16 libdispatch.dylib              0x1990e18c0 _dispatch_queue_drain + 1332
17 libdispatch.dylib              0x1990d91ac _dispatch_queue_invoke + 464
18 libdispatch.dylib              0x1990d56a8 _dispatch_client_callout + 16
19 libdispatch.dylib              0x1990e3b40 _dispatch_root_queue_drain + 2140
20 libdispatch.dylib              0x1990e32dc _dispatch_worker_thread3 + 112
21 libsystem_pthread.dylib        0x1992e9470 _pthread_wqthread + 1092
22 libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

#11. Thread
0  libsystem_kernel.dylib         0x199223440 __semwait_signal + 8
1  libsystem_c.dylib              0x199141e2c nanosleep + 212
2  libc++.1.dylib                 0x197f1e314 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 84
3  JavaScriptCore                 0x184fc9c1c bmalloc::Heap::scavenge(std::__1::unique_lock<bmalloc::StaticMutex>&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) + 188
4  JavaScriptCore                 0x184fc98cc bmalloc::Heap::concurrentScavenge() + 84
5  JavaScriptCore                 0x184fcbe0c bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::entryPoint() + 100
6  JavaScriptCore                 0x184fcbd9c bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::pthreadEntryPoint(void*) + 12
7  libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
8  libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
9  libsystem_pthread.dylib        0x1992e9028 thread_start + 4

#12. WebThread
0  libsystem_kernel.dylib         0x199222f90 __psynch_mutexwait + 8
1  libsystem_pthread.dylib        0x1992ee39c _pthread_mutex_lock_wait + 96
2  libsystem_pthread.dylib        0x1992ee57c _pthread_mutex_lock_slow + 296
3  WebCore                        0x1957dc840 _WebTryThreadLock(bool) + 128
4  WebCore                        0x1957dc7a0 WebRunLoopLock(__CFRunLoopObserver*, unsigned long, void*) + 44
5  CoreFoundation                 0x1833cfbd0 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
6  CoreFoundation                 0x1833cd974 __CFRunLoopDoObservers + 372
7  CoreFoundation                 0x1833cdca4 __CFRunLoopRun + 672
8  CoreFoundation                 0x1832fcca0 CFRunLoopRunSpecific + 384
9  WebCore                        0x1957da54c RunWebThread(void*) + 456
10 libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
11 libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
12 libsystem_pthread.dylib        0x1992e9028 thread_start + 4

#13. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x199208a40 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1992088bc mach_msg + 72
2  CoreFoundation                 0x1833d0108 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1833cde0c __CFRunLoopRun + 1032
4  CoreFoundation                 0x1832fcca0 CFRunLoopRunSpecific + 384
5  CFNetwork                      0x182b95b84 +[NSURLConnection(Loader) _resourceLoadLoop:] + 412
6  Foundation                     0x18435bc80 __NSThread__start__ + 1000
7  libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
8  libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
9  libsystem_pthread.dylib        0x1992e9028 thread_start + 4

#14. JavaScriptCore::Marking
0  libsystem_kernel.dylib         0x199222f48 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1992eace8 _pthread_cond_wait + 648
2  libc++.1.dylib                 0x197ee0074 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  JavaScriptCore                 0x184d78ad8 JSC::GCThread::waitForNextPhase() + 144
4  JavaScriptCore                 0x184d78b70 JSC::GCThread::gcThreadMain() + 84
5  JavaScriptCore                 0x184a4e824 WTF::threadEntryPoint(void*) + 212
6  JavaScriptCore                 0x184a4e734 WTF::wtfThreadEntryPoint(void*) + 24
7  libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
8  libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
9  libsystem_pthread.dylib        0x1992e9028 thread_start + 4

#15. Thread
0  libsystem_kernel.dylib         0x199222f48 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1992eace8 _pthread_cond_wait + 648
2  libc++.1.dylib                 0x197ee0074 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  Talabat                        0x100c4bec0 NewRelic::WorkQueue::task_thread() + 2091276
4  Talabat                        0x100c4c11c std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >::__execute() + 2091880
5  Talabat                        0x100c4c070 void* std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >*> >(void*) + 2091708
6  libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
7  libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
8  libsystem_pthread.dylib        0x1992e9028 thread_start + 4

#16. Thread
0  libsystem_kernel.dylib         0x199222f48 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1992eace8 _pthread_cond_wait + 648
2  libc++.1.dylib                 0x197ee0074 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  Talabat                        0x100c4bec0 NewRelic::WorkQueue::task_thread() + 2091276
4  Talabat                        0x100c4c11c std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >::__execute() + 2091880
5  Talabat                        0x100c4c070 void* std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >*> >(void*) + 2091708
6  libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
7  libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
8  libsystem_pthread.dylib        0x1992e9028 thread_start + 4

#17. Thread
0  libsystem_kernel.dylib         0x199222f48 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1992eace8 _pthread_cond_wait + 648
2  libc++.1.dylib                 0x197ee0074 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  Talabat                        0x100c4bec0 NewRelic::WorkQueue::task_thread() + 2091276
4  Talabat                        0x100c4c11c std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >::__execute() + 2091880
5  Talabat                        0x100c4c070 void* std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >*> >(void*) + 2091708
6  libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
7  libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
8  libsystem_pthread.dylib        0x1992e9028 thread_start + 4

#18. Crashed: XPC API Misuse: Given object not of required type.
0  libxpc.dylib                   0x19932e8fc _xpc_api_misuse + 52
1  libxpc.dylib                   0x19932e8fc _xpc_api_misuse + 52
2  libxpc.dylib                   0x19931f338 _xpc_dictionary_apply_apply + 138
3  libsystem_network.dylib        0x1992a5aac nw_path_agents_are_satisfied_update_reason + 132
4  libsystem_network.dylib        0x1992a5974 nw_path_uses_interface_type + 84
5  SystemConfiguration            0x1889460a8 __SCNetworkReachabilityGetFlagsFromPath + 240
6  SystemConfiguration            0x188947214 SCNetworkReachabilityGetFlags + 148
7  Talabat                        0x1002ccbbc __47-[AFNetworkReachabilityManager startMonitoring]_block_invoke.50 (AFNetworkReachabilityManager.m:226)
8  libdispatch.dylib              0x1990d56e8 _dispatch_call_block_and_release + 24
9  libdispatch.dylib              0x1990d56a8 _dispatch_client_callout + 16
10 libdispatch.dylib              0x1990e3b40 _dispatch_root_queue_drain + 2140
11 libdispatch.dylib              0x1990e32dc _dispatch_worker_thread3 + 112
12 libsystem_pthread.dylib        0x1992e9470 _pthread_wqthread + 1092
13 libsystem_pthread.dylib        0x1992e9020 start_wqthread + 4

#19. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x199223368 __select + 8
1  CoreFoundation                 0x1833d6670 __CFSocketManager + 648
2  libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
3  libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
4  libsystem_pthread.dylib        0x1992e9028 thread_start + 4

#20. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x199208a40 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1992088bc mach_msg + 72
2  CoreFoundation                 0x1833d0108 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1833cde0c __CFRunLoopRun + 1032
4  CoreFoundation                 0x1832fcca0 CFRunLoopRunSpecific + 384
5  libAVFAudio.dylib              0x181a65810 GenericRunLoopThread::Entry(void*) + 164
6  libAVFAudio.dylib              0x181a3a384 CAPThread::Entry(CAPThread*) + 84
7  libsystem_pthread.dylib        0x1992ebb28 _pthread_body + 156
8  libsystem_pthread.dylib        0x1992eba8c _pthread_body + 154
9  libsystem_pthread.dylib        0x1992e9028 thread_start + 4

**Comment by SlaunchaMan** [comment]
The “XPC API Misuse: Given object not of required type.” message in the log makes me think the crash is from opening the Settings app, not AFNetworking. Try filing a bug with Apple?
