### ISSUE TITLE
How to save pdf file into device ?

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [AFNetworking/AFNetworking#3910]
NSString *filename = @"test";
    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
    AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];
    
    NSString *urlString = [NSString stringWithFormat:@"url?id=%@",@"22"];
    
    NSURL *URL = [NSURL URLWithString:urlString];
    NSURLRequest *request = [NSURLRequest requestWithURL:URL];
        NSURLSessionDownloadTask *downloadTask = [manager downloadTaskWithRequest:request progress:nil destination:^NSURL *(NSURL *targetPath, NSURLResponse *response)
         {
    
            ` NSURL *documentsDirectoryURL = [[NSFileManager defaultManager] URLForDirectory:NSDocumentDirectory inDomain:NSUserDomainMask appropriateForURL:nil create:NO error:nil];
        return [documentsDirectoryURL URLByAppendingPathComponent:[response suggestedFilename]];`
     } completionHandler:^(NSURLResponse *response, NSURL *filePath, NSError *error)
                                              {
    NSLog(@"%@", filePath.path);
                                                  
     `  }];
    
    [downloadTask resume];
`
`
could you please help me

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
