### ISSUE TITLE
Parameters lost

### ISSUE THREAD

**Issue by winterlow** [AFNetworking/AFNetworking#3911]
I used the 2.+ for the two request who needs keep sessions,and it worked.But when I changed it to 3.1.0,the first request is allright,the second failed,and I saw the request on the server had no parameters,all the parameters became null,what happened? Help!Help!Help!

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
