### ISSUE TITLE
Logic error in AFURLRequestSerialization.h

### ISSUE THREAD

**Issue by nzmb** [AFNetworking/AFNetworking#3916]
`Line 646: @property (readwrite, nonatomic, copy) NSMutableURLRequest *request;`

Using AFNetworking (3.1.0)

> **Logic error**
> Property of mutable type 'NSMutableURLRequest' has 'copy' attribute; an immutable object will be stored instead

**Comment by fanyanming** [comment]
I have the same problem, when analyzing the project.

**Comment by yikibug** [comment]
I have the same problem, when analyzing the project in Xcode 8.3.2
How to solve this problem?

**Comment by tewha** [comment]
This would be a great thing to have fixed. That said, it's an analyzer issue and you can probably just ignore it.

**Comment by ghmlee** [comment]
```
@property (readwrite, nonatomic, strong) NSMutableURLRequest *request;
```

```
self.request = [urlRequest mutableCopy];
```

**Comment by LiLejia** [comment]
https://developer.apple.com/videos/play/wwdc2017/411/

Or can explicit change the setter to `_ request = [request mutableCopy];` it would be more friendly.

**Comment by funnel20** [comment]
@ghmlee Great suggestion, thank you.
We have changed this manually in our production code as we want to ship apps without any Xcode warnings, bot from Compiler and Analyzer.

**Comment by funnel20** [comment]
@SlaunchaMan Hi, it's great to finally see a new official release (3.2.0).
It would be great to have these Xcode warnings solved as well.
Can I contribute by creating a PR?

**Comment by funnel20** [comment]
Version 3.2.0 contains the following setter:
```ObjC
- (void)setRequest:(NSMutableURLRequest *)request
{
    _request = [request mutableCopy];
}
```

As a result Xcode Analyzer doesn't complain anymore. Verified with Xcode 9.2.

This issue can be closed.
