### ISSUE TITLE
memory Leaks

### ISSUE THREAD

**Issue by mitchell-dream** [AFNetworking/AFNetworking#3930]
### A Memory Leak about OS_dispatch_source
My Project use AF 3.0. When I use instrument to test our app, their is a memory leak problem about OS_dispatch_source in CFNetwork, I am not sure it is caused by AF. 
<img width="1001" alt="2017-04-12 7 26 06" src="https://cloud.githubusercontent.com/assets/9442979/24955566/8efd91dc-1fb6-11e7-856b-c32a44c5fe04.png">

### Call Tree
<img width="1008" alt="2017-04-12 7 25 46" src="https://cloud.githubusercontent.com/assets/9442979/24955616/b30bc01c-1fb6-11e7-933e-a63f1744a6fc.png">

**Comment by nzmb** [comment]
Try to review your code for such place where you initialize `[AFHTTPSessionManager manager]`

```
if (!manager)
    manager = [AFHTTPSessionManager manager]
```

I faced same memory leaks after implementation above checking the problem was solved.
In my case whole part of the code was:

```
if (!manager)
{
    manager = [AFHTTPSessionManager manager];

    AFJSONResponseSerializer * responseSerializer = [AFJSONResponseSerializer serializer];
    [responseSerializer setAcceptableContentTypes:[NSSet setWithObject:@"application/json"]];
    [manager setResponseSerializer:responseSerializer];
        
    AFJSONRequestSerializer * requestSerializer = [AFJSONRequestSerializer serializer];
    [manager setRequestSerializer:requestSerializer];
}
```
