### ISSUE TITLE
Property of mutable type 'NSMutableURLRequest' has 'copy' attribute; an immutable object will be stored instead

### ISSUE THREAD

**Issue by Uliori** [AFNetworking/AFNetworking#3933]
When Analyzing my project, I get that issue : /Project/Pods/AFNetworking/AFNetworking/AFURLRequestSerialization.m:646:1: Property of mutable type 'NSMutableURLRequest' has 'copy' attribute; an immutable object will be stored instead

![screen shot 2017-04-14 at 6 21 40 pm](https://cloud.githubusercontent.com/assets/10160533/25050430/5673a1aa-213f-11e7-8fd8-406b47721ed2.png)

**Comment by nzmb** [comment]
duplicated with [Logic error in AFURLRequestSerialization.h #3916](https://github.com/AFNetworking/AFNetworking/issues/3916)
