### ISSUE TITLE
-1005 error occurs when the network is normal.

### ISSUE THREAD

**Issue by Esllesr** [AFNetworking/AFNetworking#3937]
In the case of normal network, the use of AF3.0 will be a -1005 error occurs, but when the server changes the timeout parameter becomes larger, there will be no -1005 error. However, these anomalies in the use of CFNetwork based ASIHTTPRequest will not appear, this is why? Can anyone explain this to me? What is the reason?

**Comment by Cooriyou** [comment]
same as u

**Comment by PSSDeveloper** [comment]
me too.

**Comment by Esllesr** [comment]
Maybe I know the reason. You can see this link: http://www.jianshu.com/p/2e7200bd5b79. May be helpful.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
