### ISSUE TITLE
Code=-1001 "The request timed out" Issue

### ISSUE THREAD

**Issue by totoourworld** [AFNetworking/AFNetworking#3939]
First of All,  thanks for your providing such this wonderful framework.
I used AFNetworking framework in previous projects and worked well.
So I am using this framework as no.1 for network related.
Currently , i am working on one project and it is requiring HTTPS POST request.
I used AFHTTPRequestOperationManager for this.
Tried to google for this code and I made the code like as below.

/************************************************* code *****************************************************/
    AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
    manager.securityPolicy.allowInvalidCertificates=YES;
    manager.requestSerializer = [AFJSONRequestSerializer serializer];
    manager.responseSerializer = [AFJSONResponseSerializer serializer];
    NSDictionary *params = @{@"email": username,
                             @"password": password};
    [manager.requestSerializer setTimeoutInterval:100];
    [manager POST:@"https://www.revbits.co:8443/api/check_user" parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {
        NSLog(@"JSON: %@",responseObject);
    } failure:^(AFHTTPRequestOperation operation, NSError error) {
        NSLog(@"Error: %@", error);
    }];
/************************************************* code *****************************************************/

I ran the debug and got below issue.
/*************************************************DEBUG RESULT *****************************************/
Error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x170245a00 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.revbits.co:8443/api/check_user, NSErrorFailingURLKey=https://www.revbits.co:8443/api/check_user, kCFStreamErrorCodeKey=-2102, kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=https://www.revbits.co:8443/api/check_user, NSErrorFailingURLKey=https://www.revbits.co:8443/api/check_user, kCFStreamErrorDomainKey=4, kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}
/************************************************DEBUG RESULT******************************************/

Can you give me some reason for this ?
In additional, I checked the url using 'curl -k -x POST "https://www.revbits.co:8443/api/check_user"
But it has got the return code , so i thought the api is working.
Can anybody advise for this?
I am really stuck on mad for  1 week for this problem.

Regards.

**Comment by tewha** [comment]
Have you tried `nscurl` yet? (`nscurl --help` shows the help page)

**Comment by totoourworld** [comment]
Thanks for your reply.
That was the problem with server side blocking the ip address.
Regards.
Ps: I love the AFNetworking Framework.
