### ISSUE TITLE
Not working on production server

### ISSUE THREAD

**Issue by techmehra** [AFNetworking/AFNetworking#3940]
Yesterday I got a strange issue while communicating with my web service through AFNetworking.
I am able to receive response from my development server but when I change my API route to production server it stop getting response from server 
Live server response is working fine on android and postman. 
Our server is developed in PHP.
After communicating with API Web Service developer. We are found that server is able to get data from request 

After that, I hit the web service with NSURLSession class and I am able to get response

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
