### ISSUE TITLE
403

### ISSUE THREAD

**Issue by wasterd** [AFNetworking/AFNetworking#3941]
The first request for success, second request to go the way of success, but reported a 403 error！why？
response code:登录成功Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x60000023afc0> { URL: http://xxxx.xxxx.xxxx.com/xxx/login?_format=json } { status code: 403, headers {

**Comment by tewha** [comment]
It's your server returning 403.

**Comment by wasterd** [comment]
We backstage personnel in the URL to join the cookie, I clear the cookie will not report 403

**Comment by wasterd** [comment]
However, I have a question: why is the first time I request to get data, and in the second request, header will have a cookie, you cache policy in the existence of cookie?

**Comment by maliha-wiva** [comment]
i am facing the same issue and recheck my code. its due the the same file name as with already uploaded a file
