### ISSUE TITLE
seTimeoutInterval crash

### ISSUE THREAD

**Issue by xueselangman91** [AFNetworking/AFNetworking#3942]
[self.mutableObservedChangedKeyPaths addObject:keyPath];    when it comes to this code,it crashes,and that is when it was running after setTimeoutInterval;

**Comment by xumeng** [comment]
I have this problem too. Have AFNetworking resolved it?
btw:I writed the network request code in custom thread.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).

**Comment by codeflayer** [comment]
Me too, nobody fix it?
