### ISSUE TITLE
still timeout after I suspend  NSURLSessionDataTask. AFN3.1.0

### ISSUE THREAD

**Issue by braveeeehu** [AFNetworking/AFNetworking#3945]
Xcode 8.3.1   iOS 10.2.1
I  init NSURLSessionDataTask with follow method

`- (NSURLSessionDataTask *)dataTaskWithRequest:(NSURLRequest *)request
                            completionHandler:(nullable void (^)(NSURLResponse *response, id _Nullable responseObject,  NSError * _Nullable error))completionHandler;`

then call `setDataTaskDidReceiveResponseBlock` and `setDataTaskDidReceiveDataBlock` to write data to file.
and then I call `suspend` but the after the timeoutInterval I get  completionHandler with timeout error.

**Comment by wujianbotju** [comment]
+1. It also happened to me.

**Comment by czqiang1992** [comment]
It also confused me ,Don't kown how to slove it.
