### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-999 "cancelled"

### ISSUE THREAD

**Issue by techmehra** [AFNetworking/AFNetworking#3946]
Everything is working fine when working in Xcode 7, but not working in Xcode 8 above

- (void)POSTInfoRequestWithURLString:(NSString *)URLString parameters:(BFJSONSerializableObject *)parameters completionBlock:(BFAPIInfoCompletionBlock) block {
    NSError *error;
    NSDictionary *dictParameters = [parameters JSONDictionaryWithError:&error];
	NSLog(@"Request parameter >>>>>>>>%@\n", dictParameters);
    if(error) {
        if(block) {
            block(nil, error);
        }
    }
    else {
        [self POST:URLString parameters:dictParameters progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
            if (block) {
				NSString * temp = [[NSString alloc] initWithData:responseObject encoding:NSASCIIStringEncoding];
				NSLog(@"Response  >>>>>>>>%@\n", temp);
                block(responseObject, nil);
            }
        } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
            if (block) {
				NSLog(@"Error  >>>>>>>>%@\n", error);
                block(nil, error);
            }
        }];
    }
}

**Comment by hazelement** [comment]
Experiencing the same issue here. Even deployed apps see the error popped up, they weren't complaining before. I'm using SSL certificate pinning.

**Comment by jakobsa** [comment]
I can confirm that certificate pinning is somehow involved.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
