### ISSUE TITLE
AFHTTPSessionManager Leak issue unsolved mystory

### ISSUE THREAD

**Issue by vickydhas** [AFNetworking/AFNetworking#3947]
Hello Team,

Good work on such an awesome library. I am facing a leaks issue on following files always.

Have tried from the other sources and issue list in this repo for _**invalidatesessionbyCancellingtask:**_ but none have worked. I still get the leaks shown at these lines for all the services I have created.

  ```
AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
  manager.responseSerializer = [AFJSONResponseSerializer serializer];
  manager.requestSerializer = [AFJSONRequestSerializer serializer];
```

Attached the Image as well for reference for one of the file.

![screen shot 2017-05-12 at 6 50 39 pm](https://cloud.githubusercontent.com/assets/834663/25995257/f4d759da-3743-11e7-83f7-63384b21d16a.png)

**Comment by ytmoye** [comment]
@vickydhas hello, i suggest that you can use "dispatch_once" to create AFHTTPSessionManager. And the leaks maybe disappear.

`+ (AFHTTPSessionManager *)sharedAFHTTPManager
{
    static AFHTTPSessionManager *AFHTTPManager;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        AFHTTPManager = [AFHTTPSessionManager manager];
        AFHTTPManager.requestSerializer = [AFJSONRequestSerializer serializer];
        AFHTTPManager.responseSerializer = [AFJSONResponseSerializer serializer];
    });
    return AFHTTPManager;
}`

**Comment by vickydhas** [comment]
I will check this and let you know thanks for valuable input given.
-- 
Sent from my iPhone6+

**Comment by Dying5566** [comment]
I user "dispatch_once"",but How to update http headers?

**Comment by ytmoye** [comment]
Unfortunately, it is unconvenient to set HttpHeaders for some requests beause of singleton. But most of the time our httpHeaders is set to the same. You can set it separately for a few special requests before generate task, and reset it after task is generated. Or create a new manager which is not a singleton for special requests.
