### ISSUE TITLE
pod update doesn't download all source files because of podspec definition error

### ISSUE THREAD

**Issue by sopracreau** [AFNetworking/AFNetworking#3948]
The podspec is not complete. It causes error when first building app because cocoapod does not download all files. 
The source files for subspec UIKit need to change. 
You can see a fix in the attaching file.
[AFNetworking.podspec.txt](https://github.com/AFNetworking/AFNetworking/files/997095/AFNetworking.podspec.txt)

**Comment by sopracreau** [comment]
Only the 2 lines in the end are wrong 
    ss.public_header_files = 'UIKit+AFNetworking/{AF,UI}*.h'
    ss.source_files = 'UIKit+AFNetworking/{AF,UI}*.{h,m}'

Thank you in advance for this little fix

**Comment by SlaunchaMan** [comment]
It looks like the existing patterns already match these:

```Ruby
ss.public_header_files = 'UIKit+AFNetworking/*.h'
ss.source_files = 'UIKit+AFNetworking'
````

The header files match all `.h` files in the directory, and the source files are the entire `UIKit+AFNetworking` directory.

Moreover, I was able to build a sample app using `AFNetworkActivityIndicatorManager` successfully with this Podfile:

```Ruby
target 'AFNetworkingUIKitTest' do
	pod 'AFNetworking/UIKit'
end
```
