### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by victorstewart** [AFNetworking/AFNetworking#3949]
Getting an unsupported URL error for this link...

i.cdn.cnn.com/cnn/.e/img/3.0/global/misc/apple-touch-icon.png

(and I tried with https://)

Anything I can do here?

**Comment by Jackielc** [comment]
This url is not supported under iOS URL Loading System. Please communicate with the server and support both iOS and Android

**Comment by tewha** [comment]
https:// is indeed what's missing, so I'd try whatever you did again.
