### ISSUE TITLE
copy -> strong ?

### ISSUE THREAD

**Issue by wanshanhu79** [AFNetworking/AFNetworking#3950]
@interface AFStreamingMultipartFormData ()
** @property (readwrite, nonatomic, copy) NSMutableURLRequest *request; **
@property (readwrite, nonatomic, assign) NSStringEncoding stringEncoding;
@property (readwrite, nonatomic, copy) NSString *boundary;
@property (readwrite, nonatomic, strong) AFMultipartBodyStream *bodyStream;
@end

**copy -> strong

**Comment by tewha** [comment]
Dupe of #3916, I believe.
