### ISSUE TITLE
Use of undeclared identifier AFNetworkReachabilityManager with additional Watch OS target in project

### ISSUE THREAD

**Issue by avsmirnov567** [AFNetworking/AFNetworking#3952]
Hi, I'm importing <AFNetworking/AFNetworking.h> to my class and trying to use [AFNetworkReachabilityManager sharedManager]. But I always getting "Use of undeclared identifier" error. I think, that it is because my iOS project contains additional WatchOS target. In AFNetworking.h I've found this:

```
#if !TARGET_OS_WATCH
    #import "AFNetworkReachabilityManager.h"
#endif
```

My podfile looks like:

```
use_frameworks!
inhibit_all_warnings!

def shared_pods
      pod 'AFNetworking'
end

target 'Find My Kids' do
     platform :ios, '9.0'
     shared_pods
end

target 'Find My Kids Watch Extention' do
     platform :watchos, '2.0'
     shared_pods
end

```
If I'm right, how can I organize my podfile or project in order to get access to ReachabilityManager in iOS target? Thank you!

**Comment by SlaunchaMan** [comment]
Are you trying to use the reachability manager from your watchOS code? It’s not available on watchOS, but that configuration should work on iOS.

**Comment by avsmirnov567** [comment]
Thank you for replying! The problem was exactly there. I was trying to use the reachability manager from code, that compiles for watchOS also.
