### ISSUE TITLE
Crash in AFAssetDownloadManager.m line 145

### ISSUE THREAD

**Issue by mayur43s** [AFNetworking/AFNetworking#3956]
I'm getting a crash in AFAssetDownloadManager.m line 145. 
Here's fabric description of crash: 
![crash report](https://cloud.githubusercontent.com/assets/5563481/26442005/6292a96e-4150-11e7-86c9-886b37a29c46.png)

**Comment by SlaunchaMan** [comment]
Is AFAssetDownloadManager a class you wrote? There doesn’t appear to be such an `.m` file in this project.
