### ISSUE TITLE
好多内存泄漏 (memory leak)

### ISSUE THREAD

**Issue by hw20101101** [AFNetworking/AFNetworking#3957]
![wx20170525-161312](https://cloud.githubusercontent.com/assets/9107226/26441999/52649d76-4165-11e7-99d4-d16b944ff7d1.png)

**Comment by lbwnh123** [comment]
用单例

**Comment by ZeroOnet** [comment]
单例模式也不能完全解决内存泄露问题，只能减少

**Comment by SlaunchaMan** [comment]
As the comment says, sometimes `-uploadTaskWithRequest:fromFile:` will erroneously return `nil`, so even though this is all marked non-null, it’s possible to return `nil`.
