### ISSUE TITLE
Crash in file 'AFURLSessionManager.m' line 461

### ISSUE THREAD

**Issue by lwl19891025** [AFNetworking/AFNetworking#3958]
Xcode8.3.2 
iOS7.1.2
iPhone 4 GSM
Application received signal SIGSEGV
(null)
((
	0   CoreFoundation                      0x30c7bf9b <redacted> + 154
	1   libobjc.A.dylib                     0x3b42cccf objc_exception_throw + 38
	2   CoreFoundation                      0x30c7bec5 <redacted> + 0
	3   myApp                           0x3ee843 myApp + 4106307
	4   libsystem_platform.dylib            0x3ba53f8b _sigtramp + 34
	5   CFNetwork                           0x308eff95 <redacted> + 488
	6   CFNetwork                           0x308eff95 <redacted> + 488
	7   CFNetwork                           0x308f054d <redacted> + 60
	8   libdispatch.dylib                   0x3b91481f <redacted> + 22
	9   libdispatch.dylib                   0x3b926c9b <redacted> + 226
	10  CFNetwork                           0x30895ca1 <redacted> + 100
	11  **myApp                           0x96071 myApp + 598129**
	12  myApp                           0x19a813 myApp + 1665043
	13  myApp                           0x19aaef myApp + 1665775
	14  CFNetwork                           0x308953d5 <redacted> + 116
	15  Foundation                          0x315c03c7 <redacted> + 130
	16  Foundation                          0x315b05ab <redacted> + 770
	17  Foundation                          0x3165476d <redacted> + 60
	18  libdispatch.dylib                   0x3b91481f <redacted> + 22
	19  libdispatch.dylib                   0x3b914777 <redacted> + 254
	20  CoreFoundation                      0x30c468a1 <redacted> + 8
	21  CoreFoundation                      0x30c45175 <redacted> + 1300
	22  CoreFoundation                      0x30bafebf CFRunLoopRunSpecific + 522
	23  CoreFoundation                      0x30bafca3 CFRunLoopRunInMode + 106
	24  GraphicsServices                    0x35ab5663 GSEventRunModal + 138
	25  UIKit                               0x334fc14d UIApplicationMain + 1136
	26  myApp                           0x33c5f myApp + 195679
	27  libdyld.dylib                       0x3b939ab7 <redacted> + 2
)
0x000c429d:     TAG_subprogram [162] *
                 AT_low_pc( 0x00096044 )
                 AT_high_pc( 0x000960c0 )
                 AT_frame_base( r7 )
                 AT_object_pointer( {0x000c42b7} )
                 AT_name( "-[_AFURLSessionTaskSwizzling af_resume]" )
                 AT_decl_file( "***/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m" )
                 AT_decl_line( 458 )
                 AT_prototyped( 0x01 )
                 AT_APPLE_optimized( 0x01 )
                 AT_APPLE_isa( 0x01 )
Line table dir : '***/Pods/AFNetworking/AFNetworking'
Line table file: 'AFURLSessionManager.m' line 461, column 5 with start address 0x000000000009605e # #

**Comment by wenyhooo** [comment]
?????

**Comment by SlaunchaMan** [comment]
Can you post a symbolicated crash report? Is this still happening?

**Comment by lwl19891025** [comment]
@SlaunchaMan we have changed the deployment target to 8.0+, so we have no more information now.

**Comment by lwl19891025** [comment]
changed the deployment target to 8.0+
