### ISSUE TITLE
error：3840 

### ISSUE THREAD

**Issue by liuniuliuniu** [AFNetworking/AFNetworking#3959]
rror.descriptionError Domain=NSCocoaErrorDomain Code=3840 "Unescaped control character around character 3342." UserInfo={NSDebugDescription=Unescaped control character around character 3342.}

**Comment by yinqiangw** [comment]
_sharedClient.responseSerializer = [AFJSONResponseSerializer serializerWithReadingOptions:NSJSONReadingAllowFragments];

Can't work for me!

What's the solution?

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
