### ISSUE TITLE
Initialization BOOL property of AFHTTPRequestSerializer

### ISSUE THREAD

**Issue by scfhao** [AFNetworking/AFNetworking#3963]
AFHTTPRequestSerializer class has two `BOOL` properties, `allowsCellularAccess` and `HTTPShouldHandleCookies`, who's default value is `YES`. But in `init`method of AFHTTPRequestSerializer class, there have not set those value to `YES`.

So, when I read value of those properties, I got `NO` not `YES`.

**Comment by skyline75489** [comment]
Why would you want to read the those values in the first place?

**Comment by scfhao** [comment]
In my setting page, I want add a UISwitch control to show whether allow to use cellular network, user can also setting this value by the way. I read `allowsCellularAccess` property to init this switch control's status.
