### ISSUE TITLE
How to set the request parameters to GBK encoding?

### ISSUE THREAD

**Issue by JiaoYingBo** [AFNetworking/AFNetworking#3967]
I set it like this:

    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    manager.requestSerializer = [AFJSONRequestSerializer serializer];
    NSStringEncoding GBK_Encoding = CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_18030_2000);
    manager.requestSerializer.stringEncoding = GBK_Encoding;

But it doesn't work. And I found the method`- (NSURLRequest *)requestBySerializingRequest:(NSURLRequest *)request withParameters:(id)parameters error:(NSError *__autoreleasing *)error`in `AFURLRequestSerialization`didn't use the property `stringEncoding`. Is there any other solution? Or it is a design defects?

**Comment by skyline75489** [comment]
See #3751
