### ISSUE TITLE
Xcode 9 warning: Unknown warning group '-Wreceiver-is-weak', ignored

### ISSUE THREAD

**Issue by Whirlwind** [AFNetworking/AFNetworking#3968]
```
/AFNetworking/UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m:76:34: warning: unknown warning group '-Wreceiver-is-weak', ignored [-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wreceiver-is-weak"
                                 ^
/AFNetworking/UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m:97:34: warning: unknown warning group '-Wreceiver-is-weak', ignored [-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wreceiver-is-weak"
                                 ^
/AFNetworking/UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m:106:34: warning: unknown warning group '-Wreceiver-is-weak', ignored [-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wreceiver-is-weak"
                                 ^
3 warnings generated.
```

**Comment by hank-ehly** [comment]
@Whirlwind 

The `receiver-is-weak` compiler warning is said [here](http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20150309/125204.html) to have been removed from the clang codebase in favor of the "better" `arc-repeated-use-of-weak` warning; however, the date of this ticket is March 10th, 2015, which confuses me because we are just now seeing this.

Because `arc-repeated-use-of-weak` is a replacement for `receiver-is-weak`, and `unknown-warning-option` is simply a warning about an unknown compiler option, it may be safe to completely ignore this; however, if your customers demand "zero warnings" then this may need to be taken care of.

**Comment by dpfannenstiel** [comment]
Is a version with the updated code scheduled to come out prior to the Xcode 9 release?

**Comment by anderscarling** [comment]
Since these warnings are only occurring in the `UIKit` subspec, they can be avoided by explicitly using only the `NSURLSession` subspec.

`NSURLSession` depends on all the other subspecs except `UIKit`, so most users can probably just change their `Podfile` to `pod 'AFNetworking/NSURLSession'`. Unless you actually use the `UIKit` extensions everything should just keep working.

**Comment by zapjonny** [comment]
Fix coming up?

**Comment by ecaselles** [comment]
Taking into account that the last release is 80 commits away from master, it sounds about time a new tagged release is made. Any plans on doing so @kcharwood @kylef & Company? 🙏

**Comment by hellohufan** [comment]
Come on, super man,answer the question.

**Comment by moazkh60** [comment]
Waiting for an answer

**Comment by dpfannenstiel** [comment]
While waiting for the fix to be published I have forked the project and then started using my forked version of AFNetworking to continue working.  Just change the pod declaration in your pod file.
```
pod 'AFNetworking', :git => 'https://github.com/<FORKING_ORG>/AFNetworking.git', :branch => '<BRANCH_NAME>'
```

**Comment by samchen945** [comment]
Wait for the release here too.

**Comment by zapjonny** [comment]
Is this maintained at all anymore? Last commit is in July...

**Comment by ivulyov90** [comment]
There are more warnings in Xcode 9.0.1

/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m:163:30: 'setResumingHandler:' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSProgress.h:150:35: 'setResumingHandler:' has been explicitly marked partial here
/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m:163:30: Enclose 'setResumingHandler:' in an @available check to silence this warning
/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m:181:32: 'setResumingHandler:' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSProgress.h:150:35: 'setResumingHandler:' has been explicitly marked partial here
/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m:181:32: Enclose 'setResumingHandler:' in an @available check to silence this warning

**Comment by XcqRomance** [comment]
me too, Any one solved these warnings.

**Comment by SlaunchaMan** [comment]
I'm going to try to get a release out soon.

**Comment by z2xy** [comment]
yeeeeeeeears went by ...

**Comment by moazkh60** [comment]
We are waiting.

**Comment by dpfannenstiel** [comment]
If you're using pods, I found an alternate solution
```
    pod 'AFNetworking', '3.1.0', :inhibit_warnings => true 
```

Cocoapods realizes that this is a thing.  That consumers of a pod might not have control over the source.  So by setting `inhibit_warnings` to true it will silence warnings on the pod when installing it.  It doesn't remove the warning, but that was never my problem.  I wanted my project down at 0 warnings.  And now I have it and I continue to trust that the pod maintainer knows that these warnings may be safely ignored.

**Comment by evictor** [comment]
@dpfannenstiel why did I not know about this sooner. 😒  Thanks a ton.

**Comment by SlaunchaMan** [comment]
The current release should have fixed this; please feel free to re-open if not.
