### ISSUE TITLE
 In iOS 9.x-8.x crashes on the issue SEGV_ACCERR ( CoreFoundation _CFBasicHashGetBucket)

### ISSUE THREAD

**Issue by Cooriyou** [AFNetworking/AFNetworking#3971]
There is about 0.02% crash rate on  CoreFoundation _CFBasicHashGetBucket  

Only crash on  iOS 8.x  to iOS 9.x  ,without iOS 10.x

<img width="587" alt="screen shot 2017-06-16 at 10 59 20 am" src="https://user-images.githubusercontent.com/16461292/27210146-ee017f32-5282-11e7-8277-d846911f6b38.png">

I don't know why ？ how to fixed it.

**Comment by SlaunchaMan** [comment]
Hard to say what’s going on from that screenshot; I don't even see any AFNetworking code. This should probably be in a bug report to Apple. If you can find out anything that points to AFNetworking please re-open this or make a new issue.

**Comment by BaihaoTian** [comment]
I want to say this crash also happened to my app, and cause a lots of crash
