### ISSUE TITLE
AFNetworking Error Domain=NSURLErrorDomain Code=-1005  

### ISSUE THREAD

**Issue by nadagamal** [AFNetworking/AFNetworking#3973]
Randomly getting Error Domain=NSURLErrorDomain Code=-1005 “The network connection was lost.” at all OSs and different devices with different network connections at different time.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
