### ISSUE TITLE
Callbacks not invoked for background upload tasks with error code -999 kCFURLErrorCancelled

### ISSUE THREAD

**Issue by charshep** [AFNetworking/AFNetworking#3976]
According to Apple's docs if the user force quits the app any running background tasks will be canceled, but `NSURLSessionTaskDelegate:URLSession:task:didCompleteWithError:` will still be invoked for each task when the user relaunches the app and the background session is recreated. This does indeed seem to be the case but the delegate method `AFURLSessionManager:URLSession:task:didCompleteWithError:` is losing the race with the init method`AFURLSessionManager:initWithSessionConfiguration:` that recreates all the `AFURLSessionManagerTaskDelegates` that the delegate method relies on.

The way to recreate this bug is to start an upload and then suspend and manually kill the app while the upload is in progress. Relaunch the app. If you insert log statements in the methods mentioned above and watch the output in the console app you'll see that the delegate method gets called for the canceled tasks before the initializer can recreate their delegates.

It's necessary to propagate these canceled callbacks to to the host app so that any necessary cleanup, retries, etc can be performed.

Xcode 8.3.2 iOS 10

**Comment by charshep** [comment]
I have a quick fix in place based on dispatch_semaphore_t but no tests written. I can flesh it out some more and submit a pull request but it doesn't look like AFNetworking is being actively maintained at this time?

**Comment by SlaunchaMan** [comment]
AFNetworking is being actively maintained; please do send in that PR!
