### ISSUE TITLE
post file can't callback progress block

### ISSUE THREAD

**Issue by Petarding** [AFNetworking/AFNetworking#3978]
when I used this method ,I can't get the progress block call back ，so I want someone can help me  thank you ！

 NSMutableURLRequest *request = [[AFHTTPRequestSerializer serializer]multipartFormRequestWithMethod:@"POST" URLString:url parameters:parmater constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
        block(formData);
    } error:nil];
    NSURLSessionUploadTask *uploadTask;
    uploadTask = [_manager
                  uploadTaskWithStreamedRequest:request
                  progress:^(NSProgress * _Nonnull uploadProgress) {
                      progress (1.0*uploadProgress.completedUnitCount/uploadProgress.totalUnitCount);
                      NSLog(@"responseProgress == %.2f",1.0*uploadProgress.completedUnitCount/uploadProgress.totalUnitCount);
                  }
                  completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
                }];

**Comment by Arpit723** [comment]
Same error, Request is called but finish or failed block is never get called.

**Comment by inputfuture** [comment]
NSMutableURLRequest :

setHTTPBody:     ->    work good
setHTTPBodyStream    ->     not work
