### ISSUE TITLE
AFHTTPBodyPart doesn't get deallocated

### ISSUE THREAD

**Issue by doublecheese** [AFNetworking/AFNetworking#3980]
Hi,

We have the following code:

`
 NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
AFHTTPSessionManager *manager =  [[AFHTTPSessionManager alloc] initWithSessionConfiguration:configuration];
NSURLSessionDataTask *requestOperation = [httpManager POST:uploadUrl parameters:@{} constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        
            [self addFieldsToFormData:formData skipContent:YES];
     
            [formData appendPartWithFileData:currentChunkData
                                        name:@"files[]"
                                    fileName:fileName mimeType:mimeType];`

and on success/failure i call
`[httpManager invalidateSessionCancelingTasks:false];`

But I noticed that the AFHTTPBodyPart doesn't get deallocated and I am left with lots of CFData objects hanging around and not being released. This looks like a memory issue.

**Comment by doublecheese** [comment]
This is probably related to this: https://github.com/AFNetworking/AFNetworking/issues/3790

**Comment by apalvai** [comment]
We are seeing the same issue, whenever our app makes POST request with multi-part form data and it has strong correlation with #3864.

**Comment by EddyLB** [comment]
I also encounter the same issue when making POST requests with multi-part form data.

**Comment by EddyLB** [comment]
Still an issue despite calling [… invalidateSessionCancelingTasks:…]
