### ISSUE TITLE
Library not loaded (xCode)

### ISSUE THREAD

**Issue by ChenCodes** [AFNetworking/AFNetworking#3986]
Hey guys, I got this error after I tried doing Carthage update and putting the line:

github "AFNetworking/AFNetworking" ~> 3.0

Here's the error:
dyld: Library not loaded: @rpath/AFNetworking.framework/AFNetworking
  Referenced from: /var/containers/Bundle/Application/83811799-03C8-47D2-A9C0-54D0E0E676A4/Progressly Dev.app/Progressly Dev
  Reason: image not found

Does anyone know the fix for this? Thanks in advance!

**Comment by ChenCodes** [comment]
Also, something that I noticed was that the installed files were called: AFNetworking.framework.dysm, not AFNetworking.framework, so I can't just import it directly into my project.

**Comment by StrongerWM** [comment]
Here occured similar error. 

dyld: Library not loaded: @rpath/AFNetworking.framework/AFNetworking
Referenced from:.......
Reason: image not found

Try : 
Find your target --> Build Phases --> Add New Copy Files Phase -->Choose Destination Option,Frameworks -->Click add AFNetworking.framework --> Done.

Hope its useful.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).

**Comment by Nautiyalsachin** [comment]
Any help here ? I am also getting the same issue. @SlaunchaMan I tried all the ways which are given on Stackoverflow. Please help me out. 
Tried  downgrading pods 2.5, 2.6.4, latest one, etc..

Thanks for the help!

**Comment by YKV** [comment]
Same error !

dyld: Library not loaded: .framework/AFNetworking
Referenced from:.......
Reason: image not found

**Comment by SlaunchaMan** [comment]
If you're using CocoaPods, try:
* Make sure you're opening the `.xcworkspace` file, _not_ the `.xcodeproj` file.
* Run `pod deintegrate` to remove all CocoaPods files, then `pod install` to re-add them. Sometimes this can fix it.

**Comment by kissoflove** [comment]
I get the same error when I import it with Cocoapods:
Library not loaded: @rpath/AFNetworking.framework/Versions/A/AFNetworking

Below is my solution to fix it 
`# Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
`
comment out **use_frameworks!**

**Comment by JianhuisHuang** [comment]
> * xcworkspace

Yeah, I have fixed it by your answer, thanks.

**Comment by JianhuisHuang** [comment]
> If you're using CocoaPods, try:
> 
> * Make sure you're opening the `.xcworkspace` file, _not_ the `.xcodeproj` file.
> * Run `pod deintegrate` to remove all CocoaPods files, then `pod install` to re-add them. Sometimes this can fix it.

Yeah, I have fixed it by your answer, thanks.
