### ISSUE TITLE
Instruments suggest memory leaks

### ISSUE THREAD

**Issue by lizuba** [AFNetworking/AFNetworking#3987]
when i use the instruments to check memory leaks,  and it tell me that i have much about leaks ,instruments help me locate the mistake, it finds that url have the memory leaks. i never encounter this error before.  the url is like this:"www.google.com"  it's normal
```
    NSParameterAssert(method);
    NSParameterAssert(URLString);

    NSURL *url = [NSURL URLWithString:URLString];

    NSParameterAssert(url);
```

**Comment by LIZUBA** [comment]
i have try to run afnetworking example and why it's also have memory leaks.  why?

**Comment by OrangeVarko** [comment]
maybe you should called [manager.session finishTasksAndInvalidate]

**Comment by LIZUBA** [comment]
i have try this method before but it still does not work.
