### ISSUE TITLE
AfNetworking Domain=NSURLErrorDomain Code=-1004 after few launch app  Ask

### ISSUE THREAD

**Issue by nadagamal** [AFNetworking/AFNetworking#3988]
The below issue appeared sometimes when I launch the app immediately when the push notification received and if I wait more than 10 seconds after receiving the push then open the push , the request is succeeded and In case of failure the http status code is zero and all requests are https and please note that the request failed after a few seconds and I use the default time out of AFnetworking which is 60 seconds.

Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x170454940 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "Could not connect to the server." UserInfo={NSErrorFailingURLStringKey=, NSErrorFailingURLKey=, _kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1, NSLocalizedDescription=Could not connect to the server.}}, NSErrorFailingURLStringKey=, NSErrorFailingURLKey=, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.}

**Comment by barneychen** [comment]
Any idea?

**Comment by sakshijoshi** [comment]
I have same issue

**Comment by nadagamal** [comment]
@barneychen  & @sakshijoshi  The issue is from the server side. Please check the SSL certificate installation .

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
