### ISSUE TITLE
question  init

### ISSUE THREAD

**Issue by eliganel** [AFNetworking/AFNetworking#3990]
AFHTTPRequestSerializer class has two BOOL properties, allowsCellularAccess and HTTPShouldHandleCookies, who's default value is YES. But in init method of AFHTTPRequestSerializer class, there have not set those value to YES.

So, when I read value of those properties, I got NO not YES.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
