### ISSUE TITLE
.txt file not able to dwonload from server.

### ISSUE THREAD

**Issue by tikamsingh** [AFNetworking/AFNetworking#3994]
I am using 3.0 Afnetwroking framework , it working fine for downloading json file but

.txt file not able to  downoload  

I have tried to add below code but still not getting download.
self.responseSerializer.acceptableContentTypes = [NSSet setWithObject:@"text/plain"];
Please suggest 

Error:
 rror Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x608000227320> { URL: http://backgrounds.xxx.com/xxx/xxx.txt/ } { status code: 403, headers {
    "Content-Length" = 887;
    "Content-Type" = "application/octet-stream";
    Date = "Thu, 13 Jul 2017 13:00:05 GMT";
    Etag = "\"03f1598800a2e5aca123e0dc9d5365a4\"";
    "Last-Modified" = "Sun, 12 Apr 2015 01:19:02 GMT";
    Server = AmazonS3;
    "x-amz-error-code" = AccessDenied;
    "x-amz-error-message" = "Access Denied";
    "x-amz-id-2" = "fDEgT3VtO8Fa6eECD1DzwIl4JJr3sFARAar/TUj22bDQ4/CHg8CNstkD9ouZayAs+3c5RMgDbVM=";
    "x-amz-request-id" = C189F9A3E23F447E;
} }, NSErrorFailingURLKey=http://backgrounds.xxx.com/xxx/xxx.txt/, com.alamofire.serialization.response.error.data=<7b0a2262 61736522 3a226874 74703a5c 2f5c2f62 61636b67 726f756e 64732e64 65786174 692e636f 6d5c2f22 2c0a2269 6d616765 73223a5b 7b227468 756d626e 61696c22 3a227468 756d6266 6c6f7765 7273312e 6a706722 2c22696d 61676522 3a22666c 6f776572 73312e6a 7067227d 2c0a2009 20202020 20207b22 7468756d 626e6169 6c223a22 7468756d 626e6174 75726531 2e6a7067 222c2269 6d616765 223a226e 61747572 65312e6a 7067227d 2c0a0909 20207b22 7468756d 626e6169 6c223a22 7468756d 626e6174 75726532 2e6a7067 222c2269 6d616765 223a226e 61747572 65322e6a 7067227d 2c0a0909 20207b22 7468756d 626e6169 6c223a22 7468756d 62776174 65726661 6c6c7331 2e6a7067 222c2269 6d616765 223a2277 61746572 66616c6c 73312e6a 7067227d 2c0a0909 20207b22 7468756d 626e6169 6c223a22 7468756d 62726169 6e626f77 312e6a70 67222c22 696d6167 65223a22 7261696e 626f7731 2e6a7067 227d2c0a 09092020 7b227468 756d626e 61696c22 3a227468 756d6277 61746572 66616c6c 73352e6a 7067222c 22696d61 6765223a 22776174 65726661 6c6c7335 2e6a7067 227d2c0a 09092020 7b227468 756d626e 61696c22 3a227468 756d6277 61746572 66616c6c 73322e6a 7067222c 22696d61 6765223a 22776174 65726661 6c6c7332 2e6a7067 227d2c0a 09092020 7b227468 756d626e 61696c22 3a227468 756d6266 6c6f7765 7273322e 6a706722 2c22696d 61676522 3a22666c 6f776572 73322e6a 7067227d 2c090a09 0920207b 22746875 6d626e61 696c223a 22746875 6d626e61 74757265 332e6a70 67222c22 696d6167 65223a22 6e617475 7265332e 6a706722 7d2c0a09 0920207b 22746875 6d626e61 696c223a 22746875 6d626e61 74757265 342e6a70 67222c22 696d6167 65223a22 6e617475 7265342e 6a706722 7d2c0a09 0920207b 22746875 6d626e61 696c223a 22746875 6d62666c 6f776572 73332e6a 7067222c 22696d61 6765223a 22666c6f 77657273 332e6a70 67227d2c 0a090920 207b2274 68756d62 6e61696c 223a2274 68756d62 77617465 7266616c 6c73332e 6a706722 2c22696d 61676522 3a227761 74657266 616c6c73 332e6a70 67227d2c 0a090920 207b2274 68756d62 6e61696c 223a2274 68756d62 77617465 7266616c 6c73342e 6a706722 2c22696d 61676522 3a227761 74657266 616c6c73 342e6a70 67227d09 0a5d7d>, NSLocalizedDescription=Request failed: forbidden (403)}

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
