### ISSUE TITLE
The request attribute in AFStreamingMultipartFormData was Error

### ISSUE THREAD

**Issue by youran1024** [AFNetworking/AFNetworking#3995]
@interface AFStreamingMultipartFormData ()
--
  | @property (readwrite, nonatomic, copy) NSMutableURLRequest *request;

-----------
if the request property is copy, then you assign to the request, the request value will be an **immutable** object.

**Comment by ElfSundae** [comment]
This has been fixed in 00addee8a11a21b3a32b140f404d7443664b1e4f
