### ISSUE TITLE
scalar initializer cannot be empty

### ISSUE THREAD

**Issue by uu1022** [AFNetworking/AFNetworking#3997]
uploadTask = [manager uploadTaskWithStreamedRequest:request progress:(NSProgress *__autoreleasing  _Nullable * _Nullable){
        
    }completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
        
    }];

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
