### ISSUE TITLE
why doesn't intervaltimeout work?

### ISSUE THREAD

**Issue by jaychen04** [AFNetworking/AFNetworking#3998]
[manager.requestSerializer willChangeValueForKey:@"timeoutInterval"];  
    manager.requestSerializer.timeoutInterval = 3.f;  
    [manager.requestSerializer didChangeValueForKey:@"timeoutInterval"]; 

why doesn't intervaltimeout work?
 i know mutablrequest can set intervaltimeout，but i wanna set  a gloabl intervaltimeout.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
