### ISSUE TITLE
No Response for 204 (No content)

### ISSUE THREAD

**Issue by barkiiqbal** [AFNetworking/AFNetworking#4011]
AFNetworking does not work properly for status code 204(NO Content), it just keep waiting till the timeout interval reached. I think the issue is because the response header does not contain content type because there is No Content in response.

https://stackoverflow.com/questions/45229400/afnetworking-fails-for-status-code-204

**Comment by tewha** [comment]
I used AFNetworking all the time with 204 results last year. You should check your code again; it's hard to believe that would regress.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).

**Comment by barkiiqbal** [comment]
I still believe the problem is in the AFNetworking. but i had by pass this issue by changing the response with empty json from server side.
