### ISSUE TITLE
When I send a "get" request, why is there a "=" before the request parameter?

### ISSUE THREAD

**Issue by Dong12138** [AFNetworking/AFNetworking#4012]
When I send a "get" request, why is there a "=" before the request parameter?
![wechatimg1130](https://user-images.githubusercontent.com/14012842/28918463-e96ae7aa-787b-11e7-9d23-e10d97fb5641.jpeg)

**Comment by Dong12138** [comment]
AFN version: 3.x.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
