### ISSUE TITLE
a simple request about -1001 confuse me long time!

### ISSUE THREAD

**Issue by xsxhxb** [AFNetworking/AFNetworking#4024]
I have a simple GET  request , but sometimes it occurs request fail error code = -1001 .this questions have happened continue 2 years.now I use AFN 3.x。Please help me thank you very much.  error message eg:
error=Error Domain=NSURLErrorDomain Code=-1001 "请求超时。" UserInfo={NSUnderlyingError=0x1702487f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}},

**Comment by ghmake1y** [comment]
Check the settings about request serialization's timeoutInterval.If this property set a short value,it might be throw this error before the server returns.

**Comment by xsxhxb** [comment]
@ghmake1y I set AFN all of requests timeoutInterval 10s , timeoutInterval is OK.
