### ISSUE TITLE
how can i use a GET request with pathinfo not querystring

### ISSUE THREAD

**Issue by NickNameWolf** [AFNetworking/AFNetworking#4026]
now , i have one question , i want to use a GET request with pathinfo like https://github.com/AFNetworking/AFNetworking/issues/new not https://www.google.co.jp/search?q=ios&oq=ios&aqs=chrome..69i57.7451j0j7&sourceid=chrome&ie=UTF-8

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
