### ISSUE TITLE
AFNetworkReachabilityManager.h generates warning "Conflicting nullability specifier on return types"

### ISSUE THREAD

**Issue by pouriaalmassi** [AFNetworking/AFNetworking#4027]
AFNetworkReachabilityManager.h generates a warning stemming from conflicting definitions of `init`. Specifically the following definitions conflict. 

AFNetworkReachabilityManager.h's `- (nullable instancetype)init NS_UNAVAILABLE;` conflicts with NSObject.h's `- (instancetype)init`.

Warning:  `AFNetworkReachabilityManager.h:115:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'`.

Environment
- Xcode Version 8.3.3 (8E3004b)
- iOS 10.3
- AFNetworking Version: 3.1.0
- macOS Version 10.12.6 (16G29)
- Installed via Cocoapods.

**Comment by Jaron-Lowe** [comment]
I am also experiencing this issue in one of my projects.

**Environment**
- Xcode Version: 9.1 (9B55)
- iOS Version: 11.1
- Deployment Target: 10.0
- AFNetworking Version: 3.1.0
- macOS Version: 10.13.1
- Installed: Manually

**Comment by sspitzer** [comment]
I'm seeing this too AFNetworking Version: 3.2.0, this silences the warning:

```
- (nullable instancetype)init NS_UNAVAILABLE;
```

to:

```
- (instancetype)init NS_UNAVAILABLE;
```

**Comment by racer1988** [comment]
This is still happening :)

But I guess AFNetworking is not maintained anymore?
