### ISSUE TITLE
Error Domain=kCFErrorDomainCFNetwork Code=-1205 "The server “” did not accept the certificate." 

### ISSUE THREAD

**Issue by sallyahmed** [AFNetworking/AFNetworking#4031]
i have problem with iOS 11 with cer.

Error Domain=NSURLErrorDomain Code=-1205 "The server "" did not accept the certificate." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x60000010dec0>, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9834, NSUnderlyingError=0x6040002590e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1205 "The server "" did not accept the certificate." UserInfo={NSErrorFailingURLStringKey=https://<Link>/content?id_TERMS_PRIVACY, _kCFNetworkCFStreamSSLErrorOriginalValue=-9834, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7ff5cc0b9c00) s: <server> i: DigiCert SHA2 Secure Server CA>",
    "<cert(0x7ff5cc0bb400) s: DigiCert SHA2 Secure Server CA i: DigiCert Global Root CA>",
    "<cert(0x7ff5cc08f200) s: DigiCert Global Root CA i: DigiCert Global Root CA>"
), _kCFStreamPropertySSLClientCertificateState=2, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x60000010dec0>, NSLocalizedDescription=The server  did not accept the certificate., _kCFStreamPropertySSLClientCertificates=(
    "<SecIdentityRef: 0x60000022d880>",
    "<cert(0x7ff5cb50e360) s:  i: DigiCert SHA2 Assured ID CA>",
    "<cert(0x7ff5cc09ee00) s: DigiCert SHA2 Assured ID CA i: DigiCert Assured ID Root CA>",
    "<cert(0x7ff5cc09f800) s: DigiCert Assured ID Root CA i: DigiCert Assured ID Root CA>"
), _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://<Link>content?id=_TERMS_PRIVACY, _kCFStreamErrorCodeKey=-9834}}, NSErrorPeerCertificateChainKey=(
    "<cert(0x7ff5cc0b9c00) s: i: DigiCert SHA2 Secure Server CA>",
    "<cert(0x7ff5cc0bb400) s: DigiCert SHA2 Secure Server CA i: DigiCert Global Root CA>",
    "<cert(0x7ff5cc08f200) s: DigiCert Global Root CA i: DigiCert Global Root CA>"
), NSErrorClientCertificateChainKey=(
    "<SecIdentityRef: 0x60000022d880>",
    "<cert(0x7ff5cb50e360) s:  i: DigiCert SHA2 Assured ID CA>",
    "<cert(0x7ff5cc09ee00) s: DigiCert SHA2 Assured ID CA i: DigiCert Assured ID Root CA>",
    "<cert(0x7ff5cc09f800) s: DigiCert Assured ID Root CA i: DigiCert Assured ID Root CA>"
), NSLocalizedDescription=The server did not accept the certificate., NSErrorFailingURLKey=https://<Link>/content?id=_TERMS_PRIVACY, NSErrorFailingURLStringKey=https://<Link>/content?id=_TERMS_PRIVACY, NSErrorClientCertificateStateKey=2}

**Comment by hjh920722** [comment]
@sallyahmed I've got the same issue.Did you find the solution?

**Comment by qijizhuimeng** [comment]
hello,I have the same problem.Did you solve it?

**Comment by sallyahmed** [comment]
You should make sure that your server support TLS v 1.2 

After updating app works great

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).

**Comment by liuwin7** [comment]
@sallyahmed is right!
