### ISSUE TITLE
AFN get function response data include lots of  strings like \321

### ISSUE THREAD

**Issue by chiplua** [AFNetworking/AFNetworking#4032]
I use this library for swift project.
When I use 'get' function, I received data from server, but include lots of strings like \321. 
My code is:
        AFNetHelper.get(urlString:urlString!, parameters: nil, progress: nil, success: { (responsObject) in
            let str:String = (NSString(data: responsObject! as! Data, encoding: String.Encoding.utf8.rawValue))! as String // UTF8 String
            print(str)

class AFNetHelper: AFHTTPSessionManager {
    static let shareManager:AFNetHelper = {
        let baseURL = URL(string: "")
        let manager = AFNetHelper(baseURL: baseURL, sessionConfiguration: URLSessionConfiguration.default)
        //manager.responseSerializer.acceptableContentTypes = NSSet(objects: "application/json", "text/json", "text/javascript", "text/plain", "text/html") as? Set<String>
        manager.responseSerializer.acceptableContentTypes = NSSet(objects: "application/json; charset=utf-8", "text/json; charset=utf-8", "text/javascript; charset=utf-8", "text/plain; charset=utf-8", "text/html; charset=utf-8") as? Set<String>
        manager.responseSerializer = AFHTTPResponseSerializer()
        manager.requestSerializer.timeoutInterval = 10
        
        return manager
    }()
    class func get(urlString:String, parameters:AnyObject?, progress:AnyObject?, success:((_ responseObject:AnyObject?) -> Void)?, failure:((NSError) -> Void)?) -> Void {
        AFNetHelper.shareManager.get(urlString, parameters: parameters, progress: { (progress) in
            }, success: { (task, responseObject) in
            //如果responseObject不为空时
            if responseObject != nil {
                success!(responseObject as AnyObject?)
            }
        }, failure: { (task :URLSessionDataTask?, error:Error?) -> Void in
        })
    }
}

Log in console is:
{'id':'871868','company_name':'辽宁丹生生物制药有限\345\205公司司'},{'id':'871635','company_name':'辽宁修正生物制药有峰维康生化制药有限公司'},{'id':'887273','company_name':'赤峰荣\346\265济堂药业有限公司'},{'id':'872467','company_name':'赤峰蒙欣药\344\270业有限公司'},{'id':'883172','company_name':'辅仁药业集团有\351\231限公司'},{'id':'871868','company_name':'辽宁丹生生物制药有限\345\205公司司'},{'id':'871635','company_name':'辽宁修正生物制药有\351限公司'},{'id':'871676','company_name':'辽宁华瑞联合制药有限公司'},{'id':'870888','company_name':'辽宁华鑫药业有限公司'},{'id':'870864','company_name':'辽宁味邦生物制药有限公司'},{'id':'871624','company_name':'辽宁天铖制药有限公司'},{'id':'1000004527','company_name':'辽宁奥达制药有限公司'},{'id':'870736','company_name':'辽宁康泰药业有限公司'},{'id':'870961','company_name':'辽宁森荣制药有限公司'},{'id':'872159','company_name':'辽宁泰兴生物科技有限公司'},{'id':'870602','company_name':'辽宁王牌速效制药有限公司'},{'id':'863906','company_name':'辽宁福源药业有限公司'},{'id':'883806','company_name':'辽宁绿丹药业有限公司'},{'id':'870825','company_name':'辽宁良心(集团)德宁绿丹药业有限公司'},{'id':'870825','company_name':'辽宁良心(集团)德\345\263峰药业有限公司'},{'id':'872112','company_name':'辽宁金丸药业有限公司'},{'id':'868187','company_name':'辽源市百康药业有限责任公司'},{'id':'868703','company_name':'辽源市真雨药业有限公责任公司'},{'id':'868703','company_name':'辽源市真雨药业有限公\345\217司'},{'id':'887171','company_name':'辽源市迪康药业有限责任公司'},{'id':'869882','company_name':'辽源誉隆亚东药业有限责任公司'},{'id':'840819','company_name':'远大医药(中国)有限公司'},{'id':'876981','company_name':'通化东宝五药有限公司'},{'id':'867686','company_name':'通化东宝永健制药有限公司'},{'id':'868319','company_name':'通化中辰药业有限责任公司'},{'id':'868894','company_name':'通化仁民药业股份有限公司'},{'id':'869413','company_name':'通化兴华药业有限责任公司'},{'id':'868991','company_name':'通化利民药业有限责任公司'},{'id':'868140','company_name':'通化华夏药业有限责任公司'},{'id':'868193','company_name':'通化吉通药业有限公司'},{'id':'868105','company_name':'通化嘉丰药业股份有限公司'},{'id':'868157','company_name':'通化新东日药业股份有限公司'},{'id':'868571','company_name':'通化爱心药业有限责任公司'},{'id':'868203','company_name':'通化神龙药业股份有限公司'},{'id':'868972','company_name':'通化茂祥制药有限公司'},{'id':'867998','company_name':'通化长城药业股份有限公司'},{'id':'867659','company_name':'通化颐生药业股份有限公司'},{'id':'873028','company_name':'通辽东北六药业有限公司'},{'id':'863763','company_name':'邢台市明神通辽东北六药业有限公司'},

**Comment by chiplua** [comment]
When I use the same url in android phone or I put the url in web url address, I get the response like this:
NEVER FOUND \xxx strings.
How can i fix this bug?



{'search_namecn':'安乃近','search_result_number':'13','search_result_list':[{'namecn':'复方青蒿安乃近片','company':[{'id':'858182','company_name':'南宁市冠峰制药有限公司'},{'id':'858184','company_name':'广西双蚁药业公司'},{'id':'858392','company_name':'广西壮族自治区花红药业股份有限公司'},{'id':'834326','company_name':'广西河丰药业有限责任公司'},{'id':'834325','company_name':'广西花红药业有限责任公司'},{'id':'501590','company_name':'成都倍特药业有限公司'}]},{'namecn':'安乃近','company':[{'id':'850420','company_name':'上海五洲药业股份有限公司'},{'id':'849683','company_name':'华东医药(西安)博华制药有限公司'},{'id':'869255','company_name':'吉林恒和制药股份有限公司'},{'id':'876000','company_name':'天津中新药业集团股份有限公司新新制药厂'},{'id':'847134','company_name':'山东新华制药股份有限公司'},{'id':'757556','company_name':'广东华南药业集团有限公司'},{'id':'833513','company_name':'广州白云山汉方现代药业有限公司'},{'id':'835622','company_name':'开封制药(集团)有限公司'},{'id':'764602','company_name':'武汉武药制药有限公司'},{'id':'866389','company_name':'河北冀衡(集团)药业有限公司'},{'id':'862270','company_name':'浙江海森药业有限公司'},{'id':'855714','company_name':'浙江金华康恩贝生物制药有限公司'},{'id':'869399','company_name':'长春大政药业科技有限公司'}]},{'namecn':'安乃近(口服用)','company':[{'id':'843679','company_name':'大丰兄弟制药有限公司'}]},{'namecn':'安乃近(注射用)','company':[{'id':'843680','company_name':'大丰兄弟制药有限公司'}]},{'namecn':'安乃近氯丙嗪注射液','company':[{'id':'864430','company_name':'北京双鹤药业股份有限公司'},{'id':'845821','company_name':'大丰兄弟制药有限公司'},{'id':'832792','company_name':'广东南国药业有限公司'},{'id':'834298','company_name':'桂林南药股份有限公司'},{'id':'843632','company_name':'江苏大红鹰恒顺药业有限公司'},{'id':'835604','company_name':'河南天方药业股份有限公司'},{'id':'848944','company_name':'西安利君制药有限责任公司'}]},{'namecn':'安乃近注射液','company':[{'id':'851051','company_name':'上海信谊金朱药业有限公司'},{'id':'835631','company_name':'上海现代哈森(商丘)药业有限公司'},{'id':'845513','company_name':'世贸天阶制药(江苏)有限责任公司'},{'id':'871451','company_name':'东北制药集团沈阳第一制药有限公司'},{'id':'871593','company_name':'丹东医创药业有限责任公司'},{'id':'854481','company_name':'云南傣药有限公司'},{'id':'855057','company_name':'云南植物药业有限公司'},{'id':'854778','company_name':'云南生物谷灯盏花药业有限公司'},{'id':'854980','company_name':'云南白药集团股份有限公司'},{'id':'854598','company_name':'云南省陇川县章凤制药厂'},{'id':'869009','company_name':'修正药业集团长春高新制药有限公司'},{'id':'864276','company_name':'北京双鹤药业股份有限公司'},{'id':'864282','company_name':'北京市永康药业有限公司'},{'id':'840594','company_name':'华中药业股份有限公司'},{'id':'835743','company_name':'南阳市全宇制药有限公司'},{'id':'835757','company_name':'南阳普康药业有限公司'},{'id':'868754','company_name':'吉林省华威药业有限公司'},{'id':'869316','company_name':'吉林省辉南辉发制药股份有限公司'},{'id':'842549','company_name':'吉林省辉南长龙生化药业股份有限公司'},{'id':'868591','company_name':'吉林精优长白山药业有限公司'},{'id':'835676','company_name':'和力达(信阳)药业有限责任公司'},{'id':'838755','company_name':'哈药集团三精制药股份有限公司'},{'id':'851892','company_name':'四川升和药业股份有限公司'},{'id':'852178','company_name':'四川奇力同心制药有限公司'},{'id':'852875','company_name':'四川省长征药业股份有限公司'},{'id':'703133','company_name':'四川科伦药业股份有限公司'},{'id':'853262','company_name':'四川美大康华康药业有限公司'},{'id':'879993','company_name':'回音必集团抚州制药有限公司'},{'id':'703388','company_name':'国药集团国瑞药业有限公司'},{'id':'835761','company_name':'国药集团容生制药有限公司'},{'id':'854072','company_name':'国药集团新疆制药有限公司'},{'id':'843168','company_name':'国营张家港市制药厂'},{'id':'843755','company_name':'大丰兄弟制药有限公司'},{'id':'498730','company_name':'大同市惠达药业有限责任公司'},{'id':'835748','company_name':'天津药业集团新郑股份有限公司'},{'id':'885061','company_name':'天津金耀氨基酸有限公司'},{'id':'839948','company_name':'天津金耀集团湖北天药药业股份有限公司'},{'id':'827589','company_name':'宁夏启元国药有限公司'},{'id':'858632','company_name':'宁波大红鹰药业股份有限公司'},{'id':'828746','company_name':'安徽凤阳科苑药业有限公司'},{'id':'828751','company_name':'安徽城市药业有限责任公司'},{'id':'828748','company_name':'安徽生物药业有限责任公司'},{'id':'828750','company_name':'安徽省皖北药业股份有限公司'},{'id':'828747','company_name':'安徽联谊药业股份有限公司'},{'id':'835630','company_name':'安阳九州药业有限责任公司'},{'id':'840933','company_name':'宜昌三峡制药有限公司'},{'id':'841108','company_name':'宜昌人福药业有限责任公司'},{'id':'831830','company_name':'尼克美制药(中山)有限公司'},{'id':'847143','company_name':'山东新华制药股份有限公司'},{'id':'875175','company_name':'山西中宝曙光药业有限公司'},{'id':'874350','company_name':'山西国润制药有限公司'},{'id':'874577','company_name':'山西太原药业有限公司'},{'id':'875208','company_name':'山西振东安特生物制药有限公司'},{'id':'873314','company_name':'山西晋新双鹤药业有限责任公司'},{'id':'857381','company_name':'广东三才石岐制药有限公司'},{'id':'832797','company_name':'广东南国药业有限公司'},{'id':'833008','company_name':'广东新峰药业股份有限公司'},{'id':'1000004647','company_name':'广东罗浮山国药股份有限公司'},{'id':'833143','company_name':'广东邦民制药厂有限公司'},{'id':'858044','company_name':'广州白云山天心制药股份有限公司'},{'id':'859548','company_name':'广西南宁百会药业集团有限公司'},{'id':'835659','company_name':'开封制药(集团)有限公司'},{'id':'835660','company_name':'开开援生制药股份有限公司'},{'id':'844434','company_name':'徐州莱恩药业有限公司'},{'id':'844366','company_name':'必康制药江苏有限公司'},{'id':'845220','company_name':'成都倍特药业有限公司'},{'id':'852859','company_name':'成都利尔药业有限公司'},{'id':'853168','company_name':'成都天台山制药有限公司'},{'id':'852357','company_name':'成都市海通药业有限公司'},{'id':'852308','company_name':'成都第一药业有限公司'},{'id':'835665','company_name':'新乡同心药业有限公司'},{'id':'1000001889','company_name':'新乡市常乐制药有限责任公司'},{'id':'854939','company_name':'昆明制药集团股份有限公司'},{'id':'828278','company_name':'昆明市宇斯药业有限责任公司'},{'id':'1000005106','company_name':'朗致集团万荣药业有限公司'},{'id':'879994','company_name':'杭州回音必集团抚州制药有限公司'},{'id':'760133','company_name':'杭州赛诺菲民生健康药业有限公司'},{'id':'834203','company_name':'桂林南药股份有限公司'},{'id':'854431','company_name':'楚雄和创药业有限责任公司'},{'id':'843533','company_name':'正大天晴药业集团股份有限公司'},{'id':'840762','company_name':'武汉久安药业有限公司'},{'id':'840781','company_name':'武汉恒信源药业有限公司'},{'id':'840294','company_name':'武汉滨湖双鹤药业有限责任公司'},{'id':'840020','company_name':'武汉爱民制药有限公司'},{'id':'843853','company_name':'江苏华阳制药有限公司'},{'id':'857700','company_name':'江苏安格药业有限公司'},{'id':'587533','company_name':'江苏涟水制药有限公司'},{'id':'846103','company_name':'江西制药有限责任公司'},{'id':'1000008959','company_name':'江西赣江制药有限责任公司'},{'id':'846074','company_name':'江西银涛药业有限公司'},{'id':'870626','company_name':'沈阳新马药业有限公司'},{'id':'835690','company_name':'河南前锋药业科技有限公司'},{'id':'835758','company_name':'河南华利制药股份有限公司'},{'id':'835710','company_name':'河南天方药业股份有限公司'},{'id':'835722','company_name':'河南省安阳豫北制药厂'},{'id':'835700','company_name':'河南省百泉制药有限公司'},{'id':'847713','company_name':'济南永宁制药股份有限公司'},{'id':'843818','company_name':'济川药业集团有限公司'},{'id':'866149','company_name':'浙江万邦药业股份有限公司'},{'id':'856035','company_name':'浙江万马药业有限公司'},{'id':'703134','company_name':'浙江济民制药有限公司'},{'id':'852926','company_name':'浙江瑞新药业股份有限公司'},{'id':'834948','company_name':'海南全星制药有限公司'},{'id':'834617','company_name':'海南制药厂有限公司'},{'id':'1000004154','company_name':'海南制药厂有限公司制药二厂'},{'id':'859099','company_name':'海南海灵化学制药有限公司'},{'id':'840550','company_name':'湖北亿雄祥瑞药业有限公司'},{'id':'1000007479','company_name':'湖北兴华制药有限公司'},{'id':'840409','company_name':'湖北同济奔达鄂北制药有限公司'},{'id':'839901','company_name':'湖北天圣康迪制药有限公司'},{'id':'840035','company_name':'湖北欧立制药有限公司'},{'id':'840192','company_name':'湖北武当金鼎制药有限公司'},{'id':'840113','company_name':'湖北潜江制药股份有限公司'},{'id':'841358','company_name':'湖南天鑫药业有限公司'},{'id':'841392','company_name':'湖南振华制药有限责任公司'},{'id':'841407','company_name':'湖南正清制药集团股份有限公司'},{'id':'860055','company_name':'漯河南街村全威制药股份有限公司'},{'id':'835625','company_name':'灵宝市豫西药业有限责任公司'},{'id':'835742','company_name':'焦作福瑞堂制药有限公司'},{'id':'847311','company_name':'瑞阳制药有限公司'},{'id':'831241','company_name':'甘肃兰药药业有限公司'},{'id':'831129','company_name':'甘肃莫高实业发展股份有限公司祁连山制药厂'},{'id':'865325','company_name':'石家庄市北方制药厂'},{'id':'874831','company_name':'石药银湖制药有限公司'},{'id':'865776','company_name':'石药集团欧意药业有限公司'},{'id':'866005','company_name':'神威药业集团有限公司'},{'id':'828092','company_name':'福州海王福药制药有限公司'},{'id':'827986','company_name':'福建南少林药业有限公司'},{'id':'827934','company_name':'福建古田药业有限公司'},{'id':'827842','company_name':'福建汇天生物药业有限公司'},{'id':'827743','company_name':'福建省泉州海峡制药有限公司'},{'id':'841379','company_name':'紫光古汉集团衡阳制药有限公司'},{'id':'828548','company_name':'芜湖康奇制药有限公司'},{'id':'845227','company_name':'苏州弘森药业有限公司'},{'id':'833522','company_name':'茂名市力奇制药有限公司'},{'id':'878801','company_name':'葵花药业集团(冀州)有限公司'},{'id':'876887','company_name':'蓬莱诺康药业有限公司'},{'id':'835759','company_name':'裕松源药业有限公司'},{'id':'856459','company_name':'西南药业股份有限公司'},{'id':'848892','company_name':'西安利君制药有限责任公司'},{'id':'849510','company_name':'西安安健药业有限公司'},{'id':'849913','company_name':'西安风华药业有限公司'},{'id':'849452','company_name':'西安高科陕西金方药业公司'},{'id':'834655','company_name':'贵州光正制药有限责任公司'},{'id':'834451','company_name':'贵州圣济堂制药有限公司'},{'id':'834419','company_name':'贵州天地药业有限责任公司'},{'id':'870425','company_name':'赤峰蒙欣药业有限公司'},{'id':'886285','company_name':'辽宁天龙药业有限公司'},{'id':'840416','company_name':'远大医药(中国)有限公司'},{'id':'868616','company_name':'通化新东日药业股份有限公司'},{'id':'888082','company_name':'邯郸市冀南制药有限公司'},{'id':'856749','company_name':'重庆国泰康宁制药有限责任公司'},{'id':'856404','company_name':'重庆迪康长江制药有限公司'},{'id':'845523','company_name':'金陵药业股份有限公司南京金陵制药厂'},{'id':'878277','company_name':'金陵药业股份有限公司浙江天峰制药厂'},{'id':'869927','company_name':'长春大政药业科技有限公司'},{'id':'876915','company_name':'长春精优药业股份有限公司'},

**Comment by chiplua** [comment]
The URL is:
http://healthy.os.lianluo.com/drug_list.php?namecn=安乃近

**Comment by ArcRain** [comment]
The response data  from PHP server is not formatted as JSON.
You can check your data format from here: [http://www.json.cn/](url)

**Comment by github641** [comment]
有可能是数据的字符编码的问题，"\345\205"这样的格式，似乎是UTF-8的原始形式

**Comment by SlaunchaMan** [comment]
This might be an issue with how you’re deserializing the data. For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
