### ISSUE TITLE
Error Error Domain=NSURLErrorDomain Code=-999 "cancelled

### ISSUE THREAD

**Issue by GaneshKumarSelvam** [AFNetworking/AFNetworking#4037]
Why Getting this error, Unable to solve, using https protocol?

Error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://example.com/demo/appusercontroller/applogin/zipcode_list,, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://example.com/demo/appusercontroller/applogin/zipcode_list,}

**Comment by alvincrisuy** [comment]
I also have the same problem. Does anybody solved it? 😢

**Comment by socialvanana** [comment]
Same here, from 4days ago suddenly.

**Comment by GaneshKumarSelvam** [comment]
No, after a day it started working.

**Comment by Sjoerdjanssenen** [comment]
I'm still experiencing this. Would love to hear from anyone that managed to solve or debug it.

**Comment by arpitVishwakarma** [comment]
I am having the same problem. anybody solved it?

**Comment by manuel21** [comment]
https://github.com/Alamofire/Alamofire/issues/1757

**Comment by MarkMolina** [comment]
I wasn't retaining the manager but now I am. Still the same -999 error saying the request got cancelled. Also tested by connecting to our production server (where ssl is set up correctly) but I got the same problem. Problem occurred a day ago.

**Comment by rahulchowdhury** [comment]
I had the same issue with **Alamofire** and **RxSwift**. My problem was that I was calling `disposedBy()` after the `subscribe()` function to dispose of unused resources.

However, that might have disposed of the resource even before the network call succeeded. Removing the `disposedBy()` call after `subscribe()` solved the issue for me.

My working code looks like this:

```
fetchUserAction
            .execute(t: userId)
            .subscribe { event in
                switch event {
                case .success(let user):
                    completion(Result.success(user))
                case .error:
                    completion(Result.error)
                }
            }
```

Maybe that'll help someone facing a similar issue.

**Comment by garg204** [comment]
Hi

i tried to set security policy. It seems its not working for me. All api request succeeded even if i do not attach certificate in application bundle. I am writing below code in my custom class.

(instancetype)initWithSessionConfiguration:(nullable NSURLSessionConfiguration *)configuration {
if (self = [super init]) {
self.urlSessionManager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];
self.urlSessionManager.securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModePublicKey];
}

return self;
}
