### ISSUE TITLE
request's ip address was changed

### ISSUE THREAD

**Issue by zombiechou** [AFNetworking/AFNetworking#4039]
The app send a request. The ip address is http:xxxxxx,and our server do not use redirect.But "connection:  willSendRequest: redirectResponse:" was called.Then i see that the ip address from connection is not equal to request's.What amazing is that most iPhone is ok, only some iPhone has this  event.I do not know what happened, i need help.

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
