### ISSUE TITLE
IOS11 setReachabilityStatusChangeBlock

### ISSUE THREAD

**Issue by alphacentory** [AFNetworking/AFNetworking#4042]
[[AFNetworkReachabilityManager sharedManager] setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {

This line will not run in IOS simulator, however if I downgrade to ios10.3 || iOS10.2 the app runs as expected. 

Any ideas would be awesome.

**Comment by alphacentory** [comment]
It actually looks like: 
In IOS 11 having the 

[[AFNetworkReachabilityManager sharedManager] startMonitoring];

in didFinishLaunchingWithOptions

will not allow setReachabilityStatusChangeBlock to run. 

I moved the startMonitoring to the same function applicationDidBecomeActive
and everything worked. sorry ahead time. Can anyone explain why?

**Comment by xuhongfei** [comment]
I'm having the same confusedness. I also 
[[AFNetworkReachabilityManager sharedManager] startMonitoring];
in didFinishLaunchingWithOptions
the first time into the app it runs
and then after i close the network 
setReachabilityStatusChangeBlock not run 
but i moved it into the applicationDidBecomeActive
evething worked.who can tell me why? Thanks!

**Comment by xuhongfei** [comment]
@alphacentory Just now, I found my error.
you cound search for where stopMonitoring
