### ISSUE TITLE
Is AFNetworking still being maintained?

### ISSUE THREAD

**Issue by wjehenddher** [AFNetworking/AFNetworking#4053]
Seems like there hasn't been any accepted PRs since one by @TheDom

**Comment by SlaunchaMan** [comment]
Yes.

**Comment by wjehenddher** [comment]
Thank you @SlaunchaMan 

Is there any ETA for reviewing PR #4010 ?

It's been ready since August 11

**Comment by SlaunchaMan** [comment]
Looking into it!
