### ISSUE TITLE
急!急!急! 大家帮我看看 这个崩溃的描述

### ISSUE THREAD

**Issue by wanyiyuan** [AFNetworking/AFNetworking#4060]
<__NSCFURLSessionConfiguration: 0x11343bdb0>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled. Key path: fractionCompleted Observed object: <NSProgress: 0x170524060> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 35 of 35 Change: { kind = 1; new = 1; } Context: 0x0

CoreFoundation | ___exceptionPreprocess + 124
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | -[NSException initWithCoder:]
3 Foundation | -[NSObject(NSKeyValueObserving) observeValueForKeyPath:ofObject:change:context:] + 164
4 Foundation | _NSKeyValueNotifyObserver + 304
5 Foundation | _NSKeyValueDidChange + 404
6 Foundation | -[NSObject(NSKeyValueObserverNotification) didChangeValueForKey:] + 120
7 CoreFoundation | ___53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 132
8 CoreFoundation | -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 312
9 Foundation | -[NSProgress _setValueForKeys:settingBlock:] + 632
10 Foundation | -[NSProgress setCompletedUnitCount:] + 124
11 我的App | -[AFURLSessionManagerTaskDelegate URLSession:dataTask:didReceiveData:] (AFURLSessionManager.m:260)
12 我的App | -[AFURLSessionManager URLSession:dataTask:didReceiveData:] (AFURLSessionManager.m:1105)
13 CFNetwork | ___67-[NSURLSession delegate_dataTask:didReceiveData:completionHandler:]_block_invoke.242 + 36
14 Foundation | ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
15 Foundation | -[NSBlockOperation main] + 96
16 Foundation | -[__NSOperationInternal _start:] + 620
17 Foundation | ___NSOQSchedule_f + 228
18 libdispatch.dylib | __dispatch_client_callout + 16
19 libdispatch.dylib | __dispatch_queue_serial_drain + 928
20 libdispatch.dylib | __dispatch_queue_invoke + 652
21 libdispatch.dylib | __dispatch_root_queue_drain + 572
22 libdispatch.dylib | __dispatch_worker_thread3 + 124
23 libsystem_pthread.dylib | _pthread_wqthread + 1288
24 libsystem_pthread.dylib | start_wqthread + 4

没啥头绪, 大神们帮忙分析下

**Comment by SeanChense** [comment]
This can be closed for not related issue.
