### ISSUE TITLE
iOS 11 default cachePolicy behaviour has changed

### ISSUE THREAD

**Issue by SeanChense** [AFNetworking/AFNetworking#4062]
Default cache policy is `NSURLRequestUseProtocolCachePolicy` in iOS.
When I upgraded my phone to iOS 11, I notice that default request header has added a cache control header `If-None-Match` which results in getting 304 NOT MODIFIED from server.

**Comment by SeanChense** [comment]
This is a mistake by cache proxy

**Comment by Vincent-CDeng** [comment]
if i set cache policy to NSURLRequestUseProtocolCachePolicy ,then i won't get 304 NOT MODIFIED  from server?

**Comment by hahaGitHub** [comment]
@Vincent-CDeng i meet the situation. Would you tell me how to resolve it?
