### ISSUE TITLE
升级完X9，iOS11之后，原来一切都正常，现在无法连接服务器。

### ISSUE THREAD

**Issue by DuanJiChao** [AFNetworking/AFNetworking#4064]
AFHTTPSessionManager *session = [AFHTTPSessionManager manager];
    //添加证书
    NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"mnchip" ofType:@"cer"];
    NSData *cerDat = [NSData dataWithContentsOfFile:cerPath];
    AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate withPinnedCertificates:[NSSet setWithObject:cerDat]];
    securityPolicy.allowInvalidCertificates = YES;
    securityPolicy.validatesDomainName = YES;
    session.securityPolicy = securityPolicy;

    NSDictionary *params = [NSDictionary dictionaryWithObjectsAndKeys:@"DoPassword",VALUE_NAME,temDevicenum,VALUE_ID,@(time),VALUE_TIMESTAMP,mmm,VALUE_MD5,@"",@"cPassword", nil];

    [session POST:KURL parameters:params progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        NSDictionary *dictionary = (NSDictionary *)responseObject;
        if ([dictionary[@"ReturnValue"] intValue] == 1) {
            //  NSLog(@"请求登陆口令成功");
        }
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        [OperationHelper writeLog:@"连接服务器连接失败"];   //升级后，一直连接失败。
    }]; 

error 信息:
Error Domain=NSURLErrorDomain Code=-1200 "发生了 SSL 错误，无法建立与该服务器的安全连接。" UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x1c0302370>, NSLocalizedRecoverySuggestion=您仍要连接此服务器吗？, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<cert(0x1011bdc00) s: service.mnchip.cn i: service.mnchip.cn>"
), NSUnderlyingError=0x1c0258090 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x1c0302370>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x1011bdc00) s: service.mnchip.cn i: service.mnchip.cn>"
)}}, NSLocalizedDescription=发生了 SSL 错误，无法建立与该服务器的安全连接。, NSErrorFailingURLKey=https://service.mnchip.cn:8443/PointcareService/ifservlet, NSErrorFailingURLStringKey=https://service.mnchip.cn:8443/PointcareService/ifservlet, NSErrorClientCertificateStateKey=0}

**Comment by ljxjxl** [comment]
I have same issue after update to  ios11.
Have you solved it?

**Comment by DuanJiChao** [comment]
@ljxjxl  Not yet, the certificate is TLS1.2, SHA256 algorithm, 2048 bits of RSA key. Now do not know exactly where the problem is. Do you also use a self-signed certificate?

**Comment by ljxjxl** [comment]
使用的自签证书

**Comment by DuanJiChao** [comment]
@ljxjxl 我去年十月份上线的时候没有添加白名单也是可以的（APP Transport Security Setting下没有添加任何键值对）。不过现在升级到X9和iOS11后，添加白名单就没有报错了。你可以尝试一下。具体原因也是很清楚。

**Comment by ljxjxl** [comment]
@DuanJiChao 我一直在APP Transport Security Setting下面添加的有白名单，升级前是好的，升级后就报错，可以把你的白名单截图给我不，我对比一下？

**Comment by DuanJiChao** [comment]
![e26251b3-ff4c-4fa8-91ec-535635f6fc9d](https://user-images.githubusercontent.com/17640102/30901396-28d87f58-a39a-11e7-8488-d6b9afbcfa3b.png)
@ljxjxl

**Comment by ljxjxl** [comment]
@DuanJiChao 谢谢，不过还是不行，我用的是自带的NSUrlSession，没有用第三方AFNetworking。

**Comment by Liangxue** [comment]
你好，我也遇到这个问题了，请问你解决了吗

**Comment by liuxiaowugithub** [comment]
应该是没有读取到证书

**Comment by ljxjxl** [comment]
@liuxiaowugithub  我这边后台处理的，现在可以运行了

**Comment by Liangxue** [comment]
你好，能方便问一下后台都改什么了吗？我也有同样的问题

**Comment by Liangxue** [comment]
@ljxjxl 你好，能方便问一下后台都改什么了吗？我也有同样的问题

**Comment by ljxjxl** [comment]
好像是TLSv1.0升级到TLVs1.2了，因为后台跟我们不在一个地区办公，所以我不是很确定

**Comment by Liangxue** [comment]
@ljxjxl 能不能帮我问一下，我这两天要上线，谢谢啦。。。。。拜托了。。。。

**Comment by zhuamaodeyu** [comment]
这个问题有人解决没有呀 ，使用的是自签名证书 ，还是无法连接网络

**Comment by cyl123** [comment]
现在解决了么？这个问题

**Comment by git-timor** [comment]
所以是什么导致的呢 是因为没有备案吗

**Comment by cml19891124** [comment]
我这边对这个问题也追查了两个月了 ，比较着急，请问 有比较靠谱的解决方案嘛，急
