### ISSUE TITLE
error: property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by heroims** [AFNetworking/AFNetworking#4066]
In cocospod1.4.0 use  `use_frameworks!` if create a pod add`static_framework=true`  dependency  other pod and  other pod`dependency 'AFNetworking'`  this error #3241 reappear .

you need revert #3177  @kcharwood

**Comment by SlaunchaMan** [comment]
What version of Xcode are you using? What version of iOS is your deployment target set to?

**Comment by heroims** [comment]
I using Xcode9 ios11,when use pod 'dependency' got this error @SlaunchaMan.

**Comment by SlaunchaMan** [comment]
What version of AFNetworking do you have installed? Can you paste in your `Podfile`?
