### ISSUE TITLE
http headers with similar keys

### ISSUE THREAD

**Issue by y500** [AFNetworking/AFNetworking#4071]
If write like below:

`[[AFHTTPSessionManager manager].requestSerializer setValue:@"1" forHTTPHeaderField:@"Version"];
[[AFHTTPSessionManager manager].requestSerializer setValue:@"2" forHTTPHeaderField:@"version"];`

there will bill two key-values in the HTTPHeaders dictionary, but when build the HTTP request, it will only pick one of them, I think this will be a little conflict.

Because RFC 2616 said:

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

**Comment by SlaunchaMan** [comment]
This seems like a valid concern—the value of the `HTTPHeaders` dictionary should reflect the actual headers that will be sent.

**Comment by chaseacton** [comment]
The HTTP spec says header field names are case-insensitive: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
