### ISSUE TITLE
Falls Into Infinite Hole Creating Background NSURLSession After Crash

### ISSUE THREAD

**Issue by victorstewart** [AFNetworking/AFNetworking#4073]
Testing some networking failure scenarios and just found a nightmare...

When a EXC_BAD_ACCESS / SIGSEGV crash occurs, while there exists an instantiated background NSURLSession (i.e. created with backgroundSessionConfigurationWithIdentifier), that identifier string becomes unusable ever again.

Because when the app is rebooted, and you try to recreate the background session with the **same** identifier string... it falls into an infinite loop on this line...

`self.session = [NSURLSession sessionWithConfiguration:self.sessionConfiguration delegate:self delegateQueue:self.operationQueue];`

due too...

CFNetwork
+[NSURLConnection(Loader) _resourceLoadLoop:]

If you use a new identifier string, that of course works. Even if you shut your phone on/off, do this 100 times, you can still never use that identifier string again... always results in that infinite hang. 

I'm submitting an official bug report to Apple as we speak.

**Comment by SlaunchaMan** [comment]
Did you ever hear back from Apple?

**Comment by victorstewart** [comment]
@SlaunchaMan just checked. nope no word back yet. filled the bug report on Oct 1
