### ISSUE TITLE
AFNetworkReachabilityManager   isReachable return error statu

### ISSUE THREAD

**Issue by tianhongyin** [AFNetworking/AFNetworking#4076]
When i use xcode9,isReachable method in AFNetworkReachabilityManager.m  return false,but my iphone is connecting to internet(xcode9 & ios10.3.2)

**Comment by SlaunchaMan** [comment]
From the documentation:

>  Reachability can be used to determine background information about why a network operation failed, or to trigger a network operation retrying when a connection is established. It should not be used to prevent a user from initiating a network request, as it's possible that an initial request may be required to establish reachability.

You should try to make a request _first_, as your phone may be on Wi-Fi but the radio turned off.
