### ISSUE TITLE
'sharedApplication' is unavailable: not available on iOS (App Extension)

### ISSUE THREAD

**Issue by bharath-dev** [AFNetworking/AFNetworking#4078]
Hi, I am facing "'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead." issue in Restkit pod.

![screen shot 2017-10-09 at 2 16 52 pm](https://user-images.githubusercontent.com/16458195/31330624-cc7aca9c-acfc-11e7-9db4-edb347e9eee7.png)

And similar issue in these files,
AFRKNetworkActivityIndicatorManager.m &
AFURLConnectionOperation.m

I also compared those two files with the AFNetworking files(from latest version), There seems few 
 changes in these two files in the respective methods. I hope for integrating it with the Restkit there could be some changes made by Restkit team, So how to resolve this issue ?

**Comment by SlaunchaMan** [comment]
You’ll have to ask RestKit to update their version of the code.
