### ISSUE TITLE
Crash on upload task with backgroundConfiguration

### ISSUE THREAD

**Issue by sajadkhan** [AFNetworking/AFNetworking#4079]
`NSString *appID = [[NSBundle mainBundle] bundleIdentifier];
    NSURLSessionConfiguration *config = [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:appID];
    
    NSMutableURLRequest *request = [[AFHTTPRequestSerializer serializer] multipartFormRequestWithMethod:@"POST"
                                                                                              URLString:uploadURLString
                                                                                             parameters:nil
                                                                              constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        [formData appendPartWithFileURL:fileURL name:@"file.JPG" fileName:@"file.JPG" mimeType:@"image/png" error:nil];
    }
                                                                                                  error:nil];
    
    AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:config];
    manager.responseSerializer = [AFHTTPResponseSerializer serializer];
    
    _currentUploadTask = [manager uploadTaskWithStreamedRequest:request progress:^(NSProgress * _Nonnull uploadProgress) {
        NSLog(@"Progress = %.2f", uploadProgress.fractionCompleted);
    } completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
        if (error) {
            NSLog(@"Error: %@", error);
        } else {
            NSLog(@"%@ %@", response, responseObject);
        }
    }];
    
    [_currentUploadTask resume];`

I'm trying to create `AFURLSessionManger` with backgroundSessionConfigration and using it to generate `uploadTask` but it crashes.

**Comment by SlaunchaMan** [comment]
Do you have crash logs for this? Is `appID` `nil`?
