### ISSUE TITLE
Crashed On UXAFURLConnectionOperation.m line 159

### ISSUE THREAD

**Issue by moontecholabs** [AFNetworking/AFNetworking#4080]
We are using Afnetworking and in our febrics log We found most of Crash occure at UXAFURLConnectionOperation.m line 159
+[UXAFURLConnectionOperation networkRequestThreadEntryPoint:]

**Comment by SlaunchaMan** [comment]
`UXAFURLConnectionOperation` seems like some other framework is including renamed AFNetworking classes; you should ask them to follow up on this issue.

**Comment by bohachevskyy** [comment]
Hello @moontecholabs did you manage to solve this issue?

**Comment by danialmoghaddam** [comment]
I guess it's from UXCam framework.

**Comment by moontecholabs** [comment]
Thanks for your response, now this issue resolved once update pod.
