### ISSUE TITLE
[self af_resume]  I had a crash problem，Here is the screenshot。

### ISSUE THREAD

**Issue by asd8855** [AFNetworking/AFNetworking#4082]
<img width="914" alt="2017-10-12 5 17 16" src="https://user-images.githubusercontent.com/20153584/31542981-d17621f6-afd9-11e7-9102-274d5a75b3c1.png">
<img width="905" alt="2017-10-12 5 17 00" src="https://user-images.githubusercontent.com/20153584/31543012-ed2314e0-afd9-11e7-8ea7-cc2d4f3d5c89.png">

**Comment by asd8855** [comment]
system 11.0.2

**Comment by WW-Wang** [comment]
![snip20171027_4](https://user-images.githubusercontent.com/13793808/32093945-db201780-bac3-11e7-9595-4d1741b6001c.png)
![snip20171027_3](https://user-images.githubusercontent.com/13793808/32093946-db5be9d6-bac3-11e7-9059-9e430db76cfc.png)
same as

**Comment by SlaunchaMan** [comment]
It’s hard to tell what’s happening with an unsymbolicated crash report. Can you reproduce this issue and provide more information?
