### ISSUE TITLE
AFHTTPSessionManager POST  -> unrecognized selector sent to instance

### ISSUE THREAD

**Issue by columbusLGEN** [AFNetworking/AFNetworking#4083]
[AFHTTPSessionManager POST:parameters:progress:success:failure:]: unrecognized selector sent to instance

i am confused with this problem

Who can help me?
Thank you!

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
