### ISSUE TITLE
NSJSONSerialization dataWithJSONObject

### ISSUE THREAD

**Issue by h249848** [AFNetworking/AFNetworking#4085]
NSJSONSerialization dataWithJSONObject is converting a float value of single digit to multiple digit.
For e.g.: float = 2.3
after converting into NSJSONSerialization dataWithJSONObject we are getting float = 2.3000000.

Class name: AFURLRequestSerialization.m
Line number: 1312

**Comment by SlaunchaMan** [comment]
Hi there, this is happening in `NSJSONSerialization`, not AFNetworking—I’d encourage you to [file a bug](https://bugreport.apple.com) with Apple if you’d like to see it fixed.
