### ISSUE TITLE
NSData *data = error.userInfo[AFNetworkingOperationFailingURLResponseDataErrorKey]; 为什么获取不到错误信息,都是nil

### ISSUE THREAD

**Issue by douliyangwan** [AFNetworking/AFNetworking#4086]
NSData *data = error.userInfo[AFNetworkingOperationFailingURLResponseDataErrorKey]; 为什么获取不到错误信息,都是nil

**Comment by SlaunchaMan** [comment]
Hi there, you may have better luck asking a question [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking).
