### ISSUE TITLE
Domain Error on iOS 8 not on iOS 10 version? 

### ISSUE THREAD

**Issue by GopiK14** [AFNetworking/AFNetworking#4089]
Hi All,
   We are facing domain error only on iOS 8 versions and not able to get response from API but the same code works fine on iOS 10 versions. I have attached the required information below, please check and let me know if any solution.

**AFNetworking Version** : 3.1.0
**ERROR:** " Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" UserInfo=0x7fd440dc6e00 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7fd44586cbb0> { URL: http://......../users/login } { status code: 401, headers {
    "Accept-Ranges" = none;
    Connection = "keep-alive";
    "Content-Length" = 381;
    "Content-Type" = "text/html; charset=iso-8859-1";
    Date = "Fri, 27 Oct 2017 10:17:40 GMT";
    "Keep-Alive" = "timeout=5, max=100";
    "Proxy-Support" = "Session-Based-Authentication";
    Server = Apache;
    Via = "HTTP/1.1 sophos.http.proxy:3128";
    "Www-Authenticate" = "Basic realm=\"Restricted\"";
} }"
  
`AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    AFJSONRequestSerializer *serializer = [AFJSONRequestSerializer serializer];
    [serializer setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    [serializer setValue:@"application/json" forHTTPHeaderField:@"Accept"];
    manager.requestSerializer = serializer;
    manager.responseSerializer = [AFHTTPResponseSerializer serializer];
    manager.securityPolicy.allowInvalidCertificates = YES;
    manager.securityPolicy.validatesDomainName = NO;
[manager POST:url parameters:parameters constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
    } progress:^(NSProgress * _Nonnull uploadProgress) {
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        [MBProgressHUD hideHUDForView:[UIApplication sharedApplication].keyWindow.rootViewController.view animated:YES];
        NSLog(@"responseObject %@",responseObject);
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
               NSLog(@"err : %ld",(long)[error code]);
                NSLog(@"err : %@",[error description]);
    }];
`
**API:** HTTP (Development)
we have added 
`<key>NSAppTransportSecurity</key>
   <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
`
in plist.

Please let me know if any solution. 

Thanks!

**Comment by SlaunchaMan** [comment]
It’s going to be tough to know why your server is returning a 401 error for some iOS versions and not others. Might be better asked [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking).
