### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by swinpa** [AFNetworking/AFNetworking#4090]
Why i request data from server very frequently（60 times/s）,memory would rise，is any one meet this problem?

**Comment by oushizishu** [comment]
I had the same problem.

macOX Version 10.13; 
XCode Version 9.0.1 (9A1004)
iOS: 10.3.3

Creat a new project,  send ONE request with AFHTTPSessionManager. 
Check leak with Instruments. When  sending a request, it show some leaks.

**Comment by zeroffei** [comment]
I also had this problem!!!
mac OS Version 10.12.6
Xcode Version 8.3.3 (8E3004b)
Creat a new project, send ONE request with AFHTTPSessionManager.
Check leak with Instruments. When sending a request, it show some leaks.
And I'm trying to use the native NSURLSession to send a request,but in the end there will be a lot of memory leaks pointing to CFNetwok or Foundation,etc, therefore, I feel very confused, I trouble you to answer me OK?Thank you very much...

**Comment by ilanl** [comment]
Any news from this bug? I experience the same. And if I wrap manager prop thru singleton, doesn't show the leaks.
Assuming we want to keep having different manager instances everywhere use different serializer. How should we handle it?

**Comment by qingfengiOS** [comment]
[AFHTTPSessionManager manager] lead to leak, Because this initialize method is not single,use dispatch_once can resovle it

**Comment by daishuyi** [comment]
It will raise with swift, and AFHTTPSessionManager is single instance. Why?
