### ISSUE TITLE
AFURLConnectionOperation.h Semantic Issue. This block declaration is not a prototype

### ISSUE THREAD

**Issue by WillJonesMagic** [AFNetworking/AFNetworking#4093]
Line 69 in AFURLConnectionOperation.h throws a Semantic Issue warning in Xcode 9.1.
Changing from 
`typedef void (^AFURLConnectionOperationBackgroundTaskCleanupBlock)();` 
to 
`typedef void (^AFURLConnectionOperationBackgroundTaskCleanupBlock)(void);`
silences the issue. 
Update: Target platform is set to iOS.

**Comment by SlaunchaMan** [comment]
What version of AFNetworking are you using? The latest version does not include `AFURLConnectionOperation.h`.

**Comment by MatrixMiaou** [comment]
I had got the same issue before, and then I found this problem is caused by the Apple LLVM's Setting. You can silence the issue by the other way: Select "Build Setting", text "Strict Prototypes" into the search bar, and Selects "NO". and rebuild, the issue will be fixed.

**Comment by WillJonesMagic** [comment]
So it doesn't. I've updated to the latest version (and appear to have done so some time ago, unsure what happened there!).
This is what happens when I don't pay attention!
