### ISSUE TITLE
Property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by chirag225** [AFNetworking/AFNetworking#4094]
What i did

Remove all pod files and reinstall
Added pod 'AFNetworking', '~> 3.0'
Removed derived data
Clean the project
![screen shot 2017-11-06 at 5 31 10 pm](https://user-images.githubusercontent.com/7522791/32440269-75d2f30e-c318-11e7-9e41-373c35b071c4.png)

in AFURLSessionManager.h

**Comment by SlaunchaMan** [comment]
What version of Xcode are you using? This should work on all modern Xcodes.

**Comment by tewha** [comment]
I'm not the issue reporter, I believe this change was made in Fall 2012 (iOS 6/Xcode 4.5).

**Comment by SlaunchaMan** [comment]
Closing this as the minimum version of Xcode required by AFNetworking will not experience this issue.
