### ISSUE TITLE
Got denied callback for cellular when cellular is allowed

### ISSUE THREAD

**Issue by shamikagasc** [AFNetworking/AFNetworking#4095]
- Some of my applications are unable to connect to the internet when on cellular networks only. 
- I have already gone through all the steps listed on https://www.imobie.com/support/how-to-fix-cellular-data-issue-on-iphone.htm
- Some interaction between AFNetworking & Core iOS libraries seems to be failing
- The most incriminating evidence is 

`Jun  7 11:08:23 iPhone advomobo(CFNetwork)[4515] <Error>: NSURLSessionTask finished with error - code: -1009
Jun  7 11:08:23 iPhone CommCenter[81] <Notice>: #I New CTServerConnection from pid 4515 (conn=0x1076efb80)
Jun  7 11:08:23 iPhone CommCenter[81] <Notice>: #I CTServerConnection from pid 4515[<private>] is named '<private>'.
Jun  7 11:08:23 iPhone advomobo(CFNetwork)[4515] <Error>: HTTP load failed (error code: -1009 [1:50])
Jun  7 11:08:23 iPhone advomobo(CFNetwork)[4515] <Error>: NSURLSessionTask finished with error - code: -1009
Jun  7 11:08:23 iPhone CommCenter[81] <Notice>: #I CTServerConnection from pid 4515 has closed (conn=0x1076efb80)
Jun  7 11:08:23 iPhone advomobo(CFNetwork)[4515] <Notice>: TIC TCP Conn Start [42:0x17019ce50]
Jun  7 11:08:23 iPhone CommCenter[81] <Notice>: #I Got denied callback for cellular when cellular is allowed
Jun  7 11:08:23 iPhone CommCenter[81] <Notice>: #I Ignoring access denied callback for bundle id: <private>
Jun  7 11:08:23 iPhone advomobo(CFNetwork)[4515] <Notice>: TIC TCP Conn Event [42:0x17019ce50]: 3 Err(50)
Jun  7 11:08:23 iPhone advomobo(CFNetwork)[4515] <Error>: TIC TCP Conn Failed [42:0x17019ce50]: 1:50 Err(50)`

pay special attention to **I Got denied callback for cellular when cellular is allowed**
Any help debugging this would be greatly appreciated

**Comment by SlaunchaMan** [comment]
I’m not sure from this what the problem would be or how you’ve set up the code. If you can provide a code sample that you think should work but doesn’t, please re-open, but you might have more luck asking this [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking).
