### ISSUE TITLE
download progress block is not performed

### ISSUE THREAD

**Issue by columbusLGEN** [AFNetworking/AFNetworking#4096]
`NSURL *downloadURL = [NSURL URLWithString:URLString];

    NSURLRequest *request = [NSURLRequest requestWithURL:downloadURL];
    
    NSURLSessionConfiguration *config = [NSURLSessionConfiguration defaultSessionConfiguration];
 
    AFURLSessionManager *sessionMgr = [[AFURLSessionManager alloc] initWithSessionConfiguration:config];

    NSURLSessionDownloadTask *downloadTask = [sessionMgr downloadTaskWithRequest:request progress:^(NSProgress * _Nonnull downloadProgress) {

        **_# this block is not performed_**

    } destination:^NSURL * _Nonnull(NSURL * _Nonnull targetPath, NSURLResponse * _Nonnull response) {
      
        return downloadURL;
    } completionHandler:^(NSURLResponse * _Nonnull response, NSURL * _Nullable filePath, NSError * _Nullable error) {
       
    }];
    
    [downloadTask resume];`

**Comment by SlaunchaMan** [comment]
For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).
