### ISSUE TITLE
Invalid parameter not satisfying: mimeType

### ISSUE THREAD

**Issue by wanyiyuan** [AFNetworking/AFNetworking#4097]
我尝试改变mimeType的类型和值,测试发现:只有mimeType = nil的时候会崩溃,但是崩溃日志提示的代码行数与收集到的日志代码崩溃行数不同(真机调试),所以我不确定是直接引用AFN造成的崩溃,还是第三方SDK内部引用AFN造成的崩溃

1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | +[NSException raise:format:]
3 Foundation | -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] +112
4 myApp | -[AFStreamingMultipartFormData appendPartWithFileData:name:fileName:mimeType:] (AFURLRequestSerialization.m:774)
5 myApp | -[AFHTTPRequestSerializer multipartFormRequestWithMethod:URLString:parameters:constructingBodyWithBlock:error:] (AFURLRequestSerialization.m:415)
6 myApp | -[QNSessionManager multipartPost:withData:withParams:withFileName:withMimeType:withCompleteBlock:withProgressBlock:withCancelBlock:] (QNSessionManager.m:269)
7 myApp | -[QNFormUpload put] (QNFormUpload.m:118)

0 CoreFoundation | ___exceptionPreprocess + 124
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | +[NSException raise:format:]
3 Foundation | -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] +112
4 myApp | -[AFStreamingMultipartFormData appendPartWithFileData:name:fileName:mimeType:] (AFURLRequestSerialization.m:774)
5 myApp | -[AFHTTPRequestSerializer multipartFormRequestWithMethod:URLString:parameters:constructingBodyWithBlock:error:] (AFURLRequestSerialization.m:415)
6 myApp | -[QNSessionManager multipartPost:withData:withParams:withFileName:withMimeType:withCompleteBlock:withProgressBlock:withCancelBlock:] (QNSessionManager.m:269)
7 myApp | -[QNFormUpload put] (QNFormUpload.m:118)
8 libdispatch.dylib | __dispatch_call_block_and_release + 24
9 libdispatch.dylib | __dispatch_client_callout + 16
10 libdispatch.dylib | __dispatch_queue_override_invoke$VARIANT$mp + 716
11 libdispatch.dylib | __dispatch_root_queue_drain + 596
12 libdispatch.dylib | __dispatch_worker_thread3 + 120
13 libsystem_pthread.dylib | _pthread_wqthread + 1268
14 libsystem_pthread.dylib | start_wqthread + 4

**Comment by dabing1022** [comment]
It seems that the crash is caused by the 3rd library `QNFormUpload`.

```
-[QNSessionManager multipartPost:withData:withParams:withFileName:withMimeType:withCompleteBlock:withProgressBlock:withCancelBlock:] (QNSessionManager.m:269)
```
line 269, check the mimeType, the value is nil.

**Comment by wanyiyuan** [comment]
thank you,  I'll try
