### ISSUE TITLE
download large file

### ISSUE THREAD

**Issue by lu0371** [AFNetworking/AFNetworking#4100]
when download large file(more than 1G),
this code :
[self.mutableData appendData:data];
in AFURLSessionManager.m will cause memery leak

**Comment by SlaunchaMan** [comment]
This code shouldn’t leak any memory. What makes you think there’s a leak—are you observing this with Instruments?

**Comment by SlaunchaMan** [comment]
Closing for now but if you can provide more information about this, please re-open.

**Comment by shantj** [comment]
@SlaunchaMan i have the same problem. 
[self.mutableData appendData:data];
“self.mutableData” this object will become biger and biger. it will not release until download finish. so if i need to download large file(more than 1G), the object in memory is the same large, at that time, app will crash.

**Comment by shantj** [comment]
@SlaunchaMan  how about add a property to determine that if we need the memory cache?

**Comment by SlaunchaMan** [comment]
If you’re downloading a file that’s this large, instead of downloading to memory, you should download to a file using a download task.

**Comment by shantj** [comment]
@SlaunchaMan But how that method set the start offset ? I need to resume download task from the break point.

**Comment by flyling** [comment]
> @SlaunchaMan But how that method set the start offset ? I need to resume download task from the break point.

I have the same problem.did you solve it ?
