### ISSUE TITLE
I have a question about Networking Frameworks, not only AFNetworking

### ISSUE THREAD

**Issue by huFly** [AFNetworking/AFNetworking#4105]
Why almost Networking Frameworks don't deal with response data when http request failed, Like AFNetworking, it only return "dataTask" and "error" in failBlock.
        Our server API write for web and mobile, and return error data when the http status code not equal to "200"(eg. 404, 406...). In the browser , it will show JSON data about server custom error message, but in mobile ,use AFNetworking , i want to show error message but could't get JSON data in failBlock.
         
         Of course, it's easy to change code to adapt this situation or server side can coustom other status code and send it when http 200. I want to know why many popular Frameworks  don't provide data on error by default. Is it our server API have Logical error???

**Comment by SlaunchaMan** [comment]
Hi there! For general questions, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
