### ISSUE TITLE
AFURLSessionManagerTaskDelegate .cxx_destruct crash

### ISSUE THREAD

**Issue by Huanhoo** [AFNetworking/AFNetworking#4107]
Hi, I met a crash, the thread is:

0 libobjc.A.dylib | objc_msgSend + 16
1 Foundation | -[NSProgress dealloc] + 232
2 MyApp | -[AFURLSessionManagerTaskDelegate .cxx_destruct] (AFURLSessionManager.m:128)
3 libobjc.A.dylib | object_cxxDestructFromClass(objc_object*, objc_class*) + 148
4 libobjc.A.dylib | objc_destructInstance + 92
5 libobjc.A.dylib | object_dispose + 28
6 MyApp | -[AFURLSessionManager URLSession:task:didCompleteWithError:] (AFURLSessionManager.m:1098)
7 CFNetwork | ___51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.185 + 72
8 Foundation | ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
9 Foundation | -[NSBlockOperation main] + 96
10 Foundation | -[__NSOperationInternal _start:] + 612
11 Foundation | ___NSOQSchedule_f + 228
12 libdispatch.dylib | __dispatch_client_callout + 16
13 libdispatch.dylib | __dispatch_queue_serial_drain + 928
14 libdispatch.dylib | __dispatch_queue_invoke + 884
15 libdispatch.dylib | __dispatch_root_queue_drain + 540
16 libdispatch.dylib | __dispatch_worker_thread3 + 124
17 libsystem_pthread.dylib | _pthread_wqthread + 1096

**Comment by fullwonder** [comment]
it me to

**Comment by SlaunchaMan** [comment]
Can you share the code you're using that creates a task? I suspect your `AFURLSessionManager` is being deallocated while a request is in progress.

**Comment by Huanhoo** [comment]
Thanks a lot for your response.

My network manager is a singleTon, and I alloc it like this:

+ (instancetype)sharedInstance {
    static MyNetworkManager *sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        sharedInstance = [self new];
        sharedInstance.sessionManager = [AFHTTPSessionManager manager];
    });
    return sharedInstance;
}

I create a task use this code:

NSURLSessionDataTask *sessionTask = nil;
sessionTask = [self.sessionManager POST:URLString parameters:[parameters copy] progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {

  //handle success block
                    
                } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
  //handle failure block             
                }];

**Comment by SlaunchaMan** [comment]
Nothing there seems suspicious. Is this crash reproducible?

**Comment by Huanhoo** [comment]
It can't be reproduced and only appears once.

**Comment by SlaunchaMan** [comment]
Hmm. In that case, I'm going to close this issue, but if you figure out how to reproduce it, or can get any more info from the logs, feel free to re-open it!
