### ISSUE TITLE
Cocoapods update

### ISSUE THREAD

**Issue by zkrige** [AFNetworking/AFNetworking#4108]
Please do new release and update cocoapods to point at latest release. pods version is 3.1.0 from 2016

**Comment by alvincrisuy** [comment]
Up

**Comment by zkrige** [comment]
thank you! you rock!

**Comment by YoamFarges** [comment]
Bump, as the latest version in https://cocoapods.org/pods/AFNetworking is still `3.1`, while the `3.2` release on this repo was released on Friday, December 15, 2017 (4 days ago).

Is there a reason the `pod trunk push` has not been done yet?

**Comment by Coeur** [comment]
`pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', :tag => '3.2.0'`

**Comment by rsimenok** [comment]
up

**Comment by stefan-sabau-3pg** [comment]
Hi. Any updates on when the 3.2.0 specs will be pushed to the Cocoapods/Specs repo?

**Comment by Coeur** [comment]
@stefan-sabau-3pg , just assume it will never happen, as `AlamoFire` is superseding the the maintenance of AFNetworking.

**Comment by joeboyscout04** [comment]
Same here.  Would be great to see 3.2.0 released to cocoapods.

**Comment by rsimenok** [comment]
@SlaunchaMan can you comment please?

**Comment by SlaunchaMan** [comment]
It will be released. Not sure where @Coeur is getting that info. Nobody is working on this full-time; it’s all in our free time, of which we have precious little.

**Comment by Coeur** [comment]
Released 11 hours ago: https://github.com/CocoaPods/Specs/blob/master/Specs/a/7/5/AFNetworking/3.2.0/AFNetworking.podspec.json
It's also on Twitter: https://twitter.com/AFNetworking/status/958531569140076544

**Comment by Coeur** [comment]
Arf, I didn't notice until now that you moved your "3.2.0" tag -_-. Normally you should have made it a "3.2.1" instead, @SlaunchaMan .
