### ISSUE TITLE
AFNetworking + Notification Service extension

### ISSUE THREAD

**Issue by vahotm** [AFNetworking/AFNetworking#4111]
When using AFNetworking from Notification Service extension - request completion is never called and system immediately shows original push, same as if my extension crashed. 
Debugger output: Program ended with exit code: 0
I am using [AFHTTPSessionManager POST:parameters:progress:success:failure:]. 

Xcode 9.1
Target iOS version: 9.0
Test device iOS version: 10.3.3

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
