### ISSUE TITLE
problem with UPLOAD VIDEO/IMAGE/TEXT file

### ISSUE THREAD

**Issue by prasenraj** [AFNetworking/AFNetworking#4115]
unc callApiWithMultipartData(_ strApiName: String, param: NSDictionary, data:Array<NSDictionary>, CompletionHandler:@escaping (_ code: Int, _ error:NSError?, _ response:AnyObject?) -> Void) {
        var param = param
        let strUrl: String = BASEURL + strApiName
        
        let (timestamp,nonce,token) = AppSingletonObj.fetchTimeStampNonceToken()
        
        let newDictParam = NSMutableDictionary(dictionary:param)
        newDictParam["token"] = token
        newDictParam["nonce"] = nonce
        newDictParam["timestamp"] = timestamp
        param = newDictParam
        
        let request: NSMutableURLRequest = AFHTTPRequestSerializer().multipartFormRequest(withMethod: POSTREQ, urlString: strUrl, parameters: param as? [String : String], constructingBodyWith: { (formData:AFMultipartFormData) -> Void in
            
            var i = 0
            for dict:NSDictionary in data {
                let extention = dict["format"] as? String
                let strMimeType = dict["strMimeType"] as? String
                let nameofFile:String = (self.randomStringWithLength(6) as String)+"."+extention!
                if (dict["data"] as? Data) != nil {
                    //                    print(myType)
                    formData.appendPart(withFileData: dict["data"] as! Data, name: dict["key"] as! String, fileName: nameofFile, mimeType: strMimeType!)
                } else {
                    let strUrl = dict["data"] as! String
                    let fileURL : URL? = URL(string: strUrl)
                    try! formData.appendPart(withFileURL: fileURL!, name: dict["key"] as! String, fileName: nameofFile, mimeType: strMimeType!)
                    
                }
                i += 1
            }
            
            }, error: nil)
    
        

        let manager: AFURLSessionManager = AFURLSessionManager(sessionConfiguration: URLSessionConfiguration.default)
        var uploadTask: URLSessionUploadTask
        
        uploadTask = manager.uploadTask(withStreamedRequest: request as URLRequest, progress: { (uploadProgress:Progress) -> Void in
            // This is not called back on the main queue.
            // You are responsible for dispatching to the main queue for UI updates
            
            DispatchQueue.main.async(execute: {() -> Void in
                //Update the progress view
                //progressView.progress = uploadProgress.fractionCompleted
            })
        }, completionHandler: { (response:URLResponse, responseObject:AnyObject?, error:NSError?) -> Void in
            if error==nil {
                NSLog("%@ %@", response, (responseObject?.description)!)
                CompletionHandler(1, nil, responseObject)
            }
            else {
                NSLog("Error: %@", error!)
                CompletionHandler(0, error, nil)
            }
            } as? (URLResponse, Any?, Error?) -> Void)
        uploadTask.resume()
    
    
    }

this is my API. when I called this API data is successfully stored but image not store and I am not getting any response. how to fix this issue

**Comment by saiknc** [comment]
I'm also facing the same issue after updating to AFNetworking 3.X it was working fine when i was using AFNetworking 2.X..... All the data is getting stored in sever end except the image i'm trying to upload.
Here is my code

NSMutableURLRequest *request = [[AFHTTPRequestSerializer serializer] multipartFormRequestWithMethod:@"POST" URLString:postURL parameters:params constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
// imgData is the image in NSData
        if (imgData) {
                       [formData appendPartWithFileData:imgData name:@"file" fileName:fileName mimeType:@"image/jpeg"];
                    }
    } error:nil];
AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];
NSURLSessionUploadTask *uploadTask;
    uploadTask = [manager
                  uploadTaskWithStreamedRequest:request
                  progress:nil
                  completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
                      if (error) {
                          NSLog(@"Error: %@", error);
                      } else {
                          NSLog(@"%@ %@", response, responseObject);
                      }
                  }];
    [uploadTask resume];

This request is getting posted successfully and i'm getting the status code 200. But the problem is the image file is not getting posted in server end.
