### ISSUE TITLE
Undefined symbol linker errors: _OBJC_CLASS_$_AFHTTPResponseSerializer",

### ISSUE THREAD

**Issue by ehlersd** [AFNetworking/AFNetworking#4116]
[Similar to issue [#3586](https://github.com/AFNetworking/AFNetworking/issues/3586)]

I'm having this issue, but just with the Serializers. I have tried everything I can think of.
I'm using the latest CocoaPods production executable, along with v3.1.0 of AFNetworking.
I've tried everything short of not using CocoaPods.

Any ideas?

![34055924-dabe0a8c-e196-11e7-9fe0-e3ecdcf3e17f](https://user-images.githubusercontent.com/2302997/34231984-d9382d4e-e5a3-11e7-8634-915149b7dd38.png)

I don't think it's related at all, but I did have to modified the AFURLSessionManager.h file to fix a compiler error:

```
/**
 The dispatch queue for `completionBlock`. If `NULL` (default), the main queue is used.
 */
#if OS_OBJECT_HAVE_OBJC_SUPPORT
@property (nonatomic, strong, nullable) dispatch_queue_t completionQueue;
#else
@property (nonatomic, assign, nullable) dispatch_queue_t completionQueue;
#endif

/**
 The dispatch group for `completionBlock`. If `NULL` (default), a private dispatch group is used.
 */
#if OS_OBJECT_HAVE_OBJC_SUPPORT
@property (nonatomic, strong, nullable) dispatch_group_t completionGroup;
#else
@property (nonatomic, assign, nullable) dispatch_group_t completionGroup;
#endif

```

**Comment by SlaunchaMan** [comment]
Are you referencing AFNetworking inside of a library or from the application? Can you share your Podfile?
