### ISSUE TITLE
download large file crash

### ISSUE THREAD

**Issue by shantj** [AFNetworking/AFNetworking#4117]
[manager setDataTaskDidReceiveDataBlock:^(NSURLSession * _Nonnull session, NSURLSessionDataTask * _Nonnull dataTask, NSData * _Nonnull data) {
....
}

[manager dataTaskWithRequest:request completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
...
}

when download large file(more than 1G),
this code :
[self.mutableData appendData:data];
in AFURLSessionManager.m will cause memery growup

“self.mutableData” this object will become biger and biger. it will not release until download finish. And app will crash.

**Comment by ArkadiYoskovitz** [comment]
Why on earth would you try to download into memory a 1GB sized file?

Thats a clean download to disc use case, if you change the download into a download task it should work correctly

**Comment by shantj** [comment]
@ArkadiYoskovitz "change the download into a download task",  can this way set the start offset? i need to resume from the break point.

**Comment by SlaunchaMan** [comment]
Are you trying to resume a failed download? `-[AFURLSessionManager downloadTaskWithResumeData:progress:destination:completionHandler:]` should be able to handle that for you.

**Comment by shantj** [comment]
@SlaunchaMan `-[AFURLSessionManager downloadTaskWithResumeData:progress:destination:completionHandler:]`this has another problem. I can't get the resumeData that if i kill the app. Is there any suggestion?

**Comment by GarretChen** [comment]
Why not trying the 

```
- (NSURLSessionDownloadTask *)downloadTaskWithRequest:(NSURLRequest *)request
   progress:(nullable void (^)(NSProgress *downloadProgress))downloadProgressBlock
   destination:(nullable NSURL * (^)(NSURL *targetPath, NSURLResponse *response))destination
   completionHandler:(nullable void (^)(NSURLResponse *response, NSURL * _Nullable filePath, NSError * _Nullable error))completionHandler;
```
