### ISSUE TITLE
[NSConcreteMutableData appendBytes:length:]: unable to allocate memory for length 

### ISSUE THREAD

**Issue by icesquall** [AFNetworking/AFNetworking#4118]
Fatal Exception: NSMallocException
*** -[NSConcreteMutableData appendBytes:length:]: unable to allocate memory for length (1476398075)

Using AFNetworking (3.1.0)

![qq20171225-103754](https://user-images.githubusercontent.com/6966213/34331220-b6e88242-e95f-11e7-96e6-4c3e5ce35e78.png)

**Comment by SlaunchaMan** [comment]
Hi there! It seems likely that your download is too large to fit into memory—it’s almost 1.5 GB. Try using a download task instead to download it to a file.
