### ISSUE TITLE
I want to update the header each time ,how to do it

### ISSUE THREAD

**Issue by Xingefb** [AFNetworking/AFNetworking#4119]
- (void)setValue:(nullable NSString *)value
forHTTPHeaderField:(NSString *)field;  
can not do  it 
version- 3.1.0

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
