### ISSUE TITLE
Getting the api via 30 seconds leads to crash

### ISSUE THREAD

**Issue by haokunjiang** [AFNetworking/AFNetworking#4121]
I want to get three or five api via 30 seconds, but i defined a timer about getting the api leading to the crash In ios8.4.please answer this question for me,I will appreciate if you can answer me as soon as possible.

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
