### ISSUE TITLE
What does the reachabilityManager property do for the AFURLSessionManager ?

### ISSUE THREAD

**Issue by heistings** [AFNetworking/AFNetworking#4124]
I am reading code for study, and I notice there is something weird in the `-[AFURLSessionManager initWithSessionConfiguration:]` method:

```
#if !TARGET_OS_WATCH
    self.reachabilityManager = [AFNetworkReachabilityManager sharedManager];
#endif
```

The reachabilityManager property is not used in any other method within the .m file. What if we remove this property of AFURLSessionManager ?

**Comment by SlaunchaMan** [comment]
Removing the `reachabilityManager` property would break any code that calls the property from outside of the class.
