### ISSUE TITLE
when i use setReachabilityStatusChangeBlock,for example

### ISSUE THREAD

**Issue by yixiaojichunqiu** [AFNetworking/AFNetworking#4126]
FirstViewController* f = [FirstViewController new];
AFNetworkReachabilityManager *manger = [AFNetworkReachabilityManager sharedManager];
    [manger startMonitoring];
    [manger setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {
        switch (status) {
            case AFNetworkReachabilityStatusUnknown:
                break;
            case AFNetworkReachabilityStatusNotReachable:
                break;
            case AFNetworkReachabilityStatusReachableViaWWAN:
                break;
            case AFNetworkReachabilityStatusReachableViaWiFi:
                SecondViewController* s = [SecondViewController new];
                [self.navigationController pushViewController:f animated:YES];
                [self.navigationController pushViewController:s animated:YES];
                break;
            default:
                break;
        }
    }];
    [manger stopMonitoring];

when i pop controller,s run dealloc ,but f can not run dealloc,why?

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
