### ISSUE TITLE
Crash in AFURLResponseSerialization.m at line 137

### ISSUE THREAD

**Issue by Haberdashery1234** [AFNetworking/AFNetworking#4128]
We are getting crashes reported on Crashlytics at line 137 of AFURLResponseSerialization.m inside the validateResponse method. 

Crashed: com.alamofire.networking.session.manager.processing
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000f7202bec8

```
0 | libobjc.A.dylib | objc_object::release() + 16
1 | MyApp | AFURLResponseSerialization.m line 137-[AFHTTPResponseSerializer validateResponse:data:error:]
2 | MyApp | AFURLResponseSerialization.m line 239-[AFJSONResponseSerializer responseObjectForResponse:data:error:]
3 | MyApp | AWJSONResponseSerializer.m line 25-[AWJSONResponseSerializer responseObjectForResponse:data:error:]
4 | MyApp | AFURLSessionManager.m line 292__72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke.147

```

**Comment by SlaunchaMan** [comment]
Is there any further data in Crashlytics for this crash? Hard to know what’s going on from these lines.

**Comment by Haberdashery1234** [comment]
Unfortunately no more information. I suppose any information about what could cause this crash or how to hunt it down would be helpful. Even if it's not specific.

**Comment by SlaunchaMan** [comment]
I'm not sure what version of AFNetworking you’re using, but in `master` this line covers error reporting. If you put a breakpoint there, do you hit it?

**Comment by Haberdashery1234** [comment]
I am using 3.1. The crash has only reproduced in production, I've never managed to get it locally.

**Comment by zhenian** [comment]
@Haberdashery1234   you should update to the latest version.

#3526 had fixed that.

**Comment by mcmengchen** [comment]
I think this problem is not fixed, my team use the same code as the 

> @Haberdashery1234 you should update to the latest version.
> 
> #3526 had fixed that.

Maybe this question is not fixed. I have the same code in my app, but it still have the same question.

**Comment by streeter** [comment]
@mcmengchen - the latest version release (3.2.1) does not include the changes, but if you pull from the master branch using:

```ruby
pod 'AFNetworking',  :git => 'https://github.com/AFNetworking/AFNetworking.git', :commit => '685e31a31bb1ebce3fdb5a752e392dfd8263e169'
```

Then you'll get the fixes.

**Comment by streeter** [comment]
It looks like [4.0.0](https://github.com/AFNetworking/AFNetworking/releases/tag/4.0.0) was just released, which should fix this issue, and so I believe this could be closed.
