### ISSUE TITLE
How to calculate download speed (MB/s) with AFNetworking?

### ISSUE THREAD

**Issue by MeiBlack** [AFNetworking/AFNetworking#4130]
`NSURLSessionConfiguration` *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];
[manager setDownloadTaskDidWriteDataBlock:^(NSURLSession *session, NSURLSessionDownloadTask *downloadTask, int64_t bytesWritten, int64_t totalBytesWritten, int64_t totalBytesExpectedToWrite) {
        
    }];`

How can I calculate download speed (MB/s)?

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
