### ISSUE TITLE
Uploading MutlipartFormData, error "The network connection was lost"

### ISSUE THREAD

**Issue by astha-gupta** [AFNetworking/AFNetworking#4137]
I am uploading a locally saved image to the server by constructing a multipart form data.
-(void)uploadImage {
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
NSString *directoryPath = [paths objectAtIndex:0];
NSString *filePath =[directoryPath stringByAppendingPathComponent:@"user_profile"];

AF1_HTTPSessionManager *manager = [AF1_HTTPSessionManager manager];
[manager.requestSerializer setValue:@"private_auth_fields" forHTTPHeaderField:@"Authorization"];
manager.responseSerializer = [AF1_HTTPResponseSerializer serializer];
NSURLSessionTask *task = [manager POST:@"media/upload" parameters:nil constructingBodyWithBlock:^(id<AF1_MultipartFormData> formData) {
    NSError *error;
    if (![formData appendPartWithFileURL:[NSURL fileURLWithPath:filePath] name:@"random_name" fileName:@"random_name" mimeType:@"image/png" error:&error]) {
        NSLog(@"error appending part: %@", error);
    }
} success:^(NSURLSessionTask *task, id responseObject) {
    NSLog(@"responseObject = %@", responseObject);
} failure:^(NSURLSessionTask *task, NSError *error) {
    NSLog(@"error = %@", error);
}];
}

The error I face is:
error = Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x170840390 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://ios.mobile.mindtickle.com/mapi/v9/media/upload, NSErrorFailingURLKey=https://ios.mobile.mindtickle.com/mapi/v9/media/upload, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}

Charles request:
<img width="712" alt="charles-request" src="https://user-images.githubusercontent.com/22569451/35377325-ad9cfc62-01d4-11e8-9465-aff2832169ca.png">

**Comment by SlaunchaMan** [comment]
Do your log statements log output? If the network connection is lost then we’d expect this error to appear.
