### ISSUE TITLE
Crash in CoreFoundation - CFDictionaryGetValue

### ISSUE THREAD

**Issue by bondarenko95** [AFNetworking/AFNetworking#4140]
We have a crash in the app. We using the AFNetworking 3.0. 

There are logs: 

> Crashed: com.apple.NSURLSession-work
> 0  CoreFoundation                 0x228f7cdc CFDictionaryGetValue + 27
> 1  Foundation                     0x231eeb5b _NSSetLongLongValueAndNotify + 54
> 2  Foundation                     0x231eeb5b _NSSetLongLongValueAndNotify + 54
> 3  CFNetwork                      0x22f05251 -[__NSCFLocalDataTask _onqueue_didReceiveResponse:completion:] + 68
> 4  CFNetwork                      0x22f48789 __61-[__NSCFURLLocalSessionConnection _didReceiveResponse:sniff:]_block_invoke + 96
> 5  CFNetwork                      0x22f473c3 -[__NSCFURLLocalSessionConnection withDelegateAndPendingCompletion:] + 190
> 6  CFNetwork                      0x22f4871b -[__NSCFURLLocalSessionConnection _didReceiveResponse:sniff:] + 374
> 7  CFNetwork                      0x22f4aa67 SessionConnectionLoadable::_loaderClientEvent_DidReceiveResponse(_CFURLResponse*) + 170
> 8  CFNetwork                      0x22fb1271 ___ZN19URLConnectionLoader26protocolDidReceiveResponseEP14_CFURLResponse_block_invoke + 24
> 9  libdispatch.dylib              0x2255d823 _dispatch_call_block_and_release + 10
> 10 libdispatch.dylib              0x2256a423 _dispatch_queue_drain$VARIANT$mp + 1758
> 11 libdispatch.dylib              0x22569a61 _dispatch_queue_invoke$VARIANT$mp + 284
> 12 libdispatch.dylib              0x2256c15d _dispatch_root_queue_drain + 396
> 13 libdispatch.dylib              0x2256bfcd _dispatch_worker_thread3 + 96
> 14 libsystem_pthread.dylib        0x22721b29 _pthread_wqthread + 1024
> 15 libsystem_pthread.dylib        0x22721718 start_wqthread + 8 

This issue occurs on the iPad 2 (iOS 9.3.5), iPad 3 (iOS 9.3.5), iPhone 6 Plus (iOS 9.3.0).

Can you please help resolve this issue? 
Thanks!

**Comment by SlaunchaMan** [comment]
Sorry, but there’s not enough in that log to go off of—I don’t even see any AFNetworking code in the backtrace.

**Comment by jesusmateos1234** [comment]
same issue
