### ISSUE TITLE
State of AFNetworking

### ISSUE THREAD

**Issue by jcavar** [AFNetworking/AFNetworking#4142]
Hi everyone,
I've been upgrading our project to latest version of AFNetworking and encountered number of issues. I am not blaming anyone, I know people are doing this in their free time and I am very thankful for that. I would just like to understand state of AFNetworking library.

Project currently has 183 open issues and 72 PRs. 

3 most recent releases were:
3.2.0 - Dec 15, 2017 (No CocoaPods release as of yet)
3.1.0 - Mar 31, 2016
3.0.4 - Dec 18, 2015

There is way less activity then before - https://github.com/AFNetworking/AFNetworking/graphs/contributors

Alamofire (which looks much healthier at the moment) is I would guess part of the reason for this but AFNetworking is still useful I believe for many people.

If someone could clarify state of AFNetworking to community I would be thankful.

Thanks once again all contributors for hard work!

**Comment by SlaunchaMan** [comment]
You’re correct that there is more effort behind Alamofire. AFNetworking should be considered to be in maintenance—if there are big issues that come up I’ll try to fix them, but I don’t have the time to invest in large new features. PRs are open if there’s something you want to work on!
