### ISSUE TITLE
Invalid Security Policy

### ISSUE THREAD

**Issue by Jason318** [AFNetworking/AFNetworking#4144]
hello,i used the verson of afnetworking  is 3.2.0,but i get a cresh in my project,"Invalid Security Policy"

code:

- (AFSecurityPolicy *)configureSecurityPolicy
{
    NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"helloufu" ofType:@"cer"];
    NSData *certData = [NSData dataWithContentsOfFile:cerPath];
    NSSet *set = [[NSSet alloc] initWithObjects:certData, nil];
    
    AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
    securityPolicy.allowInvalidCertificates = YES;
    securityPolicy.validatesDomainName = YES;
    securityPolicy.pinnedCertificates = set;
    
    return securityPolicy;
}

Where is the wrong place?

**Comment by Jason318** [comment]
i get it

**Comment by butinmv** [comment]
@Jason318 what happened?

**Comment by Asif332** [comment]
Did anyone get the solution? I am facing the same issue.
 AFNetworking Version 4.0
Xcode: 11.3.1

**Comment by ws752958369** [comment]
@Jason318  I have the same problem now, can you help me?
