### ISSUE TITLE
Version 3.2.0  having Issue with Setting AFSecuirity Policy , "A security policy configured with `%@` can only be applied on a manager with a secure base URL (i.e. https)" same code working in 3.1.0  version.

### ISSUE THREAD

**Issue by kamabhavik** [AFNetworking/AFNetworking#4150]
I am using AFNetworking version 3.2.0.In my app am using SSL Pining with certificate. 

Recently when I have updated my AFNetworking pods from 3.1.0 to 3.2.0 then my SSL Code stopped working with throwing exception with "A security policy configured with `%@` can only be applied on a manager with a secure base URL (i.e. https)".

Please guide me if am doing something wrong or is there anything else I need to improve upon.

**Comment by raistlin969** [comment]
I have this as well, wondering if it is related to issue #4141

**Comment by petrinichav** [comment]
+1 Looks that you have baseURL == nil or http instead https

**Comment by Brukhan** [comment]
+1 I also have same issue. It worked before.

**Comment by CoderSimonWong** [comment]
+1

**Comment by Yelles** [comment]
+1, rollback back for me to the 3.1.0 version...

**Comment by czh0318** [comment]
Init you session manager by this way:
AFHTTPSessionManager * manager = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:<your base url>]];

**Comment by lizhaojie001** [comment]
I think it's come from other libs

**Comment by wangjufan** [comment]
Yes . It is a feature of 3.2.0 , you should use https or pinning none , http with other pinning mode is invalide .

**Comment by Yelles** [comment]
@wangjufan i’m already in full https & pinning mode...

**Comment by wangjufan** [comment]
Check the baseURL , it can't be nil .

**Comment by marcocattai** [comment]
any news on this?

**Comment by jleisurely** [comment]
> Init you session manager by this way:
> AFHTTPSessionManager * manager = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:]];

it is a beat way to solve this problem
