### ISSUE TITLE
Large delay between 100% and compleat uploading files with AFHTTPSessionManager

### ISSUE THREAD

**Issue by Indiana8000** [AFNetworking/AFNetworking#4158]
I use the below method to upload a 2MB image file. It works fine except that the uploadProgress is 100% after 3 Seconds (fast internet) but than stay's there for 5 Seconds. When using a 9MB image the delay is 15 Seconds!
I verified this against a NSURLSessionUploadTask version which immediately go into the success block after 100% is reached (with 2MB and 9MB).

```
AFHTTPSessionManager* networkingManager = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:cURL_API]];
[networkingManager POST:<#(nonnull NSString *)#> parameters:<#(nullable id)#> progress:<#^(NSProgress * _Nonnull uploadProgress)uploadProgress#> success:<#^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject)success#> failure:<#^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error)failure#>
```

**Comment by JunsW** [comment]
Hi, buddy. I'm running into the same issue, How did you solve this ? It's pretty annoying.

**Comment by Indiana8000** [comment]
Looks like it is an iOS issue. I re-build the upload with raw NSURLConnection (where you need to build your own body with NSMutableURLRequest) and had nearly the same effect, just a second faster but still annoying. Setting NSURLCache to zero only impacts downloads. I just wonder how the "big" Apps doing it, maybe there is a secrete parameter?

**Comment by wangjufan** [comment]
Hi, buddies ,  what's exact you do in  [networkingManager POST:<#(nonnull NSString *)#> parameters:<#(nullable id)#> progress:<#^(NSProgress * _Nonnull uploadProgress)uploadProgress#> success:<#^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject)success#> failure:<#^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error)failure#> ?  , i mean the paras you passed in . 
I think the a multipart `POST` request method should be use .
