### ISSUE TITLE
AFURLSessionManagerTaskDelegate crash

### ISSUE THREAD

**Issue by mitchell-dream** [AFNetworking/AFNetworking#4164]
I have a crash in ```[AFURLSessionManagerTaskDelegate initWithTask:]```.
The detail is as follow:
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]

Date/Time:           2018-03-01 01:07:33.1465 +0800
Launch Time:         2018-03-01 01:07:29.9930 +0800
OS Version:          iPhone OS 10.3.3 (14G60)

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000020
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libobjc.A.dylib               	0x000000018d18280c 0x18d17c000 + 26636
1   Foundation                    	0x000000018f113514 0x18f10d000 + 25876
2   Foundation                    	0x000000018f333074 0x18f10d000 + 2252916
3   Foundation                    	0x000000018f3333b4 0x18f10d000 + 2253748
4   myApp                    	-[AFURLSessionManagerTaskDelegate initWithTask:] (in Hao123News) (AFURLSessionManager.m:143)
5   myApp                    	-[AFURLSessionManager addDelegateForDataTask:uploadProgress:downloadProgress:completionHandler:] (in Hao123News) (AFURLSessionManager.m:582)
6   myApp                    	-[AFURLSessionManager dataTaskWithRequest:uploadProgress:downloadProgress:completionHandler:] (in Hao123News) (AFURLSessionManager.m:728)
7   myApp                    	-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:] (in Hao123News) (AFHTTPSessionManager.m:0)
8   myApp                    	-[AFHTTPSessionManager POST:parameters:progress:success:failure:] (in Hao123News) (AFHTTPSessionManager.m:179)
9   myApp                    	+[myApp WorkService httpAsyncPostWithDictionary:completionBlock:] (in myApp) (myApp NetWorkService.m:0)
10 -15 myApp call stack
16  myApp                    	__66+[myAppNetWorkService httpAsyncPostWithDictionary:completionBlock:]_block_invoke (in Hao123News) (myAppNetWorkService.m:38)
17  myApp                    	__116-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:]_block_invoke.149 (in Hao123News) (AFHTTPSessionManager.m:302)
18  myApp                    	__72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.157 (in Hao123News) (AFURLSessionManager.m:242)
19  libdispatch.dylib             	0x000000018d5da9e0 0x18d5d9000 + 6624
20  libdispatch.dylib             	0x000000018d5da9a0 0x18d5d9000 + 6560
21  libdispatch.dylib             	0x000000018d5df3c0 0x18d5d9000 + 25536
22  CoreFoundation                	0x000000018e6d10c8 0x18e5f6000 + 897224
23  CoreFoundation                	0x000000018e6cece4 0x18e5f6000 + 888036
24  CoreFoundation                	0x000000018e5feda4 0x18e5f6000 + 36260
25  GraphicsServices              	0x0000000190069074 0x19005d000 + 49268
26  UIKit                         	0x00000001948b9c9c 0x194845000 + 478364
27  myApp                    	main (in myApp) (main.m:17)
28  libdyld.dylib                 	0x000000018d60d59c 0x18d609000 + 17820

**Comment by heleiwu** [comment]
I have the same issue, seems dure to KVO。
