### ISSUE TITLE
random crash at AFQueryStringPairsFromKeyAndValue

### ISSUE THREAD

**Issue by Wu-Dong-Hui** [AFNetworking/AFNetworking#4167]
Xcode Version: 9.1 (9B55)
The version of iOS  targeting:8.0

This is online crash report, so this is all I can get
It puzzles me. What can cause this problem?Please help me. Thank you

![image](https://user-images.githubusercontent.com/8233494/37067120-5a05dbda-21e3-11e8-8236-3452b0a839e6.png)
![image](https://user-images.githubusercontent.com/8233494/37068101-fb991dbe-21e7-11e8-8d18-eb042644eac3.png)

**Comment by Wu-Dong-Hui** [comment]
So? Anyone has this issue?

**Comment by jshier** [comment]
Please attempt to replicate using version 4. If you do still see the issue, please open another issue.
