### ISSUE TITLE
一个接口用postman调用没问题，但是用afn调用有时候会出现问题

### ISSUE THREAD

**Issue by KeymonWong** [AFNetworking/AFNetworking#4168]
问题1：
一个接口用postman调用没问题，但是用afn调用，在下面方法里面 返回的responseObject说是 后台返回的错误码是 9999（系统错误，请联系管理员），但是 postman 调用确实没这问题，另外 看了一下dataTaskWithRequest:。。。这个方法是afn的，
另外这些我都设置了：
 _manager.responseSerializer = [AFJSONResponseSerializer serializer];
 _manager.responseSerializer.acceptableContentTypes = [NSSet setWithObjects:@"application/json",@"text/json",@"text/html",@"application/xml",@"text/plain", nil];

dataTask = [_manager dataTaskWithRequest:request uploadProgress:uploadProgress downloadProgress:downloadProgress completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
        [self handleRequestResult:dataTask response:response responseObject:responseObject error:error];
    }];

问题2：
App端，两个接口同时调用，afn会报数据格式错误，如以下写法：
//请求接口1：
Request1 *req1 = [[Request1 requestWithSuccessBlock:^(id){
} failureBlock:^(NSError *){
}];
req1.params = params;
[req1 startRequest];

//请求接口2：
Request2 *req2 = [[Request2 requestWithSuccessBlock:^(id){
} failureBlock:^(NSError *){
}];
req2.params = params;
[req2 startRequest];

就如上写法，有时候在afn底层下面方法里面：
#pragma mark - AFURLResponseSerialization
- (id)responseObjectForResponse:(NSURLResponse *)response
                           data:(NSData *)data
                          error:(NSError *__autoreleasing *)error
{
}
手动将data转换成string
NSString *string = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
这个string有时候拿到 会是 两个json拼在一块的字符串比如这样的：
"{code:"",data:"",msg:""}{code:"",data:"",msg:""}"

请问 这两个问题是什么问题？afn框架的问题，还是后台返回的问题？应该怎么解决？

问题2 后台说是 两个接口分别返回数据的，但是通过afn拿到的数据就是两个接口返回的json拼在一块的。另外 如果 //请求接口1 我先调用，过1秒后再调用//请求接口2，就会没问题。

谢谢！

**Comment by wangjufan** [comment]
You can use AFCompoundResponseSerializer instead of  AFJSONResponseSerializer for potential mulit-types .

**Comment by lianleven** [comment]
@KeymonWong 这个问题明显是你上层封装的问题，请仔细检查一下自己的代码
