### ISSUE TITLE
Request failed: unsupported media type (415)

### ISSUE THREAD

**Issue by coooliang** [AFNetworking/AFNetworking#4174]
you need 

self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", nil nil]; 
to
 self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript",@"text/html", nil nil];

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
