### ISSUE TITLE
How to get the version of AFNetworking in a project

### ISSUE THREAD

**Issue by subarashii** [AFNetworking/AFNetworking#4177]
I get a project source with AFNetworking Framework. Where can I get the version of AFNetworking? There is no readme file in the project. I guess it's 2.x, because AFHTTPRequestOperation.h class exist.

**Comment by SlaunchaMan** [comment]
Is there an `Info.plist` in the source you have?

**Comment by subarashii** [comment]
@SlaunchaMan there is no info.plist in the AFNetworking Folder

**Comment by SlaunchaMan** [comment]
If all you have is the AFNetworking folder, there isn’t anything in there with a version number on it, so it’s hard to say which version it is (or if it’s been modified). To be safe, you should download the version you want to use and name the folder after it or use a package manager like CocoaPods or Carthage to manage your versions.
