### ISSUE TITLE
A performance issue in AFAutoPurgingImageCache

### ISSUE THREAD

**Issue by wangjufan** [AFNetworking/AFNetworking#4185]
I just don't understand why two dispatch_barrier_async was used in 
- (void)addImage:(UIImage *)image withIdentifier:(NSString *)identifier .

I think putting all the codes in a single dispatch_barrier_async is better than splitting them into two .

What's the reasons behind the scene ? Thanks .

**Comment by z4kwin** [comment]
The dispatch queue on which to execute the barrier block. This parameter cannot be NULL.
* what's meaning the 'barrier'?
