### ISSUE TITLE
[ios 11] AFHTTPSessionManager do not response in background mode

### ISSUE THREAD

**Issue by veila** [AFNetworking/AFNetworking#4189]
Hi,
I have a problem. When I request an api, after that I lock device. The Request do not callback, it's seem interrupt. When I open app from background. It's return response immediately.
I test on ios 10, it's work

**Comment by wangjufan** [comment]
use AFJSONResponseSerializer instead .

**Comment by kwontaewan** [comment]
It works fine on iOS 10, but has the same issue on 11..
