### ISSUE TITLE
`AFNetworkReachabilityManager managerForDomain` says domain is reachable when it is not.

### ISSUE THREAD

**Issue by nirmalspeed** [AFNetworking/AFNetworking#4193]
Version: 3.2
I was testing the `managerForDomain` method to see if it would correctly behave if the host ever went offline by giving it a completely random url and for some reason the `AFNetworkReachabilityStatusReachableViaWiFi` switch statement gets hit even though the domain is a fake domain. I am not sure if I'm misunderstanding how this is supposed to behave but I don't believe it should behave this way. 

this domain is not reachable via `ping www.jgioewrajfewafewjiojwojfewoa12.com` so I assumed it would always be a non-reachable domain.
```
AFNetworkReachabilityManager *reachabilityManager = [AFNetworkReachabilityManager managerForDomain:@"www.jgioewrajfewafewjiojwojfewoa12.com"];
[reachabilityManager setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {

        AFNetworkReachabilityStatus networkStatus = status;
        switch (status) {
            case AFNetworkReachabilityStatusNotReachable:
            {
                // Hit on cellular
                break;
            }
            case AFNetworkReachabilityStatusReachableViaWWAN:
            {
                // This doesn't get hit (correct)
                break;
            }
            case AFNetworkReachabilityStatusReachableViaWiFi:
            {
                // This is getting hit
                break;
            }
            case AFNetworkReachabilityStatusUnknown:
            {
                break;
            }
            default: break;
        }
     }];
     [reachabilityManager startMonitoring];
```

**Comment by wangjufan** [comment]
Tested on simulator and device , AFNetworkReachabilityManager return no after yes when i swithed the wifi network from offline to online.  Is anyone found the solution ? I think that is an bug in SCNetwork .
