### ISSUE TITLE
Crash in [AFURLRequestSerialization observeValueForKeyPath:ofObject:change:context:]

### ISSUE THREAD

**Issue by crmo** [AFNetworking/AFNetworking#4205]
If change the AFHTTPRequestSerializer asynchronously,mutableObservedChangedKeyPaths will data race.

**Comment by codeflayer** [comment]
Have fix it ? @crmo

**Comment by codeflayer** [comment]
Have you fix it?

**Comment by codeflayer** [comment]
Have you fix it ? @crmo

**Comment by codeflayer** [comment]
I had same problem too
![1526370359397](https://user-images.githubusercontent.com/8957164/40043460-198be2ac-5857-11e8-94eb-74a82c6e13ad.jpg)

**Comment by crmo** [comment]
@codeflayer The crash may caused by data race,the mutableObservedChangedKeyPaths is not thread safety.

**Comment by codeflayer** [comment]
It seems that many people have encountered this issue, there it is.  Take a look at it, please.   @SlaunchaMan 
https://github.com/AFNetworking/AFNetworking/issues/3942,
https://stackoverflow.com/questions/49980048/swift-objective-c-use-afnetwork-crash,

**Comment by Mamakou** [comment]
Excuse me ！Who has a solution！
I have this problem too.

**Comment by Mamakou** [comment]
can we add a thread lock?

**Comment by ghass64** [comment]
I am facing this issue from a long time now, any update on the solution ?

**Comment by Mamakou** [comment]
when I use thread lock, the incidence of problems has been greatly reduced.

**Comment by xiaogehenjimo** [comment]
@Mamakou How did you fix it? Did you change the AF source code?

**Comment by Mamakou** [comment]
> @Mamakou How did you fix it? Did you change the AF source code?

yes , I did it
