### ISSUE TITLE
get 404 error sometimes,   but android allways successful, anyone know why?

### ISSUE THREAD

**Issue by JavenZ** [AFNetworking/AFNetworking#4214]
Most of the time request successful. but sometimes get 404 error. and android allways successful, never 404

**Comment by freesan44** [comment]
I have the same problem

**Comment by JavenZ** [comment]
那是两年前遇到的问题了，我记得好像最后我是在Network层判断如果返回这种特定的error message，就自动再次调用接口，重试3次还是5次来着。
