### ISSUE TITLE
Basic authentication fails when password has unicode characters

### ISSUE THREAD

**Issue by ponnierohith** [AFNetworking/AFNetworking#4217]
If the password has unicode characters (like à, å, è, ç) then basic authentication fails when using AFNetworking. AFNetworking is encoding the password string using UTF-8 before doing base64 encoding for Basic Authorization header. This is giving a 401(Unauthorized).

**Comment by karimhm** [comment]
@ponnierohith Could you give us more informations, like what is the expected password from the server, could you provide a sample code?.
