### ISSUE TITLE
cycle retain

### ISSUE THREAD

**Issue by huangdeng** [AFNetworking/AFNetworking#4218]
[[AFNetworkReachabilityManager sharedManager] setReachabilityStatusChangeBlock:^(AFNetworkReachabilityStatus status) {}];
This Method maybe lead to cycle retain.

**Comment by hulizhen** [comment]
Could you please describe that retain cycle in more detail?

**Comment by SlaunchaMan** [comment]
It’s certainly possible that misuse of this method could lead to a memory leak, but it’s the responsibility of the developer to avoid this in general.
