### ISSUE TITLE
[iOS11]: HTTPS Connection: Keep-Alive does not work properly

### ISSUE THREAD

**Issue by MorpheusDe97** [AFNetworking/AFNetworking#4221]
With iOS 11, we got a problem using the cordova-plugin-advanced-http, which uses the AFNetworking-Plugin on iOS.

We want the App to produce a persistant connection to a server with just one certificate handshake. Thats why we set the keep-alive-header for each request.

  let headers = {
    Connection: "keep-alive",
  };
But what we get is, if the App sends several requests with different nodes, like
https://{SERVER_IP}/Node1
https://{SERVER_IP}/Node2
https://{SERVER_IP}/Node3

What we now get is: The first request is kept alive, until the server closes the connection because of an arriving keep-alive-timeout.

The app waits, until the first connection was closed and starts the next request, allthough we thought that the client sends the other requests immediately after the first response.

For android, it works pretty fine, but in iOS, the keep-alive doesn't work as expected.

Is there any other flag or function that we have to set or to call, so that the keep-alive-connection works in iOS?

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!

**Comment by o2xufei** [comment]
mark!
