### ISSUE TITLE
Crashed: -[AFURLSessionManager removeNotificationObserverForTask:] (in MyApp) + 172

### ISSUE THREAD

**Issue by DarrenChen123** [AFNetworking/AFNetworking#4222]
UUID: A37E0B95-7266-3FEF-8B7D-427468E8B099
NAME: MyApp
ARCH: arm64
ADDR: 0x100028000

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString match:]: unrecognized selector sent to instance 0x17429b6c0'

Last Exception Backtrace:
0   CoreFoundation                      0x00000001920241c0 0x191ef5000 + 1241536
1   libobjc.A.dylib                     0x0000000190a5c55c 0x190a54000 + 34140
2   CoreFoundation                      0x000000019202b278 0x191ef5000 + 1270392
3   CoreFoundation                      0x0000000192028278 0x191ef5000 + 1258104
4   CoreFoundation                      0x0000000191f2259c 0x191ef5000 + 185756
5   CoreFoundation                      0x0000000191fd5d50 0x191ef5000 + 920912
6   CoreFoundation                      0x00000001920880b0 0x191ef5000 + 1650864
7   CoreFoundation                      0x000000019202d404 0x191ef5000 + 1278980
8   CoreFoundation                      0x0000000191f227a0 0x191ef5000 + 186272
9   Foundation                          0x0000000192a06e88 0x192a00000 + 28296
10  BBAPods                             -[AFURLSessionManager removeNotificationObserverForTask:] (in MyApp) + 172
11  BBAPods                             -[AFURLSessionManager removeDelegateForTask:] (in MyApp) + 168
12  BBAPods                             -[AFURLSessionManager URLSession:task:didCompleteWithError:] (in MyApp) + 156
13  CFNetwork                           0x00000001927d46e8 0x19261f000 + 1791720
14  Foundation                          0x0000000192ae57e4 0x192a00000 + 940004
15  Foundation                          0x0000000192a2a358 0x192a00000 + 172888
16  Foundation                          0x0000000192a1a954 0x192a00000 + 108884
17  Foundation                          0x0000000192ae7b90 0x192a00000 + 949136
18  libdispatch.dylib                   0x0000000190ead1c0 0x190eac000 + 4544
19  libdispatch.dylib                   0x0000000190ebb444 0x190eac000 + 62532
20  libdispatch.dylib                   0x0000000190eb09a8 0x190eac000 + 18856
21  libdispatch.dylib                   0x0000000190ebd38c 0x190eac000 + 70540
22  libdispatch.dylib                   0x0000000190ebd0ec 0x190eac000 + 69868
23  libsystem_pthread.dylib             0x00000001910b52c8 0x1910b4000 + 4808
24  libsystem_pthread.dylib             0x00000001910b4db4 0x1910b4000 + 3508

iOS10, and the device is iPhone 6s plus.

**Comment by SlaunchaMan** [comment]
Hard to say what’s happening from this crash log. What version of AFNetworking are you using?
