### ISSUE TITLE
Usage of DISPATCH_QUEUE_PRIORITY_BACKGROUND

### ISSUE THREAD

**Issue by ghugues** [AFNetworking/AFNetworking#4223]
After reading [this tweet](https://twitter.com/gregheo/status/1001501337907970048), it appears that the [official Apple documentation](https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html) mentions that background queues may be stopped when in low power mode.
 
As the result, [this block](https://github.com/AFNetworking/AFNetworking/blob/746f6c3a1e2c3a3dfbac1c3d18c08a5d121c8df3/AFNetworking/AFNetworkReachabilityManager.m#L227) may never be executed in low power mode, which doesn't seem to be the intended behavior.

**Comment by tewha** [comment]
I thought this report was wrong at first, because the documentation isn't all in one spot. But I chased it down and this looks like the correct interpretation.
