### ISSUE TITLE
Multiple image uploading as multipart form data

### ISSUE THREAD

**Issue by reenaphilip** [AFNetworking/AFNetworking#4228]
I am using AFNetworking  2.6.3 in my swift application. I have requirement of uploading multiple images to server . For this I have written the following code

self.webserviceHandler.post(serviceName, parameters: nil, constructingBodyWith: { (data:AFMultipartFormData) in
				for i in 0..<imageArray.count{
					let imagData = UIImageJPEGRepresentation(imageArray[i], 0.5)
					data.appendPart(withFileData: imagData!, name: "MenaImage\(i)", fileName: fileNameArray[i], mimeType: "image/jpeg")
					
				}
				for (key, value) in parameters{
					data.appendPart(withForm: "\(value)".data(using: .utf8)!, name: key as! String)
				}
            }, success: { (operation:AFHTTPRequestOperation!, responseObject:Any!) in
				successResponseClosure(responseObject as AnyObject)
            }) { (operation:AFHTTPRequestOperation!, error:Error!) in
					errorClosure(error as NSError)
				}

webserviceHandler is AFHTTPRequestOperationManager

With the above code, I am able to upload single image. But when I try to upload multiple images, server is not able to parse the data.
This is the request 

{
    "Accept-Language" = "en-BH;q=1, ar-BH;q=0.9, en-GB;q=0.8";
    "Content-Length" = 3023913;
    "Content-Type" = "multipart/form-data; boundary=Boundary+F955A845D801084F";
    "User-Agent" = "MBB/1.0 (iPhone; iOS 11.2.5; Scale/2.00)";
} (null)
Is there any error in my implementation ?

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
