### ISSUE TITLE
Certificate pinning fails on iOS 11.4.1 beta and iOS 12

### ISSUE THREAD

**Issue by omihailo** [AFNetworking/AFNetworking#4229]
Following Google's plan for stopping the trust in Symantec, Apple with iOS 11.4.1 beta 1 and iOS 12 beta 1, Apple started gradually to no longer trust the Symantec CA, and according to rumors will initially start not trusting the Symantec CA in the fall of 2018. 

I already checked this, where I have a server configured with Symantec Class 3 issued before 1 June 2016, and the certificate pinning with AFNetworking 2.6.0  fails with the code kSecTrustResultRecoverableTrustFailure.
I was not expecting this since if Apple starts distrusting Symantec, should only distrust in their system applications (e.g. Safari), but not in their APIs such SecTrustEvaluate, especially if you are doing certificate pinning with your own anchor certificates ignoring the build-in anchor certificates.

Can you please check this?

**Comment by SlaunchaMan** [comment]
Just to be clear: do you have the Symantec certificate in the application bundle? If you don’t have the Symantec certificate in the bundle then I would expect `SecTrustEvaluate` to fall back to the system certificates. If you have the entire certificate chain in the app bundle, then let me know—though I’m not sure how easy it would be for you to provide the certificates for testing, it would be an interesting test case.

**Comment by omihailo** [comment]
Hey @SlaunchaMan, yes is Symantec certificate, and I have it bundled in the application. SecTrustEvaluate returns kSecTrustResultRecoverableTrustFailure. So the system certificates are not taking in consideration, the Symantec is my own anchor certificates, which I am configuring.
The certificate was issued before 1 June 2016, which fits in the distrust spectra. 

Please note that I did the same thing (as AFNetworking), with my own code, and the result is the same, so this is not issued to AFNetworking, but Apple's API.

I wanted to check with you whether I am missing something and whether you are aware of it, but Apple came with an official statement https://support.apple.com/en-us/HT208860.
