### ISSUE TITLE
AFHTTPBodyPart or AFMultipartBodyStream leak

### ISSUE THREAD

**Issue by MagicNew** [AFNetworking/AFNetworking#4230]
Same like #4224 

![picture](https://user-images.githubusercontent.com/5568333/41333407-436909f0-6f14-11e8-9318-2baae058fb3c.png)
![picture1](https://user-images.githubusercontent.com/5568333/41333408-43ac66a0-6f14-11e8-8781-007c589fbf23.png)
![picture2](https://user-images.githubusercontent.com/5568333/41333409-43ece414-6f14-11e8-83ab-9061bfad78b6.png)
![picture3](https://user-images.githubusercontent.com/5568333/41333410-442111c6-6f14-11e8-9c0d-5562f773d6be.png)

**Comment by shuoli84** [comment]
Same here. Seems no update.
