### ISSUE TITLE
一发起请求就闪退

### ISSUE THREAD

**Issue by GuYueZhaoJinRen** [AFNetworking/AFNetworking#4233]
*** -[AFHTTPRequestSerializer release]: message sent to deallocated instance 0x6000002a8e20

**Comment by SlaunchaMan** [comment]
Hi there! From the looks of that message, it sounds like you aren’t storing a strong reference to this request serializer, and it’s being deallocated unexpectedly.

For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
