### ISSUE TITLE
Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/plain"

### ISSUE THREAD

**Issue by kimseak-dev** [AFNetworking/AFNetworking#4235]
**When I request POST and then it returned an error in error block. The following is error message**

`Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/plain" UserInfo={NSLocalizedDescription=Request failed: unacceptable content-type: text/plain, NSErrorFailingURLKey=https://acmob.acledabank.com.kh/Native/api/DX5JIACOVU, com.alamofire.serialization.response.error.data=<4448754d 46503446 68574b61 4e61636c 65646162 616e6b53 65637572 69747954 43445354 64307046 3739554d 35743278 6e546e42 63536955 72413662 52746453 646a3839 35415378 33417172 42356f43 4c623164 4b7a4f61 636c6564 6162616e 6b536563 75726974 79544359 42626163 6c656461 62616e6b 53656375 72697479 54435867 4d794572 4431415a 344e7964 744a6159 6e76724c 35453235 4375796c 30554b38 49665168 44376358 7561636c 65646162 616e6b53 65637572 69747954 43577966 6c526b37 67614e69 37594d65 7a71507a 49665666 4d59764f 6b2b3534 6b455066 6c654771 7a695730 42317070 55747269 51773859 61636c65 64616261 6e6b5365 63757269 74795443 5547704a 6a523449 78337751 42423139 76746a30 77376467 4647506b 424f4647 4d55647a 577a5847 5a734839 704c4868 45433643 44506143 34533736 4539774c 4f763069 6841646e 6d69576f 52686a55 47785950 4378516c 4f364932 5a785532 752b4a66 43534f48 4772706f 37697135 5557506a 3843314a 51564752 63484d71 71387351 6636336f 7a643252 684b6357 44774f57 43733135 666d3830 43385339 5a70504e 524a4667 64617768 6230446c 3459334f 2b576336 70626a42 45516376 5661636c 65646162 616e6b53 65637572 69747954 43424854 34356c67 73655244 70445031 4d414f62 712b4b34 30666a45 38785a36 52683134 4c58336e 58326a63 51773552 6b527946 4e6f4470 6f767544 78783175 39653433 79533153 6a445a36 63415676 35514a31 517a3835 646c6977 6c77576d 44576439 58784e69 6875576c 7a726838 52386342 6f56704d 374e3576 413d>, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x1c0235120> { URL: https://acmob.acledabank.com.kh/Native/api/DX5JIACOVU } { Status Code: 200, Headers {
    "Access-Control-Allow-Headers" =     (
        "Origin, Content-Type, Accept, Authorization"
    );
    "Access-Control-Allow-Methods" =     (
        "GET,POST"
    );
    "Access-Control-Allow-Origin" =     (
        "https://qruat.acledabank.com.kh/",
        "https://acmob.acledabank.com.kh/"
    );
    "Cache-Control" =     (
        "no-cache"
    );
    "Content-Length" =     (
        606
    );
    "Content-Security-Policy" =     (
        "default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'unsafe-inline';"
    );
    "Content-Type" =     (
        "text/plain; charset=utf-8"
    );
    Date =     (
        "Fri, 29 Jun 2018 01:16:57 GMT"
    );
    Expires =     (
        "-1"
    );
    Pragma =     (
        "no-cache"
    );
    "Strict-Transport-Security" =     (
        "max-age=31536000"
    );
    "X-AspNet-Version" =     (
        "4.0.30319"
    );
    "X-Content-Type-Options" =     (
        nosniff
    );
    "X-Frame-Options" =     (
        SAMEORIGIN
    );
    "X-Powered-By" =     (
        "ASP.NET"
    );
    "x-xss-protection" =     (
        "1; mode=block"
    );
} }}
`
**Code**

` public func requestPostMethodWithAFNetworkForLogin(params:Parameters, url:String, success: @escaping (JSON) -> (), failure: @escaping (String?) -> ()) {`
    `let manager = AFHTTPSessionManager()`
     `let reponseSerializer = AFJSONResponseSerializer()`
     `let urlFull = AppEnvironment.entryPointURL + "api/" + url`
     `let urlConfig = urlFull.addingPercentEncoding(withAllowedCharacters: .urlFragmentAllowed)`
     `manager.post( urlConfig!, parameters: params, progress: { (progress) in`
      `}, success: { (task, response) in`
      `}) { (task, error) in`
     `print(error)`
  ` }`
`}`

I try to add header request
 _manager.responseSerializer.acceptableContentTypes = NSSet(objects: "text/plain", "text/html", "application/json", "audio/wav", "application/octest-stream", "text/javascript") as! Set<String>_

But still not work

Could you please  help me to solve this problem ?

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!

**Comment by kimseak-dev** [comment]
ok thanks
