### ISSUE TITLE
AF3.0   -1005 error occurs when the network is normal.

### ISSUE THREAD

**Issue by OHeroJ** [AFNetworking/AFNetworking#4238]
AF3.0   -1005 error occurs when the network is normal.

Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x1c4840630 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "The network connection was lost."

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
