### ISSUE TITLE
crash while using HTTPS baseurl

### ISSUE THREAD

**Issue by Nisha-SpaceoTech** [AFNetworking/AFNetworking#4240]
Getting error when my base url is set with HTTPS. Here is the error "A security policy configured with `AFSSLPinningModeCertificate` can only be applied on a manager with a secure base URL"
I have also set allowInvalidCertificates property to TRUE. Still not working for me. Did anyone get the solution for this?

**Comment by SlaunchaMan** [comment]
The relevant part of the code is `![self.baseURL.scheme isEqualToString:@"https"]`. Make sure your base URL’s scheme is `https`; this is case-sensitive, so `HTTPS` would not work.
