### ISSUE TITLE
AFQueryStringPairsFromKeyAndValue not giving proper URL with NSArray??

### ISSUE THREAD

**Issue by priyankamistry09** [AFNetworking/AFNetworking#4241]
Hi,

I am trying to send following parameters in GET method call:
```
{
    query =     {
        "$or" =         (
                        {
                name = yes;
            },
                        {
                status = Open;
            }
        );
    };
}
```

But it seems it is not returning the proper URL:
baseURL/objects?query%5B%24or%5D%5B%5D%5Bname%5D=yes&query%5B%24or%5D%5B%5D%5Bstatus%5D=Open

I was expecting to "Or" my data, but it is doing "And".
I am using `AFURLRequestSerialization` class.

It was working properly in POST call, but in GET it is not working as expected.

Any idea about this? 
Kindly reply asap as I have a release tomorrow.

Thanks.

**Comment by priyankamistry09** [comment]
Hi, 

I have resolved this by converting dictionary against _query_ key to a string and adding this string as a value of key _query_ in the dictionary.
 So my parameters will look like:
```
parameters: {
    query = "{\"$or\":[{\"name\":\"yes\"},{\"status\":\"Open\"}]}";
}
```
Then I am passing this prameters to AFNetworking.

**Comment by SlaunchaMan** [comment]
The value for the "$or" key in your original post is an array, which is why you get the query you do. To get the result you’re expecting, it should look like:

```{
	query = {
		"$or" = {
			name = yes,
			status = Open
		}
	}
}```

Hope this helps!
