### ISSUE TITLE
can provide a API to update AFHTTPSessionManager's baseURL ?

### ISSUE THREAD

**Issue by kobe1941** [AFNetworking/AFNetworking#4242]
baseURL in AFHTTPSessionManager is readonly, sometimes we want to change it's baseURL by remoteConfig from server, but i don't want to create a new instance.
add a API is more suitable.

**Comment by SlaunchaMan** [comment]
That’s not an unreasonable idea, but we’d have to be careful when considering the `AFSecurityPolicy` of the HTTP session manager in this case. If you change the `baseURL` from an HTTPS scheme to an HTTP scheme, what should happen? If you try to set a security policy on the latter, it throws an exception. To match that behavior, we’d have to throw an exception when you change the base URL, which most developers wouldn’t expect. Alternatively, we could reset the security policy when changing the base URL, which might be unexpected in more subtle ways (that could weaken app security). I’m open to suggestions, but your best bet is to probably recreate the manager when you need a new base URL.

**Comment by kobe1941** [comment]
you are right，I will recreate the manager to update baseURL.
thanks for your reply😊
