### ISSUE TITLE
Problem with @available annotation

### ISSUE THREAD

**Issue by lukaszlabunski** [AFNetworking/AFNetworking#4244]
I have a problem with @available annotation. When I tried to build my library I got 
`Undefined symbols for architecture arm64:
  "___isOSVersionAtLeast", referenced from:
      -[AFURLSessionManagerTaskDelegate initWithTask:] in libAFNetworking.a(AFURLSessionManager.o)`

This problem disappear when I change (in Pods) iOS Deployment Target to 11 but its not a solution.

Do you known why this happens?

**Comment by SlaunchaMan** [comment]
What is your current Xcode version and deployment target? Also, what version of AFNetworking are you using?

**Comment by lukaszlabunski** [comment]
Xcode version : 9.3
Deployment target: 9.0
AFNetworking: 3.2.1

**Comment by lukaszlabunski** [comment]
I build static library and than that @available works correctly. But when I build it as a dynamic framework (AFNetworking is included statically) I get that error.

**Comment by SlaunchaMan** [comment]
Sorry for the delay on this, but I’m having trouble reproducing it on my end. I have a dynamic framework that includes AFNetworking using CocoaPods without `!use_frameworks`, and this isn't causing any issues. Can you go into any more detail about how you have AFNetworking set up?
