### ISSUE TITLE
Why set the maxConcurrentOperationCount of the delegateQueue to 1 ？

### ISSUE THREAD

**Issue by kekeYezi** [AFNetworking/AFNetworking#4251]
Hi～
I have a question I would like to ask you. I found that AF uses NSOperationQueue when NSURLSession is initialized and sets maxConcurrentOperationCount = 1. What is the purpose of doing this?
What happens if I set delegateQueue to [NSOperationQueue mainQueue]?

AF：
self.operationQueue = [[NSOperationQueue alloc] init];
self.operationQueue.maxConcurrentOperationCount = 1;
self.session = [NSURLSession sessionWithConfiguration:self.sessionConfiguration delegate:self delegateQueue:self.operationQueue];

I wanna:
self.session = [NSURLSession sessionWithConfiguration:sessionConfiguration delegate:self delegateQueue:[NSOperationQueue mainQueue]];

Thank you very much.

**Comment by CaiChenghan** [comment]
这个是**NSURLSession**的delegate的Queue，也就是URLSession**数据回调**的那个线程。如果你设置为主线程，可能会有些卡顿，毕竟数据回调的逻辑在主线程中执行了。但是设置为异步线程，那么数据逻辑处理则是在异步线程中执行的，不会影响到主线程，这种在网络环境差同时又执行了较多的请求的时候可能会有体现。至于设置为串行处理，估计是为了让接收到的数据一个一个的处理，防止数据异常。这个delegate线程，个人觉得不要动它，我们只需要使用就可以了。
