### ISSUE TITLE
Request Chinese  Domain Name

### ISSUE THREAD

**Issue by peifeiyang** [AFNetworking/AFNetworking#4252]

**Comment by peifeiyang** [comment]
Init NSMutableURLRequest url is null When I request chinese domain name (http://张仲景大药房.net:8093)
<img width="1087" alt="2018-07-20 1 57 04" src="https://user-images.githubusercontent.com/21214212/42987227-0f88441e-8c2b-11e8-9fb0-4056cbb04a05.png">

**Comment by peifeiyang** [comment]
<img width="1087" alt="2018-07-20 1 57 04" src="https://user-images.githubusercontent.com/21214212/42987309-5ee61a68-8c2b-11e8-9e23-1c5a067c296e.png">

**Comment by SlaunchaMan** [comment]
`NSURLRequest` and `NSMutableURLRequest` are Apple framework methods; a good place to ask about this would be [Apple’s developer forums](https://forums.developer.apple.com).
