### ISSUE TITLE
关于AFN下载的问题

### ISSUE THREAD

**Issue by zhangfurun** [AFNetworking/AFNetworking#4258]
AFN下载文件会下载到默认的文件夹tmp,现在想问的是,如何可以自定义文件的下载路径
这里不是说下载完走的destination,是下载中,直接将文件下载到指定的文件夹

目前考虑到的是拿到下载的数据流data,使用NSFileHandler将data写入指定的文件夹,但是感觉本身应该是AFN提供的方法接口,这样处理属于数据浪费.

AFN2.0时代,是可以设置operation.outputStream设置数据路径,升级到AFN3.0后,不知道如何处理

**Comment by CaiChenghan** [comment]
这个需要设置，例如我写的
![image](https://user-images.githubusercontent.com/9568389/43246531-8b7b7e88-9077-11e8-98cf-ccf03cb7d873.png)

这里的**targetPath**，下载数据存放的路径，也就是我们自定义的下载路径。
这里的**filePath**是下载完成的时候，告诉你这个文件存放的路径，也就是完整文件的路径，通常跟targetPath保持一致。

**Comment by zhangfurun** [comment]
看你的逻辑  在下载当前,先判断resumeData,这个因该是已经下载过得数据,这个如何获得?

**Comment by CaiChenghan** [comment]
因为下载前，设置了数据存放路径。对于每一个下载，这个路径是唯一的，相对的，这个路径下的数据文件，即使是没有下载完成的数据，也是唯一的。因此，只需要获取到这个没有下载完成的数据，就可以得到resumeData了。我以前写了一个下载的[Demo](https://github.com/CaiChenghan/MyTaskManager)，虽然有些烂，但是你可以参考下。

**Comment by zhangfurun** [comment]
@CaiChenghan 我现在的需求是,下载某个文件,下载到一半,关闭app,下次打开,继续下载

**Comment by zhangfurun** [comment]
@CaiChenghan 也就是说这个resumData你是通过AFN获取到,并且自定义保存的是吗?

**Comment by CaiChenghan** [comment]
你这个其实就是断点下载，你只需要下载之前，检查缓存数据。如果有缓存数据，就从缓存数据的点继续下载就可以了。而缓存数据，即使App关闭了，也还是存在的。所以，你只需要获取到resumData，就可以断点下载了。至于缓存数据的路径，在下载前就已经设置了，也就上面那个自定义的路径。你可以打印那个路径，用finder查看，就会发现里面的文件：未完成的和已完成的。

**Comment by zhangfurun** [comment]
@CaiChenghan 看了关于resumeData的问题,发现,在对downloadTask做操作的时候,是可以的拿到resumeData,不过,需要对这个数据进行存储....十分感谢

**Comment by Chocolate-su** [comment]
leave this issue alone
