### ISSUE TITLE
Crash: NSURLSessionTaskDelegate EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Daemonson** [AFNetworking/AFNetworking#4263]
![image](https://user-images.githubusercontent.com/7628550/43362934-bb59cb46-9329-11e8-8e4f-851a6309bed2.png)
![image](https://user-images.githubusercontent.com/7628550/43362945-eaa0b84c-9329-11e8-87d6-cb73af886f5f.png)

**Comment by apcui** [comment]
My app also has this crash.Every version, it will crash thousands times in my app. Do you have any advice?
