### ISSUE TITLE
a piece of advice

### ISSUE THREAD

**Issue by yongliangP** [AFNetworking/AFNetworking#4266]
I want to add a method（delegate） to AFURLSessionManager：

`- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didFinishCollectingMetrics:(NSURLSessionTaskMetrics *)metrics;`

So we can use 'AFNetworking'  to check network easily.

**Comment by SlaunchaMan** [comment]
@yongliangP Pull requests are open; if you want to add that method, feel free to open one!
