### ISSUE TITLE
Does it support caching ?

### ISSUE THREAD

**Issue by DeveloperAsad** [AFNetworking/AFNetworking#4268]
please let me know if i can perform caching

**Comment by zhihuitang** [comment]
it does but seems not works well

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!

**Comment by iDevelopper** [comment]
It is not a general question about how to use the framework but about an available functionality!
