### ISSUE TITLE
AFURLSessionManagerTaskDelegate 

### ISSUE THREAD

**Issue by MrCaiWH** [AFNetworking/AFNetworking#4274]
![image](https://user-images.githubusercontent.com/11872382/44516166-ee00de00-a6f6-11e8-874a-4f2d1ff58f26.png)

AFURLSessionManagerTaskDelegate need to abide by these agreements?

**Comment by SlaunchaMan** [comment]
I’m not 100% sure what you’re asking but yes, `AFURLSessionManagerTaskDelegate` conforms to those protocols.
