### ISSUE TITLE
error when getting get with parameter in json

### ISSUE THREAD

**Issue by frpereda** [AFNetworking/AFNetworking#4275]
Hello, when you did get and sent a parameter in json format of more than five elements an error occurs Error Domain = com.alamofire.error.serialization.response Code = -1011

If the parameter in JSON contains fewer elements it works correctly.

Is there any limitation on the size of the JSON parameter?

This is the JSON that does not send to the server:

[
  {
    "precio" : 6.5,
    "cantidad" : 1,
    "descripcion" : "Chili Hot Dog",
    "id_restaurante" : 8,
    "id_mesa" : 0,
    "id_consumidor" : 2,
    "id_producto" : 23,
    "total" : 6.5,
    "media_racion" : 0
  },
  {
    "precio" : 5.5,
    "cantidad" : 1,
    "descripcion" : "Classic Hot Dog",
    "id_restaurante" : 8,
    "id_mesa" : 0,
    "id_consumidor" : 2,
    "id_producto" : 22,
    "total" : 5.5,
    "media_racion" : 0
  },
  {
    "precio" : 4,
    "cantidad" : 1,
    "descripcion" : "Hot dog infantil",
    "id_restaurante" : 8,
    "id_mesa" : 0,
    "id_consumidor" : 2,
    "id_producto" : 25,
    "total" : 4,
    "media_racion" : 0
  },
  {
    "precio" : 4.5,
    "cantidad" : 1,
    "descripcion" : "Pizzela jamón york y champiñones",
    "id_restaurante" : 8,
    "id_mesa" : 0,
    "id_consumidor" : 2,
    "id_producto" : 48,
    "total" : 4.5,
    "media_racion" : 0
  },
  {
    "precio" : 4.5,
    "cantidad" : 1,
    "descripcion" : "Pizzela jamón york y queso",
    "id_restaurante" : 8,
    "id_mesa" : 0,
    "id_consumidor" : 2,
    "id_producto" : 47,
    "total" : 4.5,
    "media_racion" : 0
  },
  {
    "precio" : 4.5,
    "cantidad" : 1,
    "descripcion" : "Pizzela margarita",
    "id_restaurante" : 8,
    "id_mesa" : 0,
    "id_consumidor" : 2,
    "id_producto" : 50,
    "total" : 4.5,
    "media_racion" : 0
  },
  {
    "precio" : 4.5,
    "cantidad" : 1,
    "descripcion" : "Pizzela pepperoni y queso",
    "id_restaurante" : 8,
    "id_mesa" : 0,
    "id_consumidor" : 2,
    "id_producto" : 49,
    "total" : 4.5,
    "media_racion" : 0
  }
]

And this is the code that I use:

NSURL *baseURL = [NSURL URLWithString:webservice_url];
                NSString *methodName = @"Name of the method";
                NSDictionary *dictParameters = @{@"JSON": jsonString};
                
                AFHTTPSessionManager *manager = [[AFHTTPSessionManager alloc] initWithBaseURL:baseURL];
                manager.requestSerializer = [AFJSONRequestSerializer serializer];
                manager.responseSerializer = [AFHTTPResponseSerializer serializer];
                
                [manager GET:methodName parameters:dictParameters progress:nil success:^(NSURLSessionTask *task, id responseObject){

}failure:^(NSURLSessionTask *operation, NSError *error) {

}

Any suggestions?, thanks!!

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
