### ISSUE TITLE
AFURLSessionManagerTaskDelegate  Crash when dealloc, happens at  3.2.1

### ISSUE THREAD

**Issue by taojigu** [AFNetworking/AFNetworking#4276]
libobjc.A.dylib | objc_object::release() + 16
-- | --
1 libsystem_blocks.dylib | _Block_release + 152
2 libsystem_blocks.dylib | _Block_release + 152
3 libsystem_blocks.dylib | _Block_release + 152
4 Gundam | -[AFURLSessionManagerTaskDelegate .cxx_destruct] (AFURLSessionManager.m:127)
5 libobjc.A.dylib | object_cxxDestructFromClass(objc_object*, objc_class*) + 148
6 libobjc.A.dylib | objc_destructInstance + 68
7 libobjc.A.dylib | object_dispose + 16
8 Gundam | -[AFURLSessionManagerTaskDelegate dealloc] (AFURLSessionManager.m:173)
9 Gundam | __destroy_helper_block_ (AFURLSessionManager.m:246)
10 libsystem_blocks.dylib | _Block_release + 152
11 libdispatch.dylib | __dispatch_client_callout + 16
12 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$armv81 + 528
13 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14 CoreFoundation | ___CFRunLoopRun + 2272
15 CoreFoundation | CFRunLoopRunSpecific + 552
16 GraphicsServices | GSEventRunModal + 100
17 UIKit | UIApplicationMain + 236
18 Gundam | main (main.m:14)
19 libdyld.dylib | _start + 4

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!

**Comment by HatsuneMikuV** [comment]
StackOverflow has raised related questions, but no one answered
@SlaunchaMan
