### ISSUE TITLE
set Accept = application/json, and api redirect back html of web page, Android is back json data

### ISSUE THREAD

**Issue by daishuyi** [AFNetworking/AFNetworking#4277]

**Comment by daishuyi** [comment]
The server must set Accept = application/json, or will redirect api. So I make requestSerializer.setValue("application/json",  forHTTPHeaderField: "Accept"). But the api redirect back html code yet.

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
