### ISSUE TITLE
Control reaches end of non-void block

### ISSUE THREAD

**Issue by Gaozn** [AFNetworking/AFNetworking#4282]
- (NSURLSessionDownloadTask *)downloadTaskWithRequest:(NSURLRequest *)request
                                             progress:(void (^)(NSProgress *downloadProgress)) downloadProgressBlock
                                          destination:(NSURL * (^)(NSURL *targetPath, NSURLResponse *response))destination
                                    completionHandler:(void (^)(NSURLResponse *response, NSURL *filePath, NSError *error))completionHandler

**Comment by siddharthsuneel** [comment]
@Gaozn  can you please provide some information ??

It will help us in better understanding this problem...

**Comment by Gaozn** [comment]
sorry，忘记return个NSURL *
