### ISSUE TITLE
crash when settimeinterval: 

### ISSUE THREAD

**Issue by LeeWongSnail** [AFNetworking/AFNetworking#4283]
CoreFoundation | -[__NSSetM addObject:] + 484
1 CoreFoundation | -[__NSSetM addObject:] + 452
2 UXLive | -[AFHTTPRequestSerializer observeValueForKeyPath:ofObject:change:context:] (AFURLRequestSerialization.m:0)
3 Foundation | _NSKeyValueNotifyObserver + 304
4 Foundation | _NSKeyValueDidChange + 380
5 Foundation | _NSKeyValueDidChangeWithPerThreadPendingNotifications + 140
| -[AFHTTPRequestSerializer setTimeoutInterval:] (AFURLRequestSerialization.m:299)
| -[ULHttpRequest setCommonHeaderManager:timeOut:] (ULHttpRequest.m:207)
| -[ULHttpRequest managerWithTimeOut:] (ULHttpRequest.m:179)
 | -[ULHttpGetRequest startAsyncRequest] (ULHttpRequest.m:0)

**Comment by redcapua** [comment]
Hi!

@LeeWongSnail 

Could you please share rows fo code where you got this issue?

Just for reproducing purposes.

Thank you in advance!

**Comment by frolaqi** [comment]
HI !
I have the same problem , Do you have  salved this problem?
Thank you in advance

**Comment by SSHuiqin** [comment]
@giovazjim Would you mind to share how you delay it? If you can share a piece of code ^^ Thanks so much.

**Comment by motoband** [comment]
> Hi!
> 
> @LeeWongSnail
> 
> Could you please share rows fo code where you got this issue?
> 
> Just for reproducing purposes.
> 
> Thank you in advance!

 you can got this issue
At different Thread at same time to  call Foundation:

AFAppDotNetAPIClient *manager = [AFAppDotNetAPIClient sharedClient];
    manager.requestSerializer.timeoutInterval = timeout;

**Comment by mrshyi** [comment]
same

> > Hi!
> > @LeeWongSnail
> > Could you please share rows fo code where you got this issue?
> > Just for reproducing purposes.
> > Thank you in advance!
> 
> you can got this issue
> At different Thread at same time to call Foundation:
> 
> AFAppDotNetAPIClient *manager = [AFAppDotNetAPIClient sharedClient];
> manager.requestSerializer.timeoutInterval = timeout;

same
