### ISSUE TITLE
AFNetworking 2.0 - Network connection lost (-1005) when app goes to background

### ISSUE THREAD

**Issue by qaavi** [AFNetworking/AFNetworking#4287]
Hi, I'm using AFNetworking 2.0, and I've enabled "background fetch" on my app too.

The problem I'm facing is when the app is open, user makes a POST request. Now if he/she puts the app in background, the connection is lost immediately (though I can confirm from Wireshark that HTTP 200 OK is received).  Why is AFNetworking 2.0 disconnecting when app is in background, background fetch is also ON ?

**Comment by philgrida** [comment]
qaavi, have you managed to fix the issues you're having since I'm having similar issues ?

**Comment by qaavi** [comment]
@philgrida not yet. 
@sco Any suggestion on above please.

**Comment by sco** [comment]
@qaavi sorry, I'm no longer involved in this project.

**Comment by teffi** [comment]
@qaavi  - I think this is related to the socket reclaim issue that started in iOS12. https://github.com/AFNetworking/AFNetworking/issues/4279
