### ISSUE TITLE
Installation through Carthage fails with Xcode 10

### ISSUE THREAD

**Issue by ivan-konov** [AFNetworking/AFNetworking#4288]
I am using Xcode 10.0(was reproducible with betas) and Carthage version 0.30.1

This is the error message I get from Carthage:

*** Building scheme "AFNetworking iOS" in AFNetworking.xcworkspace
*** Building scheme "AFNetworking watchOS" in AFNetworking.xcworkspace
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -workspace /Users/username/Documents/work/application/Carthage/Checkouts/AFNetworking/AFNetworking.xcworkspace -scheme AFNetworking\ watchOS -configuration Release -derivedDataPath /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/AFNetworking/3.2.1 -sdk watchsimulator -destination platform=watchOS\ Simulator,id=B35EB6D9-8741-4DE3-9C02-D7D3D60AE244 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/user/Documents/work/application/Carthage/Checkouts/AFNetworking)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/l6/4zrqf_m91mzcx175p7t8klq40000gn/T/carthage-xcodebuild.5z9bHS.log

Thanks!

**Comment by rdewein-letsdev** [comment]
I do face the same error message.

**Comment by SlaunchaMan** [comment]
@ivan-konov Can you copy that log file here?

**Comment by ivan-konov** [comment]
It turned out to be a bug in Carthage when it builds watchOS schemes with Xcode 10. They should be releasing the fix soon. If somebody really needs it now they can just install Carthage using the master branch.

**Comment by SlaunchaMan** [comment]
Great, thanks for following up!
