### ISSUE TITLE
[iOS 10+] Unknown error when uploading a large request

### ISSUE THREAD

**Issue by dyegos** [AFNetworking/AFNetworking#4292]
I'm trying to upload a POST with a large JSON and it always returns the error bellow:
``` objc 
Error Domain=NSURLErrorDomain 
Code=-1 "unknown error" 
UserInfo={NSUnderlyingError=0x608000841c20 
{Error Domain=kCFErrorDomainCFNetwork
Code=-998 "(null)" 
UserInfo={NSErrorPeerAddressKey=<CFData 0x604000485f00 [0x10d238c80]>
{length = 16, capacity = 16, bytes = 0x100201bb23c96f310000000000000000},
_kCFStreamErrorCodeKey=0, _kCFStreamErrorDomainKey=2}}, 
NSErrorFailingURLStringKey="URL", 
NSErrorFailingURLKey="URL", 
_kCFStreamErrorDomainKey=2, _kCFStreamErrorCodeKey=0, NSLocalizedDescription=unknown error}
```
I'm using Xcode 9.4.1 and 10, hight sierra 10.13.16, AFNetworking 3.2.1. Both simulator and device are returning the same error in Wifi or LTE. I started having this problem after dropping target iOS 9. I'm using target to iOS 10.

Does anyone knows what is the problem?

**Comment by whydna** [comment]
@dyegos what was the issue

**Comment by dyegos** [comment]
@whydna I really don't remember. it was a year ago :/
