### ISSUE TITLE
Bug only in iOS12 and iPhoneX

### ISSUE THREAD

**Issue by AshCheng** [AFNetworking/AFNetworking#4299]
there is a bug: to see the networkReachabilityStatus, use  the networkReachabilityStatus of AFNetworkReachabilityManager, You can check it, actually I use 4G, it return AFNetworkReachabilityStatusUnknown

**Comment by whde** [comment]
解决了么？今天貌似也遇到这个问题，但是过一会又好了

**Comment by zyx449678686** [comment]
试一试打开Access WiFi Information . 在 capabilities 里面
