### ISSUE TITLE
Crash: com.apple.network.connections

### ISSUE THREAD

**Issue by DineshThakur** [AFNetworking/AFNetworking#4301]
Hi,

App is crashing after using for some time. Please let me know what could be the reason?

Below is the crash logs details:-

Thread 26 name:  Dispatch queue: com.apple.network.connections
Thread 26 Crashed:
0   libsystem_kernel.dylib        	0x00000001833992e0 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x000000018353e6a8 pthread_kill$VARIANT$armv81 + 360
2   libsystem_c.dylib             	0x0000000183307d0c abort + 140
3   CFNetwork                     	0x0000000183ece0b8 SmartBlockWithArgs<std::__1::shared_ptr<NetworkProxy>, bool, CFStreamError>::SmartBlockWithArgs(void + 229560 (std::__1::shared_ptr<NetworkProxy>, bool, CFStreamError) block_pointer) + 0
4   CFNetwork                     	0x0000000183ec98b0 auto TunnelProxy<HTTPEngine>::hold_unmanaged_in_shared<TunnelProxy<HTTPEngine>, TunnelProxy<HTTPEngine> >+ 211120 (TunnelProxy<HTTPEngine>*) + 40
5   CFNetwork                     	0x0000000183eca274 TunnelProxy<HTTPEngine>::bodyReadComplete+ 213620 () + 136
6   CFNetwork                     	0x00000001840c0614 HTTPEngine::_readBodyFinish+ 2270740 (dispatch_data_s*, CFStreamError, bool) + 168
7   CFNetwork                     	0x00000001840c0df0 HTTPEngine::_deliverBodyBytes+ 2272752 (dispatch_data_s*, CFStreamError, bool) + 228
8   CFNetwork                     	0x00000001840c17dc invocation function for block in HTTPEngine::_getBodyIntelligently(void + 2275292 (dispatch_data_s*, CFStreamError, bool) block_pointer) + 168
9   CFNetwork                     	0x00000001840c0a70 HTTPEngine::_getBodyIntelligently(void + 2271856 (dispatch_data_s*, CFStreamError, bool) block_pointer) + 804
10  CFNetwork                     	0x00000001840be52c HTTPEngine::_readBodyStartNextRead+ 2262316 () + 80
11  CFNetwork                     	0x00000001840bdeb0 HTTPEngine::_readHeadersFinish+ 2260656 (CFStreamError) + 220
12  CFNetwork                     	0x00000001840bfd64 HTTPEngine::_readHeadersDoParse+ 2268516 (CFStreamError) + 1728
13  CFNetwork                     	0x0000000184037e9c TCPIOConnection::readCompleted(unsigned long, unsigned long, dispatch_data_s*, int, void + 1711772 (dispatch_data_s*, CFStreamError) block_pointer) + 324
14  CFNetwork                     	0x00000001840d7af0 ConnectionProtocolReadInner(nw_protocol*, unsigned int, unsigned int, bool, long long, void (dispatch_data_s*, CFStreamError) block_pointer, void + 2366192 (nw_frame_array_s*, CFStreamError) block_pointer) + 988
15  CFNetwork                     	0x00000001840d7664 ConnectionProtocolServiceReads+ 2365028 (nw_protocol*) + 380
16  CFNetwork                     	0x00000001840d8658 ConnectionProtocolInputAvailable+ 2369112 (nw_protocol*, nw_protocol*) + 64
17  libusrtcp.dylib               	0x00000001849b1ff8 nw_protocol_tcp_wake_read + 460
18  libusrtcp.dylib               	0x00000001849dab48 tcp_input_flush + 84
19  libsystem_network.dylib       	0x000000018341947c nw_channel_add_input_frames + 4328
20  libsystem_network.dylib       	0x0000000183418330 nw_channel_update_input_source + 136
21  libsystem_network.dylib       	0x0000000183417b28 __nw_channel_create_block_invoke + 52
22  libdispatch.dylib             	0x0000000183204a60 _dispatch_client_callout + 16
23  libdispatch.dylib             	0x00000001832417c8 _dispatch_continuation_pop$VARIANT$armv81 + 416
24  libdispatch.dylib             	0x000000018324ac40 _dispatch_source_invoke$VARIANT$armv81 + 1248
25  libdispatch.dylib             	0x0000000183243094 _dispatch_queue_serial_drain$VARIANT$armv81 + 248
26  libdispatch.dylib             	0x0000000183243af8 _dispatch_queue_invoke$VARIANT$armv81 + 328
27  libdispatch.dylib             	0x000000018324449c _dispatch_root_queue_drain_deferred_wlh$VARIANT$armv81 + 332
28  libdispatch.dylib             	0x000000018324c46c _dispatch_workloop_worker_thread$VARIANT$armv81 + 612
29  libsystem_pthread.dylib       	0x0000000183537e70 _pthread_wqthread + 860
30  libsystem_pthread.dylib       	0x0000000183537b08 start_wqthread + 4

**Comment by apcui** [comment]
it's caused by CFNetwork。
