### ISSUE TITLE
[NSURL(NSURL) absoluteString] SIGSEGV crash

### ISSUE THREAD

**Issue by kobe1941** [AFNetworking/AFNetworking#4305]
use AFNetworking 3.0

crash stack 
![image](https://user-images.githubusercontent.com/7099017/47542825-c2c28700-d911-11e8-8c74-b9d0c3669294.png)

![image](https://user-images.githubusercontent.com/7099017/47542838-d53cc080-d911-11e8-85da-bcd12d07f79e.png)

**Comment by BaihaoTian** [comment]
same as me

**Comment by redcapua** [comment]
Hi!

@kobe1941 @BaihaoTian 

Could you please share code samples which can raise issue you mentioned?

Thank you in advance!

**Comment by kobe1941** [comment]
just a simple method call in sub thread .
like this
![image](https://user-images.githubusercontent.com/7099017/48176531-6a48ac00-e34b-11e8-8a48-02b5010e0107.png)

sometimes like this:
![image](https://user-images.githubusercontent.com/7099017/48176542-7c2a4f00-e34b-11e8-9752-37280dba94eb.png)

also like this:

![image](https://user-images.githubusercontent.com/7099017/48176560-919f7900-e34b-11e8-957d-9f5bbdba4f32.png)

the callStack above may difference .

**Comment by kobe1941** [comment]
something some : all the crash is not in main thread

**Comment by redcapua** [comment]
@kobe1941 

Could you please share code of application not stack?

I have to see how procedure called

**Comment by kobe1941** [comment]
@redcapua 

`
- (void)requestAppConfig
{
    [self performSelectorInBackground:@selector(getAppConfigDataFromServer) withObject:nil];
}

- (void)getAppConfigDataFromServer
{
    [self getServerConfig];
    struct utsname systemInfo;
    uname(&systemInfo);
    NSMutableDictionary* params = [NSMutableDictionary dictionary];
    params[@"uid"] = @([AccountManager sharedInstance].user_id);
    params[@"app"] = @"3";
    params[@"platform"] = @"ios";
    params[@"version"] = [[VersionManager sharedInstance] currentVersionName];
    params[@"vn"] = [[VersionManager sharedInstance] currentVersionName];
    params[@"vc"] = @([[VersionManager sharedInstance] currentVersionCode]);
    params[@"osv"] = @([[[UIDevice currentDevice] systemVersion] floatValue]);
    params[@"mo"] = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
    params[@"os"] = @"iOS";
    
    [HTTPClientInstance request:@"config/client_config" method:HTTP_METHOD_GET parameters:params completionHandler:^(id responseObject, id data, NSString *errorMsg) {
        if (data && [data isKindOfClass:[NSDictionary class]]) {
            _configModel = [SSZAppConfigModel mj_objectWithKeyValues:data];
            [self saveAppConfig];
            [self didUpdateConfig];
            [self checkTime];
            [[NSNotificationCenter defaultCenter] postNotificationName:SSZAppConfigModelChange object:nil];
        }
    }];
}
`

`
#define HTTPClientInstance  [HTTPClient sharedInstance]
`
![image](https://user-images.githubusercontent.com/7099017/48252767-7e220a00-e440-11e8-80e1-90a2c84a9bc9.png)

![image](https://user-images.githubusercontent.com/7099017/48252863-c93c1d00-e440-11e8-8c59-267ea2537bfc.png)

**Comment by redcapua** [comment]
@kobe1941 

Sorry I cannot reproduce it :(

**Comment by kobe1941** [comment]
@reacuna I cannot reproduce it too， the crash log is collect from our user's device。

**Comment by redcapua** [comment]
@BaihaoTian 

Could you please share source code lines and steps to reproduce issue?

It would be more useful than asm info from debugger.

**Comment by kobe1941** [comment]
maybe this is Xcode's bug，it not appear when I am use Xcoce 9.4.1 package my app release version.
