### ISSUE TITLE
request time out only in iOS 12..

### ISSUE THREAD

**Issue by syik** [AFNetworking/AFNetworking#4306]
After iOS12 was released, we received many user feedback about requests failed. Through the user logs, we found that the failure was due to a request timeout like this:

> Error: Error Domain=NSURLErrorDomain Code=-1001 "请求超时。" UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x280711bc0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <40EA4924-3926-4A90-832E-5BE8C1426F40>.<777>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
>     "LocalDataTask <40EA4924-3926-4A90-832E-5BE8C1426F40>.<777>"
> ), NSLocalizedDescription=请求超时。, NSErrorFailingURLStringKey=xxxxx, NSErrorFailingURLKey=xxxxx, _kCFStreamErrorDomainKey=4}

This error is common, but oddly enough, most requests continue to fail unless you restart the APP to recover!

We try to reproduce and observe the following rules:

- In the continuous switching of the foreground background, switching the network environment has a very low probability of this phenomenon.
- Breakpoint debugging code, go to the resume method of NSURLSessionTask, the flow is normal, after 15 seconds (timeout is set to 15 seconds) direct callback request timeout.
- The actual request does not seem to be initiated by the capture software (Charles) request.
- Only fixed partial requests have this problem, but they have no obvious exceptions and commonalities.
- CFNETWORK_DIAGNOSTICS also can't see the exception.
- The time data collected in NSURLSessionTaskMetrics has only the start and end time, and the remote resolution IP does not exist.

We also made the following attempts:

- We tried to call the NSURLSession reset related method, which is invalid.
- We used the latest version of AFNetworking, which is invalid.
- We replaced NSURLSessionConfiguration, which is invalid.
- We suspect that the problem is related to the Keepalive mechanism, but some of the request for the problem is not resused.
- We suspect that it is related to the HTTP/2 protocol. Switching back to HTTP/1.1 is invalid.
- The thread we initiated is all fixed in the main thread, invalid.
- We suspect that it is related to HTTPS, but the actual request does not seem to go to the handshake phase.
- When this happens, re-creating the NSURLSession instance can be restored.

Similar in the Apple Developer Forum: https://forums.developer.apple.com/message/337061#337061

Our APM platform monitors the iOS12 user timeout rate much higher than other systems. If you have any clues, please reply to us, thank you!

**Comment by cjleay001** [comment]
楼主是使用AFNetworking网络请求时收集到大量请求超时的错误吗？

**Comment by syik** [comment]
> 楼主是使用AFNetworking网络请求时收集到大量请求超时的错误吗？

是的

**Comment by 0xmtn** [comment]
+1

**Comment by sungggat** [comment]
+1

**Comment by GuoJinRui** [comment]
解决了吗？

**Comment by syik** [comment]
> 解决了吗？

目前还没有, 只临时处理了, 你们遇到了相同的问题吗?

**Comment by AOLLIU** [comment]
> > 解决了吗？
> 
> 目前还没有, 只临时处理了, 你们遇到了相同的问题吗?

请问是如果临时解决的谢谢了,我遇到的问题是,如果发生了这样的错误请求就一直不会成功,必须重新杀死app才能解决

**Comment by AOLLIU** [comment]
@syik 请问是如果临时解决的谢谢了,我遇到的问题是,如果发生了这样的错误请求就一直不会成功,必须重新杀死app才能解决

**Comment by syik** [comment]
> @syik 请问是如果临时解决的谢谢了,我遇到的问题是,如果发生了这样的错误请求就一直不会成功,必须重新杀死app才能解决

在超时时替换 NSURLSession(或AF..Manager) 实例, 限制频率与次数.

**Comment by hunterxie** [comment]
> > @syik 请问是如果临时解决的谢谢了,我遇到的问题是,如果发生了这样的错误请求就一直不会成功,必须重新杀死app才能解决
> 
> 在超时时替换 NSURLSession(或AF..Manager) 实例, 限制频率与次数. @hunterxie

我这个AFNetSessionManager是单例  按你的意思是如果出现超时，就重新初始化个SessionManager替换之前的？限制频率和次数怎么理解啊，timeout超时时间设大一点?

**Comment by syik** [comment]
> > > @syik 请问是如果临时解决的谢谢了,我遇到的问题是,如果发生了这样的错误请求就一直不会成功,必须重新杀死app才能解决
> > 
> > 
> > 在超时时替换 NSURLSession(或AF..Manager) 实例, 限制频率与次数. @hunterxie
> 
> 我这个AFNetSessionManager是单例 按你的意思是如果出现超时，就重新初始化个SessionManager替换之前的？限制频率和次数怎么理解啊，timeout超时时间设大一点?

比如1分钟只允许替换一次, 最多只允许替换5次, 实例创建过多会有内存泄漏.

**Comment by AOLLIU** [comment]
@syik 请问你请求失败的这个接口使用的http/1.1吗?我这里使用http2.0的全部可以成功,http/1.1的才偶现请求超时的这个问题,至于你说的暂时解决的方案感觉有点儿不太好,我们正在看时候可以通过更换http协议来解决这个问题

**Comment by syik** [comment]
> @syik 请问你请求失败的这个接口使用的http/1.1吗?我这里使用http2.0的全部可以成功,http/1.1的才偶现请求超时的这个问题,至于你说的暂时解决的方案感觉有点儿不太好,我们正在看时候可以通过更换http协议来解决这个问题

我通过检测 2.0的超时率比1.1的概率更高, 另外你看到的解决方案出处是?

**Comment by karosLi** [comment]
这几天我也遇到了，用户报的是 iPhoneXS Max iOS 12.2 上 我们的app 访问不了网络。但是其他app是好的。另外针对我们app的网络开关也是打开的。

**Comment by Wbqqqq** [comment]
我这边也是，每次一开机，会报大量的超时，但很奇怪的事，之后又会重连，导致每次进首页，都会卡几秒才有数据..............

**Comment by sanalraju** [comment]
is this issue solved
