### ISSUE TITLE
__destroy_helper_block_ SIGSEGV crash in (AFURLSessionManager.m:245)

### ISSUE THREAD

**Issue by kobe1941** [AFNetworking/AFNetworking#4308]
user AFNetworking 3.0

and the crash stack is 
![image](https://user-images.githubusercontent.com/7099017/47641649-9329ae00-dba1-11e8-8f59-8b2e384dd97a.png)

the code is 
![image](https://user-images.githubusercontent.com/7099017/47641752-d97f0d00-dba1-11e8-8eae-531ae58bdcd7.png)

I guess , if one people received AFNetworkingTaskDidCompleteNotification notification in main thread, and also call some method in main queue by syn pattern, it will carshed ?
just a guess

**Comment by kobe1941** [comment]
only crashed in iOS9.1 - iOS9.2.1 system.
it seems Apple's bug ?

**Comment by xunan623** [comment]
I also ran into this problem does somebody run into solve this problem excuse me? IOS11.2.1 iPhone X

**Comment by one-tea** [comment]
I also encountered the same situation, which is not currently resolved, but there is an article that may be helpful 
 https://stackoverflow.com/questions/23573114/objective-c-crash-on-destroy-helper-block
