### ISSUE TITLE
Error Domain=NSPOSIXErrorDomain Code=28 "No space left on device" UserInfo={

### ISSUE THREAD

**Issue by jinweizhao** [AFNetworking/AFNetworking#4313]
i have 1100 files to download ,all files totally 17M ,but when i download the 511th,it complete with error (Error Domain=NSPOSIXErrorDomain Code=28 "No space left on device" UserInfo={ ) ,i checked device space is enough . so why?   thank you  please

**Comment by LuKane** [comment]
the same question!

**Comment by CyberMew** [comment]
Have you figured out the solution?

**Comment by albertjson** [comment]
same question! 
 I use shared urlsessionManager to solved，and works！
