### ISSUE TITLE
Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: bad request (400)" UserInfo={NSLocalizedDescription=Request failed: bad request (400)

### ISSUE THREAD

**Issue by ECUnion-HD** [AFNetworking/AFNetworking#4314]
**### Excuse me what reason this problem：**
Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: bad request (400)" UserInfo={NSLocalizedDescription=Request failed: bad request (400), NSErrorFailingURLKey=http://192.168.0.53/bdsaas/ajax/order/addOrder.do?token=9FA0A12D4EAF4F92A3AB2B3B1B293F8C&COMPANYID=97, com.alamofire.serialization.response.error.data=<3c68746d 6c3e3c68 6561643e 3c746974 6c653e41 70616368 6520546f 6d636174 2f372e30 2e353620 2d204572 726f7220 7265706f 72743c2f 7469746c 653e3c73 74796c65 3e3c212d 2d483120 7b666f6e 742d6661 6d696c79 3a546168 6f6d612c 41726961 6c2c7361 6e732d73 65726966 3b636f6c 6f723a77 68697465 3b626163 6b67726f 756e642d 636f6c6f 723a2335 32354437 363b666f 6e742d73 697a653a 32327078 3b7d2048 32207b66 6f6e742d 66616d69 6c793a54 61686f6d 612c4172 69616c2c 73616e73 2d736572 69663b63 6f6c6f72 3a776869 74653b62 61636b67 726f756e 642d636f 6c6f723a 23353235 4437363b 666f6e74 2d73697a 653a3136 70783b7d 20483320 7b666f6e 742d6661 6d696c79 3a546168 6f6d612c 41726961 6c2c7361 6e732d73 65726966 3b636f6c 6f723a77 68697465 3b626163 6b67726f 756e642d 636f6c6f 723a2335 32354437 363b666f 6e742d73 697a653a 31347078 3b7d2042 4f445920 7b666f6e 742d6661 6d696c79 3a546168 6f6d612c 41726961 6c2c7361 6e732d73 65726966 3b636f6c 6f723a62 6c61636b 3b626163 6b67726f 756e642d 636f6c6f 723a7768 6974653b 7d204220 7b666f6e 742d6661 6d696c79 3a546168 6f6d612c 41726961 6c2c7361 6e732d73 65726966 3b636f6c 6f723a77 68697465 3b626163 6b67726f 756e642d 636f6c6f 723a2335 32354437 363b7d20 50207b66 6f6e742d 66616d69 6c793a54 61686f6d 612c4172 69616c2c 73616e73 2d736572 69663b62 61636b67 726f756e 643a7768 6974653b 636f6c6f 723a626c 61636b3b 666f6e74 2d73697a 653a3132 70783b7d 41207b63 6f6c6f72 203a2062 6c61636b 3b7d412e 6e616d65 207b636f 6c6f7220 3a20626c 61636b3b 7d485220 7b636f6c 6f72203a 20233532 35443736 3b7d2d2d 3e3c2f73 74796c65 3e203c2f 68656164 3e3c626f 64793e3c 68313e48 54545020 53746174 75732034 3030202d 20526571 75697265 6420496e 74656765 72207061 72616d65 74657220 27636166 49642720 6973206e 6f742070 72657365 6e743c2f 68313e3c 48522073 697a653d 22312220 6e6f7368 6164653d 226e6f73 68616465 223e3c70 3e3c623e 74797065 3c2f623e 20537461 74757320 7265706f 72743c2f 703e3c70 3e3c623e 6d657373 6167653c 2f623e20 3c753e52 65717569 72656420 496e7465 67657220 70617261 6d657465 72202763 61664964 27206973 206e6f74 20707265 73656e74 3c2f753e 3c2f703e 3c703e3c 623e6465 73637269 7074696f 6e3c2f62 3e203c75 3e546865 20726571 75657374 2073656e 74206279 20746865 20636c69 656e7420 77617320 73796e74 61637469 63616c6c 7920696e 636f7272 6563742e 3c2f753e 3c2f703e 3c485220 73697a65 3d223122 206e6f73 68616465 3d226e6f 73686164 65223e3c 68333e41 70616368 6520546f 6d636174 2f372e30 2e35363c 2f68333e 3c2f626f 64793e3c 2f68746d 6c3e>, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x600000a522a0> { URL: http://192.168.0.53/bdsaas/ajax/order/addOrder.do?token=9FA0A12D4EAF4F92A3AB2B3B1B293F8C&COMPANYID=97 } { Status Code: 400, Headers {
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    Connection =     (
        "keep-alive"
    );
    "Content-Language" =     (
        en
    );
    "Content-Length" =     (
        1066
    );
    "Content-Type" =     (
        "text/html;charset=utf-8"
    );
    Date =     (
        "Fri, 09 Nov 2018 09:19:07 GMT"
    );
    Server =     (
        nginx
    );
    companyid =     (
        97
    );
} }}

**Comment by dengsss** [comment]
我也遇到这个问题了。用系统自带的请求可以返回，用AF发请求就报这个错。请问你解决了吗

**Comment by ECUnion-HD** [comment]
> 我也遇到这个问题了。用系统自带的请求可以返回，用AF发请求就报这个错。请问你解决了吗

我这边仔细检查之后是数据格式错误，和后台要求的数据格式不一致，解析的时候报错，不是三方的问题，不知道你这个是不是这样的问题，你仔细检查一下你上传的参数和后台的格式要求是不是一致

**Comment by dengsss** [comment]
嗯嗯。谢谢！我这边设置了请求参数序列化为 json 格式就好了，默认为 http 格式
