### ISSUE TITLE
help, i met a crash, maybe network error.

### ISSUE THREAD

**Issue by tabor01** [AFNetworking/AFNetworking#4331]
* thread #119, queue = 'com.apple.network.connections', stop reason = EXC_BAD_ACCESS (code=1, address=0xaa1303e0aa000401)
  * frame #0: 0x0000000106976e08 libBacktraceRecording.dylib`__gcd_queue_item_enqueue_hook_block_invoke
    frame #1: 0x000000010697638c libBacktraceRecording.dylib`gcd_queue_item_enqueue_hook + 224
    frame #2: 0x00000001084c1e48 libdispatch.dylib`_dispatch_introspection_queue_item_enqueue_hook + 40
    frame #3: 0x00000001084a1304 libdispatch.dylib`_dispatch_queue_push + 196
    frame #4: 0x000000019b9c56a0 libnetwork.dylib`__nw_connection_write_multiple_block_invoke.214 + 112
    frame #5: 0x000000018ddfa808 libsystem_network.dylib`nw_write_request_complete + 184
    frame #6: 0x000000018ddfa748 libsystem_network.dylib`nw_write_request_consume_bytes_at_index + 356
    frame #7: 0x000000019b98e01c libnetwork.dylib`nw_endpoint_flow_service_writes + 1448
    frame #8: 0x000000019b990b90 libnetwork.dylib`nw_endpoint_handler_add_write_request + 140
    frame #9: 0x000000019b9c576c libnetwork.dylib`__nw_connection_write_multiple_block_invoke.234 + 44
    frame #10: 0x0000000108495a50 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #11: 0x0000000108495a10 libdispatch.dylib`_dispatch_client_callout + 16
    frame #12: 0x00000001084a32e8 libdispatch.dylib`_dispatch_queue_serial_drain + 1140
    frame #13: 0x0000000108499634 libdispatch.dylib`_dispatch_queue_invoke + 852
    frame #14: 0x00000001084a5630 libdispatch.dylib`_dispatch_root_queue_drain + 552
    frame #15: 0x00000001084a539c libdispatch.dylib`_dispatch_worker_thread3 + 140
    frame #16: 0x000000018de4f1d0 libsystem_pthread.dylib`_pthread_wqthread + 1096
    frame #17: 0x000000018de4ed7c libsystem_pthread.dylib`start_wqthread + 4

**Comment by teffi** [comment]
more code and background on what you're trying to do might help us. EXC_BAD_ACCESS only indicates your trying to locate a deallocated address.
