### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by parasappafluke** [AFNetworking/AFNetworking#4338]
Hi,
From our security analysis tool we found that there is a security threat in below method since AFNetworking  is generating random numbers to add a boundary to multiform data using arc4random.
static NSString * AFCreateMultipartFormBoundary() {
    return [NSString stringWithFormat:@"Boundary+%08X%08X", arc4random(), arc4random()];
}
Will it possible to use secure random generation instead of arc4rand.

Thanks

**Comment by parasappafluke** [comment]
Any update on this issue.

**Comment by jshier** [comment]
`arc4random()` *is* a secure generator, but even if it wasn't, the boundary identifier is not a sensitive value, it's just used to separate the parts of a form.
