### ISSUE TITLE
Crash at AFURLRequestSerialization.m:223

### ISSUE THREAD

**Issue by remember17** [AFNetworking/AFNetworking#4340]
Crash recently!

+ 0
CoreFoundation | _CFLogvEx3 + 256
Foundation | __NSLogv + 128
Foundation | NSLog + 32
offerwall.dylib | _ZL50_logos_method$IDFAIDFV_Hook$UIDevice$systemVersionP8UIDeviceP13objc_selector + 72
-[AFHTTPRequestSerializer init] (AFURLRequestSerialization.m:223)
+[AFHTTPRequestSerializer serializer] (AFURLRequestSerialization.m:197)

**Comment by July-7** [comment]
I also encounter this similar problem. How do you solve this problem? Can you tell me the solution
