### ISSUE TITLE
crash at -[AFHTTPRequestSerializer setValue:forHTTPHeaderField:]_block_invoke (AFURLRequestSerialization.m:316)

### ISSUE THREAD

**Issue by KeymonWong** [AFNetworking/AFNetworking#4341]
Hello everyone!
Like the above Title
My AFNetworking`s version is 3.2.1, what happend? Has anyone encountered it?

**Comment by baishikele** [comment]
I have the same problem.  someone says that using "lock" can resolve this problem.

**Comment by baishikele** [comment]
擦，老乡啊。。。

**Comment by milantechholding** [comment]
> I have the same problem. someone says that using "lock" can resolve this problem.

@baishikele  could you please explain in detail?

**Comment by milantechholding** [comment]
> Hello everyone!
> Like the above Title
> My AFNetworking`s version is 3.2.1, what happend? Has anyone encountered it?

Hi @KeymonWong  can you please explain in brief how you resolve this?
