### ISSUE TITLE
AFNetworking DELETE method not working

### ISSUE THREAD

**Issue by heqikang** [AFNetworking/AFNetworking#4345]
manger.requestSerializer.HTTPMethodsEncodingParametersInURI = [NSSet setWithObjects:@"GET", @"HEAD", nil];
            [manger DELETE:URLString parameters:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
                if (success) {
                    success(responseObject);
                }
            } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
                if (failure) {
                    failure(error);
                }
            }];

后台返回405 method not allowed

**Comment by SlaunchaMan** [comment]
Getting a “method not allowed” response leads me to believe that this is actually an issue with your server. Try using Charles Proxy or another debugging tool to verify that the app is sending the correct request.
