### ISSUE TITLE
How can I get resumeData which at AFNetworking 3.0

### ISSUE THREAD

**Issue by m17603048828** [AFNetworking/AFNetworking#4346]
How can I get resumeData When use this mthod to download video?  I'm doing a breakpoint continuation
`- (NSURLSessionDownloadTask *)downloadTaskWithRequest:(NSURLRequest *)request
                                             progress:(void (^)(NSProgress *downloadProgress)) downloadProgressBlock
                                          destination:(NSURL * (^)(NSURL *targetPath, NSURLResponse *response))destination
                                    completionHandler:(void (^)(NSURLResponse *response, NSURL *filePath, NSError *error))completionHandler`

destination keep the  path But when task finished !!!!
I need data when downloading

Hope to get your guidance！！！

**Comment by flyling** [comment]
How can I get resumeData?
