### ISSUE TITLE
Failed for Archive.

### ISSUE THREAD

**Issue by bala-ski** [AFNetworking/AFNetworking#4348]
**

> /AFNetworking.framework/AFNetworking was built without full bitcode.

**
Xcode version 10.1 and using swift. 

While running the app in the device its perfectly works but while archiving I am getting this error.

I using the AFNetworking via PaymentSDK framework. 

I am adding the PaymentSDK for another swift framework.

**Comment by mukeshkvns** [comment]
Same issue

> AFNetworking' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.

**Comment by mukeshkvns** [comment]
Workaround : adding 'BITCODE_GENERATION_MODE' as key and value as 'bitcode' in user define build setting fixed the issue.
