### ISSUE TITLE
URLSession:task:didReceiveChallenge: not work

### ISSUE THREAD

**Issue by linyu92** [AFNetworking/AFNetworking#4353]
In AFURLSessionManager.m, you has implement 
> - (void)URLSession:(NSURLSession *)session
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler

According to the document:

> the NSURLSession object calls the session delegate’s URLSession:didReceiveChallenge:completionHandler: method. If your app does not provide a session delegate method, the NSURLSession object calls the task delegate’s URLSession:task:didReceiveChallenge:completionHandler: method to handle the challenge.

But what i want is the callback with NSURLSessionTask , just like this:
> - (void)URLSession:(NSURLSession *)session
              task:(NSURLSessionTask *)task
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
 completionHandler
is not called anymore~

How Can I get rid of the callback without NSURLSessionTask, and so it can turn to the one with it? 
Thanks!

**Comment by SlaunchaMan** [comment]
Hi there! For general questions about how to use AFNetworking, please ask [on StackOverflow](http://stackoverflow.com/questions/tagged/afnetworking). Thanks!
