### ISSUE TITLE
Null Dereference

### ISSUE THREAD

**Issue by shyamalsphinx** [AFNetworking/AFNetworking#4356]
dataTask = [self.sessionManager
                dataTaskWithRequest:request
                uploadProgress:nil
                downloadProgress:nil
                completionHandler:^(NSURLResponse * _Nonnull response, id  _Nonnull
responseObject, NSError * _Nullable error) {}

uploadProgress:nil and downloadProgress:nil - sending nill gives null Null Dereference. Can any one help on this to solve fortify issue

**Comment by SlaunchaMan** [comment]
What version of AFNetworking are you using?
