### ISSUE TITLE
Crash at AFURLSessionManager.m:205

### ISSUE THREAD

**Issue by haiwei-Lee** [AFNetworking/AFNetworking#4358]
In a recent project in the following the collapse of the information ：

0 libobjc.A.dylib | objc_object::release() + 16
-- | --
1 **** | -[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:] (AFURLSessionManager.m:205)
2 **** | -[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:] (AFURLSessionManager.m:205)
3 **** | -[AFURLSessionManager URLSession:task:didCompleteWithError:] (AFURLSessionManager.m:1071)
4 CFNetwork | ___51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.241 + 276
5 Foundation | ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
6 Foundation | -[NSBlockOperation main] + 72
7 Foundation | -[__NSOperationInternal _start:] + 740
8 Foundation | ___NSOQSchedule_f + 272
9 libdispatch.dylib | __dispatch_call_block_and_release + 24
10 libdispatch.dylib | __dispatch_client_callout + 16
11 libdispatch.dylib | __dispatch_continuation_pop$VARIANT$armv81 + 404
12 libdispatch.dylib | __dispatch_async_redirect_invoke + 592
13 libdispatch.dylib | __dispatch_root_queue_drain + 344
14 libdispatch.dylib | __dispatch_worker_thread2 + 116
15 libsystem_pthread.dylib | _pthread_wqthread + 472

**Comment by SlaunchaMan** [comment]
Thanks for the report! Can you please reply with your:

- Xcode version
- iOS/macOS/tvOS/watchOS Deployment Target

If possible, can you include any relevant portions from the code where you’re calling AFNetworking?

**Comment by haiwei-Lee** [comment]
@SlaunchaMan Thank you for your attention to my question . My Xcode version is 10.1 .  Deployment tatget is iOS9.0 . 
+(NSURLSessionDataTask *) PostRequestUrl:(NSString *)url
                               SetParams:(NSDictionary *)params
                               didFinish:(void(^)(id json,NSError *error))didFinishBlock
{
    NSURLSessionDataTask *task = [self PostRequestUrl:url SetParams:[params copy] contentTypes:[NSSet setWithObjects:@"application/json",@"text/json",@"text/text",@"text/html",@"text/plain",@"text/javascript",nil] didFinish:didFinishBlock];
    return task;
}

+(NSURLSessionDataTask *) PostRequestUrl:(NSString *)url
                               SetParams:(NSDictionary *)params
                            contentTypes:(NSSet *)acceptableContentTypes
                               didFinish:(void(^)(id json,NSError *error))didFinishBlock
{
    
    AFHTTPSessionManager *manager = [self sessionManager];
    manager.responseSerializer = [AFJSONResponseSerializer serializer];
    manager.responseSerializer.acceptableContentTypes = acceptableContentTypes;
    
    dispatch_async_on_main_queue(^{
        //在向服务端发送请求状态栏显示网络活动标志：
        [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:YES];
    });
    
    NSURLSessionDataTask *task = [manager POST:url
                                    parameters: params
                                      progress:nil
                                       success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
                                           
#if DEBUG
                                           @try {
                                               if (![NSObject sq_isEmpty:responseObject]) {
                                                   NSString *jsonString = [[NSString alloc] initWithData:[NSJSONSerialization dataWithJSONObject:responseObject options:NSJSONWritingPrettyPrinted error:nil] encoding:NSUTF8StringEncoding];
                                                   NSString *log = [NSString stringWithFormat:@"\n**************** REQUEST: ****************\n【URL】 %@\n--------------------------------------------\npara:\n%@\n--------------------------------------------\nresponse:\n%@ \n*********************************************\n", url, [params description], jsonString];
                                                   printf("%s\n", [log UTF8String]);
                                               }
                                           } @catch (NSException *exception) {
                                               
                                           }
#endif
                                           dispatch_async_on_main_queue(^{
                                            
                                               [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:NO];
                                           });
                                           
                                           dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                                               [self getFailData:task responseObject:responseObject];
                                           });
                                           
                                           if (didFinishBlock) {
                                               didFinishBlock(responseObject,nil);
                                           }
                                   
                                           
                                       } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
#if DEBUG
                                           @try {
                                               NSString *log = [NSString stringWithFormat:@"\n**************** REQUEST ERROR: ****************\n【URL】%@\n--------------------------------------------\npara:\n%@\n--------------------------------------------\nresponse:\n%@ \n*********************************************\n", url, [params description], error];
                                               printf("%s\n", [log UTF8String]);
                                               
                                           } @catch (NSException *exception) {
                                               
                                           }
#endif
                                           dispatch_async_on_main_queue(^{
                                               //请求结束状态栏隐藏网络活动标志：
                                               [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:NO];
                                           });
                                           
                                           dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                                               [self getErrorData:task error:error];
                                           });
                                    
                                           if (didFinishBlock) {
                                               didFinishBlock(nil,error);
                                           }
                                       }];
    
    return task;
}

+ (AFHTTPSessionManager *)sessionManager {
    static dispatch_once_t onceToken;
    static AFHTTPSessionManager *manager = nil;
    dispatch_once(&onceToken, ^{
        manager = [AFHTTPSessionManager manager];
    
        manager.securityPolicy.allowInvalidCertificates = YES;
      
        [manager.securityPolicy setValidatesDomainName:NO];
        
     
    });
    
    NSString *coordinate = @"bd";
    [manager.requestSerializer setValue:coordinate forHTTPHeaderField:@"coordinate"];
 
    manager.requestSerializer.timeoutInterval = 15;
    
    return manager;
}

**Comment by Mamakou** [comment]
1   -[AFURLSessionManager delegateForTask:] (AFURLSessionManager.m:592)
2  -[AFURLSessionManager URLSession:dataTask:didReceiveData:] (AFURLSessionManager.m:0)

I have the same problem today, the top information was made by bugly,

device:iPhone 5c , system :ios10.3.3(14G60), I don't know exactly how it came about, I just feedback to you,thanks!!!

**Comment by HatsuneMikuV** [comment]
Excuse me, when can you solve it?

**Comment by JokerXu** [comment]
#0	(null) in __exceptionPreprocess ()
#1	(null) in objc_exception_throw ()
#2	(null) in +[NSException raise:format:] ()
#3	(null) in NSAllocateMemoryPages ()
#4	(null) in _NSDataCreateVMDispatchData ()
#5	(null) in -[_NSPlaceholderData initWithBytes:length:copy:deallocator:] ()
#6	(null) in -[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:] ()
#7	0x101fe106c in -[AFURLSessionManager URLSession:task:didCompleteWithError:] at /Users/xukun/open-ios-phone/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m:1012
#8	(null) in __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.207 ()
#9	(null) in __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ ()
#10	(null) in -[NSBlockOperation main] ()
#11	(null) in -[__NSOperationInternal _start:] ()
#12	(null) in _dispatch_client_callout ()
#13	(null) in _dispatch_block_invoke_direct$VARIANT$mp ()
#14	(null) in _dispatch_client_callout ()
#15	(null) in _dispatch_block_invoke_direct$VARIANT$mp ()
#16	(null) in dispatch_block_perform$VARIANT$mp ()
#17	(null) in __NSOQSchedule_f ()
#18	(null) in _dispatch_client_callout ()
#19	(null) in _dispatch_continuation_pop$VARIANT$mp ()
#20	(null) in _dispatch_async_redirect_invoke$VARIANT$mp ()
#21	(null) in _dispatch_root_queue_drain ()
#22	(null) in _dispatch_worker_thread3 ()
#23	(null) in _pthread_wqthread ()
#24	(null) in start_wqthread ()
 
I suffer this crash too

**Comment by senlinwuran** [comment]
Has this problem been solved?Is there any good solution?

**Comment by Jacky-LinPeng** [comment]
Has this problem been solved?Is there any good solution?
