### ISSUE TITLE
com.alamofire.error.serialization.response" - code: 18446744073709550605

### ISSUE THREAD

**Issue by savewoman** [AFNetworking/AFNetworking#4361]
com.alamofire.error.serialization.response  code:18446744073709550605
What's wrong with that? I just called the dataTaskWithRequest method

**Comment by savewoman** [comment]
I also set setHTTPBody

**Comment by bcichowlas** [comment]
I wish it wasn't closed. I just got this code today. I didn't get it when running to localhost but I did going to a remote server with the same code.
