### ISSUE TITLE
Why version 2.7.0 has been released now?

### ISSUE THREAD

**Issue by racer1988** [AFNetworking/AFNetworking#4362]
@SlaunchaMan Could you help me out with details about 2.7.0

https://github.com/AFNetworking/AFNetworking/releases/tag/2.7.0
Is this a update to support version 2.x?

Any plan on a new version 3.x?

**Comment by SlaunchaMan** [comment]
Sure! 2.7 was released to support some people who wanted to contribute PRs to fix bugs in their code and, for whatever reason, couldn’t update to 3.x. There is definitely a plan for future 3.x releases as time allows—[this milestone](https://github.com/AFNetworking/AFNetworking/milestone/16) is tracking PRs against it.

**Comment by racer1988** [comment]
Thanks! @SlaunchaMan
