### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]

### ISSUE THREAD

**Issue by DidiFly** [AFNetworking/AFNetworking#4374]
xcode10.2、iphone xs真机运行出现
EachAfforable[2459:860033] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 2459, TID: 860033, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0。这个问题是AFN内部问题吗？

**Comment by yimiaodaren** [comment]
同问
