### ISSUE TITLE
ssl pinning with root certificate failed using 3.0 

### ISSUE THREAD

**Issue by jiamo** [AFNetworking/AFNetworking#4375]
(AFSecurityPolicy *)customSecurityPolicy {

        NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"RootCA" ofType:@"cer"];
        NSData *certData = [NSData dataWithContentsOfFile:cerPath];
        AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
        securityPolicy.allowInvalidCertificates = YES;
        securityPolicy.validatesDomainName = NO;
        NSSet *set = [[NSSet alloc] initWithObjects:certData, nil];
        securityPolicy.pinnedCertificates = set;
        return securityPolicy;
    }

With this setting. The root ca failed. But when I use the third-level ca it can success.

**Comment by fanjiduo** [comment]
I also encountered the same problem! Help me! Help!

**Comment by ManuelSchmitzberger** [comment]
I had the same problem and I've fixed it by comparing the public keys of the chain in the `didReceiveChallenge` method of the `AFURLSessionManager`.
You can find my solution [here](https://stackoverflow.com/a/55721628/4291264) on Stackoverflow.
