### ISSUE TITLE
Getting this issue while Installing through Cartfile.

### ISSUE THREAD

**Issue by vgauravkanwar** [AFNetworking/AFNetworking#4377]
*** Skipped building AFNetworking due to the error:
Dependency "AFNetworking" has no shared framework schemes

## I am Trying to install the '2.7.0' version of AFNetworking

**Comment by Kjuly** [comment]
Got same error:

> Dependency "AFNetworking" has no shared framework schemes for any of the platforms: Mac, iOS, watchOS

Seems there's sth wrong for the release `2.7.0` (I checked the workspace under `/Carthage/Checkouts` folder, it only contains some example projects, no framework related shemes).

---
After changing `Cartfile` content from

> github "AFNetworking/AFNetworking" == 2.7.0

to 

> github "AFNetworking/AFNetworking" "5cf601ce0cbdd758da4b31d85a49514219a1faf8"
> \# Note: `5cf601ce0cbdd758da4b31d85a49514219a1faf8` is the latest commit sha, u can use any other one or even branch name like `master` to track the latest.

it built succeed w/o any error.

Hope it helps. :)
