### ISSUE TITLE
设置AFURLSessionTaskDidReceiveAuthenticationChallengeBlock无效

### ISSUE THREAD

**Issue by unkosun** [AFNetworking/AFNetworking#4383]
设置TaskDidReceiveAuthenticationChallengeBlock， 当 challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust时，`NSURLSessionTaskDelegate的代`理方法`URLSession:task:didReceiveChallenge:completionHandler:` 不会被调用。 因为在AFURLSessionManager中已经实现了`URLSession:didReceiveChallenge:completionHandler:`方法。
详见：https://developer.apple.com/documentation/foundation/nsurlsessiontaskdelegate/1411595-urlsession

pull request: #4382

**Comment by lafayea** [comment]
同上!!!

**Comment by unkosun** [comment]
> 同上!!!

我提交了一个pull request 但是没有通过 #4382

**Comment by lafayea** [comment]
I found it!!!
最近我们公司也要用httpDns把原始host换成IP发请求, 然后遇到了ssl校验不通过的问题,
第三方HTTPDns的文档或demo上都说在sessiontask 代理方法里去改host, 但是afn 根本就不会走task的代理方法, 它走的是session的代理方法;两个方法我都分别列在下面:
afn不走的task的代理方法:

(void)URLSession:(NSURLSession *)session
task:(NSURLSessionTask *)task
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;
afn走的session的代理方法:
(void)URLSession:(NSURLSession *)session
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;
这两个方法唯一的区别就是一个带task一个不带task, 但是致命问题就产生了, 不带task的session的代理方法无法拿到原始的没有换成IP的host, 也就无法再进行domain校验时再偷梁换柱将IP换成原始host地址去校验!
那么, 怎么解决这个问题, 让我们能使用afn用IP地址去请求呢?

首先明确解决思路:
在进行ssl校验时, 把ip换回原始host, 用原始host与后台服务器进行校验.

具体实现:
我们先去看看afn走的session的代理方法里做了什么:

(void)URLSession:(NSURLSession *)session
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler
{
NSURLSessionAuthChallengeDisposition disposition = NSURLSessionAuthChallengePerformDefaultHandling;
__block NSURLCredential *credential = nil;
if (self.sessionDidReceiveAuthenticationChallenge) {//注意看这里
disposition = self.sessionDidReceiveAuthenticationChallenge(session, challenge, &credential);
} else {
if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {
if ([self.securityPolicy evaluateServerTrust:challenge.protectionSpace.serverTrust forDomain:challenge.protectionSpace.host]) {
credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];
if (credential) {
disposition = NSURLSessionAuthChallengeUseCredential;
} else {
disposition = NSURLSessionAuthChallengePerformDefaultHandling;
}
} else {
disposition = NSURLSessionAuthChallengeCancelAuthenticationChallenge;
}
} else {
disposition = NSURLSessionAuthChallengePerformDefaultHandling;
}
}

if (completionHandler) {
completionHandler(disposition, credential);
}
}

注意看我标注"注意看这里"的那一行, 只要self.sessionDidReceiveAuthenticationChallenge有值他就不会走底下的else方法(也就是系统默认的校验方法), 就会走我们定义的校验方法;
那么好了我们只需要给它sessionDidReceiveAuthenticationChallenge即可:
[mgr setSessionDidReceiveAuthenticationChallengeBlock:^NSURLSessionAuthChallengeDisposition(NSURLSession * _Nonnull session, NSURLAuthenticationChallenge * _Nonnull challenge, NSURLCredential *__autoreleasing _Nullable * _Nullable credential) {
//证书校验替换IP
NSURLSessionAuthChallengeDisposition disposition = NSURLSessionAuthChallengePerformDefaultHandling;
if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {
NSString *originHost = weakMgr.requestSerializer.HTTPRequestHeaders[@"host"];
if ([weakMgr.securityPolicy evaluateServerTrust:challenge.protectionSpace.serverTrust forDomain:originHost]) {//这个方法是校验ssl的关键校验时需要把IP替换成原始host
*credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];
if (credential) {
disposition = NSURLSessionAuthChallengeUseCredential;
} else {
disposition = NSURLSessionAuthChallengePerformDefaultHandling;
}
} else {
disposition = NSURLSessionAuthChallengeCancelAuthenticationChallenge;
}
} else {
disposition = NSURLSessionAuthChallengePerformDefaultHandling;
}
return disposition;
}];
这里有个关键的地方就是, evaluateServerTrust:(SecTrustRef)serverTrust
forDomain:(NSString *)domain 这个方法会进行domain校验, 也就是ssl校验, 它需要传校验的host 和 服务器的serverTrust, 两者匹配通过则ssl校验通过, 我们就是要在这里将host换成原始host, 之后就顺利通过啦;
我将原始host存在请求头里, 这样就能通过请求头取到,上面有写到:
NSString *originHost = weakMgr.requestSerializer.HTTPRequestHeaders[@"host"];
Cheers~

**Comment by unkosun** [comment]
> `credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];`
> `if (credential) {`
> `disposition = NSURLSessionAuthChallengeUseCrede`

根据苹果的文档，其实只要AFURLSessionManager不实现`URLSession:didReceiveChallenge:completionHandler:`这个代理方法就可以了。

**Comment by lafayea** [comment]
我试过注掉afn的`URLSession:didReceiveChallenge:completionHandler:`但是发现`URLSession:task:didReceiveChallenge:completionHandler:`这个代理方法并不是每次都会走, 只会在启动的时候走一次, 不知道为什么

**Comment by VVennn** [comment]
> I found it!!!
> 最近我们公司也要用httpDns把原始host换成IP发请求, 然后遇到了ssl校验不通过的问题,
> 第三方HTTPDns的文档或demo上都说在sessiontask 代理方法里去改host, 但是afn 根本就不会走task的代理方法, 它走的是session的代理方法;两个方法我都分别列在下面:
> 
> afn不走的task的代理方法:
> `-(void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;`
> 
> afn走的session的代理方法:
> `-(void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;`
> 
> 这两个方法唯一的区别就是一个带task一个不带task, 但是致命问题就产生了, 不带task的session的代理方法无法拿到原始的没有换成IP的host, 也就无法再进行domain校验时再偷梁换柱将IP换成原始host地址去校验!
> 那么, 怎么解决这个问题, 让我们能使用afn用IP地址去请求呢?
> 
> 首先明确解决思路:
> 在进行ssl校验时, 把ip换回原始host, 用原始host与后台服务器进行校验.
> 
> 具体实现:
> 我们先去看看afn走的session的代理方法里做了什么:
> 
> > -(void)URLSession:(NSURLSession *)session
> > didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
> > completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler
> > {
> > NSURLSessionAuthChallengeDisposition disposition = NSURLSessionAuthChallengePerformDefaultHandling;
> > __block NSURLCredential *credential = nil;
> > if (self.sessionDidReceiveAuthenticationChallenge) {//注意看这里
> > disposition = self.sessionDidReceiveAuthenticationChallenge(session, challenge, &credential);
> > } else {
> > if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {
> > if ([self.securityPolicy evaluateServerTrust:challenge.protectionSpace.serverTrust forDomain:challenge.protectionSpace.host]) {
> > credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];
> > if (credential) {
> > disposition = NSURLSessionAuthChallengeUseCredential;
> > } else {
> > disposition = NSURLSessionAuthChallengePerformDefaultHandling;
> > }
> > } else {
> > disposition = NSURLSessionAuthChallengeCancelAuthenticationChallenge;
> > }
> > } else {
> > disposition = NSURLSessionAuthChallengePerformDefaultHandling;
> > }
> > }
> > if (completionHandler) {
> > completionHandler(disposition, credential);
> > }
> > }
> 
> 注意看我标注"注意看这里"的那一行, 只要self.sessionDidReceiveAuthenticationChallenge有值他就不会走底下的else方法(也就是系统默认的校验方法), 就会走我们定义的校验方法;
> 
> 那么好了我们只需要给它sessionDidReceiveAuthenticationChallenge即可:
> 
> `[mgr setSessionDidReceiveAuthenticationChallengeBlock:^NSURLSessionAuthChallengeDisposition(NSURLSession * _Nonnull session, NSURLAuthenticationChallenge * _Nonnull challenge, NSURLCredential *__autoreleasing _Nullable * _Nullable credential) {`
> 
> `//证书校验替换IP `
> ` NSURLSessionAuthChallengeDisposition disposition = NSURLSessionAuthChallengePerformDefaultHandling;`
> 
> `if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {`
> 
> `NSString *originHost = weakMgr.requestSerializer.HTTPRequestHeaders[@"host"]; `
> `if ([weakMgr.securityPolicy evaluateServerTrust:challenge.protectionSpace.serverTrust forDomain:originHost]) {//这个方法是校验ssl的关键校验时需要把IP替换成原始host`
> `*credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];`
> `if (credential) {`
> `disposition = NSURLSessionAuthChallengeUseCredential;`
> `} else {`
> `disposition = NSURLSessionAuthChallengePerformDefaultHandling;`
> `}`
> `} else {`
> `disposition = NSURLSessionAuthChallengeCancelAuthenticationChallenge;`
> `}`
> `} else {`
> `disposition = NSURLSessionAuthChallengePerformDefaultHandling;`
> `}`
> `return disposition;`
> `}]; `
> 这里有个关键的地方就是, evaluateServerTrust:(SecTrustRef)serverTrust
> forDomain:(NSString *)domain 这个方法会进行domain校验, 也就是ssl校验, 它需要传校验的host 和 服务器的serverTrust, 两者匹配通过则ssl校验通过, 我们就是要在这里将host换成原始host, 之后就顺利通过啦;
> 
> 我将原始host存在请求头里, 这样就能通过请求头取到,上面有写到:
> `NSString *originHost = weakMgr.requestSerializer.HTTPRequestHeaders[@"host"];`
> 
> Cheers~
> 备注: mgr是业务代码 它是指AFHTTPSessionManager的实例;

你好

> I found it!!!
> 最近我们公司也要用httpDns把原始host换成IP发请求, 然后遇到了ssl校验不通过的问题,
> 第三方HTTPDns的文档或demo上都说在sessiontask 代理方法里去改host, 但是afn 根本就不会走task的代理方法, 它走的是session的代理方法;两个方法我都分别列在下面:
> 
> afn不走的task的代理方法:
> `-(void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;`
> 
> afn走的session的代理方法:
> `-(void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;`
> 
> 这两个方法唯一的区别就是一个带task一个不带task, 但是致命问题就产生了, 不带task的session的代理方法无法拿到原始的没有换成IP的host, 也就无法再进行domain校验时再偷梁换柱将IP换成原始host地址去校验!
> 那么, 怎么解决这个问题, 让我们能使用afn用IP地址去请求呢?
> 
> 首先明确解决思路:
> 在进行ssl校验时, 把ip换回原始host, 用原始host与后台服务器进行校验.
> 
> 具体实现:
> 我们先去看看afn走的session的代理方法里做了什么:
> 
> > -(void)URLSession:(NSURLSession *)session
> > didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
> > completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler
> > {
> > NSURLSessionAuthChallengeDisposition disposition = NSURLSessionAuthChallengePerformDefaultHandling;
> > __block NSURLCredential *credential = nil;
> > if (self.sessionDidReceiveAuthenticationChallenge) {//注意看这里
> > disposition = self.sessionDidReceiveAuthenticationChallenge(session, challenge, &credential);
> > } else {
> > if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {
> > if ([self.securityPolicy evaluateServerTrust:challenge.protectionSpace.serverTrust forDomain:challenge.protectionSpace.host]) {
> > credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];
> > if (credential) {
> > disposition = NSURLSessionAuthChallengeUseCredential;
> > } else {
> > disposition = NSURLSessionAuthChallengePerformDefaultHandling;
> > }
> > } else {
> > disposition = NSURLSessionAuthChallengeCancelAuthenticationChallenge;
> > }
> > } else {
> > disposition = NSURLSessionAuthChallengePerformDefaultHandling;
> > }
> > }
> > if (completionHandler) {
> > completionHandler(disposition, credential);
> > }
> > }
> 
> 注意看我标注"注意看这里"的那一行, 只要self.sessionDidReceiveAuthenticationChallenge有值他就不会走底下的else方法(也就是系统默认的校验方法), 就会走我们定义的校验方法;
> 
> 那么好了我们只需要给它sessionDidReceiveAuthenticationChallenge即可:
> 
> `[mgr setSessionDidReceiveAuthenticationChallengeBlock:^NSURLSessionAuthChallengeDisposition(NSURLSession * _Nonnull session, NSURLAuthenticationChallenge * _Nonnull challenge, NSURLCredential *__autoreleasing _Nullable * _Nullable credential) {`
> 
> `//证书校验替换IP `
> ` NSURLSessionAuthChallengeDisposition disposition = NSURLSessionAuthChallengePerformDefaultHandling;`
> 
> `if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {`
> 
> `NSString *originHost = weakMgr.requestSerializer.HTTPRequestHeaders[@"host"]; `
> `if ([weakMgr.securityPolicy evaluateServerTrust:challenge.protectionSpace.serverTrust forDomain:originHost]) {//这个方法是校验ssl的关键校验时需要把IP替换成原始host`
> `*credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];`
> `if (credential) {`
> `disposition = NSURLSessionAuthChallengeUseCredential;`
> `} else {`
> `disposition = NSURLSessionAuthChallengePerformDefaultHandling;`
> `}`
> `} else {`
> `disposition = NSURLSessionAuthChallengeCancelAuthenticationChallenge;`
> `}`
> `} else {`
> `disposition = NSURLSessionAuthChallengePerformDefaultHandling;`
> `}`
> `return disposition;`
> `}]; `
> 这里有个关键的地方就是, evaluateServerTrust:(SecTrustRef)serverTrust
> forDomain:(NSString *)domain 这个方法会进行domain校验, 也就是ssl校验, 它需要传校验的host 和 服务器的serverTrust, 两者匹配通过则ssl校验通过, 我们就是要在这里将host换成原始host, 之后就顺利通过啦;
> 
> 我将原始host存在请求头里, 这样就能通过请求头取到,上面有写到:
> `NSString *originHost = weakMgr.requestSerializer.HTTPRequestHeaders[@"host"];`
> 
> Cheers~
> 备注: mgr是业务代码 它是指AFHTTPSessionManager的实例;

你好，请问为什么我的https请求既不走
```
-(void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;
```
也不走
```
-(void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;
```
我需要在项目里配置什么吗？
