### ISSUE TITLE
Xcode 10.2，I used Carthage to package AFNetworking.framework

### ISSUE THREAD

**Issue by wongshouxin** [AFNetworking/AFNetworking#4384]
I used Carthage to package AFNetworking.framework, but  Used in projects， A compiler error

**Failed to read file or folder at /Users/***/Carthage/Build/iOS/AFNetworking.framework
Command /bin/sh failed with exit code 1**
my Xcode is  10.2

**Comment by brduca** [comment]
I'm having this problem too. 

*** Building scheme "AFNetworking iOS" in AFNetworking.xcodeproj
Build Failed
	Task failed with exit code 65:
