### ISSUE TITLE
APP 崩溃，Xcode中统计到的Crash信息如下

### ISSUE THREAD

**Issue by blooming2017** [AFNetworking/AFNetworking#4388]
CFNetwork: HTTPMessage::ensureParserFinished() + 108
CFNetwork: invocation function for block in HTTPHeaderDict::sizeHeaders() const + 36
CFNetwork: ___ZNK14HTTPHeaderDict11sizeHeadersEv_block_invoke + 36

**Comment by SongHuaixu** [comment]
Has the problem been solved？

**Comment by SongHuaixu** [comment]
@blooming2017  Has the problem been solved？
