### ISSUE TITLE
AFNetworking  isReachable网络检查的方法问题反馈

### ISSUE THREAD

**Issue by yimiSun** [AFNetworking/AFNetworking#4395]
我使用的 AFNetworking 版本为 3.1.0 iPhone模拟器设备系统为 11.2，Mac电脑连接的Wifi 网路，网络正常。当使用 isReachable 方法检查网络时显示为没有网络，通过断点调试发现 self.networkReachabilityStatus 的值为 AFNetworkReachabilityStatusUnknown。因此个人以为isReachable 的判断需要调整，具体修改如下：
`- (BOOL)isReachable {
    //return [self isReachableViaWWAN] || [self isReachableViaWiFi];
    return self.networkReachabilityStatus != AFNetworkReachabilityStatusNotReachable;
}`
最后，祝愿AFNetworking 越来越强大

**Comment by 12star9** [comment]
PR看看.
