### ISSUE TITLE
[__NSCFString appendString:]: nil argument 

### ISSUE THREAD

**Issue by zhangzhiyongA** [AFNetworking/AFNetworking#4399]
[__NSCFString appendString:]: nil argument 

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x20629fec4 __exceptionPreprocess
1  libobjc.A.dylib                0x205470a40 objc_exception_throw
2  CoreFoundation                 0x2061a6594 -[NSCache init]
3  CoreFoundation                 0x2062157d8 mutateError
4  NovelCool                      0x101260c20 AFPercentEscapedStringFromString (AFURLRequestSerialization.m:73)
5  NovelCool                      0x101260eb8 -[AFQueryStringPair URLEncodedStringValue] (AFURLRequestSerialization.m:108)

**Comment by zhangzhiyongA** [comment]
[AFQueryStringPair URLEncodedStringValue] 中字符串拼接为空  崩溃

**Comment by yituwangpeng** [comment]
please deal with this issue
