### ISSUE TITLE
SSL pinned certificates in iOS 13 not working

### ISSUE THREAD

**Issue by sarsonj** [AFNetworking/AFNetworking#4403]
Hi,

I just tried to compile my app under iOS 13. The app failed on HTTPS loading. I debugged AF Networking code and it looks like, that in AFSecurityPolicy when evaluateServerTrust is called the function `AFServerTrustIsValid` returns `kSecTrustResultRecoverableTrustFailure`.

It tried to find, what changed related this on iOS 13, but didn't find anything. Any idea?

**Comment by fitch** [comment]
I'm having the same problem. Any ideas on how to fix?

**Comment by sarsonj** [comment]
There are new certificate rules on iOS 13. For example, certificate, that had validity longer than 825 days. We are using our certificates created, that has validity 10 years, therefore then they are marked as invalid on iOS 13.

https://www.zdnet.com/article/apple-deprecates-sha-1-certificates-in-ios-13-and-macos-catalina/

The solution is (in my case) to allow invalid certificates and also disable domain name validation:

```        AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
        securityPolicy.allowInvalidCertificates = YES;
    
        securityPolicy.validatesDomainName = NO;
```

Because we validate certificate by SSL pinning and check, that it is issued by our CA, it is for us feasible.
