### ISSUE TITLE
-[NSURLSessionTask(_AFStateObserving) af_resume] + 48

### ISSUE THREAD

**Issue by mohaoyang** [AFNetworking/AFNetworking#4410]
![image](https://user-images.githubusercontent.com/23443657/60409912-2830eb00-9bf8-11e9-8ef9-4db377aeb3a5.png)
谁能告诉我这个怎么解决？（who can tell me how to solve this?）

**Comment by kinarobin** [comment]
What `AFNetWorking` version are you using?

**Comment by mohaoyang** [comment]
> What `AFNetWorking` version are you using?
3.2.1

**Comment by kinarobin** [comment]
You can use 3.1.0
