### ISSUE TITLE
最大并发请求问题

### ISSUE THREAD

**Issue by msk521** [AFNetworking/AFNetworking#4421]
AFN3.0请求没有设置最大并发数的情况，只是针对回调处理加了串行处理，那么现在公司这边加了高防之后，现在请求超时数量剧增，目前猜测原因是因为请求数过多排队等待造成的超时，所以想问下如何设置请求最大并发数呢？

**Comment by 245307867** [comment]
.operationQueue.maxConcurrentOperationCount

**Comment by ericdream** [comment]
maxConcurrentOperationCount 这个不是最大并发数

**Comment by ericdream** [comment]
> .operationQueue.maxConcurrentOperationCount
maxConcurrentOperationCount 这个不是最大并发数

**Comment by wushenchao** [comment]
你可以继承AFURLSessionManager自定义自己的请求
