### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-999 for select few connections

### ISSUE THREAD

**Issue by kevinmun** [AFNetworking/AFNetworking#4422]
Currently have a few users hitting into this error. Couple of info:
1) I do keep the sessionmanager as a global object so it is always
2) it is almost the same endpoint which hits this error
3) use https but no pinned certificate
4) no successful connection log from server as well, not even for error response, meaning the connection did not quite reach our server

What other reasons are there, that might cause this -999 error code for only a select few users?

**Comment by zerozheng** [comment]
I got the same problem two week ago...single instance of sessionMananger, CA certificate

**Comment by zerozheng** [comment]
My problem is located. it was cause by the DNS error.
