### ISSUE TITLE
Crash at AFURLRequestSerialization.m->line 316

### ISSUE THREAD

**Issue by binhan198** [AFNetworking/AFNetworking#4425]
Here is the collapse information:
<img width="664" alt="WX20190822-092723@2x" src="https://user-images.githubusercontent.com/23467069/63479061-11539a00-c4bf-11e9-8e2f-c641d74cf73f.png">
Xcode Version: 10.2.1
Deployment Target: iOS 9.0

Here is my code，it's simple：
`for (NSInteger i = 0; i < 10000; ++i) {
        [self.requestSerializer copy];
    }`
I think the problem is `copyWithZone:`in AFHTTPRequestSerializer，when doing `AFHTTPRequestSerializer *serializer = [[[self class] allocWithZone:zone] init];`
`dispatch_sync(self.requestHeaderModificationQueue, ^{
        serializer.mutableHTTPRequestHeaders = [self.mutableHTTPRequestHeaders mutableCopyWithZone:zone];
    });`
They just handle the same serializer.mutableHTTPRequestHeaders in different "requestHeaderModificationQueue"

**Comment by binhan198** [comment]
by the way, `self.requestSerializer` is a AFJSONRequestSerializer object

**Comment by gestrich** [comment]
We get this lockup occasionally too leading to a crash. Here's the stack trace. The background threads are not related to AFNetworking -- just the main thread.

```
Thread 0:
0   libsystem_kernel.dylib               0x00000001ec1969d4 __ulock_wait + 8
1   libdispatch.dylib                    0x00000001ebfdab94 _dispatch_thread_event_wait_slow$VARIANT$mp + 44
2   libdispatch.dylib                    0x00000001ebfe6ec0 __DISPATCH_WAIT_FOR_QUEUE__ + 324
3   libdispatch.dylib                    0x00000001ebfe6ad8 _dispatch_sync_f_slow + 136
4   <>                           0x000000010266b8cc -[AFHTTPRequestSerializer HTTPRequestHeaders] (AFURLRequestSerialization.m:306)
5   <>                           0x000000010267075c -[AFJSONRequestSerializer requestBySerializingRequest:withParameters:error:] (AFURLRequestSerialization.m:1246)
6   <>                           0x000000010266c0dc -[AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:] (AFURLRequestSerialization.m:376)
7   <>                           0x0000000101e32a78 -[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:] (AFHTTPSessionManager.m:276)
8   <>                           0x0000000101e32130 -[AFHTTPSessionManager POST:parameters:progress:success:failure:] (AFHTTPSessionManager.m:179)
```

Here's the code where it is lockup up:

```    
dispatch_sync(self.requestHeaderModificationQueue, ^{
        value = [NSDictionary dictionaryWithDictionary:self.mutableHTTPRequestHeaders];
});
```

I'm not quite sure why it fails to acquire the queue. I'm inclined to think that a dispatch_sync on the main queue to a lower priority queue is a possible cause.

**Comment by JDongKhan** [comment]
@gestrich  me to
