### ISSUE TITLE
appstore审核提示用了UIWebView的api，被拒绝

### ISSUE THREAD

**Issue by tfy87happy** [AFNetworking/AFNetworking#4436]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.   
请问能更新代码把UIWebView分类去掉么

**Comment by spraveenk91** [comment]
We don't see any of the pull requests has been approved to fix this issue? When can we expect to see this issue to be resolved?

Any ideas @kcharwood  @mattt @Kaspik

**Comment by JinfengLi888** [comment]
I've also received the same warning from Apple. When shall fix this issue?

**Comment by leviduan** [comment]
It's just a warning, I can upload my app with the warning.

**Comment by b593771943** [comment]
> It's just a warning, I can upload my app with the warning.

But I am afraid that manual review will be affected,I've heard that some people have been turned down for this warning

**Comment by tikamsingh** [comment]
Is anybody got approved from apple reviewer with this warning?

**Comment by daniusite** [comment]
我也收到了,不知道苹果是怎么检测的

**Comment by anish190** [comment]
I got my app approved last week with UIWebview. But I am working on replacing UIWebView with WKWebView for my upcoming release.

**Comment by snow-nwh** [comment]
I delete the `UIWebView+AFNetworking`category , but it seems not working.

**Comment by Xianyus** [comment]
目前只是一个警告, 我们的AppStore已经审核过了

**Comment by anurajl** [comment]
@Xianyus As of now, Apple won't reject the build. But going forward this needs to be addressed.

**Comment by tjanela** [comment]
Hey everybody, #4439 is available and passing all CI tests. We have one dependency on one of our projects that uses this lib so we would like to see this addressed and a new version of AFNetworking pushed out.
Does anybody here have a direct comm channel with one of the maintainers?
Thanks!

**Comment by Daemonson** [comment]
> Hey everybody, #4439 is available and passing all CI tests. We have one dependency on one of our projects that uses this lib so we would like to see this addressed and a new version of AFNetworking pushed out.
> Does anybody here have a direct comm channel with one of the maintainers?
> Thanks!

From the information on the release page，some of the latest release versions were released by SlaunchaMan，maybe @SlaunchaMan can help release a new version.

**Comment by tjanela** [comment]
Thank you @Daemonson, I'm going to reach out to @SlaunchaMan and see what needs to be done to push #4439 out.

**Comment by anurajl** [comment]
@tjanela Any update from SlaunchaMan on this?

**Comment by sunKit-io** [comment]
AFNetworkin , BlockKit 删除其中的分类即可

**Comment by tjanela** [comment]
> @tjanela Any update from SlaunchaMan on this?

No, haven't heard back from any of the listed maintainers, nor from the Alamofire team.

**Comment by knarf74** [comment]
Still no traction on this? Looks like #4439 is close.

**Comment by tjanela** [comment]
@knarf74, things are pretty close. I managed to break #4439 into digestible chunks as requested by the maintainers. It’s up to them now.

**Comment by jacekdogiel** [comment]
Why is this taking so long?

**Comment by sunKit-io** [comment]
这个只是警告，并不会影响正常上线，我们的APP 已经审核通过了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jacek Dogiel"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 下午4:50
收件人: "AFNetworking/AFNetworking"<AFNetworking@noreply.github.com&gt;; 
抄送: "Casper ????????"<873235315@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [AFNetworking/AFNetworking] appstore审核提示用了UIWebView的api，被拒绝 (#4436)




Why is this taking so long?
 
&mdash;

**Comment by knarf74** [comment]
@tjanela still not looking good. lost traction with #4439?

**Comment by tjanela** [comment]
Hey @knarf74, it seems like @jshier got his attention steered elsewhere.
I would love to see this #4439 released, as the community as invested in this a lot.
Despite the warning around AFNetworking being replaced by newer approaches, it is still widely used and, as such, would warrant some form of LTS. I guess it's either maintaining our own forks or waiting for a release.

**Comment by tjanela** [comment]
See #4439

**Comment by Kaspik** [comment]
Updated, released. Can be closed.
