### ISSUE TITLE
ios13请求出错

### ISSUE THREAD

**Issue by ZClee128** [AFNetworking/AFNetworking#4442]
什么时候发布新版，在xcode11，ios13模拟器下请求出错
Task <CB3EF668-809B-4B94-9922-7788EA0CC94D>.<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])

**Comment by MagicalGemini** [comment]
@ZClee128 I have encounted the same issue and I fixed it by update the AFNetworking to 2.7.0

**Comment by liyanfei1004774105** [comment]
我是真机报错，

**Comment by liyanfei1004774105** [comment]
> 什么时候发布新版，在xcode11，ios13模拟器下请求出错
> Task .<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])

请问这个问题解决了么？

**Comment by yizems** [comment]
我们线上部分客户端报错
