### ISSUE TITLE
Carthage update broken in xcode11

### ISSUE THREAD

**Issue by shawhu** [AFNetworking/AFNetworking#4445]
Cartfile
github "AFNetworking/AFNetworking" ~> 3.0

carthage update

and it will fail, error msg:
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/shawhu/Projects/xcodeprojects/TakeAShot/Carthage/Checkouts/AFNetworking/AFNetworking.xcworkspace -scheme AFNetworking\ macOS -configuration Release -derivedDataPath /Users/shawhu/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/AFNetworking/3.2.1 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/hm/psbj1lxx3pz564q1vsytqq1m0000gn/T/AFNetworking SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/shawhu/Projects/xcodeprojects/TakeAShot/Carthage/Checkouts/AFNetworking)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details:

After switch to xcode10 using xcode-select, everything is working under xcode10

**Comment by yannickpeysale** [comment]
by checking the full log, here is the error: 

/Users/ypeysale/Documents/workspace/***/***/Carthage/Checkouts/AFNetworking/AFNetworking/AFURLRequestSerialization.m:574:26: error: implicit conversion changes signedness: 'AFHTTPRequestQueryStringSerializationStyle' (aka 'enum AFHTTPRequestQueryStringSerializationStyle') to 'NSInteger' (aka 'int') [-Werror,-Wsign-conversion]
    [coder encodeInteger:self.queryStringSerializationStyle forKey:NSStringFromSelector(@selector(queryStringSerializationStyle))];
    ~                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ypeysale/Documents/workspace/***/***/Carthage/Checkouts/AFNetworking/AFNetworking/AFURLRequestSerialization.m:1298:26: error: implicit conversion changes signedness: 'NSJSONWritingOptions' (aka 'enum NSJSONWritingOptions') to 'NSInteger' (aka 'int') [-Werror,-Wsign-conversion]
    [coder encodeInteger:self.writingOptions forKey:NSStringFromSelector(@selector(writingOptions))];
    ~                    ^~~~~~~~~~~~~~~~~~~
/Users/ypeysale/Documents/workspace/***/***/Carthage/Checkouts/AFNetworking/AFNetworking/AFURLRequestSerialization.m:1384:26: error: implicit conversion changes signedness: 'NSPropertyListFormat' (aka 'enum NSPropertyListFormat') to 'NSInteger' (aka 'int') [-Werror,-Wsign-conversion]
    [coder encodeInteger:self.format forKey:NSStringFromSelector(@selector(format))];

**Comment by acBool** [comment]
try this:
[coder encodeInteger:(NSInteger)self.writingOptions forKey:NSStringFromSelector(@selector(writingOptions))];

**Comment by jgarciatt** [comment]
Hello. 

Any update on this? I had to revert to 3.1.0 to make it work.

**Comment by chrisoneiota** [comment]
Thanks for the tip that rolling back to 3.1.0 gets round the problem!  I've been watching this as it is blocking us moving to latest XCode version.

**Comment by woutergoossens** [comment]
Any update to fix this without rolling back?

**Comment by AlexanderPan** [comment]
Any update to fix this without rolling back? +1

**Comment by saim80** [comment]
Just encountered this. I will use 3.1.0. Thanks for the note.

**Comment by joealzhou** [comment]
Thanks! i use 3.1.0 can resolve this problem

**Comment by simonnickel** [comment]
Same issue here. Version 3.2.1 is not building right now, even the status on main README.md shows build failed.

Using 3.1.0 instead works as a workaround.

**Comment by ElfSundae** [comment]
try my fork? 
```
github "ElfSundae/AFNetworking" ~> 3.0
```
https://github.com/ElfSundae/AFNetworking/issues/1

**Comment by Kaspik** [comment]
Updated, released. Can be closed I believe.
