### ISSUE TITLE
iOS13.1报错

### ISSUE THREAD

**Issue by maying1992** [AFNetworking/AFNetworking#4448]
[] nehelper sent invalid result code [1] for Wi-Fi information request

**Comment by tjanela** [comment]
@maying1992 this is related to new security enforcements made by iOS 13 when apps try to obtain WiFi information. I've looked into AFNetworking's codebase and can't seem to find a call that would trigger this console output.
Are you using AFNetworking's reachability infrastructure?
Why are you saying this is related to AFNetworking?

**Comment by MrStock007** [comment]
uicollectionview with SdWEbimage，reloadData，twice or more。 App Crash，upload is the log

**Comment by MrStock007** [comment]
UICollectionViewCell contains a UIImageView,  use SDWebImage set image ,reloadData repeatly without interval .App will crash in bad net condition.----- ios13,xcode11,

**Comment by allan304** [comment]
> @maying1992 this is related to new security enforcements made by iOS 13 when apps try to obtain WiFi information. I've looked into AFNetworking's codebase and can't seem to find a call that would trigger this console output.
> Are you using AFNetworking's reachability infrastructure?
> Why are you saying this is related to AFNetworking?

I am using AFNetworking's reachability, and " [] nehelper sent invalid result code [1] for Wi-Fi information request".  Can you help me?
