### ISSUE TITLE
iOS 13 get networkState error --reachableViaWiFi

### ISSUE THREAD

**Issue by sanlunaifen** [AFNetworking/AFNetworking#4453]
[AFNetworkReachabilityManager sharedManager].reachableViaWiFi，this func in iOS 12 is correct，but in iOS 13 is error，but setReachabilityStatusChangeBlock get the result is correct

**Comment by housenkui** [comment]
can you put a picture ?

**Comment by housenkui** [comment]
@sanlunaifen

**Comment by MQL9011** [comment]
I have the same problem.
 
Is there any solution?

**Comment by Zxudong** [comment]
Is this problem solved?

**Comment by xiangshun110** [comment]
I have the same problem.

**Comment by Anny-github** [comment]
It is recommended to adapt to iOS13 as soon as possible, and developers should not develop with xcode13 until it is ready

**Comment by MrStock007** [comment]
uicollectionview with SdWEbimage，reloadData，twice or more。 App Crash

**Comment by MrStock007** [comment]
UICollectionViewCell contains a UIImageView, use SDWebImage set image ,reloadData repeatly without interval .App will crash in bad net condition.----- ios13,xcode11,

**Comment by MrStock007** [comment]
If I /***/ the setImageWithURL ，crash won't happen

**Comment by MrStock007** [comment]
I get this from SDWebImage Developer 
https://github.com/SDWebImage/SDWebImage/issues/2868
