### ISSUE TITLE
Not working for UIKitMac on macOS Catelina

### ISSUE THREAD

**Issue by umairxiq** [AFNetworking/AFNetworking#4454]
'initWithMemoryCapacity:diskCapacity:diskPath:' is unavailable: not available on macCatalyst

**Comment by igornazarov1991** [comment]
Same problem.

**Comment by kprigel** [comment]
See this PR:  https://github.com/AFNetworking/AFNetworking/pull/4418

**Comment by Kaspik** [comment]
Updated, released. Can be closed.
