### ISSUE TITLE
while carthage build AFNetworking

### ISSUE THREAD

**Issue by ydlsl** [AFNetworking/AFNetworking#4458]
Building scheme "AFNetworking watchOS" in AFNetworking.xcworkspace
Build Failed
	Task failed with exit code 65:

**Comment by ydlsl** [comment]
Building scheme "AFNetworking macOS" in AFNetworking.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/didi/ydAdd/project/ios_carthage/CarthageTestForAFNet/Carthage/Checkouts/AFNetworking/AFNetworking.xcworkspace -scheme AFNetworking\ macOS -configuration Release -derivedDataPath /Users/didi/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/AFNetworking/3.2.1 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/lc/bdcfmzjs10v1dch03kd97dlc0000gn/T/AFNetworking SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/didi/ydAdd/project/ios_carthage/CarthageTestForAFNet/Carthage/Checkouts/AFNetworking)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/lc/bdcfmzjs10v1dch03kd97dlc0000gn/T/carthage-xcodebuild.AIN6cy.log

**Comment by woutergoossens** [comment]
Same issue. Can this be fixed without rollback to 3.1.0?
I see there are open PR's for this, can they be merged and can there be a new release for this?

**Comment by ydlsl** [comment]
I think so, when I update my carthage, it failed. I didn’t know that I had this problem until I saw it.

**Comment by kblecher** [comment]
use this before your carthage update command:

export GCC_TREAT_WARNINGS_AS_ERRORS=NO

**Comment by virusman** [comment]
@kblecher Thank you!!

**Comment by Kaspik** [comment]
Updated, released. Can be closed I believe.
