### ISSUE TITLE
'UIWebview' referenced by AFNetworking is disabled by ios13

### ISSUE THREAD

**Issue by Gordon2780** [AFNetworking/AFNetworking#4466]
When the app relies on AFNetworking to upload to iTunes connen, it receives such an email

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by tjanela** [comment]
We have #4439, which addresses this, waiting for approval.
Please support the urgency of this by reacting to the first comment.
Thank you!

**Comment by Gordon2780** [comment]
> We have #4439, which addresses this, waiting for approval.
> Please support the urgency of this by reacting to the first comment.
> Thank you!

Do you need me to delete the file that references uiwebview and upload it again?

**Comment by tjanela** [comment]
@Gordon2780 I’m afraid I don’t understand your question. What file are you referring to?

**Comment by Gordon2780** [comment]
> @ Gordon2780恐怕我听不懂你的问题。您指的是什么文件？

**Comment by Gordon2780** [comment]
> @Gordon2780 I’m afraid I don’t understand your question. What file are you referring to?

I'm trying #4439 to repair the project using and upload iTunes connect again, Thank you!

**Comment by tjanela** [comment]
That should do the trick but is a very bad approach. You’d be better off pointing the pod to the branch of the PR #4439 and submit a version that uses that repo instead. We plan to keep that fork available at least until the PR is merged and a new release of AFNetworking is released. Alternatively you can fork the #4439 repo blissapps/AFNetworking and go from there.

**Comment by Gordon2780** [comment]
> That should do the trick but is a very bad approach. You’d be better off pointing the pod to the branch of the PR #4439 and submit a version that uses that repo instead. We plan to keep that fork available at least until the PR is merged and a new release of AFNetworking is released. Alternatively you can fork the #4439 repo blissapps/AFNetworking and go from there.

I want to use a branch, but I don't know how to use it

**Comment by tjanela** [comment]
I understand. This is not the forum to explain those things, though. I recommend you read some basic level tutorials on git and cocoapods.
Those should get you started.
If you lack the time learn these things then stick with your proposed approach, deleting the files and resubmitting, knowing that problems will arise at a later time, especially if you have multiple team members working in the project and you are not pushing the Pods folder to source control.

**Comment by Gordon2780** [comment]
> I understand. This is not the forum to explain those things, though. I recommend you read some basic level tutorials on git and cocoapods.
> Those should get you started.
> If you lack the time to learn these things then stick with your proposed approach, deleting the files and resubmitting, knowing that problems will arise at a later time, especially if you have multiple team members working in the project and you are not pushing the Pods folder to source control.

OK thank you

**Comment by jacekdogiel** [comment]
@Gordon2780  add it to your Podfile:
pod 'AFNetworking', :git => 'https://github.com/blissapps/AFNetworking', :branch => 'feature/WKWebView'
