### ISSUE TITLE
Deprecated UIWebview Pod dependency issue

### ISSUE THREAD

**Issue by DebasmitaBCT** [AFNetworking/AFNetworking#4468]
We are building an app that uses AFNetworking 3.2.1 as a pod dependency. As we tried to submit the app in App Store for review, Apple says:

**" We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . "**

AFNetworking has a dependency on UIWebView which is deprecated. Any plan to remove this dependency?

Thanks for this excellent library!

**Comment by rodmytro** [comment]
There is already an issue #4428 and fix #4439.

It seems like #4439 will be in the new version: https://github.com/AFNetworking/AFNetworking/pull/4430#issuecomment-544321511

**Comment by dbolak** [comment]
Any timing estimate on the new version that will remove the UIWebView dependency ?

**Comment by JuhaO81** [comment]
When do we get the release?

**Comment by dmitry-kovba** [comment]
Any updates?

**Comment by daliadanila** [comment]
Do we have an idea about when the new release might be out, please?

**Comment by FTyouth** [comment]
waitting release

**Comment by JuhaO81** [comment]
When does the release come out?

**Comment by Alexookah** [comment]
any release?

**Comment by veerag-dev** [comment]
any new release from AFNetworking which replaced UIWebView with WKWebView ? please let me know . thank you

**Comment by SurendraK11** [comment]
Hi there,

is there any update for further release to resolve the issue **"Deprecated UIWebview"**

Thank you

**Comment by PaoloDozio** [comment]
I'm waiting also me to an update for "Deprecated UIWebview"..
Let us know..
Thanks..

**Comment by trapper-** [comment]
fyi all, until the pod is updated you can force it to use the latest git version by changing your Podfile line for AFNetworking to 
`pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking'`

**Comment by dmitry-kovba** [comment]
Is the project dead?

**Comment by valentinptc** [comment]
Any updates?

**Comment by ElfSundae** [comment]
You may like to try my fork: https://github.com/ElfSundae/AFNetworking/issues/1

**Comment by daiki1003** [comment]
I'm waiting any updates too...

**Comment by pShota** [comment]
i have to say this become urgent in my production release, any update guys???

**Comment by sachitasahu** [comment]
I'm waiting for an update on "Deprecated UIWebview". When do we get the release?

**Comment by gapoj** [comment]
I am waiting for this update too any news? do we have an ETA of when the fix will be released?

**Comment by artud2000** [comment]
Same we are waiting for this update as well

**Comment by tjanela** [comment]
Take a look at #4439

**Comment by Kaspik** [comment]
Updated, released. Can be closed.

**Comment by sachitasahu** [comment]
CocoaPods could not find compatible versions for pod "AFNetworking":
 In Podfile:AFNetworking (~> 4.0)

**Comment by Kaspik** [comment]
`pod 'AFNetworking', '~> 4.0.0'`

Also make sure your repo is up-to-date and ideally uses CocoaPods CDN.

If your problem persists, paste your podfile here.

**Comment by xhidnoda** [comment]
I put in podfile:
````
pod 'AFNetworking', '~> 4.0.1'
````

But it fail:

````
[!] CocoaPods could not find compatible versions for pod "AFNetworking":
  In snapshot (Podfile.lock):
    AFNetworking (= 3.2.1, ~> 3.0)

  In Podfile:
    AFNetworking (~> 4.0.1)

Specs satisfying the `AFNetworking (~> 4.0.1), AFNetworking (= 3.2.1, ~> 3.0)` dependency were found, but they required a higher minimum deployment target.

````
**How can i resolve this?**

**Comment by jshier** [comment]
Do what the error says: up your minimum deployment target. It is now iOS 9 for AFNetworking.

**Comment by xhidnoda** [comment]
In my project `deployment target says: iOS 11`, and in Pods iOS `deployment target says: 10` . 
What else can be?

**Comment by jshier** [comment]
The deployment target of your Podfile.

**Comment by jshier** [comment]
Looks like you may have other dependencies using an older version of AFNetworking. You could also try `pod update` to ensure you're on the latest versions.

**Comment by xhidnoda** [comment]
On top of my PodFile:
`platform :ios, '10.0'`

**Comment by xhidnoda** [comment]
> Looks like you may have other dependencies using an older version of AFNetworking. You could also try `pod update` to ensure you're on the latest versions.

Ok I will check and send a feedback...thanks

**Comment by xhidnoda** [comment]
And yep....i use `ImageSlideshow/AFURL` wich use older version `AFNetworking`. So i remove ImageSlideshow/AFURL.
Now works just fine.... thanks! @jshier

**Comment by rasmita12** [comment]
After Updating pod 4.0.4 getting below error. please help
No visible @interface for 'AFHTTPSessionManager' declares the selector 'GET:parameters:progress:success:failure:'

**Comment by Kaspik** [comment]
> After Updating pod 4.0.0 getting below error. please help
> No visible @interface for 'AFHTTPSessionManager' declares the selector 'GET:parameters:progress:success:failure:'

Please don't comment on closed issue with unrelated posts.
Use new API `GET:parameters:headers:progress:success:failure:`.

**Comment by rasmita12** [comment]
> > After Updating pod 4.0.0 getting below error. please help
> > No visible @interface for 'AFHTTPSessionManager' declares the selector 'GET:parameters:progress:success:failure:'
> 
> @rasmita12
> Please don't comment on closed issue with unrelated posts.
> Use new API `GET:parameters:headers:progress:success:failure:`.

Hey, I used this way - (NSURLSessionDataTask *)GET:(NSString *)URLString parameters:(id)param progress:(NECBProgress)progress success:(NECBSucess)success failure:(NECBFailure)failure {
    return [self.manager GET:URLString parameters:param headers:nil progress:^(NSProgress *downloadProgress). Error went and everything is working fine excluding weather forecast.

**Comment by tiffanym19** [comment]
already upgrade to 4.0.0, still UIWebView is there hmmm.... please help me can't upload to testflight

**Comment by Kaspik** [comment]
UIWebView is not part of 4.0.0 - your upgrade didn't go as expected. Uninstall and reinstall pods.

**Comment by tiffanym19** [comment]
![Screen Shot 2021-08-04 at 5 48 43 PM](https://user-images.githubusercontent.com/50227625/128160698-e67d6cd8-e8f1-409f-9613-771028719128.png)
yeah thats so very weird since I already uninstall and install the pods

**Comment by Kaspik** [comment]
In the search you can see it's from svgcom.xcworkspace, not from AFNetworking.

**Comment by tiffanym19** [comment]
ow I knew it I'm so blind I need to delete this file though hmmmmm... thank you <3
