### ISSUE TITLE
no longer supported  "application/octet-stream"

### ISSUE THREAD

**Issue by leijmin** [AFNetworking/AFNetworking#4471]
![image](https://user-images.githubusercontent.com/16099177/68019604-37739280-fcd7-11e9-9a11-69ee867347ae.png)
iOS 13 release notes no longer support application/octet-stream 。
Our application has a part of the image Content-type type is ‘application/octet-stream‘，
Loading images using setImageWithURL:placeholderImage will fail

**Comment by mathocosta** [comment]
In case someone has the same problem, here's a solution that worked for me:

```swift
let imageSerializer = AFImageResponseSerializer()
imageSerializer.acceptableContentTypes?.insert("application/octet-stream")
UIImageView.sharedImageDownloader().sessionManager.responseSerializer = imageSerializer
```
Then, call the method `setImageWithURL:placeholderImage:success:failure` normally.
