### ISSUE TITLE
Xcode iOS下Deployment 勾选Mac时集成报错

### ISSUE THREAD

**Issue by 13718004742** [AFNetworking/AFNetworking#4478]
<img width="435" alt="截屏2019-11-22下午2 09 40" src="https://user-images.githubusercontent.com/25925248/69401935-5d69e100-0d31-11ea-99a0-9f18383e4384.png">
<img width="623" alt="截屏2019-11-22下午2 10 00" src="https://user-images.githubusercontent.com/25925248/69401949-68247600-0d31-11ea-94e8-4e91806bfbac.png">

**Comment by f4st** [comment]
This is known issue with macOS Catalina.
Try PR#4418 (https://github.com/AFNetworking/AFNetworking/pull/4418)
