### ISSUE TITLE
version change

### ISSUE THREAD

**Issue by ccworld1000** [AFNetworking/AFNetworking#4480]
<img width="518" alt="ABA94415-0BA3-400C-9104-26DE9B4E8B71" src="https://user-images.githubusercontent.com/22360168/69719349-42d9a280-114b-11ea-88bf-036695b094af.png">

Why is the main version changed from 3 to 2 ?

**Comment by kinarobin** [comment]
There are just different branch, right ?

**Comment by ccworld1000** [comment]
The above is tag

**Comment by kinarobin** [comment]
2.x branch -> 2.7.0 tag ->  Release 2.7.0
3.x branch -> 3.2.1 tag ->  Release 3.2.1
