### ISSUE TITLE
Apple just complained about use of UIWebview...

### ISSUE THREAD

**Issue by luckychris** [AFNetworking/AFNetworking#4487]
I just did upload my app and got this from Apple:

We identified one or more issues with a recent delivery for your app .... Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Question: will you update AFNetworking in that way, it does not use UIWebview?

**Comment by moonagic** [comment]
We got the same notice today

**Comment by lihaojie** [comment]
me too ！

**Comment by RWarnecke** [comment]
I had the same notice. But the review for my app was passed by apple and its now in the apple App Store. Here are some issues and pull request for this message.

**Comment by NasH5169** [comment]
Hi all,

For now, i've forked the repo. Clone your fork, create a fix/uiwebview branch.

Then just remove all the references of UIWebView.

Finally, change the pod dependency:

`pod 'AFNetworking', :git => 'https://github.com/YourName/AFNetworking.git', :branch => 'fix/uiwebview'`

**Comment by juanrafernandez** [comment]
the same

**Comment by tfy87happy** [comment]
the same

**Comment by mqlsq** [comment]
the same

**Comment by JimmyAdler** [comment]
This is fixed in ticket #4439 but not released yet, appears that it will not be included until 4.x release.

**Comment by liujunliuhong** [comment]
```
  pod 'AFNetworking/Serialization'
  pod 'AFNetworking/Security'
  pod 'AFNetworking/Reachability'
  pod 'AFNetworking/NSURLSession'
```

**Comment by luckychris** [comment]
ok, i did what Nash recommended.

you can get this here: https://github.com/luckychris/AFNetworking

**Comment by tjanela** [comment]
Take a look at #4439

**Comment by Kaspik** [comment]
Updated, released. Can be closed.
