### ISSUE TITLE
有个神奇的问题

### ISSUE THREAD

**Issue by hw20101101** [AFNetworking/AFNetworking#4488]
1.我使用 `AFNetworking` 来请求一个由本地 Apache + PHP 搭建的 API URL ，
代码如下：

   ```
    NSString *url = @"http://restful/index.php/1.0/users/register";
    NSDictionary *dict = @{@"username": @"hw", @"password": @"faf"};
    
    AFHTTPSessionManager *sessionManager = [AFHTTPSessionManager manager];
    sessionManager.requestSerializer = [AFJSONRequestSerializer serializer];
    sessionManager.responseSerializer = [AFHTTPResponseSerializer serializer];
    [sessionManager POST:url parameters:dict progress:^(NSProgress * _Nonnull uploadProgress) {

    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        
        id json = [NSJSONSerialization JSONObjectWithData:responseObject options:NSJSONReadingMutableContainers error:nil];
        NSLog(@"-->> responseObject:%@", json);
 
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@"-->> error:%@", error.userInfo);
    }];
```
 
运行 App 之后 Xcode 控制台输出 json为 null。抓包截图如下：
<img width="590" alt="屏幕快照 2019-12-11 上午11 34 22" src="https://user-images.githubusercontent.com/9107226/70589247-399c0b80-1c0a-11ea-882a-c04e09c163b7.png">

---

2.修改 URL 为 `http://ywj.aaa.net/index.php/goods` （另一个项目，远程 Apache + PHP 搭建），再次运行 App ，此时 Xcode 控制台输出 json 正常。抓包截图如下：

<img width="627" alt="屏幕快照 2019-12-11 上午10 37 02" src="https://user-images.githubusercontent.com/9107226/70589288-53d5e980-1c0a-11ea-8d1f-dd914eccb7df.png">

---

3.修改 URL 为 `http://restful/index.php/1.0/users/register` 之后再次运行 App，此时 Xcode 控制台输出 json 正常，请问这是什么情况？

**Comment by zanyfly** [comment]
这种问题不要提issue
