### ISSUE TITLE
 Updating Apps that Use Web Views

### ISSUE THREAD

**Issue by MrCaiWH** [AFNetworking/AFNetworking#4490]
[Updating Apps that Use Web Views](https://developer.apple.com/news/?id=12232019b)

**Comment by liujunliuhong** [comment]
you can try:
```
  pod 'AFNetworking/Serialization'
  pod 'AFNetworking/Security'
  pod 'AFNetworking/Reachability'
  pod 'AFNetworking/NSURLSession'
```

**Comment by ywx372421496** [comment]
希望能更新下

**Comment by ywx372421496** [comment]
I hope it can be updated

**Comment by ywx372421496** [comment]
如果您的应用仍使用不推荐使用的UIWebView API嵌入网络内容，我们强烈建议您尽快更新到WKWebView，以提高安全性和可靠性。WKWebView通过将Web处理限制在应用程序的Web视图中，确保受损的Web内容不会影响应用程序的其余部分。iOS和macOS以及Mac Catalyst都支持它。

自2020年4月起，App Store将不再接受使用UIWebView的新应用程序，而自2020年12月起将不再接受使用UIWebView的应用程序更新。

**Comment by tfy87happy** [comment]
希望能更新下

**Comment by Ad1991** [comment]
Duplicate of #4428

**Comment by funnel20** [comment]
Duplicate of #4428, please close.

**Comment by tjanela** [comment]
Take a look at #4439

**Comment by Kaspik** [comment]
Updated, released. Can be closed.

**Comment by ywx372421496** [comment]
666
