### ISSUE TITLE
UIWebView+AFNetworking

### ISSUE THREAD

**Issue by XianRong** [AFNetworking/AFNetworking#4495]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by tfy87happy** [comment]
the same

**Comment by lailibo8** [comment]
the same

**Comment by SuiTang** [comment]
the same

**Comment by wangjin007** [comment]
the same , please change thanks

**Comment by Ad1991** [comment]
Duplicate of #4428

**Comment by luckychris** [comment]
i deleted the dependeny. You can download here if you want: https://github.com/luckychris/AFNetworking
