### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs。

### ISSUE THREAD

**Issue by Yosemite0915** [AFNetworking/AFNetworking#4500]
Apple will stop accepting submissions of apps that use UIWebView APIs。

**Comment by Ad1991** [comment]
Duplicate of #4428

**Comment by luckychris** [comment]
you can download here without dependency, if you want: https://github.com/luckychris/AFNetworking

**Comment by revg75** [comment]
Thanks bro.
