### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs  + AFNetworking. 

### ISSUE THREAD

**Issue by kiranSDM** [AFNetworking/AFNetworking#4502]
After Updating version 3.0 Still, UIWebView used in the AFNetworking framework. Apple sends the mail regarding  identified one or more issues with a recent delivery for your app, 

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Please update your framework according to apple warning.
![Screen Shot 2020-01-16 at 6 37 19 PM](https://user-images.githubusercontent.com/15884444/72527708-62f62a00-388f-11ea-9811-748b6a29d48a.png)
![Screen Shot 2020-01-16 at 6 36 44 PM](https://user-images.githubusercontent.com/15884444/72527710-62f62a00-388f-11ea-8b29-13b6fe8e1d0e.png)

**Comment by LinkedHK** [comment]
@kiranSDM 
https://github.com/AFNetworking/AFNetworking/pull/4439

**Comment by zhenhuamu** [comment]
> After Updating version 3.0 Still, UIWebView used in the AFNetworking framework. Apple sends the mail regarding identified one or more issues with a recent delivery for your app,
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> Please update your framework according to apple warning.
> ![Screen Shot 2020-01-16 at 6 37 19 PM](https://user-images.githubusercontent.com/15884444/72527708-62f62a00-388f-11ea-9811-748b6a29d48a.png)
> ![Screen Shot 2020-01-16 at 6 36 44 PM](https://user-images.githubusercontent.com/15884444/72527710-62f62a00-388f-11ea-8b29-13b6fe8e1d0e.png)

  pod 'AFNetworking/NSURLSession', '3.2.1'
  pod 'AFNetworking/Reachability', '3.2.1'
  pod 'AFNetworking/Security', '3.2.1'
  pod 'AFNetworking/Serialization', '3.2.1'
可以暂时这样去解决，如果你没有使用AFNetworking/UIKit

**Comment by zhenian** [comment]
@kylef  @SlaunchaMan  @cnoon @conradev 

can you fix this issues ?

**Comment by smarciel** [comment]
Hi!
when will be this issue fixed?

**Comment by hahaGitHub** [comment]
Hi!
when will be this issue fixed?

**Comment by funnel20** [comment]
Duplicate of #4428

**Comment by tjanela** [comment]
Take a look at #4439

**Comment by Kaspik** [comment]
Updated, released. Can be closed.
