### ISSUE TITLE
Crash at AFURLSessionManager.m:248

### ISSUE THREAD

**Issue by MankiAnki** [AFNetworking/AFNetworking#4506]
On the test flight version I am always getting crash on this line, when I am using the xcode its not crashing, its so weird. 

This is a crash log from test flight
![Screen Shot 2020-01-27 at 16 58 41](https://user-images.githubusercontent.com/37077724/73190757-c0f3fe80-4126-11ea-9d3b-f30f8424b216.png)

**Comment by chenchao01** [comment]
Our app also find this error much on line with version 4.0.0
