### ISSUE TITLE
Non-public API usage (SecTrustEvaluate)

### ISSUE THREAD

**Issue by marcocattai** [AFNetworking/AFNetworking#4509]
We identified one or more issues with a recent delivery for your app, "xxxxxx" xxx (xxxx). Please correct the following issues, then upload again.
**ITMS-90338: Non-public API usage** - The app references non-public symbols in **Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking:** 

### **SecTrustEvaluate**

_SecCertificateCopyData, _SecCertificateCreateWithData, _SecPolicyCreateBasicX509, _SecPolicyCreateSSL, _SecTrustCopyPublicKey, _SecTrustCreateWithCertificates, 
_SecTrustEvaluate, _SecTrustGetCertificateAtIndex, _SecTrustGetCertificateCount, _SecTrustSetAnchorCertificates, _SecTrustSetPolicies,The app references non-public symbols in Contents/MacOS/Board Intelligence: _SecCertificateCreateWithData, _SecItemAdd, _SecItemCopyMatching, _SecItemDelete, _SecItemUpdate, _SecPolicyCreateBasicX509, _SecPolicyCreateSSL, _SecRandomCopyBytes, _SecTrustCopyPublicKey, _SecTrustCreateWithCertificates, _SecTrustEvaluate, _SecTrustSetPolicies.

 If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
Best regards,
The App Store Team

**Comment by jshier** [comment]
It's easy to verify that we aren't using any of those symbols, so I suggest you contact Apple.

**Comment by marcocattai** [comment]
AFSecurityPolicy.m

inside the method: **static id AFPublicKeyForCertificate(NSData *certificate) {**

- __Require_noErr_Quiet(SecTrustEvaluate(allowedTrust, &result), _out);

inside the method: **static BOOL AFServerTrustIsValid(SecTrustRef serverTrust) {**

- __Require_noErr_Quiet(SecTrustEvaluate(serverTrust, &result), _out);

inside the method: **static NSArray * AFPublicKeyTrustChainForServerTrust(SecTrustRef** serverTrust) {
__Require_noErr_Quiet(SecTrustEvaluate(trust, &result), _out);

I believe **This is why:**
OSStatus SecTrustEvaluate(SecTrustRef trust, SecTrustResultType *result)
 API_DEPRECATED_WITH_REPLACEMENT("SecTrustEvaluateWithError",
                                    macos(10.3, 10.15),
                                    ios(2.0, 13.0),
                                    watchos(1.0, 6.0),
                                    tvos(2.0, 13.0));

**Comment by jshier** [comment]
Why do you believe that usage would trigger that iTMS issue? Use of the deprecated API should just produce a warning, not prevent App Store submission. It seems clear that AFNetworking isn't using any private symbols in the list provided.
