### ISSUE TITLE
Non-public API usage (SecTrustEvaluate) API_DEPRECATED_WITH_REPLACEMENT

### ISSUE THREAD

**Issue by marcocattai** [AFNetworking/AFNetworking#4510]
> We identified one or more issues with a recent delivery for your app, "xxxxxx" xxx (xxxx). Please correct the following issues, then upload again.
> ITMS-90338: Non-public API usage - The app references non-public symbols in Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking:
> 

This happens only when I submit the **Mac Catalyst** APP

Only the Mac Catalina app has not been accepted. The library is trying to use a **API_DEPRECATED_WITH_REPLACEMENT** only on Mac Catalyst 13.0–13.0

OSStatus SecTrustEvaluate(SecTrustRef trust, SecTrustResultType *result)
**API_DEPRECATED_WITH_REPLACEMENT("SecTrustEvaluateWithError",**
macos(10.3, 10.15),
ios(2.0, 13.0),
watchos(1.0, 6.0),
tvos(2.0, 13.0));

SecTrustEvaluate is used Inside AFSecurityPolicy.m

**Comment by jshier** [comment]
As I posted in your other issue (please don't open duplicate issues):

Why do you believe that usage would trigger that iTMS issue? Use of the deprecated API should just produce a warning, not prevent App Store submission. It seems clear that AFNetworking isn't using any private symbols in the list provided. Alamofire 5 preview releases used the same deprecated API without issue.

**Comment by marcocattai** [comment]
> As I posted in your other issue (please don't open duplicate issues):
> 
> Why do you believe that usage would trigger that iTMS issue? Use of the deprecated API should just produce a warning, not prevent App Store submission. It seems clear that AFNetworking isn't using any private symbols in the list provided. Alamofire 5 preview releases used the same deprecated API without issue.

Thank you for your answer,

**SecTrustEvaluate** is not available on **Mac Catalyst 13.0–13.0** therefore on that platform or for iOS 12.0+, we should use SecTrustEvaluateWithError. 
When I submit the **Mac catalyst app** I believe that they automatically spot that AFNetworking library is using SecTrustEvaluate which is now treated like a private API on that platform only. the old api is still available on  iOS <= 11.0. SecTrustEvaluateWithError is available from iOS 12.0+ and Catalina

--->**API_DEPRECATED_WITH_REPLACEMENT**("SecTrustEvaluateWithError",
macos(10.3, 10.15),
ios(2.0, 13.0),
watchos(1.0, 6.0),
tvos(2.0, 13.0));

**Comment by jshier** [comment]
The API *is* available, otherwise you wouldn't be able to build with it at all. It's marked as deprecated, not unavailable. 

In any event, I'll try to integrate the Catalyst changes and get 3.4 out this weekend.

**Comment by marcocattai** [comment]
> The API _is_ available, otherwise you wouldn't be able to build with it at all. It's marked as deprecated, not unavailable.
> 
> In any event, I'll try to integrate the Catalyst changes and get 3.3 out this weekend.

**Comment by marcocattai** [comment]
> The API _is_ available, otherwise you wouldn't be able to build with it at all. It's marked as deprecated, not unavailable.
> 
> In any event, I'll try to integrate the Catalyst changes and get 3.3 out this weekend.

my bad - I close the issue bu mistake ...

**Comment by mmackh** [comment]
I'm also running into this issue with Catalyst - here's an email from Apple rejecting the binary:

We identified one or more issues with a recent delivery for your app, "[redacted]". Please correct the following issues, then upload again.

ITMS-90338: Non-public API usage - The app references non-public symbols in Contents/MacOS/InstaPDF: _SecCertificateCopyData, _SecCertificateCreateWithData, _SecPolicyCreateBasicX509, _SecPolicyCreateSSL, _SecTrustCopyPublicKey, _SecTrustCreateWithCertificates, _SecTrustEvaluate, _SecTrustGetCertificateAtIndex, _SecTrustGetCertificateCount, _SecTrustSetAnchorCertificates, _SecTrustSetPolicies. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by marcocattai** [comment]
> I'm also running into this issue with Catalyst - here's an email from Apple rejecting the binary:
> 
> We identified one or more issues with a recent delivery for your app, "[redacted]". Please correct the following issues, then upload again.
> 
> ITMS-90338: Non-public API usage - The app references non-public symbols in Contents/MacOS/[redacted]: _SecCertificateCopyData, _SecCertificateCreateWithData, _SecPolicyCreateBasicX509, _SecPolicyCreateSSL, _SecTrustCopyPublicKey, _SecTrustCreateWithCertificates, _SecTrustEvaluate, _SecTrustGetCertificateAtIndex, _SecTrustGetCertificateCount, _SecTrustSetAnchorCertificates, _SecTrustSetPolicies. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

you know what I don't understand ??? I fixed **SecTrustEvaluate** and on Mac Catalyst because it was not available for Mac Catalyst 13.0+. I am now using SecTrustEvluateWithError but Apple is being a bit silly. Below the list of the private Apple APIs Apple told me I am using . On the right I wrote their availability. They are not Private at all and they should be available for Catalyst. I will write them back. 

_SecCertificateCopyData,  (Available iOS 2.0+, Mac Catalyst 13.0+)
_SecCertificateCreateWithData, (Available iOS 2.0+, Mac Catalyst 13.0+)
_SecPolicyCreateBasicX509, (Available iOS 2.0+, Mac Catalyst 13.0+)
_SecPolicyCreateSSL, (Available iOS 2.0+, Mac Catalyst 13.0+)
_SecTrustCopyPublicKey, (Available iOS 2.0+, Mac Catalyst 13.0+)
_SecTrustCreateWithCertificates, (Available iOS 2.0+, Mac Catalyst 13.0+)
_SecTrustEvaluateWithError, (Available iOS 12.0+, Mac Catalyst 13.0+)
_SecTrustGetCertificateAtIndex, (Available iOS 2.0+, Mac Catalyst 13.0+)
_SecTrustGetCertificateCount, (Available iOS 2.0+, Mac Catalyst 13.0+)
_SecTrustSetAnchorCertificates, (Available iOS 2.0+, Mac Catalyst 13.0+)
_SecTrustSetPolicies (Available iOS 2.0+, Mac Catalyst 13.0+)

**Comment by mmackh** [comment]
I haven't had this issue before, the app has already been approved. Here's a relevant link from the Apple Developer Forum: https://forums.developer.apple.com/thread/129386 

Maybe a false alarm and something they need to fix on their end.

**Comment by marcocattai** [comment]
> I haven't had this issue before, the app has already been approved. Here's a relevant link from the Apple Developer Forum: https://forums.developer.apple.com/thread/129386
> 
> Maybe a false alarm and something they need to fix on their end.

Same here - our app is already in the store and we did not have this issue before - I contacted the app review team - waiting for their reply.

**Comment by marcocattai** [comment]
> I haven't had this issue before, the app has already been approved. Here's a relevant link from the Apple Developer Forum: https://forums.developer.apple.com/thread/129386
> 
> Maybe a false alarm and something they need to fix on their end.

@mmackh Did Apple get back to you? ... I am still waiting ...

**Comment by mmackh** [comment]
No, still an issue. Tried today and same result.

**Comment by mmackh** [comment]
@marcocattai Submitted a new build today and it got through. Finally! I think you can close this issue
