### ISSUE TITLE
Why AFNetwork’ s tag stays at 3.2.1 (05/04/2018)

### ISSUE THREAD

**Issue by wizardch** [AFNetworking/AFNetworking#4517]
Why AFNetwork’ s tag stays at 3.2.1 (05/04/2018), but the lastest commit is Jan 5, 2020.
Actually I hope to update AFNetworking by Cocoapod. When I executed 'pod search AFNetworking', I got the lastest versions is  3.2.1.

**Comment by ElfSundae** [comment]
A new version has not been released. You may specify repo url:
```ruby
pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking'
```

**Comment by ElfSundae** [comment]
See https://github.com/AFNetworking/AFNetworking/issues/4428

**Comment by wizardch** [comment]
@ElfSundae Thank you for your reply, I want to know whether it is the offical' s reply?  I still can't figure out why offical didn't release a new tag.

**Comment by ElfSundae** [comment]
not official.

**Comment by yanpanpan** [comment]
I hope to update AFNetworking release tags. I hope new official release tag.

**Comment by Kaspik** [comment]
Updated, released. Can be closed.
