### ISSUE TITLE
Please  Remove UIWebView APIs。 // UIWebView+AFNetworking

### ISSUE THREAD

**Issue by tc1993** [AFNetworking/AFNetworking#4518]
Your delivery was successful, but you may wish to correct the following issues in your next delivery:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
After you’ve corrected the issues, you can upload a new binary to App Store Connect.
Best regards,
The App Store Team

**Comment by ElfSundae** [comment]
https://github.com/AFNetworking/AFNetworking/issues/4428

**Comment by madmanLi** [comment]
Please Remove UIWebView APIs

**Comment by include11** [comment]
the same problem

**Comment by phannindra** [comment]
Also in the mail I got from Apple it says they won't be accepting this builds from April 2020. So can you fix it quickly.

**Comment by SergioZhydecky** [comment]
I have the same issue. Waiting for fix :) Thanks!

**Comment by whizpool** [comment]
please make it solve asap

**Comment by Usman4Github** [comment]
please make it solve asap. :)

**Comment by Usman4Github** [comment]
seems no harm in using @ElfSundae work. great work man.

**Comment by wangdacheng** [comment]
Please remove UIWebView APIs, thanks a lot. Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020.

**Comment by BaronWj** [comment]
the same problem！

**Comment by huynguyencong** [comment]
Now it is just a few days before Apple avoid updating app that has any UIWebView code in April 2020. So please remove UIWebView from AFNetworking. Thank you!

**Comment by jshier** [comment]
Apple stops accepting new apps with `UIWebView` in April. Apps can issue updates until December. This issue is tracked by #4428.
