### ISSUE TITLE
MobileCoreServices has been renamed. Use CoreServices instead.

### ISSUE THREAD

**Issue by pirocso** [AFNetworking/AFNetworking#4520]
With Xcode 11.4, we get the following warning:
MobileCoreServices has been renamed. Use CoreServices instead.

**Comment by jshier** [comment]
Under what configuration are you seeing this warning? I can't get it to trigger for any AFNetworking target.

**Comment by Kaspik** [comment]
It's when you bundle AFNetworking to project. Needs to be updated in podspec.

**Comment by raid5** [comment]
Will this fix be applied to the 3.x line?

**Comment by ElfSundae** [comment]
@raid5 3.x may not be supported anymore, UIWebView in 3.x has been replaced with WKWebView in 4.x, for App Store distribution, you should update your AFNetworking dependency to 4.x.
