### ISSUE TITLE
CDN timeouts

### ISSUE THREAD

**Issue by dan-ryan** [AFNetworking/AFNetworking#4534]
I'm trying to update the pod to version 4.0 but getting timeout issues:

`[!] CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/7/5/AFNetworking/4.0.0/AFNetworking.podspec.json Response: Timeout was reached
`

**Comment by jshier** [comment]
Sorry, sometimes this happens. Only thing to do is to check your connection and settings and try again later. If it happens to be a longer term issue, I suggest you file an issue with CocoaPods.

**Comment by dan-ryan** [comment]
Happening for hours, and is still happening. I don't think it has anything to do with my connection. 
The URL causing trouble is githubusercontent.com; it might be a Github issue. I'll try again tomorrow...
