### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by BlankConan** [AFNetworking/AFNetworking#4540]
## What happened instead?

Dyld Error Message:
  Library not loaded: @rpath/AFNetworking.framework/Versions/A/AFNetworking
  Referenced from: /Applications/Nipaiyi.app/Contents/MacOS/Nipaiyi
  Reason: image not found

## AFNetworking Environment

**AFNetworking version:** 3.2.1
**Xcode version:** 11.3
**Swift version:** 
**Platform(s) running AFNetworking:** macos
**macOS version running Xcode:** Mac OS X 10.10.1 (14B25)

d that reproduces the issue.

**Comment by shshlomi** [comment]
same issue here

**Comment by zj381652512** [comment]
dyld: Library not loaded: /System/Library/Frameworks/CoreServices.framework/CoreServices
  Referenced from: /Users/labwe/Library/Developer/CoreSimulator/Devices/C7EBD99A-7245-43AE-B395-EE1F9AF5E6B9/data/Containers/Bundle/Application/63382FB1-1A6E-4D80-9C7D-485206648E6C/SchoolManger.app/Frameworks/AFNetworking.framework/AFNetworking
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/CoreServices.framework/CoreServices: mach-o, but not built for iOS simulator
dyld: launch, loading dependent libraries
DYLD_FRAMEWORK_PATH=/Users/labwe/Library/Developer/Xcode/DerivedData/SchoolManger-biwtlqqizwyxgybwsyrxgdzqfxfb/Build/Products/Debug-iphonesimulator
DYLD_FALLBACK_LIBRARY_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.4.simruntime/Contents/Resources/RuntimeRoot
DYLD_FALLBACK_FRAMEWORK_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks
DYLD_INSERT_LIBRARIES=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.4.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
DYLD_LIBRARY_PATH=/Users/labwe/Library/Developer/Xcode/DerivedData/Schoo
