### ISSUE TITLE
Crashed!

### ISSUE THREAD

**Issue by KorolZhu** [AFNetworking/AFNetworking#4541]
![企业微信截图_d94dbd4a-d384-4388-bb95-69a82e534254](https://user-images.githubusercontent.com/1926639/78331498-bc314800-75b8-11ea-8dd4-10f44a17b60a.png)

 [__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]' 

serverTrust is nil

**Comment by Kaspik** [comment]
Following, new crash on latest AFNetworking 4.0.0.

@jshier Worth fixing and releasing 4.0.1 with all the changes on master?

**Comment by Kaspik** [comment]
Still an issue waiting for merge.

**Comment by Kaspik** [comment]
Can be closed.

**Comment by jshier** [comment]
Fix released in 4.0.1.
