### ISSUE TITLE
Migration Guides no longer exist?

### ISSUE THREAD

**Issue by michaeldclifford** [AFNetworking/AFNetworking#4543]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/AFNetworking/AFNetworking/blob/master/CONTRIBUTING.md).

## What did you do?

Clicked the link in [Release 3.0.0](https://github.com/AFNetworking/AFNetworking/releases/tag/3.0.0) to go to the [Migration Guide](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide).

## What did you expect to happen?

That it would open the Migration Guide page.

## What happened instead?

It redirects to the [repo homepage](https://github.com/AFNetworking/AFNetworking) and the Wiki appears to be inaccessible.

**Comment by Kaspik** [comment]
@jshier It looks like our whole "WiKi" is not available anymore. Did anyone disable that module?

**Comment by jshier** [comment]
Yes, I didn't realize it was being used. It has been reenabled.

**Comment by michaeldclifford** [comment]
Thank you
