### ISSUE TITLE
Warning: MobileCoreServices has been renamed

### ISSUE THREAD

**Issue by futuretap** [AFNetworking/AFNetworking#4544]
When integrated via Cocoapods, Xcode 11.4 displays a compiler warning:

> MobileCoreServices has been renamed. Use CoreServices instead.

## AFNetworking Environment

**AFNetworking version: 4.0.0**
**Xcode version: 11.4 (11E146)**
**Platform(s) running AFNetworking: iOS 13.4, deployment target iOS 11.0**

Podfile options used:

```
use_frameworks!
inhibit_all_warnings!
```

**Comment by jshier** [comment]
This has been fixed on `master` and will go out as part of 4.0.1.

**Comment by raid5** [comment]
Will this fix be applied to the 3.x line?
