### ISSUE TITLE
How to use headers in 4.0?

### ISSUE THREAD

**Issue by pc23pankaj** [AFNetworking/AFNetworking#4545]
Earlier for passing headers we have to do.

[manager.requestSerializer setValue:@"ApiToken" forHTTPHeaderField:@"Authorization"];

Want to know now what have to pass in our POST method for headers

I am doing this but not getting any success 
 NSMutableDictionary *headers = [[NSMutableDictionary alloc]init];
            [headers setValue:@"ApiToken"  forKey:@"Authorization"];
[manager POST:[NSURL URLWithString:path].absoluteString parameters:parameter headers:headers progress:nil success:^(NSURLSessionTask *task, id responseObject)
             {
}

Please provide any solution for this.

**Comment by TheLittleBoy** [comment]
Maybe you set it twice.

**Comment by jshier** [comment]
The new API allows you to set header for a particular task, in addition to the headers set by the serializer (pending the fix in behavior in #4550). So in general, any headers you want in **all tasks**, set on the serializer, while any headers you want **a particular task**, pass to the method.
