### ISSUE TITLE
4.0.0 请求headers的添加方式导致的问题

### ISSUE THREAD

**Issue by xygkevin** [AFNetworking/AFNetworking#4549]
1、在旧的版本中，设置请求头的方式是单独的方法，调用AFHTTPRequestSerializer下的
- (void)setValue:(nullable NSString *)value forHTTPHeaderField:(NSString *)field;
然后通过[mutableRequest setValue:value forHTTPHeaderField:field]进行设置；

2、在4.0.0方法中通过参数headers的方式，调用的是[mutableRequest addValue:value forHTTPHeaderField:field]进行设置；

3、mutableRequest的add方法， 会直接拼接原有的值，而并不会检查原有值是否包含新值，这样导致服务端在处理时发生错误；（比如我要设置Content-Type = application/json，在服务端收到的是Content-Type = application/json,application/json；导致错误，这是我最近遇到的问题）

4、不知道AFNetworking是否清楚上述区别，还是有意在新版本中使用的add方法？？？还希望多多指教一二

**Comment by ElfSundae** [comment]
"Setting headers per request" 功能是在 https://github.com/AFNetworking/AFNetworking/pull/4113 引入的，当时没讨论用 `addValue` 还是 `setValue`。
我个人认为应该用 `setValue` overwrite 而不是 append。
但是一般情况下用 `addVaue` 也不会有问题。HTTPSessionManager 设计的是一个 manager 对应一个 requestSerializer，也就是一个 manager 只处理 _一种_ 请求类型。requestSerializer 中设置的公共头，是标志 request「种类」的一部分。在单个请求中不需要重写公共头，单个请求中只是添加本次请求的自定义（非公共）头。如果需要设置不同的公共头，Content-Type，User-Agent 等，更好的做法是创建新的 HTTPSessionManager 并设置不同的 requestSerializer。

**Comment by xygkevin** [comment]
感谢您的解答！

**Comment by ElfSundae** [comment]
@xygkevin `4.0.1` 已修复此问题。
