### ISSUE TITLE
关于数据请求参数的类型问题

### ISSUE THREAD

**Issue by xygkevin** [AFNetworking/AFNetworking#4556]
一般情况下的数据请求传入的parameter都是NSDictionary类型的对象，
但是目前很多项目出于安全原因parameter要求采用加密过的NSString对象，
此时就会提示  The `parameters` argument is not valid JSON 的异常，
我查找了已关闭的Issues中有类似的提问，但是由于长时间没有回应被自动关闭了，

我个人认为在设置_sessionManager.requestSerializer = [AFJSONRequestSerializer serializer]的情况下parameter类型是NSString对象也是可以被接受的；

不知道是否是AFNetworking在出于别的原因一直没有优化这个问题呢？
还望多多指教。

**Comment by TheLittleBoy** [comment]
你可以给你加密的string一个key，不就可以组成NSDictionary了嘛。标准的json不能只写一个string，否则，你就不要用AFJSONRequestSerializer。
