### ISSUE TITLE
Content-Type  application/json 的问题

### ISSUE THREAD

**Issue by BlueStormLSS** [AFNetworking/AFNetworking#4558]
AFNetworking 4.0问题
AFURLRequestSerialization.m  1259行，如果不是GET，HEADER，DELETE，会set Content-Type
然而AFHTTPSessionManager.m 264行，会继续 add HTTPHeaderField,采用的是 [request addValue:headers[headerField] forHTTPHeaderField:headerField];
使得"Content-Type" = "application/json,application/json";

因此可能会导致服务器返回错误
{
	success = 0,
	message = Invalid mime type "application/json,application/json": Invalid token character ',' in token "json,application/json",
	data = <null>,
	errCode = 500
}
此时有两种解决方案，
1、AFHTTPSessionManager.m 264行 用 [request setValue:headers[headerField] forHTTPHeaderField:headerField]; 替换[request addValue:headers[headerField] forHTTPHeaderField:headerField];

2、使用3.版本请求头设置方法，header传nil

**Comment by MarcSteven** [comment]
If you translate it to English, it’s good for developers to fix it

**Comment by ElfSundae** [comment]
This has been fixed in [`4.0.1`](https://github.com/AFNetworking/AFNetworking/releases/tag/4.0.1)

**Comment by BlueStormLSS** [comment]
Thanks, I have updated to the latest version.
