### ISSUE TITLE
-[AFStreamingMultipartFormData appendPartWithFormData:name:]

### ISSUE THREAD

**Issue by Rxx9723** [AFNetworking/AFNetworking#4560]
I have issues for AFNetWorking 4.0.1
when use the class file  AFHTTPSessionManager POST:urlStr parameters:params headers:nil progress:^(NSProgress * _Nonnull uploadProgress) {...  
And then there's an error for *** Assertion failure in -[AFStreamingMultipartFormData appendPartWithFormData:name:], /Users/cmv/Desktop/Seen_Local/Seen/Pods/AFNetworking/AFNetworking/AFURLRequestSerialization.m:792

but In AFNetWorking 3.2.1  use the class file AFHTTPSessionManager POST:urlStr parameters:params progress:^(NSProgress * _Nonnull uploadProgress) { 
No error was reported during normal operation

so I don't know how to solve it 

Please help. Thanks.

**Comment by ElfSundae** [comment]
It seems your `params` is invalid, what is it?

**Comment by Rxx9723** [comment]
The parameters are the same as those used in version 3.2.0. And version 3.2.0 There is no such problem. The difference is in 4.0.1 POST:urlStr parameters:params headers:nil. I use 
+ (AFHTTPSessionManager *)sharedManager {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _manager = [AFHTTPSessionManager manager];
        _manager.requestSerializer = [AFHTTPRequestSerializer serializer];
        _manager.responseSerializer = [AFHTTPResponseSerializer serializer];
        _manager.requestSerializer.timeoutInterval = 20.f;
    });
    return _manager;
}
Then code  _manager = [self sharedManager]; [_manager POST:urlStr parameters:params headers:nil progress:^(NSProgress * _Nonnull uploadProgress) {

**Comment by Rxx9723** [comment]
The following picture is the crash information
<img width="895" alt="AEFD958D0515C67D6963C2BC14E60CC7" src="https://user-images.githubusercontent.com/18475686/80441443-81af9680-893d-11ea-9185-8873e8a2f9ac.png">
<img width="906" alt="9ED0A7E17EEE97009C990D0DBE59381D" src="https://user-images.githubusercontent.com/18475686/80441475-8d9b5880-893d-11ea-8b24-3aa636811830.png">
<img width="905" alt="79DC772E98646C0BFFD200E851C23974" src="https://user-images.githubusercontent.com/18475686/80441488-92f8a300-893d-11ea-830d-ac5a33f6b79b.png">
<img width="882" alt="CDCD7F5352C9A13E09142051EEBF491C" src="https://user-images.githubusercontent.com/18475686/80441500-9a1fb100-893d-11ea-9d57-66286643d22c.png">
The parameters and interfaces on the last picture are currently valid parameters

**Comment by ElfSundae** [comment]
What is the content of `params`?

**Comment by Rxx9723** [comment]
I am very, very sorry that I found the problem because I missed one layer of parameter judgment. I'm sorry to have temporarily used your resources

**Comment by ElfSundae** [comment]
It doesn't matter, then this issue can be closed?
