### ISSUE TITLE
Migration Guide 3.0 to 4.0 version

### ISSUE THREAD

**Issue by pajtimid** [AFNetworking/AFNetworking#4561]
Is any migration guid for 4.0 version.
Because I updated to 4.0 and I'm having many issues

**Comment by ElfSundae** [comment]
You may check out the CHANGELOG file.
Issues like what?

**Comment by pajtimid** [comment]
I solved them.
Get and post methods now have header, also dataTaskWithRequest has changed:
`[[manager dataTaskWithRequest:request uploadProgress:nil downloadProgress:nil completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
    }] resume];`
