### ISSUE TITLE
iOS not support uiwebview。please update

### ISSUE THREAD

**Issue by zengjialong** [AFNetworking/AFNetworking#4566]
iOS not support uiwebview。please update

**Comment by ElfSundae** [comment]
Use v4 instead.

**Comment by TongFangyuan** [comment]
Version 4.0 has removed uiwebview related code

**Comment by elaget** [comment]
Apple is rejecting apps using UIWebView instead of WKWebView. So if AFNetworking 2.x is still being used (which it is) this issue needs to be resolved.

**Comment by jshier** [comment]
AFNetworking 2 and 3 are no longer supported. If you want a supported version, use AFNetworking 4.
