### ISSUE TITLE
Dependency were found, but they required a higher minimum deployment target While pod install

### ISSUE THREAD

**Issue by akjesto** [AFNetworking/AFNetworking#4567]
I tried to update AFNetworking version to 4.0.But in my podfile already added AFOAuth2Manager.My pod file looks like the following

```
platform :ios, '10.0'
pod 'AFNetworking','~> 4.0.1'
pod 'AFOAuth2Manager','~> 3.0'
```
But when tried the command **pod install**,I got the following error on my terminal

![Screen Shot 2020-05-08 at 8 49 36 AM](https://user-images.githubusercontent.com/8862491/81367091-e15e2c80-9109-11ea-9ca5-8c4ad8f81f9f.png)

Please help me.How to solve this issue 

## AFNetworking Environment

**AFNetworking version:** 4.0.1
**Xcode version:** 11.3.1
**Platform(s) running AFNetworking:** iOS10.0,11.0,12.0,13.0
**macOS version running Xcode:** 10.15.3

**Comment by ElfSundae** [comment]
[AFOAuth2Manager](https://github.com/AFNetworking/AFOAuth2Manager/blob/master/AFOAuth2Manager.podspec) does not support AFNetworking v4 currently.

**Comment by ElfSundae** [comment]
If you want to install both AFNetworking v4 and AFOAuth2Manager, you may install my AFNetworking v3 fork which versioned v3 and merged v4 code: https://github.com/ElfSundae/AFNetworking/issues/1

Update your Podfile like this:

```ruby
pod 'AFNetworking', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
pod 'AFOAuth2Manager','~> 3.0'
```

**Comment by akjesto** [comment]
Thank you for the information.
Which is the stable version in AFNetworking manged UIWebview to WKWebview?
In my project need both **AFNetWorking**(with WKWebview) and **AFOAuth2Manager** libraries.

**Comment by ElfSundae** [comment]
AFNetworking 4.x removed UIWebView and added WKWebView.
AFOAuth2Manager specifies AFNetworking 3.x as a dependency, it can only be installed together with AFNetworking 3.x.

> If you want to install both AFNetworking v4 and AFOAuth2Manager, you may install my AFNetworking v3 fork which versioned v3 and merged v4 code: [ElfSundae#1](https://github.com/ElfSundae/AFNetworking/issues/1)
> 
> Update your Podfile like this:
> 
> ```ruby
> pod 'AFNetworking', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
> pod 'AFOAuth2Manager','~> 3.0'
> ```

**Comment by tropycool** [comment]
I'm using this solution, but now I can't do `pod install` or`pod update` because now show this error

`### Error

```
Pod::StandardError - [Bug] Failed to find known source with the URL "https://github.com/ElfSundae/CocoaPods-Specs.git"`

**Comment by ElfSundae** [comment]
@tropycool Retry after upgrading CocoaPods

**Comment by tropycool** [comment]
@ElfSundae I upgrade CocoaPods and works, thank you!

**Comment by kristinharkness** [comment]
It there going to be a real fix for this?
