### ISSUE TITLE
AFNetworkReachabilityManager's property "reachable" not accurate.

### ISSUE THREAD

**Issue by macro-c** [AFNetworking/AFNetworking#4570]
ℹ when i call AFNetworkReachabilityManager's property "reachable" to find out the current network status on my device, it will return NO, when that happend, my device's wifi and Cellular network’switch is on; 
then I find that property "networkReachabilityStatus" was init with value "AFNetworkReachabilityStatusUnknown", after a few mement it refresh to "AFNetworkReachabilityStatusReachableViaWiFi" by a block；

## What did you expect to happen?

ℹ in method 
`- (instancetype)initWithReachability:(SCNetworkReachabilityRef)reachability`,  
use the code below instead of init networkReachabilityStatus with AFNetworkReachabilityStatusUnknown;
    `SCNetworkReachabilityFlags flags;`
    `if (SCNetworkReachabilityGetFlags(self.networkReachability, &flags)) {`
            `self.networkReachabilityStatus = AFNetworkReachabilityStatusForFlags(flags);`
     `} else {`
             `self.networkReachabilityStatus = AFNetworkReachabilityStatusUnknown;`
     `}` 

if there is other concern about this issue, please let me know.

thanks

**Comment by ElfSundae** [comment]
You need to call `-startMonitoring` first.

**Comment by macro-c** [comment]
YES，i have call startMonitoring before use property networkReachabilityStatus.
i find that the block where refresh property networkReachabilityStatus is called after a few moment.

**Comment by ElfSundae** [comment]
Yes, it needs time to retrieve reachability status because of `SCNetworkReachabilityGetFlags`.
FYI https://developer.apple.com/library/archive/qa/qa1693/_index.html
> The System Configuration framework reachability API (<SystemConfiguration/SCNetworkReachability.h>) operates synchronously by default. Thus, seemingly innocuous routines like `SCNetworkReachabilityGetFlags` can get you killed by the watchdog. If you're using the reachability API, you should use it asynchronously.

**Comment by macro-c** [comment]
thanks, now i know why do not use `SCNetworkReachabilityGetFlags`;

under these circumstances, the method `- (BOOL)isReachable`  should be 
`self.networkReachabilityStatus != AFNetworkReachabilityStatusNotReachable` 
rather than `[self isReachableViaWWAN] || [self isReachableViaWiFi]`

**Comment by ElfSundae** [comment]
I don't think so, The current `-isReachable` is right and clear enough - returns `YES` only when the device is reachable.
It is a boolean type, and the initial (default) value is `NO`. Before the `SCNetworkReachabilityGetFlags` returns, it is still the initial value.

**Comment by macro-c** [comment]
thanks，i know everything about that.
i use `self.networkReachabilityStatus != AFNetworkReachabilityStatusNotReachable` on my situation，that just solve just my question.

**Comment by jshier** [comment]
This seems to have been resolved.
