### ISSUE TITLE
Replacing setTaskDidReceiveAuthenticationChallengeBlock when migrating to 4.0.0

### ISSUE THREAD

**Issue by mvolpato** [AFNetworking/AFNetworking#4573]
This line https://github.com/AFNetworking/AFNetworking/blob/5b20cbd09561fa14a701fac8aabbd289dc40ff75/AFNetworking/AFURLSessionManager.h#L319 refers to `setTaskDidReceiveAuthenticationChallengeBlock`, but this method [was removed in 4.0.0](https://github.com/AFNetworking/AFNetworking/commit/c9d06846ae7746498ca3aa5a74b86bdd7639ec3c#diff-883ce4b890154ec6c238ad2862675d6c).

The reason why it was removed is not clear to me.
I am using it with AFNetworking 3.2.1, but now I need to update to 4.0.0 to remove `UIWebView` from my app.

What other method can I use instead?

**Comment by ElfSundae** [comment]
Use `-setAuthenticationChallengeHandler` instead.

**Comment by jshier** [comment]
Fixed by #4574.
