### ISSUE TITLE
NSISOLatin1StringEncoding in AFURLResponseSerialization

### ISSUE THREAD

**Issue by smarciel** [AFNetworking/AFNetworking#4582]
## What did you do?
I've upgraded the AFNetworking version in my app from 2.7.0 version to 4.0.1. Everything works fine, but I'm having some issues with the serialize process of some JSON responses.
I've been doing some tests and this is what I have seen:

- All my WS JSON responses has the ISO-8859-1 encoding. 
- The ones with special characters in some JSON fields are giving me the following error:

`Error Domain=NSCocoaErrorDomain Code=3840 "Unable to convert data to string around character 1483." UserInfo={NSDebugDescription=Unable to convert data to string around character 1483.}
`
- This same URLs were just working fine with the 2.7.0 version of the library. 

I know this is a serialization problem and that the NSJSONSerialization class doesn't support the ISO-8859-1 encoding, but I have added the following two lines to the AFJSONResponseSerializer class and it has worked:

```
NSString *iso = [[NSString alloc] initWithData:data encoding:NSISOLatin1StringEncoding];
NSData *dutf8 = [iso dataUsingEncoding:NSUTF8StringEncoding];
```

Is there any chance to add this two lines to the AFJSONResponseSerializer class (I know there are several methods to do the serialization process) so the URLs with special characters in the JSON response won't fail?

Thanks in advance.

## AFNetworking Environment

**AFNetworking version:** 4.0.1
**Xcode version:** 11.5
**Platform(s) running AFNetworking:** iOS
**macOS version running Xcode:** Catalina 10.15.5

**Comment by jshier** [comment]
No, we will not be reencoding all of the data that flows through AFNetworking. Creating a custom serializer to do the transcoding for you is the appropriate solution, especially since anything but UTF-8 is against the JSON standard.
