### ISSUE TITLE
When you click to make a network request, you can quickly switch to another network request, and then the crash in the following picture will appear. What's the cause? Xcode doesn't print any error information.

### ISSUE THREAD

**Issue by ECUnion-HD** [AFNetworking/AFNetworking#4583]
**AFNetworking version:**
  - AFNetworking/NSURLSession (3.2.1):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (3.2.1)
  - AFNetworking/Security (3.2.1)
  - AFNetworking/Serialization (3.2.1)

**Xcode version:**
Version 11.4.1 (11E503a)

**Swift version:**
4.0

**Platform(s) running AFNetworking:**
Mac mini 

**macOS version running Xcode:**
10.15.4
![Pasted Graphic](https://user-images.githubusercontent.com/14834283/83841381-520d5e80-a733-11ea-8df9-7bb8a85d1fb7.png)
![Pasted Graphic](https://user-images.githubusercontent.com/14834283/83841724-fe4f4500-a733-11ea-987a-b981b28bb3da.png)

**Comment by ElfSundae** [comment]
`timeoutInterval` of `AFHTTPRequestSerializer` is not thead-safe, see https://github.com/AFNetworking/AFNetworking/issues/4580#issuecomment-639048688
