### ISSUE TITLE
The differences between NSURLSessionTaskDelegate with NSURLSessionDelegate about Cer

### ISSUE THREAD

**Issue by stackJolin** [AFNetworking/AFNetworking#4592]
The differences between NSURLSessionTaskDelegate with NSURLSessionDelegate about Cer:

NSURLSessionTaskDelegate:
![image](https://user-images.githubusercontent.com/14361098/84787625-cd6aec00-b020-11ea-9698-4ce63527799c.png)

and NSURLSessionDelegate:
![image](https://user-images.githubusercontent.com/14361098/84787706-e6739d00-b020-11ea-82c1-eb2935fad41b.png)

Why the method of Cer is different?

**Comment by jshier** [comment]
Each method is called for different reasons. You can read Apple's documentation for more info. [`URLSessionDelegate`](https://developer.apple.com/documentation/foundation/urlsessiondelegate/1409308-urlsession) and [`URLSessionTaskDelegate`](https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1411595-urlsession)
