### ISSUE TITLE
Certificate pinning failure Scenario 

### ISSUE THREAD

**Issue by Swapnali-Kulkarni** [AFNetworking/AFNetworking#4600]
HI,

I want to test the behaviour of my code for incorrect certificate.

just want to know what exact error code it gives when there is conflicts in certificate. so that i can handle it my code.

currently it gives me error code -999
but nothing is mentioned in the documents.

**currently using** 
AFNetworking version 2.7.0
Xcode Version : 11.1
Swift version not applicable, using objc
MacOS 10.15

**Comment by jshier** [comment]
You can get a more specific error in AFNetworking 4.
