### ISSUE TITLE
Migrate AFNetworkiong 2.6.3 to 4.0.1 with depedencies AFCSVResponseSerializer for new WKwebview 

### ISSUE THREAD

**Issue by jamesondavy** [AFNetworking/AFNetworking#4601]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/AFNetworking/AFNetworking/blob/master/CONTRIBUTING.md).

## What did you do?

I would like to update AFNetworking v 2.6.3 to 4.0.1 to migrate UIWebview to WKWebview on Xcode IOS.

## What did you expect to happen?

An update without problems when I made pod install  

## What happened instead?

I was error because I used lib AFCSVResponseSerializer on 2.6.3 AFNetworking.
But now it's not available with 4.0.1. Can I change this lib with an other ? 

If I comment pod AFCSVResponseSerializer I can install the version AFNetworking 4.0.1 else no but I use AFCSVResponseSerializer in my code.

## AFNetworking Environment

**AFNetworking version: 2.6.3. to 4.0.1
**Xcode version: 11.2.1
**Swift version:no available its objective c 
**Platform(s) running AFNetworking: iPhone or iPad
**macOS version running Xcode: no available for this problem

<img width="564" alt="Capture d’écran 2020-07-13 à 16 11 12" src="https://user-images.githubusercontent.com/2980279/87314571-b5a15d80-c523-11ea-991c-ac294765be45.png">

**Comment by ElfSundae** [comment]
- Ask the author of AFCSVResponseSerializer podspec to add support for AFNetworking 4.x
- Or publish a new `AFCSVResponseSerializer.podspec` to your private repo
- Or specify a local podspec path in your Podfile

The API of `AFURLResponseSerialization` protocol in 4.x is the same as in 2.x, so you can just update the AFNetworking dependency version in AFCSVResponseSerializer.podspec, no code needs to change.
