### ISSUE TITLE
Setting HTTP proxy in afn4.0 is invalid

### ISSUE THREAD

**Issue by lijianontheway** [AFNetworking/AFNetworking#4609]
Setting HTTP proxy in afn4.0 is invalid, but it is valid in afn3.0. I'd like to know about the settings in afn4.0.

NSURLSessionConfiguration * config =  [NSURLSessionConfiguration defaultSessionConfiguration];
    config.requestCachePolicy = NSURLRequestReloadIgnoringLocalCacheData;
    
    config.connectionProxyDictionary = @
    {
        @"HTTPEnable":@YES,
        (id)kCFStreamPropertyHTTPProxyHost:@"xxxxxxxxxx",
        (id)kCFStreamPropertyHTTPProxyPort:@80,
        @"HTTPSEnable":@YES,
        (id)kCFStreamPropertyHTTPSProxyHost:@"xxxxxxxxxxxxx",
        (id)kCFStreamPropertyHTTPSProxyPort:@443
    };

**Comment by DaivePan** [comment]
Hi，I find connectionProxyDictionary in apple NSURLSession class，and find kCFStreamPropertyHTTPProxyHost key description in <CFNetwork/CFHTTPStream.h>like this：
Discussion:
 *    Proxy dictionary key. The hostname of an HTTP proxy. The value is
 *    a CFString. The key name matches kSCPropNetProxiesHTTPProxy.
so you can try use kSCPropNetProxiesHTTPProxy replace kCFStreamPropertyHTTPProxyHost。

**Comment by lijianontheway** [comment]
> 嗨，我在Apple NSURLSession类中找到connectionProxyDictionary，并在<CFNetwork / CFHTTPStream.h>中找到kCFStreamPropertyHTTPProxyHost密钥描述，如下所示：
> 讨论：
> 
> * 代理字典密钥。HTTP代理的主机名。值是
> * CFString。密钥名称与kSCPropNetProxiesHTTPProxy相匹配。
>   因此您可以尝试使用kSCPropNetProxiesHTTPProxy替换kCFStreamPropertyHTTPProxyHost。

Thank you for your answer, but kSCPropNetProxiesHTTPProxy works only on MacOS, not IOS

**Comment by DaivePan** [comment]
> > 嗨，我在Apple NSURLSession类中找到connectionProxyDictionary，并在<CFNetwork / CFHTTPStream.h>中找到kCFStreamPropertyHTTPProxyHost密钥描述，如下所示：
> > 讨论：
> > 
> > * 代理字典密钥。HTTP代理的主机名。值是
> > * CFString。密钥名称与kSCPropNetProxiesHTTPProxy相匹配。
> >   因此您可以尝试使用kSCPropNetProxiesHTTPProxy替换kCFStreamPropertyHTTPProxyHost。
> 
> Thank you for your answer, but kSCPropNetProxiesHTTPProxy works only on MacOS, not IOS

you can try use @"HTTPProxy" replace kCFStreamPropertyHTTPProxyHost.

**Comment by jshier** [comment]
Proxies are handled at the `NSURLSession` level, AFNetworking doesn't have anything to do with it.
