### ISSUE TITLE
ITMS-90809 - App updates that use UIWebView will no longer be accepted as of December 2020. 

### ISSUE THREAD

**Issue by burkaslarry** [AFNetworking/AFNetworking#4611]
## What did you do?

I use AFNetworking to upload my app .

## What did you expect to happen?

No warning issues
 
## What happened instead?
 
Apple gives me the issues as follows 

ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

## Question: 

Would updating my AFNetworking can resolve this issue? Would WKWebView instead of UIWebView to be used ? 

## AFNetworking Environment

**AFNetworking version:** 3.2.1
**Xcode version:** 11.6
**Swift version:** 5.1
**Platform(s) running AFNetworking:**  IOS
**macOS version running Xcode:**  10.15.5

**Comment by jitendraIntesols** [comment]
I faced same issue, I have fixed. 

Use AFNetworking version 4.0 or higher
