### ISSUE TITLE
弱加密算法存在风险

### ISSUE THREAD

**Issue by Gang679** [AFNetworking/AFNetworking#4612]
SecCertificateCreateWithData 

   SecCertificateCopyData

  SecPolicyCreateBasicX509 

SecPolicyCreateSSL   

   SecTrustCopyPublicKey  

   SecTrustCreateWithCertificates   

  SecTrustEvaluate  

SecTrustGetCertificateCount  

SecTrustGetCertificateAtIndex 

  SecTrustSetAnchorCertificates  

SecTrustSetPolicies   

这几个方法存在一定风险

**Comment by hansong8675** [comment]
why?
