### ISSUE TITLE
CocoaPods could not find compatible versions for pod "AFNetworking

### ISSUE THREAD

**Issue by sheejasagar** [AFNetworking/AFNetworking#4615]
##  Dependency were found, but they required a higher minimum deployment target.

I have tried to update the AFNetworking version from 3.2.1 to 4.0.0, but it failed with the following error.

<img width="1053" alt="Error" src="https://user-images.githubusercontent.com/10396253/93048269-1e1fce80-f67c-11ea-930e-44d9b2321226.png">

## Pod File

My pod file is given below.
<img width="320" alt="pod" src="https://user-images.githubusercontent.com/10396253/93049042-d437e800-f67d-11ea-800b-28c1d4af8427.png">

## What did you do?

ℹ I have tried to update the AFNetworking version from 3.2.1 to 4.0.0.  

## What did you expect to happen?

ℹ The application will run without errors after updating AFNetworking framework.  

## What happened instead?

ℹ AFNetworking Updating failed with the following error.

<img width="1053" alt="Error" src="https://user-images.githubusercontent.com/10396253/93048269-1e1fce80-f67c-11ea-930e-44d9b2321226.png"> 

## AFNetworking Environment

**AFNetworking version:** 4.0.0
**Xcode version:** 11.5
**Swift version:** 4.0
**Platform(s) running AFNetworking:** iOS 13.5
**macOS version running Xcode:** 10.15.5

**Comment by nethergrim** [comment]
Liferay-iOS-SDK depends on AFNetworking v3. You're trying to use AFNetworking v4, which is incompatible with Liferay-iOS-SDK.

You should have to:
- ask Liferay to provide an updated SDK, which will depend on AFNetworking v4
- Check if there are any updates available
- If source code is open, you may fork it, and migrate manually.
