### ISSUE TITLE
Building for iOS Simulator, but the linked and embedded framework 'AFNetworking.framework' was built for iOS

### ISSUE THREAD

**Issue by SatishMavani** [AFNetworking/AFNetworking#4618]
## What did you do?
I updated my Xcode version to Xcode12.
I used Carthage to integrate the AFNetworking, everything was working fine until I updated my Xcode version from 11.7 to 12.
Now after updating to Xcode 12 when I am trying to run the **Carthage update --platform iOS** command it shows me an error(attached in screenshot).

## What did you expect to happen?
I expected that everything will work fine

## What happened instead?
I am not able to build my project and it shows me error(Building for iOS Simulator, but the linked and embedded framework 'AFNetworking.framework' was built for iOS) as shown in the screenshot.

## AFNetworking Environment

**AFNetworking version:** 3.2.1 and 4.0
**Xcode version:** 12
**Swift version:** 5.3
**Platform(s) running AFNetworking:** iOS
**macOS version running Xcode:** 10.15.6
<img width="1480" alt="Screenshot 2020-09-22 at 12 31 47" src="https://user-images.githubusercontent.com/16286115/93873870-bea46d00-fcd2-11ea-89aa-c118375d5a08.png">
<img width="482" alt="Screenshot 2020-09-22 at 12 52 43" src="https://user-images.githubusercontent.com/16286115/93873873-c06e3080-fcd2-11ea-85e5-e9f53c45270e.png">

**Comment by SatishMavani** [comment]
One of the [answers](https://developer.apple.com/forums/thread/130684) from dev forum's question says that it is something which needs to be fixed by 3rd party framework(AFNetworking)

**Comment by ElfSundae** [comment]
@SatishMavani See https://github.com/Carthage/Carthage/issues/3019

**Comment by warisappify** [comment]
Did you try this?

![JIgFb](https://user-images.githubusercontent.com/24873180/102222570-65309080-3f05-11eb-83d6-e8f453100d8c.png)

**Comment by jugos654** [comment]
warisappify works! 
Just curious - why this works?

**Comment by exeptionerror** [comment]
Here Is Already Solved with all possible solution added [Solved Xcode 12.3: Building for iOS Simulator, but the linked and embedded framework was built for iOS + iOS Simulator](https://exerror.com/xcode-12-3-building-for-ios-simulator-but-the-linked-and-embedded-framework-wa/)
