### ISSUE TITLE
I Pull requests but Refuse

### ISSUE THREAD

**Issue by DaivePan** [AFNetworking/AFNetworking#4634]
## What did you do?

I Pull requests Chinese readme，but Refuse For “The base branch restricts merging to authorized users.You’re not authorized to merge this pull request.”

## What did you expect to happen?

Pull requests success

**Comment by gwynantj** [comment]
@DaivePan only maintainers of this repo are allowed to merge pull requests.

**Comment by DaivePan** [comment]
> @DaivePan only maintainers of this repo are allowed to merge pull requests.


How to be a maintainer ? I want to be a maintainer.

**Comment by ElfSundae** [comment]
Thanks for your contribution. Don't worry, your pull request #4633 has been successfully submitted, and it will be merged or rejected **after reviewing** by maintainers. Now, you just need to wait for the review.

**Comment by DaivePan** [comment]
> Thanks for your contribution. Don't worry, your pull request #4633 has been successfully submitted, and it will be merged or rejected **after reviewing** by maintainers. Now, you just need to wait for the review.

Thanks

**Comment by jshier** [comment]
As explained, this isn't an open repo, so PRs must be reviewed.
