### ISSUE TITLE
Help! [AFNetworkReachabilityManager startMonitoring] crash~.

### ISSUE THREAD

**Issue by AaronZhao13** [AFNetworking/AFNetworking#4650]
#0 Thread
NSRangeException
*** -[NSConcreteMutableData appendBytes:length:]: range {125, 18446744073709551615} causes integer overflow

CoreFoundation | ___exceptionPreprocess + 216
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 Foundation | -[NSConcreteMutableData length]
3 6ios.dylib | -[SocketRequest sendAndRecv:] + 456
4 6ios.dylib | -[SocketRequest sendMsg:success:] + 188
5 6ios.dylib | -[VerifyEntry go] + 1416
6 6ios.dylib | __ZL10initializev_block_invoke_2 + 1300
7 6ios.dylib | __47-[AFNetworkReachabilityManager startMonitoring]_block_invoke + 196
8 6ios.dylib | __AFPostReachabilityStatusChange_block_invoke + 92
9 libdispatch.dylib | __dispatch_call_block_and_release + 24
10 libdispatch.dylib | __dispatch_client_callout + 16
11 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$armv81 + 856
12 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
13 CoreFoundation | ___CFRunLoopRun + 2480
14 CoreFoundation | CFRunLoopRunSpecific + 572
15 GraphicsServices | GSEventRunModal + 160
16 UIKitCore | -[UIApplication _run] + 1052
17 UIKitCore | UIApplicationMain + 164
18 MangoDating | main (main.m:18)
19 libdyld.dylib | _start + 4

**Comment by AaronZhao13** [comment]
Save the children please

**Comment by AaronZhao13** [comment]
iphoneX  ios14.0.1  4G and WiFi

**Comment by fengshuo1992** [comment]
How can I solve this problem now?

**Comment by AaronZhao13** [comment]
> How can I solve this problem now?

Has the app been re-signature? user 'method_exchange' solve it.

**Comment by freecodewu** [comment]
h
